"""
Isolation funnel chains — housing, communication, and movement restriction patterns
that progressively isolate workers from outside contact and assistance.

Sources: HRW field investigations (Al Khor camps 2012, NEOM 2024, Saudi domestic
workers 2008), EJF "Blood and Water" (2019), Verite Malaysia electronics (2014),
Amnesty International Qatar (2019), Tamkeen Jordan QIZ (2023), ILO C188 Work in
Fishing Convention, US DOL TVPRA List of Goods (2024).
"""

CHAINS: list[dict] = [
    {
        "id": "isolation_funnels_001",
        "name": "Gulf Domestic Worker Employer-Controlled Housing and Communication Isolation",
        "category": "isolation_funnels",
        "steps": [
            {
                "id": "if001_s1",
                "description": "Filipino domestic worker is provided live-in accommodation in the employer's household in Riyadh under the Saudi standard employment contract. HRW's 2008 report 'As If I Am Not Human' documented that employers in Riyadh and Jeddah routinely housed domestic workers in rooms with no separate entrance, often windowless storage rooms or partitioned hallways. The worker is expected to be available during all household waking hours — an average 17.5-hour workday according to ILO survey data on Gulf domestic workers. The Absher platform (Ministry of Interior digital services) ties the worker's iqama (residency permit) to the sponsor's address, formalizing the live-in requirement.",
                "legal_basis": "Saudi Ministerial Decree No. 166 (2000) criminalizes document retention by employers but enforcement depends on the worker filing a complaint through MOHRSS; the 2013 Household Regulation requires employers to provide 'suitable accommodation' but does not define minimum standards for room size, ventilation, or separate entrance; Musaned platform (domestic worker contract system) specifies live-in arrangement as default",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Live-in arrangement with no separate entrance means the worker cannot leave or receive visitors without passing through employer-controlled spaces; HRW documented cases where employers locked external doors at night in Riyadh compounds, treating the worker's room as part of the household's internal space rather than separate accommodation",
            },
            {
                "id": "if001_s2",
                "description": "Employer confiscates the worker's personal mobile phone upon arrival, stating that household policy prohibits personal devices 'to protect the family's privacy and security.' HRW's 'As If I Am Not Human' (Jul 2008) documented this practice across 86 interviews with domestic workers in Riyadh and Jeddah — phone confiscation occurred in over 50% of cases. The employer may provide a basic landline extension or a monitored device with no SIM card. Without a phone, the worker cannot access the Philippine Overseas Labor Office (POLO) Riyadh hotline, the Saudi MOHRSS complaint portal, or contact family in the Philippines.",
                "legal_basis": "No Saudi law explicitly guarantees domestic workers the right to personal phone ownership; the 2013 Household Regulation is silent on communication devices; Saudi Ministerial Decree No. 166 (2000) does not address employer control of personal property beyond identity documents",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Phone confiscation eliminates the worker's only independent communication channel with family, the Philippine embassy, POLO, and OWWA (Overseas Workers Welfare Administration); the Absher platform — which the worker would need for exit/re-entry permits — requires a registered Saudi mobile number, creating a digital access barrier layered on top of physical isolation",
            },
            {
                "id": "if001_s3",
                "description": "Worker is granted one day off per month instead of weekly, with the employer explaining that the household 'needs continuous coverage' and that days off will be accumulated and taken together during the worker's annual leave period. HRW's 2008 report documented an average of 1 day off per month among surveyed Saudi domestic workers, with many receiving no days off at all. On the monthly day off, the employer drives the worker to a shopping mall in Riyadh and picks them up at a designated time, typically allowing 2-3 hours.",
                "legal_basis": "Saudi Royal Decree No. M/51 (2009 Labor Law reform) Art. 104 grants domestic workers one day off per week, but enforcement mechanisms for in-home domestic workers are effectively non-existent; MOHRSS inspectors cannot enter private residences without a court order; accumulated leave is a common unregulated practice",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Employer-controlled day off timing and transport eliminates autonomous movement; worker cannot choose where to go, who to meet, or how long to stay; mall visit prevents contact with embassies, legal aid, or community organizations that operate on different schedules; accumulated leave promise is rarely honored per HRW interviews",
            },
            {
                "id": "if001_s4",
                "description": "Worker is not permitted to open the front door or compound gate independently. The employer installed a smart lock system requiring a PIN code known only to family members, or uses a physical key held solely by the employer. HRW documented employers in Riyadh compounds using electronic gate systems and deadbolts that lock from the outside. The employer explains this is a 'security feature for the compound.' The worker cannot admit visitors, accept deliveries, or exit the residence without a family member physically unlocking the door.",
                "legal_basis": "Residential security systems with coded access are standard in Saudi residential compounds; the Saudi Building Code permits homeowners to install access-controlled entry systems; employers control household access as property owners under Saudi Civil Code",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Physical barrier to exit combined with phone confiscation and transport dependency creates complete isolation; HRW described this as 'imprisonment in the employer's home' in cases where workers could not open any external door; worker cannot leave, call for help, or admit anyone — including Philippine embassy officers conducting welfare checks — without employer permission",
            },
        ],
        "chain_context": "Each measure is individually defensible — employer-provided housing, household privacy rules, security systems, scheduled days off — but together they create a sealed isolation environment. HRW's 2008 investigation across Riyadh and Jeddah documented the full pattern: confiscated phones (50%+ of cases), locked doors (multiple documented cases), 17.5-hour average workdays, and 1 day off per month. The worker has no independent communication, no autonomous movement, no ability to open the door, and no unsupervised contact with the outside world. ILO Indicator 4 (isolation) and Indicator 3 (restriction of movement) are both fully met through ostensibly normal household management practices.",
        "emergent_risk": "Total isolation through household management: confiscated phone + employer-controlled transport + smart lock confinement + restricted days off = worker cut off from all outside contact, including POLO hotline, OWWA, and the Absher platform needed for exit permits",
        "difficulty": "medium",
        "source_references": [
            "HRW, 'As If I Am Not Human: Abuses Against Asian Domestic Workers in Saudi Arabia' (Jul 2008) — phone confiscation, locked doors, restricted days off across 86 interviews in Riyadh/Jeddah",
            "ILO, 'Hard to See, Harder to Count: Survey Guidelines to Estimate Forced Labour of Adults and Children' (2012) — 17.5-hour average workday for Gulf domestic workers",
            "Polaris Project, 'Domestic Worker Trafficking Indicators' — communication control as primary isolation mechanism",
            "Anti-Slavery International, 'Kafala System and Domestic Worker Isolation' (2024) — Absher platform digital dependency",
        ],
        "corridors": ["PH-SA", "ET-SA", "ID-SA", "LK-SA"],
        "palermo_elements": {
            "act": ["harbouring"],
            "means": ["restriction of movement", "isolation", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "isolation_funnels_002",
        "name": "Remote Agricultural Worksite Employer-Controlled Transport Isolation",
        "category": "isolation_funnels",
        "steps": [
            {
                "id": "if002_s1",
                "description": "Guatemalan H-2A workers are transported from the US consulate processing in Monterrey directly to a large produce farm in a rural county in Georgia, a 14-hour drive in an employer-provided van. Workers arrive at night and are housed in on-farm trailers. Under 20 CFR 655.104(d), H-2A employers must provide free housing that meets federal standards (ETA-approved), but workers arrive disoriented with no orientation to surrounding geography, no map, and no information about the nearest town, legal aid office, or Department of Labor Wage and Hour Division field office.",
                "legal_basis": "H-2A regulations 20 CFR 655.104(d) require employers to provide transportation from the point of recruitment or hiring to the place of employment at no cost to the worker; 20 CFR 655.104(e) requires free housing meeting OSHA standards at 29 CFR 1910.142 or ETA standards; employers must post DOL workplace rights posters in Spanish per 29 CFR 655.135(l)",
                "sector": "agriculture",
                "corridor": "GT-US",
                "indicator_action_ids": [],
                "red_flag_context": "Direct transport to remote site prevents workers from orienting themselves; arrival at night ensures they cannot assess their surroundings; immediate geographic disorientation despite DOL requirement that employers provide workers with a copy of the job order describing worksite location",
            },
            {
                "id": "if002_s2",
                "description": "The farm is located 22 miles from the nearest town on an unpaved county road with no sidewalks, street lighting, or public transit. The employer provides a weekly van trip to a Walmart for personal shopping on Saturday afternoons, with a farm supervisor accompanying the group and a strict 90-minute time limit. Centro de los Derechos del Migrante documented this pattern across H-2A operations in Georgia, North Carolina, and Louisiana — employer-only transport combined with rural geography creating de facto geographic confinement.",
                "legal_basis": "H-2A employers in rural areas commonly provide weekly shopping transport as a practical accommodation; 20 CFR 655.104(d) covers recruitment-to-worksite transport only, not general mobility; there is no federal legal requirement for public transit access at agricultural worksites; DOL Field Assistance Bulletin 2023-2 clarified that employer-imposed restrictions on H-2A workers leaving housing may constitute restriction of movement",
                "sector": "agriculture",
                "corridor": "GT-US",
                "indicator_action_ids": [],
                "red_flag_context": "Geographic remoteness + employer-only transport creates total mobility dependency; supervised shopping trips prevent private conversations with anyone outside the farm; 90-minute limit prevents visiting legal aid, consulates, or DOL Wage and Hour Division offices, which have limited rural presence",
            },
            {
                "id": "if002_s3",
                "description": "Workers are told their H-2A visas are 'location-specific' and that leaving the farm property without authorization could constitute visa abandonment, resulting in deportation and a ban on future H-2A participation. The farm manager posts a sign in Spanish near the housing units stating 'Workers must not leave property without supervisor approval.' In reality, H-2A workers may freely leave employer premises on personal time — this is a deliberate misrepresentation of 8 CFR 214.2(h)(5)(viii)(B), which ties the visa to the employer, not the physical property.",
                "legal_basis": "H-2A visas under INA 101(a)(15)(H)(ii)(a) are employer-specific, not location-specific; workers are free persons who may leave the worksite during non-work hours; 18 USC 1589 (forced labor) and 18 USC 1592 (document servitude) make it a federal crime to knowingly restrict workers' movement through fraud or coercion; DOL has cited employers for restricting H-2A worker movement under 20 CFR 655.135(e)",
                "sector": "agriculture",
                "corridor": "GT-US",
                "indicator_action_ids": [],
                "red_flag_context": "False legal threat weaponizes visa status to enforce geographic confinement; workers without independent legal knowledge believe leaving the farm is illegal; signage institutionalizes the restriction; this practice has been cited in multiple DOL investigations and TVPRA trafficking prosecutions in the agricultural sector",
            },
            {
                "id": "if002_s4",
                "description": "The farm's cell phone reception is limited to one carrier with intermittent signal. The employer does not provide Wi-Fi in worker housing and tells workers that the farm's internet is 'for business operations only.' Workers who brought phones find they cannot reliably call the DOL Wage and Hour Division complaint line (1-866-487-9243), the National Human Trafficking Hotline (1-888-373-7888), or use messaging apps to contact family in Guatemala. Farmworker Justice has documented rural connectivity deserts as a structural barrier to H-2A worker rights enforcement.",
                "legal_basis": "Rural broadband gaps are a documented infrastructure issue affecting 21% of rural Americans (FCC 2023 Broadband Report); employers are not required under 20 CFR 655 to provide cellular or internet service to worker housing; however, active interference with workers' communication has been cited as evidence of forced labor under 18 USC 1589",
                "sector": "agriculture",
                "corridor": "GT-US",
                "indicator_action_ids": [],
                "red_flag_context": "Communication blackout in remote location completes isolation cycle; workers cannot research their rights online, contact the DOL WHD complaint line, reach the National Human Trafficking Hotline, or coordinate with organizations like Centro de los Derechos del Migrante or the Southern Poverty Law Center",
            },
        ],
        "chain_context": "Rural agricultural isolation exploits the legitimate remoteness of farming operations. Each element — employer transport per 20 CFR 655.104(d), rural location, visa-based movement restrictions, poor connectivity — is individually explained by agricultural realities. But the combination creates a situation where workers are geographically stranded 22+ miles from town, legally intimidated from leaving based on false visa claims, communication-impaired, and entirely dependent on the employer for all contact with the outside world. DOL Field Assistance Bulletin 2023-2 recognized employer restrictions on worker movement as a forced labor indicator.",
        "emergent_risk": "Geographic captivity through agricultural remoteness: isolated farm + employer-only transport + false visa threats violating 8 CFR 214.2(h) + communication blackout = workers trapped with no way to reach DOL, NHTH, or legal aid",
        "difficulty": "medium",
        "source_references": [
            "Centro de los Derechos del Migrante, 'Ripe for Reform: Abuses of Agricultural Workers in the H-2A Visa Program' (2020) — employer-controlled transport, false visa threats, geographic isolation patterns",
            "US DOL, 'List of Goods Produced by Child Labor or Forced Labor' (2024) — US agricultural products flagged for forced labor indicators",
            "Farmworker Justice, 'No Way to Treat a Guest: Why the H-2A Agricultural Visa Program Fails US and Foreign Workers' (2011) — rural connectivity barriers, movement restrictions",
            "DOL Field Assistance Bulletin 2023-2 — employer-imposed restrictions on H-2A worker movement as forced labor indicator",
        ],
        "corridors": ["GT-US", "MX-US", "HN-US", "JM-US"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["deception", "restriction of movement", "isolation", "intimidation"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "isolation_funnels_003",
        "name": "Distant Water Fishing Vessel Communication Blackout Isolation",
        "category": "isolation_funnels",
        "steps": [
            {
                "id": "if003_s1",
                "description": "Myanmar fisher signs onto a Thai-flagged distant water trawler at Songkhla port — one of the three main trafficking-linked ports documented by EJF alongside Ranong (Myanmar border corridor) and Samut Sakhon (Mahachai, major seafood processing hub). The contract describes '3-6 months' duration. The vessel departs and immediately heads to international waters in the Indian Ocean, operating 200+ nautical miles from any coastline. Thailand's PIPO (Port-in Port-out) inspection system, introduced under the Royal Ordinance on Managing Foreign Workers B.E. 2560 (2017), requires crew manifests at departure — but EJF documented that PIPO inspections at Songkhla averaged under 5 minutes per vessel in 2018, with inspectors unable to interview crew privately.",
                "legal_basis": "ILO C188 (Work in Fishing Convention, 2007) Art. 9 establishes a fisher's right to communication with persons ashore; Art. 14 requires sufficient rest periods; Art. 16 mandates written work agreements specifying voyage duration — Thailand ratified C188 in January 2019 but implementing regulations remain incomplete; Thailand's Ministerial Regulation 10 under the Labour Protection Act B.E. 2541 (1998) exempts fishing from standard working hour protections under s.23 (max 8 hours/day)",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Once the vessel leaves Songkhla, the fisher is physically unreachable by any authority, family member, or support organization; the contract's vague '3-6 months' violates ILO C188 Art. 16 requiring specified duration; PIPO inspections are too brief to detect coercion; Ministerial Regulation 10 exempts fishing from hour limits, enabling 18-20 hour shifts at sea",
            },
            {
                "id": "if003_s2",
                "description": "The vessel's satellite communication system (Inmarsat-C or mini-C terminal) is controlled exclusively by the captain for operational purposes — weather reports, navigation, and catch reporting to the vessel owner. EJF's 'Blood and Water' report (2019) documented that crew on Thai distant water vessels were told the system 'cannot handle personal calls' due to bandwidth, and that communication costs '$5 per minute which would exceed their wages.' ILO C188 Art. 9 explicitly states that fishers shall have the right to means of communication with persons ashore at 'reasonable cost,' but enforcement on vessels in international waters depends on flag state inspection.",
                "legal_basis": "ILO C188 Art. 9: 'Every fisher shall have the right to means of communication, and at reasonable cost, with persons ashore, including the right to seek advice'; Thailand's implementing regulations under C188 (Ministerial Regulation B.E. 2562/2019) include crew communication provisions but enforcement at sea is effectively impossible without observer programs; the Marine Department seabook register tracks fisher identities but not vessel communication access",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Captain-controlled satellite comms means crew have zero ability to contact anyone; $5/minute cost claim is fabricated to deter requests — Inmarsat-C text messages cost approximately $0.25-0.50 per message; EJF documented captains physically blocking crew from the bridge where communication equipment is located",
            },
            {
                "id": "if003_s3",
                "description": "During the voyage, at-sea transshipment occurs when a refrigerated cargo vessel ('reefer') meets the trawler at sea to transfer the catch. Fresh supplies and fuel are loaded, extending the trawler's operational range by another 2-3 months without returning to port. EJF's 'Blood and Water' (2019) documented voyages extending to 18-24 months through repeated transshipment, with crew consent never sought for extensions. The captain informs the crew the trip has been extended. Vessel-to-vessel crew transfer — moving fishers between boats at sea without port documentation — was documented by EJF as a method to evade PIPO port inspection entirely.",
                "legal_basis": "At-sea transshipment is regulated by Regional Fisheries Management Organizations (RFMOs) including IOTC and WCPFC; Thailand's Fisheries Act B.E. 2558 (2015) s.57 requires transshipment reporting but does not address crew communication or consent during resupply; ILO C188 Art. 16 requires written agreements specifying duration — unilateral extensions violate this provision",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Transshipment eliminates the one opportunity fishers had to reach port; EJF documented voyages of 18-24 months through repeated resupply; vessel-to-vessel crew transfer moves fishers between boats without any port authority seeing them, making them administratively invisible; crew consent for trip extension is never sought",
            },
            {
                "id": "if003_s4",
                "description": "When the vessel does approach port in a foreign country (e.g., Mauritius, Madagascar, or Maldives) for emergency repairs, crew are confined below deck. The captain tells the crew that immigration authorities will arrest and deport anyone who disembarks without valid documents, and that their seabooks and pink cards (tor ror 38/1 registration under the Royal Ordinance B.E. 2560) are 'with the vessel owner in Thailand.' HRW's 'Hidden Chains' (Jan 23, 2018) documented captains confiscating all identity documents at the start of voyages as standard practice on Thai distant water trawlers.",
                "legal_basis": "Port state immigration controls under UNCLOS Art. 94 require valid documentation for entry; vessel operators are responsible for crew management during port calls; ILO C188 Art. 19 requires that fishers 'have the opportunity to go ashore' when a vessel is in port, subject to operational needs — confinement below deck directly violates this provision; Thailand's Royal Ordinance B.E. 2560 (2017) created the pink card (tor ror 38/1) system but documents are frequently held by brokers or vessel owners",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Document confiscation combined with false legal threats ensures fishers cannot seek help even when physically near land; confinement below deck prevents port state inspectors from seeing or interviewing crew; HRW documented this pattern across multiple Thai-flagged vessels operating in the Indian Ocean",
            },
            {
                "id": "if003_s5",
                "description": "After 14 months at sea, crew members who express desire to end their contract are told their wages will only be paid upon return to Songkhla port, and that abandoning the vessel in a foreign port would forfeit all accumulated pay and result in criminal charges for desertion under the Thai Maritime Code. EJF documented fishers earning as little as THB 3,000-5,000/month ($85-140), with wages held for the entire voyage duration. The combination of 14 months' accumulated unpaid wages and the desertion threat creates an economic and legal cage that is impossible to escape at sea.",
                "legal_basis": "Thailand's Navigation in Thai Waters Act B.E. 2456 (1913) contains provisions on crew desertion; the Maritime Labour Convention (MLC) 2006 Reg. 2.2 requires monthly wage payment but applies to merchant seafarers, not fishers (who are covered by ILO C188); ILO C188 Art. 23 requires that fishers be paid at no greater than monthly intervals — 14-month wage withholding directly violates this provision",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Wage withholding for the entire voyage duration + desertion threats create an economic and legal cage; crew have worked 14 months unpaid at THB 3,000-5,000/month and cannot afford to forfeit everything; total isolation from any support system — no communication, no documents, no port access, no legal knowledge",
            },
        ],
        "chain_context": "Distant water fishing represents the most extreme isolation environment in modern labor exploitation. EJF's 'Blood and Water' (2019) documented the full system: vessels departing from Songkhla, Ranong, and Samut Sakhon ports with 5-minute PIPO inspections, captains controlling all satellite communication in violation of ILO C188 Art. 9, at-sea transshipment extending voyages to 18-24 months, vessel-to-vessel crew transfers evading port inspection, document confiscation, below-deck confinement in foreign ports, and wage withholding for the entire voyage in violation of C188 Art. 23. Thailand ratified C188 in 2019 but implementing regulations remain incomplete, and enforcement at sea is effectively impossible.",
        "emergent_risk": "Maritime captivity through operational isolation: months at sea from Songkhla/Ranong/Samut Sakhon + captain-controlled Inmarsat violating C188 Art. 9 + transshipment extensions to 18-24 months + crew transfers evading PIPO + below-deck port confinement + wage forfeiture threats = total physical and communicative isolation for 12-24 months",
        "difficulty": "hard",
        "source_references": [
            "EJF, 'Blood and Water: Human Rights Abuse in the Global Seafood Industry' (2019) — at-sea isolation, transshipment extensions to 18-24 months, vessel-to-vessel crew transfers, Songkhla/Ranong documentation",
            "HRW, 'Hidden Chains: Rights Abuses and Forced Labor in Thailand's Fishing Industry' (Jan 23, 2018) — document confiscation, captain communication control, below-deck confinement",
            "ILO C188 (Work in Fishing Convention, 2007) Art. 9 (communication), Art. 14 (rest), Art. 16 (written agreements), Art. 19 (shore access), Art. 23 (wage payment intervals)",
            "Thailand Royal Ordinance on Managing Foreign Workers B.E. 2560 (2017) — pink card (tor ror 38/1) system, PIPO port inspection framework",
            "US DOL, 'List of Goods Produced by Child Labor or Forced Labor' (2024) — Thai seafood products flagged for forced labor and child labor indicators",
        ],
        "corridors": ["MM-TH", "KH-TH", "ID-TH", "MM-TW"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["restriction of movement", "isolation", "retention of identity documents", "debt bondage"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "isolation_funnels_004",
        "name": "Factory Dormitory Compound Curfew and Surveillance System",
        "category": "isolation_funnels",
        "steps": [
            {
                "id": "if004_s1",
                "description": "Bangladeshi electronics assembly workers arrive at a factory in the Penang Free Trade Zone — known as the 'Silicon Island of the East' and a major concentration point for forced labor in electronics manufacturing per Verite's 2014 investigation. Workers are housed in a company-operated dormitory within the factory compound managed by an outsourcing company (a common arrangement documented by Verite where the outsourcing firm controls housing, payroll, and immigration documents). The dormitory accommodates 400 workers in shared rooms of 8-12 persons and is located inside the same fenced perimeter as the production facility. Workers are told the dormitory is provided as a benefit to avoid the high cost of private housing in Penang.",
                "legal_basis": "Malaysia Workers' Minimum Standards of Housing and Amenities Act 1990 (Act 446) specifies minimum dormitory space (3.6 sq meters per person), sanitation facilities (1 toilet per 15 persons), and cooking facilities for employer-provided accommodation; the Employment Act 1955 s.24 permits employers to provide housing as part of the employment arrangement; outsourcing companies operate under the Private Employment Agencies Act 1981",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Compound housing merges the workplace and living space into a single employer-controlled environment; Verite's 2014 report documented that outsourcing companies in Penang FTZ controlled workers' passports, payroll cards, and housing simultaneously, creating a single point of dependency; workers live inside the factory perimeter 24 hours a day",
            },
            {
                "id": "if004_s2",
                "description": "The compound operates a curfew system requiring all workers to be inside the dormitory by 10:00 PM and not leave before 6:00 AM. Verite's 'Forced Labor in the Production of Electronic Goods in Malaysia' (2014) documented curfews at Penang and Kulim Hi-Tech Park electronics factories, with outsourcing companies enforcing 10 PM curfews and requiring gate pass approval for any exit. The employer explains this is a 'security and welfare measure' to protect workers from crime in the surrounding industrial area and to ensure adequate rest before shift start.",
                "legal_basis": "Act 446 s.24A permits employers to establish 'reasonable rules' for employer-provided accommodation; there is no specific Malaysian statute defining permissible curfew hours; the Employment Act 1955 does not address off-duty movement restrictions; the Malaysian Human Rights Commission (SUHAKAM) has stated that curfews restricting freedom of movement may violate Article 9(2) of the Federal Constitution but has not issued a binding ruling",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Curfew eliminates evening social activity, religious practice (including Isha and Tarawih prayers for Muslim workers), and access to after-hours services; effectively confines workers to compound for 16+ hours on non-work days; Verite documented that workers who violated curfew at Penang FTZ dormitories received warnings that could lead to contract termination and deportation",
            },
            {
                "id": "if004_s3",
                "description": "Workers who wish to leave the compound during permitted hours must obtain a gate pass from the security office. The pass requires stating the destination, expected return time, and obtaining a supervisor signature. Passes are limited to two per week per worker. CCTV cameras are positioned at the gate, dormitory entrance, and along the compound perimeter fence. Verite's 2014 investigation documented this exact system at Penang electronics factories — gate passes approved 24 hours in advance by supervisors, CCTV at all exits, and outsourcing company staff monitoring entry/exit logs.",
                "legal_basis": "Gate pass systems are standard access control measures in Malaysian industrial compounds; the Private Employment Agencies Act 1981 permits outsourcing companies to establish housing rules; CCTV surveillance is lawful under the Personal Data Protection Act 2010 (PDPA) s.40 for security purposes; visitor management is required under the Occupational Safety and Health Act 1994 (OSHA) s.15",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Gate pass system creates a documented record of every exit; supervisor signature adds a discretionary barrier — supervisors can deny passes for any reason; two-per-week limit severely restricts freedom of movement; CCTV provides constant surveillance evidence; Verite documented that workers in Penang described feeling 'monitored at all times' and avoided leaving to prevent negative attention from outsourcing company managers",
            },
            {
                "id": "if004_s4",
                "description": "The compound has an on-site canteen, convenience shop, and mobile phone top-up service, all operated by the outsourcing company managing the dormitory. Prices are 25-40% higher than market rates at nearby Penang shops. Workers are told the shops are 'for their convenience' so they don't need to leave the compound. Salary is paid partly via outsourcing company payroll cards that can only be used at on-site POS terminals, with cash withdrawal requiring a trip to a bank ATM outside the compound — which requires a gate pass.",
                "legal_basis": "Employer-operated amenities in worker housing are permitted under Act 446; company stores are legal provided prices do not exceed 'reasonable' levels (undefined in statute); the Employment Act 1955 s.25 prohibits mandatory purchases from employer shops but does not address payroll card systems; partial in-kind payment arrangements must comply with s.31 of the Employment Act (not more than 50% of wages)",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "On-site monopoly shops at 25-40% markup reduce the economic incentive to leave and extract wages back into the outsourcing company's revenue; payroll card system restricts where money can be spent — accessing cash requires a gate pass, creating a circular dependency; US DOL's 2024 List of Goods flagged Malaysian electronics for forced labor indicators including these compound store systems",
            },
        ],
        "chain_context": "Factory dormitory compounds in Malaysia's Penang FTZ and Kulim Hi-Tech Park are a widespread housing model managed by outsourcing companies that control passports, payroll, and housing simultaneously. Verite's 2014 investigation documented the full pattern: compound housing inside the factory perimeter, 10 PM curfews, gate passes requiring 24-hour advance supervisor approval limited to two per week, CCTV at all exits, and captive-market company stores with 25-40% markups. Each element is individually defensible under Act 446 and the Employment Act 1955, but the combination creates a closed system where workers live, work, eat, shop, and communicate entirely within outsourcing-company-controlled space.",
        "emergent_risk": "Compound confinement through welfare framing: Penang FTZ factory dormitory + 10 PM curfew + gate pass rationing with supervisor approval + CCTV surveillance at all exits + monopoly company store with payroll card system = 24/7 outsourcing-company-controlled environment with no autonomous movement",
        "difficulty": "medium",
        "source_references": [
            "Verite, 'Forced Labor in the Production of Electronic Goods in Malaysia' (2014) — Penang FTZ dormitory curfews, gate passes, CCTV, outsourcing company control, passport confiscation",
            "US DOL, 'List of Goods Produced by Child Labor or Forced Labor' (2024) — Malaysian electronics flagged for forced labor indicators",
            "Malaysia Workers' Minimum Standards of Housing and Amenities Act 1990 (Act 446) — dormitory space (3.6 sqm/person), sanitation (1:15), reasonable rules provisions",
            "ILO, 'Hard to See, Harder to Count: Survey Guidelines to Estimate Forced Labour of Adults and Children' (2012) — compound isolation as forced labour indicator framework",
        ],
        "corridors": ["BD-MY", "NP-MY", "MM-MY", "ID-MY", "VN-MY"],
        "palermo_elements": {
            "act": ["harbouring"],
            "means": ["restriction of movement", "isolation", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "isolation_funnels_005",
        "name": "Desert Construction Labor Camp Geographic and Economic Isolation",
        "category": "isolation_funnels",
        "steps": [
            {
                "id": "if005_s1",
                "description": "Nepali and Indian construction workers are housed in a labor camp in the Al Khor industrial outskirts, approximately 50 kilometers from central Doha. HRW visited 6 labor camps in the Al Khor area for its June 2012 report 'Building a Better World Cup' and documented 'spartan conditions — string clotheslines, cardboard storage, 1 toilet per 10 men' in camps housing 2,000-4,000 workers. The camps are surrounded by undeveloped desert land in Qatar's Doha Industrial Area zone. The nearest commercial area with shops and services is 8 kilometers away along a highway with no pedestrian infrastructure, in summer temperatures exceeding 45°C.",
                "legal_basis": "Qatar Workers' Welfare Standards (WWS), adopted under the Supreme Committee for Delivery & Legacy, specify minimum accommodation requirements for labor camps including 4 sqm per worker, 1 toilet per 8 workers, and ventilated rooms — the Al Khor camps HRW visited fell below these standards; Qatar Labour Law No. 14/2004 Art. 106 sets maximum working hours at 48/week, reduced in summer; Ministerial Decision No. 17/2021 bans outdoor work 10:00 AM-3:30 PM June-September when WBGT (Wet Bulb Globe Temperature) exceeds 32.1°C",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Desert geography creates a natural isolation barrier; HRW's documentation of 6 Al Khor camps found 1 toilet per 10 men (below the WWS 1:8 standard), cardboard used for personal storage due to lack of furniture, and workers earning QAR 1,200/month (~$330); 8 km to services through 45°C+ summer heat with no sidewalks or shade makes walking dangerous to lethal",
            },
            {
                "id": "if005_s2",
                "description": "The employer — companies such as Al-Jaber Engineering or similar large contractors managing labor camps in Al Khor and the Lusail City construction zone — operates a bus service between the labor camp and the construction site, running at 5:30 AM and returning workers at 7:00 PM. No other transport is provided. Workers who want to travel to Doha or the commercial area must arrange private taxis costing QAR 50-80 ($14-22) each way — representing 10-15% of a typical weekly wage for workers earning QAR 1,200/month (~$330). Amnesty International's 'Reality Check' (2019) documented that workers at Al Khor camps had no affordable means to leave camp outside of work hours.",
                "legal_basis": "Qatar Labour Law No. 14/2004 Art. 26 requires employers to provide transport between accommodation and worksite; there is no legal requirement to provide general transportation services beyond the work commute; Qatar's Ehteraz app (COVID-era movement tracking, repurposed for general monitoring) and QID (Qatar ID) system require workers to carry identification at all times, but do not restrict geographic movement per se",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Employer transport serves only the work route (camp to Lusail City/Doha Industrial Area sites); taxi costs of QAR 50-80 each way consume 10-15% of a QAR 1,200/month wage for a single trip; effectively limits workers to two locations: Al Khor camp and construction site; Amnesty documented workers going months without leaving camp",
            },
            {
                "id": "if005_s3",
                "description": "The labor camp contains an employer-run shop selling basic goods, phone credit, and snacks at prices 25-40% above retail rates in Doha. HRW's 2012 Al Khor investigation documented camp canteens with 25-40% markup over market prices, with workers unable to comparison-shop due to geographic isolation. There is also a camp kitchen providing meals included in the employment package — deducted from wages at QAR 200-300/month. Workers earning QAR 1,200/month (~$330) are told they 'don't need to leave the camp for anything' because all essentials are available on-site.",
                "legal_basis": "Qatar Ministerial Decree No. 18/2014 on worker accommodation standards permits on-site amenities; company shops in remote industrial areas fill a legitimate service gap; meal deductions must be 'reasonable' per Labour Law No. 14/2004 Art. 70 but no specific cap is defined; MADLSA (Ministry of Administrative Development, Labour and Social Affairs) complaint portal accepts wage deduction complaints but processing takes months",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Monopoly pricing in a captive market extracts wages back to the employer; HRW documented 25-40% markups at Al Khor camp shops; meal deductions of QAR 200-300/month from a QAR 1,200 salary consume 17-25% of income before any other spending; 'no need to leave' framing normalizes immobility; workers who spend at the camp shop have even less money for QAR 50-80 taxi transport out",
            },
            {
                "id": "if005_s4",
                "description": "Workers' mail is delivered to the company's central HR office in Doha and distributed at the camp weekly. The employer explains that the Al Khor camp location does not have a postal address recognized by Qatar Post, so the company address must be used. Workers requesting to receive packages are told they will be 'checked for prohibited items' by camp security before distribution. Amnesty International documented that workers at Qatar construction camps had no direct postal access and that company-mediated mail distribution enabled monitoring of correspondence, including letters from the Nepal embassy and the Pravasi Nepali Coordination Committee.",
                "legal_basis": "Qatar Post operates primarily to commercial and residential addresses; remote industrial labor camps in the Al Khor/Doha Industrial Area zones often lack direct postal service; employer-mediated mail distribution is a practical necessity in these locations; security screening of packages entering compounds is permitted under internal safety policies",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Employer-mediated mail enables monitoring of correspondence; package 'security checks' allow confiscation of items like SIM cards, advocacy materials, or legal documents sent by the Nepal embassy or NGOs like Pravasi Nepali Coordination Committee; workers cannot receive communications without employer knowledge",
            },
            {
                "id": "if005_s5",
                "description": "The employer provides a designated 'recreation area' within the Al Khor camp with a cricket pitch, TV room showing employer-selected channels, and a weekly outdoor movie screening. Workers are encouraged to socialize within the camp. Visitors from outside must register at the main gate with QID (Qatar ID) and state their purpose of visit, and are limited to a 2-hour visit window on Fridays. HRW's 2012 investigation documented the visitor registration system at Al Khor camps as a barrier to NGO and journalist access — researchers needed pre-arranged company permission and were accompanied by management during visits to the 6 camps they eventually accessed.",
                "legal_basis": "Qatar WWS (Workers' Welfare Standards) recommend recreational facilities in labor camps; visitor management is a standard security requirement for large residential compounds under Qatar's internal security regulations; registration is standard in Doha Industrial Area zones; the NHRC (National Human Rights Committee) has the authority to conduct unannounced camp inspections but in practice coordinates visits through employers",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Recreation provision reduces pressure for outside movement; QID-based visitor registration deters NGOs, journalists, and embassy staff from informal visits; Friday-only 2-hour window prevents meaningful outside contact; HRW noted that management accompaniment during their own camp visits prevented private conversations with workers",
            },
        ],
        "chain_context": "Qatar's labor camp system creates geographic isolation through legitimate urban planning (industrial zoning in Al Khor, 50 km from Doha), sustained by economic isolation (QAR 50-80 taxi costs consuming 10-15% of QAR 1,200/month wages, monopoly camp shops with 25-40% markup per HRW), informational isolation (employer-mediated mail), and social isolation (QID-based visitor registration, 2-hour Friday windows). HRW visited 6 Al Khor camps documenting 'spartan conditions, string clotheslines, cardboard storage, 1 toilet per 10 men.' Ministerial Decision No. 17/2021 bans outdoor work when WBGT exceeds 32.1°C, but camp-to-commercial-area walking in the same heat remains the only free transport option.",
        "emergent_risk": "Desert compound isolation: Al Khor camp 50km from Doha + no public transport (QAR 50-80 taxi = 10-15% weekly wage) + 25-40% markup monopoly economy + mediated mail + QID-based visitor registration = self-contained employer world for workers earning QAR 1,200/month",
        "difficulty": "hard",
        "source_references": [
            "HRW, 'Building a Better World Cup: Protecting Migrant Workers in Qatar Ahead of FIFA 2022' (Jun 12, 2012) — visited 6 Al Khor camps, documented spartan conditions, 1 toilet per 10 men, string clotheslines, cardboard storage, 25-40% camp shop markups",
            "Amnesty International, 'Reality Check: Migrant Workers' Rights with Four Years to Qatar 2022 World Cup' (2019) — Al Khor transport isolation, months without leaving camp, employer-mediated mail",
            "Qatar Ministerial Decision No. 17/2021 — outdoor work ban when WBGT exceeds 32.1°C, 10:00 AM-3:30 PM June-September",
            "Qatar Labour Law No. 14/2004 Art. 106 (working hours), Art. 26 (employer transport obligation), Art. 70 (wage deduction limits)",
            "ILO, 'Hard to See, Harder to Count: Survey Guidelines to Estimate Forced Labour of Adults and Children' (2012) — isolation and restriction of movement indicator methodology",
        ],
        "corridors": ["NP-QA", "IN-QA", "BD-QA", "PH-QA", "PK-QA"],
        "palermo_elements": {
            "act": ["harbouring"],
            "means": ["restriction of movement", "isolation", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "isolation_funnels_006",
        "name": "Live-in Domestic Worker SIM Card Confiscation and Communication Monitoring",
        "category": "isolation_funnels",
        "steps": [
            {
                "id": "if006_s1",
                "description": "An Indonesian domestic worker arrives in Kuwait City under a two-year Kafala-sponsored contract. The employer family confiscates the worker's Indonesian SIM card on the first day, explaining that 'international SIM cards don't work properly in Kuwait' and that they will purchase a local Kuwaiti SIM 'once the residence permit is processed.' HRW's 'As If I Am Not Human' (Jul 2008) documented identical practices across the Gulf — SIM confiscation at arrival as a standard employer action affecting the majority of domestic workers interviewed in Saudi Arabia and Kuwait. The Indonesian SIM contains pre-loaded contacts: family numbers, the Indonesian embassy in Kuwait hotline, KBRI (Kedutaan Besar Republik Indonesia) emergency number, and the recruitment agency's WhatsApp contact.",
                "legal_basis": "Indonesian SIM cards function on roaming in Kuwait via agreements between Telkomsel/Indosat and Zain/Ooredoo Kuwait, but at elevated cost; Kuwait's Domestic Workers Law No. 68/2015 Art. 3 guarantees domestic workers the right to 'use means of communication' but contains no enforcement mechanism or penalty for violation; the law lacks implementing regulations as of 2024",
                "sector": "domestic_work",
                "corridor": "ID-KW",
                "indicator_action_ids": [],
                "red_flag_context": "Confiscating the Indonesian SIM removes the worker's pre-loaded contacts — family numbers, KBRI emergency line, recruitment agency WhatsApp; Kuwait's Domestic Workers Law No. 68/2015 nominally protects communication rights but has no enforcement mechanism; the promised Kuwaiti SIM is typically delayed weeks or never provided",
            },
            {
                "id": "if006_s2",
                "description": "After three weeks, the employer provides the worker with a Kuwaiti SIM card registered under the employer's civil ID number through Zain Kuwait or Ooredoo Kuwait. Kuwait's Telecommunications Regulatory Authority (CITRA) requires SIM registration with a valid civil ID, and since the worker's residence permit (iqama) is still processing, the employer's ID is used. The SIM is on a prepaid plan with KWD 2 ($6.50) credit that the employer controls — enough for approximately 30 minutes of local calls per month. The worker cannot purchase additional credit without the employer's civil ID authentication.",
                "legal_basis": "Kuwait CITRA Regulation 2016 requires SIM registration with a valid civil ID; using the sponsor's ID for domestic worker SIM registration is a common practice documented by Migrant Rights; Kuwait Domestic Workers Law No. 68/2015 Art. 3 guarantees communication access but does not specify minimum credit, employer registration restrictions, or independent SIM access",
                "sector": "domestic_work",
                "corridor": "ID-KW",
                "indicator_action_ids": [],
                "red_flag_context": "Employer-registered SIM means employer can view call records through the telecom provider's account portal, deactivate the SIM at any time, and control credit balance; KWD 2 credit provides approximately 30 minutes — insufficient for a call to Indonesia (approximately KWD 0.15/minute = 13 minutes maximum to Indonesian mobile); worker's communication is entirely at the employer's discretion",
            },
            {
                "id": "if006_s3",
                "description": "The employer establishes a household rule that the worker may make phone calls only between 9:00 PM and 10:00 PM after all household duties are complete, and only from the worker's room. ILO survey data on Gulf domestic workers documented an average 17.5-hour workday, meaning the 9-10 PM window falls at the end of exhaustion. The employer states this is to 'ensure privacy for both the worker and the family' and to prevent calls during work hours. Video calls are prohibited because 'the family does not want their home shown on camera.' The 3-hour time difference with Indonesia (WIB) means the call window is midnight-1 AM in Jakarta — when family members are typically asleep.",
                "legal_basis": "Household phone usage rules are within the employer's domestic management authority under Kuwait's Domestic Workers Law No. 68/2015, which does not define 'reasonable' communication access; privacy concerns about video calls in private residences are recognized under Kuwait's privacy provisions; no minimum call time or frequency is specified in any Gulf domestic worker regulation",
                "sector": "domestic_work",
                "corridor": "ID-KW",
                "indicator_action_ids": [],
                "red_flag_context": "One-hour window after a 17.5-hour average workday severely limits communication; by 9 PM Kuwait time, it is midnight in Jakarta (WIB) and family is typically asleep; no video calls prevents worker from showing living conditions to family or KBRI; worker exhaustion after full workday limits cognitive ability to use the hour for anything beyond brief personal calls",
            },
            {
                "id": "if006_s4",
                "description": "The employer periodically checks the worker's phone, reviewing call logs and WhatsApp messages. The employer tells the worker this is necessary because 'some domestic workers use phones to coordinate running away' and that the employer is 'responsible for your safety under the Kafala system.' The employer deletes contacts for the Kuwait Society for Human Rights hotline, the Indonesian embassy (KBRI Kuwait) number, and the number of a fellow Indonesian domestic worker met at the mosque during the one permitted Friday outing. HRW's 2008 report documented employers across the Gulf describing phone monitoring as a 'security' measure to prevent domestic workers from 'absconding.'",
                "legal_basis": "Kuwait's Kafala system places legal responsibility on sponsors for their sponsored workers' compliance with immigration law; phone monitoring of employer-provided or employer-registered devices occupies a legal gray area under Kuwait's Cybercrime Law No. 63/2015 (which addresses unauthorized access but does not clearly protect employer-registered devices used by workers); deleting contacts is not specifically prohibited",
                "sector": "domestic_work",
                "corridor": "ID-KW",
                "indicator_action_ids": [],
                "red_flag_context": "Active communication surveillance and deletion of support contacts eliminates the worker's knowledge of available help — KBRI Kuwait, Kuwait Society for Human Rights, and peer domestic worker networks; 'running away' framing criminalizes the idea of leaving; HRW documented employers across the Gulf using this exact language to justify total communication control; monitoring deters any contact that might help the worker seek assistance",
            },
        ],
        "chain_context": "Communication control in Gulf domestic work exploits the intimacy of the live-in arrangement and the Kafala sponsor's legal authority. Kuwait's Domestic Workers Law No. 68/2015 Art. 3 nominally guarantees communication rights but contains no enforcement mechanism, penalties, or implementing regulations. SIM confiscation at arrival (documented by HRW across the Gulf), employer-registered replacement on a KWD 2 prepaid plan, time-restricted calling during the midnight hour in Indonesia, and active phone monitoring with deletion of KBRI and human rights contacts — each is individually defensible as household management. Together they create a communication environment where every call, message, and contact is visible to and controlled by the employer.",
        "emergent_risk": "Communication captivity through device control: Indonesian SIM confiscation at arrival + employer-registered Kuwaiti SIM with KWD 2 credit + 9-10 PM call window (midnight Jakarta time) + phone monitoring with deletion of KBRI/human rights contacts = worker cannot privately communicate with anyone",
        "difficulty": "hard",
        "source_references": [
            "HRW, 'As If I Am Not Human: Abuses Against Asian Domestic Workers in Saudi Arabia' (Jul 2008) — SIM confiscation, phone monitoring, 'absconding' framing across 86 interviews in Gulf states",
            "ILO, 'Hard to See, Harder to Count: Survey Guidelines to Estimate Forced Labour of Adults and Children' (2012) — 17.5-hour average workday for Gulf domestic workers, communication restriction as forced labour indicator",
            "Kuwait Domestic Workers Law No. 68/2015 Art. 3 — nominal communication rights guarantee with no enforcement mechanism or implementing regulations",
            "Migrant Rights, 'Kuwait Domestic Worker Conditions: Communication and Movement Restrictions' (2024) — employer SIM registration, credit control, call time restrictions",
        ],
        "corridors": ["ID-KW", "PH-KW", "ET-KW", "LK-KW"],
        "palermo_elements": {
            "act": ["harbouring"],
            "means": ["isolation", "intimidation", "surveillance", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "isolation_funnels_007",
        "name": "Thai Shrimp Processing Remote Facility Language Barrier Isolation",
        "category": "isolation_funnels",
        "steps": [
            {
                "id": "if007_s1",
                "description": "Myanmar migrants from Rakhine State are recruited through a Thai-Myanmar broker network for work at a shrimp peeling shed in Samut Sakhon province — Thailand's largest seafood processing hub, known locally as Mahachai, where HRW's 'Hidden Chains' (Jan 23, 2018) documented Myanmar and Cambodian workers in 'inhumane conditions and indentured servitude.' The facility is located in a semi-rural area within a cluster of similar processing facilities, surrounded by aquaculture ponds and accessible only by a single road from the main highway. Workers are housed in tin-roofed barracks adjacent to the peeling shed, in conditions EJF described as 'cramped, unsanitary, and with no separation between work and living space.'",
                "legal_basis": "Thailand Labour Protection Act B.E. 2541 (1998) s.23 sets maximum working hours at 8 hours/day and 48 hours/week, but Ministerial Regulation 10 exempts the fishing and seafood processing sectors from standard hour protections; the Royal Ordinance on Managing Foreign Workers B.E. 2560 (2017) established the pink card (tor ror 38/1) registration system for migrant workers — workers without pink cards are undocumented and subject to arrest and deportation",
                "sector": "food_processing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Samut Sakhon/Mahachai is a documented trafficking concentration point — HRW's 'Hidden Chains' and EJF's 'Blood and Water' both identified it as a major hub for exploitation of Myanmar and Cambodian workers; semi-rural location among aquaculture ponds with single-road access makes departure visible to management; tin-roofed barracks adjacent to the shed merge living and working space under constant employer proximity",
            },
            {
                "id": "if007_s2",
                "description": "The majority of the workers are Rohingya from Myanmar's Rakhine State who speak Rohingya language and limited Burmese. They do not speak, read, or write Thai. All signage at the facility, nearby shops, and roads is in Thai script only. The nearest Myanmar-speaking community is in central Mahachai (Samut Sakhon town), approximately 15 kilometers away — where NGOs including the Migrant Working Group and LPN (Labour Rights Promotion Network) Foundation operate. The facility manager does not provide information about Mahachai's Myanmar community, LPN Foundation, or the MWRN (Migrant Worker Rights Network) hotline.",
                "legal_basis": "Thailand has no legal requirement for employers to provide multilingual signage, translation services, or information about worker support organizations; the Labour Protection Act B.E. 2541 requires employment contracts in Thai — workers who cannot read Thai sign contracts they cannot understand; the National Human Rights Commission of Thailand (NHRC) recommended bilingual signage in 2017 but this remains non-binding",
                "sector": "food_processing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Linguistic isolation compounds physical isolation; Rohingya workers cannot read signs, ask directions, understand Thai-language media, or communicate with Thai officials; even if they reached Samut Sakhon town, they could not navigate to LPN Foundation or MWRN without Thai language ability; employment contracts in Thai are signed without comprehension",
            },
            {
                "id": "if007_s3",
                "description": "Workers' immigration status is irregular — many entered through informal border crossings via Ranong province (the documented Myanmar-Thailand trafficking corridor per EJF) and work under a Thai broker's arrangement without pink card (tor ror 38/1) registration. The facility manager reminds workers periodically that Thai police conduct immigration raids in the Samut Sakhon area (which is true — the Royal Thai Police conducted multiple raids in Samut Sakhon's seafood processing zone in 2017-2018) and that workers without proper documents 'will be arrested and deported to Myanmar, where Rohingya face persecution.' The manager offers to 'protect' them from police attention as long as they remain at the facility.",
                "legal_basis": "Thai Immigration Act B.E. 2522 (1979) s.12, s.54 criminalizes unauthorized entry and overstay with penalties including detention and deportation; the Royal Ordinance B.E. 2560 (2017) s.101-102 penalizes employers of undocumented workers with fines of THB 400,000-800,000 per worker, but also penalizes the workers themselves; Rohingya are not recognized as refugees by Thailand (which has not ratified the 1951 Refugee Convention), making deportation a genuine existential threat",
                "sector": "food_processing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Immigration vulnerability weaponized to enforce location-based compliance; Rohingya face genuine persecution and statelessness in Myanmar, making deportation an existential threat unlike for most economic migrants; 'protection' framing creates dependency on the exploiter; Ranong-to-Samut Sakhon is a well-documented trafficking pipeline for Rohingya per EJF and Fortify Rights",
            },
            {
                "id": "if007_s4",
                "description": "Workers are paid in cash at irregular intervals by the Thai broker, not the facility owner — a subcontracting arrangement that obscures the employer-employee relationship. Payment amounts vary and fall below the Thai minimum wage of THB 328-354/day (2024 rates, depending on province), but the broker explains that deductions are made for 'accommodation, food, and protection fees.' Workers who ask about the deductions are told the calculations are 'in Thai documents that you wouldn't understand anyway.' HRW's 'Hidden Chains' documented Samut Sakhon brokers withholding 30-50% of wages through opaque deduction systems that workers could not verify due to language barriers.",
                "legal_basis": "The Labour Protection Act B.E. 2541 (1998) s.76 requires wages to be paid at least monthly and in Thai baht; s.77 limits deductions to income tax, union dues, savings schemes, and advance repayment — 'accommodation, food, and protection fees' exceed lawful deductions; minimum wage under the Minimum Wage Committee (Notification B.E. 2567/2024) is THB 328-354/day depending on province; brokered labor arrangements are regulated under the Employment and Job Seekers Protection Act B.E. 2528 (1985)",
                "sector": "food_processing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Language barrier prevents workers from verifying wage calculations, understanding deductions, or reading Thai-language pay records; HRW documented 30-50% wage withholding through opaque deductions at Samut Sakhon facilities; 'protection fees' are extortion labeled as a service — paying the broker for not reporting the worker to police; Thai-language documents are used as a weapon of opacity against Rohingya-speaking workers",
            },
        ],
        "chain_context": "Thailand's Samut Sakhon/Mahachai seafood processing industry relies heavily on Myanmar migrant labor, particularly vulnerable Rohingya workers entering via the Ranong corridor. HRW's 'Hidden Chains' (Jan 2018) and EJF's 'Blood and Water' (2019) documented the overlapping isolation layers: geographic remoteness of aquaculture-area processing facilities with single-road access, total linguistic exclusion of Rohingya speakers from Thai-language society and Thai-script signage, weaponized immigration vulnerability under the Immigration Act B.E. 2522, and financial opacity through broker-controlled cash payments with 30-50% opaque deductions. Each factor is individually attributable to structural conditions — industry location, language diversity, immigration policy — but the combination traps workers 15 km from the nearest Myanmar-speaking community and support organizations like LPN Foundation.",
        "emergent_risk": "Multi-dimensional isolation at Samut Sakhon: remote aquaculture-zone facility + total Rohingya-Thai language barrier + undocumented status under Immigration Act B.E. 2522 (deportation = persecution) + broker-controlled cash with 30-50% opaque deductions = workers trapped by geography, language, legal status, and financial opacity",
        "difficulty": "expert",
        "source_references": [
            "HRW, 'Hidden Chains: Rights Abuses and Forced Labor in Thailand's Fishing Industry' (Jan 23, 2018) — Samut Sakhon conditions, broker wage withholding (30-50%), inhumane conditions, indentured servitude documentation",
            "EJF, 'Blood and Water: Human Rights Abuse in the Global Seafood Industry' (2019) — Ranong-Samut Sakhon trafficking corridor, cramped barracks, seafood processing exploitation",
            "Thailand Labour Protection Act B.E. 2541 (1998) s.23 (working hours), s.76 (wage payment frequency), s.77 (lawful deductions); Ministerial Regulation 10 (fishing/seafood processing hour exemption)",
            "Thailand Royal Ordinance on Managing Foreign Workers B.E. 2560 (2017) — pink card (tor ror 38/1) system, penalties for undocumented workers and their employers",
            "US DOL, 'List of Goods Produced by Child Labor or Forced Labor' (2024) — Thai shrimp and seafood products flagged for forced labor and child labor indicators",
        ],
        "corridors": ["MM-TH", "KH-TH", "LA-TH"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["isolation", "abuse of position of vulnerability", "deception", "intimidation"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "isolation_funnels_008",
        "name": "Free Trade Zone Compound Perimeter Security Marketed as Worker Safety",
        "category": "isolation_funnels",
        "steps": [
            {
                "id": "if008_s1",
                "description": "Sri Lankan garment workers arrive at a Qualifying Industrial Zone (QIZ) factory in Al Hassan Industrial Zone, northern Jordan — one of two major QIZs alongside Ad-Dulayl. Tamkeen Fields for Aid documented over 100 Bangladeshi and Indian workers at Al Hassan facilities subjected to passport confiscation for 4 months or more. Ad-Dulayl QIZ alone employs approximately 70,000 workers (2022 Jordan Ministry of Labour data), of whom 75% are female, primarily from Sri Lanka, Vietnam, Bangladesh, China, Pakistan, and Nepal. Workers are housed in a dormitory complex within the factory's walled compound — a 3-meter concrete wall topped with barbed wire, with a single vehicle gate and a pedestrian turnstile entry, both staffed by private security guards 24/7. Management explains the wall and security are 'for worker protection against outside criminal elements' and to 'maintain the secure zone status required by the QIZ designation.'",
                "legal_basis": "Jordan QIZ Agreement (1997, updated 2010) with the United States requires enhanced security for preferential trade access; Jordan Labour Law No. 8/1996 Art. 29 explicitly prohibits 'restriction of movement' as a prohibited employer practice; the Jordan-US QIZ protocol does not require perimeter security that restricts worker movement — the security requirement applies to merchandise, not people; Tamkeen documented that passport confiscation at Al Hassan violates Jordanian Passport Law No. 5/2003",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Security infrastructure designed for merchandise protection is repurposed to control worker movement; walls and barbed wire keep people in as effectively as they keep threats out; single-point access creates a monitored chokepoint; Tamkeen documented 100+ workers at Al Hassan with passports confiscated for 4+ months; 75% female workforce at Ad-Dulayl faces additional gender-based restrictions on movement and socializing",
            },
            {
                "id": "if008_s2",
                "description": "Workers must surrender their factory-issued ID badge to the gate guard when exiting and collect it upon return. Exit and entry times are logged electronically. Workers who return after the 9:30 PM curfew are written up, and three write-ups result in 'disciplinary review' that can include termination — which under Jordanian labour law triggers cancellation of the work permit under the Regulation on Conditions for Recruitment and Employment of Non-Jordanian Workers (2012), giving the worker 30 days to leave the country or face deportation. The three-step escalation (late return → write-up → termination → deportation) creates a disciplinary cascade where a single curfew violation begins a chain leading to loss of immigration status.",
                "legal_basis": "Jordan Labour Law No. 8/1996 Art. 17 permits employers to establish workplace regulations including access control; Art. 28 lists valid grounds for termination; Art. 29 prohibits employer practices that restrict freedom of movement — curfew enforcement linked to termination is arguably a violation of Art. 29; the Regulation on Conditions for Recruitment and Employment of Non-Jordanian Workers (2012) ties work permits to specific employers, meaning termination automatically triggers permit cancellation",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Electronic logging creates surveillance record of every movement; curfew violation linked to termination linked to deportation creates a three-step escalation from being late to losing immigration status — directly contravening Jordan Labour Law Art. 29's prohibition on restriction of movement; chilling effect deters workers from leaving the compound at all; 75% female workforce faces additional informal curfew pressure",
            },
            {
                "id": "if008_s3",
                "description": "The Al Hassan compound includes a prayer room, medical clinic, recreation room with TV, small supermarket, and mobile phone charging station. A company bus runs to the nearest city — Irbid, 12 km away — once per week on Friday mornings, with a sign-up sheet limited to 30 seats for a compound housing several hundred workers. Workers who want to visit Irbid at other times must arrange private taxis at JOD 5-7 ($7-10) each way — roughly 10% of weekly wages for workers earning JOD 190-220/month (2022 Jordan minimum wage for garment sector). Tamkeen's 2023 report documented that the majority of QIZ garment workers had never visited Irbid during their 2-year contract period due to transport barriers.",
                "legal_basis": "Jordan Labour Law No. 8/1996 Art. 52 requires employers to provide adequate facilities; on-site amenities exceed minimum requirements; weekly transport to Irbid is a voluntary employer benefit; Jordan's 2022 minimum wage for garment workers was set at JOD 190/month for non-Jordanians, increased to JOD 220/month by Ministerial Decision 2023; private transport costs are the worker's personal expense",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Self-contained compound reduces incentive and ability to leave; 30-seat weekly bus for hundreds of workers means most never leave; JOD 5-7 taxi cost consumes 10% of JOD 190-220/month minimum wage for a single round trip; Tamkeen documented workers completing entire 2-year contracts without visiting the nearest city; on-site amenities serve as justification for why leaving 'isn't necessary'",
            },
            {
                "id": "if008_s4",
                "description": "Visitors must present a Jordanian national ID or passport at the Al Hassan main gate, register their purpose of visit, and be escorted by security to a designated visitor area. NGO workers from organizations like Tamkeen Fields for Aid and labor inspectors from the Ministry of Labour are told they must 'coordinate visits through the company's Amman office at least 48 hours in advance.' Unannounced visitors, including workers' friends from other QIZ factories and representatives from the Sri Lankan embassy in Amman, are turned away for 'security protocol violations.' Tamkeen documented that this 48-hour notice requirement gave management time to brief workers, remove evidence of overtime violations, and prepare 'model' dormitory rooms for inspection.",
                "legal_basis": "Jordan Labour Law Art. 31 grants Ministry of Labour inspectors the right to enter any workplace without prior notice; QIZ industrial zone security protocols are established by zone management companies, not by law; the 48-hour advance notice requirement for inspectors directly violates Art. 31's unannounced inspection right; visitor management for private citizens is the property owner's prerogative but cannot obstruct official inspections",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Visitor registration deters informal visits from Tamkeen and other advocacy organizations; 48-hour advance notice for NGOs/inspectors violates Labour Law Art. 31 and gives management time to prepare — Tamkeen documented evidence of pre-inspection 'cleaning' at Al Hassan; turning away workers' friends from other QIZ factories prevents information sharing about comparative conditions and rights; blocking Sri Lankan embassy officers prevents consular welfare checks",
            },
            {
                "id": "if008_s5",
                "description": "Workers sign a 'compound rules agreement' in English (which most Sri Lankan workers can read due to English-medium secondary education in Sri Lanka) that states: 'For the safety and security of all residents, workers agree to comply with compound access protocols and understand that unauthorized departure from the compound during restricted hours may be treated as abandonment of employment.' The agreement is presented as part of the onboarding package alongside the legitimate employment contract, residency permit application, and medical insurance forms. Tamkeen documented that workers at Al Hassan and Ad-Dulayl signed compound rules agreements without understanding that 'abandonment of employment' triggers work permit cancellation and a 30-day departure order.",
                "legal_basis": "Jordan Labour Law No. 8/1996 Art. 29 explicitly prohibits restriction of freedom of movement as an unlawful employer practice; Art. 25 invalidates any contractual term that waives a right granted under the labour law — a 'compound rules agreement' restricting movement is arguably void under Art. 25; however, Jordan's labour courts have not issued a definitive ruling on whether compound curfew agreements violate Art. 29",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Contractualizing movement restrictions gives them perceived legal weight despite potential voidness under Art. 25; 'unauthorized departure = abandonment' means leaving the compound outside permitted times risks employment (Art. 28 termination), which risks the work permit (Regulation 2012), which triggers a 30-day departure order; Tamkeen documented workers signing without understanding this deportation cascade; the agreement is buried among legitimate onboarding documents",
            },
        ],
        "chain_context": "Jordan's QIZ factories at Al Hassan and Ad-Dulayl serve major international brands under US-Jordan free trade preferences, employing approximately 70,000 workers (75% female, predominantly from LK/VN/BD/CN/PK/NP). Tamkeen Fields for Aid's 2023 investigation documented the full isolation system: 3-meter walls with barbed wire, passport confiscation for 4+ months, electronic badge logging, 9:30 PM curfew linked through three disciplinary steps to deportation, 30-seat weekly bus for hundreds of workers (most never reaching Irbid during 2-year contracts), 48-hour NGO visit pre-notification violating Labour Law Art. 31, and compound rules agreements arguably void under Art. 25 but signed without comprehension of the deportation cascade. Jordan Labour Law Art. 29 explicitly prohibits restriction of movement, but enforcement within QIZ compounds remains weak.",
        "emergent_risk": "Industrial security repurposed as worker containment: Al Hassan/Ad-Dulayl QIZ walled compound + electronic badge surveillance + curfew→termination→deportation cascade + 30-seat bus for hundreds (Tamkeen: workers never leave in 2 years) + 48-hour visit notice violating Art. 31 + compound rules agreement (arguable Art. 25 void) = free trade zone as isolation chamber for 70,000 workers",
        "difficulty": "expert",
        "source_references": [
            "Tamkeen Fields for Aid, 'Working Conditions in Jordanian Industrial Zones' (2023) — Al Hassan passport confiscation (100+ workers, 4+ months), 48-hour visit notice, workers never reaching Irbid, compound rules agreements, pre-inspection preparation",
            "Jordan Labour Law No. 8/1996 Art. 29 (prohibition on restriction of movement), Art. 25 (void contractual waivers of rights), Art. 31 (unannounced inspection right), Art. 52 (adequate facilities)",
            "Jordan Ministry of Labour, 'QIZ Employment Statistics' (2022) — Ad-Dulayl 70,000 workers, 75% female, LK/VN/BD/CN/PK/NP workforce composition",
            "ILO Better Work Jordan, 'Annual Compliance Assessment Report' (2023) — QIZ dormitory conditions, curfew enforcement, freedom of movement findings",
            "US DOL, 'List of Goods Produced by Child Labor or Forced Labor' (2024) — Jordanian garments flagged for forced labor indicators in QIZ production",
        ],
        "corridors": ["LK-JO", "BD-JO", "IN-JO", "PH-JO", "MM-JO"],
        "palermo_elements": {
            "act": ["harbouring"],
            "means": ["restriction of movement", "isolation", "coercion", "intimidation"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
]
