"""
Sector-specific chains — exploitation patterns unique to particular industries
including fishing, domestic work, construction, agriculture, and education.

Sources: Migrasia sector analysis, Liberty Shared fishing research,
ILO sectoral studies, Issara Institute sector-specific worker voice data.
"""

CHAINS: list[dict] = [
    {
        "id": "sector_specific_001",
        "name": "Thai Fishing Industry Broker-to-Vessel Exploitation Pipeline",
        "category": "sector_specific",
        "steps": [
            {
                "id": "ss001_s1",
                "description": "A broker operating near the Myanmar-Thailand border recruits Burmese men from rural villages by offering well-paid fishing jobs in Thailand. The broker arranges border crossing and transport to Samut Sakhon province, charging a 'placement service fee' of 15,000 THB (~$430) deducted from future wages.",
                "legal_basis": "Labor brokers facilitating cross-border employment is a recognized intermediary function; placement fees with salary deduction agreements are documented in written contracts between the parties",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Broker controls the entire migration journey; workers arrive in Thailand already indebted, with no direct relationship to the eventual vessel owner and no ability to verify the job terms independently",
            },
            {
                "id": "ss001_s2",
                "description": "The vessel owner applies for a seabook (Seaman's Book) for the worker through the Port-in Port-out (PIPO) control center, which requires submission of the worker's passport and migrant worker card. The vessel owner retains all three documents as the 'registered custodian' for PIPO compliance.",
                "legal_basis": "Thailand's 2015 Royal Ordinance on Fisheries requires PIPO registration with valid crew documentation; vessel operators are the responsible party for presenting crew documents at port inspections under the Command Centre for Combating Illegal Fishing (CCCIF) framework",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Fake or fraudulently obtained seabooks are common; vessel owner now holds passport, pink card, and seabook — the worker has zero identity documents and cannot prove their identity to any authority without the owner's cooperation",
            },
            {
                "id": "ss001_s3",
                "description": "The worker is assigned to a distant water fishing vessel departing for a 3-to-6-month voyage in international waters. The vessel operates under a Thai flag but fishes primarily in Indonesian and Malaysian exclusive economic zones under bilateral access agreements.",
                "legal_basis": "Distant water fishing vessel assignments are standard practice in Thailand's commercial fleet; bilateral fishing access agreements between Thailand and neighboring states authorize operations in designated zones",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Extended voyages in international waters place the worker beyond the reach of any single country's labor inspectors; vessel operates across multiple jurisdictions, making enforcement practically impossible",
            },
            {
                "id": "ss001_s4",
                "description": "During the voyage, crew members are transferred between vessels at sea using small boats, a practice known as 'transshipment.' The worker is moved from the original vessel to a different vessel belonging to another owner, with no updated documentation or notification to PIPO authorities.",
                "legal_basis": "At-sea transshipment of catch is a recognized practice in commercial fishing to extend voyage efficiency; crew rotation between vessels in a fleet is described as an operational necessity during extended fishing campaigns",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "At-sea crew transfer severs the last link between the worker and any registered documentation; the worker is now on an unregistered vessel with no paper trail, effectively invisible to any monitoring system",
            },
            {
                "id": "ss001_s5",
                "description": "The worker is paid on a catch-share basis: their compensation is calculated as a percentage of the vessel's net catch value after deductions for fuel, ice, food, equipment wear, and the broker's placement fee. Monthly statements show the worker consistently owes more in deductions than the catch share yields.",
                "legal_basis": "Catch-share compensation is a traditional payment model in commercial fishing worldwide; deductions for vessel operating costs are standard in share-based fishing contracts as recognized by ILO Work in Fishing Convention C188",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Catch-share with uncapped deductions ensures the worker never earns positive income; combined with at-sea isolation, no documents, and debt to the broker, the worker is trapped in unpaid labor with no way to leave, complain, or even be identified",
            },
        ],
        "chain_context": "Thailand's fishing industry reforms (PIPO centers, seabook registration, IUU fishing crackdowns) created documentation frameworks that were intended to protect fishers but in practice handed vessel owners a complete set of document-based control tools. Each step — brokered recruitment, seabook registration, distant water assignment, at-sea transfer, catch-share pay — uses a recognized industry practice, but the chain produces forced labor at sea with no escape mechanism. Liberty Shared and EJF have documented this exact pipeline across hundreds of cases.",
        "emergent_risk": "Forced labor at sea: broker debt + document confiscation + distant water isolation + at-sea transfer + perpetual-debt catch-share pay = invisible captive labor force beyond any jurisdiction's effective reach",
        "difficulty": "expert",
        "source_references": [
            "Liberty Shared — Fishing Industry Labor Exploitation in Thailand 2024",
            "Environmental Justice Foundation — Thailand's Seafood Slaves",
            "ILO — Work in Fishing Convention C188 Implementation Assessment",
            "Issara Institute — Voices from the Thai Fishing Fleet 2023",
            "CCCIF — PIPO Inspection Framework Guidelines",
        ],
        "corridors": ["MM-TH", "KH-TH", "LA-TH"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["deception", "debt bondage", "retention of identity documents", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "sector_specific_002",
        "name": "Gulf Domestic Worker Live-In Isolation and Control Cascade",
        "category": "sector_specific",
        "steps": [
            {
                "id": "ss002_s1",
                "description": "A licensed recruitment agency in Manila or Addis Ababa places a domestic worker with a household employer in Saudi Arabia or Lebanon. The agency facilitates the standard employment contract, medical clearance, and pre-departure orientation as required by the sending country's overseas labor office.",
                "legal_basis": "Licensed placement agencies operate under POEA (Philippines) or the Ethiopian Ministry of Labour and Social Affairs; placements follow bilateral labor agreements and standard employment contracts approved by the receiving country's ministry",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Agency placement into a private household setting creates a one-to-one employer-worker relationship with no co-workers, no external oversight, and no workplace inspections — the most isolated employment relationship possible",
            },
            {
                "id": "ss002_s2",
                "description": "The employment contract specifies a live-in arrangement as a condition of employment, with the employer providing a room within the household. The worker is expected to be available during 'household hours' which are described as flexible to meet the family's needs.",
                "legal_basis": "Live-in domestic work is the standard arrangement under the Kafala system and is explicitly provided for in the Saudi Unified Contract for Domestic Workers and Lebanon's Standard Unified Contract; live-in accommodation is treated as a benefit that offsets lower cash wages",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Live-in requirement eliminates the boundary between work time and personal time; 'flexible household hours' means the worker is effectively on-call 24 hours a day; the employer's home is simultaneously workplace, housing, and de facto detention facility",
            },
            {
                "id": "ss002_s3",
                "description": "The employer confiscates the worker's mobile phone during the first week, stating that phone use during work hours is not permitted and that the household has a landline the worker may use for family calls on their day off, if granted. The employer keeps the phone in a locked drawer.",
                "legal_basis": "Employer workplace rules regarding personal electronic device use are common across many employment settings; employers may restrict phone use during working hours as a productivity and household privacy measure",
                "sector": "domestic_work",
                "corridor": "ET-LB",
                "indicator_action_ids": [],
                "red_flag_context": "Phone confiscation severs the worker's only independent communication channel to family, embassy, or help hotlines; combined with live-in arrangement, the worker is now physically and communicatively isolated inside the employer's home",
            },
            {
                "id": "ss002_s4",
                "description": "The worker consistently works from 5:30 AM to 11:00 PM (17.5 hours) with brief breaks for meals, covering childcare, cooking, cleaning, laundry, and elderly care. The employer explains that these are normal household responsibilities and that the worker agreed to 'household duties as needed' in the contract.",
                "legal_basis": "Domestic workers are typically excluded from standard labor law working-hour protections; Saudi Arabia's and Lebanon's labor codes do not specify maximum hours for domestic workers, and the contract language 'duties as needed' is the standard formulation",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "17.5-hour workdays violate ILO Domestic Workers Convention C189 (Article 10) which requires hours comparable to other workers; legal exclusion of domestic workers from standard labor law makes this technically permissible despite being exploitative",
            },
            {
                "id": "ss002_s5",
                "description": "The employer refuses to grant the worker their contractually promised weekly day off, citing family needs, guests, or Ramadan preparations. When the worker requests the day off, the employer states that 'good workers don't ask for days off' and implies that requesting leave shows ingratitude and could lead to contract termination and repatriation.",
                "legal_basis": "While the standard contract provides for one day off per week, enforcement depends on mutual agreement and household circumstances; employers may adjust rest days based on legitimate household needs with compensatory time offered later",
                "sector": "domestic_work",
                "corridor": "ET-LB",
                "indicator_action_ids": [],
                "red_flag_context": "Systematic day-off denial combined with threat of termination and repatriation completes the isolation cycle: the worker is confined to the employer's home 24/7, without rest, without communication, and with the constant threat that asserting rights means deportation and unpaid debts at home",
            },
        ],
        "chain_context": "Each step in this chain uses a legally recognized element of the Gulf domestic work system: licensed agency placement, live-in contract terms, employer household rules, flexible duty language, and schedule adjustments. But the cumulative effect is total control — the worker lives, works, eats, and sleeps within a single private space controlled entirely by the employer, with no phone, no days off, no co-workers, and no meaningful access to external help. ILO C189 specifically targets these patterns but remains unratified by Gulf states.",
        "emergent_risk": "Total domestic confinement: agency placement into private home + mandatory live-in + phone confiscation + 17-hour days + day-off denial = 24/7 captive labor with no external contact or rest",
        "difficulty": "hard",
        "source_references": [
            "ILO — Domestic Workers Convention C189",
            "Human Rights Watch — Hidden in the Home: Abuse of Domestic Workers in Saudi Arabia",
            "Anti-Slavery International — Domestic Workers Under Kafala",
            "Migrasia — Live-In Domestic Worker Isolation Patterns 2024",
            "This Is Lebanon — Domestic Worker Abuse Documentation",
        ],
        "corridors": ["PH-SA", "ET-LB", "PH-KW", "ET-SA", "ID-SA"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["abuse of position of vulnerability", "restriction of movement", "coercion", "intimidation"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "sector_specific_003",
        "name": "Qatar Construction Worker Heat Exposure and Disposable Labor Chain",
        "category": "sector_specific",
        "steps": [
            {
                "id": "ss003_s1",
                "description": "A Nepali or Indian construction worker is recruited through a licensed manpower agency in Kathmandu or Mumbai for a construction project in Doha. The agency processes the work visa under Qatar's reformed labor mobility system, and the worker signs a contract specifying a monthly salary of QAR 1,500 (~$410) plus accommodation.",
                "legal_basis": "Qatar's post-2020 labor reforms require standard employment contracts registered with the Ministry of Administrative Development, Labour and Social Affairs (ADLSA); recruitment through licensed agencies is the mandated channel under Nepal's Foreign Employment Act and India's Emigration Act",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Reformed recruitment channel creates appearance of compliance, but the actual working conditions diverge sharply from the contract terms once the worker arrives in Qatar",
            },
            {
                "id": "ss003_s2",
                "description": "The worker is housed in an employer-operated labor camp on the outskirts of the Industrial Area in Doha, sharing a room with 11 other workers. The camp provides meals and transport to the construction site. Monthly deductions of QAR 300 (~$82) are taken for food and accommodation, reducing net pay to QAR 1,200.",
                "legal_basis": "Employer-provided labor accommodation is standard for construction workers in Qatar; the Workers' Accommodation Standards issued by ADLSA set minimum space requirements (4 sq meters per person); reasonable deductions for food and housing are permitted under Qatar Labour Law Article 70",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Labor camp housing creates employer-controlled living environment; 12-to-a-room conditions barely meet minimum standards; camp location far from city center limits workers' ability to access embassies, legal aid, or alternative services",
            },
            {
                "id": "ss003_s3",
                "description": "During summer months (June-September), temperatures regularly exceed 45C (113F) on exposed construction sites. Qatar's summer working hours ban prohibits outdoor work between 10:00 AM and 3:30 PM from June 1 to September 15, but the site supervisor schedules concrete pouring and rebar work from 3:35 PM through midnight, and again from 4:00 AM to 9:55 AM, arguing this complies with the ban.",
                "legal_basis": "Qatar Ministerial Decision No. 17 of 2021 on heat stress establishes working hour restrictions during summer months; the project schedule is structured to fall outside the prohibited window while maximizing productive hours",
                "sector": "construction",
                "corridor": "IN-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Temperatures remain dangerously high outside the banned window (often 40C+ at 3:35 PM); splitting shifts to avoid the ban while maintaining total hours exposes workers to cumulative heat stress; the 2021 WBGT-based reforms are more protective but enforcement relies on worker complaints that rarely materialize due to fear of retaliation",
            },
            {
                "id": "ss003_s4",
                "description": "A worker collapses on site from heat exhaustion and is taken to Hamad Medical Corporation. The employer files an injury report classifying the incident as a 'pre-existing cardiac event' rather than a workplace heat injury. The worker is diagnosed with acute kidney injury consistent with chronic heat exposure and dehydration.",
                "legal_basis": "Employers are required to report workplace injuries to ADLSA under Qatar Labour Law; medical classification is determined by the treating physician's clinical assessment; cardiac events are a recognized category in Qatar's occupational injury reporting system",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Systematic misclassification of heat-related deaths and injuries as 'cardiac arrest' or 'natural causes' has been extensively documented; The Guardian's 2021 investigation found over 6,500 South Asian worker deaths in Qatar over a decade with most certified as 'natural' deaths despite occurring during or after extreme heat exposure",
            },
            {
                "id": "ss003_s5",
                "description": "The injured worker is medically repatriated to Nepal after 3 weeks of hospital treatment. The employer provides a one-way flight and a terminal gratuity payment of QAR 750 (~$206), representing the statutory minimum. No workers' compensation claim is filed because the injury was classified as non-occupational, and the worker's end-of-service benefits are calculated at 3 months of employment rather than the 18 months actually worked.",
                "legal_basis": "Medical repatriation is provided for under Qatar Labour Law when a worker is medically unfit to continue employment; end-of-service gratuity is calculated per Article 54 based on the employment period; non-occupational injuries do not qualify for workers' compensation under Qatar's social insurance framework",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Worker returns to Nepal with chronic kidney damage, no compensation for the occupational injury, falsified employment duration reducing their gratuity, and the original recruitment debt still partially unpaid — the worker is both physically damaged and financially worse off than before migration",
            },
        ],
        "chain_context": "Qatar's post-World Cup labor reforms created compliance frameworks (ADLSA registration, heat stress ministerial decisions, labor accommodation standards) that address each issue in isolation. But the chain demonstrates how compliant recruitment, technically-legal camp housing, work scheduling that narrowly avoids the heat ban, systematic injury misclassification, and minimum-benefit repatriation combine to produce a disposable labor model where workers absorb the health costs of construction while employers face no liability.",
        "emergent_risk": "Disposable labor through systemic gaps: compliant recruitment + camp isolation + heat ban circumvention + injury misclassification + minimal repatriation = worker permanently damaged with zero accountability",
        "difficulty": "expert",
        "source_references": [
            "The Guardian — Qatar Migrant Worker Death Investigation 2021",
            "Amnesty International — In the Prime of Their Lives: Qatar Construction Worker Deaths",
            "ILO — Qatar Heat Stress Programme Assessment 2023",
            "ADLSA — Ministerial Decision No. 17 of 2021 (Heat Stress)",
            "Nepali Embassy Doha — Worker Repatriation Statistics",
        ],
        "corridors": ["NP-QA", "IN-QA", "BD-QA", "PK-QA"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["deception", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "sector_specific_004",
        "name": "Malaysian Palm Oil Plantation Debt and Child Labor Normalization",
        "category": "sector_specific",
        "steps": [
            {
                "id": "ss004_s1",
                "description": "A village recruiter in rural Kalimantan (Indonesian Borneo) visits communities near the border offering palm oil plantation work in Sarawak, Malaysia. The recruiter arranges informal border crossing through established routes and charges 3 million IDR (~$190) as a 'transport and placement' fee, payable through salary deductions over 6 months.",
                "legal_basis": "Labor recruitment for cross-border agricultural work is a common intermediary function along the Indonesia-Malaysia border; the fee covers documented transport and coordination costs between the village and the plantation",
                "sector": "agriculture",
                "corridor": "ID-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Village recruiters operate outside formal licensing; informal border crossing means workers enter Malaysia without valid work permits, making them immediately undocumented and dependent on the plantation for any legal status",
            },
            {
                "id": "ss004_s2",
                "description": "The worker is assigned to a remote oil palm estate in interior Sarawak. Housing is provided in on-estate worker quarters. The worker is given a daily harvesting target of 1.5 tonnes of fresh fruit bunches (FFB), paid on a piece-rate of RM 30 per tonne (~$6.50). Workers who meet the daily target earn approximately RM 45/day, below Malaysia's minimum wage of RM 1,500/month.",
                "legal_basis": "Piece-rate agricultural payment is permitted under Malaysia's Employment Act; plantation employers argue that productive workers can exceed targets and earn above minimum wage; agricultural sector has historically received minimum wage exemptions",
                "sector": "agriculture",
                "corridor": "ID-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Piece-rate targets are set so that average workers earn below minimum wage; remote estate location means no alternative employment or services; workers cannot leave the estate without transport arranged by the plantation",
            },
            {
                "id": "ss004_s3",
                "description": "The plantation operates a company store (kedai estate) that is the only retail option accessible to workers on the remote estate. Workers purchase food, toiletries, phone credit, and basic supplies on credit against their monthly earnings. The store prices are 30-50% above market rate, and the running tab is deducted from wages before any cash payment is made.",
                "legal_basis": "Employer-operated retail facilities in remote agricultural settings are a recognized practice under Malaysia's plantation sector regulations; credit facilities provided to workers as an advance against wages are documented as voluntary arrangements",
                "sector": "agriculture",
                "corridor": "ID-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Classic truck system / company store debt cycle: inflated prices + sole retail access + credit deductions ensure workers receive minimal or zero cash pay; mathematically impossible to save or clear debt when essential purchases consume most of the below-minimum-wage earnings",
            },
            {
                "id": "ss004_s4",
                "description": "As the worker's family (spouse and children) join them on the estate, the children begin helping with loose fruit collection (picking up palm fruit that falls from harvested bunches). The plantation records this as 'family accompaniment' rather than child labor, and the loose fruit collection is attributed to the adult worker's daily tonnage count.",
                "legal_basis": "Malaysian law does not prohibit children from accompanying parents at a workplace; agricultural family participation is distinguished from child labor in many national frameworks; the children are not formally employed by the plantation",
                "sector": "agriculture",
                "corridor": "ID-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Children performing loose fruit collection is functionally child labor — it is necessary for the adult to meet the daily target; the 'family accompaniment' framing allows the plantation and downstream buyers to deny child labor in supply chain audits",
            },
            {
                "id": "ss004_s5",
                "description": "The cycle becomes self-perpetuating: the worker cannot clear company store debt on piece-rate earnings, needs children's help to meet targets, cannot leave the remote estate without documents or savings, and the recruitment debt from the original placement remains outstanding. The plantation offers to 'renew' the worker's informal arrangement for another season, adding new fees.",
                "legal_basis": "Seasonal agricultural contract renewals are standard practice; workers choose to continue employment voluntarily; the plantation provides ongoing housing and employment stability for the family",
                "sector": "agriculture",
                "corridor": "ID-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Intergenerational debt cycle: parent's recruitment debt + company store debt + piece-rate poverty + children working to meet targets + no documents + remote isolation = family trapped in perpetual labor with debt passed to the next generation",
            },
        ],
        "chain_context": "Malaysia's palm oil sector is the world's second-largest producer and supplies major global brands. The chain demonstrates how informal recruitment, remote estate placement, below-minimum-wage piece rates, company store monopolies, and the normalization of children's 'family help' combine to create intergenerational bonded labor. Supply chain audits by downstream buyers (Nestle, Unilever, P&G) focus on the refinery level and rarely reach individual estates where these practices occur.",
        "emergent_risk": "Intergenerational plantation bondage: informal recruitment + undocumented status + piece-rate poverty + company store debt + normalized child labor = family trapped across generations with debt deepening each season",
        "difficulty": "hard",
        "source_references": [
            "Amnesty International — The Great Palm Oil Scandal: Labour Abuses Behind Big Brand Names",
            "Rainforest Action Network — Palm Oil Supply Chain Worker Conditions",
            "US Department of Labor — List of Goods Produced by Child Labor (Palm Oil, Malaysia)",
            "Issara Institute — Plantation Worker Voices 2024",
            "ILO — Child Labour in Palm Oil: Malaysia Assessment",
        ],
        "corridors": ["ID-MY"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["debt bondage", "abuse of position of vulnerability", "deception"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "sector_specific_005",
        "name": "UK Seasonal Agriculture Gangmaster-Controlled Exploitation Chain",
        "category": "sector_specific",
        "steps": [
            {
                "id": "ss005_s1",
                "description": "A Romanian or Bulgarian agricultural worker applies through a UK Seasonal Worker Scheme (SWS) operator for a 6-month fruit-picking contract in Kent or Herefordshire. The SWS operator is licensed by the Gangmasters and Labour Abuse Authority (GLAA) and the worker receives a Temporary Worker visa tied to the licensed operator.",
                "legal_basis": "The UK Seasonal Worker Scheme is a government-administered temporary migration program; SWS operators are GLAA-licensed and audited; the visa is valid for up to 6 months of agricultural work under the Immigration Rules Appendix T5 Seasonal Worker",
                "sector": "agriculture",
                "corridor": "EU-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Visa tied to the SWS operator (not a specific farm) gives the operator control over which farm the worker is assigned to, when, and for how long — the worker cannot independently seek work or change operators without losing their visa",
            },
            {
                "id": "ss005_s2",
                "description": "The SWS operator arranges all transport from the airport to the farm and between accommodation and the work site. Workers are transported in operator-managed minibuses. A daily transport charge of GBP 7 is deducted from wages for the minibus service, which operates on the operator's schedule with no public transit alternative in the rural area.",
                "legal_basis": "Transport provision and reasonable charges are permitted under GLAA licensing conditions; transport deductions must be documented and agreed in writing; the operator's transport service is described as a worker benefit in remote agricultural locations",
                "sector": "agriculture",
                "corridor": "EU-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Operator-controlled transport creates physical dependency: workers cannot reach the farm, town, or alternative employment without the operator's minibus; daily charges accumulate to GBP 150+/month, reducing already-low piece-rate earnings",
            },
            {
                "id": "ss005_s3",
                "description": "Workers are paid on a piece-rate basis per kilogram of fruit picked. The rate is calibrated so that an experienced picker working at maximum speed for 8 hours earns approximately the National Minimum Wage, but most workers — especially in the first weeks — earn below minimum wage. The operator records hours as fewer than actually worked to maintain compliant hourly-rate records.",
                "legal_basis": "Piece-rate payment in agriculture is legal under the National Minimum Wage Act provided that the effective hourly rate meets or exceeds the NMW; employers must maintain accurate time records; piece rates are described as incentivizing productivity",
                "sector": "agriculture",
                "corridor": "EU-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Systematic under-recording of hours is a documented GLAA enforcement finding; the gap between actual hours and recorded hours means workers earn below NMW while paper records show compliance; workers who challenge records risk being moved to lower-yield fields",
            },
            {
                "id": "ss005_s4",
                "description": "Accommodation is provided in static caravans on or near the farm, with 4-6 workers per caravan. The operator deducts GBP 60 per week from wages for the accommodation, which is described as 'below local market rent.' Workers cannot arrange alternative housing because the visa is tied to the operator and the farm is in a rural area with no available rental market.",
                "legal_basis": "Accommodation offset against wages is permitted under NMW regulations up to the HMRC-set daily accommodation offset rate; caravan accommodation on agricultural sites is recognized under GLAA licensing standards",
                "sector": "agriculture",
                "corridor": "EU-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Accommodation deductions of GBP 240+/month combined with transport charges and piece-rate earnings that barely reach NMW leave workers with minimal take-home pay; housing tied to the operator means losing the job means immediate homelessness",
            },
            {
                "id": "ss005_s5",
                "description": "When a worker raises concerns about pay calculations or requests a transfer to a different farm, the operator informs them that SWS workers who are 'difficult' will not be invited back for the next season and may be reported to the Home Office for 'failure to comply with visa conditions.' The worker is told that a negative report would prevent future UK visa applications.",
                "legal_basis": "SWS operators have a reporting obligation to the Home Office regarding worker compliance with visa conditions; operators manage worker allocations across farms based on labor demand and worker performance",
                "sector": "agriculture",
                "corridor": "EU-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Blacklist threat leverages the worker's desire for future seasonal income; Home Office reporting power gives the operator quasi-immigration authority; workers self-censor complaints to protect future visa eligibility, creating a silence mechanism around labor violations",
            },
        ],
        "chain_context": "The UK Seasonal Worker Scheme is regulated by the GLAA, one of the world's strongest labor market enforcement agencies. Yet the chain demonstrates how operator-tied visas, controlled transport, piece-rate calibration, accommodation deductions, and blacklist threats create comprehensive control within a licensed, audited framework. The GLAA's own enforcement reports have documented multiple cases matching this pattern among licensed operators.",
        "emergent_risk": "Licensed exploitation: GLAA-licensed operator + tied visa + controlled transport + rigged piece rates + accommodation deductions + blacklist threat = comprehensive control within a regulated system",
        "difficulty": "hard",
        "source_references": [
            "GLAA — Annual Labour Exploitation Report 2024",
            "Focus on Labour Exploitation (FLEX) — Seasonal Worker Scheme Assessment",
            "University of Nottingham — Rights of Seasonal Workers Research",
            "The Guardian — Seasonal Workers Scheme Exploitation Investigation 2023",
            "UK Modern Slavery Act — Section 54 Reporting Analysis",
        ],
        "corridors": ["EU-UK"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["coercion", "abuse of position of vulnerability", "intimidation"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "sector_specific_006",
        "name": "Education Sector Student-Worker Visa Exploitation Chain",
        "category": "sector_specific",
        "steps": [
            {
                "id": "ss006_s1",
                "description": "A recruitment agent in the Philippines or India promotes a 'study and work' program at a vocational college or private training institution in the US (M-1 visa) or Australia (subclass 500 student visa). The agent emphasizes that the program includes 'industry placement' or 'practical training' that allows the student to earn income while studying, effectively marketing the program as a migration pathway.",
                "legal_basis": "International student recruitment is a licensed industry; vocational education providers are registered with the relevant national authority (SEVP in the US, CRICOS in Australia); student visa provisions for work are part of the immigration framework",
                "sector": "education",
                "corridor": "PH-US",
                "indicator_action_ids": [],
                "red_flag_context": "Program marketed as a work opportunity disguised as education; the agent earns commission from the institution, creating an incentive to oversell work rights and understate study requirements; the student's primary motivation is income, not education",
            },
            {
                "id": "ss006_s2",
                "description": "Upon enrollment, the student discovers that the 'industry placement' component requires mandatory unpaid or below-minimum-wage 'training hours' at businesses affiliated with the college. The student must complete 800 hours of practical training to receive their qualification. The training provider is a restaurant, hotel, or aged-care facility that receives free or cheap labor from the student pipeline.",
                "legal_basis": "Curricular Practical Training (CPT) in the US and work-integrated learning in Australia allow students to work as part of their educational program; training hours at host businesses are classified as educational activities rather than employment under the relevant frameworks",
                "sector": "education",
                "corridor": "IN-AU",
                "indicator_action_ids": [],
                "red_flag_context": "Mandatory 'training' that looks identical to regular employment but is unpaid or underpaid because it is classified as education; the host business receives labor without paying employment costs; the student cannot refuse without failing the course and losing their visa",
            },
            {
                "id": "ss006_s3",
                "description": "The tuition fees for the vocational program are $15,000-$25,000 per year. The student has taken a loan from a family member or private lender in their home country to pay the first year's tuition, with the expectation that work income would cover subsequent years. The institution requires full payment each semester before enrollment can continue.",
                "legal_basis": "Tuition fee structures are set by registered education providers within the regulatory framework; international students are required to demonstrate financial capacity for their studies as a visa condition; private lending for education is a standard financial arrangement",
                "sector": "education",
                "corridor": "PH-US",
                "indicator_action_ids": [],
                "red_flag_context": "Tuition debt creates a financial trap: the student borrowed money to access the program, needs to complete the program to justify the debt, but the 'training' work generates insufficient income to pay ongoing tuition — creating a cycle where the student must work more hours (violating visa conditions) or borrow more",
            },
            {
                "id": "ss006_s4",
                "description": "The student works additional hours beyond the visa-permitted limit (20 hours/week during term in Australia; unauthorized employment for M-1 visa holders in the US) at cash-in-hand jobs arranged through networks connected to the college or the student community. The employer pays below minimum wage knowing the student cannot complain without exposing their own visa violation.",
                "legal_basis": "Student visa work-hour limits are clearly defined in immigration law; work beyond these limits constitutes a visa breach by the student; employers are required to verify work rights but enforcement is complaint-driven",
                "sector": "education",
                "corridor": "IN-AU",
                "indicator_action_ids": [],
                "red_flag_context": "Work-hour violations are driven by tuition debt and inadequate training income; the student's own visa breach becomes a tool of employer control — any complaint about wages or conditions risks triggering the student's own deportation",
            },
            {
                "id": "ss006_s5",
                "description": "When the student falls behind on tuition payments or attendance requirements, the institution threatens to report the student to immigration authorities for failing to maintain enrollment (a visa condition). The institution offers to 'resolve' the situation if the student agrees to additional unpaid training hours at affiliated businesses, further deepening the exploitation cycle.",
                "legal_basis": "Registered education providers are legally required to report students who fail to meet visa conditions (enrollment, attendance, course progress) to immigration authorities; SEVP-certified schools and CRICOS providers have mandatory reporting obligations",
                "sector": "education",
                "corridor": "PH-US",
                "indicator_action_ids": [],
                "red_flag_context": "The institution wields immigration reporting power as a coercion tool, identical to how employers use visa threats in labor contexts; the 'resolution' of more unpaid work deepens the exploitation while appearing to be an act of institutional mercy; the student is trapped between debt, visa status, and escalating labor extraction",
            },
        ],
        "chain_context": "Education sector exploitation operates at the intersection of immigration law, education regulation, and labor law — three systems that rarely coordinate enforcement. The chain uses a registered education provider, legitimate visa categories, and standard tuition structures to create a labor exploitation pipeline disguised as international education. Australia's Migrant Worker Taskforce and the US GAO have both identified this pattern in multiple investigations of predatory vocational colleges.",
        "emergent_risk": "Education-laundered labor exploitation: recruitment-as-education + mandatory unpaid training + tuition debt + work-hour violations + visa-status threats = forced labor disguised as international student experience",
        "difficulty": "expert",
        "source_references": [
            "Australian Migrant Workers Taskforce — Report on International Student Exploitation 2023",
            "US GAO — Oversight of SEVP-Certified Schools",
            "Fair Work Ombudsman — Inquiry into the Wages and Conditions of International Students",
            "ILO — Labour Exploitation in Educational Pathways Migration",
            "Migrant Justice Institute — Student Workers at Risk 2024",
        ],
        "corridors": ["PH-US", "IN-AU", "IN-US", "NP-AU", "VN-AU"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["deception", "debt bondage", "coercion", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "sector_specific_007",
        "name": "Jordan QIZ Garment Factory Dormitory Exploitation Chain",
        "category": "sector_specific",
        "steps": [
            {
                "id": "ss007_s1",
                "description": "A Sri Lankan or Bangladeshi garment worker is recruited through a licensed agency for a sewing machine operator position at a Qualified Industrial Zone (QIZ) factory in Jordan. The QIZ designation means products exported to the US receive preferential tariff treatment, and the factory supplies major US apparel brands. The worker pays the agency $1,000-$2,000 in recruitment fees.",
                "legal_basis": "Jordan's QIZ factories operate under the US-Jordan-Israel trade agreement; recruitment through licensed agencies is the standard channel; agencies charge permitted fees for processing, documentation, and travel arrangements",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "QIZ factories benefit from US trade preferences, creating pressure to minimize labor costs; recruitment fees create pre-arrival debt that takes 5-10 months to repay on Jordanian garment wages; the worker has no realistic option to return without repaying",
            },
            {
                "id": "ss007_s2",
                "description": "The worker is housed in a factory-operated dormitory within the QIZ compound. The dormitory room is shared with 7 other workers. Meals are provided in a factory canteen. A monthly deduction of 50 JOD (~$70) is taken from the worker's 220 JOD (~$310) salary for food and accommodation, reducing net pay to 170 JOD.",
                "legal_basis": "Employer-provided dormitory housing within industrial zones is standard practice in Jordan's garment sector; accommodation deductions are documented in the employment contract and subject to Jordan Labour Law provisions; the Ministry of Labour conducts dormitory inspections",
                "sector": "manufacturing",
                "corridor": "BD-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Dormitory within the factory compound means workers live and work in the same enclosed space; deductions reduce already-low wages; the compound structure limits workers' contact with the outside world and creates physical dependency on the employer for all basic needs",
            },
            {
                "id": "ss007_s3",
                "description": "During peak production periods (typically before US retail seasons), the factory mandates overtime shifts of 3-4 additional hours per day, 6 days per week. Workers who decline overtime are told their contracts may not be renewed. Overtime pay is calculated at the standard rate rather than the legally required 125% premium, and workers must sign overtime 'consent' forms monthly.",
                "legal_basis": "Jordan Labour Law Article 56 permits overtime with worker consent up to specified limits; overtime must be compensated at 125% of the regular rate; the factory presents overtime as voluntary and documents consent through signed forms",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Forced overtime disguised as voluntary through coerced consent forms; overtime premium violation reduces effective hourly rate; contract non-renewal threat makes refusal practically impossible for workers with outstanding recruitment debt",
            },
            {
                "id": "ss007_s4",
                "description": "Wages are paid 2-3 months in arrears, with the factory citing 'payment processing delays' and 'buyer payment cycles.' Workers are given advance payments of 30-50 JOD to cover immediate needs, creating a system where the factory always owes the worker 2-3 months of accumulated wages.",
                "legal_basis": "Jordan Labour Law requires monthly wage payment but enforcement delays are common in the garment sector; advance payments are documented as goodwill measures to support workers during processing delays",
                "sector": "manufacturing",
                "corridor": "BD-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Systematic wage delay creates a financial lock: the worker cannot leave without forfeiting 2-3 months of unpaid wages (440-660 JOD) — more than the cost of returning home; combined with recruitment debt, the worker is financially trapped in both directions",
            },
            {
                "id": "ss007_s5",
                "description": "Workers who wish to leave the QIZ compound on their day off must request permission from the factory administration 48 hours in advance and receive a gate pass. The compound is surrounded by a perimeter wall with security guards at the gate. Workers report that gate pass requests are sometimes denied without explanation, especially during peak production periods.",
                "legal_basis": "Industrial zone security protocols require entry/exit documentation for safety, liability, and immigration compliance purposes; advance notification helps the factory manage transport and security staffing",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Walled compound with controlled exit, dormitory inside the compound, and discretionary gate pass denial amounts to physical confinement; the ILO Better Work Jordan program has flagged this exact pattern in multiple QIZ factory assessments as a restriction of movement indicator",
            },
        ],
        "chain_context": "Jordan's QIZ garment factories sit at the intersection of international trade policy, labor migration, and global supply chains. Major US brands source from QIZ factories because of preferential tariffs, creating cost pressure that flows down to workers. Each element — licensed recruitment, compound dormitories, documented overtime consent, payment delays, security protocols — has a business justification, but the chain creates compound-confined forced labor. The ILO Better Work Jordan program and the National Labour Committee have documented this pattern across multiple QIZ facilities.",
        "emergent_risk": "Supply chain forced labor in trade-preference zones: recruitment debt + compound dormitory + coerced overtime + systematic wage delay + exit restrictions = factory compound confinement subsidized by US trade preferences",
        "difficulty": "hard",
        "source_references": [
            "ILO Better Work Jordan — Compliance Synthesis Report 2024",
            "National Labour Committee — Made in Jordan: Hidden Abuse Behind Fashion Labels",
            "Institute for Global Labour and Human Rights — QIZ Worker Conditions",
            "US-Jordan FTA Implementation Review",
            "Verité — Forced Labor Risk in Garment Supply Chains: Jordan",
        ],
        "corridors": ["LK-JO", "BD-JO", "PH-JO", "IN-JO"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["debt bondage", "restriction of movement", "coercion"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "sector_specific_008",
        "name": "South Asian Brick Kiln Intergenerational Debt Bondage Chain",
        "category": "sector_specific",
        "steps": [
            {
                "id": "ss008_s1",
                "description": "A brick kiln owner in Uttar Pradesh, India, or in the Kathmandu Valley, Nepal, provides an advance payment (peshgi) of INR 20,000-50,000 (~$240-$600) to a family from a Dalit or marginalized tribal community at the start of the brick-making season (October-June). The advance covers family debts, medical expenses, or school fees, and is formalized with a verbal or written agreement that the family will work at the kiln until the advance is repaid.",
                "legal_basis": "Seasonal advance payments in brick manufacturing are a traditional labor arrangement recognized across South Asia; the advance provides working capital to families during the off-season and secures labor supply for the kiln operator; similar arrangements exist in India's Bonded Labour System (Abolition) Act context as documented pre-existing practices",
                "sector": "manufacturing",
                "corridor": "IN domestic",
                "indicator_action_ids": [],
                "red_flag_context": "Advance payments to marginalized caste/tribal families exploit pre-existing poverty and social vulnerability; the peshgi system has been recognized by the Indian Supreme Court and the ILO as the primary mechanism of bonded labor in brick kilns, trapping an estimated 10-23 million workers",
            },
            {
                "id": "ss008_s2",
                "description": "The entire family migrates to the brick kiln site at the start of the season. The kiln provides basic shelter (a temporary structure near the kiln) and the family is assigned a daily production target of 1,000-1,500 bricks. Payment is on a piece-rate basis per 1,000 bricks, with the advance repayment deducted first from each payment cycle.",
                "legal_basis": "Family-based seasonal migration for agricultural and manufacturing work is a recognized labor pattern in South Asia; piece-rate payment for brick making is the industry standard; kiln-site accommodation is provided as part of the seasonal employment arrangement",
                "sector": "manufacturing",
                "corridor": "NP domestic",
                "indicator_action_ids": [],
                "red_flag_context": "Family migration means the entire household's income depends on the kiln; daily targets require the labor of all family members to achieve; kiln-site housing means the family has no alternative accommodation if they leave",
            },
            {
                "id": "ss008_s3",
                "description": "Throughout the season, the kiln owner deducts charges from the family's piece-rate earnings for fuel, water, materials waste, equipment use, and advances for food purchased from the kiln's provisions store. Monthly account statements show the family's net earnings are consistently less than the deductions, causing the original advance debt to grow rather than shrink.",
                "legal_basis": "Deductions for materials and supplies are documented in the employment arrangement; the kiln's provisions store provides essential goods on credit in remote kiln locations where no other retail options exist; account statements are provided to the family showing the running balance",
                "sector": "manufacturing",
                "corridor": "IN domestic",
                "indicator_action_ids": [],
                "red_flag_context": "Perpetual debt through inflated deductions: the piece-rate is set so that deductions consistently exceed earnings; the family can never repay the advance during a single season; the ILO has documented that 60-80% of brick kiln families end each season with higher debt than they started with",
            },
            {
                "id": "ss008_s4",
                "description": "At the end of the season, the kiln owner presents the family with a statement showing an outstanding balance that exceeds the original advance. The family is offered a new, larger advance for the next season that rolls over the outstanding balance, creating a new binding obligation. The family accepts because they have no savings, the off-season provides no income, and the outstanding debt prevents them from seeking work at a different kiln.",
                "legal_basis": "Seasonal contract renewal with advance roll-over is described as a continuation of the existing employment relationship; the family voluntarily accepts the new advance; kiln owners argue they are providing year-round financial stability to seasonal workers",
                "sector": "manufacturing",
                "corridor": "IN domestic",
                "indicator_action_ids": [],
                "red_flag_context": "Debt roll-over is the intergenerational transmission mechanism: each season begins with higher debt, ensuring the family can never achieve freedom; the 'voluntary' acceptance is coerced by poverty, isolation, and the absence of any alternative — classic debt bondage as defined by the 1956 Supplementary Convention on the Abolition of Slavery",
            },
            {
                "id": "ss008_s5",
                "description": "The family's children, some as young as 5-6 years old, work alongside parents at the kiln — carrying wet bricks to drying racks, mixing clay, and stacking dried bricks. The kiln owner counts the children's production toward the family's daily target but does not pay separately for their labor. When inspectors visit, children are told to go to the family's shelter.",
                "legal_basis": "Children accompanying parents at a seasonal work site is distinguished from formal child employment under many national frameworks; the children are not on the kiln's payroll; India's Child Labour (Prohibition and Regulation) Act has specific provisions for family enterprises",
                "sector": "manufacturing",
                "corridor": "NP domestic",
                "indicator_action_ids": [],
                "red_flag_context": "Child labor is structurally necessary: the family cannot meet daily targets without children's labor; children are denied education during the 8-month kiln season; inspector evasion demonstrates awareness that the practice is illegal; intergenerational bondage ensures children inherit the debt and the labor obligation",
            },
        ],
        "chain_context": "Brick kiln bonded labor is one of the largest single categories of forced labor globally, affecting an estimated 10-23 million people across India, Nepal, Pakistan, and Bangladesh. The advance-debt-deduction-rollover cycle has persisted for generations despite being explicitly prohibited by India's Bonded Labour System (Abolition) Act 1976 and Nepal's Bonded Labour Prohibition Act 2002. Each element — seasonal advances, piece-rate production, kiln-site housing, material deductions, contract renewal — is individually defensible as a standard business practice, but the chain produces hereditary forced labor indistinguishable from servitude.",
        "emergent_risk": "Hereditary bonded labor: caste-targeted advance + family migration + rigged piece-rate deductions + debt roll-over + child labor = intergenerational servitude transmitted through a cycle of mathematically unpayable debt",
        "difficulty": "expert",
        "source_references": [
            "ILO — Bonded Labour in Brick Kilns: South Asia Assessment 2023",
            "Anti-Slavery International — Slavery in India's Brick Kilns",
            "India Supreme Court — PUCL v. State of Tamil Nadu (brick kiln bonded labour)",
            "Nepal Bonded Labour Prohibition Act 2002",
            "India Bonded Labour System (Abolition) Act 1976",
            "Kailash Satyarthi Children's Foundation — Child Labour in Brick Kilns",
        ],
        "corridors": ["IN domestic", "NP domestic"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["debt bondage", "abuse of position of vulnerability", "deception"],
            "purpose": ["forced labour", "exploitation", "slavery or practices similar to slavery"],
        },
    },
    {
        "id": "sector_specific_009",
        "name": "Nail Salon and Service Industry Immigration-Debt Control Chain",
        "category": "sector_specific",
        "steps": [
            {
                "id": "ss009_s1",
                "description": "A Vietnamese worker is recruited for a nail technician position in the US or UK through a network that arranges the visa and travel. In the US, the worker arrives on a B-1/B-2 visitor visa or through an informal channel; in the UK, the worker may arrive on a visitor visa or through clandestine entry organized by the network. The worker pays $15,000-$30,000 for the full arrangement, with the debt held by the network's financier.",
                "legal_basis": "International travel and visa applications are individual decisions; the costs cover legitimate services including documentation, travel arrangements, and job placement; debt agreements between individuals are private financial transactions",
                "sector": "services",
                "corridor": "VN-US",
                "indicator_action_ids": [],
                "red_flag_context": "Smuggling networks disguise their operations as migration services; the $15-30K debt is enforceable through threats to the worker and their family in Vietnam; the worker arrives with no valid work authorization but owes a life-altering sum",
            },
            {
                "id": "ss009_s2",
                "description": "The salon owner provides 'training' in the specific techniques and products used at the salon, describing it as an investment in the worker's skills. The training period lasts 2-3 months during which the worker receives no wages but is provided accommodation (a shared apartment with other salon workers) and meals. A 'training debt' of $3,000-$5,000 is added to the worker's existing obligations.",
                "legal_basis": "Vocational training for new employees is a standard onboarding practice; training costs represent the employer's investment in the worker; accommodation and meals during training are in-kind compensation",
                "sector": "services",
                "corridor": "VN-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Training debt layered on top of migration debt deepens the financial trap; the worker is performing productive work (servicing customers) during 'training' but receiving zero wages; shared accommodation controlled by the salon owner means the worker's housing is tied to continued employment",
            },
            {
                "id": "ss009_s3",
                "description": "After the training period, the worker begins earning wages but all tips from customers are collected by the salon owner at the end of each day. The owner states that tips are pooled and distributed monthly, but workers report receiving only a fraction of the tip pool or nothing at all. The salon pays the worker a flat daily rate of $40-$60 regardless of the number of clients served.",
                "legal_basis": "Tip pooling arrangements are permitted in many jurisdictions with specific rules; the salon owner manages the tip pool as the business operator; flat-rate daily pay provides income stability regardless of client volume",
                "sector": "services",
                "corridor": "VN-US",
                "indicator_action_ids": [],
                "red_flag_context": "Tip confiscation is a primary income theft mechanism in nail salons: tips often equal or exceed base wages in this sector; the worker cannot verify tip amounts or challenge distributions without risking termination and debt acceleration; NYT's 2015 investigation documented systemic tip theft across NYC nail salons",
            },
            {
                "id": "ss009_s4",
                "description": "The salon owner monitors the worker through a camera system in the salon and through their knowledge of the worker's accommodation. The worker is told not to speak to customers about their personal situation or immigration status. The salon owner knows the worker's family address in Vietnam and periodically reminds the worker that 'people in Vietnam' are aware of the outstanding debt.",
                "legal_basis": "Workplace surveillance cameras are standard business security measures; employer policies about professional conduct with customers are normal business practices; the salon owner's knowledge of worker background is from the recruitment process",
                "sector": "services",
                "corridor": "VN-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Surveillance + knowledge of family in Vietnam constitutes both direct monitoring and implicit threats; the reference to 'people in Vietnam' invokes the smuggling/lending network's enforcement capacity; the worker is silenced by fear of consequences for themselves and their family",
            },
            {
                "id": "ss009_s5",
                "description": "When the worker expresses a desire to leave or work elsewhere, the salon owner reminds them of their undocumented immigration status and states that contacting authorities would result in arrest, detention, and deportation — while the debt to the network would remain and be enforced against the worker's family. The owner offers to 'help' by allowing the worker to pay off the debt more quickly through additional work at a second location.",
                "legal_basis": "Information about immigration enforcement is factually accurate for undocumented workers; the salon owner presents their continued employment as protective of the worker's interests; additional work opportunities are offered as a benefit",
                "sector": "services",
                "corridor": "VN-US",
                "indicator_action_ids": [],
                "red_flag_context": "Immigration status weaponized as a final control mechanism: the worker cannot seek help without triggering their own deportation; debt collection against family in Vietnam is a credible threat; the 'second location' offer increases labor extraction while appearing to be generosity; this completes the trafficking control cycle — debt, documents, surveillance, threats, isolation",
            },
        ],
        "chain_context": "The nail salon exploitation chain has been documented extensively in the US (NYT's 'The Price of Nice Nails' investigation, DOL enforcement actions) and the UK (NCA modern slavery cases involving Vietnamese nationals). The pattern exploits the intersection of migration debt, undocumented status, cash-based businesses where labor violations are difficult to detect, and transnational networks that can enforce debt obligations in the worker's home country. Each element — recruitment services, skills training, tip management, workplace rules, immigration information — appears individually legitimate but creates total control.",
        "emergent_risk": "Transnational service sector trafficking: smuggling debt + training debt + tip confiscation + family-targeted surveillance + immigration threat = worker trapped between unenforceable debt abroad and real threats at home and in the workplace",
        "difficulty": "hard",
        "source_references": [
            "New York Times — The Price of Nice Nails (2015 Investigation)",
            "US Department of Labor — Nail Salon Industry Enforcement Actions",
            "UK National Crime Agency — Vietnamese National Modern Slavery Cases",
            "Polaris Project — Human Trafficking in Illicit Massage, Health, and Beauty Services",
            "Anti-Trafficking Review — Vietnamese Workers in the UK Service Sector",
        ],
        "corridors": ["VN-US", "VN-UK"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["debt bondage", "coercion", "intimidation", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "sector_specific_010",
        "name": "Care and Nursing Home Deskilling and Visa-Tied Exploitation Chain",
        "category": "sector_specific",
        "steps": [
            {
                "id": "ss010_s1",
                "description": "A Filipino registered nurse or an Indian physiotherapist is recruited by an international healthcare staffing agency for a care assistant or personal support worker (PSW) position in the UK or Canada. The agency markets the position as a pathway to professional registration in the destination country, emphasizing that 'bridging programs' will allow the worker to practice at their qualified level within 1-2 years.",
                "legal_basis": "International healthcare recruitment through licensed staffing agencies is a recognized practice under both the UK Health and Care Worker visa pathway and Canada's Temporary Foreign Worker Program; agencies are authorized to recruit internationally for healthcare positions where domestic labor shortages exist",
                "sector": "healthcare",
                "corridor": "PH-UK",
                "indicator_action_ids": [],
                "red_flag_context": "The agency's marketing conflates care assistant work with professional nursing/healthcare practice; the 'bridging program pathway' is technically possible but practically inaccessible for workers in the roles being offered; the worker relocates expecting career progression that is structurally unlikely to materialize",
            },
            {
                "id": "ss010_s2",
                "description": "Upon arrival, the worker discovers that their professional credentials (nursing degree, physiotherapy license) are not recognized by the destination country's regulatory body without passing additional exams, completing supervised practice hours, and paying registration fees totaling $3,000-$8,000. The employer has no obligation to support or fund this process.",
                "legal_basis": "Professional credential recognition is governed by the destination country's regulatory body (NMC in the UK, provincial colleges in Canada); international graduates must meet local standards through assessment and bridging; this is a standard professional regulation framework, not an employer decision",
                "sector": "healthcare",
                "corridor": "IN-CA",
                "indicator_action_ids": [],
                "red_flag_context": "Credential non-recognition traps a qualified professional in a lower-skilled role; the recruitment agency knew the recognition barriers but marketed the position as a pathway; the worker has relocated internationally and cannot practice at their qualified level, losing both their professional identity and their earning capacity",
            },
            {
                "id": "ss010_s3",
                "description": "The worker is employed as a care assistant or PSW in a nursing home at the entry-level wage for that position — significantly below what a registered nurse or qualified therapist would earn. The work involves physically demanding tasks (lifting patients, personal care, cleaning) that underutilize the worker's clinical training. Shifts are 12 hours, often overnight, in understaffed facilities.",
                "legal_basis": "Care assistant compensation is set by the employer within the applicable wage regulations (National Living Wage in the UK; provincial minimum wage in Canada); the worker is employed in the role they accepted; understaffing is a sector-wide challenge addressed through continued recruitment",
                "sector": "healthcare",
                "corridor": "PH-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Professional deskilling: a registered nurse performing care assistant duties at care assistant wages represents a systematic extraction of the worker's education investment without compensation; the nursing home benefits from having a clinically trained worker at a fraction of the cost; the worker's skills atrophy over time, making professional re-registration increasingly difficult",
            },
            {
                "id": "ss010_s4",
                "description": "The worker's visa is tied to the sponsoring employer (UK Health and Care Worker visa with specific Certificate of Sponsorship; or Canadian employer-specific LMIA). Changing employers requires a new sponsorship, which the current employer can delay by not releasing the worker's records or by refusing to provide a reference. The worker is told that 'most care homes won't sponsor a transfer mid-visa.'",
                "legal_basis": "Employer-specific visa sponsorship is the standard framework for both the UK Skilled Worker visa pathway and Canada's TFWP; visa portability rules exist but require a new sponsoring employer; the current employer has no legal obligation to facilitate transfers",
                "sector": "healthcare",
                "corridor": "IN-CA",
                "indicator_action_ids": [],
                "red_flag_context": "Visa tied to the employer creates structural coercion identical to the Kafala system: the worker cannot change employers without risking their immigration status; the employer's informal power to delay transfers through non-cooperation exceeds the formal legal framework; the worker is effectively bound to the sponsoring employer",
            },
            {
                "id": "ss010_s5",
                "description": "The nursing home pays the worker at the entry-level care assistant rate despite assigning them clinical responsibilities (medication administration, wound care, patient assessments) that are normally performed by registered nurses. The facility saves the cost of hiring qualified local nurses by having the internationally-trained worker perform the same tasks at a fraction of the wage, justified by the fact that the worker's credentials are not locally recognized.",
                "legal_basis": "Task delegation within a care facility is managed by the registered manager under CQC (UK) or provincial health authority regulations; the worker performs tasks under supervision as permitted by their care assistant role; the facility maintains required staffing ratios on paper",
                "sector": "healthcare",
                "corridor": "PH-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Below-market wages for above-role work: the worker performs registered nurse duties at care assistant pay, representing both wage theft and regulatory fraud; the credential non-recognition system that was supposed to protect patients is instead being exploited to justify paying qualified workers less; the worker cannot refuse the clinical tasks without jeopardizing their employment and visa status",
            },
        ],
        "chain_context": "The care sector exploitation chain leverages the global healthcare worker shortage and the complexity of professional credential recognition systems. The UK and Canada both actively recruit international healthcare workers to fill domestic shortages, but the gap between recruitment promises and credential recognition reality creates a trapped workforce of overqualified, underpaid workers whose visa status depends on continued employment with the sponsoring facility. The WHO Global Code of Practice on the International Recruitment of Health Personnel specifically warns against this pattern.",
        "emergent_risk": "Systemic healthcare deskilling trap: credential non-recognition + entry-level wages for clinical work + tied visa sponsorship + employer non-cooperation on transfers = qualified professionals performing above-role work at below-market wages with no exit path",
        "difficulty": "hard",
        "source_references": [
            "WHO — Global Code of Practice on the International Recruitment of Health Personnel",
            "UK Migration Advisory Committee — Adult Social Care Workforce Report 2024",
            "UNISON — Migrant Care Workers: Working Conditions Report",
            "Canadian Nurses Association — Internationally Educated Nurses: Barriers to Registration",
            "Kanlungan Filipino Consortium — Healthcare Worker Exploitation in the UK 2024",
            "ILO — Care Economy and Decent Work",
        ],
        "corridors": ["PH-UK", "IN-CA", "PH-CA", "IN-UK", "NP-UK"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["deception", "abuse of position of vulnerability", "coercion"],
            "purpose": ["exploitation", "forced labour"],
        },
    },
]
