"""
Supply chain chains — multi-tier subcontracting, vessel transfers, and broker
networks that obscure employer responsibility and enable exploitation.

Sources: Liberty Shared maritime research, KnowTheChain benchmarks,
BHRRC corporate accountability studies, ILO supply chain due diligence,
Amnesty International corporate indictments, Verité forced labor surveys,
RSPO complaints panel, US DOL ILAB lists, Equidem Gulf labor studies.
"""

CHAINS: list[dict] = [
    {
        "id": "supply_chain_001",
        "name": "Qatar Construction Multi-Tier Subcontracting Cascade",
        "category": "supply_chain",
        "steps": [
            {
                "id": "sc001_s1",
                "description": "The Supreme Committee for Delivery & Legacy awards a stadium construction contract for the Lusail Stadium (capacity 80,000) to a joint venture led by a multinational EPC firm. The JV subcontracts 70% of physical construction to a main contractor such as Salini Impregilo (now Webuild) or Besix Group, under an EPC agreement that specifies cost, schedule, and quality but allocates labor standards compliance to the subcontractor's 'sole responsibility'",
                "legal_basis": "Qatar Law No. 14/2004 (Labour Law) Art. 3 establishes that main contractors are jointly liable for subcontractor wage violations, but enforcement is rare; Qatar Public Works Authority (Ashghal) standard contracts permit tiered subcontracting for registered contractors under Ministerial Decision No. 18/2014",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "First layer of separation: Vinci Construction Grands Projets was indicted by a French court in November 2024 for forced labor at its Qatar sites after Sherpa NGO filed criminal complaints; the indictment named specific Lusail City projects where Vinci's subcontractors retained worker passports and withheld wages, yet Vinci maintained it was 'not the direct employer'",
            },
            {
                "id": "sc001_s2",
                "description": "The main contractor (e.g., Besix Group or HBK Contracting) further subcontracts specialist trades — structural concrete, steel reinforcement, MEP (mechanical/electrical/plumbing) — to three to five smaller Qatari-registered firms such as Al Jaber Engineering, United Development Company subsidiaries, or Redco Construction, each required to hire their own workforce through competitive bidding on fixed-price packages",
                "legal_basis": "Qatar Commercial Companies Law No. 11/2015 Art. 68 permits registered companies to enter subcontracting agreements; ILO Convention C94 (Labour Clauses in Public Contracts, 1949) — which Qatar has not ratified — would require government contracts to include labor protection clauses cascading through subcontract tiers",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Second layer: BHRRC documented in 2023 that competitive bidding pressure on Supreme Committee projects drove subcontractor labor costs to QAR 35-50/day per worker ($9.60-$13.70), forcing subcontractors to house workers in Industrial Area camps in Doha where 12-person rooms were standard; HRW's 2012 report 'Building a Better World Cup' identified this bidding-driven compression as the structural cause of wage theft",
            },
            {
                "id": "sc001_s3",
                "description": "One subcontractor engages a manpower supply company — such as Qatar Manpower Services, Al Mana Manpower, or similar MADLSA-licensed labor suppliers — to provide 200 Nepali and Indian construction workers at a per-worker daily rate of QAR 40-55 ($11-$15), with the labor supplier handling all recruitment, kafala sponsorship under its own company ID, and accommodation at its labor camps in the Industrial Area or Al Sailiya",
                "legal_basis": "Labor supply companies are licensed under Qatar's Ministry of Administrative Development, Labour and Social Affairs (MADLSA) Ministerial Decision No. 8/2005; the kafala (sponsorship) system under Law No. 4/2009 ties workers' legal residence to the labor supplier's sponsorship, not the subcontractor or main contractor they physically work for",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Third layer: workers are now three contractual steps removed from the Supreme Committee or Qatar Foundation client entity; Equidem's 2020 report 'The Cost of Contagion' documented that labor supply companies on Lusail City and Education City projects paid workers QAR 800-1,200/month ($220-$330) while billing subcontractors QAR 1,800-2,400/month ($494-$659) per worker — the 50-60% margin absorbed by housing, food, and profit",
            },
            {
                "id": "sc001_s4",
                "description": "The labor supplier recruits workers through partner agencies registered with Nepal's Department of Foreign Employment (DoFE) in Kathmandu — such as Moonlight Manpower, Galaxy International, or similar firms — and agents registered with India's Protector of Emigrants office in Kerala and Bihar. Agencies charge workers NPR 150,000-350,000 ($1,125-$2,625) in Nepal and INR 80,000-250,000 ($960-$3,000) in India; Nepal's Foreign Employment Act 2064 (2007) caps fees at NPR 10,000 ($75) but enforcement is negligible. The labor supplier's contract with the subcontractor specifies QAR 45/day ($12.36) per worker, from which the supplier deducts QAR 300/month for camp accommodation and QAR 200/month for meals",
                "legal_basis": "Nepal Foreign Employment Act 2064 (2007) s.52 sets maximum recruitment fees at NPR 10,000 (approximately $75); India's Emigration Act 1983 s.22 requires Recruiting Agent registration but does not effectively cap fees. Qatar Ministerial Decision No. 4/2015 prohibits charging workers recruitment fees but applies only to Qatar-based entities, not origin-country agencies",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Workers at the bottom of a four-tier chain carry debt equivalent to 12-24 months' net earnings before arriving; BHRRC's 2023 'Qatar Construction Supply Chain: Migrant Worker Abuse' report documented that 87% of workers interviewed had paid recruitment fees exceeding legal limits by 10-30x, with debt financed through high-interest village moneylenders at 24-36% annual rates",
            },
            {
                "id": "sc001_s5",
                "description": "When 35 Nepali workers on the Al Wakrah Stadium site file wage complaints through Qatar's Ministry of Labour online portal (established under Law No. 13/2017), the labor supplier refers them to the subcontractor, who refers them to the main contractor (Besix-managed JV), who states that labor relations are 'the responsibility of the direct employer as defined under the kafala.' The Wage Protection System (WPS) electronic transfer records show payments to the labor supplier's account, not individual workers, creating an audit trail that ends one tier above the workers",
                "legal_basis": "Qatar Ministerial Decision No. 4/2015 (Wage Protection System) mandates electronic salary payment but permits block transfers to labor supply companies who then distribute to workers; privity of contract under Qatar Civil Code Art. 171 limits each party's liability to its direct contractual counterpart",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Accountability void: Amnesty International's 2024 report on the Vinci Construction indictment documented this exact circular denial pattern on Lusail City projects — the multinational published CSR reports claiming 'zero tolerance for exploitation' and compliance with the Supreme Committee's Workers' Welfare Standards, while workers four tiers below could not identify who employed them or who held their wage arrears of QAR 3,000-8,000 ($823-$2,196) each",
            },
        ],
        "chain_context": "Qatar mega-projects — including the eight 2022 FIFA World Cup stadiums, the Lusail City mixed-use development, the Doha Metro, and Qatar Foundation's Education City — routinely involve four or more contracting tiers. The Supreme Committee for Delivery & Legacy's Workers' Welfare Standards (2014, updated 2016) apply only to Supreme Committee projects and only to entities with direct contractual relationships. HRW's 2012 report 'Building a Better World Cup: Protecting Migrant Workers in Qatar Ahead of FIFA 2022' documented 4-5 tier chains on stadium sites. The French criminal indictment of Vinci Construction Grands Projets (November 2024, filed by Sherpa NGO under French Duty of Vigilance Law No. 2017-399) established that a multinational EPC firm can face criminal liability in its home jurisdiction for forced labor conditions at the bottom of its subcontracting chain — a legal precedent that pierces the contractual separation.",
        "emergent_risk": "Employer erasure through subcontracting: workers recruited with NPR 150,000-350,000 debt in Nepal, employed by a MADLSA-licensed labor supplier paid QAR 45/day per head, three contractual layers below the Supreme Committee — Vinci Construction indictment demonstrates that home-country criminal liability can pierce the chain, but only after years of NGO litigation",
        "difficulty": "hard",
        "source_references": [
            "BHRRC, 'Qatar Construction Supply Chain: Migrant Worker Abuse' (2023) — documenting 87% illegal fee prevalence across Supreme Committee project workers",
            "HRW, 'Building a Better World Cup: Protecting Migrant Workers in Qatar Ahead of FIFA 2022' (Jun 12, 2012) — first systematic mapping of 4-5 tier subcontracting on stadium projects",
            "Amnesty International, 'Vinci Construction: Indictment for Forced Labour in Qatar' (2024) — French court criminal charges under Duty of Vigilance Law No. 2017-399",
            "Equidem, 'The Cost of Contagion: The Human Rights Impacts of COVID-19 on Migrant Workers in the Gulf' (2020) — labor supplier margin analysis and camp condition documentation",
        ],
        "corridors": ["NP-QA", "IN-QA", "BD-QA", "PH-QA"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["abuse of position of vulnerability", "deception"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "supply_chain_002",
        "name": "Thailand Fishing Vessel-to-Vessel Labor Transfer at Sea",
        "category": "supply_chain",
        "steps": [
            {
                "id": "sc002_s1",
                "description": "A Thai fishing vessel owner (pho liang) operating out of Songkhla port contracts with a broker (nai naa) in the border town of Ranong to recruit 15 Myanmar crew members for a deep-sea trawler. The nai naa works through village contacts in Mon State and Tanintharyi Region, promising THB 10,000-15,000/month ($280-$420). Downstream, the vessel's catch enters the supply chain of Thai Union Group (the world's largest canned tuna producer, operating under brands Chicken of the Sea, John West, and Petit Navire) or Charoen Pokphand Foods (CP Foods), Thailand's largest agri-food conglomerate, whose shrimp feed mills in Samut Sakhon province purchase fishmeal processed from trawler bycatch",
                "legal_basis": "Thailand Royal Ordinance on Fisheries B.E. 2558 (2015) s.83 requires crew registration through Port-In Port-Out (PIPO) inspection centers for vessels over 30 gross tonnage; Ministerial Regulation B.E. 2557 (2014) on fishing vessel crew mandates written employment contracts and crew manifests verified at PIPO",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "The Guardian's June 10, 2014 investigation 'Revealed: Asian Slave Labour Producing Prawns for Supermarkets in US, UK' traced CP Foods' shrimp supply chain to fishmeal processed from trawler bycatch caught using forced Myanmar labor; ILO's 2013 report 'Caught at Sea: Forced Labour and Trafficking in Fisheries' documented that 57% of Myanmar fishers in Thai fleet experienced conditions meeting ILO forced labor indicators, with nai naa brokers charging THB 10,000-30,000 ($280-$840) per worker for 'job placement'",
            },
            {
                "id": "sc002_s2",
                "description": "Workers are registered at the Songkhla PIPO center, where inspectors verify crew manifests against vessel registration (Royal Ordinance B.E. 2558 s.81). The trawler clears PIPO inspection and proceeds to deep-sea fishing grounds in the Andaman Sea, beyond Thailand's 200-nautical-mile exclusive economic zone, entering international waters where flag-state enforcement under UNCLOS Art. 94 applies. The vessel's captain (hua naa) holds all workers' documents — seaman's books, Myanmar identity cards, and any work permits — in the wheelhouse safe",
                "legal_basis": "PIPO inspection is mandatory under Fisheries Management Decree B.E. 2558 (2015) s.81-82 for all commercial vessels departing Thai ports; deep-sea operations in international waters are governed by flag-state obligations under UNCLOS Art. 94; ILO C188 Work in Fishing Convention (2007) — ratified by Thailand in January 2019 — requires written work agreements specifying duration, but implementing regulations took effect only in 2020",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Once beyond Thailand's EEZ, Thai labor law enforcement effectively ends; PIPO registration creates a paper trail suggesting compliance but does not extend monitoring to open ocean; ILO's 'Caught at Sea' (2013) documented that 76% of sampled vessels held crew documents, and the Environmental Justice Foundation (EJF) found in 2015 that PIPO inspections averaged 15 minutes per vessel, insufficient to interview individual crew members privately",
            },
            {
                "id": "sc002_s3",
                "description": "At sea 200+ nautical miles from Songkhla, a refrigerated carrier vessel (reefer) — often Panamanian or Honduran-flagged to exploit flag-of-convenience registration under those countries' open registries — approaches to collect the catch via at-sea transshipment. During the 4-6 hour transfer of fish from the trawler's hold to the reefer's cold storage, the hua naa transfers 5 crew members to the reefer, which then moves them to a second trawler (owned by the same pho liang or a business associate) that has lost crew to injury, desertion in a foreign port (Pattani or Indonesian waters), or death at sea",
                "legal_basis": "At-sea transshipment of catch is a legal commercial practice regulated under RFMO (Regional Fisheries Management Organization) frameworks; Thailand's Fisheries Management Decree B.E. 2558 s.92 requires transshipment reporting but implementing regulations focus on catch volume documentation, not crew transfers between vessels",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Crew transfer at sea bypasses all port-based labor protections; EJF's report 'Pirates and Slaves: Illegal Fishing and Human Trafficking in the Thai Fishing Industry' documented that transshipment-linked crew transfers occurred on 32% of monitored long-distance trawlers; workers are moved to a vessel they did not sign onto, with a hua naa they do not know, with no PIPO record of the transfer — the original crew manifest at Songkhla still lists them as aboard the first vessel",
            },
            {
                "id": "sc002_s4",
                "description": "The second trawler continues fishing for 4-6 months without returning to port, operating in waters between the Andaman Sea and the South China Sea. The transferred workers have no documents (held by the first vessel's hua naa, now hundreds of miles away), no record of their current vessel assignment at any PIPO center, and receive no wages because the nai naa in Ranong tells the pho liang that 'payment is settled at the end of the season through the broker's accounts.' Workers eat fish they catch and rice supplied by the reefer. When the vessel finally returns to Samut Sakhon's Mahachai district for offloading, the catch is sold to fishmeal processors that supply CP Foods' shrimp feed mills and Thai Union's canning operations",
                "legal_basis": "Extended fishing voyages of 3-12 months are commercially normal for Thai distant-water fleets; wage settlement through shore-based nai naa brokers is a documented payment arrangement in the Thai fishing industry described in the ILO's 2013 'Caught at Sea' survey of 596 fishers; Samut Sakhon's Mahachai district is Thailand's largest seafood processing hub, handling 60% of the country's shrimp production",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Workers are effectively disappeared from regulatory oversight: no government agency knows they changed vessels, no PIPO center has recorded the transfer, the original Songkhla crew manifest is for a different vessel, and wages are deferred indefinitely through a nai naa the workers cannot contact from sea. Liberty Shared's 2023 report 'Out of Sight: Modern Slavery in Pacific Supply Chains' documented identical vessel-transfer patterns in Thai and Taiwanese distant-water fleets, with average wage theft of $3,000-$8,000 per worker per voyage",
            },
        ],
        "chain_context": "Thailand's PIPO reforms (Fisheries Management Decree B.E. 2558, 2015) and ILO C188 ratification (January 2019) were designed to track fishing crews, but vessel-to-vessel transfers at sea create a monitoring gap no port-based system can close. The transshipment of fish is legal and commercially necessary — Thai Union Group (TUF, SET-listed, $4.1B revenue 2023) and CP Foods (CPF, SET-listed, $17B revenue 2023) depend on it — but the simultaneous transfer of crew members, undocumented and without consent, converts a legitimate supply chain operation into a mechanism for moving workers beyond regulatory reach. The Guardian's 2014 investigation traced this chain from Myanmar village recruitment through reefer transshipment to branded shrimp products on Walmart, Costco, Tesco, and Carrefour shelves. The US DOL placed Thai fish and shrimp on its 'List of Goods Produced by Child Labor or Forced Labor' (updated 2024), citing these supply chain dynamics.",
        "emergent_risk": "Regulatory evasion through at-sea transfer: PIPO-registered workers transferred between vessels without documentation via flag-of-convenience reefers, moved beyond Thai EEZ monitoring, wages deferred through Ranong nai naa brokers — workers are untraceable while their catch enters Thai Union and CP Foods branded supply chains reaching US, UK, and EU supermarket shelves",
        "difficulty": "expert",
        "source_references": [
            "ILO, 'Caught at Sea: Forced Labour and Trafficking in Fisheries' (2013) — survey of 596 fishers, 57% experiencing forced labor indicators, documenting nai naa broker system and wage deferral patterns",
            "The Guardian, 'Revealed: Asian Slave Labour Producing Prawns for Supermarkets in US, UK' (Jun 10, 2014) — tracing CP Foods/Thai Union supply chains to trawlers using forced Myanmar labor",
            "EJF, 'Pirates and Slaves: Illegal Fishing and Human Trafficking in the Thai Fishing Industry' (2015) — documenting 32% transshipment-linked crew transfer rate and 15-minute average PIPO inspections",
            "Liberty Shared, 'Out of Sight: Modern Slavery in Pacific Supply Chains' (2023) — vessel transfer patterns in Thai and Taiwanese distant-water fleets with $3,000-$8,000 per-worker wage theft documentation",
        ],
        "corridors": ["MM-TH", "KH-TH", "LA-TH"],
        "palermo_elements": {
            "act": ["transfer", "harbouring", "receipt of persons"],
            "means": ["deception", "coercion", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "supply_chain_003",
        "name": "Jordan QIZ Free Trade Zone Labor Broker Chain",
        "category": "supply_chain",
        "steps": [
            {
                "id": "sc003_s1",
                "description": "A major US apparel brand — Gap Inc., Walmart, or Target Corporation — places a $12M seasonal garment order with Classic Fashion Apparel Industry Ltd. or a comparable factory operating in the Al Hassan Industrial Zone (Irbid Governorate, Jordan), one of 13 Qualified Industrial Zones authorized under the 1996 US-Jordan-Israel QIZ agreement. The QIZ designation grants duty-free access to the US market provided at least 8% of product content originates from Israel. Jordan Ministry of Labour data (2022) shows 70,000 workers in QIZs, of whom only 29.2% are Jordanian nationals and 75% are female, predominantly from Bangladesh, Sri Lanka, and Vietnam",
                "legal_basis": "QIZ factories operate under the US-Jordan Free Trade Agreement (2001) Art. 6, which includes labor provisions requiring adherence to ILO core labor standards; the QIZ agreement (1996) between US, Jordan, and Israel establishes duty-free qualifying criteria. Jordan Labour Code No. 8/1996 Art. 12 governs employment contracts, and Regulation No. 90/2009 specifically addresses garment sector working conditions",
                "sector": "manufacturing",
                "corridor": "BD-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Brand supply chain audits by firms such as WRAP (Worldwide Responsible Accredited Production) or BSCI (Business Social Compliance Initiative) focus on factory-floor conditions — fire exits, working hours, minimum wage payment — but do not trace the recruitment chain that brought workers from Dhaka, Colombo, or Hanoi to the Irbid factory. ILO Better Work Jordan's 2022 compliance assessment found 67% of factories had at least one non-compliance on recruitment fee reimbursement",
            },
            {
                "id": "sc003_s2",
                "description": "The QIZ factory at Al Hassan Industrial Zone or Ad-Dulayl Industrial Park contracts with a Jordanian-registered outsourcing company (e.g., S&H Global, Jerash Garments, or similar MoL-licensed firms) to supply 500 Bangladeshi and Sri Lankan garment workers. The outsourcing company handles BMET (Bureau of Manpower, Employment and Training, Bangladesh) clearance, Jordan MoL work permit applications, dormitory management at company-owned housing blocks within the QIZ perimeter, and payroll at JOD 220/month ($310) — Jordan's minimum wage for garment sector foreign workers set under Minimum Wage Committee Decision 2017",
                "legal_basis": "Labor outsourcing companies are licensed under Jordan Ministry of Labour Regulation No. 43/2015 governing private employment agencies; QIZ factories commonly use outsourcing to manage foreign workforce administration. Jordan MoL Instruction No. 1/2013 requires outsourcing companies to maintain 1:1 Jordanian-to-foreign worker ratios in their registered workforce, though compliance is rarely enforced in QIZs",
                "sector": "manufacturing",
                "corridor": "BD-JO",
                "indicator_action_ids": [],
                "red_flag_context": "The outsourcing company becomes the de facto employer but is invisible in the brand's supply chain mapping — the brand's purchase order names the QIZ factory, not the outsourcing company. Verité's 2011 report 'Forced Labor in the Jordanian Garment Sector' documented that outsourcing companies in Al Hassan and Ad-Dulayl controlled dormitory access, confiscated passports in 31% of cases surveyed, and imposed curfews on female workers",
            },
            {
                "id": "sc003_s3",
                "description": "The outsourcing company subcontracts recruitment to a BMET-registered agency in Dhaka's Uttara district (such as Delta Manpower, International Recruiting Services, or similar) that operates a network of village-level recruiters (dalals) in Comilla, Gazipur, and Narayanganj districts. The Dhaka agency charges workers BDT 250,000-500,000 ($2,300-$4,600) for placement — 3-7x the BMET-regulated maximum of BDT 84,000 ($775) set under Bangladesh Overseas Employment and Migrants Act 2013 s.20. Sri Lankan workers are recruited through SLBFE (Sri Lanka Bureau of Foreign Employment)-registered agencies in Colombo at LKR 200,000-400,000 ($625-$1,250), and Vietnamese workers through DOLAB (Department of Overseas Labour)-registered agencies in Hanoi at 80-120 million VND ($3,200-$4,800)",
                "legal_basis": "Bangladesh Overseas Employment and Migrants Act 2013 s.20 caps recruitment fees at BDT 84,000 (approximately $775); BMET registration under s.15 requires agencies to maintain fee transparency. Sri Lanka's SLBFE Act No. 21/1985 regulates agencies but does not effectively cap sub-agent fees. Vietnam's Law on Vietnamese Workers Working Abroad Under Contract (2006, amended 2020) Art. 20 specifies DOLAB-approved fee schedules",
                "sector": "manufacturing",
                "corridor": "BD-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Fee extraction happens at the dalal level in villages 300+ km from BMET's Dhaka office, entirely beyond enforcement reach. KnowTheChain's 2022 'Apparel and Footwear Benchmark' scored Gap Inc. 45/100 and Target 36/100 on recruitment fee transparency, noting neither company could demonstrate verified fee reimbursement programs reaching origin-country sub-agents. Workers finance fees through village moneylenders (mohajons) at 30-60% annual interest",
            },
            {
                "id": "sc003_s4",
                "description": "Workers arrive at the Al Hassan QIZ factory dormitory with $2,300-$4,800 in debt; the outsourcing company deducts JOD 50/month ($70) from their JOD 220/month ($310) gross salary for 'dormitory, food, and administrative fees,' leaving workers with JOD 170/month ($240). After remittances home of JOD 80/month ($113) to service debt interest, net retained earnings are approximately $127/month. At this rate, a worker with median BDT 350,000 ($3,225) debt requires 25+ months to repay — on a 24-month standard contract. Workers who attempt early termination forfeit unpaid wages under the outsourcing company's contract clause requiring 90-day notice",
                "legal_basis": "Jordan Labour Code No. 8/1996 Art. 47 permits deductions for employer-provided accommodation and meals provided they do not exceed 'reasonable cost'; MoL Instruction No. 9/2018 for garment sector caps dormitory deductions at JOD 20/month but enforcement data is not publicly available. Jordan's Regulation No. 90/2009 on garment sector conditions nominally prohibits passport confiscation",
                "sector": "manufacturing",
                "corridor": "BD-JO",
                "indicator_action_ids": [],
                "red_flag_context": "The brand's CSR auditor (WRAP or BSCI) sees JOD 220/month wage payments compliant with the garment sector minimum wage; the outsourcing company's JOD 50 deductions and the dalal's BDT 250,000-500,000 recruitment fees are outside audit scope. ILO Better Work Jordan's 2022 assessment found 89% of factories used outsourcing companies for foreign workers, and the National Labour Committee's 2006 exposé of Al Hassan QIZ documented Bangladeshi workers earning $0.25/hour after deductions — conditions that prompted Gap Inc.'s first remediation commitment but did not address the structural fee chain",
            },
        ],
        "chain_context": "The QIZ model connects US consumer markets to Jordanian factories through preferential trade agreements (US-Jordan FTA 2001, QIZ Protocol 1996). Jordan's 13 QIZs employed 70,000 workers in 2022 (MoL data), of whom 70.8% were foreign nationals — predominantly Bangladeshi, Sri Lankan, Vietnamese, and Indian women. Each link — brand order (Gap/Walmart/Target), factory production (Al Hassan QIZ), outsourcing company management (MoL-licensed), Dhaka agency recruitment (BMET-registered), village dalal fee collection — is individually licensed or registered. But the chain creates a structure where BDT 250,000-500,000 recruitment debt incurred in Comilla district villages is invisible to WRAP auditors inspecting factory floors in Irbid Governorate, and workers trapped by debt that outlasts their 24-month contracts have no pathway to the entity (the US brand placing $12M orders) with the economic power to reimburse fees and change conditions.",
        "emergent_risk": "Audit-proof exploitation: brand audits see JOD 220/month wage compliance at the factory; outsourcing company deductions reduce net pay to JOD 170; BMET-registered agency's dalal network charges 3-7x legal fee caps in villages 300km from enforcement — debt is incurred five links from the entity with purchasing power, in a jurisdiction (rural Bangladesh) no supply chain audit reaches",
        "difficulty": "expert",
        "source_references": [
            "Verité, 'Forced Labor in the Jordanian Garment Sector' (2011) — documenting passport confiscation (31%), dormitory curfews, and outsourcing company control in Al Hassan and Ad-Dulayl QIZs",
            "ILO Better Work Jordan, 'Annual Compliance Assessment Report' (2022) — 67% recruitment fee non-compliance, 89% outsourcing company usage for foreign workers",
            "KnowTheChain, 'Apparel and Footwear Benchmark' (2022) — Gap Inc. scored 45/100, Target 36/100 on recruitment fee transparency and remediation",
            "National Labour Committee, 'US-Jordan Free Trade Agreement: Descending into Forced Labor?' (2006) — first exposé of $0.25/hour effective wages after deductions for Bangladeshi workers in Al Hassan QIZ",
        ],
        "corridors": ["BD-JO", "LK-JO", "IN-JO", "PH-JO"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["deception", "debt bondage", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "supply_chain_004",
        "name": "UK/EU Agricultural Gang Labour System",
        "category": "supply_chain",
        "steps": [
            {
                "id": "sc004_s1",
                "description": "A major UK supermarket chain — Tesco, Sainsbury's, or Marks & Spencer — contracts with a first-tier produce supplier (e.g., G's Fresh, Driscolls, or Greenyard) for year-round supply of fresh vegetables (leeks, brassicas, salad crops) grown across Lincolnshire, Norfolk, and Cambridgeshire. The supplier subcontracts harvest and packing labor to a Gangmasters and Labour Abuse Authority (GLAA) licensed labor provider holding a valid license under Gangmasters (Licensing) Act 2004 s.6, verified on the GLAA public register",
                "legal_basis": "UK Gangmasters (Licensing) Act 2004 s.6 requires GLAA licensing for all labor providers supplying workers to agriculture, horticulture, shellfish gathering, and associated food processing/packaging; operating without a license is a criminal offense under s.12 (up to 10 years' imprisonment). UK Modern Slavery Act 2015 s.54 requires companies with turnover exceeding £36M to publish annual supply chain transparency statements — Tesco, Sainsbury's, and M&S all publish s.54 statements covering their agricultural supply chains",
                "sector": "agriculture",
                "corridor": "EU-UK",
                "indicator_action_ids": [],
                "red_flag_context": "GLAA license provides a compliance shield — the supermarket and farm point to GLAA License No. [XXXX] as evidence of due diligence — but the GLAA itself identified in its 2022-2023 Annual Report that licensed providers sometimes subcontract actual worker management to unlicensed operators who structure arrangements as 'transport,' 'accommodation,' or 'logistics' services to circumvent licensing requirements",
            },
            {
                "id": "sc004_s2",
                "description": "The GLAA-licensed labor provider subcontracts 'transport and logistics coordination' to a smaller company registered at Companies House as a transport/logistics firm, run by a Romanian or Lithuanian national who organizes worker recruitment via Facebook groups and WhatsApp networks targeting communities in Bacău/Botoșani (Romania), Šiauliai (Lithuania), or Plovdiv (Bulgaria). This coordinator manages minibus transport from worker accommodation in Wisbech, Boston, or King's Lynn to farm sites across the Fens, and assigns daily crew rotas",
                "legal_basis": "Transport and logistics subcontracting does not require a GLAA license if the subcontractor is not directly 'supplying' or 'procuring' labor within the meaning of Gangmasters (Licensing) Act 2004 s.4(1-3); the legal distinction between 'transport coordination' and 'labor provision' was identified as a regulatory gap in the GLAA's 2019 strategic assessment. Wisbech was identified by the National Crime Agency as a labor exploitation hotspot in its 2018 NCA Strategic Assessment",
                "sector": "agriculture",
                "corridor": "EU-UK",
                "indicator_action_ids": [],
                "red_flag_context": "The transport coordinator is effectively a gangmaster — controlling which workers get shifts, providing the only available transport to remote farm sites, managing accommodation assignments — but operates without a GLAA license by structuring the arrangement as logistics. FLEX (Focus on Labour Exploitation) documented this exact licensing gap in its 2017 report 'Shaky Foundations: Labour Exploitation in London's Construction Sector' and subsequent agricultural sector analysis, noting that the GLAA's 400 license holders represent only a fraction of the labor provision ecosystem",
            },
            {
                "id": "sc004_s3",
                "description": "The transport coordinator recruits Romanian, Bulgarian, and Lithuanian workers through social media contacts in home regions, promising GBP 10-12/hour agricultural work compliant with the National Minimum Wage (£10.42/hour from April 2023, £11.44 from April 2024). Workers arrive in the UK and are housed in overcrowded HMO (House in Multiple Occupation) properties in Wisbech or Boston — towns where the Fenland District Council and Boston Borough Council have documented severe HMO overcrowding — managed by the coordinator or associates. The coordinator charges GBP 70-80/week per bed in rooms shared by 4-6 workers, in properties that may not hold required HMO licenses under Housing Act 2004 s.61",
                "legal_basis": "Renting rooms to workers is a standard landlord-tenant arrangement; Housing Act 2004 s.61 requires HMO licensing for properties housing 5+ people from 2+ households; accommodation charges are lawful if tenants have genuine choice and charges are not excessive under Employment Rights Act 1996 s.13 (unlawful deductions)",
                "sector": "agriculture",
                "corridor": "EU-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Workers depend on the coordinator for housing, transport, and work allocation — a triple dependency the Morecambe Bay cockle pickers case (R v Lin Liang Ren [2006], 23 Chinese workers drowned on Feb 5, 2004) was supposed to prevent through the Gangmasters Licensing Act. The DJ Houghton Chickens case (2012 prosecution, Lithuanian workers exploited in Norfolk poultry catching) demonstrated that GLAA licensing alone could not reach exploitation structured through subcontracted housing and transport. Accommodation fees of GBP 70-80/week consume 30-40% of net earnings, creating housing dependency that mirrors kafala sponsorship",
            },
            {
                "id": "sc004_s4",
                "description": "Workers are driven to farm sites each morning in the coordinator's minibus, departing at 05:00 from Wisbech HMO properties; a daily transport fee of GBP 7-10 is deducted from their daily earnings, plus GBP 4-6 for 'PPE hire and equipment.' Workers who question deductions or request payslips are told they will 'not be picked up tomorrow,' ending their access to both work and the GBP 70-80/week accommodation tied to the coordinator. At GBP 11.44/hour NMW for an 8-hour day (GBP 91.52 gross), daily deductions of GBP 11-16 reduce effective hourly pay to GBP 9.44-9.82 — below National Minimum Wage. The GLAA-licensed provider above has no visibility into these deductions because its contract with the 'transport coordinator' is a flat-rate logistics fee",
                "legal_basis": "Transport charges to remote agricultural sites are widespread practice; Employment Rights Act 1996 s.13 prohibits unlawful deductions from wages unless the worker has given prior written consent; Health and Safety at Work etc. Act 1974 s.9 requires employers to provide PPE free of charge — but the coordinator claims to be a 'transport provider,' not the employer, creating ambiguity about whose s.9 obligation applies",
                "sector": "agriculture",
                "corridor": "EU-UK",
                "indicator_action_ids": [],
                "red_flag_context": "The coordinator controls all three necessities — housing (GBP 70-80/week), transport (GBP 7-10/day), and daily work allocation — through a single relationship; the supermarket's Modern Slavery Act s.54 statement references GLAA licensing of its first-tier labor provider but does not extend to the unlicensed coordinator. The GLAA's 2022-2023 Annual Report documented 1,160 potential victims identified through GLAA operations in the agricultural sector, with 72% involving exactly this pattern of accommodation-transport-work bundling by unlicensed intermediaries below GLAA-licensed entities",
            },
        ],
        "chain_context": "The UK Gangmasters (Licensing) Act 2004 was enacted as a direct response to the Morecambe Bay disaster of February 5, 2004, in which 23 Chinese cockle pickers drowned in rising tides while working under gangmaster Lin Liang Ren (convicted of 21 counts of manslaughter, R v Lin Liang Ren [2006]). The Act created the GLA (renamed GLAA in 2017 after the Immigration Act 2016 expanded its powers). But the layered structure — supermarket (Tesco/Sainsbury's/M&S), first-tier supplier, GLAA-licensed provider, unlicensed 'transport coordinator,' workers — allows exploitation to persist below the licensed entity. The 2015 UK Modern Slavery Act s.54 transparency requirement covers companies with revenue exceeding £36M, but Tesco's and Sainsbury's published s.54 statements cite GLAA licensing as sufficient due diligence for agricultural supply chains without investigating below the license holder. The DJ Houghton Chickens prosecution (2012, Lithuanian workers in Norfolk poultry processing) and the Kent gangmaster operations documented in GLAA Operation Regar (2017) both involved exploitation structured through subcontracted accommodation and transport that fell outside the GLAA license scope.",
        "emergent_risk": "Below-the-license exploitation: GLAA License No. [XXXX] provides due diligence cover for the supermarket's Modern Slavery Act s.54 statement while an unlicensed coordinator in Wisbech controls housing (GBP 70-80/week), transport (GBP 7-10/day), and work allocation — workers pay 40-50% of earnings in deductions to a single gatekeeper operating in the regulatory gap between 'transport provider' and 'gangmaster'",
        "difficulty": "hard",
        "source_references": [
            "GLAA, 'Annual Report and Accounts 2022-2023' (2023) — 1,160 potential victims in agriculture, 72% involving accommodation-transport-work bundling by unlicensed intermediaries",
            "FLEX (Focus on Labour Exploitation), 'Gangmaster Licensing Gaps in Agriculture and Food Processing' (2017) — documenting transport/logistics structuring to circumvent GLAA licensing",
            "R v Lin Liang Ren [2006] — Morecambe Bay cockle pickers case: 23 Chinese workers drowned Feb 5, 2004; conviction of gangmaster for 21 counts manslaughter, precipitating Gangmasters (Licensing) Act 2004",
            "DJ Houghton Chickens Ltd prosecution (2012) — Lithuanian workers exploited in Norfolk poultry catching, first major GLAA enforcement action demonstrating subcontracted exploitation below licensed entities",
        ],
        "corridors": ["EU-UK", "RO-UK", "BG-UK", "LT-UK"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["abuse of position of vulnerability", "coercion"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "supply_chain_005",
        "name": "US Meat Processing Staffing Agency Sub-Chain",
        "category": "supply_chain",
        "steps": [
            {
                "id": "sc005_s1",
                "description": "A major US meat processor — Tyson Foods (NYSE: TSN, $53B revenue 2023), JBS USA (subsidiary of JBS S.A., world's largest meat company), or Perdue Farms — contracts with a staffing agency such as Aerotek, Elwood Staffing, or a regional workforce solutions company to fill 300 line worker positions at a processing plant in Springdale, Arkansas (Tyson HQ region), Greeley, Colorado (JBS), or Gainesville, Georgia (poultry corridor). The staffing agency bills the processor at $17-20/hour per worker and pays workers $12-14/hour, retaining the $4-6 margin to cover payroll administration, workers' compensation insurance, and profit",
                "legal_basis": "Staffing agencies are licensed under state employment agency laws (e.g., Arkansas Code § 11-11-101 et seq.); US Fair Labor Standards Act (FLSA) joint employer doctrine (29 CFR § 791.2) establishes that both the staffing agency and the worksite employer can be jointly liable for wage violations, but DOL enforcement focuses on direct employers. The US DOL's 2023 investigations into child labor at Tyson and JBS supplier facilities were conducted under FLSA s.12(a) (oppressive child labor provisions)",
                "sector": "food_processing",
                "corridor": "GT-US",
                "indicator_action_ids": [],
                "red_flag_context": "The processor avoids direct employment obligations — benefits, union exposure (UFCW organizing), OSHA injury recordkeeping on its own logs — by routing workers through staffing intermediaries. The US DOL's February 2023 investigation found that Packers Sanitation Services Inc. (PSSI), a sanitation contractor to JBS and Tyson plants in 8 states, employed at least 102 children aged 13-17 in hazardous meatpacking sanitation work — demonstrating that staffing/contractor intermediaries in US meat processing create the same visibility gaps as Gulf subcontracting",
            },
            {
                "id": "sc005_s2",
                "description": "The staffing agency subcontracts its Central American worker recruitment pipeline to a smaller sub-agency operated by a Guatemalan-American staffing recruiter based in Gainesville, Georgia or Springdale, Arkansas — cities with 30-40% Latino populations directly serving local Tyson/JBS/Mar-Jac Poultry plants. The sub-agency recruiter is paid a per-head bounty of $400-600 for each worker placed and retained for 90 days; the sub-agency specializes in recruiting recent immigrants and asylum seekers from Guatemala's western highlands (Huehuetenango, San Marcos, Quetzaltenango departments) and Honduras's northern corridor",
                "legal_basis": "Recruitment subcontracting and referral fee arrangements between staffing agencies are standard in the US staffing industry (American Staffing Association model contracts); per-placement fees incentivize volume recruitment and are not regulated under FLSA. The sub-agency may or may not hold its own state staffing license depending on whether it is classified as a 'recruiter' or 'referral service'",
                "sector": "food_processing",
                "corridor": "GT-US",
                "indicator_action_ids": [],
                "red_flag_context": "Per-head bounty of $400-600 creates incentive to recruit vulnerable workers unlikely to leave regardless of conditions; Centro de los Derechos del Migrante (CDM) documented in its 2020 report 'Recruitment Revealed' that sub-agency recruiters in US meat processing corridors systematically targeted asylum seekers with pending cases, knowing that work authorization tied to asylum processing created dependency. DOJ's 2021 prosecution of a Georgia-based recruitment operation supplying workers to poultry plants revealed per-head payments of $300-500 to village-level reclutadores in Guatemala",
            },
            {
                "id": "sc005_s3",
                "description": "The sub-agency recruiter works with a reclutador (labor contractor) in Guatemala City or Huehuetenango who identifies workers in rural departments — particularly indigenous K'iche' and Mam communities in the western highlands — and offers to arrange travel, coyote (border crossing) logistics through established routes via Tapachula (Mexico) and the Rio Grande Valley sector, and guaranteed US employment for a fee of $8,000-15,000, payable through a salary deduction plan of $200-300/week once the worker starts earning. The reclutador may also hold a lien on the worker's family land or house title as collateral, notarized at a local Guatemalan notary",
                "legal_basis": "International labor contractors provide migration facilitation services; fee repayment through payroll assignment is structured as a private loan agreement under Guatemalan civil law (Código Civil Art. 1942, contrato de mutuo). The Trafficking Victims Protection Act (TVPA, 22 U.S.C. § 7102(11)) defines 'debt bondage' as the status of a debtor arising from a pledge by the debtor of personal services as a security for debt, but enforcement requires identifying the US-side entity enforcing the debt",
                "sector": "food_processing",
                "corridor": "GT-US",
                "indicator_action_ids": [],
                "red_flag_context": "The reclutador's fee of $8,000-15,000 — often financed by mortgaging family milpa (corn field) land to village prestamistas (moneylenders) at 3-5% monthly interest — creates debt bondage before the worker reaches the US. US DOL's 2024 'List of Goods Produced by Child Labor or Forced Labor' includes Guatemalan-sourced labor in US food processing among its documented forced labor supply chains. The salary deduction plan means the sub-agency, reclutador, and prestamista jointly control the worker's earnings for 12-24 months",
            },
            {
                "id": "sc005_s4",
                "description": "Workers arrive at the Tyson/JBS/Perdue plant in Arkansas, Georgia, or Alabama owing $8,000-15,000 to the Guatemalan reclutador, with salary deductions of $200-300/week routed through the sub-agency recruiter to the reclutador via remittance services (Western Union, Intermex, or direct transfer). Workers earn $12-14/hour for 45-55 hour weeks ($540-$770 gross weekly) in refrigerated kill-floor or deboning line conditions with documented OSHA injury rates of 5.6 per 100 workers (BLS 2022) — 2x the manufacturing average. Workers cannot leave because the sub-agency controls their address for ICE check-in (asylum cases with EOIR Immigration Court), the reclutador's agent in Guatemala threatens the family's mortgaged land, and USCIS work authorization is tied to the employer listed on the I-765 EAD application",
                "legal_basis": "Salary deductions for loan repayments are legal if voluntarily agreed; USCIS Employment Authorization Documents (EADs) under asylum pending status (8 CFR § 274a.12(c)(8)) do not restrict employer but workers believe they are employer-tied; TVPA 22 U.S.C. § 7102(11) prohibits debt bondage but requires DOJ prosecution through US Attorneys' offices with limited capacity — DOJ reported only 14 federal labor trafficking prosecutions in FY2023",
                "sector": "food_processing",
                "corridor": "GT-US",
                "indicator_action_ids": [],
                "red_flag_context": "Triple lock: $8,000-15,000 debt to Guatemalan reclutador secured by family land, immigration status dependency on sub-agency address for EOIR check-ins, and perceived (if legally inaccurate) EAD employer-tying. The meat processor's supply chain audit sees a licensed staffing agency; USDA FSIS inspectors at the plant check food safety, not labor conditions. The PSSI child labor case (DOL enforcement action, Feb 2023) confirmed that 102+ children worked cleaning JBS and Tyson plant equipment through exactly this staffing sub-chain structure, establishing that the processor's 'we don't employ them directly' defense does not eliminate FLSA joint-employer liability",
            },
        ],
        "chain_context": "US meat processing — a $230B industry dominated by Tyson Foods, JBS USA, Cargill, and National Beef — has shifted to staffing agency and subcontractor models that create plausible deniability for major processors. The chain — processor (Tyson/JBS), staffing agency (Aerotek/Elwood), sub-agency recruiter (Gainesville/Springdale-based), Guatemalan reclutador, worker — mirrors the subcontracting cascade in Gulf construction but operates within US borders. The PSSI/DOL enforcement action (February 2023) — in which Packers Sanitation Services Inc. was found to have employed 102+ children aged 13-17 cleaning equipment at JBS and Tyson plants in 8 states, resulting in $1.5M in penalties — demonstrated that US processors' staffing intermediaries harbor the same exploitation risks as Gulf kafala chains. The US DOL's 2024 'List of Goods Produced by Child Labor or Forced Labor' includes US food processing products linked to forced labor recruitment from Guatemala and Honduras.",
        "emergent_risk": "Domestic supply chain trafficking: Tyson/JBS/Perdue use staffing agencies to access workers recruited through $8,000-15,000 debt-creating Guatemalan reclutadores who hold liens on family land; ICE/EOIR address dependency replaces passport confiscation as the mobility lock; FLSA joint employer doctrine theoretically reaches the processor but DOJ prosecuted only 14 federal labor trafficking cases in FY2023",
        "difficulty": "expert",
        "source_references": [
            "US DOL, 'List of Goods Produced by Child Labor or Forced Labor' (2024 update) — including Guatemalan-sourced forced labor in US food processing supply chains",
            "Centro de los Derechos del Migrante (CDM), 'Recruitment Revealed: Fundamental Flaws in the H-2 Temporary Worker Program' (2020) — sub-agency targeting of asylum seekers in US meat processing corridors",
            "US DOL Wage and Hour Division, 'Packers Sanitation Services Inc. (PSSI) Enforcement Action' (Feb 2023) — 102+ children aged 13-17 at JBS/Tyson supplier plants in 8 states, $1.5M penalties",
            "Polaris Project, 'Labor Trafficking in the US: A Closer Look at Temporary Work Visas' (2022) — documenting staffing sub-chain patterns in meat/poultry processing across Arkansas, Georgia, Alabama corridors",
        ],
        "corridors": ["GT-US", "HN-US", "MX-US", "SV-US"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["debt bondage", "coercion", "intimidation"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "supply_chain_006",
        "name": "Malaysia Palm Oil Plantation Labor Cascade",
        "category": "supply_chain",
        "steps": [
            {
                "id": "sc006_s1",
                "description": "A European consumer goods corporation (Unilever, Nestlé, or Procter & Gamble) sources certified sustainable palm oil through a Malaysian refinery operated by Wilmar International (world's largest palm oil trader, processing 45% of global palm oil) or Sime Darby Oils (subsidiary of Sime Darby Plantation Berhad, Bursa Malaysia-listed). The refinery holds RSPO (Roundtable on Sustainable Palm Oil) Supply Chain Certification under the Mass Balance or Segregated model and undergoes annual third-party audits by accredited certification bodies (e.g., BSI Group, TÜV Rheinland). Crude palm oil is aggregated from dozens of plantation companies and independent smallholders across Sabah and Sarawak, Borneo",
                "legal_basis": "RSPO Principles & Criteria (2018 revision) Principle 6 ('Responsible Consideration of Employees and of Individuals and Communities Affected by Growers and Mills') Criterion 6.1 requires no forced or trafficked labor and no child labor; RSPO Supply Chain Certification Standard (2017, updated 2020) requires traceability to mill level but not to individual plantation or smallholder. Malaysia Sustainable Palm Oil (MSPO) certification under Malaysian Standard MS 2530:2013 is mandatory since January 2020",
                "sector": "agriculture",
                "corridor": "ID-MY",
                "indicator_action_ids": [],
                "red_flag_context": "RSPO suspended Sime Darby Plantation Berhad (the world's largest palm oil company by planted area, 580,000 hectares) in 2020 over forced labor indicators on its estates including passport retention and below-minimum-wage payment; Amnesty International's 2016 report 'The Great Palm Oil Scandal' documented forced labor in Wilmar International's Indonesian and Malaysian supply chain. RSPO audits assess refinery and large plantation company operations but structurally cannot trace labor conditions to the smallholder and contractor level where 40% of Malaysian palm oil originates",
            },
            {
                "id": "sc006_s2",
                "description": "A mid-size plantation company holding 15,000 hectares in Sabah's Sandakan and Kinabatangan districts — such as Felda Global Ventures (FGV Holdings Berhad, Bursa Malaysia-listed, managing 350,000+ hectares of Felda settler schemes), IOI Corporation, or Kuala Lumpur Kepong (KLK) — supplies CPO (crude palm oil) to Wilmar's or Sime Darby's refinery. The company directly employs 200 Malaysian supervisors and administrative staff under full Employment Act 1955 contracts but relies on a labor contractor registered with Malaysia's Immigration Department under the Outsourcing Company Registration System to supply 800 Indonesian and Filipino harvest and plantation maintenance workers",
                "legal_basis": "Malaysia Employment Act 1955 s.33A establishes that the 'principal employer' (the plantation company) is responsible for wages of workers supplied by a contractor, but enforcement requires the worker to file a complaint with the Labour Department, which is impractical on remote Sabah estates 100+ km from the nearest Labour Office in Sandakan or Kota Kinabalu",
                "sector": "agriculture",
                "corridor": "ID-MY",
                "indicator_action_ids": [],
                "red_flag_context": "The plantation company passes RSPO annual audit for its 200 direct employees; the 800 contractor-supplied workers are technically employed by the labor contractor and may fall outside the auditor's scope. FGV Holdings received a US Customs and Border Protection (CBP) Withhold Release Order (WRO) in September 2020 for forced labor indicators including debt bondage, passport retention, and below-minimum-wage payments — the WRO blocked FGV palm oil imports into the United States. The Wall Street Journal's 2015 investigation documented Felda settlers earning below Malaysia's minimum wage of RM1,500/month ($330) after deductions",
            },
            {
                "id": "sc006_s3",
                "description": "The labor contractor recruited Indonesian workers through P3MI (Perusahaan Penempatan Pekerja Migran Indonesia)-registered agencies in Makassar (South Sulawesi) and Nunukan (East Kalimantan, a border town with direct ferry links to Sabah), charging workers MYR 5,000-10,000 ($1,100-$2,200) in recruitment fees — exceeding BP2MI (Badan Pelindungan Pekerja Migran Indonesia) regulated maximums. Filipino workers are recruited through POEA (Philippine Overseas Employment Administration)-accredited agencies in Zamboanga City and General Santos, paying PHP 50,000-100,000 ($900-$1,800). Workers' passports are collected by the labor contractor upon arrival in Sabah and stored at a central estate office 30-60 km from the nearest town, described as 'document safekeeping to prevent loss in the plantation'",
                "legal_basis": "Indonesia's Law No. 18/2017 on Placement and Protection of Indonesian Migrant Workers s.30 prohibits charging workers placement fees exceeding government-set maximums (currently IDR 14.8 million / $930 for Malaysia placements); Malaysia's Passport Act 1966 s.12 makes it an offense for any person other than the passport holder to retain the passport, carrying penalties of up to RM10,000 fine or 5 years imprisonment — but enforcement on remote Sabah estates is effectively zero",
                "sector": "agriculture",
                "corridor": "ID-MY",
                "indicator_action_ids": [],
                "red_flag_context": "The RSPO Complaints Panel documented in its 2020 Sime Darby Plantation suspension decision that passport retention on Sabah estates was 'systematic, not incidental,' affecting an estimated 10,000+ workers. US CBP's September 2020 WRO against FGV Holdings specifically cited passport retention, excessive recruitment fees paid by workers (averaging $1,500-$2,500), and restriction of movement on remote estates. Workers on estates 30-60 km from the nearest town with no public transport and no passports are physically unable to leave regardless of contractual terms",
            },
            {
                "id": "sc006_s4",
                "description": "Workers live in estate housing (kongsi) provided by the labor contractor — typically corrugated zinc or wooden longhouses partitioned into 10x10 foot rooms housing 2-4 workers, often without running water, documented by Amnesty International on Wilmar-linked estates in 2016. Workers earn piece-rate pay based on FFB (fresh fruit bunch) tonnage harvested: RM0.10-0.15 per kg of FFB, requiring 1.5-2 tonnes/day to earn RM150-300/day. Daily quotas are set by the mandor (foreman) at 1.5 tonnes minimum; workers who fall below quota have their daily rate reduced to RM30-50 ($6.60-$11) as a 'probationary adjustment,' well below Malaysia's national minimum wage of RM1,500/month ($330, effective May 2022 under Minimum Wages Order 2022)",
                "legal_basis": "Piece-rate pay is permitted under Malaysia Employment Act 1955 s.2 definition of 'wages'; Minimum Wages Order 2022 (P.U.(A) 140/2022) sets RM1,500/month ($330) national minimum but enforcement on agricultural estates requires Labour Department inspectors visiting remote Sabah sites — the Sabah Labour Department conducted approximately 500 plantation inspections in 2022 across 5,000+ registered estates",
                "sector": "agriculture",
                "corridor": "ID-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Workers on remote Sabah plantations with retained passports, in contractor-provided kongsi housing with mandor-controlled daily quotas, paid below minimum wage through piece-rate manipulation — the RSPO-certified refinery (Wilmar or Sime Darby) buying this CPO is four supply chain links removed from these conditions. Amnesty International's 2016 'The Great Palm Oil Scandal' documented these exact conditions on five Wilmar-linked plantations in Kalimantan and Sabah, and the US DOL placed Malaysian palm oil on its 'List of Goods Produced by Child Labor or Forced Labor' (2024 update) citing debt bondage and child labor",
            },
            {
                "id": "sc006_s5",
                "description": "Children of Indonesian and Filipino plantation workers — who have no access to Malaysian public schools (denied enrollment as children of undocumented or temporary foreign workers under Malaysia's Education Act 1996) and no plantation-operated schools within 30 km — assist their parents in FFB harvesting to help meet daily tonnage quotas. Children as young as 8 collect loose fruit (brondolan) from the ground after adult harvesters cut FFB clusters. The labor contractor does not record child presence because children are classified as 'family accompaniment' rather than workers, and their brondolan collection is attributed to the parent's tonnage tally at the weighing station",
                "legal_basis": "Malaysia Children and Young Persons (Employment) Act 1966 s.2(2) permits children to work in family enterprises 'under the immediate control of family members' — a provision originally intended for smallholder farming that labor contractors invoke to classify children as family helpers. ILO C182 (Worst Forms of Child Labour Convention, 1999) — ratified by Malaysia in 2000 — prohibits hazardous child labor, but harvesting palm fruit with sharp sickles (dodos) and exposure to pesticides (paraquat, glyphosate) on plantations meets the hazardous work definition",
                "sector": "agriculture",
                "corridor": "ID-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Child labor as a direct structural consequence of unrealistic adult quotas — parents cannot meet 1.5 tonne daily minimums without children collecting brondolan. The 'family helper' classification conceals exploitation that is invisible to RSPO auditors who visit during working hours and interview adult workers in mandor-supervised settings. The US DOL's 2024 ILAB report specifically lists Malaysian palm oil as produced with both forced labor and child labor, and US CBP's WRO mechanism has been applied to FGV Holdings (2020) and Sime Darby Plantation (2022) on these grounds",
            },
        ],
        "chain_context": "The palm oil supply chain from European consumer product (Unilever's Dove soap, Nestlé's KitKat, P&G's Tide) to Sabah plantation worker spans five or more tiers. RSPO certification — held by companies representing 19% of global palm oil production — audits at the refinery (Wilmar/Sime Darby) and large plantation company (FGV/IOI/KLK) level but structurally cannot reach labor contractor practices on remote estates where workers live in kongsi housing without passports, earn below minimum wage through quota manipulation, and rely on their children to meet harvest targets. The enforcement gap is quantified: US CBP issued Withhold Release Orders against FGV Holdings (September 2020) and Sime Darby Plantation (December 2022) under 19 U.S.C. § 1307, blocking palm oil imports worth an estimated $400M annually; RSPO suspended Sime Darby Plantation (2020) after its own Complaints Panel investigation; and Amnesty International's 2016 investigation of Wilmar-linked supply chains documented systematic forced labor indicators across five plantations. Each enforcement action targeted a different supply chain tier, none reached the labor contractor or P3MI recruitment agency level.",
        "emergent_risk": "Certification-proof exploitation: RSPO Principle 6 audits stop at the plantation company level; labor contractor on remote Sabah estate retains passports (Malaysia Passport Act 1966 s.12 violation), enforces below-minimum-wage quotas, and enables child labor classified as 'family helping' — all invisible to the RSPO-certified supply chain above, triggering US CBP WROs against FGV ($400M+ trade impact) and Sime Darby but not the labor contractors or P3MI agencies below",
        "difficulty": "expert",
        "source_references": [
            "Amnesty International, 'The Great Palm Oil Scandal: Labour Abuses Behind Big Brand Names' (Nov 30, 2016) — documenting forced labor on five Wilmar International-linked plantations in Kalimantan and Sabah",
            "RSPO, 'Sime Darby Plantation Berhad Complaints Panel Suspension Notice' (2020) — suspension for systematic passport retention and below-minimum-wage payments affecting 10,000+ workers",
            "US DOL Bureau of International Labor Affairs (ILAB), 'List of Goods Produced by Child Labor or Forced Labor' (2024 update) — Malaysian palm oil listed for both forced labor and child labor indicators",
            "US CBP, 'Withhold Release Order against FGV Holdings Berhad' (Sep 30, 2020) — blocking US imports of palm oil products based on ILO forced labor indicators including debt bondage and passport retention",
        ],
        "corridors": ["ID-MY", "PH-MY", "MM-MY", "BD-MY"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["debt bondage", "retention of identity documents", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "supply_chain_007",
        "name": "Electronics Manufacturing Outsourced Labor Management Chain",
        "category": "supply_chain",
        "steps": [
            {
                "id": "sc007_s1",
                "description": "A major consumer electronics brand — Samsung Electronics, Dell Technologies, or HP Inc. — contracts with a Penang-based contract manufacturer (CM) such as Flex Ltd. (formerly Flextronics, NASDAQ: FLEX, $26B revenue 2023) or Jabil Inc. (NYSE: JBL, $34B revenue 2023) operating in the Bayan Lepas Free Industrial Zone to assemble circuit boards, hard drives, and electronic components. The CM is a publicly traded company that undergoes annual Responsible Business Alliance (RBA) audits — the RBA Validated Assessment Program (VAP) — and maintains a 'Platinum' or 'Gold' recognition level, requiring conformance with the RBA Code of Conduct v7.0 (2021) across labor, health/safety, environment, ethics, and management systems",
                "legal_basis": "Contract manufacturing is the dominant production model in global electronics; RBA membership (comprising 200+ companies representing $7.7 trillion in combined revenue) requires adherence to RBA Code of Conduct v7.0 s.A (Labor) prohibiting forced labor, child labor, and requiring freely chosen employment. Malaysia Investment Development Authority (MIDA) administers the Penang Free Industrial Zone under Free Zones Act 1990",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Verité's landmark 2014 study 'Forced Labor in the Production of Electronic Goods in Malaysia' found that 90% of foreign workers in Malaysia's electronics sector paid their own recruitment fees, and 28% were in conditions of forced labor as defined by ILO indicators. KnowTheChain's 2022 ICT Sector Benchmark scored Samsung 62/100, Dell 52/100, and HP 47/100 on supply chain labor practices, with the lowest scores consistently in 'recruitment' and 'worker voice' categories. The CM's RBA 'Platinum' rating creates a compliance halo that does not extend to the outsourcing company supplying 60-80% of its factory workforce",
            },
            {
                "id": "sc007_s2",
                "description": "The CM (Flex or Jabil) outsources its entire foreign worker management — recruitment coordination, Malaysia Immigration Department work permit processing (Pas Lawatan Kerja Sementara, PLKS), payroll administration, dormitory management at purpose-built worker hostels in Penang mainland (Seberang Perai), and disciplinary procedures — to a Malaysian outsourcing company registered under Malaysia's Private Employment Agencies Act 1981. The outsourcing company supplies 2,500-4,000 Bangladeshi, Nepali, and Vietnamese workers to the CM's Bayan Lepas production floors, billing the CM MYR 2,800-3,500/month ($615-$770) per worker",
                "legal_basis": "Labor outsourcing is a licensed business under Malaysia's Private Employment Agencies Act 1981 and regulated by the Ministry of Human Resources; the Employment Act 1955 s.33A establishes that the 'principal' (the CM) is responsible for contractor workers' wages, but this liability is rarely invoked in the electronics sector where outsourcing companies handle all employment documentation",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Workers work on the CM's Bayan Lepas production floor wearing the CM's uniform and badge but are legally employed by the outsourcing company — a dual identity that Verité's 2014 report identified as the primary structural enabler of forced labor in Malaysia's electronics sector. The CM can report RBA VAP conformance for its own employment practices while the outsourcing company's recruitment chain, dormitory conditions, and wage deduction practices fall outside the RBA audit scope unless the auditor specifically requests access to outsourcing company records, which occurs in fewer than 30% of audits according to RBA's own 2023 transparency report",
            },
            {
                "id": "sc007_s3",
                "description": "The outsourcing company contracts recruitment to three origin-country agencies: a BMET-registered agency in Dhaka's Gulshan district (Bangladesh), a DoFE-licensed agency in Kathmandu's Thamel area (Nepal), and a DOLAB-licensed agency in Hanoi (Vietnam). Workers are charged: BDT 250,000-500,000 ($2,300-$4,600) in Bangladesh (BMET-regulated maximum: BDT 84,000/$775 under Overseas Employment Act 2013 s.20), NPR 100,000-250,000 ($750-$1,875) in Nepal (DoFE-regulated maximum: NPR 10,000/$75 under Foreign Employment Act 2064 s.52), and 80-150 million VND ($3,200-$6,000) in Vietnam (DOLAB regulates per-market fee schedules, with Malaysia placements capped at 3,600 USD equivalent). The outsourcing company's contract with origin agencies specifies 'zero recruitment fees to workers,' satisfying RBA Code v7.0 s.A1's requirement that 'workers shall not be required to pay for their employment'",
                "legal_basis": "RBA Code of Conduct v7.0 s.A1 prohibits charging workers recruitment fees (aligning with ILO General Principles and Operational Guidelines for Fair Recruitment, 2019); origin-country agency fees are governed by each sending country's regulations. The Dhaka agency's fees of BDT 250,000-500,000 violate Bangladesh Overseas Employment Act 2013 s.20 by 3-6x, but BMET enforcement data shows fewer than 200 agency license revocations per year against 1,400+ registered agencies",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Paper compliance: the outsourcing company's contract says zero fees; origin-country agencies charge $2,300-$6,000 and no one verifies. Verité's 2014 study found that 90% of workers in Malaysia's electronics sector paid recruitment fees averaging $2,500-$5,000, and RBA's own 2023 Annual Report acknowledged that 'recruitment fee practices by sub-agents in origin countries remain the most persistent non-conformance in the electronics sector.' KnowTheChain's 2022 ICT Benchmark found that only 3 of 60 benchmarked companies (5%) could demonstrate verified fee reimbursement reaching origin-country sub-agents",
            },
            {
                "id": "sc007_s4",
                "description": "Workers arrive at the CM's Bayan Lepas facility with $2,300-$6,000 in debt (often financed through village moneylenders at 24-48% annual interest); the outsourcing company deducts MYR 350-500/month ($77-$110) for dormitory accommodation in Seberang Perai hostels and meals from their gross salary of MYR 1,500-1,800/month ($330-$396), leaving MYR 1,000-1,450 ($220-$319). Passports are collected upon arrival at the hostel and stored in a 'centralized document management safe' maintained by the outsourcing company's HR department — a practice that violates Malaysia's Passport Act 1966 s.12 but was documented as affecting 73% of foreign electronics workers in Verité's 2014 survey. Dormitory exit is restricted to shift hours only via biometric (fingerprint) access control gates, described as a 'safety accountability system'",
                "legal_basis": "Employment Act 1955 s.24(1) permits deductions for accommodation provided by the employer, capped at a 'reasonable amount'; Minimum Wages Order 2022 sets MYR 1,500/month minimum wage applicable to outsourcing company employees. Passport Act 1966 s.12 makes it an offense to retain another person's passport, punishable by MYR 10,000 fine or 5 years imprisonment — but the Malaysian Bar Council's 2019 report documented zero prosecutions under s.12 against employer passport retention in the electronics sector",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "The brand (Samsung/Dell/HP) sees an RBA-certified CM (Flex/Jabil) with 'Platinum' recognition; the CM sees a licensed outsourcing company with a zero-fee policy; the outsourcing company operates dormitories with biometric access control, retains 2,500-4,000 passports in violation of Passport Act s.12, and deducts 20-30% of worker salaries — three tiers of apparent compliance above actual exploitation. KnowTheChain's 2022 ICT Benchmark noted that 'the gap between company policy and worker experience in Malaysian electronics manufacturing is the widest of any sector benchmarked,' with top-scoring companies still unable to verify fee reimbursement or passport return at the outsourcing company level",
            },
        ],
        "chain_context": "The global electronics supply chain — $3.4 trillion in annual revenue — has invested heavily in labor standards through RBA (200+ member companies, $7.7 trillion combined revenue), but the outsourcing agent model in Malaysia's Penang, Johor (Pasir Gudang industrial area), and Selangor electronics zones creates a structural gap that no audit framework has closed. Verité's 2014 'Forced Labor in the Production of Electronic Goods in Malaysia' — the most comprehensive study of electronics sector forced labor — found 28% of foreign workers in conditions meeting ILO forced labor definitions, with 90% having paid recruitment fees and 73% subject to passport retention. The brand (Samsung/Dell/HP) audits the CM (Flex/Jabil), the CM outsources worker management to a licensed outsourcing company, the outsourcing company contracts origin-country agencies with a zero-fee policy, and the agencies charge $2,300-$6,000 through sub-agents no audit reaches. Each entity's paperwork is clean — RBA Platinum, zero-fee contracts, licensed operations — but workers on the Bayan Lepas factory floor carry $2,300-$6,000 debts, lack their passports, and live in biometrically controlled dormitories.",
        "emergent_risk": "Paper compliance masking exploitation: RBA 'Platinum' recognition at CM level (Flex/Jabil), zero-fee policy at outsourcing company level, actual $2,300-$6,000 fees at origin-country level (3-6x legal caps), passport retention (73% prevalence per Verité 2014) and biometric dormitory control at worker level — KnowTheChain 2022 ICT Benchmark confirms only 5% of 60 companies can verify fee reimbursement reaching origin-country sub-agents",
        "difficulty": "hard",
        "source_references": [
            "Verité, 'Forced Labor in the Production of Electronic Goods in Malaysia' (2014) — 90% worker-paid fees, 28% forced labor prevalence, 73% passport retention across Penang/Johor electronics workforce",
            "KnowTheChain, 'ICT Sector Benchmark' (2022) — Samsung 62/100, Dell 52/100, HP 47/100; only 5% of 60 companies verified fee reimbursement to origin-country sub-agents",
            "RBA, 'Validated Assessment Program Annual Report' (2023) — acknowledging recruitment fee practices by origin-country sub-agents as 'most persistent non-conformance' in electronics sector",
            "BHRRC, 'Electronics Industry Human Rights Benchmark: Malaysia Focus' (2023) — documenting outsourcing company dormitory conditions and biometric access control in Penang FIZ and Pasir Gudang",
        ],
        "corridors": ["BD-MY", "NP-MY", "VN-MY", "MM-MY"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["debt bondage", "retention of identity documents", "deception"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "supply_chain_008",
        "name": "Gulf Hospitality Industry Multi-Tier Staffing Chain",
        "category": "supply_chain",
        "steps": [
            {
                "id": "sc008_s1",
                "description": "An international luxury hotel brand — Hilton Worldwide Holdings (NYSE: HLT, 7,300+ properties), Marriott International (NASDAQ: MAR, 8,700+ properties), or Accor S.A. (Euronext: AC, 5,400+ properties) — operates a 500-room property in Dubai (DIFC, Palm Jumeirah, or Downtown districts) or Doha (West Bay or Lusail) under a Hotel Management Agreement (HMA) with a local property owner (the 'owner company,' typically a GCC-registered LLC owned by a national family or sovereign wealth fund subsidiary). The HMA stipulates that the brand provides management services, brand standards, and global distribution (reservation systems, loyalty programs) while the owner company is the 'legal employer of all personnel' under UAE Federal Decree-Law No. 33/2021 (Labour Law) or Qatar Law No. 14/2004",
                "legal_basis": "Hotel Management Agreements are the dominant operating model for international brands in the Gulf — Hilton, Marriott, and Accor manage rather than own 95%+ of their Middle East properties. UAE Federal Decree-Law No. 33/2021 Art. 4 defines the 'employer' as the entity that employs workers and pays their wages; the brand is the 'operator' providing management services, not the employer. Qatar Law No. 14/2004 Art. 1 similarly defines employer as the entity that engages workers under an employment contract",
                "sector": "hospitality",
                "corridor": "PH-AE",
                "indicator_action_ids": [],
                "red_flag_context": "The HMA separates the brand (with its global Human Rights Policy, often referencing the UN Guiding Principles on Business and Human Rights) from the owner company (the actual employer controlling hiring, wages, and working conditions). Equidem's 2020 'The Cost of Contagion' report documented that luxury hotel workers in Dubai branded properties experienced COVID-era wage reductions of 30-50%, crowded labor camp conditions, and movement restrictions — all imposed by owner companies, not the brands whose names were on the building. The brands' Human Rights Policies explicitly covered only 'managed properties' and defined the HMA as creating 'no employment relationship with owner company staff'",
            },
            {
                "id": "sc008_s2",
                "description": "The owner company contracts with a UAE-registered staffing agency licensed by the Ministry of Human Resources and Emiratisation (MOHRE) under Ministerial Resolution No. 52/2019 to supply housekeeping, kitchen stewarding, laundry, and public area cleaning staff. The staffing agency provides 200 Filipino, Ethiopian, Nepali, and Bangladeshi workers at a per-worker monthly fee of AED 3,500-4,500 ($953-$1,225), from which the agency pays workers AED 1,200-1,800/month ($327-$490) and retains the 50-60% margin for visa processing, accommodation provision, transport, and profit",
                "legal_basis": "Staffing agencies (tawseet companies) are licensed under UAE MOHRE Ministerial Resolution No. 52/2019 on temporary staffing; outsourcing non-core hotel functions to staffing agencies is commercially standard in the Gulf hospitality sector. UAE Labour Law (Decree-Law No. 33/2021) Art. 25-27 regulates temporary staffing arrangements and establishes that the staffing agency is the employer, not the hotel or owner company",
                "sector": "hospitality",
                "corridor": "PH-AE",
                "indicator_action_ids": [],
                "red_flag_context": "Workers wear the Hilton/Marriott/Accor brand uniform, serve brand guests paying $400-800/night, and are subject to brand service standards training — but are employed by a staffing agency the brand has no contractual relationship with. The per-worker margin of 50-60% creates intense pressure to minimize worker costs. The ILO's 2017 'Employer-Migrant Worker Relationships in the Middle East' study found that staffing agency workers in Gulf hospitality earned 30-40% less than directly employed hotel staff performing identical roles, with no access to brand training programs, promotion pathways, or grievance mechanisms",
            },
            {
                "id": "sc008_s3",
                "description": "The staffing agency recruits through origin-country partners with vastly different regulatory environments: a POEA (Philippine Overseas Employment Administration, now DMW — Department of Migrant Workers under Republic Act 11641, 2021)-accredited agency in Manila charging PHP 60,000-90,000 ($1,075-$1,610) against POEA-regulated placement fees that should be capped at one month's salary; a MOLSA-registered agent in Addis Ababa charging ETB 100,000-180,000 ($1,750-$3,150) in a market with minimal fee regulation under Ethiopia's Overseas Employment Proclamation No. 923/2016; and a DoFE-licensed broker in Kathmandu charging NPR 200,000-450,000 ($1,500-$3,375) — 20-45x the NPR 10,000 ($75) legal cap under Nepal's Foreign Employment Act 2064 s.52. Workers doing identical housekeeping jobs in the same hotel arrive with debt ranging from $1,075 (Filipino, relatively regulated) to $3,375 (Nepali, minimal enforcement)",
                "legal_basis": "Philippines Republic Act 10022 (Amended Migrant Workers Act) s.6 caps placement fees at one month's salary for new hires; the DMW (successor to POEA) actively pursues unlicensed agencies. Ethiopia's Overseas Employment Proclamation No. 923/2016 was enacted after a 2013-2015 ban on overseas employment to Saudi Arabia/UAE following mass deportations, but implementing regulations on fee caps remain weak. Nepal's Foreign Employment Act 2064 (2007) s.52 sets NPR 10,000 cap but DoFE's 2022 annual report documented only 45 agency license suspensions against 900+ registered agencies",
                "sector": "hospitality",
                "corridor": "PH-AE",
                "indicator_action_ids": [],
                "red_flag_context": "Workers performing identical roles in the same hotel arrive with debt varying by 3x depending on origin-country regulatory enforcement. The staffing agency benefits from this disparity — Nepali workers carrying NPR 200,000-450,000 ($1,500-$3,375) debt are less likely to leave or complain than Filipino workers whose POEA-regulated fees are partially recoverable. Equidem's 2020 Gulf labor study documented that hotels in Dubai used this 'regulatory arbitrage' deliberately, instructing staffing agencies to increase recruitment from Ethiopia and Nepal (weaker regulation, higher fees, more compliant workers) and reduce Filipino recruitment (stronger POEA oversight, more worker complaints)",
            },
            {
                "id": "sc008_s4",
                "description": "Workers live in staffing-agency-provided labor accommodation in Sonapur, Al Quoz Industrial Area, or Jebel Ali labour camps — 30-60 minutes by company bus from the hotel in Dubai Marina or Palm Jumeirah. The agency deducts AED 450-600/month ($122-$163) for shared dormitory rooms housing 8-12 workers in 25-30 sqm rooms (below Dubai Municipality's 2018 Labour Accommodation Standard of 3 sqm/person), plus AED 200-300/month ($54-$82) for twice-daily transport. Workers' passports are held by the agency 'per company policy for document safety and visa compliance' — despite UAE Ministerial Resolution No. 766/2015 explicitly prohibiting employer passport retention since 2009. Workers earning AED 1,200-1,800/month ($327-$490) lose AED 650-900/month ($177-$245) to deductions, leaving $150-$245/month net against debts of $1,075-$3,375",
                "legal_basis": "UAE Labour Law (Decree-Law No. 33/2021) Art. 13(4) prohibits employers from retaining workers' passports or travel documents; Ministerial Resolution No. 766/2015 reiterates the prohibition with penalties of AED 20,000 per violation. Dubai Municipality Technical Guidelines for Labour Accommodation (2018) specify minimum 3 sqm per person. Accommodation and transport deductions are permissible under Art. 55 if 'not exceeding the actual cost and not for the purpose of profit'",
                "sector": "hospitality",
                "corridor": "PH-AE",
                "indicator_action_ids": [],
                "red_flag_context": "Workers earning AED 1,200-1,800/month ($327-$490) net AED 300-900/month ($82-$245) after deductions; against debts of $1,075-$3,375 (origin-country-dependent), repayment requires 4-41 months. Passport retention affects 90%+ of staffing agency workers according to the ILO's 2019 'Promoting Fair Recruitment in the Middle East' assessment, despite being illegal since 2009 under Ministerial Resolution No. 766/2015. The luxury hotel guest paying $400-800/night sees the Hilton/Marriott/Accor brand; the housekeeper cleaning the room lives in a Sonapur labour camp 45 minutes away with a confiscated passport and $2,000 in origin-country debt",
            },
            {
                "id": "sc008_s5",
                "description": "The international hotel brand (Hilton, Marriott, or Accor) publishes an annual Modern Slavery Statement under UK Modern Slavery Act 2015 s.54 (for Accor and Hilton's UK entities, with combined UK turnover exceeding £36M) and/or an Australian Modern Slavery Act 2018 s.14 statement. The statement details the brand's supply chain due diligence program covering the Hotel Management Agreement with the owner company, brand-managed procurement contracts, and 'key suppliers.' However, the statement explicitly excludes the staffing agency and its origin-country recruitment partners because the brand 'does not have a direct contractual relationship with third-party staffing providers engaged by our ownership partners,' and the HMA does not grant the brand authority over the owner company's staffing procurement decisions",
                "legal_basis": "UK Modern Slavery Act 2015 s.54(4) requires the statement to describe 'steps the organisation has taken during the financial year to ensure that slavery and human trafficking is not taking place in any of its supply chains' — but s.54(1) applies to commercial organizations with turnover exceeding £36M, and the scope of 'supply chain' is self-defined by the reporting entity. Australian Modern Slavery Act 2018 s.16(1)(d) similarly requires reporting on 'actions taken to assess and address risks, including due diligence,' but does not mandate specific supply chain depth. The ILO MNE Declaration (Revised 2017) Principle 10(e) recommends enterprises 'carry out human rights due diligence' throughout their value chain, but this is voluntary",
                "sector": "hospitality",
                "corridor": "PH-AE",
                "indicator_action_ids": [],
                "red_flag_context": "The brand's legal team has structured the HMA to maintain contractual arm's-length distance from the staffing supply chain — an architecture that renders the Modern Slavery Statement technically compliant but strategically incomplete. Hilton's 2023 s.54 statement (12 pages) mentions 'hotel management relationships' and 'owned and managed properties' but does not reference staffing agencies used by owner companies at 95% of its Middle East properties. The BHRRC's 2023 hospitality sector analysis found that zero major hotel brands' Modern Slavery Statements covered staffing agencies used by their Gulf property owner-partners, despite these agencies employing 60-70% of the workers who deliver the brand experience to guests",
            },
        ],
        "chain_context": "Gulf hospitality connects global luxury brands (Hilton: 7,300 properties, $10.2B revenue 2023; Marriott: 8,700 properties, $23.7B revenue 2023; Accor: 5,400 properties, €5.1B revenue 2023) to workers from some of the world's poorest communities through a chain of legal agreements — Hotel Management Agreements, staffing agency outsourcing contracts, origin-country recruitment — that systematically separate the brand with $10-24B in revenue from the housekeeper earning $150-$245/month after deductions. Each entity operates legally: MOHRE-licensed staffing agencies, POEA/DMW-accredited Filipino agencies, HMA-structured brand relationships. But the chain's architecture ensures that Hilton's UK Modern Slavery Act s.54 statement (12 pages, covering 'managed properties') never reaches the Sonapur labor camp where its housekeepers live 8-12 to a room with passports confiscated in violation of UAE Ministerial Resolution No. 766/2015. Equidem's 2020 'The Cost of Contagion' documented that during COVID-19, luxury hotel brands publicly committed to worker welfare while owner companies imposed 30-50% wage cuts and crammed staffing agency workers into overcrowded camps where infection rates reached 40%.",
        "emergent_risk": "Disclosure-proof supply chain: hotel brand's UK Modern Slavery Act s.54 statement covers the HMA relationship but not the MOHRE-licensed staffing agency that recruits, houses in Sonapur/Al Quoz camps, and retains passports (90%+ prevalence per ILO 2019) of the workforce delivering the brand experience; the HMA is legally structured to exclude brand liability for owner company staffing decisions, creating a due diligence firewall that is technically compliant with s.54's self-defined scope but fails the ILO MNE Declaration's value-chain standard",
        "difficulty": "hard",
        "source_references": [
            "Equidem, 'The Cost of Contagion: The Human Rights Impacts of COVID-19 on Migrant Workers in the Gulf' (2020) — documenting luxury hotel worker wage cuts (30-50%), crowded camp conditions, passport retention during pandemic across Dubai and Doha branded properties",
            "BHRRC, 'Hospitality Industry Human Rights Obligations in the Gulf: Modern Slavery Statement Analysis' (2023) — finding zero major hotel brands' s.54 statements covered staffing agencies at Gulf properties",
            "ILO, 'Promoting Fair Recruitment in the Middle East: Policy Brief and Implementation Assessment' (2019) — 90%+ passport retention prevalence among staffing agency workers, despite UAE prohibition since 2009",
            "KnowTheChain, 'Hospitality Sector Due Diligence Gap Analysis: Gulf States' (2023) — scoring methodology for brand-to-worker supply chain transparency in hotel management agreement structures",
        ],
        "corridors": ["PH-AE", "ET-AE", "NP-AE", "IN-AE", "PH-QA", "NP-QA"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["debt bondage", "retention of identity documents", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
]
