"""
Document control chains — passport/visa/ID confiscation and document-based coercion.

Sources: Human Rights Watch giga-projects report (Dec 2024), Amnesty International
Qatar World Cup reality check (2019), Tamkeen Fields for Aid Jordan QIZ study (2023),
TWC2 Singapore work permit research (2017), Justice Centre Hong Kong forced labour
prevalence study (2016), EJF "Blood and Water" Thai fishing report (2019),
ILO Reform of the Kafala System (2017), US TIP Report 2024 country narratives.
"""

CHAINS: list[dict] = [
    {
        "id": "document_control_001",
        "name": "Kafala System Passport Retention Cascade",
        "category": "document_control",
        "steps": [
            {
                "id": "dc001_s1",
                "description": "Upon arrival at King Abdulaziz International Airport (Jeddah) or King Khalid International Airport (Riyadh), the kafeel (sponsor) or their mandoub (authorized representative) collects the Filipino domestic worker's passport to 'process the iqama application' at the nearest Jawazat (General Directorate of Passports) office — the Jawazat branches in Riyadh's Al Olaya district, Jeddah's Al Sharafiyah, or Dammam's Al Faisaliyah handle the bulk of domestic worker iqama issuance",
                "legal_basis": "Iqama (residence permit) processing genuinely requires passport submission to Jawazat; the sponsor is the legally designated applicant under the kafala system as codified in Royal Decree M/17 (Saudi Residence Regulations). Saudi Labor Law Art. 61 states: 'The employer shall not retain the worker's passport, residence permit, or health insurance card' — penalty SAR 15,000 per Ministerial Decision No. 166 (2000), but enforcement requires the worker to file a complaint at the labour office, which domestic workers excluded from the Labor Law until 2009 could not do",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Legitimate iqama processing at Jawazat takes 5-15 business days per standard Absher platform tracking timelines, but HRW's 2008 report 'As If I Am Not Human' documented that 90% of 142 interviewed domestic workers never received their passport back after iqama issuance was complete — the processing pretext becomes indefinite retention",
            },
            {
                "id": "dc001_s2",
                "description": "After the Jawazat issues the iqama (a green laminated card bearing the sponsor's name, the worker's photo, and the sponsor's establishment number), the sponsor retains the worker's passport in the household safe alongside the kafalat sponsorship agreement, stating it is held 'for safekeeping so it does not get lost' — the iqama card itself may or may not be given to the worker",
                "legal_basis": "Saudi Ministerial Decision No. 166 (2000) criminalized passport retention with a penalty of SAR 15,000, but HRW documented in 'Die First, and I'll Pay You Later' (Dec 4, 2024) that among workers at NEOM and Red Sea giga-project sites, passport confiscation remained 'near-universal' — the enforcement mechanism requires the worker to physically travel to a Jawazat office or labor office and file a complaint, which is functionally impossible for live-in domestic workers whose movement is controlled by the sponsor",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "The 'safekeeping' framing exploits the gap between Art. 61's prohibition and the complaint-dependent enforcement mechanism; the worker's only proof of legal status (iqama) may also be withheld, leaving them unable to prove identity at police checkpoints (known as security patrols or dawriyyat amniyya) that routinely stop non-Saudi-appearing individuals",
            },
            {
                "id": "dc001_s3",
                "description": "The worker is informed that leaving the sponsor's residence requires carrying the iqama at all times, as Saudi Residence Regulations mandate that all non-citizens carry valid residency documentation — since the sponsor controls both the passport and often the iqama card, the worker cannot move freely in the city without risk of detention by dawriyyat amniyya patrols or at Jawazat checkpoints",
                "legal_basis": "Saudi Residence Regulations (Royal Decree M/17, Art. 3) require all residents to carry valid identification; failure to produce an iqama on demand is an administrative violation that can result in detention at a tawqeef (deportation detention center). The ILO's 2017 'Reform of the Kafala System' report noted that this ID-carrying requirement, combined with employer custody of documents, 'effectively ties the worker's freedom of movement to the sponsor's cooperation'",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Without passport AND without physical possession of the iqama card, the worker cannot: (1) prove legal status to police, (2) access healthcare at government hospitals that require iqama presentation, (3) open a bank account for wage payment, or (4) file a complaint at the labour office (which requires iqama as identification) — creating complete administrative invisibility outside the sponsor's household",
            },
            {
                "id": "dc001_s4",
                "description": "When the worker attempts to use the 2021 labour mobility reforms to transfer to a new sponsor (enabled by Ministerial Resolution No. 51848 allowing transfer without sponsor consent after 1 year), the current sponsor pre-emptively files a huroob (absconding/runaway) report through the Absher platform (absher.sa) — a Ministry of Interior online portal that allows sponsors to report workers as absent from work with a few clicks, instantly converting the worker's iqama status to 'expired/cancelled'",
                "legal_basis": "The huroob reporting system was originally created to track workers who genuinely abandon employment, but the Absher platform allows sponsors to file reports unilaterally with no verification requirement. The 2021 reforms (Ministerial Resolution No. 51848) intended to allow worker-initiated transfer, but the huroob counter-filing creates a de facto veto — the worker's iqama is cancelled before the transfer processes. US TIP Report 2024 (Saudi Arabia section) specifically noted that 'sponsors continued to file absconding charges against workers who reported abuse'",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "The Absher platform's huroob filing is instantaneous (minutes), while the labour mobility transfer process takes weeks to months — this timing asymmetry means the sponsor can always cancel the worker's legal status faster than the transfer can be completed; HRW's December 2024 giga-projects report documented multiple cases of workers at NEOM who had huroob filed against them within hours of requesting a transfer",
            },
            {
                "id": "dc001_s5",
                "description": "The worker is now in huroob status: iqama cancelled, passport held by the former sponsor, wanted by Jawazat for 'absconding' — they face arrest at any checkpoint, cannot access healthcare, cannot work legally, cannot leave Saudi Arabia (exit requires valid iqama clearance), and any interaction with authorities risks detention at a tawqeef deportation center (such as the Shumaisi detention facility in Jeddah, documented by AP and HRW for severe overcrowding)",
                "legal_basis": "Under Saudi Residence Regulations Art. 39, a person in huroob status is subject to a fine of SAR 50,000 for a first offense, detention, and deportation with a permanent re-entry ban. The worker must clear huroob status before any legal action is possible — clearing requires either the sponsor's cooperation (withdrawing the report) or a lengthy appeal process at the labour court (hay'at tasheel al-khilafat al-umaliyya), which itself requires valid identification documents the worker does not possess",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Complete document-based control achieved through sequential administrative mechanisms: (1) passport confiscated under iqama-processing pretext, (2) iqama withheld under safekeeping claim, (3) movement restricted by ID-carrying requirement, (4) legal status destroyed by Absher huroob filing, (5) remedial access blocked by requirement to produce documents the worker does not have — the US TIP Report 2024 placed Saudi Arabia on the Tier 2 Watch List, citing this circular trap as a key indicator of forced labor",
            },
        ],
        "chain_context": "Each step exploits a genuine Saudi administrative mechanism — Jawazat iqama processing, Ministerial Decision No. 166's complaint-dependent enforcement, Residence Regulation ID requirements, the Absher platform's unilateral huroob filing — but the chain creates total document-based control. The 2021 Ministerial Resolution No. 51848 labour mobility reforms are structurally undermined by the sponsor's ability to file instantaneous huroob reports via Absher before transfers process. HRW's December 2024 report 'Die First, and I'll Pay You Later' documented this exact sequence among workers at NEOM and Red Sea giga-project sites, where passport confiscation was 'near-universal' despite Art. 61 prohibition.",
        "emergent_risk": "Complete identity erasure through cascading administrative mechanisms: passport retention (violating Art. 61 but unenforced per SAR 15,000 penalty gap) + iqama withholding + huroob via Absher = worker has no legal existence independent of sponsor, cannot access courts/healthcare/police, and faces detention at Shumaisi or similar tawqeef facilities if discovered",
        "difficulty": "medium",
        "source_references": [
            "HRW, 'Die First, and I'll Pay You Later: Saudi Arabia's Giga-Projects' (Dec 4, 2024) — documented near-universal passport confiscation at NEOM/Red Sea sites",
            "HRW, 'As If I Am Not Human: Abuses Against Asian Domestic Workers in Saudi Arabia' (Jul 2008) — 90% of 142 domestic workers surveyed never received passports back after iqama processing",
            "ILO, 'Reform of the Kafala System' (2017) — analysis of ID-carrying requirement as mobility restriction mechanism",
            "US TIP Report 2024, Saudi Arabia country narrative — Tier 2 Watch List, noting huroob misuse against workers reporting abuse",
            "Saudi Labor Law Art. 61 (passport retention prohibition), Ministerial Decision No. 166/2000 (SAR 15,000 penalty), Ministerial Resolution No. 51848/2021 (labor mobility reform)",
        ],
        "corridors": ["PH-SA", "ET-SA", "ID-SA", "BD-SA"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["retention of identity documents", "abuse of position of vulnerability"],
            "purpose": ["exploitation", "forced labour"],
        },
    },
    {
        "id": "document_control_002",
        "name": "Employer-Tied Work Permit Single-Employer Lock",
        "category": "document_control",
        "steps": [
            {
                "id": "dc002_s1",
                "description": "Bangladeshi electronics factory worker arrives in Malaysia on a PLKS (Pas Lawatan Kerja Sementara — Temporary Employment Visit Pass), a single-employer work permit issued by Jabatan Imigresen Malaysia (Immigration Department of Malaysia, headquartered in Putrajaya) that binds the worker's legal immigration status to the employer's company registration number; the PLKS card displays the employer's name, the worker's photo, and the permitted sector (e.g., 'pembuatan/manufacturing')",
                "legal_basis": "Malaysia's Immigration Act 1959/63 s.10 requires employer-specific work permits for all foreign workers; the PLKS is renewed annually and cancellation by the employer immediately renders the worker undocumented. The worker also pays an annual foreign worker levy (currently RM1,850 for manufacturing sector) that is deducted from wages despite being legally the employer's obligation per Employment Act 1955 s.24A",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "PLKS tied to single employer means any labor dispute — complaining about unpaid overtime, unsafe conditions, or contract violations — risks the employer cancelling the permit, instantly converting the worker into an undocumented person subject to penalties under Immigration Act 1959/63 s.55(1): fine up to RM10,000, imprisonment up to 5 years, or caning (whipping) of not more than 6 strokes",
            },
            {
                "id": "dc002_s2",
                "description": "The factory's outsourcing agent (a licensed recruitment intermediary under Malaysia's Private Employment Agencies Act 1981) collects the worker's passport during the first week, claiming it is needed for 'annual PLKS renewal processing at Jabatan Imigresen Putrajaya' — the passport is stored in the outsourcing company's office safe, not at immigration, alongside passports from hundreds of other workers placed at factories in Penang FTZ and Bayan Lepas industrial compounds",
                "legal_basis": "Malaysia's Anti-Trafficking in Persons and Anti-Smuggling of Migrants Act 2007 (ATIPSOM) s.12(1) criminalizes document retention as a trafficking indicator, but enforcement relies on police reports by workers who fear immigration consequences. The Verité 2014 study 'Forced Labor in the Production of Electronic Goods in Malaysia' found that 94% of surveyed foreign workers in electronics had their passports held by employers or agents",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Outsourcing agents — operating as intermediaries between the PLKS-holding employer and the worker — create an additional layer of document control; the worker must negotiate with both the agent and the employer to access their passport. Verité's 94% passport retention figure among electronics workers demonstrates this is systematic, not incidental",
            },
            {
                "id": "dc002_s3",
                "description": "When the worker files a complaint with the Jabatan Tenaga Kerja (Department of Labour, Putrajaya) about unpaid overtime wages exceeding the Employment Act 1955 s.24 cap of 50% wage deductions, the outsourcing agent informs the worker that their PLKS renewal is 'under review pending employer assessment' and they should 'show good performance and cooperation' before the renewal will be processed at Jabatan Imigresen",
                "legal_basis": "PLKS renewal is at the employer's discretion — the employer must submit the renewal application and pay the processing fee. Employment Act 1955 s.24 limits wage deductions to 50% of monthly wages, but enforcement through labour courts takes 6-18 months, during which the worker's permit may expire. The US TIP Report 2024 (Malaysia section, Tier 2 Watch List) noted that 'foreign workers who filed labor complaints frequently had their work permits cancelled by employers in retaliation'",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "PLKS renewal weaponized as retaliation for exercising legal rights: the worker filed a legitimate wage complaint under Employment Act 1955, but the employer uses permit renewal discretion to threaten the worker's immigration status — creating a forced choice between accepting wage theft and risking undocumented status with s.55(1) penalties (imprisonment + caning)",
            },
            {
                "id": "dc002_s4",
                "description": "The worker's PLKS expires while 'under review'; they are now technically overstaying under Immigration Act 1959/63 s.15 and the outsourcing agent warns that leaving the factory compound — a gated dormitory-factory complex in the Penang FTZ — risks arrest by RELA (Ikatan Relawan Rakyat, the People's Volunteer Corps) immigration enforcement raids that regularly target industrial areas and worker dormitories, with overstayers subject to detention at Lenggeng or Semenyih immigration detention centers",
                "legal_basis": "Immigration Act 1959/63 s.55(1): overstaying is punishable by fine up to RM10,000, imprisonment up to 5 years, and/or caning of up to 6 strokes. Workers may apply for a Special Pass (Pas Khas) to regularize status, but this costs RM100/month and requires employer sponsorship. RELA enforcement operations (Ops Mega, Ops Sapu) specifically target industrial areas; workers detained during raids are held at Lenggeng Immigration Detention Centre (Negeri Sembilan) where SUHAKAM (Human Rights Commission of Malaysia) has documented overcrowding and inadequate conditions",
                "sector": "manufacturing",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Employer deliberately engineered undocumented status by withholding PLKS renewal: the worker's passport is in the outsourcing agent's safe, their PLKS has expired, they face caning and imprisonment if caught outside the compound, and regularization via Special Pass requires the same employer's cooperation — the US TIP Report 2024 identified this permit-expiration-as-control pattern as a 'significant indicator of forced labor in Malaysian manufacturing'",
            },
        ],
        "chain_context": "Malaysia's employer-tied PLKS system gives structural document control to the employer from day one. Combined with passport retention by outsourcing agents (94% prevalence per Verité research), retaliatory PLKS non-renewal when workers file labour complaints, and the severity of Immigration Act 1959/63 s.55(1) penalties (caning + imprisonment for overstaying), the worker's immigration status becomes the primary coercion tool. The worker cannot leave, complain, or change employers without risking arrest by RELA enforcement operations and detention at facilities like Lenggeng. Employment Act 1955 s.24 wage protections and ATIPSOM s.12(1) anti-retention provisions exist on paper but are structurally undermined by the employer's unilateral control over the PLKS.",
        "emergent_risk": "Legal status as coercion instrument: employer-tied PLKS + 94% passport retention rate + retaliatory non-renewal + s.55(1) caning/imprisonment penalties for overstaying = engineered undocumented status that converts labour rights complaints into immigration crimes",
        "difficulty": "medium",
        "source_references": [
            "Verité, 'Forced Labor in the Production of Electronic Goods in Malaysia' (2014) — 94% passport retention rate among surveyed electronics workers",
            "US TIP Report 2024, Malaysia country narrative (Tier 2 Watch List) — documented retaliatory permit cancellation and permit-expiration control patterns",
            "Immigration Act 1959/63 s.55(1) (overstaying penalties: fine/imprisonment/caning), s.15 (PLKS conditions)",
            "Employment Act 1955 s.24 (50% wage deduction cap), s.24A (levy payment responsibility)",
            "SUHAKAM, 'Report on the Conditions of Detention Centres in Malaysia' — Lenggeng/Semenyih conditions documentation",
        ],
        "corridors": ["BD-MY", "NP-MY", "MM-MY", "ID-MY"],
        "palermo_elements": {
            "act": ["harbouring"],
            "means": ["retention of identity documents", "coercion", "abuse of position of vulnerability"],
            "purpose": ["forced labour"],
        },
    },
    {
        "id": "document_control_003",
        "name": "UAE Construction Worker Document Substitution Chain",
        "category": "document_control",
        "steps": [
            {
                "id": "dc003_s1",
                "description": "Indian construction worker signs an employment contract in Mumbai specifying a salary of AED 2,200/month (approx. $600 USD) as a 'skilled electrician' — the contract is attested by the Indian Embassy in Abu Dhabi (via eMigrate, the Indian government's emigration clearance portal) and stamped by the UAE Ministry of Human Resources and Emiratisation (MOHRE) to obtain the initial entry permit; the worker pays the recruiting agent in Mumbai between INR 80,000-200,000 ($960-$2,400) in placement fees",
                "legal_basis": "India's Emigration Act 1983 (now replaced by Emigration Bill 2021 provisions) requires emigration clearance via eMigrate for ECR (Emigration Check Required) passport holders going to 18 specified countries including UAE. MOHRE Ministerial Decree No. 764/2015 requires pre-attestation of employment contracts. The recruitment fee paid to the Mumbai agent violates both UAE Ministerial Decree No. 1283/2020 (zero-cost recruitment policy) and ILO Fair Recruitment Initiative guidelines, but enforcement is in the sending country",
                "sector": "construction",
                "corridor": "IN-AE",
                "indicator_action_ids": [],
                "red_flag_context": "The eMigrate-attested and MOHRE-stamped contract creates a false sense of government-verified security; HRW's December 2024 report documented that contracts attested for NEOM and Red Sea Project workers in Saudi Arabia (same Gulf pattern) were routinely replaced upon arrival — the attestation stamp verifies the document existed, not that its terms will be honored",
            },
            {
                "id": "dc003_s2",
                "description": "Upon arrival at Dubai International Airport (Terminal 2, the dedicated low-cost/labor migration terminal), the employer's PRO (Public Relations Officer — the company's government liaison for visa processing) collects the worker's passport and presents a new Arabic-language employment contract at the labor camp in Al Quoz Industrial Area or Sonapur (International City labor camp area), describing the position as 'aamil/general laborer' at AED 1,100/month ($300 USD) — half the originally agreed salary — with the worker told this is 'the same contract translated into the required official language for MOHRE registration'",
                "legal_basis": "UAE Federal Decree-Law No. 33/2021 (new labor law effective Feb 2, 2022) Art. 13 states workers must receive a copy of their employment contract, and Art. 6 prohibits contract substitution. MOHRE requires Arabic-language contracts for registration. However, HRW documented in multiple Gulf reports that the 'translation' pretext is used to introduce materially different terms — the worker, not reading Arabic, cannot verify the content. The UAE Wage Protection System (WPS) registers the new lower salary, making the substituted terms the 'official' record",
                "sector": "construction",
                "corridor": "IN-AE",
                "indicator_action_ids": [],
                "red_flag_context": "Classic contract substitution at the point of maximum vulnerability: the worker has already paid INR 80,000-200,000 in recruitment debt, surrendered their passport, and is in a foreign country with no Arabic language ability — signing the substituted contract is coerced by circumstance. Federal Decree-Law No. 33/2021 Art. 6 nominally prohibits this, but the worker's only recourse is filing a MOHRE complaint (which requires the passport they no longer possess and Arabic-language documentation of the original terms)",
            },
            {
                "id": "dc003_s3",
                "description": "The employer's PRO takes the worker's passport, the original eMigrate-attested Indian contract, and the new Arabic-language contract to the MOHRE office in Dubai (Al Aweer or Jebel Ali Free Zone branches) for work permit processing and Emirates ID application at the ICA (Federal Authority for Identity, Citizenship, Customs and Port Security) — stating that all original documents must be submitted together as a complete file",
                "legal_basis": "MOHRE work permit processing (via the Tasheel service center system) does require passport submission, and Emirates ID (issued by ICA, replacing the former EIDA) requires biometrics and passport. However, Federal Decree-Law No. 33/2021 Art. 13 requires that the worker retain a copy of their contract. By taking the Indian eMigrate-attested contract — which shows the original $600/month terms — the employer removes the worker's only documentary evidence of the salary fraud",
                "sector": "construction",
                "corridor": "IN-AE",
                "indicator_action_ids": [],
                "red_flag_context": "The eMigrate-attested contract showing AED 2,200/month is the only evidence that could prove contract substitution in a MOHRE dispute — by confiscating it during 'administrative processing,' the employer ensures the only contract in the MOHRE system is the Arabic-language AED 1,100/month version. The worker cannot access eMigrate records from the UAE without Indian embassy assistance, which requires a passport they do not possess",
            },
            {
                "id": "dc003_s4",
                "description": "The worker's Emirates ID (a white card with gold accents bearing the worker's photo, Emirates ID number, and visa expiry date, issued by ICA) is registered to the employer's labor camp address in Sonapur/Al Quoz and the physical card is retained by the camp manager (mushrif) 'to prevent loss on construction sites in Jebel Ali or Dubai Marina project areas' — the worker is given a photocopy of the Emirates ID front side only",
                "legal_basis": "Federal Decree-Law No. 33/2021 Art. 13 protects workers' right to retain their identity documents. ICA regulations require all UAE residents to carry their Emirates ID. However, HRW and Amnesty International have documented that labor camp managers routinely retain Emirates IDs citing construction site loss risk — a practice that is technically illegal but unenforced because camp-level document management falls outside MOHRE inspection scope (MOHRE inspects worksites, not camps, which are under municipality jurisdiction)",
                "sector": "construction",
                "corridor": "IN-AE",
                "indicator_action_ids": [],
                "red_flag_context": "Worker now possesses zero documents: passport held by employer's PRO, original eMigrate-attested contract confiscated, substituted Arabic contract filed with MOHRE at terms the worker never agreed to, Emirates ID held by camp mushrif — only a front-side photocopy of the Emirates ID remains, which is not accepted by police, banks, MOHRE complaint offices, or airlines. The US TIP Report 2024 (UAE section, Tier 2) specifically cited 'confiscation of passports and wages' as ongoing forced labor indicators despite Federal Decree-Law No. 33/2021 reforms",
            },
        ],
        "chain_context": "Contract substitution is the most documented trafficking indicator in Gulf construction per ILO and MOHRE's own 2023 compliance data. But each step in this chain uses a legitimate administrative procedure — eMigrate attestation, Arabic-language MOHRE registration, Tasheel processing, ICA Emirates ID issuance, construction site document security — to systematically strip the worker of every document that could prove identity or original contractual terms. Federal Decree-Law No. 33/2021 (effective Feb 2, 2022) nominally prohibits both contract substitution (Art. 6) and document retention (Art. 13), but enforcement requires the worker to file a complaint at a MOHRE Tasheel center with identification they no longer possess, in a language (Arabic) they do not speak, regarding a contract whose original version was confiscated.",
        "emergent_risk": "Evidence destruction through sequential administrative procedure: eMigrate-attested contract confiscated + Arabic substitution registered with MOHRE/WPS + passport held by PRO + Emirates ID held by camp mushrif = worker cannot prove original terms, identity, or legal status despite Federal Decree-Law No. 33/2021 Art. 6 and Art. 13 protections",
        "difficulty": "hard",
        "source_references": [
            "HRW, 'Die First, and I'll Pay You Later: Saudi Arabia's Giga-Projects' (Dec 4, 2024) — same Gulf contract substitution pattern documented at NEOM",
            "UAE Federal Decree-Law No. 33/2021 Art. 6 (contract substitution prohibition), Art. 13 (document retention prohibition)",
            "MOHRE Ministerial Decree No. 764/2015 (contract pre-attestation), Ministerial Decree No. 1283/2020 (zero-cost recruitment)",
            "US TIP Report 2024, UAE country narrative (Tier 2) — passport confiscation and wage withholding as ongoing indicators",
            "ILO, 'Employer-Migrant Worker Relationships in the Middle East: Exploring Scope for Internal Labour Market Mobility and Fair Migration' (2017)",
        ],
        "corridors": ["IN-AE", "PK-AE", "BD-AE", "NP-AE"],
        "palermo_elements": {
            "act": ["recruitment", "transfer"],
            "means": ["deception", "retention of identity documents"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "document_control_004",
        "name": "Singapore Domestic Worker Employer Dependency Lock",
        "category": "document_control",
        "steps": [
            {
                "id": "dc004_s1",
                "description": "Filipino domestic worker's Work Permit card (a blue credit-card-sized document bearing the worker's photo and FIN — Foreign Identification Number) is issued by MOM (Ministry of Manpower) to the employer, not the worker, under the Employment of Foreign Manpower Act (EFMA) Part IV — the Work Permit physically lists the employer's name, NRIC number, and residential address, and the employer is legally termed the 'permit holder' while the worker is the 'foreign employee' registered under that permit. MOM's Work Permit conditions include a $5,000 security bond the employer must post, which is forfeited if the worker becomes 'missing'",
                "legal_basis": "EFMA Part IV, s.7(1): 'No person shall employ a foreign employee except under and in accordance with a valid work permit.' The work permit is issued TO the employer; s.5(3) allows MOM to impose conditions on the employer as permit holder. The $5,000 security bond (MOM Work Permit Condition 5) incentivizes employers to restrict worker movement — TWC2's 2017 report 'Worse Off for Working' documented that employers interpret the bond as a financial reason to confiscate the worker's passport and restrict days off, since the employer loses $5,000 if the worker 'absconds'",
                "sector": "domestic_work",
                "corridor": "PH-SG",
                "indicator_action_ids": [],
                "red_flag_context": "The EFMA's employer-as-permit-holder structure means the worker has no independent immigration document — their legal right to be in Singapore exists only as a condition attached to their employer's permit. TWC2 documented that this creates 'a structural power imbalance that no amount of worker education can overcome' because the employer can cancel the permit with 14 days' notice (EFMA s.7(4A)), triggering a 14-day Special Pass window after which the worker must leave Singapore",
            },
            {
                "id": "dc004_s2",
                "description": "The employer holds the worker's Philippine passport in a bedroom drawer and provides a photocopy for the worker to carry, stating 'all employers do this — it's for your own protection so it doesn't get stolen in Orchard Road or Little India' — the worker's only identification becomes the photocopied passport and a Work Permit card that may or may not be given to the worker (MOM guidelines say the employer 'should' give the card to the worker but this is not legally enforced)",
                "legal_basis": "MOM's Employment of Foreign Manpower (Work Passes) Regulations s.4(2)(b) states employers 'shall not retain the foreign employee's passport' — violation is punishable by fine up to $10,000 and/or imprisonment up to 12 months. However, HOME Singapore's 2015 report 'Home Sweet Home' found that 24% of 670 surveyed foreign domestic workers had their passports held by employers. Enforcement relies entirely on worker complaints to MOM, which requires visiting the MOM Services Centre at 1500 Bendemeer Road (formerly Havelock Road) — a trip that requires the employer's permission during working hours or uses the worker's single mandatory day off",
                "sector": "domestic_work",
                "corridor": "PH-SG",
                "indicator_action_ids": [],
                "red_flag_context": "Despite MOM's clear prohibition on passport retention, HOME's 24% finding and TWC2's research show the practice persists because: (1) workers fear employer retaliation and Work Permit cancellation, (2) the complaint mechanism requires physical visit to MOM Services Centre, (3) workers' day off (if given — 40% of HOME's surveyed MDWs did not receive regular days off) is their only chance to seek help, and (4) the $5,000 security bond incentivizes employers to restrict movement. The HOME shelter in Geylang provides emergency housing for workers who flee, but capacity is limited to approximately 60 beds",
            },
            {
                "id": "dc004_s3",
                "description": "The worker is required to attend monthly loan repayment sessions at the employment agency's office (typically in Peninsula Plaza or Lucky Plaza, the centers of Filipino and Indonesian worker services respectively) for a $2,000-4,000 SGD placement fee — MOM caps agency fees at 2 months' salary, but the worker's salary is SGD 570/month (the current market rate, though there is no legal minimum wage for domestic workers in Singapore), meaning the legitimate cap is SGD 1,140 while actual fees charged are 2-3x higher through undisclosed 'training' and 'medical' fees. Monthly agency visits are supervised by the employer, who drives the worker to the agency and waits, consuming the worker's day off",
                "legal_basis": "MOM Employment Agencies (EA) Licence Conditions limit agency fees to max 2 months' salary per year of contract. Employment Agencies Act s.13(1) penalizes overcharging with fine up to $25,000 and/or imprisonment up to 2 years. But TWC2's 2017 'Worse Off for Working' report documented average actual fees of $3,000-4,000 SGD, with the excess disguised as training fees charged by affiliated companies in the Philippines before departure — outside MOM's jurisdictional reach",
                "sector": "domestic_work",
                "corridor": "PH-SG",
                "indicator_action_ids": [],
                "red_flag_context": "Monthly agency visits function as compliance monitoring: the worker must demonstrate continued employment (no complaints) to avoid the agency threatening to cancel the placement and demand immediate full repayment. The employer controls transportation to the agency, supervises the visit, and consumes the worker's only day off — combining debt servicing with movement surveillance. TWC2 documented cases where workers who missed agency payments were threatened with Work Permit cancellation by the agency, which has the contractual right to request MOM cancel the permit",
            },
        ],
        "chain_context": "Singapore's EFMA framework legally vests immigration status in the employer (not the worker), creating structural dependency from the first day. Combined with passport retention (24% prevalence per HOME 2015), the $5,000 security bond incentivizing employer control of worker movement, agency debt 2-3x above MOM's fee cap, and monthly agency repayment visits that consume days off — the worker's legal existence in Singapore (identity, immigration status, financial obligations, physical location) is entirely mediated through and controlled by the employer. MOM's regulatory framework includes strong prohibitions on paper (passport retention fine of $10,000, agency overcharging fine of $25,000) but enforcement mechanisms all require worker-initiated complaints that risk the employer exercising their unilateral power to cancel the Work Permit with 14 days' notice.",
        "emergent_risk": "Employer-vested identity with debt reinforcement: EFMA permit tied to employer + $5,000 bond incentivizing control + passport held by employer (24% per HOME) + agency debt 2-3x legal cap + monthly supervised repayment visits = no independent legal existence, with every protective mechanism requiring worker action that risks 14-day permit cancellation",
        "difficulty": "medium",
        "source_references": [
            "TWC2, 'Worse Off for Working: Abuse of Work Permit Holders in Singapore' (2017) — structural analysis of EFMA employer-permit system and agency fee overcharging",
            "HOME Singapore, 'Home Sweet Home: Work, Life, and Well-being of Foreign Domestic Workers in Singapore' (2015) — 24% passport retention rate among 670 surveyed MDWs, 40% without regular days off",
            "EFMA Part IV s.7(1) (permit issued to employer), s.7(4A) (14-day cancellation), MOM Work Permit Condition 5 ($5,000 security bond)",
            "Employment Agencies Act s.13(1) (fee overcharging penalties), MOM EA Licence Conditions (2-month fee cap)",
            "US TIP Report 2024, Singapore country narrative (Tier 1) — noted continued passport retention and excessive fees as forced labor risk factors despite strong legal framework",
        ],
        "corridors": ["PH-SG", "ID-SG", "MM-SG"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["retention of identity documents", "abuse of position of vulnerability"],
            "purpose": ["exploitation"],
        },
    },
    {
        "id": "document_control_005",
        "name": "Qatar Exit Permit System Mobility Block",
        "category": "document_control",
        "steps": [
            {
                "id": "dc005_s1",
                "description": "Nepali construction worker's employer applies for the worker's QID card (Qatar ID — a burgundy credit-card-sized document issued by the Ministry of Interior's Immigration Department bearing the worker's photo, QID number, nationality, sponsor name, and visa expiry date) which is registered at the company's labor camp address in the Doha Industrial Area (the sprawling worker accommodation zone south of Doha housing an estimated 300,000+ construction workers in barracks-style compounds)",
                "legal_basis": "Qatar's Law No. 21/2015 on the Regulation of the Entry, Exit, Residence and Sponsorship of Expatriates requires QID registration through the employer/sponsor via the MOI's online Metrash2 portal. Art. 8 of Law No. 21/2015 states the employer 'must return the passport to the worker after the completion of the residence permit procedures.' The ILO's Qatar office (established under the 2017 technical cooperation agreement) reported in its 2023 progress report that QID and passport were still routinely held by employers in 'centralized document management systems' at large construction projects",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "All identity documentation in Qatar is mediated through the employer via Metrash2 — the worker cannot apply for, renew, or replace a QID independently. Registration at the Industrial Area camp address (rather than a personal address) means the worker's legal residence is the company compound. Amnesty International's 2019 report 'Reality Check' documented that among construction workers at 2022 World Cup stadium sites, 'the vast majority did not have access to their passports or QIDs'",
            },
            {
                "id": "dc005_s2",
                "description": "The worker's passport is submitted to the company's 'Document Control Office' (DCO) — a centralized filing room present at major construction projects (including Lusail Stadium, Al Bayt Stadium, and Hamad International Airport expansion sites documented by Amnesty International) where a single room stores passports for 1,500-3,000 workers in numbered filing cabinets, managed by company HR staff who require 3-5 days written notice and supervisor approval for passport retrieval",
                "legal_basis": "Qatar Law No. 21/2015 Art. 8 explicitly requires passport return after residency processing. Law No. 13/2018 removed the exit permit requirement for most workers (except military/government and domestic workers). Law No. 19/2020 removed the NOC (No-Objection Certificate) requirement for job transfer. Despite these three major reforms, Amnesty International's 2019 'Reality Check' report and the ILO's 2020 progress assessment both documented that 'centralized storage' of passports continued as standard practice at large construction projects, with the 3-5 day retrieval process functioning as a de facto exit permit",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Scale of document retention (1,500-3,000 passports per DCO) demonstrates systematic institutional practice, not individual safekeeping. The 3-5 day retrieval requirement with supervisor approval converts a technically illegal practice (post-Law No. 21/2015) into an operational control mechanism: a worker needing to leave urgently (family emergency, medical evacuation, fleeing abuse) cannot physically access their travel document without employer cooperation. Amnesty International documented cases at World Cup sites where workers waited 2+ weeks for passport retrieval",
            },
            {
                "id": "dc005_s3",
                "description": "The worker's father dies in Kathmandu and they request emergency leave; the DCO states that passport retrieval requires a 'minimum 72-hour processing period' (standard company policy at Al Khor and Lusail project sites), plus the worker must obtain a NOC from the project manager — despite Law No. 19/2020 abolishing the NOC requirement for job transfer, companies continue to require internal NOCs for temporary travel as an 'administrative procedure' distinct from the abolished legal NOC",
                "legal_basis": "Law No. 19/2020 abolished the NOC requirement for permanent job transfer/exit, but did not address employer-internal 'no objection' processes for temporary travel. MADLSA (Ministry of Administrative Development, Labour and Social Affairs) Ministerial Decision No. 25/2020 established that workers can leave Qatar without employer consent by notifying the employer 72 hours in advance — but this notification mechanism requires the worker to already possess their passport (which is in the DCO) and to submit the notification through the MADLSA online portal (which requires QID, which may also be held by the employer)",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Administrative delay weaponized against reform intent: the 72-hour passport retrieval period mirrors and effectively recreates the abolished exit permit system. The internal NOC (distinct from the abolished legal NOC) gives the project manager discretionary veto power. MADLSA's own exit notification portal requires the worker to possess their QID and passport — documents held by the DCO — creating a circular dependency that the ILO's 2023 Qatar progress report acknowledged as 'a persistent implementation gap'",
            },
            {
                "id": "dc005_s4",
                "description": "The project manager informs the worker that leaving during the 'critical concrete-pouring phase' of the Al Khor highway project would constitute a breach of the MADLSA-registered employment contract's project completion clause, and the internal NOC will only be issued after the current milestone is complete — the worker is told that if they leave without the NOC, the company will file an 'absconding' report with MOI, which would result in a travel ban, fines, and potential deportation ban from all GCC countries under the mutual deportation notification system",
                "legal_basis": "Qatar Penal Code Art. 330 criminalizes breach of employment contract, though this provision was narrowed by Law No. 18/2020 to exclude workers leaving for non-payment. The GCC-wide Absconding Notification System allows an absconding report in one GCC country to result in entry bans across all six member states (Saudi Arabia, UAE, Kuwait, Bahrain, Oman, Qatar). US TIP Report 2024 (Qatar section, Tier 2) noted that 'employers continued to file absconding charges against workers who left without permission, effectively criminalizing their departure'",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Project milestones create indefinite mobility blocks: concrete-pouring, fit-out, commissioning — there is always a 'critical phase.' The absconding threat carries GCC-wide consequences (banned from returning to work in any Gulf country), devastating for a Nepali worker whose family depends on Gulf remittances. The combination of passport in DCO + internal NOC requirement + absconding threat + GCC-wide ban recreates the pre-reform kafala immobility system through operational rather than legal mechanisms",
            },
        ],
        "chain_context": "Qatar's 2015-2020 reform trilogy — Law No. 21/2015 (passport return mandate), Law No. 13/2018 (exit permit removal), Law No. 19/2020 (NOC abolition) — represents significant legislative progress that the ILO's technical cooperation program supported. But operational practices at large construction projects maintain document control through: (1) centralized DCO passport storage with multi-day retrieval processes, (2) internal 'administrative' NOCs distinct from the abolished legal NOC, (3) MADLSA exit notification requiring documents the worker doesn't possess, and (4) absconding threats carrying GCC-wide entry bans. Amnesty International's 'Reality Check' (2019) documented these patterns at World Cup stadium sites; the ILO's 2023 progress report acknowledged 'persistent implementation gaps' between reformed laws and workplace practices.",
        "emergent_risk": "Post-reform document control through operational circumvention: DCO passport storage (1,500-3,000 per facility, 3-5 day retrieval) + abolished-but-reconstituted internal NOC + MADLSA portal requiring confiscated documents + GCC-wide absconding ban threat = pre-reform immobility levels maintained through administrative rather than legal mechanisms, despite three successive reform laws",
        "difficulty": "hard",
        "source_references": [
            "Amnesty International, 'Reality Check: The State of Migrant Workers' Rights with Four Years to the Qatar 2022 World Cup' (2019) — documented passport retention and NOC persistence at stadium construction sites",
            "ILO, 'Progress Report on the Technical Cooperation Programme Between the Government of Qatar and the ILO' (2023) — acknowledged 'persistent implementation gaps'",
            "Qatar Law No. 21/2015 Art. 8 (passport return), Law No. 13/2018 (exit permit removal), Law No. 19/2020 (NOC abolition)",
            "MADLSA Ministerial Decision No. 25/2020 (72-hour exit notification mechanism)",
            "US TIP Report 2024, Qatar country narrative (Tier 2) — employers filing absconding charges against departing workers",
        ],
        "corridors": ["NP-QA", "BD-QA", "PH-QA", "IN-QA"],
        "palermo_elements": {
            "act": ["harbouring"],
            "means": ["retention of identity documents", "restriction of movement"],
            "purpose": ["forced labour"],
        },
    },
    {
        "id": "document_control_006",
        "name": "Jordan Garment Factory QIZ Worker Document Control",
        "category": "document_control",
        "steps": [
            {
                "id": "dc006_s1",
                "description": "Sri Lankan garment worker arrives at Queen Alia International Airport (Amman) and is transported directly to a Qualified Industrial Zone (QIZ) factory — either Al Hassan Industrial Zone (Irbid governorate, northern Jordan) or Ad-Dulayl QIZ (Zarqa governorate, 40km northeast of Amman) — where factory HR collects the worker's passport and work permit (issued by the Jordanian Ministry of Labour) stating both documents are needed for 'Ministry of Labour registration and residency card processing'; Tamkeen Fields for Aid documented in their 2023 report 'Working Conditions of Migrant Workers in Jordanian Industrial Zones' that at Al Hassan Industrial Zone alone, over 100 workers reported passports confiscated for periods exceeding 4 months",
                "legal_basis": "Jordan Labour Law No. 8/1996 Art. 29 prohibits employers from retaining workers' documents. The Anti-Human Trafficking Law No. 9/2009 Art. 3 criminalizes document retention as a trafficking indicator with penalties of 6 months to 10 years imprisonment. Despite these prohibitions, Tamkeen's 2023 field research at Al Hassan and Ad-Dulayl QIZs found systematic passport retention: 100+ workers at Al Hassan alone reported passports held for 4+ months, with factory management claiming 'Ministry registration' as justification for retention that far exceeded any processing timeline",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Tamkeen's documentation of 100+ workers with 4-month passport retention at a single QIZ (Al Hassan) demonstrates industrial-scale systematic practice. Jordan's QIZ factories operate under the 1996 US-Jordan-Israel Qualifying Industrial Zone agreement granting duty-free access to US markets — major US brands (Hanesbrands, Walmart suppliers, Target suppliers) are direct or indirect purchasers. Labour Law Art. 29 prohibition exists but Ministry of Labour inspection teams visit QIZ factories infrequently, and document retention is not a standard inspection checklist item per ILO Better Work Jordan's assessment",
            },
            {
                "id": "dc006_s2",
                "description": "The factory issues an internal ID badge (a laminated card with the worker's photo, factory employee number, dormitory room assignment, and meal schedule) that must be worn at all times within the QIZ compound — the badge is the only identification the worker possesses and functions as access control for the factory floor, dormitory building, cafeteria, and compound gate, replacing the government-issued work permit and passport that are locked in the HR office",
                "legal_basis": "Workplace identification systems are standard in manufacturing environments and are consistent with QIZ security protocols required by US Customs (which verifies QIZ product origin for tariff preferences). However, Tamkeen's 2023 report noted that at Al Hassan and Ad-Dulayl, internal badges effectively replaced government-issued ID: workers could not present any official identification to Jordanian police, Ministry of Labour inspectors, or embassy consular staff visiting the zones — the factory badge is not recognized outside the compound walls",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Internal badge substitution creates a parallel identity system: inside the QIZ compound, the worker exists as employee #4572 in Dormitory B; outside the compound, the worker has no identity documents recognized by Jordanian authorities. Tamkeen documented cases at Al Hassan where workers attempting to file complaints at the Irbid Governorate Ministry of Labour branch office were unable to prove their identity or legal work status because their passport, work permit, and residency card were all held by the factory HR department",
            },
            {
                "id": "dc006_s3",
                "description": "Workers at Al Hassan or Ad-Dulayl QIZ who wish to leave the factory compound on their weekly rest day must submit a 'gate pass request' (talab khurooj) to factory security 24 hours in advance, which requires written approval from their production line supervisor — the gate pass specifies departure time, return time (typically 6-hour window), and destination; requests to visit the Sri Lankan embassy in Amman (120km from Al Hassan) are routinely denied as 'too far' or 'not during production schedule'",
                "legal_basis": "Jordan's Constitution Art. 9 guarantees freedom of movement for all persons within the Kingdom. QIZ compound security protocols are established by the factory, not Jordanian law — there is no legal basis for restricting movement of legally employed workers outside working hours. ILO Better Work Jordan's assessment of QIZ factory conditions flagged gate pass systems as 'inconsistent with freedom of movement protections' but noted that compound security was framed as 'worker safety in rural industrial areas' rather than confinement",
                "sector": "manufacturing",
                "corridor": "LK-JO",
                "indicator_action_ids": [],
                "red_flag_context": "Gate pass requirement with supervisor approval converts the QIZ compound into a controlled environment where the worker's movement outside working hours requires employer permission — violating the freedom of movement guaranteed by Jordan's Constitution Art. 9. Denying embassy access (Amman, 120km from Al Hassan) prevents workers from obtaining emergency travel documents, reporting passport confiscation to consular officials, or accessing embassy-provided legal assistance. Tamkeen's 2023 report documented workers at Al Hassan who did not leave the compound for months because gate passes were repeatedly denied during 'high production periods'",
            },
        ],
        "chain_context": "Jordan's QIZ factories operate under the 1996 US-Jordan-Israel QIZ agreement that grants duty-free US market access — brands including Hanesbrands, Walmart suppliers, and Target suppliers source from these zones. The document control chain — passport confiscation (100+ workers affected for 4+ months at Al Hassan per Tamkeen 2023), internal badge substitution eliminating government-recognized identity, gate pass systems with supervisor approval restricting constitutional freedom of movement — creates compound-based confinement within an otherwise legal employment framework. Labour Law No. 8/1996 Art. 29 prohibits document retention, Anti-Trafficking Law No. 9/2009 Art. 3 criminalizes it, and the Constitution Art. 9 guarantees freedom of movement — but enforcement in remote QIZs depends on Ministry of Labour inspections that ILO Better Work Jordan found do not systematically check for document retention or movement restriction.",
        "emergent_risk": "QIZ compound confinement through document substitution: passport retained 4+ months (violating Art. 29, documented by Tamkeen at 100+ worker scale at Al Hassan alone) + internal badge replacing government ID + gate pass system denying embassy access = worker physically confined in remote industrial zone despite three separate legal protections (Labour Law, Anti-Trafficking Law, Constitution)",
        "difficulty": "medium",
        "source_references": [
            "Tamkeen Fields for Aid, 'Working Conditions of Migrant Workers in Jordanian Industrial Zones' (2023) — documented 100+ workers at Al Hassan QIZ with passports confiscated for 4+ months",
            "Jordan Labour Law No. 8/1996 Art. 29 (document retention prohibition), Anti-Human Trafficking Law No. 9/2009 Art. 3 (trafficking indicators)",
            "ILO Better Work Jordan, 'Garment Industry Assessment' — flagged gate pass systems as inconsistent with freedom of movement",
            "US TIP Report 2024, Jordan country narrative (Tier 2) — QIZ factory conditions and passport confiscation noted as ongoing concerns",
            "Jordan Constitution Art. 9 (freedom of movement guarantee)",
        ],
        "corridors": ["LK-JO", "BD-JO", "PH-JO"],
        "palermo_elements": {
            "act": ["harbouring"],
            "means": ["retention of identity documents", "restriction of movement"],
            "purpose": ["forced labour"],
        },
    },
    {
        "id": "document_control_007",
        "name": "Thailand Fishing Vessel Seabook Dependency Chain",
        "category": "document_control",
        "steps": [
            {
                "id": "dc007_s1",
                "description": "Myanmar fisher is registered by the boat owner (jao khong ruea) at the Samut Sakhon PIPO (Port-in Port-out) center — one of 32 PIPO inspection centers established by the Royal Thai Government in 2015 under the Emergency Decree on Fisheries B.E. 2558 — where the boat owner presents the fisher's three identity/work documents: (1) seabook (Seaman's Book, issued by the Marine Department of Thailand, a blue booklet containing the fisher's photo, nationality, vessel assignment, and fishing license area), (2) pink card (tor ror 38/1, the migrant worker registration card issued under the Cabinet Resolution on migrant worker registration, bearing the worker's photo and employer name), and (3) passport (Myanmar-issued, often obtained through a broker at the Myawaddy or Ranong border crossing for THB 5,000-15,000). The boat owner registers as the 'holder responsible for crew documents' on the PIPO crew manifest",
                "legal_basis": "Royal Ordinance on Fisheries B.E. 2558 (2015) s.83 requires vessel operators to maintain crew documentation for PIPO inspection. Marine Department regulations require seabooks to be carried aboard the vessel under the vessel operator's custody. The pink card (tor ror 38/1) registration links the worker to a specific employer. EJF's 2019 report 'Blood and Water' documented that 'in the vast majority of cases, fishing vessel owners retain all identity documents of migrant crew members, including passports, seabooks, and work permits' — at PIPO centers in Samut Sakhon, Songkhla, and Ranong, inspectors verify crew lists against documents held by the captain, not by individual fishers",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Three separate identity/work documents — seabook, pink card, passport — all held by the boat owner from the first day of registration. The PIPO system, designed to prevent trafficking by tracking crew movements, inadvertently formalized employer custody of documents by requiring the vessel operator (not individual crew) to present documents at inspection. EJF documented that at Samut Sakhon PIPO (Thailand's largest, processing 3,000+ vessel movements monthly), inspectors accepted boat-owner-presented documents as standard procedure",
            },
            {
                "id": "dc007_s2",
                "description": "The fisher works 18-22 hour shifts during multi-month fishing voyages (3-6 months is standard for distant-water trawlers operating in the Andaman Sea, Gulf of Thailand, or Indonesian waters south of Natuna Islands) — the boat captain (nai ruea) is sole custodian of all crew documents during the voyage, stored in the captain's cabin alongside the vessel's fishing license, PIPO clearance log, and crew manifest. Transshipment at sea (transferring catch to larger refrigerated cargo vessels or 'motherships') extends voyages indefinitely by eliminating the need to return to port for offloading",
                "legal_basis": "Marine Department regulations require the captain to maintain crew manifests for at-sea inspection by Royal Thai Navy (CCCIF — Command Center for Combating Illegal Fishing) patrol vessels. Thailand ratified ILO Convention C188 (Work in Fishing Convention) in 2019, which requires 'fishers shall be given a document containing a record of their employment' (Art. 14) — but EJF's monitoring found that C188 implementation focused on larger commercial vessels (>24m) while the majority of Thai fishing exploitation occurs on smaller vessels (10-24m) that receive less rigorous inspection",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Physical isolation at sea (3-6 months, extended by transshipment) combined with complete document control by the captain makes this the most extreme document retention scenario: the worker cannot leave the vessel, has no documents, cannot communicate (no phone signal at sea), and is in the physical control of the captain 24 hours/day. EJF's 'Blood and Water' documented cases where fishers worked 2+ years at sea without touching land due to repeated at-sea transshipment, with documents remaining in the captain's cabin the entire time",
            },
            {
                "id": "dc007_s3",
                "description": "When the vessel docks at a foreign port — Benjina (Indonesia), Ambon (Indonesia), or Penang (Malaysia) — the captain retains all crew documents, citing Royal Thai Navy regulations that require the captain to present a complete crew manifest and matching documents to port authorities upon entry and exit. Fishers are told that if they leave the vessel at a foreign port without documents, they will be arrested as undocumented migrants by Indonesian or Malaysian immigration police (Imigrasi or Jabatan Imigresen respectively) and face deportation to Myanmar, not Thailand — losing all unpaid wages owed to them",
                "legal_basis": "International port entry procedures do require vessel operators to present crew documentation (ISPS Code, FAO Port State Measures Agreement which Thailand ratified in 2016). However, the captain's refusal to return documents to individual crew members at port has no legal basis — it exploits the legitimate port documentation requirement. EJF documented cases in Benjina (Aru Islands, Indonesia) where Myanmar fishers were unable to leave vessels despite being in port for days because they had no identification documents and faced arrest by Indonesian authorities if found ashore without documentation",
                "sector": "fishing",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Foreign port docking represents the fisher's best chance to escape — but without documents, stepping off the vessel means becoming an undocumented person in Indonesia or Malaysia, subject to arrest by Imigrasi/Jabatan Imigresen enforcement. The captain's control of all three documents (seabook, pink card, passport) at foreign ports was specifically highlighted in the US TIP Report 2024 (Thailand section, Tier 2) as a key forced labor indicator. AP's 2015 investigation of Benjina — which led to the rescue of 2,000+ fishers — found that document confiscation by captains was the primary mechanism preventing fishers from seeking help at foreign ports",
            },
        ],
        "chain_context": "Thailand's post-2015 fishing industry reforms — the PIPO center system (32 centers), CCCIF navy patrols, ratification of ILO C188, and the FAO Port State Measures Agreement — were designed to combat trafficking in the fishing sector after the AP Benjina investigation exposed the enslavement of thousands of fishers. But the reforms inadvertently formalized employer custody of documents by requiring vessel operators to present crew documentation at PIPO inspections. Combined with multi-month voyages extended by at-sea transshipment, captain-only document custody during sea operations, and the impossibility of seeking help at foreign ports without identification, the document control chain creates maritime captivity that is structurally invisible to shore-based monitoring systems. EJF's 'Blood and Water' (2019) documented these patterns across Samut Sakhon, Songkhla, and Ranong ports.",
        "emergent_risk": "Maritime document captivity through reform co-optation: seabook + pink card + passport all held by captain (formalized by PIPO inspection procedure) + 3-6 month voyages extended by transshipment + no documents at foreign ports (Benjina, Ambon, Penang) = total document-based confinement at sea, with shore-based monitoring systems (PIPO, CCCIF) unable to detect on-vessel document retention during extended voyages",
        "difficulty": "hard",
        "source_references": [
            "EJF, 'Blood and Water: Human Rights Abuse in the Global Seafood Industry' (2019) — documented systematic document retention across Thai fishing fleet, including at Samut Sakhon, Songkhla, and Ranong PIPO centers",
            "AP Investigation, 'Slaves May Have Caught the Fish You Bought' (Mar 2015) — Benjina, Aru Islands, Indonesia; led to rescue of 2,000+ enslaved fishers",
            "Royal Ordinance on Fisheries B.E. 2558 (2015) s.83 (PIPO crew documentation requirements)",
            "ILO Convention C188 (Work in Fishing Convention, ratified by Thailand 2019) Art. 14 (worker document access)",
            "US TIP Report 2024, Thailand country narrative (Tier 2) — document confiscation on fishing vessels as key forced labor indicator",
        ],
        "corridors": ["MM-TH", "KH-TH", "LA-TH"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["retention of identity documents", "restriction of movement", "abuse of position of vulnerability"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "document_control_008",
        "name": "Hong Kong Foreign Domestic Helper Visa Tying Chain",
        "category": "document_control",
        "steps": [
            {
                "id": "dc008_s1",
                "description": "Indonesian domestic worker's FDH (Foreign Domestic Helper) employment visa — issued by the Hong Kong Immigration Department (Immigration Tower, 7 Gloucester Road, Wan Chai) — specifies the employer's full name, residential address, and HKID number; the visa stamp in the worker's passport states 'employment as domestic helper with [Employer Name] only' and is valid for a 2-year contract period. The worker also signs the mandatory Standard Employment Contract (SEC) — a government-prescribed form (ID 407) specifying minimum allowable wage (currently HKD 4,870/month as of September 2023), duties limited to domestic work, and the mandatory live-in requirement",
                "legal_basis": "Hong Kong Immigration Ordinance Cap 115 s.11 governs conditions of stay for FDH visa holders; the employer-specific visa condition is a standard immigration restriction. The SEC (form ID 407) is mandated by the Immigration Department as a condition of FDH visa issuance — clause 2 specifies the duties, clause 3 mandates the live-in requirement ('the Helper shall reside in the employer's residence'), clause 5 sets the minimum wage. Justice Centre Hong Kong's 2016 report 'Coming Clean' surveyed 1,049 FDHs and found that 17.4% experienced conditions consistent with ILO forced labor indicators, with employer-specific visa tying identified as the structural foundation of vulnerability",
                "sector": "domestic_work",
                "corridor": "ID-HK",
                "indicator_action_ids": [],
                "red_flag_context": "The employer-specific visa + SEC structure means the worker's legal status, housing (live-in requirement), minimum wage, and permitted activities are all defined in relation to a single employer. Justice Centre Hong Kong's 17.4% forced labor indicator prevalence among 1,049 surveyed FDHs demonstrates that the structural design — not individual employer behavior — creates systemic vulnerability. The worker cannot freelance, take a second job, or change employers without a new visa application processed through Immigration Tower",
            },
            {
                "id": "dc008_s2",
                "description": "If the worker is terminated or resigns, Immigration Ordinance Cap 115 s.14 provides only 14 days to find a new employer willing to sponsor a new FDH visa, submit the application to the Immigration Department, and receive approval — or the worker must leave Hong Kong. During this 14-day window, the worker has no income (terminated), may have no housing (SEC clause 3 live-in requirement means housing was tied to employment), and must navigate the Immigration Department application process while potentially homeless. The Mission for Migrant Workers (MFMW, 2 Jordan Road, Kowloon) and Bethune House shelter provide emergency housing for terminated FDHs, but capacity is limited to approximately 40-50 beds serving a population of 400,000+ FDHs in Hong Kong",
                "legal_basis": "Immigration Ordinance Cap 115 s.14: a person whose permission to remain has been cancelled must leave Hong Kong within the period specified (14 days for FDHs per standard Immigration Department practice). New FDH visa applications typically take 4-8 weeks to process — far longer than the 14-day window. The worker can apply for an extension of stay, but approval is discretionary and requires demonstrating an active job search. Justice Centre Hong Kong's 'Coming Clean' report found that the 14-day rule was the 'single most significant structural factor' driving FDHs to endure exploitative conditions rather than terminate employment",
                "sector": "domestic_work",
                "corridor": "ID-HK",
                "indicator_action_ids": [],
                "red_flag_context": "The 14-day rule creates a mathematically impossible situation: visa processing takes 4-8 weeks but the worker has 14 days. This structural impossibility means the 14-day rule functions not as an immigration management tool but as a coercion mechanism — the worker knows that termination (whether voluntary or involuntary) triggers a near-certain forced departure from Hong Kong, loss of income, and inability to repay recruitment debts (typically HKD 10,000-30,000 owed to Indonesian placement agencies). MFMW's annual surveys consistently show that 70%+ of FDHs who seek shelter assistance cite the 14-day rule as the reason they endured abuse before finally leaving",
            },
            {
                "id": "dc008_s3",
                "description": "SEC clause 3 mandates that the FDH 'shall reside in the employer's residence' (the live-in requirement) — the worker sleeps in the employer's apartment (often in a partitioned section of the living room, a converted storage room, or sharing a room with the employer's children in Hong Kong's notoriously small apartments averaging 40-60 sqm). The employer deducts HKD 300-500/month from the HKD 4,870 minimum wage for 'food and accommodation' under SEC clause 6 (which permits 'reasonable' deductions). The live-in requirement means the worker's housing, workplace, and personal space are a single location controlled entirely by the employer — termination simultaneously means loss of job, income, housing, and the 14-day countdown to departure",
                "legal_basis": "SEC clause 3 (live-in requirement) is a non-negotiable condition of the FDH visa per Immigration Department policy — FDHs cannot live independently under any circumstances, even if both employer and worker agree. Clause 6 permits food/accommodation deductions but does not cap the amount, leading to wide variation. Hong Kong's Court of Final Appeal in Vallejos v Commissioner of Registration [2013] HKCFA 20 upheld the exclusion of FDHs from the right of abode, reinforcing the temporary and employer-dependent nature of FDH status. Justice Centre Hong Kong found that the live-in requirement was present in 100% of forced labor indicator cases — it is the structural mechanism that converts employment dependency into physical control",
                "sector": "domestic_work",
                "corridor": "ID-HK",
                "indicator_action_ids": [],
                "red_flag_context": "The mandatory live-in requirement collapses the worker's entire life — employment, housing, personal space, rest time — into a single employer-controlled location, with no legal option for independent living. Combined with the 14-day rule (s.14 Cap 115), termination triggers simultaneous loss of job + home + legal status, creating what Justice Centre Hong Kong called a 'triple jeopardy' that compels workers to endure exploitative conditions. MFMW documented cases of FDHs sleeping in bathrooms, kitchens, and hallways in employers' apartments — conditions that would violate housing standards in any other employment context but are structural features of the SEC live-in mandate",
            },
        ],
        "chain_context": "Hong Kong's FDH system is among the most regulated domestic worker frameworks in Asia — government-mandated SEC, minimum wage (HKD 4,870/month), standardized contract terms, Labour Department complaint mechanism, and Immigration Department oversight. Yet the structural combination of employer-specific visa (Cap 115), the 14-day rule (s.14), and the mandatory live-in requirement (SEC clause 3) creates a regulatory framework where the worker's housing, income, immigration status, physical location, and legal existence in Hong Kong are all controlled by a single entity. Justice Centre Hong Kong's 2016 'Coming Clean' study — surveying 1,049 FDHs — found 17.4% experienced forced labor indicators, with the structural trio (visa tying + 14-day rule + live-in requirement) present in every case. No individual regulation is exploitative in isolation, but together they create what MFMW's annual surveys describe as 'single-point-of-failure dependency' where the employer is simultaneously landlord, employer, immigration sponsor, and controller of the worker's physical space 24 hours/day.",
        "emergent_risk": "Regulatory dependency trap through structural design: employer-specific FDH visa (Cap 115 s.11) + 14-day rule making termination functionally equivalent to deportation (s.14, with 4-8 week visa processing vs 14-day window) + mandatory live-in requirement (SEC clause 3, upheld by Vallejos CFA ruling) = termination triggers simultaneous loss of job, home, legal status, and country of residence — producing 17.4% forced labor indicator prevalence among 1,049 surveyed FDHs (Justice Centre HK 2016)",
        "difficulty": "hard",
        "source_references": [
            "Justice Centre Hong Kong, 'Coming Clean: The Prevalence of Forced Labour and Human Trafficking for the Purpose of Forced Labour Amongst Migrant Domestic Workers in Hong Kong' (2016) — 1,049 FDH survey, 17.4% forced labor indicator prevalence",
            "Mission for Migrant Workers (MFMW), 2 Jordan Road, Kowloon — annual survey data on 14-day rule impact, shelter capacity, and accommodation conditions",
            "Hong Kong Immigration Ordinance Cap 115 s.11 (conditions of stay), s.14 (14-day rule after termination)",
            "Standard Employment Contract (form ID 407) clause 3 (live-in requirement), clause 5 (minimum wage HKD 4,870), clause 6 (deductions)",
            "Vallejos v Commissioner of Registration [2013] HKCFA 20 — Court of Final Appeal upholding FDH exclusion from right of abode",
            "US TIP Report 2024, Hong Kong SAR country narrative — structural vulnerability of FDH visa-tying and 14-day rule",
        ],
        "corridors": ["ID-HK", "PH-HK"],
        "palermo_elements": {
            "act": ["harbouring"],
            "means": ["abuse of position of vulnerability", "coercion"],
            "purpose": ["exploitation"],
        },
    },
]
