"""
Gender-specific exploitation chains — patterns where gender dynamics create
distinct trafficking vulnerabilities including forced marriage, pregnancy-based
coercion, sexual harassment escalation, beauty industry recruitment fraud,
caregiver-to-servitude pipelines, masculinity-based workplace exploitation,
LGBTQ+ identity weaponization, and reproductive coercion in agriculture.

These chains address the gendered dimensions of human trafficking and forced
labor. Gender is not merely a demographic descriptor but a structural axis of
exploitation: women, men, and LGBTQ+ individuals face different recruitment
tactics, control mechanisms, and barriers to escape. Each chain documents how
gender-specific vulnerabilities are systematically leveraged through sequences
of individually legal or culturally normalized steps.

Sources: UN Women, CEDAW Committee General Recommendations, ILO gender and
forced labor studies, Human Rights Watch domestic worker and LGBTQ+ reports,
ILGA World criminalization data, Polaris Project, Guardian migrant worker
investigations, Farmworker Justice, Centro de los Derechos del Migrante.
"""

CHAINS: list[dict] = [
    {
        "id": "gender_specific_001",
        "name": "Forced Marriage as Labor Trafficking Mechanism",
        "category": "gender_specific",
        "steps": [
            {
                "id": "gs001_s1",
                "description": "A family in rural Pakistan or Bangladesh arranges the marriage of their daughter to a man residing in the UK, receiving a bride price (haq mehr or jahez reversal) of $5,000-$15,000. The marriage is conducted under local personal status law, often with the woman's nominal consent obtained under intense family pressure. The arrangement is facilitated by a transnational matchmaker operating within diaspora networks who receives a commission from the groom's family.",
                "legal_basis": "Marriage is a legally recognized institution under Pakistani Muslim Family Laws Ordinance 1961 and Bangladeshi Muslim Marriages and Divorces (Registration) Act 1974; bride price is a documented component of nikah contracts; transnational marriage facilitation is a common diaspora community service",
                "sector": "domestic_work",
                "corridor": "PK-UK",
                "indicator_action_ids": [],
                "red_flag_context": "The bride price creates a financial transaction around the woman's person; family pressure negates meaningful consent; the matchmaker's commission incentivizes placement volume over the woman's welfare; the marriage becomes a migration mechanism rather than a genuine partnership",
            },
            {
                "id": "gs001_s2",
                "description": "The woman arrives in the UK on a spousal visa (Appendix FM to the Immigration Rules), which grants her leave to remain for 33 months tied to the marriage. During the first months, the husband confiscates her passport and biometric residence permit, stating he will keep all documents 'safe' in a locked drawer. The woman has limited English proficiency and no independent knowledge of the UK immigration system.",
                "legal_basis": "Spousal visa issuance follows standard UK immigration procedures; the husband as the sponsoring partner is the primary point of contact with the Home Office; document safekeeping by the household's primary English speaker is presented as a practical arrangement",
                "sector": "domestic_work",
                "corridor": "PK-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Spousal visa dependency creates immigration control: the woman's right to remain depends on the marriage continuing; document confiscation eliminates her ability to travel, access services, or prove her identity independently; language barriers compound the isolation",
            },
            {
                "id": "gs001_s3",
                "description": "The husband's extended family operates a small business — a restaurant, grocery shop, or textile workshop — and the woman is expected to work in the business as part of her 'family duties.' She works 10-14 hour shifts without wages, with the family characterizing her labor as a wife's contribution to the household economy. When she asks about pay, the mother-in-law tells her that 'in our culture, wives don't take salary from family.'",
                "legal_basis": "Family members working in family businesses is a recognized practice; the UK does not require formal employment contracts between spouses in a family enterprise; cultural norms around spousal economic contribution vary across communities",
                "sector": "domestic_work",
                "corridor": "BD-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Unpaid labor in the husband's business is forced labor disguised as cultural expectation; the 'family duty' framing exploits cultural norms to extract commercial labor without compensation; the woman generates economic value for the business while receiving no independent income",
            },
            {
                "id": "gs001_s4",
                "description": "The husband controls all household finances, providing the woman with no bank account, no cash allowance, and no access to household income. Her phone usage is monitored and restricted to calls with family in Pakistan or Bangladesh, which the husband listens to. Social contacts outside the extended family are prohibited under the justification that 'people will talk' and it would damage family honor (izzat).",
                "legal_basis": "Household financial management by the primary earner is a common domestic arrangement; monitoring phone usage and social contacts is characterized as protective concern for a newly arrived family member adjusting to a new country",
                "sector": "domestic_work",
                "corridor": "PK-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Total financial, communicative, and social control replicates the isolation mechanisms of labor trafficking; the honor-based framing transforms control into a cultural obligation that the woman may internalize; without money, contacts, or communication freedom, she cannot seek help",
            },
            {
                "id": "gs001_s5",
                "description": "When the woman expresses a desire to leave the marriage, the husband threatens to report her to the Home Office and have her visa cancelled, resulting in deportation. The family in Pakistan or Bangladesh pressures her to stay, citing the shame of divorce and the expectation that she would need to repay the $5,000-$15,000 bride price. The husband tells her that under UK immigration rules, she has no recourse to public funds and would be destitute if she leaves.",
                "legal_basis": "Spousal visa holders are subject to the 'no recourse to public funds' condition under Immigration Rules; the husband's immigration reporting is technically available; bride price repayment expectations are governed by personal status and customary law in the origin country",
                "sector": "domestic_work",
                "corridor": "BD-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Triple coercion trap: immigration threat (deportation), financial threat (bride price repayment), and social threat (family shame) close every exit route simultaneously; the UK's Forced Marriage (Civil Protection) Act 2007 and the Destitute Domestic Violence Concession exist precisely for this scenario, but the woman has no way to learn about them without independent contacts or legal advice",
            },
        ],
        "chain_context": "Forced marriage as a trafficking mechanism operates at the intersection of immigration law, personal status law, cultural honor systems, and family business economics. Each element — culturally recognized marriage, spousal visa, family business participation, household financial management, immigration dependency — is individually lawful or culturally normalized. But the chain converts a woman into an unpaid laborer whose exit is blocked by immigration status, bride price debt, and family honor. The UK Forced Marriage Unit handled 1,355 cases in 2022, with Pakistan (44%) and Bangladesh (9%) among the top origin countries. CEDAW General Recommendation No. 21 explicitly links forced marriage to trafficking and servitude.",
        "emergent_risk": "Marriage-laundered forced labor: bride price transaction + spousal visa dependency + unpaid family business labor + financial and social isolation + triple-threat coercion = trafficking disguised as cultural marriage practice",
        "difficulty": "expert",
        "source_references": [
            "CEDAW Committee — General Recommendation No. 21 on Equality in Marriage and Family Relations",
            "UK Forced Marriage Unit — Statistics 2022",
            "UK Forced Marriage (Civil Protection) Act 2007",
            "IOM — Forced Marriage and Human Trafficking Nexus Research 2023",
            "Human Rights Watch — Marry Before Your House is Swept Away: Forced Marriage in Bangladesh",
            "Karma Nirvana — UK Forced Marriage and Honour-Based Abuse Data",
        ],
        "corridors": ["PK-UK", "BD-UK", "VN-CN", "MM-CN"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["coercion", "deception", "abuse of position of vulnerability", "debt bondage"],
            "purpose": ["forced labour", "exploitation", "slavery or practices similar to slavery"],
        },
    },
    {
        "id": "gender_specific_002",
        "name": "Pregnancy-Based Employment Termination Chain",
        "category": "gender_specific",
        "steps": [
            {
                "id": "gs002_s1",
                "description": "A Filipina or Ethiopian domestic worker undergoes a mandatory pre-departure pregnancy test at a government-accredited medical clinic as part of the Overseas Filipino Workers (OFW) medical clearance process or Ethiopian pre-departure screening. The test is a standard requirement for obtaining an Overseas Employment Certificate (OEC) in the Philippines or clearance from the Ethiopian Ministry of Labour. Workers who test positive are barred from departure.",
                "legal_basis": "Pre-departure medical screening including pregnancy testing is mandated by several Gulf destination countries as a visa issuance condition; the Philippines' POEA Standard Employment Contract requires medical fitness certification; these requirements are framed as worker health and safety measures",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Mandatory pregnancy screening at departure treats female fertility as an employment disqualification; the test is not applied to male workers; it establishes from the outset that the woman's reproductive status is subject to employer and state control as a condition of her economic migration",
            },
            {
                "id": "gs002_s2",
                "description": "The employment contract — often the Saudi Standard Contract for Domestic Workers or the Lebanese Unified Contract — contains an explicit clause stating that pregnancy constitutes grounds for immediate contract termination and repatriation at the worker's expense. Some contracts additionally specify that the worker must not become pregnant during the two-year contract period. The clause is presented as a standard term that all domestic workers sign.",
                "legal_basis": "Employment contracts in Gulf states are approved by the destination country's ministry of labor; contract terms regarding fitness for duty are standard across domestic worker contracts; employers argue that pregnancy renders a live-in domestic worker unable to perform contracted duties",
                "sector": "domestic_work",
                "corridor": "ET-LB",
                "indicator_action_ids": [],
                "red_flag_context": "A contractual pregnancy ban converts a fundamental reproductive right into a terminable offense; CEDAW Article 11(2)(a) explicitly prohibits dismissal on grounds of pregnancy; the contract effectively requires the worker to surrender reproductive autonomy for two years as a condition of employment",
            },
            {
                "id": "gs002_s3",
                "description": "In certain Gulf states, employers provide or mandate that domestic workers take employer-administered contraception, including injectable contraceptives (Depo-Provera) given by the employer or a family member rather than a healthcare professional. Human Rights Watch documented cases in Saudi Arabia and the UAE where workers reported being given injections or pills by their employer without full informed consent or medical supervision.",
                "legal_basis": "Employers present contraception provision as a benefit that protects the worker from pregnancy-related contract termination; injectable contraceptives are available over-the-counter or through pharmacies in many Gulf states; the employer frames this as acting in the worker's interest",
                "sector": "domestic_work",
                "corridor": "PH-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Employer-administered contraception without informed medical consent is a violation of bodily autonomy and reproductive rights; the power imbalance between employer and live-in domestic worker makes genuine consent impossible; ILO Convention C183 (Maternity Protection) establishes that maternity should not be a source of discrimination in employment",
            },
            {
                "id": "gs002_s4",
                "description": "A domestic worker who becomes pregnant despite these measures faces immediate contract termination. The employer notifies the recruitment agency, which processes the termination and arranges repatriation. Under Saudi Labour Law, domestic workers are excluded from general labor protections including maternity leave provisions under Royal Decree M/51. The worker receives no severance pay, no end-of-service benefits, and must cover the cost of her own repatriation flight ($400-$800) or have it deducted from any unpaid wages.",
                "legal_basis": "Saudi Labour Law Article 7 excludes domestic workers from the general labor code's protections; contract termination for cause (pregnancy clause violation) follows the standard contract terms; repatriation costs for terminated workers are allocated per the contract's termination provisions",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Pregnancy termination means the worker loses income, housing, and legal immigration status simultaneously; exclusion of domestic workers from labor law maternity protections creates a gender-specific legal gap; the repatriation cost from unpaid wages functions as a financial penalty for becoming pregnant",
            },
            {
                "id": "gs002_s5",
                "description": "The terminated worker is repatriated with outstanding recruitment debt (typically $1,000-$3,000 paid to the agency in the origin country), no severance, and potential unpaid wages for the final month of employment that the employer withholds as 'breach of contract' penalty. In the Philippines, the worker may face social stigma for returning pregnant and unemployed. The recruitment agency may blacklist the worker from future placements, and the worker's family, who depended on remittances, faces immediate financial hardship.",
                "legal_basis": "Recruitment debt repayment obligations survive contract termination; employer wage withholding for contractual breach is claimed under the employment contract's termination provisions; agency placement records are maintained as standard business practice",
                "sector": "domestic_work",
                "corridor": "ID-KW",
                "indicator_action_ids": [],
                "red_flag_context": "The chain converts pregnancy into a comprehensive punishment: debt remains, wages are confiscated, future employment is blocked, and social stigma compounds the financial loss; Human Rights Watch's 2008 report 'As If I Am Not Human' documented this exact chain across hundreds of cases in Saudi Arabia; the entire system treats female reproductive capacity as an employer-controlled asset",
            },
        ],
        "chain_context": "The pregnancy-based employment termination chain weaponizes female reproductive biology against migrant domestic workers through a sequence of state-mandated screening, contractual prohibition, employer-controlled contraception, legal exclusion from maternity protections, and financial punishment upon termination. Each step is embedded in the legal and contractual framework of the Kafala system: pre-departure testing is a visa requirement, pregnancy clauses are standard contract terms, domestic worker exclusions are statutory, and repatriation costs are contractually allocated. CEDAW Article 11 and ILO Convention C183 directly address these practices, but neither instrument is effectively enforceable in Gulf destination countries. The result is a gender-specific forced labor mechanism where women must surrender reproductive autonomy as a condition of economic survival.",
        "emergent_risk": "Reproductive autonomy as employment condition: mandatory pregnancy screening + contractual pregnancy ban + employer-administered contraception + no maternity protections + financial punishment upon termination = gender-specific forced labor through reproductive coercion",
        "difficulty": "expert",
        "source_references": [
            "CEDAW Committee — Article 11 on Employment and Maternity Protection",
            "ILO — Convention C183 on Maternity Protection",
            "Human Rights Watch — 'As If I Am Not Human': Abuses against Asian Domestic Workers in Saudi Arabia 2008",
            "Saudi Labour Law Royal Decree M/51 — Domestic Worker Exclusions",
            "Amnesty International — My Sleep Is My Break: Exploitation of Migrant Domestic Workers in Qatar 2014",
            "ILO — Gender and Forced Labour in the Gulf States 2022",
        ],
        "corridors": ["PH-SA", "ET-LB", "PH-QA", "ID-KW"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["coercion", "abuse of position of vulnerability", "deception"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "gender_specific_003",
        "name": "Sexual Harassment Escalation in Isolated Workplaces",
        "category": "gender_specific",
        "steps": [
            {
                "id": "gs003_s1",
                "description": "An Ethiopian or Filipina domestic worker is placed in a private household in Beirut, Lebanon, or Riyadh, Saudi Arabia, through a licensed recruitment agency. The placement creates a one-to-one or one-to-family employment relationship inside a private residence with no co-workers, no workplace inspectors, and no public visibility. The household may include a single male employer or multiple adult males. The worker lives in the employer's home under a standard Kafala live-in arrangement.",
                "legal_basis": "Domestic worker placement in private households is the standard employment model under the Kafala system; live-in arrangements are contractually specified; the employer's home is legally a private residence, not a regulated workplace subject to labor inspection",
                "sector": "domestic_work",
                "corridor": "ET-LB",
                "indicator_action_ids": [],
                "red_flag_context": "Private household placement creates the most isolated workplace possible: no co-workers to witness abuse, no inspectors with right of entry, no security cameras in shared spaces, and the worker sleeps in the same building as the potential abuser; ILO estimates that 80% of domestic workers globally work in conditions of isolation",
            },
            {
                "id": "gs003_s2",
                "description": "The male employer or male family member begins making comments about the worker's appearance, initially framed as 'compliments' — commenting on her body, her clothing, or how she looks when cleaning. The worker is uncomfortable but has been instructed by the agency and by pre-departure orientation to 'be patient and respectful with the employer' and to 'adapt to the cultural environment.' When the worker adjusts her clothing to be more conservative, the employer comments on that too.",
                "legal_basis": "Comments between household members are interpersonal interactions within a private home; pre-departure orientation programs advise cultural sensitivity and patience during the adjustment period; verbal interactions do not constitute a legally defined offense in many jurisdictions",
                "sector": "domestic_work",
                "corridor": "PH-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Verbal sexual harassment in an isolated private home has no witnesses and no reporting mechanism; pre-departure training that emphasizes 'patience' and 'cultural adaptation' conditions the worker to tolerate boundary violations; the escalation from comments to physical contact follows a documented pattern in domestic worker abuse cases",
            },
            {
                "id": "gs003_s3",
                "description": "Physical boundary violations begin: the employer touches the worker's arm, back, or hair during interactions, enters her room without knocking, and appears when she is changing or bathing. These incidents are characterized as 'accidental' or attributed to the small living space. The worker has no lock on her door. When she attempts to avoid the employer, she is reprimanded for 'not being available when needed' as a live-in domestic worker.",
                "legal_basis": "Physical contact within a household is interpreted as incidental; employer access to all rooms in their own home is a property right; the live-in worker's availability is a contractual obligation; private space boundaries in shared living are described as cultural rather than legal matters",
                "sector": "domestic_work",
                "corridor": "ET-LB",
                "indicator_action_ids": [],
                "red_flag_context": "Escalation from verbal to physical harassment follows a predatory grooming pattern; the absence of a lockable door eliminates the worker's last physical boundary; being reprimanded for avoidance behavior punishes the worker's self-protective instincts and teaches her that resistance has professional consequences",
            },
            {
                "id": "gs003_s4",
                "description": "The worker contacts her recruitment agency in Lebanon (or calls the agency's local representative) to report the harassment and request a transfer to a different employer. The agency responds that the worker should 'be patient, it's just cultural differences' and that requesting a transfer would result in a three-month waiting period in the agency's shelter (effectively unpaid detention), after which the worker would need to repay the placement fee for the new employer. KAFA (Enough) Violence & Exploitation, a Lebanese NGO, has documented this exact agency response pattern in hundreds of cases.",
                "legal_basis": "Recruitment agencies manage employer-worker relationships as part of their placement service; transfer procedures involve contract cancellation and re-placement, which require processing time and may incur additional fees; agency mediation is the standard dispute resolution mechanism under the Kafala system",
                "sector": "domestic_work",
                "corridor": "PH-AE",
                "indicator_action_ids": [],
                "red_flag_context": "Agency dismissal of sexual harassment as 'cultural difference' re-victimizes the worker and blocks the only institutional complaint channel available; the three-month unpaid shelter period and re-placement fee create financial disincentives to reporting; the agency profits from both the original and replacement placements, incentivizing worker retention over protection",
            },
            {
                "id": "gs003_s5",
                "description": "Sexual assault occurs. When the worker attempts to report to police in Lebanon or Saudi Arabia, she faces multiple barriers: Lebanon has no specific law criminalizing sexual assault of domestic workers by employers and did not criminalize marital rape until the 2014 Law on Protection of Women and Family Members (and enforcement remains minimal). If the worker left the employer's home to reach a police station, she may face a counter-charge of 'absconding' — leaving the employer without permission, which is a criminal offense under the Kafala system. Saudi Arabia's anti-harassment law (Royal Decree A/96 of 2018) exists but enforcement for domestic workers is effectively nonexistent.",
                "legal_basis": "Criminal law applies to sexual assault in both countries, but domestic workers must navigate complex procedural requirements; leaving the employer's residence without permission constitutes absconding under Kafala regulations; police investigations require victim presence and cooperation over extended periods during which the worker has no income or housing",
                "sector": "domestic_work",
                "corridor": "ET-LB",
                "indicator_action_ids": [],
                "red_flag_context": "The legal system punishes the victim for seeking help: absconding charges criminalize the worker for escaping abuse; the counter-charge mechanism means reporting sexual assault triggers the worker's own prosecution; without independent housing, income, or legal status, the worker is trapped between enduring abuse and being criminalized for fleeing it — this is the defining feature of gender-specific trafficking in domestic work",
            },
        ],
        "chain_context": "Sexual harassment escalation in domestic work exploits the structural isolation of private households, the power imbalance of the Kafala system, and the failure of legal systems to protect domestic workers from gender-based violence. Each step — private placement, verbal harassment, physical escalation, agency dismissal, legal barriers to reporting — uses a recognized element of the domestic work employment relationship. But the chain creates a gender-specific trap where a woman is confined with her abuser, has no effective complaint mechanism, and faces criminal prosecution if she escapes. KAFA Lebanon documented 250+ cases matching this pattern in 2019-2023. Human Rights Watch reports on domestic worker abuse in Saudi Arabia and Lebanon consistently identify this escalation chain.",
        "emergent_risk": "Gender-based violence trap: private household isolation + verbal-to-physical escalation + agency dismissal + absconding counter-charges = sexual abuse with legal impunity and criminalization of the victim's escape",
        "difficulty": "expert",
        "source_references": [
            "Human Rights Watch — Without Protection: How the Lebanese Justice System Fails Migrant Domestic Workers 2020",
            "KAFA (Enough) Violence & Exploitation — Domestic Worker Abuse Case Documentation 2019-2023",
            "Human Rights Watch — 'As If I Am Not Human': Abuses against Asian Domestic Workers in Saudi Arabia 2008",
            "ILO — Ending Violence and Harassment Against Women and Men in the World of Work (Convention C190)",
            "Lebanon Law on Protection of Women and Family Members (Law 293 of 2014)",
            "Saudi Arabia Royal Decree A/96 of 2018 on Anti-Harassment",
        ],
        "corridors": ["ET-LB", "PH-SA", "ID-KW", "PH-AE"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["coercion", "abuse of position of vulnerability", "threat of force", "sexual exploitation"],
            "purpose": ["exploitation", "sexual exploitation", "forced labour"],
        },
    },
    {
        "id": "gender_specific_004",
        "name": "Beauty and Modeling Industry Recruitment Fraud",
        "category": "gender_specific",
        "steps": [
            {
                "id": "gs004_s1",
                "description": "A 'talent scout' or 'modeling agent' contacts young women (ages 18-25) in Nigeria, Ukraine, the Philippines, or Ethiopia through Instagram, TikTok, or Facebook, offering an opportunity to work as a model or brand ambassador in Dubai, Turkey, or Japan. The scout operates through a polished social media presence with photos of apparent models at high-end events and luxury locations. UNODC's 2020 report on social media and trafficking identified this recruitment pattern across 50+ countries.",
                "legal_basis": "Social media talent scouting is a recognized practice in the modeling and entertainment industry; international model management agencies routinely recruit through digital platforms; direct messaging for talent identification is standard industry practice",
                "sector": "entertainment",
                "corridor": "NG-AE",
                "indicator_action_ids": [],
                "red_flag_context": "Social media recruitment bypasses regulated employment channels; fabricated online portfolios create false credibility; targeting young women in countries with limited economic opportunities exploits aspiration and economic vulnerability simultaneously; the scout operates outside any licensing or regulatory framework",
            },
            {
                "id": "gs004_s2",
                "description": "The scout tells the recruited woman that she needs 'professional portfolio development' — a photoshoot, comp cards, and a website presence — before she can be placed with agencies in the destination country. The portfolio development costs $2,000-$5,000, which the woman pays upfront or takes as a loan from the scout's 'agency.' The photoshoot occurs at a local studio and produces legitimate-looking modeling materials. The Polaris Project has documented portfolio investment scams as a primary recruitment mechanism in modeling-related trafficking.",
                "legal_basis": "Portfolio investment is a recognized upfront cost in the modeling industry; agencies routinely require professional photos and promotional materials before placement; aspiring models commonly self-fund initial portfolio development as a career investment",
                "sector": "entertainment",
                "corridor": "UA-TR",
                "indicator_action_ids": [],
                "red_flag_context": "The portfolio investment creates a financial hook: the woman has now spent $2,000-$5,000 on a career that exists only in the scout's promises; the sunk-cost psychology makes her more likely to continue even when red flags appear; the debt — whether paid upfront or loaned — becomes leverage for the next step",
            },
            {
                "id": "gs004_s3",
                "description": "The scout arranges a 'modeling visa' or 'entertainment visa' for the woman to travel to Dubai, Istanbul, or Tokyo. In practice, the visa may be a tourist visa, a visit visa, or in some cases a visa obtained through a legitimate-looking but fraudulent sponsorship company. Travel and accommodation are arranged by the scout's network. Upon arrival at the airport, the woman is met by a local contact who takes her to accommodation — typically a shared apartment with other women who arrived through the same pipeline.",
                "legal_basis": "Visa arrangements through agencies are a common travel service; entertainment and performance visas exist in multiple jurisdictions; arrival assistance including airport pickup and accommodation provision is a standard service for international placements",
                "sector": "entertainment",
                "corridor": "PH-JP",
                "indicator_action_ids": [],
                "red_flag_context": "The visa type and the actual employment do not match; the woman has no independent knowledge of her legal status in the destination country; the scout's network controls arrival logistics, accommodation, and the woman's initial orientation — replicating the document and information control pattern of labor trafficking",
            },
            {
                "id": "gs004_s4",
                "description": "Upon arrival, the woman discovers that no modeling work exists. Instead, she is placed in a 'hospitality' or 'entertainment' role at a hotel, nightclub, or private event company. The work involves serving drinks, accompanying clients to events, or providing 'companionship services.' The scout's local contact explains that this is 'how models earn while waiting for bookings' and that the hospitality work will pay off the portfolio investment debt. The IOM has documented this bait-and-switch from modeling to hospitality/entertainment across the Gulf states, Turkey, and East Asia.",
                "legal_basis": "Hospitality and entertainment employment is legal in the destination countries; the employer holds appropriate business licenses; the woman's work activities are described within the legal boundaries of the entertainment sector; payment arrangements reference the outstanding portfolio investment",
                "sector": "entertainment",
                "corridor": "ET-LB",
                "indicator_action_ids": [],
                "red_flag_context": "Classic bait-and-switch: the promised employment (modeling) does not exist and was never intended to exist; the hospitality/entertainment placement is the actual objective; the portfolio investment debt is now used as financial leverage to compel participation in work the woman did not agree to; 'companionship services' is frequently a euphemism for escalating sexual exploitation",
            },
            {
                "id": "gs004_s5",
                "description": "The woman's debt from the portfolio investment ($2,000-$5,000) is augmented by charges for accommodation, food, transport, and 'agency management fees' in the destination country, growing to $8,000-$15,000. The local contact pressures her to accept increasingly explicit 'entertainment' assignments, including escort services and coerced commercial sexual exploitation, framed as the fastest way to 'pay off the debt and start real modeling work.' Her passport is held by the local contact 'for safekeeping.' Women who resist are threatened with exposure of compromising photos taken during the initial portfolio shoot or the hospitality work.",
                "legal_basis": "Accommodation and management fee deductions are documented as standard agency costs; the woman's continued participation is described as voluntary; the agency holds travel documents as part of visa management services in the destination country",
                "sector": "entertainment",
                "corridor": "NG-AE",
                "indicator_action_ids": [],
                "red_flag_context": "Debt escalation + document confiscation + blackmail through compromising images + pressure toward sexual exploitation completes the trafficking chain; the portfolio photoshoot that seemed legitimate at stage 2 now provides material for coercion; the woman is trapped by debt, document loss, shame, and the threat of exposure in both destination and origin countries",
            },
        ],
        "chain_context": "Beauty and modeling industry recruitment fraud exploits aspirational migration — the desire for a glamorous career — as a trafficking entry point. The chain uses social media's reach, the modeling industry's legitimate upfront investment norms, and the blurred boundaries between entertainment and sexual exploitation in certain destination markets to move women from recruitment through debt bondage to coerced sexual exploitation. Each step — talent scouting, portfolio investment, visa facilitation, hospitality placement, debt escalation — uses a recognized industry practice as cover. UNODC and the Polaris Project have identified this as one of the fastest-growing recruitment patterns, particularly targeting young women in Nigeria, Eastern Europe, and Southeast Asia.",
        "emergent_risk": "Aspiration-driven trafficking: social media recruitment + portfolio debt + fraudulent visa + entertainment bait-and-switch + debt escalation with blackmail = coerced sexual exploitation disguised as a modeling career pathway",
        "difficulty": "hard",
        "source_references": [
            "UNODC — The Role of Social Media in Human Trafficking Recruitment 2020",
            "IOM — Beauty Industry and Entertainment Sector Trafficking Data 2023",
            "Polaris Project — Human Trafficking in the Modeling Industry",
            "Human Rights Watch — Exported and Exposed: Abuses against Migrant Domestic Workers in Dubai",
        ],
        "corridors": ["NG-AE", "UA-TR", "PH-JP", "ET-LB"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["deception", "debt bondage", "coercion", "retention of identity documents"],
            "purpose": ["sexual exploitation", "exploitation", "forced labour"],
        },
    },
    {
        "id": "gender_specific_005",
        "name": "Caregiver-to-Domestic-Servitude Pipeline",
        "category": "gender_specific",
        "steps": [
            {
                "id": "gs005_s1",
                "description": "A Filipina caregiver is recruited through a licensed agency for an 'elderly care' position in Israel (under the B/1 work visa for caregiving), Canada (under the Home Support Worker Stream of the Temporary Foreign Worker Program), or Singapore (under the Work Permit for domestic workers). The job description specifies care for one elderly person with mobility limitations, including meal preparation, medication reminders, and light housekeeping. The salary is set at the destination country's minimum for caregivers — approximately NIS 5,300/month in Israel, CAD $15-17/hour in Canada, or SGD $600-800/month in Singapore.",
                "legal_basis": "Caregiver recruitment through licensed agencies is the mandated channel in all three countries; the B/1 visa in Israel, TFWP in Canada, and Work Permit in Singapore are legal frameworks specifically designed for foreign caregiver employment; job descriptions and salary terms are approved by the relevant ministry",
                "sector": "domestic_work",
                "corridor": "PH-IL",
                "indicator_action_ids": [],
                "red_flag_context": "The job description is deliberately narrow to attract the worker while the actual workload will be far broader; the 'light housekeeping' clause in the contract is elastic enough to expand into full domestic servitude; the one-person care role becomes a justification for 24/7 availability",
            },
            {
                "id": "gs005_s2",
                "description": "Upon arrival, the caregiver discovers that the elderly patient has severe dementia requiring constant supervision and physical assistance with all daily activities (bathing, toileting, feeding, repositioning). The patient is non-verbal and cannot be left unattended. The care needs far exceed the 'mobility limitations' described in the recruitment materials. The Israeli Supreme Court case of Yolanda Glaten v. State of Israel established that caregivers are entitled to rest hours even when caring for patients who require 24/7 supervision, but enforcement of this ruling remains inconsistent.",
                "legal_basis": "Patient acuity levels can change between recruitment and arrival; the employer has a legitimate care need; the caregiver's professional skills qualify her for dementia care; the employment contract covers 'care for an elderly person' without specifying acuity limitations",
                "sector": "domestic_work",
                "corridor": "PH-CA",
                "indicator_action_ids": [],
                "red_flag_context": "The gap between the described role and the actual care needs is a deliberate recruitment deception; severe dementia care requires specialized training and typically a team of carers rotating in shifts, not a single live-in worker; the mismatch is systematic, not incidental — agencies and employers know the patient's condition before recruitment",
            },
            {
                "id": "gs005_s3",
                "description": "The caregiver's duties progressively expand beyond patient care to include all household work for the entire family: cooking meals for 4-6 family members, cleaning the entire house (not just the patient's room), doing laundry for the household, grocery shopping, and childcare for grandchildren during family visits. The employer family explains that 'since you're already here, it's easier if you handle everything' and that the household duties are part of 'supporting the patient's family environment.'",
                "legal_basis": "Live-in caregiver contracts in Israel and Singapore include 'household duties as reasonably required'; the distinction between patient-specific care and general household work is ambiguous in standard contracts; employers characterize household tasks as incidental to the primary caregiving role",
                "sector": "domestic_work",
                "corridor": "ID-SG",
                "indicator_action_ids": [],
                "red_flag_context": "Duty expansion transforms a single-patient caregiver into a full household domestic worker without any change in compensation; the 'since you're already here' logic exploits the live-in arrangement to extract unlimited labor; the caregiver is now performing two full-time jobs (dementia care + household management) for one salary",
            },
            {
                "id": "gs005_s4",
                "description": "The caregiver works from 6:00 AM to 10:00 PM on household and care duties, with nighttime wake-ups 2-3 times per night for the dementia patient (toileting, agitation, wandering). She averages 4-5 hours of interrupted sleep per night. When she requests her contractual day off (one day per week in Israel, one day per month in Singapore), the employer states that the patient 'cannot be left alone' and that no replacement caregiver is available. In Singapore, the Employment of Foreign Manpower Act allows the employer to determine rest day arrangements. The employer offers to 'compensate' the missed day off with a token payment of SGD $20-30 or no compensation at all.",
                "legal_basis": "Caregiver rest day provisions vary by country; Israel's Foreign Workers Law provides for weekly rest but enforcement in live-in care is difficult; Singapore's EFMA requires one rest day per month but allows encashment by mutual agreement; the patient's continuous care needs are a legitimate operational concern",
                "sector": "domestic_work",
                "corridor": "PH-IL",
                "indicator_action_ids": [],
                "red_flag_context": "Systematic rest day denial combined with nighttime wake-ups produces chronic sleep deprivation that is both a health hazard and a control mechanism; exhausted workers are less likely to assert rights, seek information, or plan alternatives; the 'patient cannot be left alone' justification is a structural trap — it is true, but the solution is not to deny the caregiver rest, it is to provide a replacement",
            },
            {
                "id": "gs005_s5",
                "description": "When the caregiver requests a transfer to a different employer through her agency, the agency warns that transfer processing takes 2-3 months, during which she would be without income and potentially without accommodation. In Israel, the caregiver's B/1 visa is tied to the specific employer, and transferring requires the new employer to file a new visa application. In Singapore, the Work Permit is employer-specific, and cancellation by the current employer triggers a short departure window. The agency adds that 'employers don't want workers who complain' and that her 'record' will affect future placements.",
                "legal_basis": "Visa transfer procedures are governed by immigration law in each country; processing times are administrative realities; agencies manage their client relationships and worker reputations as part of their business model; employer-specific visa frameworks are the legal norm for foreign caregivers",
                "sector": "domestic_work",
                "corridor": "IN-UK",
                "indicator_action_ids": [],
                "red_flag_context": "Visa-tied employment + transfer processing delays + income gap during transfer + agency blacklist threat creates a multi-layered deterrent to seeking help; the caregiver is economically trapped (recruitment debt, no savings), legally trapped (employer-tied visa), and professionally trapped (blacklist risk); ILO Convention C189 on Domestic Workers specifically addresses these barriers but remains unratified by Israel and Singapore",
            },
        ],
        "chain_context": "The caregiver-to-domestic-servitude pipeline exploits the feminized nature of care work and the structural isolation of live-in employment. Women are recruited for a specific care role but arrive to find unlimited duty expansion, 24/7 availability demands, rest day denial, and visa-tied employment that prevents mobility. The Israeli Supreme Court's Yolanda Glaten ruling and Singapore's EFMA rest-day provisions acknowledge the problem but enforcement in private households remains minimal. The Canadian Home Support Worker Stream requires a labour market impact assessment but does not effectively monitor post-arrival working conditions. Each country's framework addresses one element while leaving the chain intact.",
        "emergent_risk": "Care work duty trap: narrow recruitment description + expanded duties + 24/7 availability + rest day denial + employer-tied visa = total labor extraction disguised as elderly care employment",
        "difficulty": "hard",
        "source_references": [
            "Israeli Supreme Court — Yolanda Glaten v. State of Israel (caregiver rest hours)",
            "Canada IRCC — Home Support Worker Stream (Temporary Foreign Worker Program)",
            "Singapore Employment of Foreign Manpower Act (EFMA) — Rest Day Provisions",
            "ILO — Convention C189 on Domestic Workers",
            "Human Rights Watch — A Raw Deal: Abuses of Thai Workers in Israel's Agricultural Sector 2015",
            "Transient Workers Count Too (TWC2) — Foreign Domestic Worker Conditions in Singapore",
        ],
        "corridors": ["PH-IL", "PH-CA", "ID-SG", "IN-UK"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["deception", "abuse of position of vulnerability", "coercion"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "gender_specific_006",
        "name": "Male Construction Worker Masculinity-Based Exploitation",
        "category": "gender_specific",
        "steps": [
            {
                "id": "gs006_s1",
                "description": "A Nepali or Bangladeshi man is recruited for construction work in Qatar or Saudi Arabia through an agency that emphasizes physical toughness in its marketing: 'Strong men needed for challenging Gulf construction projects — high pay for hard workers.' The recruitment materials target male breadwinners who support extended families through remittances. The agency charges 80,000-150,000 NPR ($600-$1,100) in recruitment fees, often financed through family land collateral. Pre-departure orientation frames the work as a test of masculine endurance.",
                "legal_basis": "Construction recruitment through licensed manpower agencies is the standard channel under Nepal's Foreign Employment Act 2007 and Bangladesh's Overseas Employment and Migrants Act 2013; recruitment fees within regulated caps are permitted; pre-departure orientation is a mandatory government requirement",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Masculinity-coded recruitment ('strong men,' 'challenging work,' 'hard workers') establishes a cultural framework where enduring suffering is equated with being a good man and provider; this framing is later weaponized to prevent workers from reporting injuries, seeking medical care, or complaining about conditions",
            },
            {
                "id": "gs006_s2",
                "description": "On the construction site in Doha or Riyadh, a workplace culture develops where reporting injuries, requesting medical attention, or expressing fatigue is equated with weakness. Supervisors — often from the same nationality as the workers — reinforce this through comments like 'real men don't complain,' 'your father worked harder than this,' and 'boys in the village would take your place tomorrow.' Workers who visit the site clinic are mocked by peers and supervisors and may be assigned to less desirable tasks. The Guardian's 'The Workers' investigation documented this culture across multiple Qatar World Cup construction sites.",
                "legal_basis": "Workplace culture and supervisor communication are management practices; peer pressure and workplace norms exist in every industry; supervisors' comments reflect cultural attitudes rather than formal company policy; task assignment is a management prerogative",
                "sector": "construction",
                "corridor": "BD-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Masculinity-based workplace culture creates a social enforcement mechanism more powerful than any formal policy: workers self-police and police each other, voluntarily suppressing complaints and medical needs; this is a gender-specific control mechanism — it works because the workers' identity as men, providers, and breadwinners is tied to their ability to endure",
            },
            {
                "id": "gs006_s3",
                "description": "During summer months, workers perform physically demanding tasks — concrete pouring, rebar tying, scaffolding — in temperatures exceeding 45C (113F) with humidity above 60%. Workers experience heat exhaustion symptoms (dizziness, nausea, confusion, dark urine indicating dehydration) but do not report them because seeking medical attention would trigger the masculinity-based stigma. Water breaks are technically available but in practice limited by production targets — workers who stop for water fall behind on daily quotas and risk pay deductions.",
                "legal_basis": "Qatar's Ministerial Decision No. 17 of 2021 prohibits outdoor work when the Wet Bulb Globe Temperature (WBGT) exceeds a threshold; Saudi Arabia's summer work ban covers 12:00-3:00 PM from June to September; employers are required to provide water and shade; these regulations are presented as evidence of worker protection",
                "sector": "construction",
                "corridor": "IN-AE",
                "indicator_action_ids": [],
                "red_flag_context": "Heat stress regulations exist on paper but are undermined by production-target pressure and masculinity norms that discourage rest; ILO heat stress research in Qatar found that 34% of construction workers surveyed continued working through heat illness symptoms because of peer and supervisor pressure; the WBGT threshold is difficult for individual workers to verify independently",
            },
            {
                "id": "gs006_s4",
                "description": "A worker collapses on site from heat stroke or cardiac arrest. The company medical officer classifies the death as 'natural causes' — specifically 'acute cardiac failure' — without an autopsy. The worker's death certificate lists the cause of death as cardiac arrest, which is technically true (all deaths involve cardiac arrest) but obscures the occupational heat exposure that precipitated it. Amnesty International's 2016 report 'The Ugly Side of the Beautiful Game' documented that the majority of Nepali worker deaths in Qatar were certified as cardiovascular deaths without investigation of workplace conditions.",
                "legal_basis": "Death certification follows the medical officer's clinical assessment; cardiac arrest is a recognized medical cause of death; autopsies are not mandatory for deaths classified as natural causes under Qatar or Saudi law; the employer files the required death report with the ministry",
                "sector": "construction",
                "corridor": "PK-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Systematic misclassification of heat-related deaths as 'cardiac failure' or 'natural causes' renders occupational deaths statistically invisible; The Guardian's investigation found over 6,500 South Asian migrant worker deaths in Qatar between 2010-2020, with the vast majority attributed to 'natural causes' despite the workers being young, healthy men who passed pre-departure medical examinations",
            },
            {
                "id": "gs006_s5",
                "description": "The deceased worker's family in Nepal or Bangladesh receives a death benefit that varies dramatically depending on the death classification. For occupational deaths, Qatar's Workers' Compensation Law provides for substantial compensation; for 'natural cause' deaths, the family receives only the statutory end-of-service benefit (typically $1,000-$3,000) and the cost of repatriating the body. The family has no mechanism to challenge the death classification — they are in a different country, do not speak the language, and have no access to the medical records. The agency recruits a replacement worker from the same village using the same masculinity-coded messaging.",
                "legal_basis": "Death benefit calculations follow the statutory framework based on the certified cause of death; end-of-service benefits are calculated per the labor law; body repatriation is the employer's obligation; the family can pursue claims through the country's labor tribunal system if they choose to",
                "sector": "construction",
                "corridor": "NP-QA",
                "indicator_action_ids": [],
                "red_flag_context": "Death misclassification has direct financial consequences: families of workers killed by occupational heat exposure receive a fraction of the compensation they are legally owed; the replacement cycle — recruiting from the same village with the same messaging — demonstrates that worker death is a calculated business cost, not a crisis; the masculinity framing that prevented the worker from seeking medical care now prevents the family from recognizing the death as occupational",
            },
        ],
        "chain_context": "Male construction worker exploitation in the Gulf operates through a gender-specific mechanism: masculinity norms are weaponized to suppress complaint, prevent medical care-seeking, and normalize extreme physical suffering as evidence of manly endurance. The chain demonstrates how recruitment messaging, workplace culture, heat exposure, death misclassification, and family compensation denial interact to produce a disposable labor system where young men are worked to death and their deaths are erased from occupational statistics. The Guardian's decade-long investigation, Amnesty International's reports, and ILO heat stress studies have documented every step of this chain across Qatar, Saudi Arabia, and the UAE.",
        "emergent_risk": "Masculinity-weaponized disposable labor: toughness-coded recruitment + stigma against medical care + heat exposure + death misclassification + minimal family compensation = occupational killing disguised as natural death with immediate worker replacement",
        "difficulty": "hard",
        "source_references": [
            "The Guardian — 'The Workers': Qatar Migrant Worker Deaths Investigation 2010-2021",
            "Amnesty International — 'The Ugly Side of the Beautiful Game': Exploitation of Migrant Workers on a Qatar 2022 World Cup Site 2016",
            "ILO — Heat Stress and Occupational Health in Qatar Construction Sector 2023",
            "Qatar National Human Rights Committee (NHRC) — Worker Death Classification Reports",
            "Nepal Ministry of Labour — Foreign Employment Death Statistics 2022",
        ],
        "corridors": ["NP-QA", "BD-SA", "IN-AE", "PK-QA"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["deception", "abuse of position of vulnerability", "coercion"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "gender_specific_007",
        "name": "LGBTQ+ Worker Targeting with False Safe-Space Promises",
        "category": "gender_specific",
        "steps": [
            {
                "id": "gs007_s1",
                "description": "An LGBTQ+ person in Uganda, Nigeria, Bangladesh, or Myanmar seeks to emigrate from a country where homosexuality is criminalized — Uganda's Anti-Homosexuality Act 2023 prescribes life imprisonment and death in some cases; Nigeria's Same-Sex Marriage (Prohibition) Act 2013 carries 14 years imprisonment; Bangladesh's Penal Code Section 377 carries life imprisonment. The person contacts a recruiter or migration facilitator who advertises through LGBTQ+ social media networks, encrypted messaging groups, or word-of-mouth, offering placement with a 'tolerant, progressive employer' in the UAE, Saudi Arabia, Malaysia, or Thailand.",
                "legal_basis": "International labor migration from these countries is a legal and common process; labor recruiters operate within national licensing frameworks; social media and messaging-based recruitment is increasingly common; the recruiter's marketing emphasizes employer quality and workplace culture",
                "sector": "services",
                "corridor": "UG-AE",
                "indicator_action_ids": [],
                "red_flag_context": "The recruiter specifically targets LGBTQ+ individuals because their criminalized identity in the origin country creates desperation to leave and willingness to trust anyone who appears sympathetic; the promise of a 'tolerant employer' in countries that also criminalize homosexuality (UAE Penal Code Article 354: up to 14 years; Saudi Arabia: death penalty; Malaysia: Section 377A up to 20 years) is an inherent deception — the destination is no safer than the origin",
            },
            {
                "id": "gs007_s2",
                "description": "The LGBTQ+ worker arrives in the destination country on a standard work visa (UAE employment visa, Saudi Arabia work permit, Malaysian Employment Pass) and begins employment in the hospitality, retail, or domestic work sector. During the initial period, the employer appears welcoming. The worker, relieved to have escaped criminal prosecution at home, is cautiously optimistic. The employer gradually learns or already knows the worker's LGBTQ+ identity through the recruiter's information, through social media observation, or through the worker's own disclosure in what they believe is a safe environment.",
                "legal_basis": "Employment visa issuance and arrival follow standard immigration procedures; the employment relationship is governed by the destination country's labor law; employer-employee interactions including personal disclosure are part of the workplace relationship",
                "sector": "services",
                "corridor": "NG-SA",
                "indicator_action_ids": [],
                "red_flag_context": "The employer's knowledge of the worker's LGBTQ+ identity becomes the central control mechanism; whether the employer knew from the outset (recruiter-informed) or discovered later, the information gives the employer absolute power over the worker in a jurisdiction where the worker's identity is criminalized",
            },
            {
                "id": "gs007_s3",
                "description": "The employer begins using the worker's LGBTQ+ identity as leverage. When the worker raises concerns about working conditions — long hours, delayed wages, or unsafe tasks — the employer responds with statements like 'You should be grateful I don't report you' or 'Do you know what happens to people like you in this country?' In the UAE, consensual same-sex activity is punishable under Federal Penal Code Article 354 (up to 14 years imprisonment) and under individual emirate-level Sharia law provisions. In Saudi Arabia, same-sex activity carries penalties including imprisonment, flogging, and potentially death under the kingdom's interpretation of Sharia.",
                "legal_basis": "Employers are within their rights to manage employee conduct and performance; references to legal consequences for employee behavior are presented as informational rather than threatening; the criminalization of same-sex activity is the law of the land in the destination country",
                "sector": "services",
                "corridor": "BD-MY",
                "indicator_action_ids": [],
                "red_flag_context": "Identity-based blackmail is a uniquely powerful coercion mechanism: the employer does not need to threaten violence or even formal termination — the threat of criminal prosecution, imprisonment, or death for the worker's identity is sufficient to ensure complete compliance; the worker cannot seek police protection because the police are the threat; this inverts the normal relationship between law enforcement and victim protection",
            },
            {
                "id": "gs007_s4",
                "description": "The worker cannot report labor exploitation to authorities without risking criminal prosecution for their LGBTQ+ identity. Filing a labor complaint at the Ministry of Labour, contacting the police about unpaid wages, or seeking help at their embassy could result in the worker's sexual orientation being disclosed — either by the employer as a counter-charge, by the worker's own behavior or social connections being scrutinized, or by the worker being forced to explain why they cannot return to their home country. ILGA World's 2023 State-Sponsored Homophobia report documents 64 UN member states where homosexuality is criminalized, creating a global map of jurisdictions where this exploitation mechanism operates.",
                "legal_basis": "Labor complaint mechanisms are available to all workers regardless of personal characteristics; the worker's right to file a complaint is formally protected; however, criminal law enforcement operates independently of labor dispute mechanisms and can be triggered by information disclosed during proceedings",
                "sector": "services",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Double criminalization trap: the worker is a victim of labor exploitation but also a potential target of criminal prosecution; seeking help for one victimization exposes the worker to the other; this creates a perfect silence mechanism — the exploited worker is also the most thoroughly silenced worker; even in Thailand, where homosexuality is not criminalized, migrant workers in irregular status face deportation if they attract official attention",
            },
            {
                "id": "gs007_s5",
                "description": "The exploitation deepens: the employer reduces wages, extends hours, assigns degrading tasks, and in some cases facilitates physical or sexual abuse by third parties, knowing the worker cannot report. The worker's passport is withheld by the employer. If the worker attempts to leave, the employer threatens to contact police and 'out' the worker, or to contact the worker's family in the origin country to disclose their identity — in Uganda, Nigeria, and Bangladesh, this disclosure would put the worker's family at risk of social ostracism, violence, and in Uganda's case, potential prosecution for 'failure to report' homosexuality under the 2023 Act's provisions.",
                "legal_basis": "Employment relationship management including task assignment and work scheduling is an employer prerogative; passport retention is described as standard visa management; the employer's knowledge of the worker's personal background is presented as incidental to the employment relationship",
                "sector": "services",
                "corridor": "UG-AE",
                "indicator_action_ids": [],
                "red_flag_context": "Total control through identity weaponization: the worker faces criminal prosecution in the destination country if reported, social destruction and family endangerment in the origin country if outed, and immigration detention and deportation if discovered; every possible exit route leads to catastrophic consequences; this is the most comprehensive coercion trap documented in trafficking research — it requires no physical confinement because the legal and social environment provides inescapable coercion",
            },
        ],
        "chain_context": "LGBTQ+ worker exploitation through identity weaponization operates at the intersection of criminalized identity, labor migration, and the global patchwork of anti-LGBTQ+ laws. The chain requires no physical chains, locked doors, or debt bondage — the criminalization of the worker's identity in both origin and destination countries creates a coercion mechanism that is total, invisible, and virtually undetectable by standard labor inspection. Human Rights Watch has documented cases of LGBTQ+ migrant workers in the Gulf states trapped in this pattern, and the ILO has identified the intersection of discrimination and forced labor as a key research gap. ILGA World's mapping of 64 criminalizing states means this exploitation pattern has global reach wherever these workers migrate.",
        "emergent_risk": "Identity-weaponized coercion: criminalized identity in origin + criminalized identity in destination + employer knowledge + double prosecution risk + family endangerment = total control without physical confinement through legal and social coercion alone",
        "difficulty": "expert",
        "source_references": [
            "ILGA World — State-Sponsored Homophobia: Global Legislation Overview 2023",
            "Human Rights Watch — 'They Hunt Us Down for Fun': Discrimination and Violence against LGBTQ+ People in Uganda 2023",
            "ILO — Discrimination and Forced Labour: Intersectional Vulnerabilities 2022",
            "UAE Federal Penal Code Article 354 — Same-Sex Activity Provisions",
            "Uganda Anti-Homosexuality Act 2023",
            "Nigeria Same-Sex Marriage (Prohibition) Act 2013",
        ],
        "corridors": ["UG-AE", "NG-SA", "BD-MY", "MM-TH"],
        "palermo_elements": {
            "act": ["recruitment", "transfer", "harbouring"],
            "means": ["coercion", "abuse of position of vulnerability", "intimidation", "blackmail"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
    {
        "id": "gender_specific_008",
        "name": "Reproductive Coercion in Agricultural Work",
        "category": "gender_specific",
        "steps": [
            {
                "id": "gs008_s1",
                "description": "Female agricultural workers from Guatemala, Mexico, Ethiopia, or Myanmar are hired for seasonal or contract work in US farms, Saudi Arabian agricultural operations, or Thai agribusiness. Upon starting work or during periodic employer-conducted 'health checks,' workers are required to take pregnancy tests administered by supervisors or employer-designated staff rather than independent medical professionals. In the US, Farmworker Justice documented mandatory pregnancy testing on farms in Florida, North Carolina, and California, despite this practice violating Title VII of the Civil Rights Act. In Saudi Arabia, agricultural workers (like domestic workers) are excluded from general labor law protections.",
                "legal_basis": "Employer health screening is presented as an occupational safety measure; pre-employment medical testing is common in agricultural work; employers argue that pregnancy creates safety risks around pesticides and heavy machinery; the testing is characterized as protective of the worker rather than discriminatory",
                "sector": "agriculture",
                "corridor": "GT-US",
                "indicator_action_ids": [],
                "red_flag_context": "Mandatory employer-administered pregnancy testing is pregnancy discrimination regardless of its stated rationale; supervisor-administered tests (rather than independent medical professionals) violate bodily autonomy and medical privacy; the practice establishes employer surveillance of female workers' reproductive status as a condition of employment",
            },
            {
                "id": "gs008_s2",
                "description": "Workers who test positive for pregnancy face immediate contract termination and, for foreign workers, repatriation. In US agricultural operations using H-2A temporary worker visas, pregnant workers are sent home as 'medically unfit' — the H-2A visa is employer-tied, so losing the job means losing legal status. In Thailand, Myanmar agricultural workers on border passes face deportation upon contract termination. Centro de los Derechos del Migrante documented cases where pregnant H-2A workers were terminated and deported within 48 hours, losing unpaid wages and end-of-contract bonuses.",
                "legal_basis": "Employment termination for medical unfitness is a recognized employer action; H-2A visa conditions require active employment with the sponsoring employer; agricultural work is classified as physically demanding, and employers claim pregnancy creates legitimate safety concerns for the worker",
                "sector": "agriculture",
                "corridor": "MX-US",
                "indicator_action_ids": [],
                "red_flag_context": "Pregnancy-based termination converts a protected characteristic into a firing offense; the employer-tied visa transforms pregnancy into simultaneous job loss, housing loss, legal status loss, and forced departure; the speed of termination and deportation (48 hours) prevents the worker from accessing legal aid, filing a complaint, or collecting unpaid wages",
            },
            {
                "id": "gs008_s3",
                "description": "To avoid pregnancy-related termination, employers provide or require female workers to use long-acting contraception — typically Depo-Provera (injectable, 3-month) or Nexplanon (implant, 3-year) — administered by employer-arranged medical staff or distributed by supervisors. Workers report being told that contraception is 'mandatory for female workers' or that 'it's for your own safety around the chemicals.' The ACLU documented reproductive coercion in US agriculture including cases where workers were told they would be fired if they did not accept contraceptive injections.",
                "legal_basis": "Employer health and safety programs may include referrals to medical services; contraception provision is framed as a benefit that protects female workers from pregnancy-related employment risks; medical services offered through employer health programs are presented as voluntary",
                "sector": "agriculture",
                "corridor": "ET-SA",
                "indicator_action_ids": [],
                "red_flag_context": "Employer-mandated contraception is a direct violation of reproductive autonomy and constitutes reproductive coercion under international human rights law; the 'voluntary' framing is negated by the employer's power to terminate and deport; long-acting methods (implants, injectables) are chosen specifically because they cannot be easily discontinued by the worker without medical intervention",
            },
            {
                "id": "gs008_s4",
                "description": "Workers who refuse employer-provided contraception are systematically assigned to the hardest, lowest-paying, or most pesticide-exposed tasks — picking in recently sprayed fields, mixing chemical solutions, or performing manual labor in extreme heat. These punitive assignments function as retaliation but are documented as normal task rotation. Workers who accept contraception receive preferable assignments and may be eligible for overtime. This creates a two-tier workforce where reproductive compliance determines working conditions and earnings.",
                "legal_basis": "Agricultural task assignment is a management prerogative based on operational needs and worker capability; task rotation is a standard practice in seasonal agriculture; the employer does not formally link contraception status to task assignment in any written policy",
                "sector": "agriculture",
                "corridor": "MM-TH",
                "indicator_action_ids": [],
                "red_flag_context": "Punitive task assignment for reproductive non-compliance is retaliation disguised as neutral management; exposure to pesticides as punishment specifically targets the reproductive health the worker sought to protect; the two-tier system creates peer pressure — workers who accept contraception receive better conditions, incentivizing compliance and stigmatizing resistance",
            },
            {
                "id": "gs008_s5",
                "description": "Female agricultural workers exposed to organophosphate pesticides, paraquat, and other agrochemicals experience reproductive health impacts including miscarriages, stillbirths, and birth defects in children conceived during or after pesticide exposure. Workers who miscarry on the job receive no medical care, no workers' compensation (foreign agricultural workers are excluded from many state workers' comp programs in the US), and no report is filed with occupational health authorities. Pregnant workers are hidden from labor inspectors and farm auditors during scheduled visits — supervisors instruct them to stay in housing or work in areas away from inspection routes. Farmworker Justice and the University of California-Davis documented elevated miscarriage rates of 30-40% among female farmworkers exposed to organophosphates.",
                "legal_basis": "Pesticide application follows the product label requirements and EPA or destination country regulations; workers are provided personal protective equipment as required; miscarriages are classified as personal medical events rather than occupational injuries; labor inspection schedules are coordinated with farm management for logistics",
                "sector": "agriculture",
                "corridor": "GT-US",
                "indicator_action_ids": [],
                "red_flag_context": "Miscarriages from pesticide exposure are occupational injuries that are systematically unrecognized and unreported; hiding pregnant workers from inspectors demonstrates awareness that their presence violates either labor law or the employer's own pregnancy-free workplace policy; the combination of mandatory pregnancy testing, employer-controlled contraception, pesticide exposure, and unreported miscarriages constitutes a comprehensive reproductive coercion system that treats female workers' bodies as employer-managed assets",
            },
        ],
        "chain_context": "Reproductive coercion in agricultural work operates through a gender-specific exploitation chain that has no parallel in male-dominated sectors. Mandatory pregnancy testing, contractual pregnancy bans, employer-controlled contraception, punitive task assignment for non-compliance, and unreported pesticide-related miscarriages create a system where female agricultural workers must surrender reproductive autonomy as a condition of employment and economic survival. The chain is documented across US agriculture (H-2A workers), Gulf state farming operations, and Thai agribusiness, with consistent patterns regardless of geographic context. Farmworker Justice, the ACLU, and Centro de los Derechos del Migrante have documented each element independently; the chain analysis reveals how these individual practices constitute a systematic reproductive coercion regime.",
        "emergent_risk": "Agricultural reproductive coercion system: mandatory pregnancy testing + employer-controlled contraception + punitive task assignment + pesticide exposure + unreported miscarriages + inspector evasion = comprehensive control of female workers' reproductive capacity as an employment management tool",
        "difficulty": "expert",
        "source_references": [
            "Farmworker Justice — Reproductive Health and Pesticide Exposure in US Agriculture 2022",
            "ACLU — Reproductive Rights Violations in Agricultural Work",
            "Centro de los Derechos del Migrante — H-2A Worker Rights and Pregnancy Discrimination",
            "University of California-Davis — Pesticide Exposure and Reproductive Outcomes in Farmworkers",
            "ILO — Safety and Health in Agriculture Convention C184",
            "CEDAW Committee — General Recommendation No. 34 on Rural Women's Rights",
        ],
        "corridors": ["GT-US", "MX-US", "ET-SA", "MM-TH"],
        "palermo_elements": {
            "act": ["recruitment", "harbouring"],
            "means": ["coercion", "abuse of position of vulnerability", "deception"],
            "purpose": ["forced labour", "exploitation"],
        },
    },
]
