"""African migrant worker exploitation -- Ethiopia, Kenya, Nigeria, Ghana, South Africa, and regional patterns."""

AFRICA_FACTS: list[dict] = [
    # ══════════════════════════════════════════════════════════════════════
    # ETHIOPIA (ET) -- at least 20 facts
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "ET",
        "title": "Ethiopia Overseas Employment Proclamation 923/2016",
        "summary": "Replaced the 2009 proclamation. Regulates private employment agencies sending Ethiopian workers abroad. Establishes licensing requirements, prohibits fee-charging to workers, mandates pre-departure training, and requires standard employment contracts vetted by MoLSA. Maximum 3-year contracts. Agencies must post a bond of ETB 500,000.",
        "source": "Federal Negarit Gazette / ILO NATLEX",
    },
    {
        "type": "law",
        "jurisdiction": "ET",
        "title": "Ethiopia Proclamation 1178/2020 -- Prevention and Suppression of Trafficking in Persons and Smuggling of Persons",
        "summary": "Updated Ethiopia's anti-trafficking legal framework. Defines trafficking and smuggling offenses separately. Penalties of 15-25 years imprisonment for trafficking. Establishes a National Partnership Coalition against Trafficking. Criminalizes confiscation of travel documents and forced labour. Provides for victim protection and restitution.",
        "source": "Federal Negarit Gazette / US TIP Report 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "corridor": "ET-SA",
        "title": "Ethiopian Domestic Workers in Saudi Arabia -- Largest Corridor",
        "exploitation_type": "multiple",
        "sector": "domestic_work",
        "summary": "ET-SA is the largest Ethiopian labour migration corridor, with an estimated 500,000+ Ethiopian domestic workers in Saudi Arabia. Exploitation patterns include: passport confiscation upon arrival, contract substitution (promised SAR 1,500 but paid SAR 800), 18-20 hour workdays, physical and sexual abuse, confinement to employer household, denial of food. Kafala system ties workers to employers with no legal mobility.",
        "source": "Human Rights Watch / ILO / IOM Ethiopia",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "corridor": "ET-LB",
        "title": "Ethiopian Domestic Workers in Lebanon -- Kafala Exploitation",
        "exploitation_type": "multiple",
        "sector": "domestic_work",
        "summary": "Tens of thousands of Ethiopian women worked in Lebanon under kafala. Pattern: recruitment by brokers in Addis Ababa promising USD 200-400/month, arrival to find different employer and USD 150/month. Passport confiscated. Locked in homes. Physical abuse documented in 40% of cases surveyed by HRW. After Lebanon economic crisis (2019), employers abandoned workers at Ethiopian embassy. Workers thrown off balconies -- multiple deaths documented.",
        "source": "Human Rights Watch / Anti-Slavery International / This is Lebanon",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "corridor": "ET-AE",
        "title": "Ethiopian Workers in UAE -- Contract Substitution and Wage Theft",
        "exploitation_type": "deception",
        "sector": "domestic_work",
        "summary": "Ethiopian workers recruited through irregular channels arrive in UAE to find contracts different from those signed in Addis Ababa. Wages 30-50% lower than promised. Workers report confinement, unpaid wages for 3-6 months, and being 'loaned out' to work in multiple households. Ethiopian embassy in Abu Dhabi reports 200+ distress calls monthly. Workers who flee face arrest for absconding.",
        "source": "IOM / Ethiopian Embassy UAE / Migrant-Rights.org",
    },
    {
        "type": "advisory",
        "jurisdiction": "ET",
        "title": "Ethiopia Migration Ban 2013-2018 -- Impacts and Outcomes",
        "summary": "Ethiopia banned overseas labour deployment in October 2013 following widespread abuse and deaths of domestic workers in Middle East. Ban lasted until January 2018 when Proclamation 923/2016 framework was implemented. Unintended consequence: irregular migration surged via Djibouti-Yemen-Saudi smuggling route, exposing migrants to far worse exploitation. IOM estimated 100,000+ Ethiopians transited Yemen annually during ban period, with torture, ransom, and deaths en route.",
        "source": "IOM / MoLSA Ethiopia / Mixed Migration Centre",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "title": "Saudi Arabia Mass Deportation of Ethiopians (2013)",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "In November 2013, Saudi Arabia's Nitaqat labour law enforcement led to mass deportation of 163,000+ Ethiopian migrants over 3 months. Workers rounded up from homes and workplaces, detained in overcrowded facilities in Riyadh and Jeddah. Reports of beatings, theft of belongings, and deaths in detention. Ethiopia conducted emergency repatriation flights. Many deportees had lived in Saudi Arabia for 10-20 years.",
        "source": "HRW / IOM / BBC / Al Jazeera",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "title": "Saudi Arabia Mass Deportation of Ethiopians (2022-2023)",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Saudi authorities deported an estimated 100,000+ Ethiopians between 2022-2023, many via Riyadh detention centres. AP and HRW investigations documented severe overcrowding (hundreds per cell), beatings by guards, deaths in detention, and sexual abuse of women detainees. Deportees included those with valid work permits. Many had crossed from Yemen via Houthi-controlled territory. Ethiopian government struggled to process returnees.",
        "source": "AP Investigation / Human Rights Watch / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "title": "Ethiopian Returnee Reintegration Challenges",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Returnees from Gulf states face severe reintegration barriers: psychological trauma (PTSD in 60% of surveyed returnees), physical injuries, unpaid wages with no recovery mechanism, social stigma (especially for women who experienced sexual abuse), lack of economic opportunities in origin communities. IOM-Ethiopia runs reintegration programs but funding covers only 15-20% of returnees. Many re-migrate through irregular channels within 1-2 years.",
        "source": "IOM Ethiopia / Addis Ababa University Migration Studies / EUTF",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "title": "Internal Trafficking in Ethiopia -- Domestic Work and Agriculture",
        "exploitation_type": "debt_bondage",
        "sector": "domestic_work",
        "summary": "Internal trafficking is widespread within Ethiopia. Rural children (predominantly girls aged 10-15) trafficked to Addis Ababa, Dire Dawa, and Hawassa for domestic work. Brokers recruit from Amhara, SNNPR, and Oromia regions. Children work 14-16 hours daily, receive no pay (wages sent to parents or kept by broker), suffer physical abuse. Boys trafficked for agriculture, herding, weaving in Tigray and Afar. US TIP Report consistently identifies internal trafficking as a primary concern.",
        "source": "US State Dept TIP Report / IOM / UNICEF Ethiopia",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "title": "Child Labour in Ethiopian Agriculture -- Coffee and Chat",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Ethiopia has one of Africa's highest child labour rates: 40% of children aged 5-14 engaged in work (2019 survey). Coffee sector (Ethiopia's top export) relies heavily on child labour during harvest. Chat (khat) cultivation in Harari and eastern regions employs children for picking and bundling. Children work 8-12 hours daily during peak seasons, missing school. ILO-IPEC programs have reduced rates but enforcement remains weak in rural areas.",
        "source": "ILO-IPEC / US DOL ILAB / Ethiopia CSA Labour Force Survey",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "corridor": "ET-SA",
        "title": "Djibouti-Yemen-Saudi Smuggling Route -- Transit Exploitation",
        "exploitation_type": "physical_sexual_violence",
        "sector": "multiple",
        "summary": "Primary irregular migration route for Ethiopians to Saudi Arabia: Dire Dawa/Harar overland to Obock (Djibouti), boat crossing to Yemen, overland through Houthi-controlled territory to Saudi border. IOM estimates 100,000-150,000 people annually. Exploitation en route: ransom demands (USD 500-2,000, families tortured via phone), sexual violence, forced labour in Yemen, abandonment in desert, drowning at sea. Yemen conflict has not reduced flows.",
        "source": "IOM / Mixed Migration Centre / RMMS",
    },
    {
        "type": "statistic",
        "jurisdiction": "ET",
        "title": "Ethiopian Migrant Worker Deaths Abroad",
        "metric": "Documented migrant worker deaths (Gulf states)",
        "value": "Over 10,000 (2008-2023, incomplete)",
        "year": 2023,
        "summary": "Ethiopian embassy records and media reports document over 10,000 deaths of Ethiopian migrant workers in Gulf states between 2008-2023, though actual figures are believed to be significantly higher. Leading causes: suicide, workplace accidents, unexplained 'cardiac arrest,' and murder by employers. Saudi Arabia accounts for the majority. Death certificates often lack detail, obstructing investigation.",
        "source": "IOM / Ethiopian MoFA / Migrant-Rights.org",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "ET",
        "title": "Ethiopia Bilateral Labour Agreement with Saudi Arabia (2017)",
        "summary": "Ethiopia and Saudi Arabia signed a bilateral labour agreement in 2017 as a precondition for lifting the migration ban. Agreement covers: standard employment contracts, minimum wage for domestic workers (SAR 1,000/month), dispute resolution mechanism, consular access requirements, and employer obligations. Enforcement remains weak: Ethiopian embassy reports most employers ignore contract terms. Saudi Arabia does not permit domestic workers to file labour court complaints.",
        "source": "MoLSA Ethiopia / Saudi MoHRSD / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "corridor": "ET-KW",
        "title": "Ethiopian Domestic Workers in Kuwait -- Abuse Pattern",
        "exploitation_type": "physical_sexual_violence",
        "sector": "domestic_work",
        "summary": "Ethiopian domestic workers in Kuwait report systematic patterns: passport confiscation (reported by 85% in survey), physical abuse (50%), sexual abuse (23%), non-payment of wages for 3+ months (60%), food deprivation, and confinement. Kuwait's Domestic Workers Law 68/2015 provides limited protection but enforcement is minimal. Ethiopian government temporarily suspended deployment to Kuwait in 2014.",
        "source": "ILO / Amnesty International / KFHR (Kuwait)",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "title": "Recruitment Fraud in Ethiopia -- Unlicensed Brokers (Delala)",
        "exploitation_type": "deception",
        "sector": "multiple",
        "summary": "Despite Proclamation 923/2016 requiring licensed agencies, an estimated 60% of Ethiopian migration is facilitated by unlicensed brokers (delala). Brokers operate through personal networks in rural communities, charging ETB 50,000-200,000 (USD 900-3,600). False promises include high wages, good working conditions, and specific employers. Brokers often have connections to transnational smuggling networks. MoLSA has only 30+ licensed agencies but estimates 500+ unlicensed operators.",
        "source": "MoLSA Ethiopia / IOM / RMMS Horn of Africa",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "title": "Ethiopian Women Stranded in Lebanon During Economic Crisis (2019-2020)",
        "exploitation_type": "withholding_wages",
        "sector": "domestic_work",
        "summary": "Lebanon's economic collapse (2019) and Beirut explosion (2020) left thousands of Ethiopian domestic workers destitute. Employers stopped paying wages, abandoned workers at Ethiopian consulate. An estimated 4,000-5,000 Ethiopian workers stranded without documents or resources. Ethiopian government arranged charter flights but thousands waited months in dire conditions. Some employers demanded workers repay 'recruitment costs' before releasing passports.",
        "source": "Reuters / BBC / Ethiopian Embassy Beirut / This is Lebanon",
    },
    {
        "type": "statistic",
        "jurisdiction": "ET",
        "title": "Ethiopian Overseas Migrant Worker Population",
        "metric": "Ethiopians working abroad",
        "value": "1.5-2 million (estimated)",
        "year": 2023,
        "summary": "MoLSA and IOM estimate 1.5-2 million Ethiopian migrant workers abroad, though exact figures are uncertain due to high irregular migration rates. Saudi Arabia hosts the largest population (estimated 750,000+), followed by Lebanon (before economic crisis: 250,000), Kuwait, UAE, Qatar, and Djibouti. Women in domestic work constitute approximately 70% of total migration. Remittances: USD 1.2B officially recorded (2022), actual flows estimated at 2-3x higher through informal channels.",
        "source": "MoLSA / IOM / World Bank Migration Data",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "title": "Tigray Conflict and Displacement Trafficking (2020-2022)",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "The Tigray conflict (2020-2022) displaced 2.5 million people, creating acute trafficking vulnerabilities. Reports of forced labour and sexual violence in conflict zones. IDPs in camps in Amhara and Afar regions targeted by traffickers for domestic work and sexual exploitation. Conflict disrupted anti-trafficking institutions and migration governance in northern Ethiopia. Children separated from families particularly vulnerable to exploitation.",
        "source": "UNHCR / IOM / EHRC / US TIP Report 2022",
    },
    {
        "type": "advisory",
        "jurisdiction": "ET",
        "title": "Ethiopia TIP Report Tier Rating",
        "summary": "US TIP Report has consistently rated Ethiopia as Tier 2 (2019-2024). Key findings: government demonstrates significant efforts but does not fully meet minimum standards. Concerns include: insufficient prosecution of traffickers (fewer than 50 convictions annually despite scale), inadequate victim identification especially for internal trafficking, limited funding for victim services, and failure to regulate unlicensed brokers effectively.",
        "source": "US State Dept TIP Report 2024",
    },
    # ══════════════════════════════════════════════════════════════════════
    # KENYA (KE) -- at least 15 facts
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "KE",
        "title": "Kenya Counter-Trafficking in Persons Act (2010)",
        "summary": "Kenya's primary anti-trafficking legislation. Criminalizes trafficking in persons with penalties of 30 years to life imprisonment. Establishes a National Assistance Trust Fund for victims. Creates the Counter-Trafficking in Persons Advisory Committee. Covers both transnational and internal trafficking. Amended in 2012 to strengthen child trafficking provisions.",
        "source": "Kenya Law / US TIP Report",
    },
    {
        "type": "law",
        "jurisdiction": "KE",
        "title": "Kenya Employment Act (2007) -- Migrant Worker Protections",
        "summary": "Kenya's Employment Act provides basic labour protections applicable to migrant workers: minimum wage, maximum working hours (52 hours/week), annual leave (21 days), written contracts requirement, protection from discrimination. However, domestic workers excluded from many provisions until 2022 amendments. Act does not specifically regulate overseas employment or recruitment agencies for outbound migration.",
        "source": "Kenya Law / ILO NATLEX",
    },
    {
        "type": "law",
        "jurisdiction": "KE",
        "title": "Kenya National Employment Authority Act (2016)",
        "summary": "Established the National Employment Authority (NEA) to regulate labour migration including overseas employment. NEA mandated to: register and license recruitment agencies, maintain a register of Kenyans employed abroad, develop bilateral labour agreements, regulate recruitment fees, and provide pre-departure training. Implementation has been slow: by 2023, fewer than 50 agencies were licensed while hundreds operate informally.",
        "source": "Kenya Law / ILO / IOM Kenya",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "corridor": "KE-SA",
        "title": "Kenyan Domestic Workers in Saudi Arabia -- Exploitation Pattern",
        "exploitation_type": "multiple",
        "sector": "domestic_work",
        "summary": "An estimated 100,000+ Kenyan domestic workers in Saudi Arabia. Exploitation patterns mirror those of Ethiopian workers: passport confiscation, contract substitution (promised KES 50,000/month, receive KES 20,000), physical and sexual abuse, confinement, and non-payment of wages. Kenyan government issued multiple travel advisories but did not impose a formal deployment ban. NEA lacks resources for effective pre-departure screening.",
        "source": "FIDA Kenya / IOM / Kenya National Commission on Human Rights",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "corridor": "KE-QA",
        "title": "Kenyan Construction Workers in Qatar -- World Cup Projects",
        "exploitation_type": "debt_bondage",
        "sector": "construction",
        "summary": "Thousands of Kenyan workers recruited for Qatar construction projects (2015-2022). Workers paid KES 100,000-300,000 (USD 700-2,100) to recruitment agents. Arrived to find: lower wages than contracted, 12-hour shifts in extreme heat, cramped dormitories (8-10 per room). Workers who complained were threatened with deportation. Kenyan embassy in Doha received 500+ distress calls in 2021 alone. Some workers reported 4-6 months of unpaid wages.",
        "source": "Amnesty International / ILO / Kenya Embassy Doha",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "corridor": "KE-AE",
        "title": "Kenyan Workers in UAE -- Hospitality and Security Sectors",
        "exploitation_type": "withholding_wages",
        "sector": "hospitality",
        "summary": "Kenyan workers in UAE employed in hospitality, security, and cleaning sectors. Common complaints: wages 30-40% lower than contracted amount after 'deductions' for accommodation and food, passport retention (though illegal under UAE law), inability to change employers, and threats of deportation for complaints. Security sector workers report 12-14 hour shifts with no overtime pay. Kenyan embassy reports increasing distress cases, averaging 300+ per year.",
        "source": "IOM / Kenya Embassy Abu Dhabi / Migrant-Rights.org",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "title": "Kenya Gulf Return Migration -- Trauma and Destitution",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "domestic_work",
        "summary": "Kenyan workers returning from Gulf states face severe challenges: unpaid wages with no recovery mechanism, psychological trauma (PTSD, depression), physical injuries, social stigma. Women returning from domestic work face particular stigma. IOM Kenya's assisted voluntary return program supported 2,500+ returnees (2019-2023) but demand far exceeds capacity. Returnees report feeling 'trapped' between debt incurred for migration and inability to earn domestically.",
        "source": "IOM Kenya / UNHCR / Kenya Red Cross",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "title": "Kenyan Children Trafficked for Domestic Work -- Internal Pattern",
        "exploitation_type": "debt_bondage",
        "sector": "domestic_work",
        "summary": "Internal trafficking of children from rural Kenya (Turkana, West Pokot, Baringo, Kwale) to Nairobi, Mombasa, and Kisumu for domestic work. Children aged 10-16 recruited by brokers promising education. Instead placed in households working 14-16 hours daily with no pay. Wages sent to parents or retained by broker. Counter-Trafficking in Persons Advisory Committee identifies 3,000+ child victims annually but actual figures likely much higher.",
        "source": "US TIP Report / UNICEF Kenya / Terre des Hommes",
    },
    {
        "type": "statistic",
        "jurisdiction": "KE",
        "title": "Kenyan Overseas Migrant Workers",
        "metric": "Kenyans working abroad",
        "value": "3-4 million (estimated)",
        "year": 2023,
        "summary": "Kenya's diaspora is estimated at 3-4 million, with a significant proportion in Gulf states as labour migrants. Saudi Arabia, UAE, and Qatar are primary destinations for low-skilled workers. Remittances: USD 4.1B (2023), Kenya's largest foreign exchange earner ahead of tea and tourism. NEA reports 120,000+ Kenyans deployed through formal channels annually, but irregular migration is estimated at 2-3x formal deployments.",
        "source": "Central Bank of Kenya / NEA / IOM / World Bank",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "title": "Kenya Recruitment Agency Fraud -- Fake Job Offers",
        "exploitation_type": "deception",
        "sector": "multiple",
        "summary": "Fraudulent recruitment agencies in Nairobi, Mombasa, and Eldoret collect KES 50,000-200,000 from job seekers for Gulf positions that do not exist. Workers surrender passports and receive fake employment contracts. Some are trafficked to different employers or countries than promised. NEA closed 23 unlicensed agencies (2022) but enforcement is inconsistent. Social media platforms (Facebook, TikTok) increasingly used for fraudulent recruitment.",
        "source": "NEA Kenya / DCI (Directorate of Criminal Investigations) / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "corridor": "KE-SA",
        "title": "Deaths of Kenyan Workers in Saudi Arabia -- Consular Data",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "domestic_work",
        "summary": "Kenyan embassy in Riyadh documented 89 deaths of Kenyan workers in Saudi Arabia (2019-2022). Causes listed: suicide (28%), workplace accidents (22%), 'natural causes' (35%), murder (15%). Families report difficulty obtaining autopsy reports or death certificates with accurate cause of death. Repatriation of remains takes 2-6 months and costs KES 500,000+. Several high-profile cases prompted Parliamentary inquiries (2021, 2023).",
        "source": "Kenya Embassy Riyadh / Nation Media / Kenya Parliament Hansard",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KE",
        "title": "Kenya Bilateral Labour Agreement with Saudi Arabia (2019)",
        "summary": "Kenya signed a bilateral labour agreement with Saudi Arabia in 2019. Provisions include: standard employment contract for domestic workers, minimum salary of SAR 1,000/month, weekly rest day, employer-paid health insurance, dispute resolution mechanism, and consular notification requirements. Implementation hampered by: lack of enforcement mechanism, Saudi resistance to domestic worker protections, and continued dominance of informal recruitment channels.",
        "source": "MoL Kenya / Saudi MoHRSD / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "title": "Somali Refugee Exploitation in Kenyan Urban Areas",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "services",
        "summary": "An estimated 500,000 Somali refugees in Kenya, many in Nairobi's Eastleigh district. Urban refugees exploited in informal sector: domestic work, hospitality, small businesses. Lack of work permits forces irregular employment at below-market wages. Employers threaten to report workers to police. Women particularly vulnerable to sexual exploitation. UNHCR Kenya identifies urban refugees as high-risk trafficking population.",
        "source": "UNHCR Kenya / IOM / Refugee Consortium of Kenya",
    },
    {
        "type": "advisory",
        "jurisdiction": "KE",
        "title": "Kenya TIP Report Tier Rating",
        "summary": "US TIP Report rates Kenya as Tier 2 (2024). Kenya demonstrates increasing efforts: 34 trafficking convictions (2023), national referral mechanism operational, NEA expanding regulatory capacity. Ongoing concerns: insufficient investigation of complicit officials, limited victim services funding, inadequate regulation of recruitment agencies, and failure to address internal trafficking of children at scale.",
        "source": "US State Dept TIP Report 2024",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "title": "Forced Labour in Kenyan Tea and Flower Sectors",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Kenya is the world's largest tea exporter and a major cut-flower producer. Investigations have documented: piece-rate pay below minimum wage on tea plantations, excessive hours (10-12 hours daily during peak), exposure to pesticides without PPE in flower farms, sexual harassment of women workers, and casualization (90% of workforce on temporary contracts without benefits). Lake Naivasha flower farms employ 50,000+ workers under these conditions.",
        "source": "Kenya Human Rights Commission / War on Want / Fairtrade Foundation",
    },
    # ══════════════════════════════════════════════════════════════════════
    # NIGERIA (NG) -- at least 15 facts
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "NG",
        "title": "Nigeria Trafficking in Persons (Prohibition) Enforcement and Administration Act (2003, amended 2015)",
        "summary": "Nigeria's comprehensive anti-trafficking law. Establishes NAPTIP (National Agency for the Prohibition of Trafficking in Persons). Criminalizes all forms of trafficking with penalties of 5 years to life imprisonment. 2015 amendments increased penalties, expanded definitions to cover organ harvesting and baby factories, and strengthened NAPTIP's enforcement powers including asset forfeiture.",
        "source": "NAPTIP / Nigeria Official Gazette / US TIP Report",
    },
    {
        "type": "statistic",
        "jurisdiction": "NG",
        "title": "NAPTIP Enforcement Data",
        "metric": "Trafficking prosecutions and convictions",
        "value": "700+ convictions (2004-2023)",
        "year": 2023,
        "summary": "NAPTIP has secured over 700 trafficking convictions since inception (2004-2023). Annual averages: 100+ investigations, 50-70 prosecutions, 30-40 convictions. Rescued 18,000+ victims. However, conviction rates remain low relative to scale of trafficking. Penalties often below statutory maximum. State task forces in Edo, Lagos, and Kano supplement NAPTIP operations.",
        "source": "NAPTIP Annual Reports / US TIP Report 2024",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "corridor": "NG-LY",
        "title": "Nigerian Migrants Exploited in Libya Transit",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "Libya is the primary transit country for Nigerians heading to Europe. An estimated 200,000+ Nigerians were stranded in Libya (2017 peak). Exploitation includes: forced labour in construction and agriculture, sexual exploitation of women, detention in informal prisons, ransom demands (USD 500-5,000), sale at 'slave markets' (CNN 2017 investigation). IOM emergency evacuated 19,000+ Nigerians from Libya (2017-2020). Many returnees re-trafficked to Libya.",
        "source": "CNN Investigation / IOM / NAPTIP / UNHCR",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "corridor": "NG-IT",
        "title": "Nigerian Sex Trafficking Networks in Italy",
        "exploitation_type": "debt_bondage",
        "sector": "sex_trafficking",
        "summary": "Nigeria-to-Italy is one of the world's most documented sex trafficking corridors. Edo State (Benin City) is primary origin. Women and girls recruited with false promises of jobs, subjected to juju/voodoo rituals creating psychological bondage. Debt of EUR 30,000-65,000 imposed for 'travel costs.' Madams (often former trafficking victims) control women in Italy. 80% of Nigerian women arriving in Italy by sea are trafficking victims (IOM estimate). Italian authorities prosecute 100+ trafficking cases annually linked to Nigerian networks.",
        "source": "IOM / UNICRI / Italian DIA / NAPTIP",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "corridor": "NG-EU",
        "title": "Nigerian Trafficking Routes to Europe -- Trans-Saharan and Maritime",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Two primary NG-EU routes: (1) Trans-Saharan through Niger-Libya-Mediterranean to Italy, and (2) through Morocco-Spain (Canary Islands or Ceuta). 80% of trafficking victims identified in Europe who are African are Nigerian. Routes controlled by organized crime networks connecting Nigerian madams with Libyan smugglers and European facilitators. Exploitation at every transit point. EU-funded AVRR programs returned 30,000+ Nigerians (2017-2023).",
        "source": "UNODC / Frontex / NAPTIP / Europol",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "title": "Internal Trafficking in Nigeria -- Domestic Work and Agriculture",
        "exploitation_type": "debt_bondage",
        "sector": "domestic_work",
        "summary": "Internal trafficking is Nigeria's most prevalent form. Children trafficked from rural states (Akwa Ibom, Cross River, Benue, Oyo) to Lagos, Abuja, and Port Harcourt for domestic work, street vending, and begging. Granite mining in Ogun and Ekiti states uses child labour. Agriculture in northern states employs children in exploitative conditions. NAPTIP estimates 15 million Nigerian children engaged in child labour, with 2+ million in worst forms.",
        "source": "NAPTIP / UNICEF Nigeria / US DOL ILAB",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "title": "Baby Factory Cases in Nigeria",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "Nigeria has documented numerous 'baby factory' cases -- facilities where young women and girls are confined, impregnated, and their babies sold. Documented in Imo, Abia, Lagos, Ebonyi, and Anambra states. Babies sold for NGN 500,000-3,000,000 (USD 300-1,800) for illegal adoption, rituals, or trafficking. Police raided 30+ facilities (2018-2023). Victims include women trafficked specifically for this purpose and homeless/destitute women lured with shelter promises.",
        "source": "NAPTIP / Nigeria Police Force / Premium Times / Guardian Nigeria",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "corridor": "NG-SA",
        "title": "Nigerian Workers Exploited in Saudi Arabia",
        "exploitation_type": "deception",
        "sector": "domestic_work",
        "summary": "Growing corridor of Nigerian women recruited for domestic work in Saudi Arabia. Recruitment through social media and informal networks. Workers report: different employers than promised, wages 50% below contract, passport confiscation, physical abuse, and inability to return. Nigerian embassy in Riyadh handles 50+ distress cases monthly. Nigeria lacks a bilateral labour agreement with Saudi Arabia, leaving workers without institutional protection.",
        "source": "NAPTIP / IOM / Nigeria Embassy Riyadh",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "title": "Boko Haram and Trafficking in Northeast Nigeria",
        "exploitation_type": "physical_sexual_violence",
        "sector": "multiple",
        "summary": "Boko Haram insurgency (2009-present) has created acute trafficking conditions in northeast Nigeria. Armed groups abduct women and girls for forced marriage and sexual slavery (Chibok 2014: 276 girls, Dapchi 2018: 110 girls). IDPs in camps (2.2 million displaced) exploited through transactional sex, child labour, and forced recruitment. Camp officials documented facilitating exploitation. Trafficking intersects with conflict and displacement.",
        "source": "UNHCR / UNODC / US TIP Report / NAPTIP",
    },
    {
        "type": "advisory",
        "jurisdiction": "NG",
        "title": "Nigeria TIP Report Tier Rating and Edo State Response",
        "summary": "US TIP Report rates Nigeria as Tier 2 (2024). Edo State, the origin of most sex trafficking victims, established the Edo State Task Force Against Human Trafficking (ETAHT) in 2017 under Governor Obaseki. ETAHT convicted 100+ traffickers (2017-2023), operated shelters, and conducted community awareness reducing recruitment by 60% in targeted communities. Model for sub-national anti-trafficking response.",
        "source": "US State Dept TIP Report 2024 / ETAHT",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "title": "Nigerian Fishermen Exploited in Ghana and Cameroon",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "Nigerian fishermen recruited for work on Lake Volta (Ghana) and Atlantic fishing boats operating from Cameroon. Workers report: debt bondage for boat passage, confinement to remote fishing camps, non-payment of wages, threats of violence for attempting to leave. Some fishermen held for years. IOM documented 200+ cases (2019-2023). Cross-border nature complicates prosecution under both Nigerian and Ghanaian law.",
        "source": "IOM / NAPTIP / Ghana Anti-Human Trafficking Unit",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "corridor": "NG-MA",
        "title": "Nigerians Stranded in Morocco -- Transit Exploitation",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Morocco is an increasingly important transit country for Nigerians heading to Europe. Estimated 15,000-20,000 Nigerians in Morocco at any time (IOM). Workers exploited in agriculture (seasonal harvest), construction, and domestic work while waiting for crossing opportunity. Women and girls face sexual exploitation. Moroccan authorities conduct periodic roundups and relocations of sub-Saharan migrants from border areas. IOM provides AVRR from Morocco.",
        "source": "IOM / GADEM / Medecins Sans Frontieres",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "title": "Juju Rituals as Psychological Coercion in Nigerian Trafficking",
        "exploitation_type": "intimidation",
        "sector": "sex_trafficking",
        "summary": "Trafficking networks from Edo State use traditional oath-taking (juju) ceremonies to psychologically bind victims. Rituals involve: blood oaths, ingestion of substances, threats of madness or death for breaking the oath. Victims are told they will die if they report trafficking to police or refuse to pay debt. Psychological control persists even in destination countries. NAPTIP and Oba of Benin (2018) conducted public ceremony revoking all trafficking-related oaths, which reportedly helped some victims come forward.",
        "source": "UNODC / Anti-Slavery International / NAPTIP",
    },
    {
        "type": "statistic",
        "jurisdiction": "NG",
        "title": "Nigeria Anti-Trafficking Victim Identification",
        "metric": "Victims identified by NAPTIP annually",
        "value": "1,500-2,000",
        "year": 2023,
        "summary": "NAPTIP identifies 1,500-2,000 trafficking victims annually (2020-2023). 60% are children, 70% are female. Internal trafficking accounts for 65% of identified victims. NAPTIP operates 8 shelters across Nigeria with capacity for 300 residents at a time. IOM repatriated 19,000+ Nigerian victims from Libya alone (2017-2020). Actual victim population estimated at 1.4 million (Global Slavery Index).",
        "source": "NAPTIP / IOM / Global Slavery Index 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "title": "Almajiri Child Exploitation in Northern Nigeria",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "An estimated 10 million Almajiri children in northern Nigeria -- boys sent by families to Quranic schools (tsangaya). Many schools require children to beg for food and money, which teachers (mallams) keep. Children work as street vendors, scavengers, and farmhands. Living conditions include: sleeping outdoors, malnutrition, physical punishment. System intersects with internal trafficking when children are sent far from home. Federal government banned street begging (2020) but enforcement is negligible.",
        "source": "UNICEF Nigeria / HRW / US TIP Report",
    },
    # ══════════════════════════════════════════════════════════════════════
    # GHANA (GH) -- at least 10 facts
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "GH",
        "title": "Ghana Human Trafficking Act 2005 (Act 694)",
        "summary": "Ghana's primary anti-trafficking legislation. Criminalizes trafficking in persons with penalties of 5-25 years imprisonment. Establishes the Human Trafficking Management Board. Covers recruitment, transportation, harbouring for exploitation. 2009 amendment (Act 784) increased penalties and expanded definition to include internal trafficking. Ghana was the first West African country to enact specific anti-trafficking legislation.",
        "source": "Ghana Law / UNODC / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "GH",
        "title": "Lake Volta Child Fishing Slavery -- Ghana's Largest Internal Trafficking Pattern",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "Lake Volta (world's largest artificial lake) is the site of Ghana's most documented child trafficking. An estimated 20,000+ children (some as young as 4) trafficked from Volta, Northern, and Upper East regions. Children dive to disentangle nets (drowning risk), paddle boats, and process fish. Purchased from families for GHS 200-500 (USD 15-40) or 'fostered' to fishermen. Working 14-16 hours daily. IJM and Partners in Community Development Programme have rescued 3,000+ children since 2009.",
        "source": "IJM / IOM / Ghana Anti-Human Trafficking Unit / ILO-IPEC",
    },
    {
        "type": "case_study",
        "jurisdiction": "GH",
        "title": "Cocoa Sector Child Labour in Ghana",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Ghana is the world's second-largest cocoa producer. NORC study (2020) found 770,000 children in child labour in Ghanaian cocoa (similar figure for Cote d'Ivoire). Children use machetes, carry heavy loads, apply pesticides. Some are trafficked from northern Ghana or neighbouring countries (Burkina Faso, Togo). Harkin-Engel Protocol (2001) industry commitment to eliminate worst forms by 2005 (extended to 2025) has not succeeded. Child labour increased 14% since 2010.",
        "source": "NORC / US DOL ILAB / ILO-IPEC / Cocoa Barometer 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "GH",
        "corridor": "GH-SA",
        "title": "Ghanaian Domestic Workers Exploited in Gulf States",
        "exploitation_type": "deception",
        "sector": "domestic_work",
        "summary": "Growing migration of Ghanaian women to Saudi Arabia, Kuwait, and UAE for domestic work. Recruitment through informal networks and unlicensed agencies. Workers report: contract substitution, passport confiscation, non-payment of wages, physical abuse, and confinement. Ghana Immigration Service and MoELR lack systematic registration of outgoing domestic workers. No bilateral labour agreements with Gulf states as of 2024.",
        "source": "IOM Ghana / Ghana Immigration Service / Migrant-Rights.org",
    },
    {
        "type": "case_study",
        "jurisdiction": "GH",
        "title": "Trokosi System -- Ritual Servitude in Ghana",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Trokosi is a traditional practice in Volta Region where young girls (aged 8-15) are given to shrines to atone for family offenses. Girls serve shrine priests for years or life, performing domestic work, farming, and subjected to sexual exploitation. Estimated 3,000-5,000 trokosi in Ghana. Criminal Code Amendment Act 1998 criminalized trokosi (Section 314A) with penalty of 3+ years imprisonment. International Needs Ghana has freed 4,000+ girls. Practice continues in reduced form despite legal prohibition.",
        "source": "International Needs / HRW / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "GH",
        "title": "Kayaye (Head Porters) -- Internal Trafficking of Girls to Accra",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "services",
        "summary": "An estimated 60,000-100,000 kayaye (female head porters) in Accra and Kumasi markets, predominantly girls and young women from northern Ghana (Tamale, Bolgatanga, Wa). Recruited by agents or migrate independently seeking income. Sleep in open markets, earn GHS 10-30/day (USD 0.80-2.50), face sexual violence, and work while pregnant. Many are trafficking victims: recruited with false promises, wages controlled by 'madams.' Kayaye is Ghana's most visible form of urban child labour.",
        "source": "IOM Ghana / UNICEF / Challenging Heights",
    },
    {
        "type": "statistic",
        "jurisdiction": "GH",
        "title": "Ghana Child Labour Prevalence",
        "metric": "Children in child labour",
        "value": "1.9 million (21% of children aged 5-17)",
        "year": 2022,
        "summary": "Ghana's child labour rate remains among the highest in West Africa. 1.9 million children in child labour (2022 survey), with 1.2 million in hazardous work. Sectors: agriculture (70%, primarily cocoa and fishing), domestic work (15%), mining (5%), street vending (10%). Regional disparities: Northern and Upper regions have rates above 35%. National Plan of Action on Child Labour (2017-2021) had limited impact.",
        "source": "Ghana Statistical Service / ILO-IPEC / UNICEF",
    },
    {
        "type": "case_study",
        "jurisdiction": "GH",
        "title": "Small-Scale Mining (Galamsey) Child Labour in Ghana",
        "exploitation_type": "excessive_overtime",
        "sector": "mining",
        "summary": "An estimated 50,000+ children work in Ghana's small-scale gold mining (galamsey). Children dig shafts, carry ore, wash gold using mercury. Exposure to mercury causes neurological damage. Mine collapses kill children annually. Documented in Western, Ashanti, and Eastern regions. Chinese-operated galamsey operations employ both children and adults under exploitative conditions. Government's 'Operation Vanguard' anti-galamsey enforcement has disrupted some operations but enforcement is uneven.",
        "source": "US DOL ILAB / ILO / Solidaridad / Ghana Minerals Commission",
    },
    {
        "type": "advisory",
        "jurisdiction": "GH",
        "title": "Ghana TIP Report Tier Rating",
        "summary": "US TIP Report rates Ghana as Tier 2 (2024). Ghana demonstrates significant efforts: Anti-Human Trafficking Unit secured 30+ convictions (2023), government operates 2 shelters, National Plan of Action against Trafficking updated. Concerns: limited funding for victim services, inadequate regulation of recruitment agencies, judicial delays (cases take 3-5 years), and insufficient attention to adult forced labour in cocoa and fishing sectors.",
        "source": "US State Dept TIP Report 2024",
    },
    {
        "type": "case_study",
        "jurisdiction": "GH",
        "title": "Ghanaian Workers Exploited in Libya and North Africa",
        "exploitation_type": "multiple",
        "sector": "construction",
        "summary": "Ghanaian men transit through Burkina Faso and Niger to reach Libya, seeking passage to Europe. Many are stranded and exploited in Libyan construction and agriculture. Reports include: forced labour, detention in warehouses, ransom demands from families (USD 1,000-3,000), beatings, and sale to other employers. IOM repatriated 5,000+ Ghanaians from Libya (2017-2022). Returnees report severe trauma. Some re-migrate within months.",
        "source": "IOM / Ghana Immigration Service / BBC Africa",
    },
    # ══════════════════════════════════════════════════════════════════════
    # SOUTH AFRICA (ZA) -- at least 10 facts
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "ZA",
        "title": "South Africa Prevention and Combating of Trafficking in Persons Act 7 of 2013",
        "summary": "South Africa's comprehensive anti-trafficking legislation, effective July 2015. Criminalizes all forms of trafficking with penalties up to life imprisonment. Establishes a national inter-sectoral committee on trafficking. Provides for victim identification, protection, and repatriation. Requires forfeiture of assets from trafficking proceeds. Also criminalizes forced labour and debt bondage as standalone offenses. Extraterritorial jurisdiction for South African nationals or residents.",
        "source": "South Africa Government Gazette / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "ZA",
        "title": "Zimbabwean and Mozambican Worker Exploitation in South Africa",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "South Africa hosts an estimated 3-4 million migrants from Zimbabwe, Mozambique, Malawi, and other countries. Undocumented workers (60%+) face severe exploitation: below-minimum wages (often 30-50% of legal minimum), no written contracts, no access to labour courts due to fear of deportation, arbitrary dismissal. Sectors: agriculture (Limpopo, Mpumalanga), construction, domestic work, hospitality, mining. Xenophobic violence compounds vulnerability.",
        "source": "IOM South Africa / Consortium for Refugees and Migrants in SA / HRW",
    },
    {
        "type": "case_study",
        "jurisdiction": "ZA",
        "title": "Farm Worker Exploitation in Western Cape -- De Doorns and Stellenbosch",
        "exploitation_type": "withholding_wages",
        "sector": "agriculture",
        "summary": "Western Cape wine and fruit farms employ thousands of migrant workers from Zimbabwe, Lesotho, and Mozambique alongside South African labourers. Documented exploitation: wages below sectoral minimum (ZAR 25/hour, 2024), piece-rate systems that penalize workers, housing in dilapidated on-farm compounds, pesticide exposure without PPE, dismissal without notice. 2012-2013 De Doorns farm worker strikes highlighted conditions. Labour inspectorate has 1,500 inspectors for the entire country.",
        "source": "Women on Farms Project / Human Rights Watch / BAWSI",
    },
    {
        "type": "case_study",
        "jurisdiction": "ZA",
        "title": "Mining Sector Labour Exploitation in South Africa",
        "exploitation_type": "excessive_overtime",
        "sector": "mining",
        "summary": "South Africa's mining sector employs 500,000+ workers. Migrant workers from Mozambique, Lesotho, Swaziland, and Zimbabwe in underground gold and platinum mines face: silicosis and other occupational diseases (30% prevalence in gold miners), contractor-labour system that reduces protections, hostel housing separating families, below-minimum wages for subcontracted workers. Marikana massacre (2012, 34 miners killed by police) exposed conditions. Ex-mineworkers in home countries receive inadequate compensation for occupational disease.",
        "source": "TEBA / Bench Marks Foundation / Marikana Commission / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "ZA",
        "title": "Trafficking for Sexual Exploitation in South Africa",
        "exploitation_type": "debt_bondage",
        "sector": "sex_trafficking",
        "summary": "South Africa is a destination for sex trafficking from Mozambique, Zimbabwe, DRC, Thailand, and China. Major trafficking hubs: Johannesburg (Hillbrow), Durban, Cape Town. Women and girls from Mozambique trafficked through Komatipoort border. Internal trafficking of South African girls from Eastern Cape and KwaZulu-Natal to Gauteng. Brothel raids have identified victims as young as 13. Hawks (Directorate for Priority Crime Investigation) has a dedicated human trafficking unit.",
        "source": "Hawks / US TIP Report / UNODC / Stop Trafficking SA",
    },
    {
        "type": "case_study",
        "jurisdiction": "ZA",
        "title": "Undocumented Migrant Workers in South African Informal Economy",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "services",
        "summary": "An estimated 2-4 million undocumented migrants in South Africa's informal economy. Workers in car washes, restaurants, spaza shops, construction, and domestic work earn below minimum wage with no protections. Fear of deportation prevents reporting. Employers use documentation status as leverage. Lindela Repatriation Centre processes 2,000+ deportees monthly. South African Constitutional Court ruled (Kylie v CCMA, 2010) that all workers, including undocumented, have labour rights, but enforcement for undocumented workers remains virtually nonexistent.",
        "source": "CCMA / Constitutional Court / Lawyers for Human Rights / IOM",
    },
    {
        "type": "statistic",
        "jurisdiction": "ZA",
        "title": "South Africa Trafficking Prosecutions",
        "metric": "Trafficking convictions under TIP Act",
        "value": "40+ (2015-2023)",
        "year": 2023,
        "summary": "Since the TIP Act took effect in 2015, South Africa has secured approximately 40 trafficking convictions, a low number given the estimated scale of trafficking. NPA (National Prosecuting Authority) cites challenges: complex cases requiring 2-4 years to prosecute, witness intimidation, difficulty proving exploitation versus smuggling, and insufficient training of prosecutors. Hawks' Human Trafficking desk has 30 investigators nationally.",
        "source": "NPA / Hawks / US TIP Report 2024",
    },
    {
        "type": "case_study",
        "jurisdiction": "ZA",
        "title": "Ethiopian and Somali Migrants Exploited in South African Spaza Shops",
        "exploitation_type": "debt_bondage",
        "sector": "retail",
        "summary": "Ethiopian and Somali migrants operate or work in spaza shops (informal convenience stores) across South African townships. Workers recruited from East Africa pay USD 3,000-5,000 to smugglers/employers for passage and placement. Work 14-16 hours daily, sleep in shop, wages withheld until 'debt' repaid (12-18 months). Shops targeted in xenophobic attacks (2008, 2015, 2019). Workers cannot report exploitation due to irregular status and community hostility.",
        "source": "SAMP (Southern African Migration Programme) / IOM / Scalabrini Centre",
    },
    {
        "type": "case_study",
        "jurisdiction": "ZA",
        "title": "Child Trafficking in South Africa -- Domestic and Cross-Border",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Children trafficked within South Africa and from neighbouring countries for: domestic work, street vending, sexual exploitation, and drug running. Eastern Cape to Gauteng is a primary internal route. Children from Mozambique trafficked through Mpumalanga. DSD (Department of Social Development) identifies 200+ child trafficking victims annually but estimates actual numbers are 10x higher. Unaccompanied minors from Zimbabwe (estimated 100,000+) are particularly vulnerable.",
        "source": "DSD / UNICEF / Molo Songololo / US TIP Report",
    },
    {
        "type": "advisory",
        "jurisdiction": "ZA",
        "title": "South Africa TIP Report Tier Rating",
        "summary": "US TIP Report rates South Africa as Tier 2 (2024). Significant efforts noted: inter-departmental coordination improving, National Policy Framework finalized (2019), provincial anti-trafficking task teams active in Gauteng, Western Cape, KZN. Concerns: low conviction rate, victim identification remains weak (especially for labour trafficking), inadequate shelters (only 3 government-funded), and continued conflation of trafficking with smuggling in law enforcement practice.",
        "source": "US State Dept TIP Report 2024",
    },
    # ══════════════════════════════════════════════════════════════════════
    # REGIONAL PATTERNS -- at least 30 facts
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "AU-regional",
        "title": "AU Ouagadougou Action Plan to Combat Trafficking in Human Beings (2006)",
        "summary": "Adopted by the AU-EU Ministerial Conference in Tripoli (2006). Comprehensive framework covering: prevention (awareness, root causes), protection (victim assistance, safe return), prosecution (legislative harmonization, mutual legal assistance), and partnership (cooperation between origin/transit/destination countries). Non-binding but has guided national legislation in 30+ African countries. Updated at AU-EU Summits in 2010, 2014, and 2017.",
        "source": "African Union / EU External Action Service",
    },
    {
        "type": "law",
        "jurisdiction": "ECOWAS",
        "title": "ECOWAS Initial Plan of Action against Trafficking in Persons (2002-2003)",
        "summary": "ECOWAS adopted a comprehensive anti-trafficking framework including: Declaration on the Fight against Trafficking in Persons (2001), Initial Plan of Action (2002), and Multilateral Cooperation Agreement (2005). Framework addresses cross-border trafficking within West Africa, establishes a Trafficking in Persons Unit within ECOWAS Commission, and requires member states to adopt national legislation. All 15 ECOWAS states have enacted anti-trafficking laws, though enforcement varies widely.",
        "source": "ECOWAS Commission / UNODC",
    },
    {
        "type": "case_study",
        "jurisdiction": "ECOWAS",
        "title": "Intra-ECOWAS Child Trafficking -- West African Pattern",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "ECOWAS free movement protocols inadvertently facilitate child trafficking. Dominant routes: Burkina Faso and Mali to Cote d'Ivoire (cocoa), Togo and Benin to Nigeria (domestic work and markets), Ghana to Cote d'Ivoire (mining). An estimated 200,000 children trafficked annually within West Africa. ECOWAS Task Force on Trafficking (2005) coordinates, but porous borders and limited birth registration hamper prevention. Joint border operations between Nigeria-Benin and Ghana-Togo have intercepted thousands of children.",
        "source": "UNICEF / ILO-IPEC / ECOWAS Commission / Terre des Hommes",
    },
    {
        "type": "case_study",
        "jurisdiction": "regional-east-africa",
        "title": "East African Trafficking Routes -- Kenya-Tanzania-Uganda Triangle",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "East Africa Community (EAC) countries experience complex internal and cross-border trafficking. Kenya-Tanzania: children trafficked for domestic work and agriculture. Uganda-Kenya: girls trafficked for sexual exploitation in Nairobi. Rwanda-Uganda: cross-border exploitation in agriculture. Tanzania-Middle East: growing domestic worker corridor via Nairobi or Addis Ababa. EAC Common Market Protocol provides free movement but no anti-trafficking harmonization.",
        "source": "UNODC East Africa / IOM / HAART Kenya",
    },
    {
        "type": "case_study",
        "jurisdiction": "LY",
        "title": "North Africa Transit Exploitation -- Libya as Hub",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "Libya is the primary transit point for African migrants heading to Europe. An estimated 600,000-1,000,000 migrants in Libya at any time. Post-Gaddafi (2011) collapse of state authority created trafficking vacuum. Exploitation includes: forced labour in construction and agriculture, sexual exploitation, detention in government and militia-run centres, ransom (USD 1,000-10,000), and 'slave auctions' (CNN documented in 2017). IOM estimates 60%+ of migrants in Libya experience exploitation. EU-funded Libyan Coast Guard returns intercepted migrants to detention centres.",
        "source": "CNN / IOM / UNHCR / MSF / OHCHR",
    },
    {
        "type": "case_study",
        "jurisdiction": "TN",
        "title": "Tunisia as Emerging Transit Hub -- Sub-Saharan Migrant Exploitation",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "agriculture",
        "summary": "Tunisia has become an increasingly important transit country for sub-Saharan migrants seeking to reach Europe via Lampedusa (Italy). In 2023, Tunisia surpassed Libya as the primary departure point for Mediterranean crossings. Sub-Saharan migrants face: exploitation in agriculture (olive harvest, date farms), racist violence, arbitrary detention, and forced relocations to desert border areas. President Saied's 2023 remarks about 'demographic replacement' increased xenophobic targeting of sub-Saharan Africans.",
        "source": "FTDES / MSF / UNHCR / Alarm Phone",
    },
    {
        "type": "case_study",
        "jurisdiction": "regional-gulf",
        "corridor": "ET-SA",
        "title": "Gulf Migration from East Africa -- Dangerous Routes",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "East Africans (primarily Ethiopians, Somalis, and Eritreans) migrate to Gulf states via two routes: (1) Djibouti-Yemen-Saudi (Eastern Route), and (2) Sudan-Egypt-Libya-Mediterranean. IOM estimated 150,000+ East Africans transited Yemen annually (pre-2020). Workers exploited at every stage: smuggler extortion, forced labour in Yemen, detention in Saudi Arabia. COVID-19 led to mass deportations: Saudi expelled 16,000+ Ethiopians (2020). Many transited war-torn Yemen both ways.",
        "source": "IOM / Mixed Migration Centre / RMMS / UNHCR",
    },
    {
        "type": "case_study",
        "jurisdiction": "regional-sahel",
        "title": "Sahel Trafficking Networks -- Niger as Crossroads",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Niger's Agadez region is the primary crossroads for trans-Saharan migration. An estimated 300,000+ migrants passed through Agadez annually before Niger's 2015 anti-smuggling law. Smuggling networks overlap with trafficking: migrants who cannot pay are abandoned in the Sahara, sold to Libyan groups, or forced to work. IOM desert rescue operations save thousands annually (5,000+ rescued from Sahara 2016-2023). Niger's 2015 law criminalized smuggling but pushed routes underground, increasing danger. Military coup (2023) further destabilized migration governance.",
        "source": "IOM / UNODC / Mixed Migration Centre / Alarm Phone Sahara",
    },
    {
        "type": "case_study",
        "jurisdiction": "ER",
        "title": "Eritrean Refugee Exploitation -- Sinai, Libya, and Sudan",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "Eritreans fleeing indefinite military conscription are among the most exploited refugees globally. Trafficking patterns: (1) Sinai trafficking (2009-2015): Eritreans kidnapped from Sudanese refugee camps, sold to Bedouin traffickers in Sinai, tortured for ransom (USD 10,000-50,000), organs harvested; (2) Libya: detention, forced labour, sexual violence; (3) Sudan: exploitation in gold mining, domestic work. An estimated 500,000+ Eritreans in diaspora. UNHCR identifies Eritreans as highest per-capita refugee population globally.",
        "source": "UNHCR / HRW / UN Commission of Inquiry on Eritrea / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "title": "Somali Refugee Exploitation in Dadaab and Kakuma Camps -- Kenya",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Kenya hosts 580,000+ registered refugees, primarily Somali (Dadaab: 370,000) and South Sudanese (Kakuma: 210,000). Camp-based exploitation includes: child marriage (girls aged 13-15 married to older men for bride price), sexual exploitation by camp officials and community members, child labour in camp businesses, and trafficking networks recruiting from camps for domestic work in Nairobi and Gulf states. Kenya's encampment policy restricts refugee movement and employment, increasing vulnerability.",
        "source": "UNHCR / Refugee Consortium of Kenya / Danish Refugee Council",
    },
    {
        "type": "case_study",
        "jurisdiction": "MG",
        "corridor": "MG-SA",
        "title": "Madagascar-Gulf Corridor -- Domestic Worker Exploitation",
        "exploitation_type": "deception",
        "sector": "domestic_work",
        "summary": "Madagascar is an emerging origin country for domestic workers to Saudi Arabia, Kuwait, and Lebanon. Workers recruited through social media and informal agents in Antananarivo. Reports of: contract substitution, wages 50% below promised amount, passport confiscation, and physical abuse. Madagascar lacks overseas employment legislation or bilateral labour agreements with Gulf states. Government capacity to protect overseas workers is severely limited. IOM documented 300+ distress cases (2021-2023).",
        "source": "IOM Madagascar / US TIP Report / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "MU",
        "title": "Mauritius Factory Exploitation -- Bangladeshi and Malagasy Workers",
        "exploitation_type": "debt_bondage",
        "sector": "garment",
        "summary": "Mauritius hosts 35,000+ migrant workers in garment, textile, and seafood processing. Workers from Bangladesh, India, Madagascar, and China pay USD 1,500-3,000 recruitment fees. Three-year contracts with: salary deductions for accommodation (30%), confinement to dormitories, passport retention, forced overtime during peak season, and dismissal threats for complaints. Mauritius has bilateral agreements but enforcement is inconsistent. US and EU market access tied to labour standards has driven some improvements.",
        "source": "Verité / Anti-Slavery International / Mauritius MoL / ITUC",
    },
    {
        "type": "case_study",
        "jurisdiction": "CM",
        "title": "Child Trafficking in Cameroon -- Cocoa and Domestic Work",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Cameroon is an origin, transit, and destination country for trafficking. Children from northern regions trafficked to cocoa farms in South West and Littoral regions. Children from Nigeria and Central African Republic trafficked through Cameroon. Girls trafficked for domestic work in Douala and Yaounde. Boys exploited in fishing on Lake Nyos and agriculture. An estimated 1.5 million children in child labour. Anti-trafficking law (2011) provides penalties of 10-20 years but convictions remain rare (fewer than 10 annually).",
        "source": "US TIP Report / UNICEF / ILO / Plan International",
    },
    {
        "type": "case_study",
        "jurisdiction": "CI",
        "title": "Cote d'Ivoire Cocoa Child Labour -- Trafficking from Burkina Faso and Mali",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Cote d'Ivoire is the world's largest cocoa producer. NORC study (2020) found 790,000 children in child labour in Ivorian cocoa. Children trafficked from Burkina Faso and Mali by recruiters promising school and wages. Reality: 12-14 hour days, machete use, pesticide application, carrying 30-50kg loads. Workers paid in kind (food, shelter) not cash. Interpol operations (Operation Kolosse) have intercepted thousands of children. Industry commitments (Harkin-Engel, 2001) have not eliminated the practice.",
        "source": "NORC / US DOL ILAB / Mighty Earth / ICI (International Cocoa Initiative)",
    },
    {
        "type": "case_study",
        "jurisdiction": "MZ",
        "title": "Mozambican Workers Exploited in South Africa -- Cross-Border Pattern",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "agriculture",
        "summary": "Mozambique-South Africa is one of Africa's oldest labour migration corridors (dating to gold mining in 1890s). Currently: 500,000+ Mozambicans work in South African agriculture, mining, construction, and domestic work. Exploitation patterns: below-minimum wages (60% of legal rate), no written contracts, housing in shacks on farms, employer confiscation of documents, and physical abuse. Workers cross via informal border points in Mpumalanga and Limpopo. Deportation fear prevents reporting. Bilateral agreement (1964, revised 2007) covers only mining.",
        "source": "IOM / TEBA / SAMP / Lawyers for Human Rights",
    },
    {
        "type": "case_study",
        "jurisdiction": "SD",
        "title": "Sudan Trafficking -- Gold Mining and Refugee Exploitation",
        "exploitation_type": "multiple",
        "sector": "mining",
        "summary": "Sudan has complex trafficking patterns: (1) Artisanal gold mining in Darfur, River Nile, and Red Sea states uses forced labour including children; (2) Eritrean and Ethiopian refugees in eastern Sudan exploited in agriculture and domestic work; (3) South Sudanese refugees in Khartoum exploited in informal sector; (4) Sudanese trafficked to Libya and Gulf states. Civil war (2023-present) has displaced 8+ million and destroyed anti-trafficking institutions. UNODC reports trafficking has surged since conflict began.",
        "source": "UNODC / UNHCR / US TIP Report / OHCHR",
    },
    {
        "type": "case_study",
        "jurisdiction": "UG",
        "title": "Ugandan Workers Exploited in Middle East and China",
        "exploitation_type": "deception",
        "sector": "domestic_work",
        "summary": "Uganda is an emerging source country for domestic workers to Saudi Arabia, UAE, Oman, and increasingly China. Workers recruited through licensed and unlicensed agencies pay UGX 2-5 million (USD 500-1,300). Reports of: contract substitution, wages 50% below promised, confinement, physical abuse. Uganda-China corridor emerged in 2019: workers lured with factory job promises but subjected to exploitation. Ministry of Gender Labour and Social Development (MoGLSD) suspended 15 agencies (2022) but enforcement capacity is limited.",
        "source": "IOM Uganda / US TIP Report / Monitor Uganda / Daily Monitor",
    },
    {
        "type": "case_study",
        "jurisdiction": "TZ",
        "title": "Tanzanian Mining and Domestic Work Child Trafficking",
        "exploitation_type": "excessive_overtime",
        "sector": "mining",
        "summary": "Tanzania has significant child trafficking in artisanal mining (Mwanza gold mines: 30,000+ children), domestic work (internal trafficking from rural to Dar es Salaam), and agriculture (tobacco, tea, coffee). Tanzanite mining in Mererani involves children in dangerous underground shafts. Anti-Trafficking in Persons Act (2008) provides penalties of 2-20 years. Fewer than 15 convictions annually. Tanzania TIP rating: Tier 2 Watch List.",
        "source": "US DOL ILAB / HRW / ILO / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "MW",
        "title": "Malawian Workers Exploited in Mozambique and South Africa",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "agriculture",
        "summary": "Malawians migrate to Mozambique (tobacco farms), South Africa (agriculture, mining, domestic work), and Zambia (mining). Workers recruited by informal agents pay MWK 200,000-500,000 (USD 100-250). Exploitation includes: below-contracted wages, no return transport, passport/document retention, and isolation on remote farms. Internal trafficking: children from rural areas to tobacco estates in Kasungu and Mzimba (65,000+ children in tobacco sector). Malawi's Trafficking in Persons Act (2015) led to 20+ convictions but enforcement is underfunded.",
        "source": "US TIP Report / IOM / Plan International / ECLT Foundation",
    },
    {
        "type": "case_study",
        "jurisdiction": "CD",
        "title": "DRC Mining Exploitation -- Cobalt and Conflict Minerals",
        "exploitation_type": "multiple",
        "sector": "mining",
        "summary": "DRC produces 70% of global cobalt (essential for batteries). An estimated 40,000+ children in artisanal cobalt mining in Katanga province. Workers (including children aged 7+) dig by hand in tunnels prone to collapse, wash ore with bare hands (cobalt toxicity), and earn USD 1-2/day. Armed groups control mining sites in eastern DRC, using forced labour. Supply chain links to Apple, Samsung, Tesla, and others. EU Battery Regulation (2023) and US Dodd-Frank Act Section 1502 require due diligence.",
        "source": "Amnesty International / SOMO / US DOL ILAB / Enough Project",
    },
    {
        "type": "case_study",
        "jurisdiction": "SO",
        "title": "Somali Refugee Exploitation -- Kenya, Ethiopia, and Yemen",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Somalia's 3+ decades of conflict have created 2.6 million IDPs and 1 million refugees. Exploitation patterns: (1) Dadaab camp (Kenya): child marriage, sexual exploitation, trafficking to Nairobi; (2) Dollo Ado camp (Ethiopia): child labour, forced movement; (3) Yemen transit: Somali refugees exploited en route to Gulf states; (4) Al-Shabaab recruitment of children as soldiers and domestic servants. Somali diaspora remittances (USD 1.7B/year) sustain the economy but also create trafficking incentive.",
        "source": "UNHCR / UNODC / IOM / Rift Valley Institute",
    },
    {
        "type": "statistic",
        "jurisdiction": "regional-africa",
        "title": "Sub-Saharan Africa Modern Slavery Prevalence",
        "metric": "Modern slavery victims in sub-Saharan Africa",
        "value": "7.0 million",
        "year": 2022,
        "summary": "ILO Global Estimates (2022): 7.0 million people in modern slavery in sub-Saharan Africa, including 3.8 million in forced labour and 3.2 million in forced marriage. Prevalence rate: 7.6 per 1,000 people (highest regional rate globally alongside Central Asia). Children constitute 26% of forced labour victims in the region. State-imposed forced labour in Eritrea (national service) is a significant contributor.",
        "source": "ILO / Walk Free / IOM Global Estimates 2022",
    },
    {
        "type": "statistic",
        "jurisdiction": "regional-africa",
        "title": "African Child Labour Prevalence",
        "metric": "Children in child labour in sub-Saharan Africa",
        "value": "86.6 million (23.9% of children)",
        "year": 2020,
        "summary": "Sub-Saharan Africa has the highest child labour rate globally: 86.6 million children aged 5-17 (23.9%), of whom 36.7 million are in hazardous work. Sectors: agriculture (80%), services (11%), industry (9%). The region is the only world region where child labour increased between 2012-2020 (by 16.6 million). Population growth, COVID-19, and conflict drive the increase. ILO targets elimination of child labour by 2025 (SDG 8.7) will not be met in Africa.",
        "source": "ILO-UNICEF Child Labour Global Estimates 2020",
    },
    {
        "type": "case_study",
        "jurisdiction": "BF",
        "title": "Burkina Faso Child Trafficking to Cote d'Ivoire Cocoa and Gold",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Burkina Faso is a major source country for children trafficked to Cote d'Ivoire (cocoa) and within Burkina Faso (gold mining). Recruiters target families in rural Sahel, Boucle du Mouhoun, and Cascades regions. Children promised school and wages but placed in cocoa farms or artisanal gold mines (Essakane, Poura). An estimated 900,000 children in child labour in Burkina Faso. Anti-trafficking law (2008) led to 50+ prosecutions but sentences are typically 5-10 years, below statutory maximum.",
        "source": "UNICEF / ILO-IPEC / US TIP Report / Plan International",
    },
    {
        "type": "case_study",
        "jurisdiction": "ML",
        "title": "Mali Child Trafficking -- Agriculture, Mining, and Armed Groups",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "Mali is origin, transit, and destination for trafficking. Children trafficked to: Cote d'Ivoire (cocoa, rice), Senegal (Quranic schools/begging), Burkina Faso (gold mining), and Guinea (domestic work). Armed groups in northern Mali forcibly recruit children as soldiers. Internal trafficking: children from rural areas to Bamako for domestic work and vending. Conflict (2012-present) has displaced 400,000+ and increased vulnerabilities. Anti-trafficking law (2012) but fewer than 5 convictions annually.",
        "source": "UNODC / UNICEF / US TIP Report / MINUSMA",
    },
    {
        "type": "case_study",
        "jurisdiction": "SN",
        "title": "Senegal Talibe Child Exploitation -- Forced Begging",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "An estimated 100,000+ talibe children in Senegal forced to beg by Quranic school teachers (marabouts). Children required to bring daily quota (CFA 300-1,000) or face beatings. Living in squalid conditions without adequate food, healthcare, or education. HRW documented 16 talibe deaths (2017-2019) from abuse, fire, and disease. Government committed to regulation but cultural and religious sensitivities impede enforcement. Anti-trafficking law criminalizes forced begging but only 10+ convictions of marabouts to date.",
        "source": "HRW / Global Partnership to End Violence Against Children / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "RW",
        "title": "Cross-Border Exploitation in the Great Lakes Region",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "The Great Lakes region (Rwanda, Burundi, DRC, Uganda, Tanzania) has complex cross-border trafficking driven by conflict and poverty. Patterns: DRC women and children trafficked to Rwanda and Uganda for domestic work and sexual exploitation, Burundian refugees in Tanzania exploited in agriculture, Rwandan women trafficked to East Africa and Middle East. Regional coordination through the International Conference on the Great Lakes Region (ICGLR) protocol on trafficking (2006). Rwanda's anti-trafficking law (2018) is considered strong but enforcement is limited.",
        "source": "ICGLR / UNODC / US TIP Report / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "AO",
        "title": "Angola -- Trafficking of Congolese Workers in Diamond Mining",
        "exploitation_type": "restriction_of_movement",
        "sector": "mining",
        "summary": "Angola's Lunda Norte and Lunda Sul provinces have significant artisanal diamond mining employing Congolese and Angolan workers. Congolese workers smuggled across the border face: forced labour in illegal diamond pits, armed guard surveillance, non-payment of wages, violence for attempting to leave. Periodic Angolan military operations (Operacao Brilhante) deport thousands of Congolese miners but do not address trafficking. Women and girls accompanying miners are exploited for sex and domestic work.",
        "source": "HRW / Partnership Africa Canada / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "regional-mediterranean",
        "title": "Mediterranean Crossing Deaths -- Africa to Europe",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "IOM's Missing Migrants Project documents 28,000+ deaths in the Mediterranean (2014-2024). Central Mediterranean (Libya/Tunisia to Italy) is deadliest route globally. Victims predominantly from West Africa (Nigeria, Guinea, Gambia), East Africa (Eritrea, Sudan, Somalia), and North Africa. Deaths from drowning, dehydration, and violence by smugglers and coast guards. Traffickers often control the journey: migrants who cannot pay face exploitation at departure points or are thrown overboard. EU's border policy (Frontex, Libyan Coast Guard) intercepts migrants and returns them to exploitation in Libya.",
        "source": "IOM Missing Migrants Project / UNHCR / MSF / Alarm Phone",
    },
    {
        "type": "case_study",
        "jurisdiction": "regional-west-africa",
        "title": "Fishing Sector Exploitation in West Africa -- Ghana, Senegal, Mauritania",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "West African fishing boats (Ghana, Senegal, Mauritania, Guinea-Bissau) employ migrant fishermen under exploitative conditions. Workers from landlocked countries (Burkina Faso, Niger, Mali) recruited for fishing with no prior experience. Debt for equipment and transport. Confinement to boats for weeks, piece-rate pay well below minimum wage. Children used on Lake Volta (Ghana), along Senegalese coast, and in Mauritanian waters. ILO C188 (Work in Fishing Convention) ratified by very few African states.",
        "source": "EJF / ILO / FAO / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "regional-north-africa",
        "title": "Algeria Deportation of Sub-Saharan Migrants",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Algeria has conducted mass deportations of sub-Saharan African migrants, including to the Niger border in the Sahara. Between 2017-2023, Algeria deported an estimated 50,000+ migrants to Niger, often abandoning them in desert areas near the border town of Assamaka. Migrants report: theft of possessions, beatings, separation of families, forced marches in desert heat. Some deportees were asylum seekers and refugees. IOM provides water and assistance at Assamaka but resources are limited. Migrants in Algeria also face exploitation in construction and agriculture before deportation.",
        "source": "AP / HRW / IOM / Alarm Phone Sahara",
    },
    {
        "type": "case_study",
        "jurisdiction": "MR",
        "title": "Mauritania -- Hereditary Slavery (Haratine)",
        "exploitation_type": "state_imposed",
        "sector": "multiple",
        "summary": "Mauritania was the last country to criminalize slavery (1981, enforced 2007). Despite legal abolition, hereditary slavery of Haratine (descendants of enslaved Black Africans) persists. An estimated 90,000+ people in slavery (Global Slavery Index). Enslaved Haratine work in domestic service, herding, and agriculture without pay. Masters control marriages, separate families, and bequeath slaves through inheritance. Anti-slavery law strengthened in 2015 (5-10 years imprisonment) but only 4 convictions by 2023. IRA (Initiative for the Resurgence of the Abolitionist Movement) activists imprisoned for anti-slavery advocacy.",
        "source": "Global Slavery Index / Anti-Slavery International / SOS Esclaves / MRG",
    },
    {
        "type": "case_study",
        "jurisdiction": "regional-east-africa",
        "title": "East Africa to Gulf Migration -- Oman and Bahrain Corridors",
        "exploitation_type": "deception",
        "sector": "domestic_work",
        "summary": "Oman and Bahrain are emerging Gulf destinations for East African domestic workers (Kenyan, Ugandan, Tanzanian, Ethiopian). Workers recruited through social media and informal agents. Exploitation patterns mirror SA-AE-KW but with even less regulatory oversight. Oman's kafala system has minimal reform. Bahrain's flexi-permit system intended to reduce exploitation but creates new vulnerabilities. Workers report: 18-hour workdays, no rest days, food deprivation, and difficulty contacting embassies (limited consular presence).",
        "source": "IOM / Migrant-Rights.org / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "DJ",
        "title": "Djibouti -- Transit Exploitation and Domestic Worker Trafficking",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Djibouti serves as a critical transit point for Ethiopian and Somali migrants heading to Yemen and Saudi Arabia. An estimated 100,000+ migrants transit Djibouti annually. Exploitation in transit: smugglers confine migrants in safe houses (200+ per house), ransom demands, sexual violence, forced labour in construction. Djibouti's own migrant worker population (30,000+ in military bases and port) faces: contract substitution, wage theft, passport confiscation. Anti-trafficking law (2007) but no trafficking convictions recorded.",
        "source": "IOM / RMMS / US TIP Report / Mixed Migration Centre",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "regional-africa",
        "title": "AU Protocol to the African Charter on Human and Peoples' Rights on the Rights of Women in Africa (Maputo Protocol, 2003)",
        "summary": "Article 4(2)(g) specifically addresses trafficking: 'States Parties shall take appropriate and effective measures to prevent and condemn trafficking in women, prosecute the perpetrators of such trafficking and protect those women most at risk.' Ratified by 44 of 55 AU member states. Provides legal basis for regional anti-trafficking legislation and cross-border cooperation. Implementation varies widely.",
        "source": "African Union / OHCHR / Equality Now",
    },
    {
        "type": "statistic",
        "jurisdiction": "regional-africa",
        "title": "African Migration to Gulf States -- Volume Estimates",
        "metric": "African migrant workers in Gulf Cooperation Council states",
        "value": "4-5 million (estimated)",
        "year": 2023,
        "summary": "An estimated 4-5 million African migrant workers in GCC states (Saudi Arabia, UAE, Qatar, Kuwait, Oman, Bahrain). Primary origins: Ethiopia (750,000+), Kenya (300,000+), Nigeria (200,000+), Uganda (200,000+), Tanzania (100,000+). Predominantly women in domestic work (65%) and men in construction/services (35%). Only 4 African countries have bilateral labour agreements with GCC states. Remittances from GCC to sub-Saharan Africa: USD 8-10B annually.",
        "source": "IOM / World Bank / ILO / Mixed Migration Centre",
    },
    {
        "type": "case_study",
        "jurisdiction": "GM",
        "title": "Gambian Youth Trafficked via 'Backway' to Europe",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "The Gambia has one of the highest per-capita emigration rates in Africa. Young Gambians take the 'backway' route through Senegal-Mali-Burkina Faso-Niger-Libya-Mediterranean. Families invest USD 1,000-3,000 (a year's income) for the journey. Youth exploited en route: forced labour in Libya, sexual exploitation, and detention. Those who reach Europe face modern slavery in agriculture (Italy), construction (Spain), and car washes (UK). IOM Return and Reintegration programs assist 2,000+ Gambians annually.",
        "source": "IOM / UNODC / Gainako / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "BI",
        "title": "Burundian Refugee Exploitation in Tanzania and DRC",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "agriculture",
        "summary": "Political crisis in Burundi (2015) displaced 400,000+ refugees, primarily to Tanzania (300,000), DRC (50,000), Rwanda, and Uganda. Refugees in Tanzanian camps (Nduta, Mtendeli, Nyarugusu) face: forced labour in surrounding tobacco farms, sexual exploitation, child marriage of adolescent girls, and restrictions on movement outside camps. Tanzania forcibly returned 72,000+ Burundians (2020-2022), violating non-refoulement. Returnees face re-trafficking risk in Burundi's conflict-affected areas.",
        "source": "UNHCR / HRW / Refugees International / IRIN",
    },
    {
        "type": "case_study",
        "jurisdiction": "SS",
        "title": "South Sudan -- Conflict-Related Trafficking and Child Soldiers",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "South Sudan's civil war (2013-2018) and ongoing instability have created widespread trafficking. Armed groups recruit children (estimated 19,000+ child soldiers since 2013). Women and girls subjected to sexual slavery and forced marriage by armed actors. IDPs (2.2 million) and refugees in Uganda (1 million+) exploited in transit and camps. Internal displacement enables domestic trafficking: children trafficked for cattle herding and domestic work. UN Panel of Experts has documented recruitment by all warring parties.",
        "source": "UNMISS / UNICEF / UN Panel of Experts on South Sudan / US TIP Report",
    },
]
