"""Americas migrant worker exploitation -- US, Canada, Mexico, Brazil, and Central America."""

AMERICAS_FACTS: list[dict] = [
    # ══════════════════════════════════════════════════════════════════════
    # MEXICO / CENTRAL AMERICA -- at least 30 facts
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "MX",
        "title": "Mexico General Law on Victims (Ley General de Victimas, 2013)",
        "summary": "Comprehensive victims' rights law establishing a national victim registry, a victims' compensation fund (CEAV), and legal assistance obligations. Covers trafficking victims explicitly. Entitles victims to shelter, medical care, legal representation, and reparations. Amended in 2017 to strengthen inter-institutional coordination. Implementation hampered by funding shortfalls and bureaucratic delays: only 30% of registered trafficking victims received compensation by 2023.",
        "source": "Diario Oficial de la Federacion / CEAV / US TIP Report",
    },
    {
        "type": "law",
        "jurisdiction": "MX",
        "title": "Mexico General Law to Prevent, Sanction and Eradicate Trafficking in Persons (2012, amended 2014)",
        "summary": "Mexico's primary anti-trafficking statute. Criminalizes all forms of trafficking with penalties of 5-30 years imprisonment. Establishes an Inter-Secretarial Commission to coordinate anti-trafficking efforts. Mandates state-level anti-trafficking laws (all 32 states compliant by 2015). Creates a national program for the prevention and punishment of trafficking. Penalties increase for public officials involved in trafficking. Requires annual trafficking reports from the executive.",
        "source": "Diario Oficial de la Federacion / UNODC / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Central American Transit Migration Exploitation in Mexico",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "An estimated 400,000-500,000 Central Americans transit Mexico annually heading to the US. Migrants face systematic exploitation: (1) Cartel-controlled territory charges 'transit taxes' (USD 200-500 per person); (2) Kidnapping for ransom -- CNDH documented 20,000+ kidnappings (2011); (3) Forced recruitment into cartel operations; (4) Sexual violence (80% of women/girls assaulted en route per MSF); (5) Forced labour in agriculture and domestic work in southern Mexico. Train route ('La Bestia') particularly dangerous.",
        "source": "CNDH Mexico / MSF / Sin Fronteras / UNHCR",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Cartel Exploitation of Migrants at US-Mexico Border",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "Mexican cartels (Sinaloa, CJNG, Gulf, Zetas) control migrant smuggling across the US-Mexico border. Exploitation includes: forced labour at cartel safe houses (cooking, cleaning, drug packaging), forced drug carrying (human mules), sexual exploitation of women and children, ransom demands (USD 3,000-10,000 from families), and murder of those who cannot pay. CBP encountered 2.4 million migrants at southern border (FY2023). Cartels earn estimated USD 13B annually from human smuggling.",
        "source": "US DOJ / CBP / CNDH Mexico / InSight Crime",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "corridor": "MX-US",
        "title": "US-Mexico Border Sex Trafficking -- Tenancingo-New York Pipeline",
        "exploitation_type": "debt_bondage",
        "sector": "sex_trafficking",
        "summary": "Tenancingo, Tlaxcala is considered a major origin point for sex trafficking to the United States. Trafficking networks recruit women and girls using the 'lover boy' method: men pursue romantic relationships, then coerce victims into sex trafficking in New York, Atlanta, Chicago, and Houston. Networks are family-based, multigenerational. US DOJ has prosecuted 70+ Tenancingo-linked cases. Mexico has prosecuted fewer than 20. Tlaxcala state anti-trafficking commission established (2014) but local complicity remains a challenge.",
        "source": "US DOJ / Polaris Project / Tlaxcala State Attorney General / NYT",
    },
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala Coffee and Palm Oil Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Guatemala's coffee and palm oil sectors depend on indigenous labour (primarily Q'eqchi', Mam, and K'iche' communities). Exploitation patterns: debt bondage through company stores (tienda de raya), below-minimum wages (GTQ 90/day legal minimum, workers receive GTQ 40-60), 10-12 hour workdays, child labour during harvest (children aged 8+), exposure to pesticides without PPE. Palm oil expansion in Peten and Izabal displaces indigenous communities and creates forced labour conditions. US DOL lists Guatemalan coffee and palm oil as products of child/forced labour.",
        "source": "US DOL ILAB / Verité / COVERCO Guatemala / Oxfam",
    },
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemalan Migration Exploitation -- Northern Triangle Dynamics",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Guatemala is both origin and transit country. An estimated 200,000+ Guatemalans emigrate annually (primarily to US). Exploitation: (1) Coyote fees: USD 5,000-15,000 (families take loans at 15-25% interest); (2) Transit exploitation in Mexico: kidnapping, forced labour, sexual violence; (3) Children travelling unaccompanied (50,000+ apprehended at US border in FY2023); (4) Returned deportees face re-trafficking. Guatemalan consulates in Mexico inadequately staffed to assist. Remittances: USD 19.3B (2023, 19% of GDP).",
        "source": "IOM / UNHCR / PDH Guatemala / World Bank",
    },
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras Gang-Related Trafficking and Forced Recruitment",
        "exploitation_type": "intimidation",
        "sector": "multiple",
        "summary": "Honduran gangs (MS-13, Barrio 18) drive trafficking through: forced recruitment of boys as young as 12 as lookouts, drug runners, and soldiers; forced sexual exploitation of girls in gang-controlled territories; extortion of businesses forcing owners to launder money or provide free goods. Gang control is primary push factor for migration. Honduras homicide rate (36 per 100,000 in 2022, down from 90+ in 2011) remains among world's highest. Internal displacement from gang territories: 247,000+ (IDMC 2023).",
        "source": "UNHCR / CONADEH Honduras / InSight Crime / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "SV",
        "title": "El Salvador Gang Trafficking and Mass Incarceration Impact",
        "exploitation_type": "intimidation",
        "sector": "multiple",
        "summary": "El Salvador's gang crisis (MS-13, Barrio 18) created widespread trafficking: forced recruitment, sexual exploitation, and extortion. President Bukele's state of emergency (2022-present) incarcerated 75,000+ suspected gang members in CECOT mega-prison. While reducing gang activity, mass incarceration created new vulnerabilities: families of incarcerated breadwinners destitute, children abandoned, and trafficking networks adapting. Internal trafficking of girls for sexual exploitation continues. El Salvador TIP rating improved to Tier 2 (2024) from Tier 2 Watch List.",
        "source": "UNHCR / Cristosal / US TIP Report / HRW",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Maquiladora Labour Conditions at Mexico-US Border",
        "exploitation_type": "excessive_overtime",
        "sector": "manufacturing",
        "summary": "3,000+ maquiladoras along Mexico-US border employ 1.3 million workers. Exploitation patterns: wages of MXN 300-500/day (USD 17-29, below living wage), mandatory overtime (60+ hours/week), exposure to chemicals without PPE, sexual harassment (documented in 40% of factories surveyed), suppression of independent unions, and dismissal of pregnant workers. Matamoros strike (2019): 30,000 workers won 20% raise. USMCA labour provisions (2020) have enabled some improvements but enforcement is slow.",
        "source": "CFO (Comite Fronterizo de Obreras) / AFL-CIO / USMCA Rapid Response Panel",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexican Agricultural Worker Internal Trafficking -- Jornaleros",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "An estimated 2-3 million jornaleros (agricultural day labourers) in Mexico, 30% indigenous. Exploitation: recruited by enganchadores (labour brokers) from Guerrero, Oaxaca, and Chiapas for farms in Sinaloa, Sonora, Baja California, and San Quintin. Debt bondage through transport and housing advances. Entire families including children (300,000+ child jornaleros) work in fields. Wages below minimum, no contracts, no social security. San Quintin farmworker strike (2015) exposed conditions on export berry farms. STPS inspections cover less than 5% of farms.",
        "source": "CONEVAL / STPS / Red de Jornaleros / The Guardian",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Forced Disappearances and Trafficking in Mexico -- Intersection",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "Mexico has 100,000+ disappeared persons (2006-2024). Intersection with trafficking: migrants kidnapped from buses and transit routes by cartels, forced into labour or sex trafficking, bodies found in mass graves. Tamaulipas (2010-2011): 72 migrants murdered at San Fernando, 193 bodies found in mass graves nearby. Iguala (2014): 43 Ayotzinapa students disappeared. CNDH and CNB investigations reveal trafficking as a motive in many disappearances. Impunity rate: 98% for homicide, even higher for trafficking.",
        "source": "CNB / CNDH / CMDPDH / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Child Sex Tourism in Mexico",
        "exploitation_type": "physical_sexual_violence",
        "sector": "sex_trafficking",
        "summary": "Mexico is a destination for child sex tourism, particularly in border cities (Tijuana, Ciudad Juarez), resort areas (Cancun, Acapulco, Puerto Vallarta), and transit hubs. ECPAT estimates 30,000+ children in commercial sexual exploitation in Mexico. US perpetrators cross into border towns. Mexican law criminalizes child sex tourism (15-30 years), but convictions are rare. National tourism campaigns ('Codigo de Conducta') encourage reporting. UNODC and ECPAT support prevention programs.",
        "source": "ECPAT / UNODC / US TIP Report / Save the Children Mexico",
    },
    {
        "type": "statistic",
        "jurisdiction": "MX",
        "title": "Mexico Anti-Trafficking Prosecutions",
        "metric": "Federal and state trafficking convictions annually",
        "value": "40-60 (federal) + 200-300 (state)",
        "year": 2023,
        "summary": "Mexico's FGR (federal) and state attorneys general together achieve 250-350 trafficking convictions annually (2022-2023). However, victim identification is low (2,000-3,000 annually vs. estimated 340,000+ victims per Global Slavery Index). 77% of convictions are for sex trafficking; labour trafficking prosecutions remain rare. Sentences average 12-15 years but early release is common. State-level capacity varies enormously: Mexico City, Tlaxcala, and Chihuahua lead; most states have fewer than 5 convictions annually.",
        "source": "FGR / SEGOB / US TIP Report / CdE",
    },
    {
        "type": "case_study",
        "jurisdiction": "NI",
        "title": "Nicaragua Political Crisis and Migration-Trafficking Nexus",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Political crisis since 2018 has driven 200,000+ Nicaraguans to flee, primarily to Costa Rica (150,000+) and the US. Migrants exploited in Costa Rica: agriculture (coffee, pineapple), domestic work, and construction at below-minimum wages. Transit exploitation through Honduras and Guatemala. Nicaraguan government does not cooperate with US TIP Report. Remittances: USD 4.3B (2023, 27% of GDP). Costa Rica granted temporary protected status to 80,000+ Nicaraguans.",
        "source": "IOM / UNHCR / IACHR / Costa Rica DGME",
    },
    {
        "type": "case_study",
        "jurisdiction": "CR",
        "title": "Costa Rica -- Agricultural Worker Exploitation (Coffee, Pineapple, Banana)",
        "exploitation_type": "withholding_wages",
        "sector": "agriculture",
        "summary": "Costa Rica employs 200,000+ migrant workers (primarily Nicaraguan, Panamanian indigenous) in agriculture. Exploitation: below-minimum wages (coffee: CRC 5,000-8,000/day vs. CRC 12,000 minimum), no social security enrollment, substandard housing on plantations, exposure to agrochemicals (pineapple sector uses bromacil, banned in EU), and child labour during harvest. Del Monte and Dole supply chains linked to violations. Oxfam and BSR reports have driven some improvements in banana sector.",
        "source": "ILO / ASEPROLA / Oxfam / US DOL ILAB",
    },
    {
        "type": "case_study",
        "jurisdiction": "PA",
        "title": "Panama Darien Gap Transit Exploitation",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "The Darien Gap (Colombia-Panama jungle) is a critical transit point for migrants from South America, Caribbean, and increasingly Africa and Asia heading to the US. 520,000+ crossed in 2023 (record). Exploitation: armed group extortion (USD 50-200 per person), sexual violence (60%+ of women report assault per MSF), robbery, and forced labour at transit camps. Children (113,000+ in 2023) particularly vulnerable. Panamanian government established reception stations but overwhelmed. Bodies found regularly on jungle trails.",
        "source": "IOM / UNHCR / MSF / SENAFRONT Panama",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Cuban and Venezuelan Migration Exploitation in Mexico",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Mexico hosts 500,000+ Venezuelan and 100,000+ Cuban migrants (2023), many transiting to US. Exploitation in Mexico: forced labour in informal economy (street vending, restaurants, car washes), sexual exploitation of Venezuelan women (documented in Tijuana, Tapachula, CDMX), and extortion by cartels and corrupt officials. COMAR (Mexico's refugee agency) received 140,000+ asylum applications (2023) but processing capacity is limited. Migrants exploited while awaiting resolution.",
        "source": "COMAR / UNHCR / Sin Fronteras / Doctors Without Borders",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Chiapas -- Exploitation of Guatemalan Cross-Border Agricultural Workers",
        "exploitation_type": "withholding_wages",
        "sector": "agriculture",
        "summary": "An estimated 200,000 Guatemalan seasonal workers cross into Chiapas annually for coffee, banana, and sugar cane harvest. Workers receive Tarjeta de Visitante Trabajador Fronterizo (TVTF) but exploitation persists: wages below Mexican minimum (MXN 207/day in 2024, workers receive MXN 120-150), no written contracts, no social security, employer-provided housing in substandard conditions, and child labour. Workers fear reporting due to potential TVTF revocation. STPS inspections in Chiapas agriculture are minimal.",
        "source": "ILO / CDH Fray Bartolome / INM Mexico / El Colegio de la Frontera Sur",
    },
    {
        "type": "advisory",
        "jurisdiction": "MX",
        "title": "Mexico TIP Report Tier Rating",
        "summary": "US TIP Report downgraded Mexico to Tier 2 Watch List (2024). Key concerns: complicity of government officials at all levels, insufficient victim identification (estimated 340,000+ victims vs. 2,000-3,000 identified), impunity for labour trafficking, inadequate services for male victims, and failure to address official complicity. Positive: increased federal prosecutions, USMCA labour complaints mechanism, and state-level anti-trafficking improvements in Mexico City and Jalisco.",
        "source": "US State Dept TIP Report 2024",
    },
    {
        "type": "case_study",
        "jurisdiction": "BZ",
        "title": "Belize -- Exploitation of Central American Migrant Workers",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "agriculture",
        "summary": "Belize employs thousands of Guatemalan, Honduran, and Salvadoran migrant workers in banana, citrus, and sugar cane sectors. Workers enter irregularly through porous border areas. Exploitation: below-minimum wages (BZD 3.30/hour, workers receive BZD 2-2.50), no work permits, employer-controlled housing, and threats of deportation. Shrimp farming sector also employs migrant workers under exploitative conditions. Belize's Trafficking in Persons Act (2013) has produced fewer than 10 convictions.",
        "source": "US TIP Report / IOM / National Trade Union Congress Belize",
    },
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala Internal Trafficking -- Indigenous Community Exploitation",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "domestic_work",
        "summary": "Internal trafficking in Guatemala disproportionately affects indigenous girls from rural highlands (Quiche, Huehuetenango, San Marcos, Totonicapan). Girls trafficked to Guatemala City, Quetzaltenango, and Antigua for domestic work. Recruited at ages 10-14, work 14-16 hours daily, paid GTQ 500-1,000/month (USD 65-130, well below minimum wage). Educational opportunities denied. Physical and sexual abuse documented. PDH (Procuraduria de Derechos Humanos) receives 500+ complaints annually but prosecutions are rare.",
        "source": "PDH Guatemala / UNICEF / US TIP Report / ECPAT Guatemala",
    },
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras Palm Oil and Melon Sector Labour Exploitation",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Honduras is Central America's largest palm oil producer. Plantations in Aguan Valley employ workers under exploitative conditions: temporary contracts to avoid benefits, below-minimum wages (HNL 230/day legal minimum, workers report HNL 150-180), mandatory 12-hour shifts during harvest, exposure to pesticides, and violent suppression of union organizing (100+ farm activists killed 2010-2023 in Aguan land disputes). Melon export sector in Choluteca employs women packers under similar conditions. Products enter US and EU supply chains.",
        "source": "COFADEH / Oxfam / US DOL ILAB / FIAN International",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico -- Trafficking of Indigenous Communities (Tarahumara, Mixtec, Triqui)",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "agriculture",
        "summary": "Indigenous communities are disproportionately trafficked within Mexico. Raramuri (Tarahumara) from Chihuahua forced into drug cultivation by cartels. Mixtec and Triqui from Oaxaca trafficked to agricultural export zones in Sinaloa, Baja California, and Sonora. Language barriers (60+ indigenous languages) prevent accessing justice. Indigenous women and girls face intersectional exploitation: gender, ethnicity, and poverty. INPI (National Institute of Indigenous Peoples) lacks capacity to address trafficking specifically.",
        "source": "CNDH / CDH Tlachinollan / UN Special Rapporteur on Indigenous Rights",
    },
    {
        "type": "case_study",
        "jurisdiction": "regional-central-america",
        "title": "Unaccompanied Migrant Children from Central America",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "130,000+ unaccompanied children (UACs) from Guatemala, Honduras, and El Salvador apprehended at US border (FY2022). Children exploited in transit: forced to carry drugs, sexual exploitation by smugglers, labour exploitation in Mexico. Push factors: gang recruitment, poverty, family reunification. In US: placed with ORR sponsors, some then exploited in US workforce. NYT investigation (2023) revealed widespread child labour exploitation of UACs in meatpacking, factories, and construction across the US.",
        "source": "ORR / UNHCR / NYT Investigation (2023) / KIND",
    },
    {
        "type": "case_study",
        "jurisdiction": "HT",
        "title": "Haiti Restavek Child Servitude System",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "domestic_work",
        "summary": "Restavek ('stay with') system places 225,000-300,000 Haitian children (predominantly girls, aged 6-14) from poor rural families with wealthier urban households as domestic servants. Children work 14+ hours daily: cooking, cleaning, washing, carrying water. Most receive no education, wages, or healthcare. Physical and sexual abuse prevalent. Legally prohibited under Haiti's Anti-Trafficking Law (2014) but culturally embedded and rarely prosecuted. Restavek Freedom Foundation and IOM provide rehabilitation. Practice persists due to extreme poverty (59% below poverty line).",
        "source": "Restavek Freedom / IOM / UNICEF / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "DO",
        "title": "Dominican Republic -- Haitian Sugar Plantation Exploitation (Bateyes)",
        "exploitation_type": "restriction_of_movement",
        "sector": "agriculture",
        "summary": "An estimated 500,000+ Haitians and Dominicans of Haitian descent live in bateyes (sugar plantation communities). Historical pattern: Haitian workers recruited or trafficked for sugar cane cutting under exploitative conditions. Workers paid by weight (USD 2-4/ton), work 12-hour days, live in company housing without running water or electricity. Despite diversification away from sugar, batey communities remain in extreme poverty. Constitutional Tribunal ruling (2013) stripped citizenship from 200,000+ Dominicans of Haitian descent, increasing vulnerability.",
        "source": "Amnesty International / HRW / IOM / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "DO",
        "title": "Dominican Republic -- Construction Sector Haitian Worker Exploitation",
        "exploitation_type": "withholding_wages",
        "sector": "construction",
        "summary": "An estimated 250,000 Haitian workers in Dominican construction sector (90% undocumented). Exploitation: wages 30-50% below Dominican workers for same work (DOP 500-800/day vs. DOP 1,200 minimum), no written contracts, no social security, employer threats of deportation. Mass deportation campaigns (2015, 2022-2023) increased vulnerability: 200,000+ Haitians deported annually. Workers who report exploitation face immediate deportation. ILO Better Work program does not cover construction sector.",
        "source": "IOM / Amnesty International / OBMICA / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico Domestic Worker Exploitation -- Informal Sector",
        "exploitation_type": "excessive_overtime",
        "sector": "domestic_work",
        "summary": "Mexico has 2.5 million domestic workers (96% women, 30% indigenous). Until 2019, domestic workers were excluded from mandatory social security enrollment. Exploitation: 14-16 hour workdays (live-in workers), wages of MXN 2,000-4,000/month (below minimum wage), no written contracts (90%+), physical and sexual abuse, and denial of rest days. ILO C189 ratified by Mexico in 2020. Supreme Court ruling (2018) and IMSS pilot program (2019) mandated social security. By 2023, only 60,000 domestic workers enrolled (2.4%).",
        "source": "CONLACTRAHO / ILO / IMSS / INEGI",
    },
    # ══════════════════════════════════════════════════════════════════════
    # BRAZIL (BR) -- at least 20 facts
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "BR",
        "title": "Brazil Lista Suja (Dirty List) -- Transparency Tool Against Slave Labour",
        "summary": "Brazil's 'Lista Suja' publicly names employers convicted of using slave labour (trabalho escravo). Established by MTE Portaria 540/2004. Employers remain listed for 2 years. Consequences: exclusion from government contracts, denial of public bank credit (major banks signed National Pact), reputational damage. List has included 2,500+ employers since inception. Temporarily suspended (2014-2017) after court challenge but reinstated. Considered a global best practice for supply chain transparency by ILO.",
        "source": "MTE Brazil / Reporter Brasil / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Grupo Especial de Fiscalizacao Movel (GEFM) -- Mobile Inspection Squads",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "Brazil's GEFM (Mobile Inspection Groups) are specialized units of MTE labour inspectors, federal police, and prosecutors that conduct surprise raids on workplaces suspected of slave labour. Operational since 1995. Squads travel to remote areas (Amazon, Cerrado, rural Northeast) for multi-day operations. By 2024, GEFM had rescued 63,000+ workers from conditions analogous to slavery. Operations cover: cattle ranches, sugar cane plantations, charcoal kilns, urban sweatshops, and coffee farms. Annual rescues: 1,500-3,000 workers.",
        "source": "MTE Brazil / Reporter Brasil / ILO / Anti-Slavery International",
    },
    {
        "type": "statistic",
        "jurisdiction": "BR",
        "title": "Brazil Workers Rescued from Slave Labour (1995-2024)",
        "metric": "Workers rescued from conditions analogous to slavery",
        "value": "63,000+",
        "year": 2024,
        "summary": "Since 1995, Brazil's labour inspection system (GEFM) has rescued 63,000+ workers from conditions analogous to slavery across all states. Peak: 2007 (5,999 rescued). Annual average (2020-2024): 2,000-2,500. Sectors: cattle (25%), sugar cane (15%), coffee (10%), construction (10%), charcoal (8%), urban garment (8%), other agriculture (24%). 60% of rescued workers are from Maranhao, Piaui, Bahia, and Para states. Recidivism rate: 30% of rescued workers found in exploitative conditions again within 5 years.",
        "source": "MTE / Reporter Brasil / Comissao Pastoral da Terra",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Coffee Sector Slave Labour -- Minas Gerais and Bahia",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Brazil is the world's largest coffee producer. GEFM rescues 200-400 workers annually from coffee farms. Pattern: workers recruited from northeastern Brazil (Maranhao, Bahia, Piaui) by gatos (labour brokers) with promises of BRL 100-150/day. Arrive to find: debt for transport and tools, piece-rate pay yielding BRL 30-50/day, substandard housing (tarpaulin shelters), no sanitation, and inability to leave due to debt and remote location. Major brands (Starbucks, Nestle, JDE Peet's) linked through supply chains. Certification systems (Rainforest Alliance, UTZ) have improved but not eliminated exploitation.",
        "source": "Reporter Brasil / MTE / Repórter Brasil / Danwatch",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Sugar Cane Cutting -- Exhaustion Deaths and Exploitation",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Brazil's sugar cane sector (ethanol and sugar production) employs 500,000+ workers during harvest. Exploitation: piece-rate system requires cutting 10-15 tons/day (up from 5 tons in 1980s due to mechanization-driven productivity pressure), 12-14 hour workdays, heat exhaustion deaths (21 documented deaths in Sao Paulo state, 2004-2007), debt bondage for transport from northeast. Mechanization has reduced workforce but remaining manual cutters face intensified exploitation. NR-31 safety regulations poorly enforced.",
        "source": "Pastoral da Terra / Repórter Brasil / ILO / UNESP Studies",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Cattle Ranching Slave Labour -- Amazon Deforestation Link",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Cattle ranching in the Amazon (Para, Mato Grosso, Rondonia, Tocantins) is the sector with most slave labour rescues in Brazil. Pattern: workers recruited from towns by gatos for 'forest clearing' (desmatamento) jobs. Debt bondage for transport, food, and tools. Workers clear forest with machetes and chainsaws in extreme conditions. Armed guards prevent departure. GEFM rescues 500-1,000 annually from cattle ranches. Environmental link: 80% of deforestation in Brazilian Amazon is for cattle. JBS, Marfrig, and Minerva supply chains implicated.",
        "source": "MTE / Greenpeace / Repórter Brasil / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Charcoal Production Slave Labour",
        "exploitation_type": "restriction_of_movement",
        "sector": "manufacturing",
        "summary": "Charcoal kilns in Minas Gerais, Maranhao, and Para employ workers under slavery conditions. Workers (often from indigenous communities and northeast Brazil) confined to remote kiln sites, exposed to extreme heat and toxic fumes, housed in makeshift shelters. Charcoal used in pig iron production for steel industry. GEFM rescues 100-200 workers annually from charcoal operations. Children documented working kilns. Supply chain links to global steel and automotive industries. Pig iron exported to US, EU, and China.",
        "source": "Reporter Brasil / MTE / Bloomberg / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Amazon Deforestation Forced Labour Camps",
        "exploitation_type": "restriction_of_movement",
        "sector": "agriculture",
        "summary": "Forced labour camps in the Amazon are linked to illegal deforestation, land grabbing, and cattle ranch expansion. Workers recruited with promises of BRL 2,000-3,000/month. Reality: debt bondage, BRL 500-800/month after deductions, armed guards, remote location (days from nearest town), confiscation of documents. IBAMA environmental officers and GEFM labour inspectors sometimes conduct joint operations. Workers rescued from camps face retaliation threats. 70% of rescued workers return to exploitative conditions within 2 years due to lack of alternative employment.",
        "source": "IBAMA / MTE / Comissao Pastoral da Terra / HRW",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Sao Paulo Textile Sweatshops -- Bolivian and Paraguayan Workers",
        "exploitation_type": "debt_bondage",
        "sector": "garment",
        "summary": "Sao Paulo's garment district (Bras, Bom Retiro) employs an estimated 20,000+ irregular migrant workers from Bolivia, Paraguay, Peru, and Haiti in sweatshops. Workers housed in windowless workshops, sewing 14-16 hours daily, paid per piece (BRL 0.50-2.00 per garment). Debt bondage for transit and housing. Families including children work together. GEFM rescues 300-500 workers annually from Sao Paulo garment workshops. Supply chains link to major Brazilian retailers (Renner, C&A, Zara). Brands fined BRL 2-10 million for supply chain violations.",
        "source": "Reporter Brasil / MTE / MPT (Ministerio Publico do Trabalho) / CPI da Moda",
    },
    {
        "type": "law",
        "jurisdiction": "BR",
        "title": "Brazil Constitutional Amendment 81 (PEC do Trabalho Escravo, 2014)",
        "summary": "Constitutional amendment allowing confiscation without compensation of rural and urban properties where slave labour is found. Properties confiscated for agrarian reform or social housing. Passed after 15 years of legislative debate. Implementing legislation still pending (as of 2024), limiting practical application. When implemented, this will be one of the world's strongest penalties for slave labour: property forfeiture without compensation.",
        "source": "Congresso Nacional / Comissao Pastoral da Terra / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazilian Wine Region Slave Labour -- Vineyards in Rio Grande do Sul",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "February 2023: GEFM rescued 207 workers from vineyards in Bento Goncalves, Rio Grande do Sul (Brazil's wine capital). Workers from Bahia, Minas Gerais, and Sergipe held in degrading conditions: sleeping on beds without mattresses, single toilet for 200+ workers, wages withheld for months. Vineyards supplied grapes to major Brazilian wineries (Aurora, Garibaldi, Salton). Operation generated national outrage and international media coverage. Companies placed on Lista Suja. Largest rescue operation in southern Brazil's history.",
        "source": "MTE / MPT / Reuters / The Guardian / Reporter Brasil",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Haitian Migrant Worker Exploitation in Brazil",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "construction",
        "summary": "100,000+ Haitians migrated to Brazil (2010-2020), initially after the 2010 earthquake and through humanitarian visa program. Workers concentrated in meatpacking (Santa Catarina, Parana), construction (Sao Paulo), and services. Exploitation: below-minimum wages (BRL 1,000-1,400/month vs. BRL 1,412 minimum in 2024), dangerous work conditions, racial discrimination, and employer abuse of immigration status. Many Haitians subsequently migrated onward to Chile, Mexico, and US due to Brazil's economic recession and exploitation.",
        "source": "IOM / UNHCR / Centro Scalabriniano / IBGE",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Construction Sector Slave Labour -- Mega-Projects",
        "exploitation_type": "debt_bondage",
        "sector": "construction",
        "summary": "Brazil's mega-projects (hydroelectric dams, World Cup stadiums, Olympic venues) employed thousands of migrant workers under exploitative conditions. Belo Monte Dam (Para, 2011-2019): 30,000+ workers, reports of degrading living conditions, excessive overtime, and restriction of movement. World Cup stadium construction: 8 worker deaths, labour violations documented at multiple venues. GEFM rescues 200-400 construction workers annually. Pattern: subcontracting chains obscure responsibility.",
        "source": "MTE / MPT / Reporter Brasil / Building and Wood Workers International",
    },
    {
        "type": "statistic",
        "jurisdiction": "BR",
        "title": "Brazil Lista Suja Employer Count",
        "metric": "Employers listed on Dirty List (current)",
        "value": "200-300 (active at any time)",
        "year": 2024,
        "summary": "Brazil's Lista Suja maintains 200-300 employers at any given time (2-year listing period). Cumulative: 2,500+ employers listed since 2004. Sectors represented: agriculture (50%), construction (15%), garment (10%), charcoal (8%), other (17%). Financial impact: listed employers lose access to BRL billions in public credit (BNDES, Banco do Brasil). Major employer challenges to the list have largely failed in courts. Transparency measure has been replicated in modified form by other countries.",
        "source": "MTE / Reporter Brasil / InPACTO",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Venezuelan Refugee Exploitation in Northern Brazil",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "350,000+ Venezuelan refugees and migrants in Brazil (2024), concentrated in Roraima (Boa Vista, Pacaraima) and spreading to Manaus, Sao Paulo, and Brasilia. Exploitation: street vending and begging, domestic work at below-minimum wages, sexual exploitation, and informal sector labour without contracts. 'Operacao Acolhida' (federal response since 2018) relocated 100,000+ to other states but integration challenges persist. Women particularly vulnerable to sexual exploitation. GEFM found Venezuelan workers in slave-like conditions on farms in Para and Roraima.",
        "source": "UNHCR / IOM / Reporter Brasil / ACNUR Brazil",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Domestic Worker Exploitation -- Legacy of Slavery",
        "exploitation_type": "excessive_overtime",
        "sector": "domestic_work",
        "summary": "Brazil has 5.7 million domestic workers (92% women, 65% Black/parda), the world's largest domestic workforce. Constitutional Amendment 72/2013 (PEC das Domesticas) extended full labour rights to domestic workers: 44-hour week, overtime pay, FGTS, and formal contracts. Implementation: by 2023, only 28% of domestic workers had formal contracts. Live-in workers (800,000+) report: 14-16 hour workdays, food restrictions, and sleeping in servant quarters. Intersection with racial inequality reflects legacies of slavery (abolished 1888).",
        "source": "IBGE / ILO / FENATRAD / OIT Brasilia",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Soybean and Cotton Plantation Labour Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Brazil's soybean sector (world's largest exporter) and cotton production in Mato Grosso, Goias, and MATOPIBA region employ seasonal workers under exploitative conditions. GEFM rescues 100-200 workers annually from soy and cotton farms. Pattern: workers from Maranhao and Piaui recruited for clearing, planting, and spraying. Debt bondage for transport. Exposure to heavy pesticide use (Brazil is world's largest pesticide consumer). Supply chains link to Cargill, Bunge, ADM, and Louis Dreyfus.",
        "source": "Reporter Brasil / MTE / Mighty Earth / Amnesty International",
    },
    {
        "type": "advisory",
        "jurisdiction": "BR",
        "title": "Brazil TIP Report Tier Rating",
        "summary": "US TIP Report rates Brazil as Tier 2 (2024). Strengths: robust legal framework, mobile inspection squads (GEFM), Lista Suja transparency tool, high rescue numbers. Concerns: limited convictions (50-80 annually vs. 2,000+ rescues), insufficient victim services post-rescue, 70% re-exploitation rate, pending implementing legislation for Constitutional Amendment 81, and budget cuts to GEFM (20% reduction 2019-2023).",
        "source": "US State Dept TIP Report 2024",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Fishing Sector Exploitation -- Amazon and Northeast",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "Artisanal and industrial fishing in Amazon rivers and northeastern coast employs workers under exploitative conditions. Pattern: workers recruited from riverine communities for fishing boats operating in remote areas. Debt bondage for equipment. Confinement to boats for weeks. Piece-rate pay below minimum wage. Children work alongside adults on family and commercial boats. GEFM has limited capacity to inspect waterborne operations. ILO C188 (Work in Fishing Convention) not ratified by Brazil.",
        "source": "MTE / CPT / ILO / Repórter Brasil",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Tobacco Sector Child and Forced Labour -- Rio Grande do Sul and Santa Catarina",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Brazil is the world's second-largest tobacco exporter. Family farming model in southern Brazil (90% of production) uses child labour: children aged 8+ harvest leaves, exposed to green tobacco sickness (nicotine absorption through skin). 30,000+ children in tobacco according to IBGE. Adult workers also exploited: piece-rate system, 12-hour days during harvest, and nicotine poisoning. Supply chains link to BAT, Philip Morris, and JTI through Brazilian leaf dealers (Universal, Alliance One). ECLT Foundation programs show limited impact.",
        "source": "US DOL ILAB / Reporter Brasil / Sindifumo / ECLT",
    },
    # ══════════════════════════════════════════════════════════════════════
    # CANADA (CA) -- at least 20 facts
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "CA",
        "title": "Canada Immigration and Refugee Protection Act (IRPA) -- Trafficking Provisions",
        "summary": "IRPA Section 118 criminalizes trafficking in persons with penalties up to life imprisonment and CAD 1 million fine. Applies to: organizing entry of persons by force, coercion, deception, or use of threat for exploitation. Section 117 criminalizes organizing illegal entry for profit. Trafficking victims may receive Temporary Resident Permits (TRPs) for up to 180 days (renewable). Between 2006-2023, approximately 900 TRPs issued to trafficking victims. RCMP-led Human Trafficking National Coordination Centre (HTNCC) operational since 2005.",
        "source": "IRPA / RCMP / Public Safety Canada / US TIP Report",
    },
    {
        "type": "law",
        "jurisdiction": "CA",
        "title": "Canada Criminal Code Trafficking Offenses (Sections 279.01-279.04)",
        "summary": "Criminal Code Sections 279.01-279.04 criminalize trafficking in persons (including for labour exploitation), receiving material benefit from trafficking, withholding/destroying documents, and trafficking of persons under 18. Maximum penalty: life imprisonment (adult trafficking), mandatory minimum 5 years (child trafficking). Prosecutions: 200+ charges laid (2005-2023), resulting in 100+ convictions. Most convictions involve sexual exploitation; labour trafficking convictions remain extremely rare (fewer than 10 total as of 2024).",
        "source": "Criminal Code / DOJ Canada / Public Safety Canada",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Temporary Foreign Worker Program (TFWP) Exploitation in Canada",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Canada's TFWP employs 800,000+ workers annually. Closed work permits tie workers to a single employer, creating dependency. Exploitation documented: wage theft (30% report being paid less than promised), substandard employer-provided housing, excessive hours, and threats of deportation for complaints. Low-wage stream workers particularly vulnerable: agriculture, food processing, hospitality, and caregiving. IRCC issued 1,200+ employer-specific work permit revocations (2022-2023). Migrant Workers Alliance for Change documents 10,000+ complaints annually.",
        "source": "IRCC / Migrant Workers Alliance for Change / Auditor General of Canada / UFCW",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Seasonal Agricultural Worker Program (SAWP) Exploitation -- Canada",
        "exploitation_type": "withholding_wages",
        "sector": "agriculture",
        "summary": "Canada's SAWP brings 60,000+ workers annually from Mexico and Caribbean countries (Jamaica, Trinidad, Barbados, OECS) for farm work. Issues: employer-tied permits, employer-controlled housing (often crowded bunkhouses), mandatory deductions for housing/transport reducing take-home pay, limited access to healthcare despite paying into provincial health plans, and inability to change employers. Workers who report violations face non-recall (blacklisting) the following season. Fatalities: farm workers die at 4x rate of other workers. COVID-19 outbreaks on farms (2020-2021) killed 3+ SAWP workers.",
        "source": "UFCW / Justicia for Migrant Workers / Auditor General / CBC",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Live-In Caregiver Program Exploitation -- Canada",
        "exploitation_type": "excessive_overtime",
        "sector": "domestic_work",
        "summary": "Canada's Live-In Caregiver Program (LCP, replaced by new pathways in 2014/2019) brought 30,000+ workers (primarily Filipino women) annually. Exploitation: mandatory live-in requirement created dependency, 80-hour workweeks documented (paid for 40), monitoring of personal life, sexual harassment, and delayed permanent residency processing (3-5 years average, some waited 10+). Post-2014 reforms removed live-in requirement but new 'Home Child Care Provider' and 'Home Support Worker' pathways still tie workers to employer.",
        "source": "Migrante Canada / Philippine Women Centre BC / IRCC / UFCW",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "CA",
        "title": "Canada Open Work Permit for Vulnerable Workers (2019)",
        "summary": "IRCC introduced the Open Work Permit for Vulnerable Workers (OWPVW) in June 2019, allowing TFWP workers experiencing or at risk of abuse to leave their employer and work for any employer. Eligibility requires evidence of abuse (physical, sexual, financial, psychological) or risk thereof. Processing: 5-day target. Issued 4,500+ OWPVWs (2019-2023). Criticisms: workers unaware of program, narrow definition of 'abuse,' requirement to provide evidence while still in abusive situation, and limited to employer-specific permit holders only.",
        "source": "IRCC / Migrant Workers Alliance for Change / Canadian Labour Congress",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "British Columbia TFWP Exploitation -- Construction and Hospitality",
        "exploitation_type": "withholding_wages",
        "sector": "construction",
        "summary": "British Columbia is a primary destination for temporary foreign workers in construction, hospitality, and food services. Documented cases: construction workers from Philippines and Latin America paid CAD 12-15/hour (below minimum wage of CAD 16.75), housed in overcrowded employer-controlled accommodations, and charged excessive rent deductions. RCMP investigated 12+ employer fraud cases in BC (2020-2023). BC Employment Standards Branch received 800+ TFWP-related complaints (2022). Whistler, Kelowna, and Vancouver Island particularly affected.",
        "source": "BC Employment Standards / RCMP / MWAC / Vancouver Sun",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Ontario Agricultural Worker Deaths and Exploitation",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Ontario employs 25,000+ SAWP workers annually in greenhouse, nursery, and field crop production. Documented: 20+ farm worker deaths (2019-2023) from workplace accidents, heat stroke, and COVID-19. Leamington-Kingsville greenhouse corridor: workers housed 10-15 per trailer, exposed to pesticides without training, 12-hour shifts 6 days/week. Ontario Occupational Health and Safety Act excludes farm workers from many protections. Migrant Workers Alliance: 80% of workers surveyed fear retaliation for reporting.",
        "source": "Ontario Ministry of Labour / MWAC / Justicia for Migrant Workers / Toronto Star",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Alberta Temporary Foreign Worker Exploitation -- Meatpacking and Oil Sands",
        "exploitation_type": "debt_bondage",
        "sector": "food_processing",
        "summary": "Alberta's meatpacking plants (Cargill High River, JBS Brooks) and oil sands employ thousands of TFWs. Exploitation: recruitment fees paid to agents in Philippines, India, and Guatemala (CAD 5,000-15,000, despite Canadian prohibition on worker-paid fees), employer-tied permits preventing exit, below-promised wages, and unsafe conditions. Cargill High River COVID-19 outbreak (2020): 950+ workers infected, 3 deaths, highlighting TFW vulnerability. Alberta Employment Standards investigations increased but penalties remain low.",
        "source": "UFCW / Alberta Employment Standards / CBC / Globe and Mail",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Provincial Nominee Program (PNP) Exploitation -- Immigration Fraud",
        "exploitation_type": "deception",
        "sector": "multiple",
        "summary": "Provincial Nominee Programs allowing provinces to nominate immigrants have been exploited by fraudulent employers and consultants. Pattern: workers pay CAD 20,000-50,000 to immigration consultants for PNP nomination tied to specific employer. Employer provides letter but job is fictitious or at much lower wage than promised. Workers trapped: leaving employer means losing nomination and investment. IRCC and CBSA investigated 200+ PNP fraud cases (2020-2023). Manitoba, Saskatchewan, and Atlantic provinces most affected.",
        "source": "IRCC / CBSA / CBC Marketplace / Canadian Anti-Fraud Centre",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Canada Seafood Processing Worker Exploitation -- Atlantic Provinces",
        "exploitation_type": "withholding_wages",
        "sector": "food_processing",
        "summary": "Seafood processing plants in New Brunswick, Nova Scotia, PEI, and Newfoundland employ 5,000+ TFWs from Mexico, Philippines, and Thailand. Exploitation: seasonal work means 4-6 months employment followed by unemployment (no EI eligibility for TFWs until 2022 reform), substandard employer housing, excessive deductions, and isolation in rural communities. Thai workers in PEI lobster processing reported paying THB 300,000 (CAD 12,000) to recruiters. RCMP Human Trafficking unit investigated 5+ cases in Atlantic Canada (2021-2023).",
        "source": "RCMP / NB Employment Standards / UFCW / The Narwhal",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Trucking Industry TFWP Exploitation -- Canada",
        "exploitation_type": "debt_bondage",
        "sector": "transport",
        "summary": "Long-haul trucking industry in Canada recruited 15,000+ TFWs (predominantly Indian workers) via TFWP and LMIA process. Exploitation: workers pay CAD 20,000-40,000 to immigration consultants and recruiters for LMIA-backed work permits. Arrive to find: lower pay than promised, deductions for truck lease, forced to work as 'owner-operators' without benefits, 16-hour driving days exceeding Hours of Service regulations. Major accident in Humboldt, SK (2018) highlighted training and safety concerns. IRCC tightened trucking LMIAs in 2023.",
        "source": "IRCC / TeamstersCan / Globe and Mail / Driving Canada",
    },
    {
        "type": "statistic",
        "jurisdiction": "CA",
        "title": "Canada Temporary Foreign Worker Population",
        "metric": "Active temporary foreign worker permit holders",
        "value": "800,000+ (2023)",
        "year": 2023,
        "summary": "Canada had 800,000+ active TFWP permit holders in 2023, up from 300,000 in 2015. Includes: SAWP (60,000+), low-wage stream (200,000+), high-wage stream (150,000+), and International Mobility Program (400,000+). Top source countries: India, Philippines, Mexico, Jamaica, Guatemala. TFWP grew 35% in 2022-2023 alone. Growing reliance on temporary migration raises systemic exploitation concerns. Auditor General (2024) found IRCC conducts compliance inspections on only 5-10% of employers annually.",
        "source": "IRCC / Statistics Canada / Auditor General 2024",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "International Student Worker Exploitation in Canada",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "services",
        "summary": "Canada's 800,000+ international students (2023) are increasingly exploited in the labour market. Students allowed to work 20 hours/week (temporarily unlimited 2022-2024) face: below-minimum wages in cash economy, employer threats to report visa violations, exploitation by private college recruiters (CAD 20,000-50,000 tuition for low-quality programs), and housing exploitation (8-10 students per unit). Indian students constitute 40% of international students and are disproportionately affected. Immigration minister acknowledged 'broken system' in 2024.",
        "source": "IRCC / Statistics Canada / Migrant Students United / Globe and Mail",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Canada Nail Salon and Restaurant Worker Exploitation",
        "exploitation_type": "withholding_wages",
        "sector": "services",
        "summary": "Vietnamese, Chinese, and Korean workers exploited in Canadian nail salons, restaurants, and massage parlours. Pattern: workers arrive on visitor visas or refugee claims, work without permits for cash below minimum wage. Employers withhold pay, threaten deportation, control housing. Toronto Star investigation (2019) documented Vietnamese nail salon workers earning CAD 3-5/hour for 60-hour weeks. RCMP identified 30+ trafficking cases in restaurant and personal services sector (2019-2023). Convictions remain rare due to victim reluctance to testify.",
        "source": "RCMP / Toronto Star / Canadian Centre to End Human Trafficking",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Guatemala-Canada SAWP Corridor Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Guatemala joined Canada's SAWP in 2003. 10,000+ Guatemalan workers arrive annually for farm work in Quebec, Ontario, and BC. Recruitment through Guatemala's Ministry of Labour. Workers pay GTQ 5,000-15,000 (CAD 900-2,700) for documents and travel. Exploitation: inability to change employers, substandard housing, language barriers (indigenous language speakers face double barrier), and non-recall for workers who complain. Quebec greenhouse sector particularly dependent on Guatemalan workers. FERME (Foundation des Entreprises en Recrutement de Main-d'oeuvre agricole Etrangere) manages Quebec component.",
        "source": "IOM / UFCW / CISO Quebec / La Presse",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Filipino Workers in Canadian Meatpacking -- COVID-19 Exploitation",
        "exploitation_type": "excessive_overtime",
        "sector": "food_processing",
        "summary": "Filipino workers constitute 30-40% of the workforce in Canadian meatpacking plants. During COVID-19, these workers were disproportionately affected: Cargill High River (AB): 950+ infections among 2,000 workers, 3 deaths, 70% Filipino workforce. Workers reported being pressured to work while symptomatic, inadequate PPE, and crowded break rooms. Olymel Red Deer: 500+ infections. Workers feared reporting due to employer-tied work permits. Filipino Migrant Workers Association documented 100+ complaints. Class action lawsuits filed against Cargill and Olymel.",
        "source": "UFCW / Migrante Alberta / Alberta OHS / CBC",
    },
    {
        "type": "advisory",
        "jurisdiction": "CA",
        "title": "Canada TIP Report Tier Rating",
        "summary": "US TIP Report rates Canada as Tier 1 (2024). Recognized strengths: robust legal framework, RCMP National Human Trafficking Strategy (2019), CAD 75M federal investment, TRP program for victims. Concerns raised: employer-tied work permits create systemic vulnerability, labour trafficking convictions remain near-zero, SAWP workers lack effective complaint mechanisms, and Indigenous women and girls disproportionately affected by domestic sex trafficking.",
        "source": "US State Dept TIP Report 2024",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Canada Recruitment Fee Prohibition -- Enforcement Gap",
        "exploitation_type": "debt_bondage",
        "sector": "multiple",
        "summary": "Canadian federal and provincial laws prohibit employers and recruiters from charging recruitment fees to temporary foreign workers. Manitoba (2008), BC (2018), Ontario (2009), and Saskatchewan (2013) have recruiter licensing laws. Despite prohibition, 50-60% of surveyed TFWs report paying fees (Migrant Workers Alliance, 2023). Fees paid in source countries (Philippines, India, Guatemala, Jamaica) are difficult to enforce against. Federal government announced Recognized Employer Pilot (2023) but does not address overseas fee collection. Total fees paid by TFWs to Canada estimated at CAD 500M+ annually.",
        "source": "IRCC / MWAC / Provincial Employment Standards / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "CA",
        "title": "Canada Indigenous Women and Girls -- Trafficking Vulnerability",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "sex_trafficking",
        "summary": "Indigenous women and girls in Canada are disproportionately victims of sex trafficking. National Inquiry into MMIWG (2019) documented trafficking as a form of genocide. Indigenous women: 4% of female population but 50%+ of sex trafficking victims. Factors: intergenerational trauma from residential schools, poverty, child welfare system (52% of children in care are Indigenous), and over-policing combined with under-protection. Manitoba and Saskatchewan have highest rates. Federal response: CAD 724M for MMIWG National Action Plan (2021) but implementation criticized as slow.",
        "source": "MMIWG National Inquiry / Public Safety Canada / Native Women's Association / Canadian Centre to End Human Trafficking",
    },
    # ══════════════════════════════════════════════════════════════════════
    # OTHER AMERICAS -- at least 20 facts
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "case_study",
        "jurisdiction": "AR",
        "title": "Argentina Textile Workshop Exploitation -- Buenos Aires Sweatshops",
        "exploitation_type": "debt_bondage",
        "sector": "garment",
        "summary": "Buenos Aires garment workshops employ an estimated 30,000+ irregular Bolivian, Paraguayan, and Peruvian migrants under exploitation. Workers housed in windowless workshops, sewing 14-18 hours daily, paid ARS 50,000-100,000/month (USD 50-100 at parallel rate). Debt bondage for transit from Bolivia. Passport retention by workshop owners. 2006 Caballito workshop fire killed 6 (including 4 children). Government rescued 2,500+ workers (2015-2023) but workshops reopen after raids. Supply chains link to major Argentine brands (Kosiuko, Awada, Cheeky).",
        "source": "La Alameda Foundation / MTE Argentina / UNODC / Pagina 12",
    },
    {
        "type": "case_study",
        "jurisdiction": "PE",
        "title": "Peru Illegal Gold Mining Exploitation -- Madre de Dios",
        "exploitation_type": "restriction_of_movement",
        "sector": "mining",
        "summary": "Peru's Madre de Dios region has 30,000+ informal gold miners, many exploited under forced labour conditions. Pattern: workers recruited from Andean highlands (Puno, Cusco, Arequipa) with promises of income. Arrive to find: debt bondage for equipment and food, armed camp operators who restrict departure, mercury exposure without PPE, and sexual exploitation of women and girls in mining camp bars. Children (aged 10+) work as mercury processors. Government 'Operacion Mercurio' (2019) disrupted some operations but miners relocated deeper into jungle.",
        "source": "US TIP Report / Verité / MINAM Peru / Carnegie Amazon Mercury Project",
    },
    {
        "type": "case_study",
        "jurisdiction": "PE",
        "title": "Peru Domestic Worker Exploitation -- Internal Trafficking of Indigenous Girls",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "domestic_work",
        "summary": "Internal trafficking of indigenous girls from Andean and Amazonian communities to Lima, Arequipa, and Trujillo for domestic work. Girls aged 10-15 placed with urban families by parents or brokers seeking educational opportunities. Reality: 14-16 hour workdays, no education access, physical abuse, minimal or no pay (PEN 200-500/month vs. PEN 1,025 minimum). 'Madrinazgo' (godmother) system culturally embeds practice. Peru's Law 28950 criminalizes trafficking but only 20-30 convictions annually.",
        "source": "CHS Alternativo / ILO / UNICEF / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "CO",
        "title": "Colombia Internal Displacement and Trafficking Nexus",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Colombia has 6.8 million internally displaced persons (second-largest IDP population globally after Sudan). Displacement creates trafficking vulnerability: Afro-Colombian and indigenous women/girls trafficked for sexual exploitation in Bogota, Medellin, and Cartagena. Boys recruited by armed groups (FARC dissidents, ELN, AGC). Venezuelan refugees (2.9 million in Colombia) face exploitation in agriculture, domestic work, street vending, and sex trafficking. Colombia's Law 985 (2005) criminalizes trafficking but enforcement is weak in conflict-affected areas.",
        "source": "UARIV Colombia / IOM / UNHCR / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "CO",
        "title": "Venezuelan Migrant Worker Exploitation in Colombia",
        "exploitation_type": "withholding_wages",
        "sector": "multiple",
        "summary": "2.9 million Venezuelan refugees and migrants in Colombia (2024). 70% in informal economy earning below minimum wage (COP 1,300,000/month in 2024, Venezuelans average COP 600,000-800,000). Exploitation sectors: agriculture (palm oil, coffee), domestic work, construction, street vending, and sex work. Temporary Protection Statute (ETPV, 2021) regularized 1.6 million but work rights implementation is slow. Women face disproportionate sexual exploitation: 45% of identified sex trafficking victims in Colombia are Venezuelan.",
        "source": "DANE Colombia / IOM / UNHCR / Migración Colombia",
    },
    {
        "type": "case_study",
        "jurisdiction": "CL",
        "title": "Chile Agricultural Worker Exploitation -- Haitian and Bolivian Workers",
        "exploitation_type": "withholding_wages",
        "sector": "agriculture",
        "summary": "Chile's agriculture sector (fruit export: grapes, berries, avocados) employs migrant workers from Haiti (180,000+ in Chile), Bolivia, Peru, and increasingly Venezuela. Exploitation: below-minimum wages (CLP 410,000 minimum, workers receive CLP 250,000-300,000), pesticide exposure, 12-hour days during harvest, substandard employer housing, and racial discrimination (especially against Haitian workers). Chile's Ley 20.507 (2011) criminalizes trafficking but labour trafficking prosecution is nearly nonexistent. DT (Dirección del Trabajo) inspections cover less than 3% of farms annually.",
        "source": "DT Chile / IOM / Fundación Libera / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "HT",
        "title": "Haiti-Dominican Republic Trafficking Corridor",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "500,000-1 million Haitians in the Dominican Republic, most undocumented. Cross-border trafficking: children trafficked for domestic work and begging in DR border towns (Dajabón, Jimaní). Adults exploited in construction, agriculture (rice, banana), and domestic work. Women and girls in sex trafficking in tourist areas (Boca Chica, Sosúa). DR mass deportations (200,000+/year since 2015) increase vulnerability by disrupting communities and separating families. Bilateral anti-trafficking cooperation is minimal.",
        "source": "IOM / UNHCR / OBMICA / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "VE",
        "title": "Venezuela Crisis-Driven Trafficking and Exploitation",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Venezuela's economic/political crisis has displaced 7.7 million people (2024). Refugees and migrants exploited across the Americas: Colombia (sex trafficking, informal labour), Peru (domestic work, mining), Ecuador (agriculture, sex trafficking), Brazil (street vending, agriculture), Trinidad and Tobago (fishing, sex trafficking), and Chile (agriculture, services). Venezuelan women and girls particularly vulnerable to sex trafficking. IOM estimates 40% of Venezuelan migrants experience some form of exploitation in transit or destination.",
        "source": "R4V Platform / IOM / UNHCR / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "EC",
        "title": "Ecuador -- Banana and Flower Sector Labour Exploitation",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Ecuador is the world's largest banana exporter and a major flower producer. Exploitation: banana workers earn USD 350-450/month (below USD 450 sectoral minimum), 12-hour days, aerial pesticide spraying over workers. Flower farms in highland provinces (Cotopaxi, Pichincha) employ women (65% of workforce) under conditions of: 10-12 hour shifts during Valentine's/Mother's Day peak, pesticide exposure, sexual harassment, and temporary contracts avoiding benefits. Colombian and Venezuelan migrants increasingly exploited. HRW report (2002) drove some improvements but violations persist.",
        "source": "HRW / US DOL ILAB / ILO / BananaLink",
    },
    {
        "type": "case_study",
        "jurisdiction": "BO",
        "title": "Bolivia Sugar Cane and Brazil Nut Sector Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Bolivia's sugar cane harvest in Santa Cruz department employs 30,000+ Guarani indigenous workers and highland migrants under debt bondage. Pattern: advances from contractors (habilito system) create debt repaid through below-minimum wages. Brazil nut collection in Pando and Beni departments involves 20,000+ workers in remote Amazon areas, including children. Workers confined to collection sites for months. ILO-Bolivia programs reduced worst practices but debt bondage persists in 20-30% of sugar operations.",
        "source": "ILO / Defensor del Pueblo / CEDLA Bolivia / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "PY",
        "title": "Paraguay Criadazgo Child Domestic Servitude",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "domestic_work",
        "summary": "Criadazgo is a practice in Paraguay where rural children (predominantly girls) are placed with urban families as domestic servants in exchange for education and shelter. Estimated 46,000 children in criadazgo (ILO/UNICEF). Children work 12-16 hours daily: cooking, cleaning, childcare. Education rarely provided. Physical and sexual abuse documented. Paraguay's Law 1657 (2001) on the Protection of Children and Adolescents prohibits criadazgo but enforcement is negligible. Cultural normalization makes prosecution difficult.",
        "source": "ILO / UNICEF / Global March Against Child Labour / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "TT",
        "title": "Trinidad and Tobago -- Venezuelan Migrant Exploitation",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "An estimated 40,000+ Venezuelans in Trinidad and Tobago, most without legal status. Exploitation: domestic work at below-minimum wages (TTD 17.50/hour, Venezuelans receive TTD 8-12), construction, fishing (forced labour on pirogues), and sex trafficking. Venezuelan women trafficked to nightclubs and bars. Government registration exercise (2019) regularized 16,000 but expired. Workers without status cannot access labour courts. Murders and exploitation of Venezuelans reported by UNHCR. Anti-trafficking law (2011) but fewer than 5 trafficking convictions.",
        "source": "UNHCR / IOM / Living Water Community / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US H-2A Agricultural Guest Worker Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "US H-2A program employed 370,000+ foreign agricultural workers (FY2023, up from 79,000 in FY2013). Workers primarily from Mexico (95%), Guatemala, Honduras, South Africa, and Jamaica. Exploitation: recruitment fees (USD 1,000-5,000 despite prohibition), employer-tied visa, substandard housing, wage theft, pesticide exposure, and retaliation for complaints. Workers who leave employer lose legal status. DOL WHD investigations find violations in 70%+ of H-2A employers inspected. Farmworker Justice and Centro de los Derechos del Migrante document systemic abuses.",
        "source": "DOL WHD / Farmworker Justice / CDM / Economic Policy Institute",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US Child Labour Crisis -- Migrant Children in Meatpacking and Manufacturing",
        "exploitation_type": "excessive_overtime",
        "sector": "food_processing",
        "summary": "NYT investigation (February 2023) revealed widespread exploitation of migrant children in US workplaces. DOL found: 5,800+ child labour violations (FY2023, up 300% from 2015). Cases: Packers Sanitation Services (PSSI) employed 100+ children (aged 13-17) in overnight meatpacking plant cleaning in 8 states (fined USD 1.5M). Hyundai supplier in Alabama employed children. Hearthside Food Solutions employed children in packaging. Children were UACs placed with ORR sponsors who arranged employment. Bipartisan outrage led to increased enforcement.",
        "source": "NYT Investigation / DOL WHD / DOL OIG / Reuters",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US H-2B Visa Worker Exploitation -- Hospitality and Landscaping",
        "exploitation_type": "withholding_wages",
        "sector": "hospitality",
        "summary": "US H-2B program provides 66,000-130,000 temporary non-agricultural workers annually (cap increased from 66,000). Sectors: landscaping, hospitality (hotels, resorts), seafood processing, forestry, and carnival workers. Exploitation: recruitment fees (USD 2,000-10,000), wage theft (30% report being paid less than promised), employer-controlled housing (deductions reduce pay below minimum wage), and inability to change employers. Workers from Mexico, Jamaica, Philippines, and Central America. DOL WHD investigations find H-2B violations in 50%+ of audited employers.",
        "source": "DOL WHD / SPLC / Centro de los Derechos del Migrante / National Guestworker Alliance",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US Domestic Worker Exploitation -- National Domestic Workers Alliance Findings",
        "exploitation_type": "withholding_wages",
        "sector": "domestic_work",
        "summary": "2.5 million domestic workers in the US (nannies, housecleaners, home care aides), 90% women, 52% immigrants. NDWA survey: 23% paid below minimum wage, 70% paid no overtime, 65% have no written contract, 35% experienced verbal abuse. Undocumented workers face worst conditions: employer threats of deportation, 60-80 hour weeks, wages of USD 2-5/hour. Domestic worker exclusion from FLSA (partial) and NLRA reflects historical racism (originally excluded to deny protections to Black workers). Domestic Workers Bill of Rights enacted in 11 states and 3 cities.",
        "source": "NDWA / EPI / ILO / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US Trafficking Victims Protection Act (TVPA) -- Framework",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "TVPA (2000, reauthorized 2003, 2005, 2008, 2013, 2019) is the foundational US anti-trafficking law. Criminalizes forced labour (18 USC 1589), trafficking (18 USC 1590), and sex trafficking (18 USC 1591). Establishes T-visa for trafficking victims (5,000 cap/year, 2,500 issued annually). DOJ Human Trafficking Prosecution Unit: 600+ defendants convicted (2000-2024). Mandates annual TIP Report on all countries. Creates Interagency Task Force to Monitor and Combat Trafficking. TVPA model has influenced 150+ countries' anti-trafficking legislation.",
        "source": "US DOJ / DOJ HTPU / Office to Monitor and Combat Trafficking / Polaris Project",
    },
    {
        "type": "case_study",
        "jurisdiction": "GY",
        "title": "Guyana Mining Sector Trafficking and Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "mining",
        "summary": "Guyana's interior gold mining operations exploit workers under forced labour conditions. Workers from coastal Guyana, Brazil, and Venezuela recruited for gold mining in Potaro-Siparuni, Upper Demerara, and Cuyuni-Mazaruni regions. Debt bondage for transport and supplies. Workers confined to remote jungle camps, paid in gold below market rate, and unable to leave. Women and girls trafficked to mining camps for sexual exploitation. Mining camp 'shops' extend credit creating further debt. Government mining inspectors rarely reach interior operations.",
        "source": "US TIP Report / Guyana Human Rights Association / IOM / Stabroek News",
    },
    {
        "type": "case_study",
        "jurisdiction": "SR",
        "title": "Suriname Gold Mining and Brazilian Garimpeiro Exploitation",
        "exploitation_type": "restriction_of_movement",
        "sector": "mining",
        "summary": "Suriname's interior gold mining employs an estimated 15,000-20,000 Brazilian garimpeiros (miners) and Maroon/indigenous workers. Exploitation: workers recruited in northern Brazil (Para, Maranhao), smuggled across border, confined to mining camps in Sipaliwini and Brokopondo districts. Debt bondage for transport and equipment. Mercury exposure without PPE. Women and girls trafficked to mining camps for sexual exploitation. Suriname's anti-trafficking law (2006) has produced fewer than 5 convictions. Mining operations controlled by armed groups with ties to Brazilian organized crime.",
        "source": "US TIP Report / WWF / UNDP / Mongabay",
    },
    {
        "type": "case_study",
        "jurisdiction": "JM",
        "title": "Jamaica SAWP Workers in Canada -- Exploitation and Non-Recall",
        "exploitation_type": "withholding_wages",
        "sector": "agriculture",
        "summary": "Jamaica sends 10,000+ workers annually to Canada under SAWP (since 1966, oldest such program). Workers employed in Ontario greenhouse and nursery sectors. Exploitation: employer-controlled housing (deducted from wages), inability to change employers, 12-hour shifts, and 'non-recall' as punishment (workers not invited back next season for complaining). Jamaican liaison service mediates but primarily represents government/employer interests. Workers report 30-50% effective wage reduction after deductions. Justicia for Migrant Workers has documented 500+ complaints from Jamaican SAWP workers.",
        "source": "Justicia for Migrant Workers / UFCW / Jamaica Gleaner / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "CU",
        "title": "Cuba State-Sponsored Labour Export -- Medical and Technical Missions",
        "exploitation_type": "state_imposed",
        "sector": "healthcare",
        "summary": "Cuba deploys 50,000+ healthcare and technical workers to 60+ countries under bilateral agreements. Cuban government retains 75-90% of workers' salaries. Workers face: passport confiscation, restriction of movement, monitoring by Cuban security, threats against family members for non-compliance. Defection results in 8-year ban on returning to Cuba. Brazil's 'Mais Medicos' program (2013-2018) employed 11,000+ Cuban doctors (Cuba received USD 3,600/month per doctor, doctors received USD 900-1,200). Some legal scholars and US TIP Report categorize this as state-sponsored forced labour.",
        "source": "US TIP Report / Prisoners Defenders / Cuban Medical Professional Parole / NYT",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US Restaurant and Food Service Worker Trafficking",
        "exploitation_type": "debt_bondage",
        "sector": "hospitality",
        "summary": "DOJ has prosecuted dozens of restaurant trafficking cases. Patterns: workers from Mexico, Philippines, Thailand, and India recruited for restaurant work with H-2B or J-1 visas. Arrive to find: lower wages than promised, excessive hours (70-80/week), tips confiscated by management, employer-controlled housing with wage deductions, and threats of deportation. Notable case: Bimbo's restaurant (Connecticut, 2012) -- Indonesian workers paid USD 1.78/hour. Polaris Project identifies restaurant/food service as a top 5 labour trafficking industry in the US.",
        "source": "DOJ / Polaris Project / National Human Trafficking Hotline / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US Nail Salon Worker Exploitation -- Vietnamese and Korean Workers",
        "exploitation_type": "withholding_wages",
        "sector": "services",
        "summary": "NYT investigation (2015) revealed systemic exploitation in New York nail salons: Vietnamese and Korean workers paid USD 30-40/day (some nothing during 'training'), exposed to toxic chemicals without PPE, and fined for mistakes. Estimated 100,000 nail salon workers in New York alone. New York State enacted the Nail Salon Minimum Standards Council Act (2015) mandating wage bonds and ventilation requirements. DOL investigations found wage violations in 70%+ of nail salons inspected nationally. Workers face language barriers and immigration status fears.",
        "source": "NYT Investigation / NYS DOL / DOL WHD / AALDEF",
    },
    {
        "type": "case_study",
        "jurisdiction": "PE",
        "title": "Peru Brick Kiln Forced Labour -- Andean Highlands",
        "exploitation_type": "debt_bondage",
        "sector": "manufacturing",
        "summary": "Artisanal brick kilns (ladrilleras) in Cusco, Puno, Huancavelica, and Ayacucho employ indigenous families under debt bondage. Pattern: families receive advance payments (PEN 500-2,000) that create perpetual debt due to below-subsistence piece rates. 14-hour workdays including children aged 6+. Silica dust exposure causes chronic lung disease. An estimated 30,000 families in brick kiln labour. ILO and Solidaridad programs have improved conditions in some areas but practice remains widespread in rural Andes.",
        "source": "ILO / CHS Alternativo / US DOL ILAB / Solidaridad",
    },
    {
        "type": "case_study",
        "jurisdiction": "AR",
        "title": "Argentina Rural Agricultural Worker Exploitation -- Fruit and Vegetable Harvest",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Argentina's fruit and vegetable sector (Mendoza wine grapes, Alto Valle apples and pears, Tucuman citrus, NEA yerba mate) employs 500,000+ seasonal workers, many Bolivian and Paraguayan migrants. Exploitation: piece-rate pay below minimum (ARS 2,000-3,000/day vs. ARS 5,000 minimum), unregistered employment (40%+ of agricultural workers), no safety equipment, pesticide exposure, and child labour (50,000+ children in agriculture). RENATEA (national rural worker registry) has registered only 60% of agricultural workers. Labour inspections in remote areas are rare.",
        "source": "RENATEA / UATRE / US TIP Report / COPRETI Argentina",
    },
    {
        "type": "law",
        "jurisdiction": "US",
        "title": "US Fair Food Program -- Tomato Worker Protection Model",
        "summary": "The Fair Food Program (FFP), created by the Coalition of Imigmokalee Workers (CIW) in 2011, is a worker-driven social responsibility model in Florida tomato farming. Major buyers (Walmart, McDonald's, Whole Foods) pay a premium (1 cent/pound), which goes directly to workers. FFP includes: zero tolerance for forced labour, sexual violence, and child labour; worker education on rights; third-party auditing; and a 24-hour complaint line. 35,000+ workers covered. Has eliminated forced labour from participating farms. Expanded to strawberries, peppers, and dairy. Recognized by UN and White House as a best practice.",
        "source": "CIW / UN OHCHR / White House / Harvard Business Review",
    },
    {
        "type": "case_study",
        "jurisdiction": "CO",
        "title": "Colombia Gold Mining Exploitation -- Armed Group Controlled Mines",
        "exploitation_type": "restriction_of_movement",
        "sector": "mining",
        "summary": "Colombia's artisanal and small-scale gold mining (ASGM) employs 300,000+ workers, many in mines controlled by FARC dissidents, ELN, and criminal organizations (Clan del Golfo). Exploitation: workers in Choco, Antioquia, Bolivar, and Nariño departments confined to mining camps by armed groups, paid in kind or below-market rates, exposed to mercury. Women and girls trafficked to mining areas for sexual exploitation. Child labour (estimated 15,000+ children in mining). Gold enters formal supply chain through intermediaries, reaching European and US refineries.",
        "source": "Defensoría del Pueblo / Global Witness / OECD / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Palm Oil Plantation Exploitation -- Para State",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Palm oil expansion in Para state (Amazon region) has created forced labour conditions. Workers recruited from Maranhao for land clearing and palm harvesting. GEFM rescued 100+ workers from palm plantations (2014-2023). Pattern: debt for transport and accommodation, below-minimum wages, degrading housing, and restriction of movement on remote plantations. Companies including Biopalma (Vale subsidiary) and Agropalma linked to violations. EU Deforestation Regulation (2023) creates additional due diligence obligations for palm oil imported from Brazil.",
        "source": "Reporter Brasil / MTE / Amnesty International / Mongabay",
    },
    {
        "type": "statistic",
        "jurisdiction": "regional-americas",
        "title": "Americas Modern Slavery Prevalence",
        "metric": "Modern slavery victims in the Americas",
        "value": "5.1 million",
        "year": 2022,
        "summary": "ILO Global Estimates (2022): 5.1 million people in modern slavery in the Americas, including 3.6 million in forced labour and 1.5 million in forced marriage. Prevalence rate: 5.2 per 1,000 people. Latin America and Caribbean: 2.6 million in forced labour. North America: 1.0 million in forced labour (US and Canada). Forced labour in private economy dominates. Sectors: agriculture, domestic work, construction, manufacturing, and sex trafficking. Migration vulnerability is a key driver across the region.",
        "source": "ILO / Walk Free / IOM Global Estimates 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexican Fishing Sector Exploitation -- Sinaloa and Baja California",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "Mexico's Pacific coast fishing fleet employs migrant and indigenous workers under exploitative conditions. Workers recruited from Guerrero, Oaxaca, and Chiapas for shrimp trawling and tuna fishing based in Mazatlan, Guaymas, and Ensenada. Exploitation: debt bondage for equipment, confinement to vessels for weeks, piece-rate pay yielding below minimum wage, and dangerous working conditions (drowning is leading cause of death). ILO C188 not ratified by Mexico. STPS labour inspections do not cover fishing vessels. Children aged 14+ documented on boats.",
        "source": "EJF / ILO / STPS / Oceana Mexico",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US Garment Worker Exploitation -- Los Angeles Fashion District",
        "exploitation_type": "withholding_wages",
        "sector": "garment",
        "summary": "Los Angeles garment district employs 45,000+ workers (predominantly Latina immigrants) producing fast fashion. DOL investigations find: 85% of LA garment factories violate wage laws, workers paid USD 4-6/hour (piece rate), 10-12 hour shifts, no overtime, and unsafe conditions. Brands (Fashion Nova, Ross, TJ Maxx) sourcing from violating factories face no legal liability under traditional contracting. California Garment Worker Protection Act (SB62, 2021) created brand accountability for wage theft. First-of-its-kind in the US.",
        "source": "DOL WHD / Garment Worker Center / UCLA Labor Center / NYT",
    },
]
