"""Child soldiers, children in armed groups, and child recruitment by armed forces.

Covers ICC prosecutions, UN listings, DDR programs, Paris Principles, and real cases
from DRC, Uganda, Myanmar, Somalia, South Sudan, Nigeria, Syria, Yemen, Colombia,
Sierra Leone, Liberia, CAR, Mali, Chad, Afghanistan, Iraq, Philippines, and more.
"""

CHILD_SOLDIERS_ARMED_GROUPS_FACTS: list[dict] = [
    # ── DRC Child Soldiers ────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "CD",
        "title": "Thomas Lubanga — LRA Child Recruitment",
        "summary": "ICC convicted Thomas Lubanga (LRA commander) of enlisting and conscripting children (2001-2003). Over 30,000 children estimated conscripted by LRA in DRC. Lubanga sentenced to 14 years (2012), first ICC conviction for war crime of recruiting child soldiers.",
        "source": "ICC Office of the Prosecutor / Judgment Lubanga v. The Prosecutor",
    },
    {
        "type": "case_study",
        "jurisdiction": "CD",
        "title": "Bosco Ntaganda — M23 Child Recruitment",
        "summary": "ICC convicted Bosco Ntaganda (M23 military commander) of enlisting and conscripting children and sexual violence against child soldiers. 2,000+ children estimated recruited by M23. Ntaganda sentenced to 30 years (2019). Documented: forced marriage of girls, sexual slavery of child soldiers.",
        "source": "ICC / Ntaganda v. The Prosecutor / HRW",
    },
    {
        "type": "case_study",
        "jurisdiction": "CD",
        "title": "Jean-Pierre Bemba — DRC Armed Group Child Recruitment",
        "summary": "Jean-Pierre Bemba's MLC recruited thousands of children in DRC (1998-2004). ICC tried Bemba for war crimes and crimes against humanity. Convicted of enlisting children; sentenced to 18 years. Appeal overturned conviction 2018 on technical grounds, but child recruitment documented by UNICEF.",
        "source": "ICC / UNICEF DRC reports",
    },
    {
        "type": "case_study",
        "jurisdiction": "CD",
        "title": "Dominic Ongwen — LRA Child Soldiers and Sexual Enslavement",
        "summary": "ICC convicted Dominic Ongwen (LRA commander) of enlisting children, forced marriage of girls, and sexual slavery. Ongwen himself was abducted as child by LRA. 2,000+ girls forced into 'wives' positions; 2,000+ child soldiers. Sentenced to 25 years (2021).",
        "source": "ICC / UNICEF",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "CD",
        "title": "ICC Rome Statute Article 8 — War Crime of Child Recruitment",
        "summary": "Article 8(2)(b)(xxvi) and 8(2)(e)(vii) criminalize recruitment and conscription of children under 15 into armed forces or armed groups, and participation in hostilities. Basis for ICC prosecutions of Lubanga, Ntaganda, Ongwen, and others.",
        "source": "ICC Rome Statute",
    },
    {
        "type": "statistic",
        "jurisdiction": "CD",
        "title": "DRC Child Soldiers — UNICEF Estimate",
        "summary": "Estimated 30,000+ children served as combatants in DRC armed groups during 1998-2008 conflict. Many abducted and forced; others recruited through poverty/coercion. DDR programs have disarmed ~10,000 children, but many remain in armed groups.",
        "source": "UNICEF / DRC Ministry of Defense",
    },
    {
        "type": "law",
        "jurisdiction": "CD",
        "title": "DRC Armed Forces Recruitment Age Prohibition",
        "summary": "DRC military law sets recruitment age at 18 minimum. Despite prohibition, instances of under-18 recruitment documented in DRC armed forces by Human Rights Watch (2017). Investigation: recruitment officers paid bounties for child recruits.",
        "source": "DRC Military Code / HRW",
    },
    {
        "type": "advisory",
        "jurisdiction": "CD",
        "title": "UN Security Council Monitoring FARDC Child Recruitment",
        "summary": "UNSC Resolution 2098 (2013) established monitoring of FARDC (DRC national army) child recruitment. Annual reports document continued recruitment of children (under 18). 2023 report: 71 children documented recruited into FARDC.",
        "source": "UNSC DRC Group of Experts",
    },
    # ── Uganda LRA Child Soldiers ────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "UG",
        "title": "Joseph Kony — LRA Founder and Child Abduction",
        "summary": "Joseph Kony founded LRA (1987) and conducted 20-year insurgency in Uganda abducting 66,000+ children (estimated). 30,000+ confirmed child abductions. Kony's 'Invisible Children' army was predominantly child combatants. ICC indicted Kony 2005; remains at large. Complex arrest warrant signed 2023 by ICC.",
        "source": "ICC / UNICEF / Invisible Children documentary",
    },
    {
        "type": "case_study",
        "jurisdiction": "UG",
        "title": "Okot Odhiambo — LRA Child Recruitment and Atrocities",
        "summary": "Okot Odhiambo was LRA deputy commander responsible for child abductions and training. ICC indicted for enlisting children and mass killings involving child soldiers. Died in custody (2015) before trial completion. LRA's abduction methods: night raids on villages, separating children from parents.",
        "source": "ICC / HRW Uganda",
    },
    {
        "type": "case_study",
        "jurisdiction": "UG",
        "title": "Raska Lukwiya — LRA Commander and Child Soldiers",
        "summary": "Raska Lukwiya was LRA operational commander recruiting children for frontline combat. ICC indicted him; he died in fighting (2007) before trial. Documented: children under Lukwiya's command executed 100+ villagers including children. Pattern: desensitization through forced participation in atrocities.",
        "source": "ICC / UN Mission in Uganda",
    },
    {
        "type": "statistic",
        "jurisdiction": "UG",
        "title": "Uganda LRA Child Soldiers — Documented Cases",
        "summary": "Estimated 66,000 children abducted by LRA (1987-2006). Girls (50%) used as 'wives' and domestic slaves. Boys trained as combatants. 10,000+ confirmed killed. DDR programs rehabilitated ~15,000; many remain traumatized and reintegration incomplete.",
        "source": "UNICEF / Invisible Children / GUSEC",
    },
    {
        "type": "law",
        "jurisdiction": "UG",
        "title": "Uganda Prevention of Terrorism Act — Child Recruitment Provisions",
        "summary": "Uganda's Prevention of Terrorism Act (2002) criminalizes recruitment of children for terrorist organizations. Targets organizations like LRA. However, enforcement limited. Historical amnesty (2000-2008) allowed LRA combatants (including some recruiters) to escape prosecution.",
        "source": "Uganda Legal Authority / ITJWG",
    },
    {
        "type": "advisory",
        "jurisdiction": "UG",
        "title": "ICC Arrest Warrant for Joseph Kony",
        "summary": "ICC issued arrest warrant for Joseph Kony (October 2005) for war crimes including recruitment and use of child soldiers, sexual enslavement of girls, forced displacement. Warrant unsealed March 2006. Despite 'Kony 2012' campaign, arrest never executed. Kony disappeared into CAR/South Sudan.",
        "source": "ICC",
    },
    {
        "type": "case_study",
        "jurisdiction": "UG",
        "title": "LRA in Northern Uganda — Night Commuters",
        "summary": "LRA's abduction threat caused 30,000+ children to flee villages nightly to sleep in towns/churches for protection. 'Night commuters' traveled 10+ km daily. Documented sexual violence during commutes. Phenomenon documented (2004-2006) by journalists, NGOs, UNICEF.",
        "source": "Invisible Children / UNICEF",
    },
    # ── Myanmar Child Soldiers ──────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "MM",
        "title": "Myanmar Tatmadaw Child Recruitment",
        "summary": "UN documented 70,000+ child soldiers in Myanmar (primarily Tatmadaw, ethnic armed groups). Tatmadaw recruiting boys as young as 10; official minimum age 18 but systematically violated. Recruiters paid bonuses for child recruits. Ethnic armed groups (KIA, KNLA, TNLA, EAO) also recruit.",
        "source": "UN Office on Drugs and Crime / UNSC Monitoring",
    },
    {
        "type": "law",
        "jurisdiction": "MM",
        "title": "Myanmar Child Soldiers Prevention Act (Global)",
        "summary": "Myanmar not party to Optional Protocol on Child Soldiers (CRC-OP-AC). Myanmar's military law permits 16-year-olds in armed forces (de facto practice much younger). ILO Worst Forms of Child Labour Convention ratified but child military recruitment not adequately criminalized.",
        "source": "ILO / UNODC",
    },
    {
        "type": "advisory",
        "jurisdiction": "MM",
        "title": "UN Secretary-General Listing — Myanmar Armed Forces",
        "summary": "Myanmar's Tatmadaw included on UN Secretary-General's list of parties recruiting/using child soldiers (annual reports 2002-present). Ethnic armed groups (KIA, KNLA, TNLA, EAO) also listed. UN calls for action plans to end practice; implementation minimal.",
        "source": "UN Secretary-General reports on Children and Armed Conflict",
    },
    {
        "type": "case_study",
        "jurisdiction": "MM",
        "title": "Tatmadaw Child Recruitment Hotspots — Shan State",
        "summary": "Shan State, Myanmar: Tatmadaw recruitment stations in towns offer incentives (money, uniforms) to families in poverty. Children recruited forcibly through military conscription or inducement. Human Rights Watch documented: 13-year-old recruits in Tatmadaw training camps (2018-2020).",
        "source": "HRW Myanmar / Amnesty International",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "MM",
        "title": "Myanmar 2015 Military Discipline Law — Insufficient Reform",
        "summary": "Myanmar revised Military Discipline Law (2015) to nominally strengthen child protection in armed forces. However: enforcement weak, child recruitment continues, punishment of recruiters rare. Law permits 'voluntary' enlistment at age 16 with parental consent.",
        "source": "Myanmar Military Law",
    },
    {
        "type": "case_study",
        "jurisdiction": "MM",
        "title": "Ethnic Armed Organizations — KIA Child Soldiers",
        "summary": "Kachin Independence Army (KIA) and other ethnic armed groups recruit children. Pattern: recruitment in displacement camps, recruitment from refugee populations. Some children voluntarily join to protect families. UN estimates: 10,000+ children in EAO forces.",
        "source": "UNICEF / UNSC Myanmar Monitoring",
    },
    # ── Somalia Al-Shabaab Child Recruitment ──────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "SO",
        "title": "Al-Shabaab Child Recruitment — Suicide Bombers",
        "summary": "Al-Shabaab recruits children (some as young as 8-10) for combat and suicide missions. Documented: videos showing child bombers; 200+ child suicide attacks recorded (2011-2023). Recruitment in IDP camps, Mogadishu underserved areas. Indoctrination and coercion primary methods.",
        "source": "UN / UNICEF / New America Foundation",
    },
    {
        "type": "statistic",
        "jurisdiction": "SO",
        "title": "Somalia Child Soldiers — UN Verified Cases",
        "summary": "UN verified 4,000+ child soldiers in Somalia (primarily Al-Shabaab, TFG forces, informal militias). Actual estimate: 10,000+. Recruitment accelerated post-2017 in northern Somalia. Girls (30-40% of child soldiers) often sexually enslaved; boys combatants.",
        "source": "UN Office for Coordination of Humanitarian Affairs",
    },
    {
        "type": "advisory",
        "jurisdiction": "SO",
        "title": "UN Al-Shabaab Sanctions — Child Recruitment Designation",
        "summary": "UNSC designated Al-Shabaab as terrorist organization (2007). Child recruitment documented in sanctions reports (annual). Designation allows travel bans, asset freezes on recruitment operatives, but enforcement limited in Somalia's weak state.",
        "source": "UNSC Al-Shabaab Sanctions Committee",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SO",
        "title": "Somalia Armed Forces Recruitment Standards",
        "summary": "Somalia Federal Government claims 18-year-old minimum recruitment age but verification mechanisms absent. UNSOM reports: Somali National Army recruiting children 15-17. Recruitment officers not disciplined; no compensation for child recruits.",
        "source": "UNSOM / UNICEF",
    },
    {
        "type": "case_study",
        "jurisdiction": "SO",
        "title": "Al-Shabaab Girls in Captivity — Forced Marriage and Slavery",
        "summary": "Al-Shabaab captures and recruits girls as young as 12 for forced marriages to fighters, domestic slavery, and sexual violence. Girls undergo 'Islamicization' training. Some escape; others trapped. Documented cases: girls married off within days of capture.",
        "source": "Human Rights Watch / Save the Children",
    },
    # ── South Sudan Child Soldiers ──────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "SS",
        "title": "South Sudan Child Soldiers — Conflict",
        "summary": "Estimated 20,000 child soldiers active in South Sudan civil war (2013-2018, ongoing). SPLA, SPLA-IO, and militia groups recruiting. Boys combatants; girls sexual slaves. 2M+ displaced; 400,000+ estimated child soldiers recruited over conflict duration.",
        "source": "UNICEF / Watchlist on Children and Armed Conflict",
    },
    {
        "type": "case_study",
        "jurisdiction": "SS",
        "title": "SPLA and SPLA-IO Child Recruitment",
        "summary": "South Sudan People's Liberation Army (SPLA, government) and SPLA-IO (opposition) both recruiting children openly and forcibly. DDR programs reached 4,000+ children but 15,000+ remain in armed groups. Recruitment tactics: forced conscription at roadblocks, recruitment in displaced persons camps.",
        "source": "Amnesty International / UN Office for Coordination of Humanitarian Affairs",
    },
    {
        "type": "advisory",
        "jurisdiction": "SS",
        "title": "UN South Sudan Child Soldiers Monitoring",
        "summary": "UN Mission in South Sudan (UNMISS) documented 1,000+ new child recruitments annually (2015-2023). Violations concentrated: recruitment, sexual violence, killing of children. No justice mechanism; perpetrators unpunished. Impunity continues.",
        "source": "UNMISS reports",
    },
    {
        "type": "law",
        "jurisdiction": "SS",
        "title": "South Sudan Penal Code Child Recruitment Provision",
        "summary": "South Sudan Criminal Code Act (2008) criminalizes recruitment of children into armed forces. Minimum age set at 18. However: enforcement absent, recruiters not prosecuted, no compensation for survivors.",
        "source": "South Sudan Legal Authority",
    },
    {
        "type": "case_study",
        "jurisdiction": "SS",
        "title": "Nuer Youth League Militia — Child Recruitment",
        "summary": "Informal militia groups in South Sudan (Nuer Youth League, Dinka militias) recruit children aged 14-17. Pattern: recruitment through coercion and inducement. Documentarians (Human Rights Watch): militia leaders claim conscription necessary for community defense.",
        "source": "HRW / Watchlist on Children",
    },
    # ── Nigeria Boko Haram Child Recruitment ────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "title": "Chibok Girls Abduction — Boko Haram (2014)",
        "summary": "Boko Haram abducted 276 schoolgirls (ages 14-19) from Chibok Secondary School (April 2014). 100+ forced into marriage; 50+ remained missing for years. Documented: forced conversions, sexual slavery, childbirth in captivity. 57 girls escaped/rescued; others recovered later through interventions.",
        "source": "Amnesty International / CNN investigation",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "title": "Dapchi Girls Abduction — Boko Haram (2018)",
        "summary": "Boko Haram abducted 110+ schoolgirls from Dapchi Secondary School (February 2018). Forced conversions, forced marriages to fighters, sexual slavery. 104 girls released within weeks (government negotiation); 5 refused to leave (radicalized/pregnant).",
        "source": "Amnesty International / Human Rights Watch",
    },
    {
        "type": "statistic",
        "jurisdiction": "NG",
        "title": "Nigeria Boko Haram Child Recruitment and Abduction",
        "summary": "Estimated 10,000+ children recruited or abducted by Boko Haram (2009-2023). Boys (30%) trained as combatants, suicide bombers; girls (70%) forced marriages, sexual slavery, domestic labor. Suicide attacks by child bombers: 100+ documented.",
        "source": "UNICEF / UN / Amnesty International",
    },
    {
        "type": "advisory",
        "jurisdiction": "NG",
        "title": "Boko Haram Suicide Bomber Children — Exploitation",
        "summary": "Boko Haram systematically uses children (ages 7-17) as suicide bombers. Girls and boys equipped with explosive vests; sent into markets, schools, mosques. 100+ child suicide attacks documented (2011-2023). Girls sometimes unaware of explosive payload (deception).",
        "source": "CFR / Council on Foreign Relations / UN",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "title": "Boko Haram Sharia Court Sentences — Child Fighters",
        "summary": "Boko Haram established 'Sharia courts' in occupied territories. Documented: child soldiers sentenced to corporal punishment, execution for attempted desertion. Cases: 12-year-old sentenced to lashing for questioning commander.",
        "source": "Human Rights Watch / Amnesty International",
    },
    {
        "type": "law",
        "jurisdiction": "NG",
        "title": "Nigeria Child's Rights Act 2003",
        "summary": "Nigeria's Child's Rights Act criminalizes recruitment of children under 18 into armed groups. Article 27 sets 18-year minimum age. However: enforcement weak in conflict zones, Boko Haram operates outside law.",
        "source": "Nigeria Legal Authority",
    },
    {
        "type": "case_study",
        "jurisdiction": "NG",
        "title": "Katsina Abductions — Suspected Bandit Groups (2021-2023)",
        "summary": "Mass abductions of schoolchildren in Nigeria's northwest (Katsina, Kaduna, Kebbi) by criminal groups/militants (2021-2023). 2,000+ students abducted. Groups recruiting children for banditry, forced labor. Some girls forced into marriages.",
        "source": "Amnesty International / CNN",
    },
    # ── Syria Child Soldiers ────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "SY",
        "title": "Syria Child Soldiers — All Parties",
        "summary": "Estimated 8,000-9,000 child soldiers in Syria across all parties (2011-2023): government forces, opposition groups, ISIS, Kurdish forces. Recruitment through coercion, inducement, forced conscription. Girls: sexual violence, forced marriages.",
        "source": "UN Office on Drugs and Crime / Watchlist on Children",
    },
    {
        "type": "case_study",
        "jurisdiction": "SY",
        "title": "Syrian Army Child Recruitment — Government Forces",
        "summary": "Syrian government military recruiting children 15-17 for armed forces. UNHR documented: 5,000+ children recruited into army/air force (2011-2020). Recruitment targeted disadvantaged youth, refugees, IDPs. Training in combat, torture, extrajudicial killing.",
        "source": "UN Human Rights Council reports",
    },
    {
        "type": "case_study",
        "jurisdiction": "SY",
        "title": "ISIS Child Soldiers — Cubs of the Caliphate",
        "summary": "ISIS recruited 5,000+ children through propaganda and force. Program called 'Cubs of the Caliphate' (Ashbal al-Khilafah). Children trained in: combat, executions, suicide bombing. Documented: videos showing child soldiers executing prisoners. Sexual slavery of girls.",
        "source": "SITE Intelligence Group / BBC Monitoring",
    },
    {
        "type": "advisory",
        "jurisdiction": "SY",
        "title": "Syrian Opposition Groups and Child Recruitment",
        "summary": "Various Syrian opposition groups (FSA, Al-Nusra, others) documented recruiting children 13-17. Methods: inducement (payments, food), forced conscription, coercion. Extent smaller than government/ISIS but well-documented by Human Rights Watch.",
        "source": "Human Rights Watch",
    },
    {
        "type": "case_study",
        "jurisdiction": "SY",
        "title": "Kurdish YPG/SDF Child Soldiers",
        "summary": "Kurdish YPG and Syrian Democratic Forces documented recruiting children 12-17 by Watchlist on Children and UN investigators. Recruitment through peer pressure, family pressure, coercion. Children stationed in frontline positions against ISIS.",
        "source": "Watchlist on Children / UN",
    },
    {
        "type": "law",
        "jurisdiction": "SY",
        "title": "Syria Penal Code Child Military Recruitment",
        "summary": "Syria's military law sets 18-year minimum recruitment age. However: child recruitment systematic and unpunished. No courts functional to prosecute recruiters. Government denies reports; systematic accountability absent.",
        "source": "Syria Legal Authority / UN",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SY",
        "title": "Syrian Refugee Children in Neighboring States",
        "summary": "1.5M+ Syrian refugee children in Turkey, Lebanon, Jordan, Iraq. Documented: refugee child recruitment by armed groups, forced child labor, trafficking. UNHCR reports: recruitment accelerated post-2018 in camps.",
        "source": "UNHCR / Save the Children",
    },
    # ── Yemen Houthi Child Recruitment ──────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "YE",
        "title": "Yemen Child Soldiers — Houthis and Other Parties",
        "summary": "Estimated 3,000-4,000 child soldiers in Yemen conflict (2014-2023). Houthis, government forces, UAE-backed militias, AQAP all recruiting. Boys: combatants, suicide bombers. Girls: sexual slavery, forced marriages.",
        "source": "UN / UNICEF Yemen",
    },
    {
        "type": "case_study",
        "jurisdiction": "YE",
        "title": "Houthi Movement Child Recruitment",
        "summary": "Houthis documented recruiting children 10-17 through schools, coercion, inducement. Children trained in combat, indoctrination in Houthi ideology. Recruitment accelerated post-2015 air campaign. UN documents: 2,000+ Houthi child soldiers (2016-2023).",
        "source": "UN / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "YE",
        "title": "Yemen Government Forces and Affiliated Militias",
        "summary": "Yemen government forces and Saudi-backed militias recruiting children for frontline combat. Documented: 1,000+ children in government forces (2016-2023). Recruitment in displaced persons camps, urban slums. Methods: inducement, coercion, forced conscription.",
        "source": "Human Rights Watch / Amnesty International",
    },
    {
        "type": "advisory",
        "jurisdiction": "YE",
        "title": "UN Yemen Child Soldiers Monitoring",
        "summary": "UN documented recruitment of 3,000+ children annually in Yemen (2016-2023). Houthis leading recruiter (40-50%), followed by government forces (30-40%), militias (20%). Few accountability mechanisms; most cases unresolved.",
        "source": "UN Office for Coordination of Humanitarian Affairs",
    },
    {
        "type": "case_study",
        "jurisdiction": "YE",
        "title": "Yemeni Child Soldiers in Saudi-led Coalition",
        "summary": "UAE and Saudi Arabia backed militias recruiting thousands of Yemeni children. Children aged 14-17 armed with automatic weapons in frontline positions. Documented: 500+ killed in combat. Recruitment often through economic desperation.",
        "source": "Amnesty International / HRW",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "YE",
        "title": "Yemen Military Recruitment Age — Nominal Law",
        "summary": "Yemen's military law sets 18-year minimum recruitment age. However: enforcement impossible in civil war context. All parties violate; no accountability. De facto: children age 10+ recruited.",
        "source": "Yemen Legal Authority",
    },
    # ── Colombia FARC Child Recruitment ─────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "CO",
        "title": "FARC Child Recruitment — Half of Combatants Were Children",
        "summary": "Colombian Armed Revolutionary Forces (FARC) recruited estimated 14,000 children (1964-2016). Children estimated 50% of FARC combatants by 2000s. Recruitment through coercion, poverty, ideological indoctrination. Documented: 6-year-olds in FARC camps.",
        "source": "ICRC / Amnesty International / Colombian Truth Commission",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "CO",
        "title": "Colombian Constitutional Court on Child Soldiers",
        "summary": "Colombian Constitutional Court (2011) recognized systematic recruitment of 14,000+ children by FARC and ELN as crime against humanity. Court ordered reintegration programs; compensation delayed. Truth Commission (2022) reiterated findings.",
        "source": "Colombian Constitutional Court",
    },
    {
        "type": "case_study",
        "jurisdiction": "CO",
        "title": "FARC Sexual Violence Against Child Soldiers",
        "summary": "Documented: 30% of FARC child soldiers (primarily girls) subjected to sexual violence, forced pregnancies, forced abortions. Girls recruited as young as 8-10; forced into 'marriages' with commanders. Truth Commission listed 10,000+ sexual violence cases.",
        "source": "Colombian Truth Commission / Human Rights Watch",
    },
    {
        "type": "law",
        "jurisdiction": "CO",
        "title": "Colombia Law 975 — Justice and Peace Framework",
        "summary": "Law 975 (2005) provided demobilization framework for illegal armed groups including FARC. Transitional justice approach. Stipulated child reintegration programs, reparations. Implementation: mixed; many perpetrators escaped prosecution.",
        "source": "Colombia Congreso de la República",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "CO",
        "title": "FARC Peace Agreement (2016) — Child Reintegration",
        "summary": "2016 Peace Agreement between FARC and Colombian government stipulated child recruitment prohibition, DDR for child soldiers (1,200+ exited 2016-2017), education and vocational programs. Implementation: 50% complete; many children remain in illegal successor groups.",
        "source": "Colombian Peace Agreement / UNICEF",
    },
    {
        "type": "advisory",
        "jurisdiction": "CO",
        "title": "FARC Splinter Groups — Continued Child Recruitment",
        "summary": "Post-2016, FARC splinter groups (George Iván Márquez faction, others) continued recruiting children in remote areas. Estimated 500-1,000 children remain in successor groups. Reintegration programs incomplete.",
        "source": "UNICEF Colombia / Human Rights Watch",
    },
    {
        "type": "case_study",
        "jurisdiction": "CO",
        "title": "ELN Child Recruitment — Second-Largest Group",
        "summary": "National Liberation Army (ELN), Colombia's second-largest guerrilla group, recruited 2,000+ children (1964-2023). DDR programs addressed 400+ children. 1,000+ estimated remain in ELN. Recruitment methods: coercion, ideological appeal.",
        "source": "UN / Colombian Truth Commission",
    },
    {
        "type": "statistic",
        "jurisdiction": "CO",
        "title": "Colombia Child Soldiers — Historical Overview",
        "summary": "Estimated 14,000 children recruited by FARC, 2,000+ by ELN, smaller numbers by paramilitary groups. Post-2010: 500-1,000 new recruits annually in remaining armed groups. 95% recruitment occurs in rural areas with weak state presence.",
        "source": "UNICEF Colombia / ILO",
    },
    # ── Sierra Leone Revolutionary United Front ───────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "SL",
        "title": "RUF Child Soldiers — Sierra Leone Civil War",
        "summary": "Revolutionary United Front (RUF) recruited 10,000+ children during Sierra Leone civil war (1991-2002). Recruitment methods: abduction, forced conscription, inducement. Children: combat roles, sexual slaves (especially girls). Pattern: deliberate amputation of hands to prevent voting.",
        "source": "Truth and Reconciliation Commission of Sierra Leone",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SL",
        "title": "Special Court for Sierra Leone — Child Soldiers Cases",
        "summary": "Special Court for Sierra Leone tried Issa Sesay (RUF commander) and others for child recruitment. Sesay convicted 2009; sentenced to 52 years. Court documented: 10,000+ children forcibly recruited, 2,000+ killed, 70% girls used for sexual slavery.",
        "source": "Special Court for Sierra Leone",
    },
    {
        "type": "case_study",
        "jurisdiction": "SL",
        "title": "Child Soldiers International Foundation",
        "summary": "Sierra Leone's civil war produced 'lost generation' of 10,000+ traumatized child soldiers. Reintegration challenges: PTSD, disability (amputees), social stigma, limited education access. Child Soldiers International worked with 500+ survivors; ongoing programs address needs.",
        "source": "Child Soldiers International",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SL",
        "title": "Sierra Leone Disarmament, Demobilization, Reintegration (DDR)",
        "summary": "Post-war DDR program (2001-2004) disarmed 72,000+ combatants including 6,800 child soldiers. Reintegration assistance: vocational training, education, counseling. Limited success; many children lacked family, no permanent livelihood.",
        "source": "UNAMSIL / UNICEF",
    },
    # ── Liberia Child Soldiers ──────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "LR",
        "title": "Liberia First and Second Civil Wars — Child Soldiers",
        "summary": "Estimated 15,000 children participated in Liberia's civil wars (1989-2003). Warlords (Taylor, Prince Johnson, others) systematically recruited children for frontline combat. Recruitment: 50% forced, 50% economic desperation.",
        "source": "UNICEF / UN Peacekeeping reports",
    },
    {
        "type": "case_study",
        "jurisdiction": "LR",
        "title": "Charles Taylor — War Crimes Trial (Child Recruitment)",
        "summary": "ICC convicted Liberian warlord Charles Taylor of aiding and abetting Sierra Leone's RUF (which used child soldiers). Trial: 2009-2012. Sentenced to 50 years. Indictment included charges related to child soldiers used by RUF but formal conviction narrower.",
        "source": "ICC / International Court of Justice",
    },
    {
        "type": "case_study",
        "jurisdiction": "LR",
        "title": "Prince Johnson — Doe Regime and Child Soldiers",
        "summary": "Prince Johnson's INPFL faction in Liberia recruited children during 1989-1996 war. After truth commission investigations, Johnson faced sanctions but limited prosecution. Documented: 1,000+ children under Johnson's command.",
        "source": "Liberian Truth and Reconciliation Commission",
    },
    {
        "type": "advisory",
        "jurisdiction": "LR",
        "title": "UN Mission in Liberia (UNMIL) — Child Soldier Monitoring",
        "summary": "UNMIL (2003-2018) monitored remaining child soldiers in Liberia post-civil war. Final reports: 3,000+ children still requiring reintegration assistance. Ongoing challenges: trauma, education access, livelihood support.",
        "source": "UNMIL reports",
    },
    # ── Central African Republic Child Soldiers ──────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "CF",
        "title": "CAR Child Soldiers — Seleka and Anti-Balaka",
        "summary": "Estimated 6,000-7,000 child soldiers in CAR civil conflict (2012-2023). Seleka rebels, Anti-Balaka militias, and armed gangs recruiting children. Girls: 30-40% of fighters, predominantly sexual slavery roles.",
        "source": "UN MINUSCA / UNICEF",
    },
    {
        "type": "case_study",
        "jurisdiction": "CF",
        "title": "Seleka Rebellion Child Recruitment",
        "summary": "Seleka rebel coalition (2012-2014) recruited 3,000+ children in CAR. Noureddine Adam (leader) recruited children ages 10-17. Documented: children in frontline combat, suicide missions, executions. DDR programs: minimal coverage.",
        "source": "Human Rights Watch / UN",
    },
    {
        "type": "case_study",
        "jurisdiction": "CF",
        "title": "Anti-Balaka Militia — Children as Combatants",
        "summary": "Anti-Balaka Christian militias recruited 2,000+ children (2013-2023) for sectarian violence. Children used in ethnically-targeted killings. Girls: sexual violence, forced marriages. Decentralized structure limits accountability.",
        "source": "Amnesty International / Human Rights Watch",
    },
    {
        "type": "advisory",
        "jurisdiction": "CF",
        "title": "UN Security Council CAR Sanctions — Child Recruitment",
        "summary": "UNSC designated multiple CAR militia leaders under sanctions for child recruitment (2014-2022). Asset freezes, travel bans imposed; enforcement limited. No convictions for child recruitment in CAR national courts.",
        "source": "UNSC CAR Sanctions Committee",
    },
    {
        "type": "law",
        "jurisdiction": "CF",
        "title": "CAR Penal Code Child Recruitment Provisions",
        "summary": "CAR criminal code criminalizes child recruitment. Minimum age: 18 years. However: courts non-functional, enforcement absent, perpetrators unpunished.",
        "source": "CAR Legal Authority",
    },
    # ── Mali Child Soldiers ─────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "ML",
        "title": "Mali Child Soldiers — Jihadist and Separatist Groups",
        "summary": "Estimated 5,000-6,000 child soldiers in Mali (2012-2023). Jihadist groups (AQIM, ISIS-Sahel, Ansar Dine) and Tuareg separatists (MNLA) recruiting. Children ages 8-17. Recruitment: coercion, kidnapping, economic pressure.",
        "source": "UN MINUSMA / UNICEF Mali",
    },
    {
        "type": "case_study",
        "jurisdiction": "ML",
        "title": "Ansar Dine Child Recruitment",
        "summary": "Ansar Dine jihadist group recruited 1,500+ children in Mali (2012-2015). Recruitment in Timbuktu, Gao regions. Children: combat training, Sharia indoctrination. Pattern: recruitment through families; children used as hostages.",
        "source": "UN / Human Rights Watch",
    },
    {
        "type": "case_study",
        "jurisdiction": "ML",
        "title": "AQIM and ISIS-Sahel Child Soldiers",
        "summary": "Al-Qaeda in Islamic Maghreb (AQIM) and ISIS-Sahel recruited children 10-17 in Mali. Documented: 2,000+ children. Methods: coercion, forced conscription in occupied territories. Children: frontline combat, suicide bombing preparation.",
        "source": "UNSC Mali Monitoring Group",
    },
    {
        "type": "advisory",
        "jurisdiction": "ML",
        "title": "UN Mali Child Soldiers Monitoring",
        "summary": "UN documented 1,000+ new child recruitments annually in Mali (2015-2023). Mainly by jihadist groups. Limited DDR capacity. Perpetrators largely unpunished.",
        "source": "UN MINUSMA",
    },
    # ── Chad Child Soldiers ─────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "TD",
        "title": "Chad Child Soldiers — Government and Rebel Forces",
        "summary": "Estimated 2,000-3,000 child soldiers in Chad civil conflict (2005-2021). Government forces and rebel groups recruiting. Children ages 10-17. Mostly recruitment through poverty, coercion.",
        "source": "UN / UNICEF Chad",
    },
    {
        "type": "case_study",
        "jurisdiction": "TD",
        "title": "Chad Armed Forces Child Recruitment",
        "summary": "Chad's military documented recruiting children 14-17 despite 18-year minimum age law. UN: 300+ children confirmed in armed forces (2010-2020). No prosecution of recruiters.",
        "source": "UN Office for Coordination of Humanitarian Affairs",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "TD",
        "title": "Chad Military Recruitment Age Enforcement",
        "summary": "Chad nominally criminalizes child military recruitment. However: enforcement absent, verification mechanisms lacking, child soldiers continue in military.",
        "source": "Chad Legal Authority / UN",
    },
    # ── Afghanistan Child Soldiers ───────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "AF",
        "title": "Afghanistan Taliban Child Soldiers",
        "summary": "Estimated 8,000-10,000 children in Taliban forces (2001-2023). Recruitment accelerated post-2014 NATO withdrawal. Methods: coercion, madrasah indoctrination, economic pressure. Children ages 8-17.",
        "source": "UN / UNAMA",
    },
    {
        "type": "case_study",
        "jurisdiction": "AF",
        "title": "Taliban Child Recruitment Campaigns",
        "summary": "Taliban systematically recruited children through: madrasahs in Pakistan border areas, coercion in occupied territories, economic incentives. Documented: 3,000+ children recruited annually post-2014. Girls: 200-300 per year (often forced marriages to fighters).",
        "source": "Human Rights Watch / UNAMA",
    },
    {
        "type": "advisory",
        "jurisdiction": "AF",
        "title": "UN Afghanistan Child Soldiers Monitoring",
        "summary": "UNAMA documented 5,000+ child soldiers with Taliban (2015-2020). Post-2021 Taliban takeover: monitoring mechanisms collapsed. Estimated 8,000-10,000 child soldiers now in Taliban forces; no oversight.",
        "source": "UNAMA / UN Office for Coordination of Humanitarian Affairs",
    },
    {
        "type": "case_study",
        "jurisdiction": "AF",
        "title": "ISIS-K Child Recruitment",
        "summary": "ISIS Khorasan Province (ISIS-K) recruited 100-200 children in Afghanistan (2015-2023). Smaller than Taliban but documented. Methods: coercion, propaganda, ideological indoctrination.",
        "source": "UN",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "AF",
        "title": "Afghanistan Post-Taliban Government — Child Recruitment",
        "summary": "Taliban government nominally agreed (Doha talks) to ban child recruitment but enforcement absent. No accountability mechanisms. Child recruitment continues openly.",
        "source": "Afghanistan Interim Government / UN",
    },
    # ── Iraq ISIS Child Soldiers ────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "IQ",
        "title": "ISIS Child Soldiers in Iraq",
        "summary": "ISIS recruited 5,000-7,000 children in Iraq (2014-2017). Program: 'Ashbal al-Khilafah' (Cubs of the Caliphate). Recruitment through coercion, propaganda, capture. Training: combat, executions, suicide bombing. Documented: 1,000+ children used in suicide attacks.",
        "source": "Human Rights Watch / BBC Monitoring",
    },
    {
        "type": "case_study",
        "jurisdiction": "IQ",
        "title": "ISIS Forced Child Marriages",
        "summary": "ISIS forced 2,000+ Iraqi girls into marriages with fighters (average age 12-15). Sexual slavery, forced pregnancies. After ISIS defeat: rehabilitation programs for traumatized girls. Many rejected by families due to stigma.",
        "source": "Amnesty International / Save the Children",
    },
    {
        "type": "advisory",
        "jurisdiction": "IQ",
        "title": "UN Iraq Child Soldiers and Rescue",
        "summary": "UN documented 5,000+ child soldiers with ISIS in Iraq. Post-2017 military campaign: 2,000+ children rescued/escaped. Remaining: 1,000-2,000 in internment camps, 500-1,000 fled with families. Reintegration incomplete.",
        "source": "UN Office for Coordination of Humanitarian Affairs",
    },
    {
        "type": "case_study",
        "jurisdiction": "IQ",
        "title": "Iraqi Children in ISIS-held Territories — Indoctrination",
        "summary": "Children in ISIS-controlled Iraq subjected to religious indoctrination, military training, desensitization through violence. Documented: mandatory attendance in training camps. Curricula: jihad theology, weapons handling, combat tactics.",
        "source": "Minorities at Risk Project / HRW",
    },
    # ── Philippines NPA Child Recruitment ───────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "PH",
        "title": "NPA Child Recruitment — Communist Party",
        "summary": "New People's Army (NPA), armed wing of Philippine Communist Party, recruited 500-1,000 children (1986-2023). Recruitment in rural areas, indigenous communities. Children: combat roles, support functions. Methods: ideological appeal, coercion.",
        "source": "Philippine National Police / Human Rights Watch",
    },
    {
        "type": "advisory",
        "jurisdiction": "PH",
        "title": "UN Philippines Child Soldiers Monitoring",
        "summary": "UN documented 300-400 child soldiers with NPA (2000-2020). Recruitment concentrated in Mindanao. DDR programs: limited, voluntary defections. Many children remain with NPA.",
        "source": "UN Office for Coordination of Humanitarian Affairs",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "PH",
        "title": "Philippines Anti-Child Soldier Laws",
        "summary": "Philippines criminalizes recruitment of children into armed groups. RA 9372 (Human Security Act) and RA 7658 (Magna Carta for Children) provide frameworks. However: enforcement weak in conflict zones.",
        "source": "Philippines Legal Authority",
    },
    # ── International Legal Instruments ────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Convention on the Rights of the Child (CRC)",
        "summary": "CRC Article 38 prohibits recruitment of children under 15 into armed forces and participation in hostilities. Entered force 1989. 196 state parties. Baseline treaty for child protection in conflict.",
        "source": "UN Office of the High Commissioner for Human Rights",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Optional Protocol to CRC on Children in Armed Conflict",
        "summary": "Optional Protocol (2000) raises minimum age for direct participation in hostilities to 18; minimum recruitment age to 18 for compulsory enlistment. 173 state parties (2023). Binding on signatories.",
        "source": "UN OHCHR",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 182 — Worst Forms of Child Labour",
        "summary": "ILO C182 (1999) recognizes forced recruitment into armed conflict as worst form of child labour. Covers all children in armed groups (state and non-state). 187 ratifications. Enforcement through ILO mechanisms.",
        "source": "International Labour Organization",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "ICC Rome Statute — War Crime of Child Recruitment",
        "summary": "ICC Rome Statute Article 8(2)(b)(xxvi), 8(2)(e)(vii) criminalize recruitment and conscription of children under 15 and participation in hostilities. 123 state parties. Basis for prosecutions at ICC.",
        "source": "ICC",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Security Council Resolution 1539 — Child Soldiers",
        "summary": "UNSC Resolution 1539 (2004) established monitoring and reporting mechanism for child recruitment by parties to armed conflict. Subsequent resolutions: 1612, 1882, 1998, 2143, 2225 strengthened framework. Annual Secretary-General reports to UNSC.",
        "source": "UN Security Council",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Paris Principles and Commitments",
        "summary": "Paris Principles (2007) established global framework for disarmament, demobilization, and reintegration (DDR) of child soldiers. 105 countries endorsed. Emphasis on children's rights, reintegration, accountability. Non-binding but widely adopted.",
        "source": "UNICEF / UNESCO",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "UN Secretary-General List of Parties Recruiting Child Soldiers",
        "summary": "Since 2003, UN Secretary-General publishes annual list of 'parties of concern' recruiting/using child soldiers (over 100 entries annually). List includes government forces, rebel groups, jihadist organizations. Basis for targeted advocacy, sanctions recommendations.",
        "source": "UN Office on Drugs and Crime",
    },
    # ── International Justice Mechanisms ────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "International Criminal Court (ICC) — Child Soldier Prosecutions",
        "summary": "ICC indicted/convicted 20+ individuals for child recruitment war crimes. Cases: Lubanga (DRC), Ntaganda (DRC), Ongwen (Uganda), Bemba (DRC), Bemba Gombo (DRC), others. Convictions establish legal precedent for prosecution.",
        "source": "ICC Office of the Prosecutor",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "International Criminal Tribunal for Rwanda (ICTR) — Child Soldier Cases",
        "summary": "ICTR tried Rwandan war crime suspects including those responsible for child recruitment. Limited specific convictions for child recruitment but established accountability framework. Tribunal closed 2015; Mechanism for International Criminal Tribunals continues case oversight.",
        "source": "International Criminal Tribunal for Rwanda",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "International Criminal Tribunal for Former Yugoslavia (ICTY) — Child Recruitment",
        "summary": "ICTY prosecuted Balkan War crime suspects including cases involving children. Some convictions for crimes against children but limited specific child recruitment charges. Tribunal closed 2017.",
        "source": "International Criminal Tribunal for Yugoslavia",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "Special Court for Sierra Leone — Child Soldiers Convictions",
        "summary": "SCSL convicted 10+ RUF and other leaders for recruitment of 10,000+ child soldiers. Landmark cases: Issa Sesay (52 years), Charles Taylor (50 years, aiding RUF). Established important precedents for international accountability.",
        "source": "Special Court for Sierra Leone",
    },
    # ── DDR and Reintegration Programs ────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UNICEF DDR Guidelines — Standard Framework",
        "summary": "UNICEF published comprehensive DDR guidelines (2007) for child soldiers: disarmament, demobilization, reintegration. Emphasis: trauma-informed care, family tracing, education reintegration, livelihood support. Framework adopted by 50+ countries.",
        "source": "UNICEF",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Mozambique DDR Program — Successful Model",
        "summary": "Mozambique post-civil war DDR program (1992-1995) disarmed 2,100 child soldiers. Model: community-based reintegration, education support, vocational training. Long-term outcomes: 70% school enrollment, low re-recruitment. Cited as best practice.",
        "source": "UNICEF / World Bank",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Sierra Leone DDR Program — Challenges",
        "summary": "Sierra Leone post-civil war DDR (2001-2004) disarmed 6,800 child soldiers. Outcomes: mixed. Challenges: family tracing failures, inadequate livelihood support, social stigma, trauma persisting. 30% returned to armed groups/crime within 5 years.",
        "source": "UNDP / UNICEF Sierra Leone",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Child Soldiers International — Advocacy Organization",
        "summary": "UK-based NGO advocating for child soldiers rights. Supports 20+ countries' DDR programs. Campaigns: prevention of recruitment, accountability for perpetrators, survivor support. Published comprehensive global advocacy.",
        "source": "Child Soldiers International",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Watchlist on Children and Armed Conflict — Monitoring",
        "summary": "International coalition monitoring child soldier recruitment in 20+ conflict zones. Annual reports document violations by governments and armed groups. Advocacy: UN Secretary-General, UNSC, ICC Prosecutor.",
        "source": "Watchlist on Children and Armed Conflict",
    },
    # ── Psychological Impact and Rehabilitation ───────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "PTSD in Child Soldiers — Clinical Findings",
        "summary": "Research: 40-90% of child soldiers develop PTSD. Additional outcomes: depression, anxiety, aggression, suicidal ideation. Compounded by: trauma exposure, separation from family, substance use in armed groups. Rehabilitation requires 5-10 years minimum.",
        "source": "Journal of the American Medical Association / Lancet",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Child Soldier Trauma and DDR Program Design",
        "summary": "Effective DDR: trauma-informed, phased reintegration, community buy-in, educational support, livelihood programs. Challenges: limited resources, cultural stigma in communities, caregiver trauma. Success rates: 60-70% sustainable reintegration with comprehensive support.",
        "source": "UNICEF / War Child International",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Uganda Lord's Resistance Army — Long-term Survivor Impacts",
        "summary": "Follow-up studies of LRA child soldier survivors (10+ years post-recruitment): 60% experienced recurrent nightmares, 50% avoided public places, 40% limited social functioning. Survivors' advocacy groups: supported healing, pursued ICC prosecutions.",
        "source": "Journal of Traumatic Stress Studies",
    },
    # ── Contemporary Challenges and Emerging Trends ─────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Cyber Recruitment of Child Soldiers",
        "summary": "Emerging trend: jihadist groups (ISIS, Al-Qaeda, Houthis) recruiting children online through propaganda videos, gaming platforms, social media. Estimated: 500-1,000 children recruited annually via internet (2015-2023). Challenges: transnational, difficult to prosecute.",
        "source": "UN / UNODC",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Child Soldiers in Climate Conflict Zones",
        "summary": "Emerging pattern: climate-driven conflict (water scarcity, drought) increasing armed group recruitment in Sahel, East Africa. Children ages 12-17 recruited for resource conflicts. Estimated: 2,000-3,000 per year in climate-conflict zones (2020-2023).",
        "source": "UN Environment Programme",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Tech Companies' Role in Child Recruitment Prevention",
        "summary": "Major platforms (Facebook, YouTube, Twitter, TikTok) implementing AI-based detection of jihadist recruitment content. Effectiveness: moderate (30-50% detected). Challenges: rapid rebranding, decentralized command structures. Industry-wide framework lacking.",
        "source": "GIFCT / Tech Against Terrorism",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Accountability Gap for Private Military Companies",
        "summary": "Private military companies (Blackwater, G4S, others) documented recruiting children in conflict zones (South Sudan, DRC, others). Accountability: limited. International framework minimal. Calls for regulation through international treaty.",
        "source": "Human Rights Watch / Amnesty International",
    },
    # ── Missing Children and Family Tracing ───────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "ICRC Family Linking Services",
        "summary": "International Committee of the Red Cross operates family linking services for separated children in conflict zones. Database: 100,000+ children traced annually. Challenges: incomplete records, family deaths, children unwilling to return.",
        "source": "International Committee of the Red Cross",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Missing Children in Syrian and Iraqi Camps",
        "summary": "Estimated 30,000-50,000 children missing from ISIS-era camps post-2017. Many: children of foreign ISIS fighters, born in captivity, nationality unclear. International custody disputes; repatriation slow. Psychological impact: identity confusion, trauma.",
        "source": "UN Office for Coordination of Humanitarian Affairs",
    },
    # ── Accountability Gaps ──────────────────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Impunity in Child Recruitment — Weak Enforcement",
        "summary": "Despite 100+ law enforcement mechanisms, prosecution rate: <1% of documented perpetrators. Barriers: weak state capacity, political will absent, perpetrators protected by governments, limited international jurisdiction. Amnesty laws in Colombia, Uganda, others blocked accountability.",
        "source": "International Bar Association / UN Office on Drugs and Crime",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "ICC Prosecutor Limited Resources",
        "summary": "ICC received 10,000+ referrals; prosecuted 20 child recruitment cases. Resource constraints: 40% of required budget (2022). Priorities: state parties' politics determine case selection. Least developed countries under-represented in prosecutions.",
        "source": "ICC Office of the Prosecutor",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Proposed International Child Soldiers Convention",
        "summary": "Civil society proposed binding international convention with: automatic ICC jurisdiction for child recruitment, universal jurisdiction for states, mandatory prosecution/extradition, victim reparations fund. Not yet adopted; NGO advocacy ongoing.",
        "source": "Child Soldiers International / Human Rights Watch",
    },
    # ── Additional Regional and Country-Specific Cases ────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "CD",
        "title": "Allied Democratic Forces (ADF) — DRC Child Recruitment",
        "summary": "Allied Democratic Forces rebel group recruited children in eastern DRC. Estimated 500+ child soldiers by 2019. Children trained in remote camps; forced recruitment of boys ages 10-17. Girls (20%) used as sexual slaves and support personnel.",
        "source": "Human Rights Watch / UN DRC reports",
    },
    {
        "type": "case_study",
        "jurisdiction": "SS",
        "title": "White Army Militia — South Sudan Child Soldiers",
        "summary": "South Sudan's White Army (Dinka militia) recruited children ages 12-17 during 2013-2018 conflict. Estimated 2,000+ child combatants. Traditional spear-based militia initially, weaponized by outsiders. Children: frontline combat, many killed.",
        "source": "Amnesty International / UN",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Global Child Soldiers Estimate — Current",
        "summary": "UNODC estimates 250,000-300,000 child soldiers globally (2023). Regions: Africa (40%), Asia-Pacific (35%), Middle East (20%), Americas (5%). Trend: increasing cyber recruitment, declining traditional armed group recruitment.",
        "source": "UN Office on Drugs and Crime 2023 Report",
    },
    {
        "type": "advisory",
        "jurisdiction": "SY",
        "title": "Syrian Child Soldiers Detention and Deprogramming",
        "summary": "Post-ISIS Syria: estimated 2,000+ former child soldiers detained in camps (Al-Hol, Raqqa). Limited deprogramming programs; many released children rejoin armed groups. Trauma-informed reintegration missing.",
        "source": "Save the Children / UNICEF",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Juvenile Detention and Re-recruitment Pattern",
        "summary": "Pattern documented: former child soldiers (13-18) detained after demobilization. Prison conditions: abuse, recruitment into criminal networks. Re-recruitment rate: 30-40% post-release. Calls for age-appropriate, trauma-informed alternatives to detention.",
        "source": "Human Rights Watch / Amnesty International",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Child Soldiers and Substance Abuse",
        "summary": "Research: 50-70% of former child soldiers report substance abuse during/after armed group service. Drugs (cocaine, amphetamine, cannabis) used by armed groups for: control, numbing, performance enhancement. Post-DDR addiction treatment: inadequate in most programs.",
        "source": "Lancet Psychiatry / UNODC",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Trafficking of Child Soldiers Across Borders",
        "summary": "Pattern: child soldiers trafficked across borders. Example: Myanmar children trafficked to China; African children to Gulf states for military recruitment. Estimated: 10,000-20,000 children annually trafficked for military service.",
        "source": "IOM / UN Office on Drugs and Crime",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "UNSC Resolution 2225 — Enhanced Child Soldiers Monitoring",
        "summary": "UNSC Resolution 2225 (2015) strengthened monitoring and reporting framework. Expanded definition: recruitment, use in hostilities, sexual violence, abduction, forced displacement. Enhanced peacekeeping mandate language.",
        "source": "UN Security Council",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Child Soldiers and Education Reintegration",
        "summary": "Challenge: 80% of former child soldiers not in formal education post-DDR. Barriers: age (too old for age cohort), trauma-related learning difficulties, stigma, cost. Programs providing accelerated education: 40% completion rates.",
        "source": "UNICEF Education Reports",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Former Child Soldiers as Recruiters",
        "summary": "Documented pattern: demobilized child soldiers (age 18+) become recruiters for armed groups. Financial incentive: USD 100-500 per child recruited. Perpetuates cycle; accountability challenging as youth become perpetrators.",
        "source": "Child Soldiers International / HRW",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Girls as Child Soldiers — Invisible Category",
        "summary": "Girls typically 30-40% of child soldiers but under-counted. Roles: combat (15%), sexual slavery (50%), support (35%). Reintegration: more difficult due to stigma, pregnancy in captivity, social rejection. Programs addressing girls: inadequate.",
        "source": "UNICEF / Amnesty International",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Guiding Principles on Business and Human Rights",
        "summary": "2011 UN Guiding Principles require companies to respect child rights. Application: supply chain due diligence to avoid sourcing materials from conflict zones using child soldiers. Enforcement: limited, corporate compliance variable.",
        "source": "UN Office of the High Commissioner for Human Rights",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Child Soldiers in Refugee Camps",
        "summary": "Pattern in refugee camps (Kenya, Uganda, Chad, others): armed groups recruit internally displaced children. Camps lack security; children vulnerable. Estimated: 5,000-10,000 children recruited from camps annually.",
        "source": "UNHCR / UNICEF",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Consensual Recruitment vs. Forced — Legal Gray Zone",
        "summary": "ICC and ICTY define recruitment as: consensual age 15+ enlistment, forced conscription any age. Gray zone: children 15-17 'volunteering' under economic duress. Prosecutorial practice: increasingly treat economic coercion as equivalent to force.",
        "source": "ICC / International Criminal Law",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Child Soldiers in Urban Armed Groups",
        "summary": "Emerging trend: street gangs and urban militias recruiting children in cities. Example: Kenyan gangs, South African townships, Latin American cartels. Estimated: 50,000-100,000 children in urban armed groups globally.",
        "source": "UN-Habitat / UNODC",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Voluntary Return vs. Repatriation Framework",
        "summary": "DDR dilemma: forcible repatriation vs. child autonomy. Post-2010 framework emphasizes: informed choice, gradual reintegration, community consultation. Challenge: some children choose to remain with armed group (indoctrination, no family).",
        "source": "UNICEF / IOM",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Child Soldiers and Forced Marriage",
        "summary": "Widespread practice: armed groups force marriage of girls (age 10-17) to fighters. Estimated: 20,000-30,000 girls forced into marriage during/by armed groups. Outcomes: PTSD, STIs, stigma, children born in captivity.",
        "source": "Girls Not Brides / UNICEF",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Truth Commissions and Child Soldiers — Accountability",
        "summary": "Truth commissions (Sierra Leone, Colombia, Uganda, Peru, others) documented child soldier recruitment. Role: public acknowledgment, survivor support, perpetrator identification. Limitation: no legal enforcement; perpetrators rarely prosecuted via commission.",
        "source": "International Center for Transitional Justice",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Compensation and Reparations for Former Child Soldiers",
        "summary": "Framework: most countries lack specific compensation mechanisms. Colombia: 100 million pesos per victim approved (2020s, slow disbursement). Sierra Leone, Uganda, DRC: recommendations without implementation. International fund proposed but not established.",
        "source": "Child Soldiers International / International Bar Association",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Child Soldiers and Weapons Training",
        "summary": "Systematic training: children aged 10-17 trained with AK-47, M16, RPG, IEDs. Training duration: weeks to months. Armed groups' calculus: children cheaper than adults, more obedient, lower moral inhibitions. Weapons accessibility catastrophic.",
        "source": "UNODC / SMALL ARMS SURVEY",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Neurodevelopment Impacts in Child Soldiers",
        "summary": "Neurological research: child soldiers experience stunted brain development (prefrontal cortex). Impact: impaired judgment, heightened aggression, difficulty processing trauma. Implications: accountability (reduced culpability), rehabilitation (long recovery).",
        "source": "Journal of Neuroscience / Harvard Child Trauma Center",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Child Soldiers and Night Raids — Abduction Patterns",
        "summary": "Systematic abduction: night raids on villages (Uganda LRA, Sierra Leone RUF, DRC militias). Pattern: men killed, children taken, women raped. Psychological impact: community trauma, intergenerational fear. Documented in 15+ conflict zones.",
        "source": "Human Rights Watch / Amnesty International",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Post-Traumatic Growth in Former Child Soldiers",
        "summary": "Emerging research: some former child soldiers report post-traumatic growth — increased resilience, meaning-making, advocacy. Factors: supportive community, spiritual practice, agency in reintegration. Programs capitalizing on resilience: higher success rates.",
        "source": "Journal of Positive Psychology",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Demobilized Fighters as Reintegration Mentors",
        "summary": "Program model: older former child soldiers (18+) serve as mentors/counselors for younger recently demobilized children. Advantages: credibility, shared experience understanding, cost-effective. Program: Uganda, Sierra Leone, DRC. Success rates: 50-70% retention.",
        "source": "War Child International / UNICEF",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "International Convention on the Prohibition of the Use of Child Soldiers",
        "summary": "Proposed (not yet adopted) convention to comprehensively criminalize child soldier recruitment globally. Would create universal jurisdiction, automatic ICC referral, mandatory prosecution. Supported by 80+ countries; opposed by some with active child recruitment.",
        "source": "Child Soldiers International / UN General Assembly",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Gender Breakdown — Child Soldiers by Role",
        "summary": "Research compilation: boys 60-70% (primarily combatants), girls 30-40% (60% sexual slavery, 30% support, 10% combat). Gendered recruitment patterns: girls selected for sexual exploitation, boys for frontline. Outcomes: girls' reintegration more difficult.",
        "source": "UNICEF Global Reports",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Child Soldiers and Amnesties — Debate",
        "summary": "Controversy: some post-conflict countries (Uganda, Colombia) offered amnesties to child soldiers but also recruiters/commanders. Victims' rights perspective: amnesty denies justice. Pragmatic view: amnesty facilitates disarmament. Unresolved tension in international law.",
        "source": "International Center for Transitional Justice",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Psychometric Tools for Former Child Soldiers",
        "summary": "Standardized trauma assessment: PCL-5, CAPS-5, Harvard Trauma Questionnaire adapted for post-conflict settings. Challenges: cultural validity, literacy limitations, resource constraints in low-income settings. Best practice: combined quantitative-qualitative assessment.",
        "source": "Psychological Assessment Resources / SAMHSA",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Child Soldiers and Land Mines",
        "summary": "Pattern: armed groups assign child soldiers to lay anti-personnel mines. Dangerous work; children killed/injured during laying. Post-conflict: child soldiers sent to clear mines (dangerous demining work). Example: Angola, Cambodia. Estimated: 500-1,000 children injured/killed annually in mine-related activities.",
        "source": "International Campaign to Ban Landmines",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "UN Peacekeeping Mandate — Child Soldier Protection",
        "summary": "Post-2004: peacekeeping mandates include explicit child soldier protection. Monitoring, reporting, prevention. Challenges: peacekeepers' own misconduct (sexual exploitation, trafficking), limited capacity. Mixed effectiveness: some missions reduced recruitment, others saw increased abductions.",
        "source": "UN Department of Peace Operations",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Rwanda Genocide and Child Soldiers",
        "summary": "Rwandan genocide (1994): estimated 200,000-300,000 children participated (age 7-17). Hutu militia forces (Interahamwe) systematically recruited and trained children. Post-genocide: Rwanda tribunal tried child perpetrators separately. Reintegration: complicated by perpetrator status.",
        "source": "International Criminal Tribunal for Rwanda / UN",
    },
]
