"""Worker complaint mechanisms, dispute resolution, and grievance systems."""

COMPLAINT_FACTS: list[dict] = [
    {
        "type": "complaint",
        "jurisdiction": "HK",
        "title": "Hong Kong Labour Tribunal — FDH Wage Claims",
        "summary": "Labour Tribunal handles wage disputes without legal representation requirement. FDHs can file claims for: unpaid wages, unlawful deductions, rest day denial, wrongful termination. Free legal aid available (Duty Lawyer Scheme). Processing: 2-6 months. Two-week rule creates urgency: workers may lose immigration status before case concludes. Annual FDH complaints: 5,000-7,000. Success rate: ~55%.",
        "source": "Hong Kong Labour Department / Duty Lawyer Service",
    },
    {
        "type": "complaint",
        "jurisdiction": "SG",
        "title": "Singapore MOM Complaint Process for Foreign Workers",
        "summary": "Workers file complaints at MOM Employment Standards Division. Process: mediation → investigation → prosecution if warranted. Workers issued Special Pass (renewable) to remain during proceedings. Temporary accommodation at MOM-funded shelters. Processing: 1-6 months. Annual foreign worker salary claims: 8,000+. MOM can prosecute employers under EFMA. Employer penalties: fines up to SGD 30,000, imprisonment up to 12 months.",
        "source": "Singapore MOM / TWC2 / HOME",
    },
    {
        "type": "complaint",
        "jurisdiction": "QA",
        "title": "Qatar Labour Dispute Resolution Committees (LDRC)",
        "summary": "LDRCs established 2018, operational 2020. Handle wage claims, contract disputes, end-of-service benefits. Process: filing → notification → hearing (within 3 weeks) → decision (within 3 more weeks). Appeals to Court of Appeal. Workers can file in Arabic, English, or through interpreter. Free of charge. 35,000+ cases filed (2022-2023). Average claim: QAR 15,000. Employer compliance with decisions: ~60%.",
        "source": "Qatar Ministry of Labour / ILO",
    },
    {
        "type": "complaint",
        "jurisdiction": "SA",
        "title": "Saudi Arabia Labour Court System",
        "summary": "Labour courts handle disputes between employers and workers. Process: amicable settlement attempt (MOHRE) → labour court filing → hearing → judgment. Duration: 3-12 months. Workers must remain in country during proceedings (visa dependency). Legal aid limited. Language barriers: proceedings in Arabic. Annual migrant worker cases: 100,000+. Many workers accept settlement below entitlement to expedite departure.",
        "source": "Saudi Ministry of Justice / ILO",
    },
    {
        "type": "complaint",
        "jurisdiction": "AE",
        "title": "UAE MOHRE Online Complaint Portal",
        "summary": "Workers file complaints via MOHRE app, website, or service centres. Process: automatic mediation (14 days) → referral to court if unresolved. Workers issued temporary work permit during proceedings. 6-month grace period after termination to find new employer or resolve dispute. Smart complaint system tracks cases. Annual complaints: 200,000+. Common issues: wage non-payment (40%), end-of-service (25%), contract disputes (20%).",
        "source": "UAE MOHRE",
    },
    {
        "type": "complaint",
        "jurisdiction": "MY",
        "title": "Malaysia Labour Department Complaint Process",
        "summary": "Workers file at Jabatan Tenaga Kerja (Labour Department). Process: mediation → Labour Court hearing. Workers must have valid work permit to file (undocumented workers effectively excluded). Processing: 3-12 months. Language: Malay (interpreter not always available). Special Pass for workers whose permits expire during proceedings: difficult to obtain. Many workers deported before case resolves.",
        "source": "Malaysia Department of Labour / Tenaganita / Bar Council",
    },
    {
        "type": "complaint",
        "jurisdiction": "TH",
        "title": "Thailand Labour Protection Office Complaint System",
        "summary": "Workers file at provincial Labour Protection Office. Process: inspection → conciliation → Labour Court. Workers need identification (work permit or passport). Undocumented workers can file but risk arrest and deportation. Processing: 2-12 months. Language barriers: proceedings in Thai. Legal aid from NGOs (LPN, MAP Foundation, Migrant Working Group). Success rate for documented workers: ~40%.",
        "source": "Thailand Department of Labour Protection and Welfare / LPN",
    },
    {
        "type": "complaint",
        "jurisdiction": "KR",
        "title": "South Korea EPS Worker Grievance System",
        "summary": "EPS workers file grievances at: Employment Security Center, Korea Foreign Workers Center, or EPS Help Desk. Process: counselling → mediation → labour tribunal. Workers issued humanitarian visa (G-1) during proceedings. Free legal aid and interpretation available. Annual EPS complaints: 15,000+. Workplace change possible after complaint (up to 3 times). Korean Labour Standards Act applies equally to migrant workers.",
        "source": "Korea HRD Service / Korea Foreign Workers Center",
    },
    {
        "type": "complaint",
        "jurisdiction": "JP",
        "title": "Japan TITP/SSW Worker Complaint Channels",
        "summary": "TITP: complaints to OTIT (Organization for Technical Intern Training) via hotline (multilingual). OTIT conducts inspections. Workers can also contact Labour Standards Inspection Office. SSW: complaints to regional immigration bureau. NGO support: Solidarity Network with Migrants Japan (SMJ). Key issue: TITP workers cannot change employer, so complaints risk retaliation. Language support in Vietnamese, Chinese, Filipino, Indonesian, English.",
        "source": "OTIT / Japan Ministry of Justice / SMJ",
    },
    {
        "type": "complaint",
        "jurisdiction": "US",
        "title": "US National Human Trafficking Hotline — Complaint Mechanism",
        "summary": "24/7 hotline: 1-888-373-7888 (call) or text 233733. Operated by Polaris Project. 200+ languages. Annual contacts: 50,000+ (2022). Reports referred to law enforcement, FBI, DOJ, or local agencies. T-visa pathway for identified trafficking victims (5,000/year cap, rarely filled). Workers can also file complaints with WHD (Wage and Hour Division) for FLSA violations without immigration consequences.",
        "source": "Polaris Project / US DOJ / DHS",
    },
    {
        "type": "complaint",
        "jurisdiction": "UK",
        "title": "UK Modern Slavery Helpline and NRM Referral",
        "summary": "Modern Slavery Helpline: 0800 121 700 (24/7). Operated by Unseen. 10,000+ contacts/year. Referral to National Referral Mechanism (NRM) for victim identification. NRM decision: 'reasonable grounds' (within 5 days) → 'conclusive grounds' (within 45 days). Positive NRM decision: 12 months discretionary leave, support services. Annual NRM referrals: 17,000+ (2023). Top nationalities: Albanian, Vietnamese, Eritrean, British.",
        "source": "UK Home Office / Unseen / Salvation Army",
    },
    {
        "type": "complaint",
        "jurisdiction": "international",
        "title": "Retaliation Risks for Workers Filing Complaints",
        "summary": "Workers filing complaints face: immediate termination (most common), visa cancellation by employer, absconding charges filed by employer (Gulf states), physical threats/violence, blacklisting by recruitment agencies (preventing future deployment), deportation before case resolves, eviction from employer-provided housing. Only 10-15% of exploited workers file formal complaints. Fear of retaliation is primary deterrent.",
        "source": "ILO / GAATW / Migrant Forum in Asia",
    },
    {
        "type": "complaint",
        "jurisdiction": "international",
        "title": "Anonymous Reporting Channels for Migrant Workers",
        "summary": "Anonymous reporting options: IOM Counter-Trafficking helplines (multi-country), NGO hotlines (HOME SG, TWC2 SG, Justice Centre HK), faith-based organizations (churches, mosques), online platforms (Apprise app by Unseen, IOM MigApp). Limitations: anonymous reports cannot trigger individual case investigation, used primarily for intelligence gathering and trend analysis. Workers prefer trusted community members as intermediaries.",
        "source": "IOM / Unseen / NGO networks",
    },
    {
        "type": "complaint",
        "jurisdiction": "international",
        "title": "Third-Party Complaint Filing by NGOs and Unions",
        "summary": "In jurisdictions where workers cannot safely file directly, NGOs file on their behalf: TWC2 (Singapore) assists with MOM claims, Justice Centre HK provides legal representation, BWI files ILO complaints on behalf of construction workers, ITUC uses OECD National Contact Points to file against multinationals. Union representation rare for migrant workers (most destination countries restrict migrant unionization).",
        "source": "ITUC / BWI / TWC2 / Justice Centre HK",
    },
    {
        "type": "complaint",
        "jurisdiction": "international",
        "title": "Cross-Border Complaint Mechanisms — Limitations",
        "summary": "Workers who return home before resolving disputes lose access to destination country courts. Cross-border mechanisms limited to: bilateral labour agreement provisions (rarely invoked), OECD National Contact Point complaints (against multinationals, non-binding), UN treaty body complaints (individual petitions, years to process), ILO Committee of Experts (state-level, not individual). No effective international mechanism for individual cross-border wage claims.",
        "source": "ILO / OHCHR / OECD",
    },
    {
        "type": "complaint",
        "jurisdiction": "QA",
        "title": "Qatar National Human Rights Committee (NHRC) Complaints",
        "summary": "NHRC accepts complaints from migrant workers regarding: labour rights violations, living conditions, access to justice. Investigates and refers to MoL or prosecution. Receives 3,000+ complaints annually. Can conduct surprise inspections of workplaces and accommodation. Limited enforcement power: recommendations only. Criticized for insufficient independence from government.",
        "source": "Qatar NHRC / ILO",
    },
    {
        "type": "complaint",
        "jurisdiction": "international",
        "title": "Common Complaint Categories by Destination Country",
        "summary": "Top complaint categories: SA — wage non-payment (35%), contract substitution (20%), physical abuse (15%). QA — wage theft (40%), accommodation (20%), heat exposure (15%). HK — rest day denial (30%), wage underpayment (25%), verbal abuse (20%). SG — salary deductions (35%), agency fee overcharge (25%), food inadequacy (15%). MY — passport confiscation (30%), wage withholding (25%), poor accommodation (20%).",
        "source": "ILO / National labour departments / NGO case data",
    },
]
