"""Landmark court rulings and legal precedents on trafficking and forced labour."""

COURT_RULING_FACTS: list[dict] = [
    # ── ECHR ──────────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "Rantsev v. Cyprus and Russia [2010] — Trafficking State Obligations",
        "court": "European Court of Human Rights",
        "year": 2010,
        "summary": "ECHR ruled that trafficking falls under Article 4 (prohibition of slavery/forced labour). States have positive obligation to: (1) establish legal/administrative framework, (2) protect identified victims, (3) investigate potential trafficking. Landmark for state responsibility.",
        "relevance": "Established that anti-trafficking obligations are part of human rights law, not just criminal law.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "Siliadin v. France [2005] — Domestic Servitude",
        "court": "European Court of Human Rights",
        "year": 2005,
        "summary": "Togolese girl brought to France as domestic servant, forced to work unpaid, passport confiscated. ECHR found France violated Article 4 by failing to have adequate criminal law provisions against servitude. Led to French law reform.",
        "relevance": "First ECHR ruling explicitly recognizing domestic servitude as prohibited under the Convention.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "Chowdury and Others v. Greece [2017] — Forced Labour of Migrants",
        "court": "European Court of Human Rights",
        "year": 2017,
        "summary": "Bangladeshi strawberry pickers in Greece shot at when demanding unpaid wages. ECHR found forced labour and trafficking. Greece failed to protect workers and investigate effectively. First ECHR judgment on labour trafficking.",
        "relevance": "Extended Article 4 protection to migrant agricultural workers; established that coercion need not be physical.",
    },

    # ── Hong Kong ─────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "HK",
        "title": "ZN v. Secretary for Justice [2020] — Trafficking Screening Obligation",
        "court": "High Court of Hong Kong",
        "year": 2020,
        "summary": "Court ruled Hong Kong must establish a screening mechanism to identify potential trafficking victims among arrested migrants. Government had relied on ad hoc assessments. Led to development of victim identification procedures.",
        "relevance": "First HK court recognition of obligation to screen for trafficking victims.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "HK",
        "title": "CB v. Commissioner of Police [2019] — Trafficking Framework",
        "court": "Court of First Instance, Hong Kong",
        "year": 2019,
        "summary": "Court found HK's existing legal framework insufficient to identify and protect trafficking victims. Ordered development of comprehensive anti-trafficking policy. Government responded with Action Plan to Tackle Trafficking (2018).",
        "relevance": "Established judicial basis for anti-trafficking policy reform in Hong Kong.",
    },

    # ── Singapore ─────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Lim Choon Hong and Chong Sui Foon [2016] — Starving Domestic Worker",
        "court": "State Courts of Singapore",
        "year": 2016,
        "summary": "Couple convicted of starving their Filipino domestic worker: victim weighed 29kg at rescue. Charged under EFMA and Penal Code. Sentenced to prison. Case prompted MOM to strengthen monitoring of domestic worker welfare.",
        "relevance": "Led to enhanced inspection protocols and mandatory rest-day provisions for domestic workers.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Gaiyathiri Murugayan [2021] — Domestic Worker Abuse Leading to Death",
        "court": "High Court of Singapore",
        "year": 2021,
        "summary": "Employer convicted of culpable homicide after systematically abusing Myanmar domestic worker who died. Sentenced to 30 years imprisonment. Documented 12 months of starvation, assault, and confinement.",
        "relevance": "Longest sentence for domestic worker abuse in Singapore. Established judicial severity for extreme cases.",
    },

    # ── United Kingdom ────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "UK",
        "title": "R v. Connors [2013] — GRT Forced Labour",
        "court": "Crown Court / Court of Appeal",
        "year": 2013,
        "summary": "Connors family convicted of forcing vulnerable homeless men to work on driveways/block paving for over 15 years. Victims recruited from streets and hostels. Subjected to violence and control. First major UK forced labour prosecution.",
        "relevance": "Demonstrated that forced labour can involve domestic victims, not just migrants.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "UK",
        "title": "Hounga v. Allen [2014] — Trafficking Victim Employment Rights",
        "court": "UK Supreme Court",
        "year": 2014,
        "summary": "Supreme Court held that a trafficking victim could bring employment discrimination claim despite having worked illegally. Public policy against trafficking outweighs illegality defense. Victim was a Nigerian teenager brought to UK as domestic worker.",
        "relevance": "Established that trafficking victims retain employment rights regardless of immigration status.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "UK",
        "title": "R v. SK [2011] — Domestic Servitude",
        "court": "Central Criminal Court (Old Bailey)",
        "year": 2011,
        "summary": "Saudi diplomat's assistant convicted of keeping Tanzanian woman as domestic servant. Victim confined, beaten, paid nothing. First prosecution under s.71 Coroners and Justice Act 2009 (holding a person in servitude).",
        "relevance": "First UK conviction specifically for holding a person in servitude.",
    },

    # ── United States ─────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "US",
        "title": "United States v. Kil Soo Lee [2003] — American Samoa Garment Factory",
        "court": "US District Court, Hawaii",
        "year": 2003,
        "summary": "Korean factory owner convicted of forced labour: 200+ Vietnamese and Chinese workers held in compound, beaten, starved, wages withheld. Sentenced to 40 years. Largest human trafficking case in US history at the time.",
        "relevance": "Established precedent for TVPA forced labour prosecutions in US territories.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "US",
        "title": "Bureerong v. Uvawas [1996] — Thai Garment Worker Trafficking",
        "court": "US District Court, Central District of California",
        "year": 1996,
        "summary": "72 Thai workers held in apartment complex in El Monte, CA, forced to sew garments 17 hours/day behind razor wire. Civil case resulted in USD 4M settlement. Led to anti-sweatshop legislation in California.",
        "relevance": "Landmark civil trafficking case that influenced TVPA enactment in 2000.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "US",
        "title": "David v. Signal International [2015] — Indian Worker H-2B Trafficking",
        "court": "US District Court, Eastern District of Louisiana",
        "year": 2015,
        "summary": "500 Indian workers recruited for post-Katrina rebuilding paid USD 10,000-25,000 in fees. Confined in labour camps, passports taken, threatened with deportation. Jury awarded USD 14M in damages.",
        "relevance": "Established that H-2B visa worker recruitment fees can constitute forced labour.",
    },

    # ── Australia ─────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v. Tang [2008] — Sexual Servitude Landmark",
        "court": "High Court of Australia",
        "year": 2008,
        "summary": "Brothel owner convicted of slavery offences against Thai women. High Court established that slavery in Australia requires control of a person exercised as property right. Set the legal standard for slavery prosecutions.",
        "relevance": "First High Court of Australia interpretation of slavery in criminal law context.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v. Kovacs [2008] — Construction Worker Trafficking",
        "court": "County Court of Victoria",
        "year": 2008,
        "summary": "Hungarian men trafficked to Australia for construction work. Debt bondage through inflated airfare and housing costs. Passports confiscated. Wages paid to trafficker. First Australian conviction for labour trafficking.",
        "relevance": "Demonstrated that labour trafficking occurs in developed-country construction sectors.",
    },

    # ── Philippines ───────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "PH",
        "title": "People v. Casio [2015] — Trafficking for Sexual Exploitation",
        "court": "Supreme Court of the Philippines",
        "year": 2015,
        "summary": "Supreme Court upheld conviction for trafficking in persons under RA 9208. Established that the victim's consent is irrelevant when any means of trafficking (deception, coercion, abuse of vulnerability) are used.",
        "relevance": "Strengthened anti-trafficking jurisprudence in the Philippines: consent is not a defense.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "PH",
        "title": "IACAT Administrative Sanctions on Recruitment Agencies (2023)",
        "court": "Inter-Agency Council Against Trafficking (IACAT)",
        "year": 2023,
        "summary": "IACAT revoked licenses of 47 recruitment agencies for violations including excessive fee charging, contract substitution, and deployment to non-verified employers. Largest single enforcement action against illegal recruitment.",
        "relevance": "Demonstrated increased enforcement capacity of Philippine anti-trafficking institutions.",
    },

    # ── Thailand ──────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "TH",
        "title": "Rong Poh Fishing Case [2016] — Fishing Industry Prosecution",
        "court": "Criminal Court of Thailand",
        "year": 2016,
        "summary": "Conviction of fishing vessel operators for trafficking of Myanmar and Cambodian workers. Forced labour on vessels for months. Prompted Thailand's fishing industry reforms. Part of response to EU yellow card.",
        "relevance": "Landmark prosecution demonstrating Thailand's commitment to fishing sector reform.",
    },

    # ── Qatar ─────────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "QA",
        "title": "Labour Dispute Resolution Committee Wage Recovery (2021-2023)",
        "court": "Qatar Labour Dispute Resolution Committees",
        "year": 2023,
        "summary": "Qatar's Labour Dispute Resolution Committees processed 35,000+ cases (2021-2023), recovering QAR 1.8 billion in unpaid wages. Fast-track process: 3-week resolution. Covers all workers including domestic. Major reform achievement.",
        "relevance": "Demonstrates operational effectiveness of Qatar's post-reform dispute resolution system.",
    },

    # ── Additional Court Rulings (expanded) ──────────────────────────
    # ── United States ────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "US",
        "title": "US v. Kil Soo Lee [2003] — American Samoa Garment Factory",
        "court": "US District Court, District of Hawaii",
        "year": 2003,
        "summary": "Vietnamese and Chinese workers trafficked to Daewoosa garment factory in American Samoa. 200+ workers subjected to forced labour: beatings, food deprivation, confinement. Lee convicted of involuntary servitude, extortion, money laundering. Sentenced to 40 years imprisonment. Workers awarded USD 3.5M in restitution. One of the largest forced labour convictions in US history.",
        "relevance": "Established federal prosecution template for large-scale forced labour operations in US territories.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "US",
        "title": "David v. Signal International [2015] — H-2B Worker Trafficking",
        "court": "US District Court, Eastern District of Louisiana",
        "year": 2015,
        "summary": "500+ Indian workers recruited for Signal International shipyard post-Hurricane Katrina. Paid USD 10,000-25,000 to recruiters promised green cards, received H-2B temporary visas. Jury found forced labour, fraud, racketeering. USD 14M verdict. Signal International filed bankruptcy. Landmark case establishing recruiter liability for deceptive H-2B practices.",
        "relevance": "Set precedent that recruiters and employers jointly liable for H-2B worker exploitation.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "US",
        "title": "EEOC v. Global Horizons [2014] — Thai Farm Workers",
        "court": "US District Court, District of Hawaii",
        "year": 2014,
        "summary": "EEOC filed discrimination complaint on behalf of 600+ Thai workers recruited by Global Horizons for US farms. Workers paid USD 9,500-21,000 to brokers, passports confiscated, confined to farm housing. DOJ criminal case (largest trafficking indictment at time) partially dismissed. EEOC civil case: USD 8.5M settlement. Global Horizons CEO convicted of trafficking conspiracy.",
        "relevance": "Demonstrated EEOC jurisdiction over trafficking-related employment discrimination against foreign workers.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "US",
        "title": "Bureerong v. Uvawas [1996] — El Monte Thai Garment Workers",
        "court": "US District Court, Central District of California",
        "year": 1996,
        "summary": "72 Thai workers held in barbed-wire compound in El Monte, California, producing garments for major retailers. Workers paid USD 0.60/hour, 18-hour shifts, imprisoned for up to 7 years. FBI raid freed workers (1995). Civil suit against manufacturers and retailers for benefiting from sweatshop labour. Settlement with multiple defendants. Led to California AB 633 (garment worker protection).",
        "relevance": "Pioneered supply chain liability theory: brands that benefit from forced labour can be held accountable.",
    },
    # ── India ────────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "IN",
        "title": "Bandhua Mukti Morcha v. Union of India [1984] — Bonded Labour",
        "court": "Supreme Court of India",
        "year": 1984,
        "summary": "PIL case brought by Bandhua Mukti Morcha (Bonded Labour Liberation Front). Supreme Court held: bonded labour is a violation of Articles 21 and 23 of the Constitution, state has obligation to identify and release bonded labourers and provide rehabilitation. Directed government to enforce Bonded Labour System (Abolition) Act 1976. Broadened definition of bonded labour to include economic compulsion.",
        "relevance": "Landmark constitutional interpretation making state responsible for bonded labour eradication.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "IN",
        "title": "PUCL v. State of Tamil Nadu [2004] — Child Labour in Silk Industry",
        "court": "Supreme Court of India",
        "year": 2004,
        "summary": "Public interest litigation documenting child labour in Tamil Nadu silk reeling and cotton spinning industries. Court directed: rescue of child workers, rehabilitation (education, stipend), prosecution of employers, periodic compliance reports. Established pattern of judicial monitoring of child labour in specific sectors.",
        "relevance": "Demonstrated judicial monitoring as tool for child labour elimination in specific industries.",
    },
    # ── Brazil ───────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "BR",
        "title": "Brazil Lista Suja (Dirty List) Constitutional Challenge [2017]",
        "court": "Supreme Federal Court of Brazil (STF)",
        "year": 2017,
        "summary": "Brazil's Dirty List (Cadastro de Empregadores que tenham submetido trabalhadores a condições análogas à de escravo) — public list naming employers caught using forced labour — challenged as unconstitutional. STF upheld list (2017) as proportionate measure. Listed employers face: government contract ban, restricted credit access, supply chain exclusion. 53,000+ workers rescued since 1995. Most effective forced labour accountability tool in any country.",
        "relevance": "Validated public naming and shaming as constitutional and effective forced labour deterrent.",
    },
    # ── Israel ───────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "IL",
        "title": "Kav LaOved — High Court Rulings on Binding Arrangement",
        "court": "High Court of Justice (Israel)",
        "year": 2006,
        "summary": "Series of Kav LaOved (Worker's Hotline) petitions challenging Israel's 'binding arrangement' (employer-tied work permit). High Court ruled binding arrangement violated workers' liberty and constituted modern slavery characteristics (2006). Led to reforms allowing limited employer change. 200,000+ migrant workers (Thai agriculture, Chinese construction, Filipino caregivers) affected.",
        "relevance": "Judicial recognition that employer-tied visa systems can constitute modern slavery.",
    },
    # ── Japan ────────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "JP",
        "title": "TITP Trainee Runaways — Japanese Court Precedent on Employer Change",
        "court": "Various District Courts (Japan)",
        "year": 2020,
        "summary": "Series of Japanese court cases involving TITP trainees who left employers due to abuse. Courts increasingly ruling that: trainees who leave abusive employers are not in breach of contract, employers who confiscate passports or impose illegal work conditions forfeit right to damages, trainees can claim unpaid overtime. OTIT data: 9,000+ trainees 'disappeared' from employers (2019), many due to abuse.",
        "relevance": "Evolving Japanese jurisprudence recognizing TITP workers' right to leave abusive placements.",
    },
    # ── Malaysia ─────────────────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "MY",
        "title": "Malaysian Court on Forced Labour in Electronics Sector",
        "court": "Malaysian Industrial Court",
        "year": 2021,
        "summary": "Multiple Industrial Court cases involving Nepali and Bangladeshi workers in Malaysian electronics factories. Court ruled: recruitment fees deducted from wages constitute forced labour indicator, passport retention is criminal offense (Employment Act 1955 §60L), forced overtime beyond Employment Act limits voids consent. Awards include back pay for illegal deductions. Few criminal prosecutions despite court findings.",
        "relevance": "Established that recruitment fee deduction from wages constitutes forced labour indicator in Malaysian law.",
    },
    # ── ICC / International ──────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "ICC Situation in Libya — Migrant Detention as Crime Against Humanity",
        "court": "International Criminal Court",
        "year": 2021,
        "summary": "ICC Prosecutor opened investigation into crimes against migrants in Libya: enslavement, torture, sexual violence, persecution in detention centres. Arrest warrant issued against al-Werfalli (subsequently killed). Investigation ongoing into DCIM officials and militia leaders. First ICC case focused specifically on crimes against migrants. Could establish precedent for international prosecution of migrant exploitation.",
        "relevance": "First ICC investigation focused on crimes against migrants, potentially establishing new international norms.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "IACtHR Advisory Opinion OC-21/14 — Rights of Migrant Children",
        "court": "Inter-American Court of Human Rights",
        "year": 2014,
        "summary": "Advisory opinion establishing that: migrant children have right to non-detention based on immigration status, best interests of child must prevail over immigration enforcement, states must provide access to education and healthcare regardless of migration status. Applicable to 23 states under IACtHR jurisdiction. Referenced by courts in Argentina, Mexico, Costa Rica.",
        "relevance": "Established regional human rights standard for treatment of migrant children.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "UK",
        "title": "R v. Rooney and Others [2010] — Irish Traveller Forced Labour",
        "court": "Luton Crown Court (England)",
        "year": 2010,
        "summary": "Connors/Rooney family convicted of conspiracy to require persons to perform forced labour. Trafficked vulnerable British men (homeless, learning disabilities) for block paving/driveway work. Workers lived in caravans, beaten, paid nothing, held for years. Sentences: 2-10 years imprisonment. First major UK prosecution under Section 71 Coroners and Justice Act 2009.",
        "relevance": "First successful UK prosecution for forced labour of domestic victims (not cross-border trafficking).",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "UK",
        "title": "Hounga v. Allen [2014] — Trafficking Victim Employment Rights",
        "court": "UK Supreme Court",
        "year": 2014,
        "summary": "Nigerian minor trafficked to UK, employed as domestic servant. Dismissed, filed unfair dismissal claim. Employment Tribunal ruled illegality defence (no work visa) barred claim. Supreme Court reversed: trafficking victims cannot be denied employment protections due to illegality of their immigration status. Defence of illegality incompatible with anti-trafficking obligations.",
        "relevance": "Established that trafficking victims retain employment rights regardless of immigration status.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "NL",
        "title": "Netherlands Curaçao Phosphate Mining — Modern Slavery Finding",
        "court": "Court of Appeal, The Hague",
        "year": 2019,
        "summary": "Dutch court found modern slavery conditions in phosphate mining operations on Curaçao (Dutch territory). Workers from Dominican Republic and Haiti exploited: 16-hour shifts, deductions for housing and food exceeding wages, restriction of movement, threats of deportation. Court applied Palermo Protocol definitions. Employer convicted. Highlighted forced labour in Dutch overseas territories.",
        "relevance": "Applied international trafficking definitions to exploitation in European overseas territories.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "TH",
        "title": "Kantang Human Trafficking Case [2017] — Fishing Industry Prosecution",
        "court": "Criminal Court, Trang Province (Thailand)",
        "year": 2017,
        "summary": "Prosecution of trafficking network operating fishing vessels from Kantang port. Defendants included vessel operators, brokers, and government officials (harbourmaster). Myanmar and Cambodian workers forced to work on vessels for months. Physical violence, food deprivation. 8 defendants convicted, sentences up to 14 years. First Thai case convicting government officials for complicity in fishing trafficking.",
        "relevance": "Established that government officials can be prosecuted as complicit in fishing sector trafficking.",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "PH",
        "title": "People v. XXX — Large-Scale Illegal Recruitment Conviction",
        "court": "Regional Trial Court (Philippines)",
        "year": 2022,
        "summary": "Pattern of Philippine RTC convictions for large-scale illegal recruitment (RA 8042/10022): agency operators convicted for recruiting 3+ workers with fraudulent job offers. Sentences: life imprisonment + PHP 2-5M fine (economic sabotage classification). IACAT (Inter-Agency Council Against Trafficking) coordinates prosecution. Annual convictions: 50-100 recruiters. However, thousands of cases pending with slow court processing.",
        "relevance": "Demonstrated Philippines' aggressive prosecution of illegal recruiters under economic sabotage classification.",
    },
]
