"""Restriction of movement — locked dormitories, curfews, and confinement patterns."""

FREEDOM_OF_MOVEMENT_FACTS: list[dict] = [
    # ── International Standards ─────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Indicator — Restriction of Movement",
        "summary": "Restriction of movement is one of 11 ILO indicators of forced labour. Includes: locking workers in workplace or living quarters, constant surveillance, accompaniment required when outside, confining workers to compound, denying workers right to leave premises freely. Applies to both workplace and accommodation.",
        "source": "ILO Indicators of Forced Labour (2012)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ICCPR Article 12 — Freedom of Movement",
        "summary": "International Covenant on Civil and Political Rights (Art. 12) guarantees freedom of movement and freedom to leave any country. Lawfully present persons have right to liberty of movement and choice of residence. Restrictions permitted only if provided by law, necessary for national security, public order, or rights of others. Employer-imposed restrictions have no legal basis under international law.",
        "source": "UN OHCHR / ICCPR (1966)",
    },
    # ── Domestic Workers ────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Domestic Worker Confinement in Employer Homes",
        "sector": "domestic_work",
        "exploitation_type": "restriction_of_movement",
        "summary": "Human Rights Watch (2022) documented systematic confinement of domestic workers: locked inside employer homes, denied rest days, not allowed to leave without employer or family member accompaniment, phone confiscated. Workers who escape are charged with 'absconding'. Embassy shelters in Riyadh house 500+ workers fleeing confinement at any time.",
        "source": "Human Rights Watch / Philippines Overseas Labor Office",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon — Locked Apartment Syndrome",
        "sector": "domestic_work",
        "exploitation_type": "restriction_of_movement",
        "summary": "Common pattern in Lebanon: domestic workers locked inside employer apartments during work hours and at night. Cannot leave even on designated day off. Employers justify as 'protection' or 'security'. Pattern linked to multiple worker deaths from falls attempting to escape through windows. Anti-Racism Movement Lebanon documented 300+ cases annually.",
        "source": "Anti-Racism Movement Lebanon / ILO Beirut",
    },
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "Kuwait — Domestic Worker Isolation and Surveillance",
        "sector": "domestic_work",
        "exploitation_type": "isolation",
        "summary": "Kuwait Society for Human Rights survey (2021): 65% of domestic workers reported being denied a weekly day off, 40% never allowed to leave the house unaccompanied, 25% reported having CCTV in their bedroom. Workers from Philippines and Ethiopia most affected. Recent regulations (Domestic Workers Law 2015) mandate weekly rest but enforcement is employer self-reporting.",
        "source": "Kuwait Society for Human Rights / Migrant-Rights.org",
    },
    # ── Labour Camps ────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Qatar — Construction Worker Compound Restrictions",
        "sector": "construction",
        "exploitation_type": "restriction_of_movement",
        "summary": "Workers housed in remote labour camps (Industrial Area, Al Khor) with restricted movement: buses only to worksite and back, no public transport access, camps fenced with guard checkpoints, curfews after 10pm. Workers depend on employer for food and transport. Some camps located 40km+ from Doha with no independent transport options.",
        "source": "Amnesty International / Business & Human Rights Resource Centre",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE — Labour Camp Curfews and Movement Controls",
        "sector": "construction",
        "exploitation_type": "restriction_of_movement",
        "summary": "UAE construction worker camps operate curfew systems: workers must return by 9-10pm, sign in/out logs, ID checks at entry. Camps in Saadiyat Island (Louvre Abu Dhabi, Guggenheim projects) documented by HRW: workers confined during non-work hours, no private transport, limited phone access. Post-2017 reforms improved some conditions but structural isolation remains.",
        "source": "Human Rights Watch / NYU Abu Dhabi Project Report / ITUC",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Singapore — Foreign Worker Dormitory Restrictions (COVID-19)",
        "sector": "construction",
        "exploitation_type": "restriction_of_movement",
        "summary": "COVID-19 revealed extreme conditions in Singapore foreign worker dormitories: 300,000+ workers confined to dorms during lockdown (Apr-Dec 2020), 17 per room, shared toilets for 100+, 60% infection rate. Post-COVID: new Standards of Accommodation Regulations (2022) mandate max 12 per room, personal space requirements. Workers still face movement restrictions on rest days.",
        "source": "Transient Workers Count Too (TWC2) / Singapore MOM",
    },
    # ── Agricultural and Fishing ────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "TH",
        "title": "Thailand — Fishing Vessel Confinement at Sea",
        "sector": "fishing",
        "exploitation_type": "restriction_of_movement",
        "summary": "Workers on Thai fishing vessels kept at sea for months to years through 'transshipment' — transferring catch to cargo vessels without returning to port. Workers cannot leave, communicate with family, or access authorities. ILO survey: 33% of fishers unable to leave vessel when they wanted. Some workers not allowed on shore even when vessel docks for repairs.",
        "source": "ILO / Environmental Justice Foundation / Greenpeace",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "Malaysia — Plantation Worker Movement Restrictions",
        "sector": "palm_oil",
        "exploitation_type": "restriction_of_movement",
        "summary": "Palm oil plantation workers in Sabah and Sarawak (Malaysian Borneo) face geographic isolation: plantations in remote areas with no public transport, nearest town 50-100km away, employer-controlled transport. Workers need permission to leave estate. Undocumented Indonesian workers face arrest at police checkpoints. Sime Darby, FGV plantations documented by Amnesty.",
        "source": "Amnesty International / Verité / Rainforest Action Network",
    },
    {
        "type": "case_study",
        "jurisdiction": "IT",
        "title": "Italy — Ghetto System for Agricultural Migrant Workers",
        "sector": "agriculture",
        "exploitation_type": "restriction_of_movement",
        "summary": "African migrant workers in southern Italy's agricultural sector housed in informal settlements (ghettos) controlled by caporali (gangmasters). Workers depend on caporali for transport to fields, food, and water — all at inflated prices deducted from pay. Geographic isolation and lack of transport create de facto confinement. Foggia, Rosarno, and Calabria regions most affected.",
        "source": "FLAI-CGIL / Medici Senza Frontiere / Ferrara University",
    },
    # ── Surveillance and Control ────────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "GPS Tracking and Digital Surveillance of Migrant Workers",
        "summary": "Emerging pattern: employers use GPS tracking via company phones, worker apps, or ankle monitors. CCTV in worker accommodation and workplaces. Social media monitoring. Digital surveillance supplements physical restrictions. Workers unaware of tracking or unable to refuse employer-provided devices. No international standards yet addressing digital monitoring of workers.",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Isolation Techniques Beyond Physical Restriction",
        "summary": "Non-physical isolation methods: (1) linguistic isolation — placing worker where no one speaks their language, (2) information isolation — denying access to news, phone, internet, (3) social isolation — prohibiting contact with other workers or community, (4) geographical isolation — remote worksites far from authorities, (5) cultural isolation — preventing religious practice or cultural activities.",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Rest Day Denial as Movement Restriction",
        "summary": "Denying mandatory weekly rest day effectively restricts movement: worker cannot visit embassy, contact lawyer, attend religious services, send remittances, or socialise. ILO survey across GCC: 44% of domestic workers reported never receiving a rest day. Even where rest day laws exist, 'voluntary' overtime pressure or employer expectations prevent workers from leaving.",
        "source": "ILO / Migrant Forum in Asia",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Prevalence of Movement Restrictions in Forced Labour",
        "metric": "movement_restriction_prevalence",
        "value": "68%",
        "summary": "ILO Global Estimates (2022): restriction of movement present in 68% of forced labour cases involving migrants. Second only to document retention (78%) as most common indicator. Higher in domestic work (82%) and fishing (79%) due to live-in/on-board conditions. Physical confinement (locked premises) present in 23% of cases.",
        "source": "ILO Global Estimates of Modern Slavery (2022)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Protocol of 2014 — Forced Labour and Restriction of Movement",
        "summary": "ILO Protocol P029 (2014) to the Forced Labour Convention requires states to take measures including: protecting victims from punishment for unlawful activities they were compelled to commit while trafficked, ensuring victims have access to remedies, and preventing employer retaliation. Recognises restriction of movement as a defining element of forced labour requiring criminal sanctions.",
        "source": "ILO NORMLEX / 50 for Freedom Campaign",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "USA — Agricultural Workers Under H-2A Visa Movement Constraints",
        "sector": "agriculture",
        "exploitation_type": "restriction_of_movement",
        "summary": "H-2A temporary agricultural workers tied to single employer; cannot change jobs. Housed in employer-provided accommodation, often in rural areas without transport. Workers who leave face visa revocation and deportation. DOJ cases (2020-2023) include: employers confiscating vehicle keys, threatening workers who leave housing at night, charging fees for transport to town.",
        "source": "US DOJ / Polaris Project / Centro de los Derechos del Migrante",
    },
]
