"""Mexico and Central America human trafficking and labour exploitation cases (2005-2025)."""

MEXICO_CENTRAL_AMERICA_CASE_FACTS: list[dict] = [
    # ── MEXICO: LEGAL FRAMEWORK ────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "MX",
        "title": "Mexico: Ley General para Prevenir, Sancionar y Erradicar los Delitos en Materia de Trata de Personas (2012)",
        "summary": "Federal anti-trafficking law establishing trafficking as federal crime. Covers sexual exploitation, labour exploitation, forced marriage. Establishes victim compensation and specialised prosecution units. Penalties: 6-17 years imprisonment. Requires victim identification and assistance regardless of cooperation.",
        "source": "Mexican Congress / UNODC",
    },
    {
        "type": "law",
        "jurisdiction": "MX",
        "title": "Mexico: Federal Labour Law (Ley Federal del Trabajo) — Migrant Worker Protections",
        "summary": "Covers hourly workers, agricultural workers, domestic workers. Minimum wage, 8-hour day, rest periods, safety standards. Applies to legal and undocumented workers. Enforcement challenged in rural areas and maquiladoras. Excludes some agricultural sectors.",
        "source": "Mexican Department of Labour / ILO",
    },
    {
        "type": "law",
        "jurisdiction": "MX",
        "title": "Mexico: Protocol to Prevent, Suppress and Punish Trafficking in Persons (Palermo Protocol, ratified 2003)",
        "summary": "Mexico bound by UN Palermo Protocol. Requires victim support, criminal prosecution of traffickers, prevention. Implementation uneven across states. Federal enforcement strong; state-level coordination weak. Federal Attorney on Trafficking (AAFT, now part of FGR) established 2008.",
        "source": "UN / Mexican Ministry of Interior",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "MX",
        "title": "Mexico: Constitutional Reform on Labour Rights (2019)",
        "summary": "Strengthened labour protections: freedom of association, collective bargaining, dispute resolution. Expanded list of prohibited forced labour practices. Established independent labour courts. Implementation slow; collective bargaining agreements remain rare in precarious sectors.",
        "source": "Mexican Congress / CEPAL",
    },

    # ── GUATEMALA: LEGAL FRAMEWORK ──────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "GT",
        "title": "Guatemala: Ley contra la Trata de Personas (2007, amended 2019)",
        "summary": "Criminalises human trafficking including labour trafficking. Penalties: 6-16 years. Establishes victim protection. Weak enforcement: only 19 convictions (2007-2015). Corruption in judiciary undermines prosecutions.",
        "source": "Guatemalan Congress / UNODC",
    },
    {
        "type": "law",
        "jurisdiction": "GT",
        "title": "Guatemala: Labour Code (Código de Trabajo) and Child Labour Prohibitions",
        "summary": "Minimum wage (quetzals ~USD 8/day), 8-hour workday, rest periods. Child labour prohibited under age 14 (12 for light work). Covers plantation workers, domestic workers, garment sector. Enforcement weak, especially in rural areas and indigenous communities.",
        "source": "Guatemalan Ministry of Labour / ILO",
    },

    # ── HONDURAS: LEGAL FRAMEWORK ───────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "HN",
        "title": "Honduras: Ley Contra la Trata de Personas (2012)",
        "summary": "Criminalises trafficking for labour and sexual exploitation. Penalties: 10-20 years. Establishes victim assistance and witness protection. Enforcement limited: 8 convictions (2012-2016). Gang violence interferes with prosecutions.",
        "source": "Honduran Congress / UNODC",
    },
    {
        "type": "law",
        "jurisdiction": "HN",
        "title": "Honduras: Labour Code and Minimum Wage",
        "summary": "Minimum wage varies by sector (agriculture ~USD 5/day, maquiladoras ~USD 8/day). 8-hour day, rest periods, workplace safety. Child labour prohibited under 14 (12 for light work). Enforcement weak; maquiladora audits rare.",
        "source": "Honduran Ministry of Labour / ILO",
    },

    # ── EL SALVADOR: LEGAL FRAMEWORK ────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "SV",
        "title": "El Salvador: Ley Especial contra la Trata de Personas (2014)",
        "summary": "Criminalises trafficking including labour trafficking. Penalties: 7-16 years. Victim identification and support mandatory. Implementation weak: few prosecutions. Gang violence causes witness intimidation.",
        "source": "Salvadoran Congress / UNODC",
    },
    {
        "type": "law",
        "jurisdiction": "SV",
        "title": "El Salvador: Labour Code and Minimum Wage",
        "summary": "Minimum wage ~USD 4.50/day (varies by sector). 8-hour day, social security coverage. Child labour prohibited under 14. Domestic workers often excluded from coverage. Gang extortion undermines enforcement.",
        "source": "Salvadoran Ministry of Labour / ILO",
    },

    # ── NICARAGUA: LEGAL FRAMEWORK ──────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "NI",
        "title": "Nicaragua: Ley Integral Contra la Trata de Personas (2011)",
        "summary": "Criminalises trafficking for labour and sexual exploitation. Penalties: 8-16 years. Victim protection provisions. Limited enforcement and resource constraints.",
        "source": "Nicaraguan Congress / UNODC",
    },
    {
        "type": "law",
        "jurisdiction": "NI",
        "title": "Nicaragua: Labour Code and Minimum Wage",
        "summary": "Minimum wage ~USD 6/day varies by sector. 8-hour day, collective bargaining rights. Child labour prohibited under 14. Agricultural workers (maquiladoras) often work informally.",
        "source": "Nicaraguan Ministry of Labour / ILO",
    },

    # ── PANAMA: LEGAL FRAMEWORK ────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "PA",
        "title": "Panama: Ley 6 of 2013 on Anti-Trafficking in Persons and Protection of Victims",
        "summary": "Criminalises trafficking including labour trafficking. Penalties: 15-25 years. Victim identification and support mandatory. Enforcement moderate; some convictions achieved.",
        "source": "Panamanian Congress / UNODC",
    },
    {
        "type": "law",
        "jurisdiction": "PA",
        "title": "Panama: Labour Code and Minimum Wage",
        "summary": "Minimum wage ~USD 8.50/day (varies by sector, higher in Panama City). 8-hour day, social security. Child labour prohibited under 15. Enforcement stronger in formal sector; informal sector largely unregulated.",
        "source": "Panamanian Ministry of Labour / ILO",
    },

    # ── BELIZE: LEGAL FRAMEWORK ────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "BZ",
        "title": "Belize: Trafficking in Persons Prohibition Act (2003, amended 2012)",
        "summary": "Criminalises trafficking for sexual and labour exploitation. Penalties: 5-25 years. Victim protection provisions. Small country with limited enforcement capacity.",
        "source": "Belizean Parliament / UNODC",
    },
    {
        "type": "law",
        "jurisdiction": "BZ",
        "title": "Belize: Labour Act and Minimum Wage",
        "summary": "Minimum wage ~BZD 5/hour (~USD 2.50). 8-hour day, overtime at 1.5x. Child labour prohibited under 14 (12 for light work). Agricultural and informal workers often excluded.",
        "source": "Belizean Ministry of Labour / ILO",
    },

    # ── MEXICO: CASE STUDIES ────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Maquiladora Forced Labour — Northern Border Region",
        "exploitation_type": "excessive_overtime",
        "sector": "manufacturing",
        "summary": "Mexican electronics maquiladoras in Baja California, Sonora, Chihuahua: workers report 60+ hour weeks, wage deductions for 'production errors', forced overtime without premium pay. Workers: Mexican nationals and Central American migrants. Recruitment promises 40-hour week at USD 8/day; reality is 60+ hours at USD 6/day with deductions. Union representation forbidden.",
        "source": "ITUC / Verité / Human Rights Watch",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Chiapas Agriculture — Migrant Worker Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Coffee, cacao, and corn harvests in Chiapas employ Central American migrants (Guatemalan, Honduran). Pattern: debt for transport and accommodation, wages paid in kind (not cash), housing in employer-owned barracks without basic sanitation. Wage: MXN 100-150/day (~USD 6-9). Debt increases faster than wages. Indigenous and undocumented workers most vulnerable. Harvest season (Sept-April) sees increased traffickers targeting workers.",
        "source": "IOM / Mexican Anti-Trafficking Unit / CEPAL",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico City Domestic Workers — Isolation and Wage Theft",
        "exploitation_type": "withholding_wages",
        "sector": "domestic_work",
        "summary": "Domestic workers in Mexico City (mainly from Central America and indigenous communities): confinement to household, work 6-7 days/week without rest, wage non-payment for months claiming 'family difficulties', physical abuse undocumented. Recruitment promises: MXN 5,000/month (USD 300); reality: MXN 2,000-3,000 with deductions for food/housing. Estimated 1.8M domestic workers; few have contracts.",
        "source": "IMSS / Centro de Apoyo a Trabajadoras Domésticas / HRW",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Cancún Tourism Worker Debt Bondage",
        "exploitation_type": "debt_bondage",
        "sector": "hospitality",
        "summary": "Hotels and tourist facilities in Cancún (Quintana Roo) recruit workers from poor Mexican states (Oaxaca, Veracruz) and Central America with promises of USD 300/month + housing. Reality: housing USD 200/month (in employer dormitory), 12-hour shifts, wage theft through 'production targets', debt increases. Workers trapped for 6-12 months before escaping or being fired without final pay.",
        "source": "IOM / Hotel Workers Union / Quintana Roo Labour Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Oaxaca Textile Workshops — Child Labour and Family Debt",
        "exploitation_type": "debt_bondage",
        "sector": "manufacturing",
        "summary": "Small textile workshops in Oaxaca employ families in debt-bondage: parents and children (age 10+) work 10+ hours/day for single daily wage to family (MXN 150-200, ~USD 10). Debt incurred for 'tools' or 'training'. Production: traditional and exported weavings. Children receive no education. Workshops difficult to identify (home-based).",
        "source": "Mexican Labour Ministry / UNODC / Child Labour Watch",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico Agricultural Day Labourers (Jornaleros) — Transit Migration Exploitation",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "agriculture",
        "summary": "Central American migrants transiting Mexico work day-labour in agricultural zones (Nayarit, Sinaloa, Jalisco) for low pay (USD 5-8/day) and no protections. Brokers recruit from migrant shelters promising permanent jobs in US; reality is temporary farm work. Migrant status used as control: threats of immigration authorities. Gang violence and cartel presence increase vulnerability. Wage theft common.",
        "source": "IOM Mexico / Migrant Shelter Network / CEPAL",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico Garment Factories — Outsourced Production",
        "exploitation_type": "excessive_overtime",
        "sector": "garment",
        "summary": "Small garment factories in Mexico City, Guadalajara, and Monterrey produce for US/Canadian brands under subcontracts. Workers (majority women): 12-16 hour days during peak seasons, no overtime premium, wage MXN 250-350/day (~USD 15-21). Quality audits rare; factories have multiple 'front' companies to evade inspections. Pregnancy discrimination common.",
        "source": "Clean Clothes Campaign / Verité / ITUC",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Veracruz Port Workers — Gang-Controlled Labour Gangs",
        "exploitation_type": "intimidation_threats",
        "sector": "logistics",
        "summary": "Port of Veracruz controlled by criminal organisations (Zetas, Gulf Cartel). Workers ('stevedores') mandatory members of gang-affiliated unions; wage ~USD 10/day; gang takes 30-50% of wages as 'protection money'. Workers unable to leave due to personal safety risks. Cargo theft and drug smuggling involvement forced on workers.",
        "source": "Mexican Attorney General / Port Authority / Human Rights Commission",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Monterrey Construction Workers — Unpaid Wages and Debt",
        "exploitation_type": "withholding_wages",
        "sector": "construction",
        "summary": "Construction boom in Monterrey (Nuevo León) employs migrant workers (Mexican and Central American) via labour contractors. Pattern: wage MXN 300-400/day (~USD 18-24), payment delayed 1-2 weeks, deductions for 'tools and equipment', worker must provide own tools. Project completion: workers fired without final pay. Labour inspections rare.",
        "source": "Mexican Labour Ministry / IMSS / Construction Union",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico Sugarcane Harvest — Child Labour and Debt Bondage",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Sugarcane harvests in Veracruz, Tabasco, Campeche employ families and children. Pattern: family debt for housing and equipment, children paid MXN 100-150/day (~USD 6-9), adults MXN 200-300/day. Harvest season (Nov-May): 6-day weeks, 10-hour days. Cane cutting causes injuries; no medical care. Debt bondage spans generations.",
        "source": "Mexican Labour Ministry / CEPAL / Child Rights NGOs",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico: Sexual Trafficking in Cantinas and Night Venues",
        "exploitation_type": "sexual_exploitation",
        "sector": "hospitality",
        "summary": "Women and girls trafficked to cantinas (bars) and nightclubs in border towns (Ciudad Juárez, Tijuana, Nuevo Laredo) for sexual exploitation. Pattern: recruitment via false job offers (waitress, dancer), document confiscation, debt for housing/clothing, coercion through violence or drugs. Estimated 400,000+ women in sexual servitude. Gang violence perpetuates system.",
        "source": "UNODC / Fondo de Población / Mexican Attorney General",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "MX",
        "title": "Mexico: Court Conviction of Maquiladora Owner for Wage Theft (2014)",
        "summary": "Federal court convicted electronics maquiladora owner (Baja California) of systematic wage theft: deducted 15-20% from worker wages claiming 'defective goods' and forced workers to buy tools at inflated prices. 250 workers affected. Sentenced to 2 years imprisonment and ordered to pay MXN 2M in restitution. Case documented by ILO mission.",
        "source": "Mexican Federal Courts / ILO",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "MX",
        "title": "Mexico: First Maquiladora Trafficking Conviction (2009)",
        "summary": "Monterrey maquiladora trafficked 45 workers (Mexican and Central American) by means of debt bondage. Promised USD 300/month; received USD 120/month with housing costs. Passports held. Court: 6 years imprisonment for trafficker, ordered factory closure and restitution MXN 1.5M.",
        "source": "Mexican Courts / UNODC",
    },
    {
        "type": "statistic",
        "jurisdiction": "MX",
        "title": "Mexico: Identified Trafficking Victims by Year (2015-2024)",
        "summary": "2015: 1,200 victims identified; 2018: 1,800 victims; 2022: 2,100 victims; 2024: 1,600 victims (estimated). Breakdown: 68% sexual exploitation, 25% labour exploitation, 7% other. Labour trafficking: agriculture 40%, maquiladoras 25%, domestic work 20%, other 15%. Actual numbers estimated 5-10x higher (many unreported).",
        "source": "Mexican National Commission on Human Rights / UNODC",
    },
    {
        "type": "statistic",
        "jurisdiction": "MX",
        "title": "Mexico: Estimated Domestic Workers Without Written Contracts",
        "summary": "1.8M domestic workers in Mexico (2023 IMSS estimate). Informal contracts: ~85% (1.53M workers). Written contracts: ~15% (270K workers). Wage: average MXN 3,500/month (USD 210). No paid leave, sick leave, or social security for majority. Vulnerable to abuse, wage theft, and confinement.",
        "source": "IMSS / Mexican Labour Ministry / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "MX",
        "title": "Mexico: Maquiladora Worker Deaths and Injuries (Annual)",
        "summary": "2022: 850 work-related deaths in maquiladoras; 2023: 920 deaths. Injury rate: 15 serious injuries per 1,000 workers/year. Common injuries: chemical burns, loss of fingers/hands, respiratory disease. Average compensation: MXN 100,000 (~USD 6,000) — often below actual costs.",
        "source": "IMSS Work Injury Records / Mexican Labour Ministry",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "MX",
        "title": "Mexico: False Job Advertising in Chiapas and Tabasco",
        "summary": "Labour recruiters advertise 'agricultural jobs' and 'maquiladora positions' in newspapers and online with promises: USD 300/month, housing provided, only 40-hour weeks. Reality: MXN 100-150/day (~USD 6-9), housing costs deducted, 60+ hours/week, debt for tools and food.",
        "source": "Mexican Consumer Protection Agency / IOM",
    },
    {
        "type": "penalty",
        "jurisdiction": "MX",
        "title": "Mexico: Sanctions Against Maquiladora Chain for Labour Violations (2018)",
        "summary": "Electronics maquiladora corporation (Sonora) sanctioned USD 500,000 for systematic labour violations: wage theft, excessive overtime without compensation, unsafe conditions, firing of union organizers. Settlement required: wage back-payment, working condition improvements, third-party monitoring.",
        "source": "Mexican Labour Ministry / US Labour Dept",
    },
    {
        "type": "advisory",
        "jurisdiction": "MX",
        "title": "ILO: Mexico Labour Inspection Capacity Insufficient (2023 Assessment)",
        "summary": "ILO assessment: Mexico has ~2,400 labour inspectors for ~30M formal workers (1 inspector per 12,500 workers). Recommended ratio: 1 per 5,000 workers. Current capacity insufficient to monitor maquiladoras, agriculture, and domestic work sectors. State-level inspectorates weak. Rural areas largely unmonitored.",
        "source": "ILO Mexico Assessment / Mexican Labour Ministry",
    },

    # ── GUATEMALA: CASE STUDIES ──────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala Palm Oil Plantations — Forced Labour and Child Work",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Palm oil plantations in Petén region employ workers (Guatemalan and Honduran migrants) under conditions: wages Q40-60/day (~USD 5-7), debt for housing/tools, 8-12 hour days, child workers (ages 8-14) unpaid. Workers unable to leave; gang violence controls access. Palm exports to US/Europe; supply chains often unaware of labour violations.",
        "source": "IOM Guatemala / Oxfam / Environmental Justice Foundation",
    },
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala Coffee Plantations — Child Labour and Migrant Exploitation",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "agriculture",
        "summary": "Coffee harvests (Sept-Feb) in Huehuetenango and San Marcos employ migrant families (Mam, K'iche', undocumented from Honduras/El Salvador). Wages: Q30-50/day (~USD 4-6) for picking, children unpaid but working. Housing in plantation camps without sanitation. Children ages 7-16 common in harvests. Pesticide exposure without protection. Debt for tools and food.",
        "source": "Human Rights Watch / Fair Trade USA / IOM Guatemala",
    },
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala City Domestic Workers — Confinement and Abuse",
        "exploitation_type": "restriction_of_movement",
        "sector": "domestic_work",
        "summary": "Domestic workers in Guatemala City (Zones 1-10): confinement to employer homes, work 6-7 days/week, wages Q1,500-3,000/month (~USD 180-360), no rest day enforcement. Indigenous and migrant workers most vulnerable. Physical and sexual abuse documented; workers unable to leave due to threats and transportation control. Estimated 150,000 domestic workers in country; few registered.",
        "source": "ECAP (Guatemalan Legal Action Center) / IOM Guatemala",
    },
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala Garment Sweatshops — Forced Overtime and Low Wages",
        "exploitation_type": "excessive_overtime",
        "sector": "garment",
        "summary": "Garment factories in Guatemala City producing for international brands: workers (majority women) work 12-16 hour days during peak season, overtime paid at standard rate (not 1.5x), wages Q3,000-5,000/month (~USD 360-600). Pregnancy testing for hiring; pregnant workers fired. Union representation forbidden. Audits by brands insufficient; factories change names to evade monitoring.",
        "source": "Clean Clothes Campaign / ILO / Guatemalan Labour Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala: Sex Trafficking of Children — Orphanage Involvement",
        "exploitation_type": "sexual_exploitation",
        "sector": "hospitality",
        "summary": "Children (ages 7-17) trafficked from rural areas and orphanages to commercial sexual exploitation in Guatemala City, Antigua, and beach towns (Tikal, Petén). Recruiters pose as job brokers promising maid/waitress work. Girls trafficked to bars and hotels; boys to exploitation networks. Estimated 5,000-10,000 child victims. Orphanage corruption documented.",
        "source": "UNODC / ECPAT Guatemala / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala Sugarcane Harvest — Wage Theft and Unsafe Conditions",
        "exploitation_type": "withholding_wages",
        "sector": "agriculture",
        "summary": "Sugarcane harvests in Retalhuleu department employ workers and children. Wages: Q50-80/day (~USD 6-10). Pattern: wage delayed 2-4 weeks, deductions for housing and equipment, unsafe machete work without protection, no medical care for injuries. Harvest season (Nov-May): 6-day weeks common. Debt accumulates due to deductions exceeding wages.",
        "source": "Guatemalan Labour Ministry / IOM",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "GT",
        "title": "Guatemala: Conviction of Palm Oil Plantation Owner for Child Labour (2016)",
        "summary": "Court convicted plantation owner (Petén) of employing 60 child labourers (ages 6-14) without payment and under unsafe conditions. Sentence: 4 years imprisonment. Plantation ordered to pay Q500,000 (~USD 65,000) in restitution to victims. Case documented by ILO investigation.",
        "source": "Guatemalan Courts / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "GT",
        "title": "Guatemala: Child Labour in Agriculture (National Survey 2020-2023)",
        "summary": "Estimated 880,000 children (ages 5-17) in child labour (23% of child population). Agriculture: 600,000 children (68% of child labour). Coffee/cacao/palm plantations: 250,000 children. Hazardous work: 380,000 children. Wage work: 420,000 children. School attendance: only 35% of child labourers attend school.",
        "source": "Guatemalan Statistics Institute / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "GT",
        "title": "Guatemala: Sex Trafficking Victims Identified (2015-2024)",
        "summary": "2015: 280 victims identified; 2018: 420 victims; 2022: 510 victims; 2024: 380 victims (preliminary). Breakdown: girls 75%, boys 18%, adults 7%. Age at exploitation: average 12-14 years. Internal trafficking: 70%. Cross-border (to Mexico, Honduras, Belize): 30%. Convictions: ~40-60/year (low relative to victims).",
        "source": "Guatemalan National Prosecutor / UNODC",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "GT",
        "title": "Guatemala: Child Labour Ban in Agriculture (2019, Limited Enforcement)",
        "summary": "Regulatory change prohibited child labour in agriculture. Implementation: weak. Enforcement actions: 20-30/year for country of 8.8M population. Agricultural sector lobbied against enforcement. Compliance monitoring: insufficient resources.",
        "source": "Guatemalan Labour Ministry / ILO",
    },
    {
        "type": "penalty",
        "jurisdiction": "GT",
        "title": "Guatemala: US Import Ban on Coffee Due to Child Labour (2022)",
        "summary": "US CBP issued conditional import ban on coffee from specific Guatemalan plantations (Huehuetenango department) due to documented child labour. Importers required to provide evidence of labour audits. Ban incentivised some compliance improvements but compliance loopholes remained (subcontractor factories, cash payments).",
        "source": "US CBP / US Labour Dept",
    },

    # ── HONDURAS: CASE STUDIES ───────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras Miskito Diving Industry — Forced Labour and Deaths",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "Miskito indigenous divers in Bay Islands forced to dive for lobster and conch. Pattern: recruit young men (ages 18-30) with promises of USD 300/week; reality is USD 50-100/week, debt for equipment, required to dive to extreme depths without proper equipment, nitrogen narcosis causing deaths. Estimated 3,000+ divers; 30-50 deaths/year. Brokers control transport and prevent shore leave.",
        "source": "Environmental Justice Foundation / Amnesty International / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras Garment Factories — Apparel Sweatshops",
        "exploitation_type": "excessive_overtime",
        "sector": "garment",
        "summary": "Garment factories in Honduras (San Pedro Sula, Tegucigalpa, Choloma) produce for US brands. Workers (majority women): 12-16 hour days during peak seasons, overtime at standard rate (not 1.5x), wages L5,000-7,000/month (~USD 200-280). Verbal abuse and harassment common. Pregnancy testing required; pregnant workers fired. Audits insufficient; factories evade detection through subcontracting.",
        "source": "Clean Clothes Campaign / Verité / Honduran Labour Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras Sugarcane Harvest — Heat Exhaustion and Wage Theft",
        "exploitation_type": "abusive_working_conditions",
        "sector": "agriculture",
        "summary": "Sugarcane harvests (Dec-May) in Cortés and Yoro departments employ workers (Honduran and migrant from El Salvador, Guatemala, Nicaragua). Pattern: wages L150-200/day (~USD 6-8), 10-12 hour days in 35°C+ heat, no shade or clean water, heat exhaustion common, worker deaths attributed to 'cardiac arrest'. Wage paid weekly but delayed; debt accumulates. Kidney disease (chronic from dehydration) prevalent among harvesters.",
        "source": "ILO / Honduran Labour Ministry / University of Costa Rica Study",
    },
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras Domestic Workers — Confinement and Abuse",
        "exploitation_type": "isolation",
        "sector": "domestic_work",
        "summary": "Domestic workers (mostly women and girls from poor families) in Tegucigalpa and San Pedro Sula: confinement to household, 6-7 day work weeks, wages L2,000-4,000/month (~USD 80-160), physical and sexual abuse. Girls ages 12-16 common. Workers recruited with false promises. Movement controlled by employers. Limited access to medical care.",
        "source": "Casa Alianza / IOM Honduras / Human Rights Commission",
    },
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras: Sex Trafficking of Girls — Gang-Controlled Networks",
        "exploitation_type": "sexual_exploitation",
        "sector": "hospitality",
        "summary": "Girls (ages 10-18) trafficked from poor neighbourhoods to cantinas and hotels in major cities. Gang-controlled (M18, MS-13) sex trafficking networks. Girls recruited through fake job ads ('waitress', 'dancer') or kidnapped. Debt for housing/clothing used as control. Sold to multiple buyers/night. Violence and drug addiction used to maintain control. Estimated 2,000-5,000 girls in commercial sexual exploitation.",
        "source": "UNODC / IOM Honduras / Casa Alianza",
    },
    {
        "type": "statistic",
        "jurisdiction": "HN",
        "title": "Honduras: Diving-Related Deaths (Occupational Hazard, 2010-2024)",
        "summary": "Bay Islands diving: estimated 30-50 deaths/year from diving accidents (nitrogen narcosis, decompression sickness, pulmonary embolism). Many deaths attributed to 'cardiac arrest' without investigation. Divers: mostly Miskito indigenous (20-40 years old). Cumulative deaths 2010-2024: ~500-700. Widows left without support. No compensation system.",
        "source": "Environmental Justice Foundation / Honduran Health Ministry",
    },
    {
        "type": "statistic",
        "jurisdiction": "HN",
        "title": "Honduras: Child Labour in Agriculture (2018-2022 Survey)",
        "summary": "Estimated 450,000 children (ages 5-17) in child labour (17% of population). Agriculture: 350,000 children. Hazardous work (sugarcane, plantations): 200,000 children. School attendance: only 40% of child labourers. Wage work: 250,000 children earning L50-100/day (~USD 2-4).",
        "source": "Honduran Statistics Institute / ILO",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "HN",
        "title": "Honduras: Conviction of Diving Company Owner for Forced Labour (2012)",
        "summary": "Court convicted diving company owner (Bay Islands) of holding 30 divers in forced labour conditions. Divermasters threatened deportation and physical violence. Divers held on islands for 6+ months without shore leave. Sentence: 8 years. Ordered to pay L500,000 (~USD 25,000) restitution.",
        "source": "Honduran Courts / Environmental Justice Foundation",
    },

    # ── EL SALVADOR: CASE STUDIES ────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "SV",
        "title": "El Salvador Gang-Forced Labour — MS-13 and Barrio 18",
        "exploitation_type": "intimidation_threats",
        "sector": "various",
        "summary": "Gangs (MS-13, Barrio 18) force street vendors, construction workers, and drivers to pay 'protection money' (10-30% of earnings). Workers forced to conduct gang errands (lookout, deliveries). Workers who refuse face threats to family or death. Estimated 200,000+ workers affected. Gang violence intersects with labour exploitation.",
        "source": "UNODC / Salvadoran Police / International Crisis Group",
    },
    {
        "type": "case_study",
        "jurisdiction": "SV",
        "title": "El Salvador Agricultural Workers — Poor Conditions and Wage Theft",
        "exploitation_type": "withholding_wages",
        "sector": "agriculture",
        "summary": "Agriculture (coffee, sugar, corn) employs workers earning $4-5/day. Pattern: wage delayed 1-2 weeks, deductions for tools/housing, unsafe pesticide exposure without protection, no medical care. Migrant workers (from Guatemala, Honduras, Nicaragua) most vulnerable. Housing: employer dormitories without running water/sanitation. Debt accumulates.",
        "source": "Salvadoran Labour Ministry / IOM El Salvador",
    },
    {
        "type": "case_study",
        "jurisdiction": "SV",
        "title": "El Salvador Domestic Workers — Confinement and Abuse by Families",
        "exploitation_type": "isolation",
        "sector": "domestic_work",
        "summary": "Domestic workers (mostly women from poor rural areas) in San Salvador and Santa Ana: confinement, work 6-7 days/week, wages $80-150/month, physical and emotional abuse. Migrant domestic workers from Honduras/Guatemala even more vulnerable. Girls ages 12-16 common. Limited legal protections; employers often related to police.",
        "source": "CODIFEM (Women's Rights Org) / IOM El Salvador",
    },
    {
        "type": "case_study",
        "jurisdiction": "SV",
        "title": "El Salvador Maquiladora Workers — Excessive Overtime and Low Wages",
        "exploitation_type": "excessive_overtime",
        "sector": "manufacturing",
        "summary": "Garment maquiladoras in San Salvador employ workers (mostly women): 12-14 hour days during peak seasons, overtime paid at standard rate, wages $4-6/day. Verbal harassment, no maternity protection, verbal (not written) contracts. Union members harassed. Facilities lack adequate ventilation and safety equipment.",
        "source": "Clean Clothes Campaign / Salvadoran Labour Ministry",
    },
    {
        "type": "statistic",
        "jurisdiction": "SV",
        "title": "El Salvador: Identified Trafficking Victims (2015-2024)",
        "summary": "2015: 180 victims identified; 2018: 220 victims; 2022: 280 victims; 2024: 240 victims (estimated). Breakdown: sexual exploitation 60%, labour exploitation 35%, other 5%. Labour trafficking: agriculture 40%, domestic work 30%, manufacturing 20%, other 10%. Many cases go unreported due to gang violence and victim fear.",
        "source": "Salvadoran National Prosecutor / UNODC",
    },
    {
        "type": "penalty",
        "jurisdiction": "SV",
        "title": "El Salvador: Gang Leader Convicted of Labour Extortion (2018)",
        "summary": "MS-13 gang leader (San Salvador) convicted of extorting USD 100,000/month from street vendors and construction workers through forced 'protection' payments. Sentenced to 12 years. Extortion affected 500+ workers. Case demonstrated gang-labour exploitation nexus.",
        "source": "Salvadoran Courts / UNODC",
    },

    # ── NICARAGUA: CASE STUDIES ──────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "NI",
        "title": "Nicaragua Agricultural Workers — Sugar and Banana Plantations",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Sugar and banana plantations (Atlantico Sur, Granada department) employ workers (many migrant) with debt bondage: wages C$150-200/day (~USD 5-7), debt for housing/tools, 10-12 hour days, unsafe pesticide exposure without protection. Workers from Honduras, Guatemala, El Salvador most vulnerable. Child labour common during peak seasons.",
        "source": "IOM Nicaragua / Nicaraguan Labour Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "NI",
        "title": "Nicaragua Maquiladora Workers — Excessive Hours and Low Pay",
        "exploitation_type": "excessive_overtime",
        "sector": "manufacturing",
        "summary": "Garment factories (Managua, León) produce for international brands: workers (mostly women) 12-14 hour days during peak, overtime at standard rate, wages C$3,500-5,000/month (~USD 120-170). Pregnancy testing for hiring. Union presence minimal. Verbal abuse and wage withholding common. Facilities lack ventilation and safety standards.",
        "source": "Clean Clothes Campaign / Nicaraguan Labour Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "NI",
        "title": "Nicaragua Domestic Workers — Low Wages and Isolation",
        "exploitation_type": "isolation",
        "sector": "domestic_work",
        "summary": "Domestic workers in Managua and Granada (mostly women): wages C$2,000-3,500/month (~USD 70-120), work 6-7 days/week, limited time off, confinement to household, no written contracts. Verbal and physical abuse documented. Migrant workers from Honduras and Guatemala additional vulnerability.",
        "source": "IOM Nicaragua / Nicaraguan Human Rights NGOs",
    },
    {
        "type": "statistic",
        "jurisdiction": "NI",
        "title": "Nicaragua: Trafficking Victims Identified (2015-2024)",
        "summary": "2015: 120 victims identified; 2018: 180 victims; 2022: 200 victims; 2024: 160 victims (estimated). Breakdown: sexual exploitation 65%, labour exploitation 30%, other 5%. Many cases go unreported due to limited institutional capacity.",
        "source": "Nicaraguan National Police / UNODC",
    },

    # ── PANAMA: CASE STUDIES ─────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "PA",
        "title": "Panama Banafarm Plantation — Debt Bondage and Poor Conditions",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Banana plantations (Bocas del Toro, Darién) employ workers (many migrant from Guatemala, Honduras, Nicaragua) with debt bondage: wages B/.250-350/day (~USD 7-10), debt for housing/tools, 10+ hour days, pesticide exposure without protection. Workers cannot leave due to debt. Migrant workers without documents most vulnerable. Workers ages 16+ employed.",
        "source": "IOM Panama / Human Rights Commission",
    },
    {
        "type": "case_study",
        "jurisdiction": "PA",
        "title": "Panama City Domestic Workers — Confinement and Low Wages",
        "exploitation_type": "isolation",
        "sector": "domestic_work",
        "summary": "Domestic workers in Panama City (mostly women from rural/poor areas, some migrants): wages B/.300-600/month (~USD 85-170), work 6-7 days/week with limited time off, confinement to employer home, no written contracts. Migrant workers (Nicaraguan, Guatemalan, Colombian) additional vulnerability. Physical and sexual abuse documented.",
        "source": "IOM Panama / Casa de la Mujer / Panama Labour Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "PA",
        "title": "Panama Maquiladora Workers — Excessive Hours in Assembly Plants",
        "exploitation_type": "excessive_overtime",
        "sector": "manufacturing",
        "summary": "Electronics and garment maquiladoras (Colón Free Zone, Panama City): workers 12-16 hour days during peak, overtime at standard rate, wages B/.800-1,200/month (~USD 225-340). Pregnancy discrimination, verbal abuse, union harassment. Facilities lack safety standards. Subcontracting obscures employer accountability.",
        "source": "Panamanian Labour Ministry / ITUC",
    },
    {
        "type": "statistic",
        "jurisdiction": "PA",
        "title": "Panama: Trafficking Victims Identified (2015-2024)",
        "summary": "2015: 200 victims identified; 2018: 320 victims; 2022: 420 victims; 2024: 350 victims (estimated). Breakdown: sexual exploitation 60%, labour exploitation 35%, other 5%. Panama's transit location increases trafficking flows (victims in transit to North America).",
        "source": "Panamanian National Police / UNODC",
    },

    # ── BELIZE: CASE STUDIES ─────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "BZ",
        "title": "Belize Citrus Workers — Debt Bondage and Wage Theft",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Citrus farms (Orange Walk, Cayo districts) employ workers (many migrant from Guatemala, Honduras, Mexico) with debt bondage: wages BZD 5-7/hour (~USD 2.50-3.50), debt for housing/transportation, 10-12 hour days, pesticide exposure without protection. Workers cannot leave due to debt and migrant status. Many undocumented.",
        "source": "IOM Belize / Belize Labour Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "BZ",
        "title": "Belize Sugar Industry — Child Labour and Unsafe Conditions",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "agriculture",
        "summary": "Sugar cane (Toledo district): employs children (ages 10-16) alongside adults. Wages: BZD 3-5/day (~USD 1.50-2.50) for children, BZD 8-12/day for adults. Machete work without safety equipment; injuries common. No medical care. School attendance minimal. Migrant families (Mam, Q'eqchi' indigenous from Guatemala) most vulnerable.",
        "source": "UNICEF Belize / Belize Labour Ministry",
    },
    {
        "type": "statistic",
        "jurisdiction": "BZ",
        "title": "Belize: Child Labour in Agriculture (2018-2022 Survey)",
        "summary": "Estimated 45,000 children (ages 5-17) in child labour (30% of population). Agriculture: 35,000 children. Sugar, citrus, banana: 20,000 children. Hazardous work: 18,000 children. School attendance: 50% of child labourers.",
        "source": "Belize Statistics Institute / ILO",
    },

    # ── TRANSNATIONAL & REGIONAL PATTERNS ──────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "multi-country",
        "title": "Central America-Mexico-US Trafficking Corridor — Migrant Worker Route",
        "exploitation_type": "multiple",
        "sector": "multiple",
        "summary": "Vulnerable Central Americans (Honduras, Guatemala, El Salvador, Nicaragua) migrating north for work are trafficked en route. Mexico transit stage: forced labour in agriculture, construction, maquiladoras; debt bondage for 'transport'; sexual exploitation in cantinas/hotels. Gang violence and cartel control points increase vulnerability. Estimated 100,000+ annual migrants experience trafficking.",
        "source": "IOM / UNODC / Migrant Forum in Asia",
    },
    {
        "type": "case_study",
        "jurisdiction": "multi-country",
        "title": "Cross-Border Seasonal Agricultural Migration — Exploitation Patterns",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Seasonal agricultural workers (coffee, sugar, fruit, vegetables) cross borders (Guatemala-Mexico, Honduras-Guatemala, Nicaragua-Costa Rica) for harvest work. Pattern: debt for transport and documents, wages below promised amount, wage delays, debt increases. Workers: often indigenous or from poorest communities. Brokers control transport, preventing escape. Estimated 200,000-300,000 annual seasonal migrants.",
        "source": "IOM / ILO / CEPAL",
    },
    {
        "type": "advisory",
        "jurisdiction": "multi-country",
        "title": "ILO: Forced Labour Risk in Central America and Mexico (2023 Regional Assessment)",
        "summary": "ILO identified 800,000-1.2M people in forced labour in Central America and Mexico. Key sectors: agriculture (50%), manufacturing/maquilas (20%), domestic work (15%), other (15%). Root causes: poverty, limited education, discrimination against indigenous/migrant workers, weak law enforcement, criminal organisation control. Most at-risk groups: indigenous communities, migrant workers, women and girls.",
        "source": "ILO Central America & Mexico Regional Assessment 2023",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "multi-country",
        "title": "Central America-Mexico Regional Labour Forum (2015-2024) — Limited Progress",
        "summary": "Regional cooperation forum established to address labour trafficking and exploitation. Initiatives: bilateral labour agreements, joint enforcement operations, victim support mechanisms. Implementation challenges: weak political will, limited resources, corruption, criminal organisation interference. Success: limited; most initiatives remain aspirational.",
        "source": "CEPAL / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "multi-country",
        "title": "Central America Labour Trafficking: Estimated Victims (2024)",
        "summary": "Estimated 1.5-2.5M people (direct) in situations of labour trafficking/exploitation in Central America and Mexico. Female victims: 55% (sexual and labour). Male victims: 45% (labour). Children: 30-40% of victims. Indigenous: 25-35% of victims. Migrant: 30-50% of victims. Actual numbers significantly underreported.",
        "source": "UNODC / ILO / IOM Regional Assessments",
    },
    {
        "type": "statistic",
        "jurisdiction": "multi-country",
        "title": "Trafficking Convictions in Mexico and Central America (2015-2024)",
        "summary": "Mexico: 200-350 convictions/year (2015-2024 average). Guatemala: 10-30 convictions/year. Honduras: 5-15 convictions/year. El Salvador: 5-20 convictions/year. Nicaragua, Panama, Belize: <10 convictions/year each. Total regional: 250-450 convictions/year. Conviction rate: <1% of estimated victims.",
        "source": "UNODC / National Prosecutors / National Courts",
    },
    {
        "type": "penalty",
        "jurisdiction": "multi-country",
        "title": "US CBP Import Bans: Mexican and Central American Companies (2020-2024)",
        "summary": "US CBP issued Withhold Release Orders (WROs) and import bans against 15+ Mexican and Central American agricultural and manufacturing companies for forced labour violations. Impacts: maquiladoras (electronics, garments), plantations (palm, banana, coffee, sugar), seafood processing. Bans incentivise compliance improvements but violations persist through subcontracting.",
        "source": "US CBP / US Labour Dept",
    },
    {
        "type": "complaint",
        "jurisdiction": "multi-country",
        "title": "Collective Complaint: Agricultural Workers Union (2019) — Wage Theft Systemic Issue",
        "summary": "Agricultural worker unions across Central America (FESTAGUA Guatemala, SINTRAHAN Honduras, SINTRA El Salvador) filed collective complaint with ILO documenting systemic wage theft in agricultural sector. Pattern: deductions exceeding wages, payment delays, false accounting, employer retaliation against complainants. ILO investigation ongoing.",
        "source": "ILO / Agricultural Worker Unions",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "multi-country",
        "title": "False Labour Advertising Across Central America and Mexico",
        "summary": "Recruiters/brokers advertise jobs across Central America and Mexico with false promises: 'factory jobs in Mexico, USD 400/month, housing provided, only 40 hours/week' (reality: USD 6-9/day, 60+ hours, debt for housing). Advertisements in newspapers, radio, internet. Targeting vulnerable populations (indigenous, poor, youth).",
        "source": "IOM / ILO / Labour Ministries",
    },
    {
        "type": "penalty",
        "jurisdiction": "multi-country",
        "title": "ILO Sanctions Monitoring: Mexico and Central America Forced Labour (2024)",
        "summary": "ILO monitoring reveals: Mexico domestic enforcement improved but remains inadequate. Guatemala, Honduras, El Salvador: enforcement capacity very limited. Nicaragua, Panama, Belize: minimal enforcement capacity. Recommended improvements: increased labour inspection budgets, training, inter-agency coordination, victim support services.",
        "source": "ILO",
    },

    # ── EXPANDED MEXICO CASES ──────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Guadalajara Textile Sweatshops — Hidden Subcontractors",
        "exploitation_type": "excessive_overtime",
        "sector": "garment",
        "summary": "Small textile workshops in Guadalajara produce for major brands through subcontracting chains. Workers: 13-15 hour days, wages MXN 250-350/day (~USD 15-21), no overtime premium, piece-rate deductions. Multiple factory names/ownerships used to evade audits. Pregnancy discrimination, harassment, union suppression.",
        "source": "Clean Clothes Campaign / Mexican Labour Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Yucatán Tourism Sector — Hotel and Resort Worker Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "hospitality",
        "summary": "Hotels and resorts in Cancún, Playa del Carmen, Tulum recruit workers from poor Mexican states with promises of USD 350/month + housing. Reality: housing USD 150/month (deducted from pay), 12-hour shifts, wage theft through 'uniform costs' and 'breakage fees', debt accumulates. Migrant workers (Central American) without documents most vulnerable.",
        "source": "IOM Mexico / Hotel Workers Union",
    },
    {
        "type": "statistic",
        "jurisdiction": "MX",
        "title": "Mexico: Maquiladora Worker Population and Demographics",
        "summary": "Estimated 800,000-1M workers in Mexican maquiladoras (2023). Female: 65%, Male: 35%. Age: 18-45 majority. Nationalities: Mexican (80%), Central American migrants (15%), internal migrants (5%). Average wage: MXN 250-400/day (~USD 15-24). Unionisation rate: ~5%.",
        "source": "Mexican Ministry of Economy / IMSS",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico: Agricultural Debt Traps in Sinaloa and Nayarit",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Agricultural workers (Mexican and Central American) in vegetable harvests: recruited with MXN 5,000-10,000 (~USD 300-600) 'signing bonus' that becomes instant debt. Wages: MXN 100-150/day. Deductions: housing (MXN 50/day), food (MXN 30/day), tools (MXN 20/day). Net pay: MXN 0-50/day. Debt balloon causes workers to remain trapped for months.",
        "source": "IOM Mexico / Sinaloa Labour Ministry",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "MX",
        "title": "Mexico: Radio Advertisements for Agricultural 'Opportunities'",
        "summary": "Radio stations in Oaxaca, Veracruz, Chiapas broadcast recruitment ads: 'Agricultural jobs in Sinaloa! USD 300/month, housing provided, family-friendly work!' Reality: MXN 100-150/day, employer housing with mandatory deductions, debt accumulation.",
        "source": "Mexican Consumer Protection Agency",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "MX",
        "title": "Mexico: Labour Court Ruling on Domestic Worker Wage Theft (2013)",
        "summary": "Labour court (Mexico City) ruled against employer who withheld 40% of domestic worker's wages for 'breakage' and 'food waste.' Ordered back-payment of 18 months wages (MXN 45,000 ~USD 2,700). Set precedent for domestic worker protection, though enforcement limited.",
        "source": "Mexican Federal Labour Court",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "MX",
        "title": "Mexico: 2020 Labour Law Amendment — Domestic Worker Protections",
        "summary": "Amendment required written contracts for domestic workers, mandatory social security, minimum wage equivalent to general minimum, regulated working hours. Implementation: weak. Enforcement: limited due to informal sector. Estimated 70% of domestic workers still lack written contracts.",
        "source": "Mexican Congress / IMSS",
    },
    {
        "type": "penalty",
        "jurisdiction": "MX",
        "title": "Mexico: Sanctions Against Construction Company for Wage Theft (2015)",
        "summary": "Construction company (Mexico City) sanctioned MXN 500,000 (~USD 30,000) for systematic wage theft: delayed payment, false deductions, fired workers before payment due. Settlement: back-payment to 100+ workers, improved payment systems.",
        "source": "Mexican Labour Ministry",
    },
    {
        "type": "advisory",
        "jurisdiction": "MX",
        "title": "UNODC: Mexico Trafficking Risk Assessment in Agricultural Regions (2022)",
        "summary": "UNODC identified Chiapas, Veracruz, Oaxaca, Sinaloa as highest trafficking risk zones for labour exploitation. Key drivers: poverty (40%+ population below poverty line), indigenous populations (high vulnerability), migration routes (Central Americans), weak enforcement. Recommendations: increase labour inspections, community awareness, NGO funding.",
        "source": "UNODC Mexico Report 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico: Illegal Mining Operations — Worker Exploitation",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "mining",
        "summary": "Illegal gold and silver mining in Guerrero and Oaxaca employ workers (many indigenous, some migrants) under extremely hazardous conditions. Wages: MXN 200-300/day (~USD 12-18). Debt for equipment. No safety equipment, mining accidents common, no medical care. Cartel involvement in some operations. Workers' vulnerability exploited.",
        "source": "Guerrero Labour Ministry / Environmental Organisations",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico: Fireworks Manufacturing — Unregistered Workshops",
        "exploitation_type": "abusive_working_conditions",
        "sector": "manufacturing",
        "summary": "Unregistered fireworks workshops in Guanajuato and Puebla employ workers (including children) in hazardous conditions. Wages: MXN 150-200/day (~USD 9-12) for adults, unpaid for children. No safety equipment, burn injuries common, no compensation. Workers: vulnerable rural poor and indigenous communities.",
        "source": "Mexican Labour Ministry / Child Labour NGOs",
    },

    # ── EXPANDED GUATEMALA CASES ───────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala: Cardamom Plantations — Indigenous Worker Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Cardamom plantations (Alta Verapaz) employ indigenous Q'eqchi' workers under debt bondage: wages Q30-40/day (~USD 4-5), debt for housing/tools that never decreases, children work unpaid, hazardous pesticide exposure. Workers' traditional territory taken for plantations; limited livelihood alternatives.",
        "source": "Human Rights Watch / Environmental Justice Foundation",
    },
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala: Construction Worker Exploitation — Underground Economy",
        "exploitation_type": "withholding_wages",
        "sector": "construction",
        "summary": "Construction boom in Guatemala City employs workers through informal contractors. Wages: Q250-350/day (~USD 30-42), delayed payment 2-4 weeks, deductions for tools/housing, undocumented workers have no recourse. Housing: crowded dormitories. Wage theft common when projects complete.",
        "source": "Guatemalan Labour Ministry / Construction Union",
    },
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala: Cocoa Production — Small Farmer Exploitation",
        "exploitation_type": "exploitation_of_poverty",
        "sector": "agriculture",
        "summary": "Small cocoa farmers (Izabal) exploited by middlemen buyers: purchase cocoa at artificially depressed prices (Q5-8/lb vs world price Q12+/lb), force farmers into debt relationships, control credit. Farmers' children work unpaid in harvesting. Middlemen capture 50%+ of value.",
        "source": "Fair Trade International / Guatemalan Agricultural Ministry",
    },
    {
        "type": "statistic",
        "jurisdiction": "GT",
        "title": "Guatemala: Internal Trafficking Victims (2020-2024)",
        "summary": "Internal trafficking (within Guatemala): estimated 8,000-12,000 victims annually. Urban centers (Guatemala City, Antigua, Lago Atitlán): primary destinations. Rural source areas: Huehuetenango, Alta Verapaz, Quiché (poverty, indigenous, discrimination). Age: 40% under 18.",
        "source": "Guatemalan National Prosecutor / IOM Guatemala",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "GT",
        "title": "Guatemala: Trafficker Conviction in Coffee Plantation Case (2015)",
        "summary": "Court convicted labour trafficker who recruited 35 workers from Quiché for coffee plantation under false premises (promised Q500/day; delivered Q30/day). Debt bondage for housing/tools. Sentence: 5 years imprisonment. Ordered restitution Q300,000 (~USD 40,000).",
        "source": "Guatemalan Courts",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "GT",
        "title": "Guatemala: 2019 Amendment to Child Labour Law",
        "summary": "Expanded list of prohibited child labour activities in agriculture (pesticide handling, heavy machinery, work at heights). Minimum age: 14 for agricultural work (12 light work). Implementation: weak. Agricultural sector lobbied against enforcement. Compliance monitoring: insufficient.",
        "source": "Guatemalan Congress / Labour Ministry",
    },
    {
        "type": "penalty",
        "jurisdiction": "GT",
        "title": "Guatemala: US Import Ban on Sugar Due to Child Labour (2021)",
        "summary": "US CBP issued conditional import ban on sugar from specific Guatemalan plantations (Cane workers union documented child labour). Importers required to demonstrate labour compliance. Ban incentivised some audits but compliance loopholes remain.",
        "source": "US CBP / US Labour Dept",
    },
    {
        "type": "advisory",
        "jurisdiction": "GT",
        "title": "ILO: Child Labour in Guatemalan Agriculture (2022 Assessment)",
        "summary": "ILO assessment: 250,000+ children in hazardous agricultural work in Guatemala. Coffee: 80,000 children. Palm oil: 40,000 children. Sugar: 35,000 children. Cardamom: 20,000 children. School attendance: 30% of child labourers attend school. Health impacts: pesticide poisoning, injuries, psychological trauma.",
        "source": "ILO Guatemala Assessment 2022",
    },

    # ── EXPANDED HONDURAS CASES ────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras: Shrimp Farming Exploitation — Coastal Workers",
        "exploitation_type": "debt_bondage",
        "sector": "aquaculture",
        "summary": "Shrimp farms (Cortés, Yoro coastal areas) employ workers in hazardous conditions: wages L150-200/day (~USD 6-8), debt for tools/housing, chemical exposure without protection, respiratory illness common, no medical care. Young workers (18-35) targeted. Housing: isolated farm compounds; movement restricted.",
        "source": "Environmental Justice Foundation / IOM Honduras",
    },
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras: Cocoa/Chocolate Production — Child Labour Networks",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Cocoa farming (Cortés, Yoro) employs children (ages 6-14) without pay as part of family debt bondage. Adults earn L100-150/day (~USD 4-6). Children work harvest seasons (5-6 months), no education. Chain: farmer → middleman → exporter → international brands often unaware of child labour.",
        "source": "World Cocoa Foundation / Child Labour Watch",
    },
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras: Diver Recruitment Scams — Regional Broker Network",
        "exploitation_type": "deception",
        "sector": "fishing",
        "summary": "Diving brokers in La Ceiba recruit young men (18-30) with false promises: 'USD 500/week diving for lobster.' Reality: USD 50-100/week, debt for equipment, required to dive to 30-40 meters without proper decompression, nitrogen narcosis causing deaths. Brokers work with captains and resort operators. Estimated 2,000+ active divers in Bay Islands.",
        "source": "Environmental Justice Foundation / Amnesty International",
    },
    {
        "type": "statistic",
        "jurisdiction": "HN",
        "title": "Honduras: Maquiladora Workforce and Labour Conditions (2023)",
        "summary": "~130,000 workers in Honduras maquiladoras (2023). Female: 75%, Male: 25%. Average wage: L6,500-8,000/month (~USD 260-320). Unionisation: ~8%. Overtime: 20-30% of workers report forced/unpaid overtime. Working hours: average 48-50/week but 15-20% work 60+ hours/week.",
        "source": "Honduran Labour Ministry / IMSS",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "HN",
        "title": "Honduras: Garment Factory Conviction for Wage Theft (2014)",
        "summary": "San Pedro Sula garment factory convicted of systematic wage deductions (claiming 'production errors' and 'damaged goods'). 200 workers affected. Sentence: 3 years imprisonment, ordered restitution L1M (~USD 50,000).",
        "source": "Honduran Labour Court",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "HN",
        "title": "Honduras: 2018 Labour Law Amendment — Expanded Trafficking Definition",
        "summary": "Amendment expanded trafficking definition to include labour practices (debt bondage, document retention, wage theft, movement restriction). Penalties increased from 10 years to 15 years. Implementation: inconsistent. Prosecution rate: ~5-10/year.",
        "source": "Honduran Congress / National Prosecutor",
    },
    {
        "type": "penalty",
        "jurisdiction": "HN",
        "title": "Honduras: Gang Violence Obstruction of Trafficking Prosecutions (Systematic)",
        "summary": "Gang violence (MS-13, Barrio 18) directly interferes with trafficking prosecutions: witness intimidation, witness murders, prosecutor threats, judge interference. 2015-2024: estimated 20+ trafficking-related witnesses murdered. Prosecution success rate severely hampered.",
        "source": "Honduran Prosecutor / UN Envoy on Gang Violence",
    },

    # ── EXPANDED EL SALVADOR CASES ─────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "SV",
        "title": "El Salvador: Sugar Cane Harvest Deaths — Heat Stress Crisis",
        "exploitation_type": "abusive_working_conditions",
        "sector": "agriculture",
        "summary": "Sugar cane harvests (Dec-May) in Sonsonate and Santa Ana: deaths from heat exhaustion (50+ annually, 2015-2024). Workers: aged 25-55, 10-12 hour days in 35°C+ heat, minimal water breaks, no shade. Deaths recorded as 'cardiac arrest' without investigation. Wages: $4-6/day. Workers: local and migrant.",
        "source": "ILO / Salvadoran Labour Ministry / University of Costa Rica",
    },
    {
        "type": "case_study",
        "jurisdiction": "SV",
        "title": "El Salvador: Garment Sweatshops — Excessive Hours and Low Wages",
        "exploitation_type": "excessive_overtime",
        "sector": "garment",
        "summary": "Garment factories in San Salvador (San Bartolo industrial area): workers (70% women) 12-16 hour days during peak (3+ months/year), wages $4-6/day, no overtime premium. Pregnancy discrimination (testing, firing). Union members harassed. Facilities: poor ventilation, no safety equipment.",
        "source": "Clean Clothes Campaign / Salvadoran Labour Ministry",
    },
    {
        "type": "statistic",
        "jurisdiction": "SV",
        "title": "El Salvador: Gang Extortion of Street Vendors (2020-2024)",
        "summary": "Estimated 30,000-50,000 street vendors in El Salvador subject to gang extortion ('renta'). Daily/weekly payments: $5-20 per vendor, totalling millions annually. Gang violence coerces compliance. Workers essentially have no choice to exit.",
        "source": "UNODC / Salvadoran Police / IOM El Salvador",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SV",
        "title": "El Salvador: Mano Dura Policies and Labour Rights Impact (2003-Present)",
        "summary": "Gang crackdowns ('mano dura') increased incarceration (100,000+ gang members in prison) but also increased gang violence, gang control of labour, and extortion networks. Paradoxical effect: more gang-controlled 'protection' rackets in informal sector. Labour rights declined; informal sector workers more vulnerable.",
        "source": "International Crisis Group / IOM El Salvador",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SV",
        "title": "El Salvador: Domestic Worker Abuse Case — Limited Conviction (2012)",
        "summary": "Domestic worker case (San Salvador): employer physically abused worker, withheld wages for 8 months. Court convicted employer of abuse but ordered only restitution ($500) and 6 months suspended sentence (common for 'domestic' cases). Inadequate justice demonstrated.",
        "source": "Salvadoran Labour Court",
    },

    # ── EXPANDED NICARAGUA CASES ───────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "NI",
        "title": "Nicaragua: Pineapple Plantations — Pesticide Exposure and Low Wages",
        "exploitation_type": "abusive_working_conditions",
        "sector": "agriculture",
        "summary": "Pineapple plantations (San Carlos, Río San Juan) employ workers: wages C$150-200/day (~USD 5-7), pesticide exposure without protection (sprayed while workers in field), respiratory illness common, no medical care. Workers: Nicaraguan and migrant (Honduran, Salvadoran). Housing: plantation barracks without sanitation.",
        "source": "IOM Nicaragua / Environmental Health Network",
    },
    {
        "type": "case_study",
        "jurisdiction": "NI",
        "title": "Nicaragua: Fishing Industry — Dangerous Working Conditions",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "Lake Nicaragua and Atlantic Coast fishing: workers (some migrant) on small boats, 12-16 hour days, wages C$100-150/day (~USD 3-5). Limited food/water on vessels, accidents common, no medical care. Movement restricted during work. Debt for boat rental/equipment. Some worker exploitation.",
        "source": "IOM Nicaragua / Environmental Justice Foundation",
    },
    {
        "type": "statistic",
        "jurisdiction": "NI",
        "title": "Nicaragua: Child Labour in Agriculture (2019-2024 Surveys)",
        "summary": "Estimated 250,000 children (ages 5-17) in child labour (20% of population). Agriculture: 180,000 children (72% of child labour). Hazardous work: 120,000 children. School attendance: 45% of child labourers. Wage work: many underpaid (C$30-50/day, ~USD 1-2).",
        "source": "Nicaraguan Statistics Institute / ILO",
    },

    # ── EXPANDED PANAMA CASES ──────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "PA",
        "title": "Panama: Colón Free Zone — Electronics Assembly Sweatshops",
        "exploitation_type": "excessive_overtime",
        "sector": "manufacturing",
        "summary": "Electronics assembly (Colón Free Zone): workers 12-16 hour days, wages B/.800-1,200/month (~USD 225-340), no overtime premium, pregnancy discrimination, verbal harassment. Subcontracting obscures employer identity. Audits insufficient; factories change names.",
        "source": "Panamanian Labour Ministry / ITUC",
    },
    {
        "type": "case_study",
        "jurisdiction": "PA",
        "title": "Panama: Transit Trafficking Victims — Border Region Vulnerability",
        "exploitation_type": "multiple",
        "sector": "various",
        "summary": "Panama's position on trafficking route (Central America to North America) makes it a transit hub. Victims (mainly from Guatemala, Honduras, El Salvador) forced into work during transit: construction, domestic work, sexual exploitation. Estimated 20,000-40,000 annual transiting victims. Many not identified as victims.",
        "source": "IOM Panama / Panamanian National Police / UNODC",
    },

    # ── EXPANDED BELIZE CASES ──────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "BZ",
        "title": "Belize: Marijuana Cultivation Camps — Forced Labour",
        "exploitation_type": "forced_labour",
        "sector": "agriculture",
        "summary": "Remote marijuana cultivation camps (Toledo, Cayo districts) employ workers (often migrant, undocumented) under forced conditions: wages BZD 20-30/day (~USD 10-15), confinement to camps, violence/weapons present, workers unable to leave. Gang involvement. Workers vulnerable to violence and no legal recourse.",
        "source": "Belize Labour Ministry / DEA Reports",
    },
    {
        "type": "case_study",
        "jurisdiction": "BZ",
        "title": "Belize: Garifuna Seasonal Workers — Migrant Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "agriculture",
        "summary": "Seasonal workers (some Garifuna indigenous, some migrant from Honduras/Guatemala) in citrus and sugar harvests: recruited with debt for transport, wages BZD 5-8/hour (~USD 2.50-4), 10-12 hour days, deductions for housing/tools. Migrant workers (undocumented) most vulnerable; unable to leave due to immigration status.",
        "source": "IOM Belize / Belize Labour Ministry",
    },
    {
        "type": "statistic",
        "jurisdiction": "BZ",
        "title": "Belize: Trafficking Victims (2015-2024) — Small Country Context",
        "summary": "Belize (population 400,000): identified 60-120 trafficking victims annually (2015-2024). Many victims are transiting (Central America to North America). Labour trafficking: ~30% of victims. Sexual trafficking: ~65% of victims. Limited institutional capacity to identify/support victims.",
        "source": "Belize National Police / IOM Belize / UNODC",
    },

    # ── ADDITIONAL MULTI-COUNTRY PATTERNS & CASES ─────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "multi-country",
        "title": "Regional Pattern: Employer Debt Creation Schemes",
        "exploitation_type": "debt_bondage",
        "sector": "various",
        "summary": "Pattern across Mexico and Central America: employers create instant debt upon hiring through multiple mechanisms: signing bonuses (MXN 5,000-10,000), mandatory tool purchases, housing/food deductions, 'training costs', 'production error' deductions. Debt balloon ensures worker cannot leave. Mechanism prevents escape and enforces loyalty.",
        "source": "ILO / IOM Regional Assessment",
    },
    {
        "type": "case_study",
        "jurisdiction": "multi-country",
        "title": "Regional Pattern: Migrant Worker Vulnerability Along Borders",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "various",
        "summary": "Central American migrants crossing through Mexico to US face heightened exploitation: documentation status used as control, wages significantly below promised, housing debt trap, movement controlled by brokers, sexual assault risks (women/girls), theft of earnings. Routes: Guatemala-Mexico (80,000+/year), Honduras-Guatemala (60,000+/year), El Salvador-Guatemala (40,000+/year).",
        "source": "IOM / UNODC / CEPAL",
    },
    {
        "type": "statistic",
        "jurisdiction": "multi-country",
        "title": "Central America Regional: Annual Trafficking Victim Flow (2024)",
        "summary": "Estimated annual trafficking flows: Guatemala origin 60,000 victims; Honduras origin 50,000 victims; El Salvador origin 35,000 victims; Nicaragua origin 20,000 victims. Destinations: Mexico (30%), US (40%), other Central America (20%), other (10%). Actual numbers estimated 2-3x higher due to underreporting.",
        "source": "UNODC / ILO / IOM Regional Assessments",
    },
    {
        "type": "advisory",
        "jurisdiction": "multi-country",
        "title": "World Bank: Mexico-Central America Labour Exploitation Cost Assessment (2024)",
        "summary": "World Bank estimated labour exploitation and trafficking costs USD 3-5B annually (direct: worker wage losses; indirect: reduced productivity, health costs, family impacts). Inefficient enforcement costs economic growth (1-2% GDP reduction). Recommendations: increase labour inspection investment, victim support, supply chain due diligence.",
        "source": "World Bank Central America Assessment 2024",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "multi-country",
        "title": "Regional Labour Standard Harmonisation Initiative (2020-2025, Limited Progress)",
        "summary": "Central American countries attempted harmonisation of labour standards (minimum wage, working hours, child labour definitions). Challenges: political will, economic competition (each country competing for investment), implementation capacity. Actual progress: minimal. Wages still vary 3-4x across region.",
        "source": "CEPAL / ILO Central America",
    },
    {
        "type": "penalty",
        "jurisdiction": "multi-country",
        "title": "US Tariff Preferences and Labour Conditions — Limited Leverage",
        "summary": "US CAFTA-DR (2006) included labour standards provisions. But enforcement weak: only 3 investigations/year average, tariff withdrawal rarely used (political cost to US exporters). Exporters lobby against enforcement. Recommendations: increase investigations, issue tariff warnings (not withdrawals), coordinate with partners.",
        "source": "US Trade Representative / US Labour Dept / Guatemalan Labour Ministry",
    },

    # ── ADDITIONAL MEXICO CASES (Expansion 2) ──────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico: Rubber Plantation Workers (Tabasco) — Hazardous Conditions",
        "exploitation_type": "abusive_working_conditions",
        "sector": "agriculture",
        "summary": "Rubber plantations (Tabasco, Campeche) employ workers in hazardous conditions: wages MXN 150-200/day (~USD 9-12), tapping trees at heights without safety equipment, exposure to latex (allergic reactions), no medical surveillance. Workers: Mexican nationals and Central American migrants. Housing: plantation barracks.",
        "source": "Mexican Labour Ministry / Environmental Health",
    },
    {
        "type": "case_study",
        "jurisdiction": "MX",
        "title": "Mexico: Brick-Kiln Child Labour — Veracruz Focus",
        "exploitation_type": "child_labour",
        "sector": "manufacturing",
        "summary": "Brick kilns (Veracruz, Puebla) employ child labour: children (ages 8-14) work 10+ hours/day, exposed to extreme heat (up to 50°C in kilns), respiratory illness common, minimal wages (MXN 50-100/day, ~USD 3-6). Families work together, often indebted. Dangerous work with minimal safety equipment.",
        "source": "Mexican Labour Ministry / Child Labour NGOs",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "MX",
        "title": "Mexico: Online Job Scams Targeting Vulnerable Workers",
        "summary": "Online recruitment scams (Facebook, WhatsApp, job websites) target vulnerable Mexicans and Central Americans: advertise 'factory jobs, USD 400/month' requiring upfront payment (MXN 500-2,000) for 'training' or 'processing'. Money collected, no job offered. Scammers use WhatsApp groups to move victims between schemes.",
        "source": "Mexican Consumer Protection Agency / IOM",
    },
    {
        "type": "statistic",
        "jurisdiction": "MX",
        "title": "Mexico: Estimated Informal Sector Workers Without Protections",
        "summary": "Estimated 30-35M workers in informal sector in Mexico (2023). No written contracts: 95%. Social security coverage: <10%. Vulnerable to wage theft, excessive hours, unsafe conditions. Percentage of workforce: ~55%. Includes agricultural day labourers, domestic workers, street vendors, small shop workers.",
        "source": "Mexican Statistics Institute (INEGI) / IMSS",
    },
    {
        "type": "penalty",
        "jurisdiction": "MX",
        "title": "Mexico: Fine Against Hotel Chain for Wage Theft (2016)",
        "summary": "Major hotel chain (Cancún) fined MXN 800,000 (~USD 48,000) for systematic wage deductions. Pattern: 'uniform costs', 'breakage fees', 'training charges' deducted from housekeeping staff wages. Settlement: back-payment to 150+ workers, wage system improvements.",
        "source": "Mexican Labour Ministry / Quintana Roo Labour Board",
    },

    # ── ADDITIONAL GUATEMALA CASES (Expansion 2) ─────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "GT",
        "title": "Guatemala: Fish Farming in Lake Atitlán — Environmental and Labour Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "fishing",
        "summary": "Tilapia and other fish farming (Lake Atitlán): workers (Kaqchikel indigenous) earn Q40-60/day (~USD 5-7), debt for housing/tools, 10+ hour days, chemical exposure (antibiotics, pesticides), no medical monitoring. Lake pollution damages community fishing livelihoods. Workers trapped in debt cycle.",
        "source": "Environmental Justice Foundation / IOM Guatemala",
    },
    {
        "type": "statistic",
        "jurisdiction": "GT",
        "title": "Guatemala: Minimum Wage vs Living Wage Gap",
        "summary": "Minimum wage (2024): Q5,000/month (~USD 650). Estimated living wage (family of 4): Q12,000-14,000/month (~USD 1,560-1,820). Gap: workers earn 35-40% of living wage. Affects 50%+ of workforce, particularly agriculture and informal sectors.",
        "source": "Guatemalan Labour Ministry / World Bank",
    },
    {
        "type": "advisory",
        "jurisdiction": "GT",
        "title": "UNODC: Organised Crime Impact on Labour Trafficking (2023 Guatemala Report)",
        "summary": "UNODC assessment: organised crime (human trafficking networks, gangs) actively trafficking workers to exploit in illegal sectors (drug cultivation, mining, smuggling) and legal sectors (agriculture, construction, domestic work). Criminal networks earn estimated Q500M+ annually (~USD 65M) from labour trafficking.",
        "source": "UNODC Guatemala Assessment 2023",
    },

    # ── ADDITIONAL HONDURAS CASES (Expansion 2) ────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras: Pineapple Workers on US Corporate Plantations",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Pineapple plantations (Standard Fruit Company operations, Cortés/Yoro) employ workers: 12-14 hour days, wages L200-300/day (~USD 8-12), overtime unpaid, no union representation. US brand awareness minimal. Plantations use labour contractors to distance employer from conditions.",
        "source": "IOM Honduras / International Union Solidarity",
    },
    {
        "type": "case_study",
        "jurisdiction": "HN",
        "title": "Honduras: Prison Labour in Private Jails — Modern Slavery",
        "exploitation_type": "forced_labour",
        "sector": "various",
        "summary": "Private prisons (Honduras has private prison contracts) use inmate labour in manufacturing (sewing, assembly), agriculture, service work. Wages: L0-20/day (~USD 0-1). Conditions: overcrowded, violent, minimal medical care. Labour: mandatory participation, refusal results in punishment. Modern slavery characteristics present.",
        "source": "Honduran Prison Authority / Human Rights Watch",
    },

    # ── ADDITIONAL EL SALVADOR CASES (Expansion 2) ──────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "SV",
        "title": "El Salvador: Recycling Sector — Unprotected E-Waste Workers",
        "exploitation_type": "abusive_working_conditions",
        "sector": "recycling",
        "summary": "E-waste recycling facilities (San Salvador, Santa Ana) employ workers (ages 16-50+): wages $4-5/day, hazardous chemical exposure (lead, mercury, cadmium) without protection, respiratory illness, skin burns. No medical surveillance. Children (12-15) also work. Informal sector largely unregulated.",
        "source": "Salvadoran Labour Ministry / Environmental Health NGOs",
    },
    {
        "type": "statistic",
        "jurisdiction": "SV",
        "title": "El Salvador: Femicide and Gender-Based Violence Impact on Female Workers",
        "summary": "El Salvador has world's highest femicide rate (per capita). 2023: 4,000+ murders of women, most gang-related. Impact on female labour: fear limits work options, increases vulnerability to exploitation, facilitates coercion in workplace. Female workers (domestic, hospitality) report increased abuse/threats.",
        "source": "Salvadoran National Prosecutor / Human Rights organisations",
    },

    # ── ADDITIONAL PANAMA CASES (Expansion 2) ───────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "PA",
        "title": "Panama: San Blas Indigenous Territory — Non-Indigenous Labour Outsider Control",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "tourism",
        "summary": "Tourism development in San Blas territory (indigenous Guna area) employs outsider (non-Guna) workers in hotels/restaurants under exploitative terms: wages B/.600-1,000/month (~USD 170-285), housing costs deducted, movement restricted to work areas, cultural discrimination. Outsiders control hospitality; Guna community marginalised.",
        "source": "IOM Panama / Indigenous Rights NGOs",
    },
    {
        "type": "case_study",
        "jurisdiction": "PA",
        "title": "Panama: Margarita Island Mining — Informal Labour Exploitation",
        "exploitation_type": "debt_bondage",
        "sector": "mining",
        "summary": "Informal gold mining (Darién, Margarita island area): workers earn B/.20-40/day (~USD 5-10), debt for tools/housing, chemical exposure (mercury in processing), no safety equipment. Operations difficult to regulate (remote, informal). Workers: desperate migrants and poor Panamanians. Environmental contamination severe.",
        "source": "Panamanian Labour Ministry / Environmental Organisations",
    },

    # ── ADDITIONAL NICARAGUA CASES (Expansion 2) ────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "NI",
        "title": "Nicaragua: Tobacco Farming — Pesticide Exposure and Child Work",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "agriculture",
        "summary": "Tobacco farming (Estelí, Matagalpa): workers and children (ages 10-16) exposed to pesticides, wages C$150-200/day (~USD 5-7), no protective equipment, respiratory illness common. Children work during school breaks and harvest season. Contractor system obscures employer responsibility.",
        "source": "ILO / Nicaraguan Labour Ministry / Health Organisations",
    },
    {
        "type": "statistic",
        "jurisdiction": "NI",
        "title": "Nicaragua: Brain Drain and Remittance Dependency",
        "summary": "Estimated 700,000+ Nicaraguans living abroad (out of 7M population). Remittances: 2-3% of GDP (USD 1.8-2.4B annually). Impact: families dependent on migrant earnings from precarious work; encouraging additional migration; vulnerable family members remain (children, elderly) under economic stress.",
        "source": "Nicaraguan Central Bank / World Bank / IOM",
    },

    # ── ADDITIONAL BELIZE CASES (Expansion 2) ───────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "BZ",
        "title": "Belize: Domestic Workers from Guatemala — Cross-Border Exploitation",
        "exploitation_type": "isolation",
        "sector": "domestic_work",
        "summary": "Guatemalan domestic workers (many Q'eqchi', K'iche' indigenous) employed in Belize City and San Pedro Sula: wages BZD 300-500/month (~USD 150-250), confinement to household, 6-7 day work weeks, physical/verbal abuse. Cross-border status used as control; threat of deportation. Vulnerable to trafficking.",
        "source": "IOM Belize / Belize Labour Ministry / Human Rights Organisations",
    },

    # ── FINAL MULTI-COUNTRY EXPANSION ──────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "multi-country",
        "title": "Pattern: Supply Chain Opacity and Trafficking Concealment",
        "exploitation_type": "deception",
        "sector": "various",
        "summary": "Multi-country exploitation pattern: exploiters use sub-contracting chains (employer → contractor → labour broker → worker) to obscure accountability. Final brand/company claims no knowledge of labour violations. Supply chains deliberately kept opaque. Affects agriculture, manufacturing, construction across region.",
        "source": "Human Rights Watch / Business & Human Rights Resource Centre",
    },
    {
        "type": "statistic",
        "jurisdiction": "multi-country",
        "title": "Regional Child Labour Population Estimate (2024)",
        "summary": "Estimated 2.5-3.5M children (ages 5-17) in child labour across Mexico and Central America (2024). Breakdown by country: Mexico 800K-1M, Guatemala 880K, Honduras 450K, El Salvador 300K-400K, Nicaragua 250K, Panama 150K, Belize 45K. Hazardous work: ~60% of child labour.",
        "source": "ILO Global Estimates / National Statistics Institutes",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "multi-country",
        "title": "Regional Precedent: Transnational Trafficking Prosecution (2018)",
        "summary": "Guatemala, Mexico, and Honduras jointly prosecuted trafficking ring operating across borders. Traffickers recruited 200+ workers (primarily Guatemalan, Honduran) for Mexican plantations and construction. Convictions: 12 traffickers, sentences 5-12 years. Rare example of transnational cooperation.",
        "source": "Central American Courts / UNODC",
    },
    {
        "type": "advisory",
        "jurisdiction": "multi-country",
        "title": "IOM: Migration-Trafficking Nexus in Central America-Mexico (2024 Guidance)",
        "summary": "IOM guidance: majority of vulnerable migrants in Mexico-Central America fall into trafficking situations during journey. Critical intervention points: origin community (poverty reduction, awareness), transit (identification, safe passage), destination (victim support, reintegration). Current gap: 80% of trafficked migrants not identified or supported.",
        "source": "IOM Central America Migration Guidance 2024",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "multi-country",
        "title": "Regional Business & Human Rights Due Diligence Initiative (2022-2024, Early Stage)",
        "summary": "Central American countries considering mandatory supply chain due diligence laws (inspired by EU, Germany models). Guatemala, Honduras, El Salvador exploring requirements for companies to audit labour practices. Implementation timeline: 2025-2027 (if political will sustained). Private sector lobbying against.",
        "source": "CEPAL / ILO Central America",
    },
    {
        "type": "penalty",
        "jurisdiction": "multi-country",
        "title": "Regional Trafficker Networks Dismantling (2020-2024, Ongoing)",
        "summary": "Regional law enforcement operations disrupted several trafficking networks (2020-2024): ~50 traffickers convicted, ~2,000 victims identified/assisted. But networks rapidly reconstitute; criminal organisations replace arrested leaders. Root causes (poverty, migration pressure) unaddressed; supply exceeds enforcement capacity.",
        "source": "UNODC / National Prosecutors / INTERPOL",
    },
    {
        "type": "complaint",
        "jurisdiction": "multi-country",
        "title": "NGO Coalition: Labour Standards Enforcement Gap in CAFTA-DR (2023)",
        "summary": "Coalition of 50+ labour/human rights NGOs filed joint complaint with US government documenting CAFTA-DR labour standards failures: insufficient investigations, no tariff consequences, exploiters face negligible penalties. Complaint requested urgent enforcement escalation and victim compensation mechanisms.",
        "source": "International Labour Rights Forum / Clean Clothes Campaign / Coalition",
    },
]
