"""
Multi-country trafficking transit routes — documented 3+ country pipelines,
transit exploitation patterns, re-trafficking dynamics, and jurisdictional
enforcement gaps.

Complements migration_corridors_database.py (bilateral corridors) by focusing
on multi-hop routes where victims cross three or more countries. Sources
include UNODC Global Reports on Trafficking in Persons, IOM Missing Migrants
Project, Mixed Migration Centre 4Mi surveys, FRONTEX risk analyses, Polaris
Project, Environmental Justice Foundation (EJF), Verite investigations, and
academic literature on transnational organized crime.

Covers: Southeast Asian maritime routes, West Africa-North Africa-Europe
overland pipelines, Central America-Mexico-US smuggling-to-trafficking
transitions, Horn of Africa-Arabian Peninsula corridors, Central/South Asian
transit exploitation, Eastern European post-conflict routes, Pacific and
Oceanian transit patterns, and cyber-scam compound recruitment chains.
"""

MULTI_COUNTRY_TRANSIT_ROUTE_FACTS: list[dict] = [
    # ════════════════════════════════════════════════════════════════════════
    # CASE STUDIES — Southeast Asian routes
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Myanmar-Thailand-Malaysia-Singapore Trafficking Pipeline",
        "route": "MM-TH-MY-SG",
        "transit_countries": ["TH", "MY"],
        "summary": "Documented multi-stage pipeline: Myanmar nationals recruited with factory job promises, transported overland to Thailand where brokers confiscate documents, then moved by sea to Malaysia for plantation or construction work. Some re-trafficked to Singapore for domestic service. IOM documented 1,200+ cases between 2015-2022 involving this route, with Thai-Malaysian border as primary exploitation handoff point.",
        "source": "IOM / UNODC Southeast Asia Report 2020",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Vietnam-Cambodia-Thailand Fishing Vessel Route",
        "route": "VN-KH-TH",
        "transit_countries": ["KH"],
        "summary": "Vietnamese men recruited in Ho Chi Minh City and Mekong Delta provinces, transported through Cambodia (Phnom Penh and border towns), then sold to Thai fishing boat captains in Samut Sakhon and Ranong provinces. Victims confined to vessels for months or years. EJF and Greenpeace documented cases of workers at sea for 3+ years without shore leave. Bodies disposed at sea. Thai government's 2015 fishing reforms partially addressed but route persists.",
        "source": "EJF / Greenpeace Southeast Asia / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Rohingya Myanmar-Bangladesh-Malaysia Sea Route",
        "route": "MM-BD-MY",
        "transit_countries": ["BD"],
        "summary": "Rohingya refugees fleeing Myanmar cross into Bangladesh (Cox's Bazar camps), then are recruited by smuggling-trafficking networks for sea voyages to Malaysia. UNHCR documented mass graves in Wang Kelian, Malaysia (2015) and Thai jungle camps. Victims held in transit camps along Thai-Malaysian border for ransom. Those unable to pay are sold into forced labor on plantations or fishing vessels. An estimated 170,000 Rohingya made the sea crossing 2012-2015.",
        "source": "UNHCR / Al Jazeera investigations / UNODC",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Chinese Workers Recruited Through Cambodia Scam Compounds",
        "route": "CN-KH-MM-LA",
        "transit_countries": ["KH", "MM"],
        "summary": "Chinese, Malaysian, and Taiwanese nationals lured by fake job advertisements to Cambodia (Sihanoukville, Poipet). Confined in compound complexes, forced to conduct online fraud. Workers who resist are beaten, Tasered, or sold to other compounds in Myanmar (Myawaddy) or Laos (Golden Triangle SEZ). UN estimated 100,000 people held in Cambodia and 120,000 in Myanmar compounds as of 2023. Some victims transited through 4+ countries before rescue.",
        "source": "UN Human Rights Office / BBC investigations / UNODC 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Philippines-Qatar-Saudi Domestic Worker Re-Trafficking",
        "route": "PH-QA-SA",
        "transit_countries": ["QA"],
        "summary": "Filipino domestic workers deployed to Qatar who flee abusive employers are recruited by informal brokers in Doha labor camps and re-trafficked to Saudi Arabia without proper documentation. Workers arrive in Saudi without valid iqama (residence permit), making them entirely dependent on new employer-trafficker. Philippine Overseas Workers Welfare Administration (OWWA) documented 340+ cases of inter-Gulf re-trafficking 2018-2023.",
        "source": "OWWA / ILO Regional Office for Arab States",
    },
    # ════════════════════════════════════════════════════════════════════════
    # CASE STUDIES — Africa-Mediterranean routes
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Nigeria-Libya-Italy Sex Trafficking Route",
        "route": "NG-LY-IT",
        "transit_countries": ["LY"],
        "summary": "Nigerian women and girls recruited from Edo State with promises of European salon or restaurant work. Transported overland through Niger and Libya where they are held in connection houses, raped, and forced into prostitution to pay transit debts of EUR 30,000-65,000. Those who survive the Mediterranean crossing to Italy are controlled by madams in Castel Volturno, Turin, and Palermo. IOM Missing Migrants Project recorded 1,400+ Nigerian trafficking victims arriving in Italy in 2016 alone. Juju oath rituals used for psychological control throughout the route.",
        "source": "UNODC / IOM Missing Migrants / NAPTIP Nigeria",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Eritrean Refugees Sudan-Libya-Mediterranean Route",
        "route": "ER-SD-LY-IT/MT",
        "transit_countries": ["SD", "LY"],
        "summary": "Eritreans fleeing indefinite military conscription cross into Sudan (Kassala, Khartoum) where Rashaida and other smuggling groups transport them through the Sahara to Libya. In Libyan detention centers and private warehouses, migrants are tortured for ransom, subjected to forced labor, sexual violence, and organ harvesting. UNHCR and MSF documented systematic abuse in Bani Walid and Sabha transit points. An estimated 5,000 Eritreans died in the Sahara and Mediterranean 2014-2020.",
        "source": "UNHCR / MSF / UN Human Rights Council COI on Eritrea",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Ethiopia-Yemen-Saudi Migration Route",
        "route": "ET-YE-SA",
        "transit_countries": ["YE"],
        "summary": "Ethiopian migrants (predominantly Oromo) travel through Djibouti or Somalia to cross the Gulf of Aden to Yemen. Despite active conflict, 138,000 migrants arrived in Yemen in 2019 (Mixed Migration Centre 4Mi data). In Yemen, migrants face detention, forced labor, and extortion by armed groups. Those who reach Saudi Arabia are often employed in agriculture or domestic work under exploitative conditions. Saudi mass deportations returned 350,000+ Ethiopians in 2023 without trafficking screening.",
        "source": "Mixed Migration Centre 4Mi / IOM Yemen",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "West Africa-Maghreb-Spain Agricultural Route",
        "route": "SN/ML/BF-MA-ES",
        "transit_countries": ["MA"],
        "summary": "Workers from Senegal, Mali, and Burkina Faso migrate through Morocco, often spending months or years in transit working in informal agriculture in Tangier and Nador provinces. Those who reach Spain (via Ceuta, Melilla enclaves or boat crossing) are channeled into agricultural labor in Almeria greenhouse complexes (mar de plastico) under exploitative conditions. Spanish labor inspections found workers earning EUR 20-30/day, living in plastic shack settlements (chabolas), with no contracts or social security.",
        "source": "UNODC / Spanish Guardia Civil / Caritas Spain",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Cameroon-Nigeria-Libya-Europe Mixed Migration Route",
        "route": "CM-NG-NE-LY-IT",
        "transit_countries": ["NG", "NE", "LY"],
        "summary": "Anglophone Cameroonians fleeing conflict in Northwest/Southwest regions transit through Nigeria (Cross River State, Lagos) and Niger (Agadez) before reaching Libya. At each transit point, migrants face exploitation: forced labor in Nigerian quarries, extortion by Niger military and smugglers in Agadez, and systematic abuse in Libyan detention. IOM flow monitoring at Agadez counted 12,000+ Cameroonian transits in 2019. Women particularly vulnerable to sexual exploitation at each stage.",
        "source": "IOM Flow Monitoring / UNHCR / Human Rights Watch",
    },
    # ════════════════════════════════════════════════════════════════════════
    # CASE STUDIES — Americas routes
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Central America-Mexico-US Smuggling-to-Trafficking Pipeline",
        "route": "HN/GT/SV-MX-US",
        "transit_countries": ["MX"],
        "summary": "Honduran, Guatemalan, and Salvadoran migrants transiting Mexico are intercepted by cartels who convert smuggling arrangements into trafficking situations. Victims forced to work as drug mules, in cartel safe houses as cooks/cleaners, or in sex trafficking. Polaris Project documented that 40% of foreign-national trafficking victims identified in US had experienced exploitation in Mexico transit. Key transit exploitation nodes: Tapachula, Villahermosa, Reynosa, Nuevo Laredo.",
        "source": "Polaris Project / US National Human Trafficking Hotline",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Honduran Workers Guatemala-Mexico-US Exploitation Chain",
        "route": "HN-GT-MX-US",
        "transit_countries": ["GT", "MX"],
        "summary": "Honduran workers recruited for agricultural jobs in the US transit through Guatemala (Peten, Quetzaltenango) and Mexico. Smuggling debts of USD 8,000-15,000 accumulated during transit create debt bondage on arrival. Workers placed on US farms or construction sites where wages are garnished to repay debts. DOJ prosecuted 23 cases of H-2A visa fraud involving Honduran workers exploited across three countries 2017-2023.",
        "source": "US DOJ / Polaris Project / Centro de Derechos Humanos Fray Matias",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Venezuelan Refugee Exploitation Across South America",
        "route": "VE-CO-EC-PE/CL",
        "transit_countries": ["CO", "EC"],
        "summary": "7.7 million Venezuelans displaced since 2015 face exploitation at multiple transit points. In Colombia (Cucuta, Bogota), Venezuelan women and girls forced into sex trafficking. In Ecuador (transit through Rumichaca border), migrants exploited in informal mining. In Peru and Chile, undocumented Venezuelans subjected to forced labor in agriculture and domestic work. Mixed Migration Centre 4Mi surveys found 38% of Venezuelan migrants experienced exploitation during transit across multiple countries.",
        "source": "Mixed Migration Centre / IOM / R4V Platform",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Haitian Migration Route Through South and Central America",
        "route": "HT-BR/CL-CO-PA-MX-US",
        "transit_countries": ["BR", "CL", "CO", "PA", "MX"],
        "summary": "Haitians who migrated to Brazil and Chile (2010-2018) undertake secondary migration through the Darien Gap (Colombia-Panama) toward the US. Transit through 5+ countries exposes migrants to robbery, sexual violence, and trafficking. In Necochea (Colombia) and Darien jungle, smuggling-trafficking networks extort and exploit migrants. IOM recorded 133,000 migrants crossing the Darien Gap in 2021, with Haitians comprising 55%. Children and women especially vulnerable to exploitation during the 5-7 day jungle crossing.",
        "source": "IOM / UNHCR / Panama SENAFRONT data",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Brazilian-Bolivian Workers in Sao Paulo Garment Sweatshops",
        "route": "BO-BR(SP)",
        "transit_countries": [],
        "summary": "Bolivian nationals recruited in La Paz and El Alto with promises of garment industry jobs in Sao Paulo. Transported through border towns (Corumba, Puerto Quijarro) without documentation. Confined in Bras and Bom Retiro district sweatshops working 16-18 hour days sewing for Brazilian fast fashion brands. Debt bondage for transport and accommodation costs. Brazilian labor inspectors freed 1,100+ Bolivian workers from sweatshops in Sao Paulo between 2013-2022. Some workers re-trafficked to other Brazilian cities (Americana, Indaiatuba) after initial rescue.",
        "source": "Brazilian Ministry of Labor / Reporter Brasil / ILO Brasilia",
    },
    # ════════════════════════════════════════════════════════════════════════
    # CASE STUDIES — South/Central Asian routes
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Nepal-India-Gulf Transit Exploitation Chain",
        "route": "NP-IN-QA/AE/SA",
        "transit_countries": ["IN"],
        "summary": "Nepali workers transit through Indian cities (Delhi, Mumbai, Chennai) where sub-agents inflate recruitment fees and substitute contracts. Workers arrive in Gulf states with different employer and lower salary than promised. Verite investigations found Nepali workers paying USD 1,500-4,000 in India-based transit fees alone. Indian transit agencies operate in legal grey zone exploiting Nepal-India open border. Some workers held in Indian transit camps for weeks while documents are processed or forged.",
        "source": "Verite / ILO Kathmandu / Nepal DOFE",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Bangladesh-Malaysia-Australia Visa Laundering Chain",
        "route": "BD-MY-AU",
        "transit_countries": ["MY"],
        "summary": "Bangladeshi workers obtain Malaysian work visas through licensed agencies paying BDT 400,000-800,000. After brief employment in Malaysia, they are connected to unlicensed migration agents who arrange onward movement to Australia (by boat pre-2013, or via fraudulent student/tourist visas post-2013). Workers arrive in Australia with massive debts and are placed in exploitative farm work, construction, or restaurant labor. Australian Federal Police disrupted 5 such networks 2014-2020.",
        "source": "Australian Federal Police / IOM Dhaka / BMET Bangladesh",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Sri Lankan Workers Through Singapore to Gulf States",
        "route": "LK-SG-SA/QA/AE",
        "transit_countries": ["SG"],
        "summary": "Sri Lankan workers recruited for construction or domestic work in Gulf states are routed through Singapore where recruitment agents inflate fees and add transit charges. Workers spend 1-4 weeks in Singapore labor camps before onward deployment. Contract terms changed during Singapore transit. Sri Lanka Bureau of Foreign Employment documented 200+ complaints of transit exploitation in Singapore 2016-2022, but cross-jurisdictional enforcement remains weak.",
        "source": "SLBFE / ILO Colombo / MOM Singapore",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Uzbekistan-Russia-Kazakhstan Labor Migration Exploitation",
        "route": "UZ-RU-KZ",
        "transit_countries": ["RU"],
        "summary": "Uzbek workers migrate to Russia (Moscow, St. Petersburg) for construction work. Those who lose employment or documents are recruited by networks that move them to Kazakhstan for agricultural or construction labor under exploitative conditions. Workers arrive in Kazakhstan without valid permits, creating complete dependence on employer-traffickers. IOM Central Asia documented that 30% of identified trafficking victims in Kazakhstan had originally migrated to Russia before being re-trafficked.",
        "source": "IOM Central Asia / ILO Moscow / Uzbekistan AMET",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Ukrainian Refugees Exploited in Transit Through Poland and Romania",
        "route": "UA-PL/RO-DE/CZ/IT",
        "transit_countries": ["PL", "RO"],
        "summary": "Post-February 2022, Ukrainian refugees (predominantly women and children) fleeing to Western Europe through Poland and Romania were targeted by trafficking networks at border crossings and reception centers. Europol identified 250+ suspects operating at Ukrainian border points by December 2022. Victims recruited for sexual exploitation in Germany, Czech Republic, and Italy. Exploitation at Polish transit shelters included forced labor in agriculture and food processing. OSCE reported that 90% of potential victims were women travelling alone with children.",
        "source": "Europol / OSCE / La Strada International / GRETA Urgent Report 2022",
    },
    # ════════════════════════════════════════════════════════════════════════
    # CASE STUDIES — Other notable routes
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Indian Workers Through East Africa to Southern Africa",
        "route": "IN-KE/ET-ZA/MZ",
        "transit_countries": ["KE", "ET"],
        "summary": "Indian nationals recruited for construction and mining in South Africa and Mozambique transit through Kenya (Nairobi) and Ethiopia (Addis Ababa) where visas are arranged. Workers arrive with debts of USD 5,000-10,000 and confiscated passports. Exploitation concentrated in Johannesburg construction sites and Mozambique mining operations. South African labour inspectors documented 45 cases of Indian worker trafficking involving East African transit points 2017-2022.",
        "source": "IOM South Africa / ILO Pretoria / South African DHA",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "North Korean Workers Through China to Russia and Mongolia",
        "route": "KP-CN-RU/MN",
        "transit_countries": ["CN"],
        "summary": "North Korean workers deployed by DPRK state agencies transit through China to Russia (Far East logging and construction) and Mongolia (construction). Workers' wages paid directly to DPRK government with workers receiving 10-30% of earnings. UN Panel of Experts estimated 50,000-100,000 DPRK workers abroad pre-2019 sanctions deadline. Despite UN Security Council Resolution 2397 (2017) requiring repatriation by December 2019, workers documented in Russia as late as 2023 under different visa categories.",
        "source": "UN Panel of Experts on DPRK / US State Department TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Afghan Refugees Through Iran and Turkey to Europe",
        "route": "AF-IR-TR-GR/BG",
        "transit_countries": ["IR", "TR"],
        "summary": "Afghan refugees transit through Iran (where 3.5 million Afghans reside, many undocumented) and Turkey en route to Europe. In Iran, undocumented Afghans forced into construction and agriculture with no legal protections. In Turkey, refugees exploited in textile sweatshops (Zeytinburnu, Istanbul) and agriculture (Adana). Those continuing to Greece or Bulgaria face exploitation by smuggling-trafficking networks. IOM documented that 60% of Afghan migrants in Turkey reported experiencing forced labor or exploitation during transit.",
        "source": "IOM / UNHCR Turkey / Mixed Migration Centre",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Somali and Ethiopian Migrants Through Djibouti-Yemen-Saudi Route",
        "route": "SO/ET-DJ-YE-SA",
        "transit_countries": ["DJ", "YE"],
        "summary": "Eastern Route from Horn of Africa through Djibouti (Obock) across Gulf of Aden to Yemen coast. Smugglers force migrants to jump overboard before reaching shore; hundreds drown annually. In Yemen (Aden, Sana'a), migrants exploited by armed groups for forced labor and held for ransom. Those reaching Saudi Arabia face arrest or exploitation in informal sector. IOM estimated 11,000 migrants held in detention in Yemen in 2022 facing severe abuse.",
        "source": "IOM Yemen / UNHCR Djibouti / Mixed Migration Centre 4Mi",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Moldovan and Romanian Workers Exploited Through Turkey to UAE/Qatar",
        "route": "MD/RO-TR-AE/QA",
        "transit_countries": ["TR"],
        "summary": "Moldovan and Romanian nationals recruited for construction and hospitality jobs in the Gulf transit through Turkey where documents are confiscated and contracts changed. Victims held in Istanbul labour camps before onward flights to UAE or Qatar. Workers arrive with inflated debts for transit fees, medical examinations, and visa costs. GRETA (Council of Europe monitoring body) documented 120+ cases of this transit exploitation pattern in its Moldova and Romania evaluation reports 2018-2023.",
        "source": "GRETA / IOM Moldova / La Strada Moldova",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Filipino Workers Re-Trafficked Within Gulf Cooperation Council States",
        "route": "PH-KW-SA-AE",
        "transit_countries": ["KW"],
        "summary": "Filipino domestic workers who flee abusive employers in Kuwait are picked up by unlicensed agencies and re-trafficked to Saudi Arabia or UAE. Workers lack exit visas and valid residency, creating complete dependence on traffickers. Bait and switch: workers promised return home but instead moved to new employers. POLO (Philippine Labour Attache) offices in Gulf documented 500+ inter-GCC re-trafficking cases 2015-2023, but cross-border enforcement between GCC states remains minimal.",
        "source": "POLO Kuwait / POLO Riyadh / OWWA",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Congolese and Burundian Refugees Through Tanzania to South Africa",
        "route": "CD/BI-TZ-MZ/ZA",
        "transit_countries": ["TZ", "MZ"],
        "summary": "Refugees from DRC and Burundi in Tanzanian camps (Nyarugusu, Nduta) are recruited by networks promising employment in South Africa. Transported through Mozambique where they face exploitation in transit. On arrival in South Africa, workers placed in exploitative domestic work, mining, or street vending. IOM Tanzania documented that transit through Mozambique is particularly dangerous, with migrants held for ransom in Tete and Maputo provinces.",
        "source": "IOM Tanzania / UNHCR / Southern African Migration Programme",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Nepali Women Trafficked Through India to Gulf for Domestic Work",
        "route": "NP-IN-KW/LB/OM",
        "transit_countries": ["IN"],
        "summary": "Nepali women recruited from rural areas (Sindhupalchok, Nuwakot districts) for domestic work in Gulf states. Trafficked through open India-Nepal border to Indian airports (Delhi IGI, Mumbai CSIA) where they board flights to Kuwait, Lebanon, or Oman using fraudulent Indian passports. Nepal government's ban on female domestic worker deployment to Gulf states (for workers under 30) drove this underground transit pattern. ILO estimated 50,000 Nepali women working undocumented in Gulf domestic service as of 2021.",
        "source": "ILO Kathmandu / Nepal NHRC / POURAKHI Nepal",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "West African Children Trafficked Through Sahel to North Africa",
        "route": "NG/GH/BF-NE-LY/DZ",
        "transit_countries": ["NE"],
        "summary": "Children from Nigeria, Ghana, and Burkina Faso trafficked through Niger (Agadez) to Libya and Algeria. In Libya, boys forced into labor in agriculture, car washes, and construction; girls subjected to sexual exploitation. UNICEF and IOM documented that 75% of children travelling through Niger reported experiencing violence or exploitation. Agadez serves as central transit hub where smuggling-trafficking networks sort migrants by ability to pay. Children who cannot pay onward transit are sold to exploiters in Libya or returned to Niger for forced begging.",
        "source": "UNICEF / IOM Niger / Save the Children",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Indonesians Trafficked Through Malaysia to Cambodia Scam Compounds",
        "route": "ID-MY-KH",
        "transit_countries": ["MY"],
        "summary": "Indonesian nationals recruited through social media job advertisements travel to Malaysia (Kuala Lumpur, Johor Bahru) before being flown to Cambodia (Phnom Penh, Sihanoukville). On arrival, passports confiscated and workers forced into online scam operations. Workers who resist face physical violence and sale to other compounds. Indonesian Embassy in Phnom Penh rescued 650+ nationals from scam compounds in 2022-2023 alone. Malaysian transit used to evade Indonesian government travel restrictions to Cambodia.",
        "source": "Indonesian Embassy Phnom Penh / UNHCR / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Gambian and Senegalese Youth Through Libya to Europe — Backway",
        "route": "GM/SN-ML-BF-NE-LY-IT",
        "transit_countries": ["ML", "BF", "NE", "LY"],
        "summary": "Young Gambian and Senegalese men take the 'backway' through 4-5 West African countries to Libya and onward to Italy. Journey takes 3-18 months with exploitation at multiple transit points. In Niger, forced to work in gold mines. In Libya, detained in official and unofficial prisons, tortured for ransom, forced to labour. Those who reach Italy often carry debts of EUR 3,000-8,000 and are channeled into exploitative agriculture in Foggia (tomato picking) or sex trafficking. IOM documented that average transit time increased from 3 months (2015) to 12+ months (2020) as routes became more dangerous.",
        "source": "IOM / UNHCR / Gambia Immigration Department / Doctors Without Borders",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Pakistani Workers Through UAE and Oman to Iran for Fishing",
        "route": "PK-AE/OM-IR",
        "transit_countries": ["AE", "OM"],
        "summary": "Pakistani fishermen from Sindh and Balochistan provinces recruited for fishing in Iranian waters. Transit through UAE (Sharjah, Ajman) or Oman (Muscat) by boat. Passports confiscated on Iranian arrival. Workers confined to fishing vessels for 6-18 months. Wages paid to agents in Pakistan, workers receive minimal food and no cash payment. Pakistan's Federal Investigation Agency documented 300+ cases of this pattern 2016-2022 but cross-jurisdictional prosecution remains absent.",
        "source": "Pakistan FIA / ILO Islamabad / Sindh Labour Department",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Cambodian and Lao Workers Through Thailand to Malaysia Rubber Plantations",
        "route": "KH/LA-TH-MY",
        "transit_countries": ["TH"],
        "summary": "Cambodian and Lao workers recruited for agricultural work cross into Thailand (Aranyaprathet, Nong Khai border crossings) and are then transported south to Malaysia for rubber and palm oil plantation work. Workers arrive without documentation, creating complete dependence. Malaysian plantation companies use Thai subcontractors as intermediaries, obscuring labor trafficking chains. Tenaganita (Malaysian NGO) documented 400+ cases of transit exploitation 2015-2022.",
        "source": "Tenaganita / ILO Bangkok / LICADHO Cambodia",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Guatemalan Workers Exploited on US H-2B Visa Through Mexican Transit",
        "route": "GT-MX-US",
        "transit_countries": ["MX"],
        "summary": "Guatemalan workers recruited by raiteros (unlicensed recruiters) for US H-2B temporary worker visas. Workers charged USD 3,000-8,000 in recruitment fees. Transit through Mexico (Tapachula for visa processing, then overland to US consulates) adds further costs and debt. On arrival at US seafood, landscaping, or hospitality worksites, wages garnished to repay debts. Workers unable to change employers due to visa tie. CDM (Centro de los Derechos del Migrante) documented systematic fee overcharging during Mexican transit phase.",
        "source": "CDM / US DOL / Polaris Project",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Thai Workers Re-Trafficked from Fishing to Seafood Processing via Indonesia",
        "route": "TH-ID-TH",
        "transit_countries": ["ID"],
        "summary": "Thai fishing workers stranded on Indonesian islands (Benjina, Ambon, Tual) after forced labor on Thai fishing vessels were documented by AP investigation in 2015. Some workers held for over a decade. Rather than being repatriated, some were re-trafficked back to Thai-flagged vessels or to Thai seafood processing facilities. AP investigation led to rescue of 2,000+ fishermen and prompted US downgrade of Thailand in 2014 TIP Report. Transit through Indonesian waters and ports enabled jurisdictional evasion.",
        "source": "Associated Press / IOM Indonesia / US State Department TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Mozambican Workers Through eSwatini to South African Farms",
        "route": "MZ-SZ-ZA",
        "transit_countries": ["SZ"],
        "summary": "Mozambican workers from Gaza and Inhambane provinces cross into eSwatini (Swaziland) before entering South Africa for farm labor in Mpumalanga and Limpopo provinces. Transit through eSwatini used to evade South African border controls. Workers employed on citrus and sugarcane farms without contracts or minimum wage compliance. South African Department of Employment documented 200+ exploited Mozambican workers on a single farm operation in Mbombela in 2021.",
        "source": "South African DEL / IOM Pretoria / Lawyers for Human Rights SA",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Kenyan Domestic Workers Through Ethiopia to Saudi Arabia",
        "route": "KE-ET-SA",
        "transit_countries": ["ET"],
        "summary": "Kenyan women recruited for domestic work in Saudi Arabia transit through Ethiopia (Addis Ababa Bole International Airport) to circumvent Kenya's 2012-2017 deployment ban to Saudi Arabia. Workers obtain Ethiopian travel documents or use Kenyan passports with Ethiopian transit visas. Ethiopian brokers add USD 500-1,500 in transit fees. Workers arrive in Saudi Arabia with dual debts (Kenyan recruiter + Ethiopian transit agent). Kenya's National Employment Authority documented 2,000+ cases of this circumvention pattern.",
        "source": "Kenya NEA / IOM Nairobi / ILO Addis Ababa",
    },
    # ════════════════════════════════════════════════════════════════════════
    # LAWS AND LEGAL FRAMEWORKS
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Palermo Protocol — Transnational Organized Crime Provisions",
        "law": "Protocol to Prevent, Suppress and Punish Trafficking in Persons",
        "year": 2000,
        "summary": "UN Protocol supplementing the Convention against Transnational Organized Crime. Article 5 requires criminalization of trafficking when committed transnationally. Article 10 mandates interstate cooperation including information exchange on transit routes. Article 11 requires border controls to detect trafficking. 178 state parties as of 2024. Key limitation: no mandatory transit state screening obligation.",
        "source": "UNODC / UN Treaty Collection",
    },
    {
        "type": "law",
        "jurisdiction": "EU",
        "title": "EU Anti-Trafficking Directive 2011/36/EU — Cross-Border Cooperation",
        "law": "Directive 2011/36/EU on preventing and combating trafficking",
        "year": 2011,
        "summary": "Article 2 establishes common definition of trafficking applicable across EU member states. Article 9 requires non-prosecution of victims for offences committed as result of trafficking. Article 11 mandates assistance regardless of willingness to cooperate with prosecution. Article 19 requires appointment of national rapporteurs or equivalent mechanisms. Enables cross-border JITs (Joint Investigation Teams) but enforcement relies on member state cooperation.",
        "source": "EUR-Lex / European Commission Anti-Trafficking",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ASEAN Convention Against Trafficking in Persons (ACTIP) 2015",
        "law": "ASEAN Convention Against Trafficking in Persons, Especially Women and Children",
        "year": 2015,
        "summary": "First legally binding regional anti-trafficking instrument in Southeast Asia. Requires member states to criminalize all forms of trafficking, establish preventive measures, protect victims, and cooperate in cross-border investigations. Entered into force March 2017. Key limitation: no enforcement mechanism or compliance monitoring body. Transit country obligations remain vague. Only 8 of 10 ASEAN members ratified as of 2024.",
        "source": "ASEAN Secretariat / UNODC",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Bali Process on People Smuggling, Trafficking and Related Transnational Crime",
        "law": "Bali Process Framework",
        "year": 2002,
        "summary": "49-member voluntary framework for Asia-Pacific region cooperation on people smuggling and trafficking. Established working groups on trafficking and smuggling, and on disruption. Launched Bali Process Government and Business Forum (2017) for supply chain accountability. Developed Regional Guide to Needs Assessment for Victims of Trafficking. Key limitation: non-binding framework with no enforcement powers; relies on voluntary cooperation. Effective for information sharing but weak on transit state accountability.",
        "source": "Bali Process Secretariat / IOM",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Protocol Against the Smuggling of Migrants by Land, Sea and Air",
        "law": "Protocol against the Smuggling of Migrants",
        "year": 2000,
        "summary": "Supplementary protocol to the UN Convention against Transnational Organized Crime addressing migrant smuggling specifically. Article 6 criminalizes smuggling when committed for financial or material benefit. Article 16 establishes protection obligations for smuggled migrants. Critical gap: no mandatory mechanism to identify trafficking victims among smuggled persons. The smuggling-to-trafficking transition that occurs during multi-country transit is poorly addressed by this instrument.",
        "source": "UNODC / UN Treaty Collection",
    },
    {
        "type": "law",
        "jurisdiction": "AU",
        "title": "African Union Convention on Cross-Border Cooperation (Niamey Convention)",
        "law": "AU Convention on Cross-Border Cooperation",
        "year": 2014,
        "summary": "Framework for cooperation in border areas including provisions relevant to combating cross-border trafficking. Promotes coordination between border communities and authorities. Entered into force 2017. Complements the Ouagadougou Action Plan to Combat Trafficking in Human Beings (2006). Implementation remains limited with only 15 of 55 AU member states ratifying. Transit exploitation across African borders largely unaddressed in practice.",
        "source": "African Union / IOM Africa",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Mutual Legal Assistance Treaties and Multi-Country Trafficking Prosecution",
        "law": "Bilateral and multilateral MLATs",
        "year": 2000,
        "summary": "Mutual Legal Assistance Treaties (MLATs) theoretically enable cross-border trafficking prosecution, but average processing time is 6-18 months, far slower than trafficking networks operate. UNODC found that fewer than 5% of cross-border trafficking cases result in prosecution in more than one country. Key barriers: different evidentiary standards, language requirements, diplomatic delays, and lack of dedicated trafficking MLAT channels. EU European Investigation Order (2017) improved intra-EU cooperation but remains exception globally.",
        "source": "UNODC / Council of Europe / INTERPOL",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Extraterritorial Jurisdiction Provisions in National Trafficking Laws",
        "law": "Various national trafficking statutes — extraterritorial provisions",
        "year": 2010,
        "summary": "Only 35% of countries have extraterritorial jurisdiction provisions in their trafficking laws (UNODC 2022). US TVPA Section 1596 allows prosecution of trafficking committed abroad by US nationals or residents. UK Modern Slavery Act 2015 Section 2 covers UK nationals acting abroad. France Law 2013-711 allows prosecution of French nationals for trafficking anywhere. These provisions are rarely used for transit exploitation. UNODC documented only 23 extraterritorial trafficking prosecutions globally 2010-2022.",
        "source": "UNODC Global Report 2022 / US DOJ / UK CPS",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "IOM International Dialogue on Migration — Transit Migration Framework",
        "law": "IOM Transit Migration Framework",
        "year": 2010,
        "summary": "IOM framework recognizing transit migration as distinct phenomenon requiring specific policy responses. Identifies three categories of transit country obligation: (1) protection of migrants in transit, (2) prevention of trafficking/smuggling, (3) cooperation with origin and destination countries. Non-binding guidance that has influenced national policies in Morocco, Libya, Turkey, and Mexico. Key recommendation: establish migrant assistance centers at major transit points.",
        "source": "IOM / International Dialogue on Migration",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Khartoum Process — EU-Horn of Africa Route Conference",
        "law": "EU-Horn of Africa Migration Route Initiative (Khartoum Process)",
        "year": 2014,
        "summary": "Political process involving EU and Horn of Africa countries to address trafficking and smuggling along migration routes. Covers transit countries (Sudan, Libya, Egypt, Ethiopia, Djibouti). Four priority areas: prevention, protection, prosecution, and policy framework. EUR 200 million EU Trust Fund for Africa allocated for transit route projects. Criticized for prioritizing migration management over human rights and for cooperating with authoritarian transit states (Sudan, Libya) whose security forces are implicated in trafficking.",
        "source": "EU External Action Service / ICMPD",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ECOWAS Free Movement Protocol and Trafficking Vulnerabilities",
        "law": "ECOWAS Protocol on Free Movement of Persons (1979, revised 1986, 1990)",
        "year": 1979,
        "summary": "ECOWAS free movement protocol enables visa-free travel for 300+ million West Africans across 15 member states. While promoting legitimate migration, creates exploitable gaps for trafficking networks. Children transported across borders without documentation controls. 2001 supplementary protocol on trafficking requires member states to criminalize trafficking but enforcement remains weak. Only 3 of 15 ECOWAS states have functional national anti-trafficking agencies. Transit exploitation between Nigeria, Niger, Burkina Faso, and Mali remains largely unprosecuted.",
        "source": "ECOWAS Commission / UNODC / IOM West Africa",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "GCC Unified Contract for Domestic Workers and Inter-State Transfer",
        "law": "GCC Unified Domestic Worker Contract",
        "year": 2014,
        "summary": "GCC states agreed on unified contract for domestic workers covering wages, working hours, and rest. However, no provisions address inter-GCC transfer of workers or re-trafficking between member states. Workers who flee abuse in one GCC state and are trafficked to another face legal limbo: absconding charges in origin state, no valid residency in destination state. The kafala system operates independently in each GCC country, preventing coordinated victim protection for workers exploited across multiple Gulf states.",
        "source": "ILO Regional Office for Arab States / Gulf Labour Markets and Migration",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Budapest Process — Silk Routes Transit Route Dialogue",
        "law": "Budapest Process and Silk Routes Partnership",
        "year": 1993,
        "summary": "Intergovernmental dialogue on migration involving 50+ countries along migration routes from Central/South Asia through Middle East and Turkey to Europe. Silk Routes Partnership (2013) specifically addresses transit exploitation. Developed Regional Guidelines on Identifying and Referring Victims of Trafficking (2019). Non-binding but has produced operational cooperation frameworks. Transit countries Turkey, Iran, and Pakistan engaged as both source and transit states. Funding through ICMPD.",
        "source": "ICMPD / Budapest Process Secretariat",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Rabat Process — Euro-African Dialogue on Migration and Development",
        "law": "Rabat Process Framework",
        "year": 2006,
        "summary": "Dialogue involving 55+ European and African states focused on West/Central African migration routes to Europe. Marrakech Action Plan (2018) includes specific commitments on transit country trafficking prevention. Identifies Niger, Libya, and Morocco as key transit states requiring capacity building. EUR 5 billion EU Emergency Trust Fund for Africa partially directed at transit route management. Criticized for conflating anti-trafficking with border externalization policies.",
        "source": "ICMPD / EU External Action / Rabat Process Secretariat",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Transit Country Liability Under International Law — Legal Gap Analysis",
        "law": "Customary international law on transit state obligations",
        "year": 2018,
        "summary": "Legal analysis by OHCHR (2018) concludes that transit states have human rights obligations toward migrants in their territory, including victims of trafficking, under customary international law and treaty obligations (ICCPR, ICESCR, CAT). However, no treaty specifically defines transit state trafficking liability. Practical result: transit countries (Libya, Niger, Turkey, Mexico) rarely investigate or prosecute trafficking within their borders when victims are in transit to other countries. OHCHR recommended a new optional protocol addressing transit state obligations.",
        "source": "OHCHR / UN Special Rapporteur on Trafficking / UNODC",
    },
    # ════════════════════════════════════════════════════════════════════════
    # COURT RULINGS
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "Rantsev v. Cyprus and Russia [2010] ECHR — Transit State Obligations",
        "court": "European Court of Human Rights",
        "year": 2010,
        "summary": "Russian national Oxana Rantseva trafficked from Russia through Cyprus where she died in suspicious circumstances. ECHR found BOTH Russia (origin state) and Cyprus (destination/transit) violated Article 4. Established that transit/destination states have positive obligation to investigate trafficking and protect victims. Cyprus failed to take operational measures when police had Rantseva in their custody. First ECHR ruling establishing dual-state obligation covering transit/destination country responsibility.",
        "source": "ECHR / HUDOC / Application no. 25965/04",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "V.C.L. and A.N. v. United Kingdom [2021] ECHR — Non-Punishment of Transit Victims",
        "court": "European Court of Human Rights",
        "year": 2021,
        "summary": "Two Vietnamese nationals trafficked through multiple countries to UK for cannabis cultivation. Prosecuted for drug offences despite being potential trafficking victims. ECHR found UK violated Article 4 by failing to adequately investigate trafficking before prosecution. Established that victims exploited during multi-country transit must be identified and protected at point of discovery, regardless of transit history. Reinforced non-punishment principle for trafficked persons across jurisdictions.",
        "source": "ECHR / HUDOC / Applications nos. 77587/12 and 74603/12",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "S.M. v. Croatia [2020] ECHR Grand Chamber — Trafficking Definition",
        "court": "European Court of Human Rights (Grand Chamber)",
        "year": 2020,
        "summary": "Grand Chamber clarified that Article 4 ECHR encompasses trafficking and exploitation even where the victim has not crossed an international border, but also where they have crossed multiple borders. Confirmed that states must have operational framework to identify victims regardless of how many countries they have transited. Broadened scope of positive obligations for both transit and destination states. Important for multi-country routes where exploitation occurs in transit.",
        "source": "ECHR Grand Chamber / HUDOC / Application no. 60561/14",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "US",
        "title": "United States v. Kalu [2015] — Multi-Country Trafficking Network Prosecution",
        "court": "US District Court, District of New Jersey",
        "year": 2015,
        "summary": "Nigerian nationals trafficked through Togo and Mexico to the US for forced labor in beauty salons. Defendants convicted under TVPA for operating multi-country trafficking network. Court established that facilitation of transit through third countries (Togo, Mexico) for purpose of exploitation constitutes trafficking elements. Sentence: 8-15 years imprisonment. Important precedent for US jurisdiction over multi-country trafficking pipelines ending in the US.",
        "source": "US DOJ / TVPA prosecution records",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "US",
        "title": "United States v. Askarkhodjaev [2009] — Multi-Country Labor Trafficking Ring",
        "court": "US District Court, Western District of Missouri",
        "year": 2009,
        "summary": "Uzbek national convicted of trafficking workers from Kazakhstan and Uzbekistan through multiple countries to the US for hospitality labor exploitation. Network operated across Central Asia, Russia, and US. Defendant used transit through multiple jurisdictions to confuse investigators. Sentenced to 12 years. DOJ secured cooperation from Uzbek and Kazakh authorities through MLAT process. Demonstrated feasibility of multi-country trafficking prosecution but took 4 years to build case.",
        "source": "US DOJ / FBI",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "EU",
        "title": "Europol Joint Investigation Team — Operation Webmaster [2018]",
        "court": "Multiple EU national courts (Romania, UK, Germany, Spain)",
        "year": 2018,
        "summary": "Largest EU Joint Investigation Team (JIT) targeting multi-country trafficking network. Romanian victims trafficked through Hungary and Austria to UK, Germany, and Spain for forced labor and sexual exploitation. 89 arrests across 4 countries. Eurojust coordinated simultaneous prosecutions. Demonstrated that JIT mechanism can effectively address transit exploitation but required 3+ years of planning. Total sentences exceeded 200 years imprisonment across participating countries.",
        "source": "Europol / Eurojust / Romanian DIICOT",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "UK",
        "title": "R v. Matyas and Others [2019] — Hungarian-UK Trafficking Network",
        "court": "Crown Court, Birmingham",
        "year": 2019,
        "summary": "Hungarian national convicted of trafficking victims from Hungary through Austria to UK for forced labor in food processing and agriculture. Victims recruited from impoverished Roma communities, transported via multiple transit points, housed in overcrowded accommodation, and paid fraction of minimum wage. National Crime Agency investigation spanning 3 countries over 2 years. Sentenced to 11 years. Court noted that transit through Austria was used specifically to launder the trafficking route and complicate detection.",
        "source": "UK NCA / CPS / Modern Slavery Act prosecutions",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "IT",
        "title": "Ferrara Trafficking Case [2017] — Nigeria-Libya-Italy Pipeline Prosecution",
        "court": "Tribunal of Catania, Italy",
        "year": 2017,
        "summary": "First Italian prosecution targeting the full Nigeria-Libya-Italy sex trafficking pipeline. Nigerian madam convicted of trafficking 13 women through Libya to Italy for sexual exploitation. Court recognized exploitation in Libyan transit (forced prostitution in connection houses) as constituent element of trafficking. Prosecution established that Libyan transit exploitation was integral part of trafficking scheme, not separate crime. Sentences of 8-20 years for network members.",
        "source": "Italian DDA / UNODC / IOM Italy",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v. McIvor and Tanuchit [2010] — Thai-Australia Trafficking Ring",
        "court": "Supreme Court of New South Wales",
        "year": 2010,
        "summary": "Australian and Thai nationals convicted of trafficking Thai women through Malaysia to Australia for sexual exploitation. Victims recruited in Thailand, transited through Malaysia (Kuala Lumpur) where passports were confiscated and debts inflated, then flown to Sydney. Court found that Malaysian transit was integral part of trafficking operation designed to increase control over victims. Sentences: 12 years (McIvor), 8 years (Tanuchit). First Australian prosecution addressing multi-country transit exploitation.",
        "source": "Australian Federal Police / Commonwealth DPP",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "FR",
        "title": "Cour de cassation — Multi-Country Domestic Servitude Network [2019]",
        "court": "Cour de cassation (French Supreme Court)",
        "year": 2019,
        "summary": "French Supreme Court upheld convictions in case involving West African domestic workers trafficked through Morocco and Spain to France. Network recruited women from Cote d'Ivoire and Cameroon, transited through Morocco (Tangier) and Spain (Algeciras), then exploited in domestic servitude in Paris and Lyon. Court affirmed that transit through third countries for purpose of exploitation constitutes aggravating circumstance under French trafficking law (Code penal art. 225-4-1). Enhanced sentences for transnational element.",
        "source": "Cour de cassation / CNCDH France / CCEM",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "NL",
        "title": "Dutch Trafficking Prosecution — Central Asian Network via Turkey [2020]",
        "court": "Rechtbank Den Haag (District Court of The Hague)",
        "year": 2020,
        "summary": "Uzbek and Tajik nationals trafficked through Turkey and Greece to the Netherlands for labor exploitation in greenhouse agriculture and construction. Dutch court asserted jurisdiction over full trafficking chain despite exploitation in Turkey transit. Convicted 4 defendants. Court recognized that workers exploited during Turkish transit phase were subsequently re-exploited in the Netherlands, establishing continuous trafficking offense across jurisdictions. Important for precedent on transit exploitation as part of ongoing criminal enterprise.",
        "source": "Dutch National Rapporteur on Trafficking / Openbaar Ministerie",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "international",
        "title": "IACtHR — Workers of the Hacienda Brasil Verde v. Brazil [2016]",
        "court": "Inter-American Court of Human Rights",
        "year": 2016,
        "summary": "Landmark Inter-American Court ruling finding Brazil responsible for failure to prevent internal trafficking and forced labor at Hacienda Brasil Verde cattle ranch. Workers trafficked from poor northern states (Maranhao, Piaui) through multiple Brazilian states to Para. Though domestic, court's reasoning on state obligation to prevent exploitation during transit through its territory is applicable to international multi-country transit. Brazil ordered to pay reparations and strengthen anti-trafficking framework.",
        "source": "IACtHR / Series C No. 318",
    },
    # ════════════════════════════════════════════════════════════════════════
    # STATISTICS
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "UNODC Global Report — Cross-Border Trafficking Flow Data",
        "metric": "cross_border_trafficking_flows",
        "value": "65% of detected victims trafficked across at least one border",
        "year": 2022,
        "summary": "UNODC Global Report on Trafficking in Persons (2022) found that 65% of detected trafficking victims were trafficked across at least one international border. Of those, 18% crossed two or more borders (3+ countries involved). Sub-Saharan African victims most likely to be detected far from origin (transregional flows). Intra-regional trafficking dominant in South America (93%) and South Asia (91%). Cross-regional routes most common from Southeast Asia to Middle East and from West Africa to Europe.",
        "source": "UNODC Global Report on Trafficking in Persons 2022",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "IOM Flow Monitoring — Transit Point Detection Data",
        "metric": "transit_point_detection_volume",
        "value": "2.4 million migrants monitored at 450+ flow monitoring points",
        "year": 2023,
        "summary": "IOM Displacement Tracking Matrix monitors migration flows at 450+ points across major transit routes in West Africa, East Africa, Middle East, Central America, and Southeast Asia. In 2023, monitored 2.4 million individuals. Key transit hubs: Agadez (Niger), Obock (Djibouti), Tapachula (Mexico), Beni Walid (Libya). 14% of monitored individuals reported experiencing or witnessing exploitation during transit. Women 3x more likely to report transit exploitation than men.",
        "source": "IOM Displacement Tracking Matrix / Flow Monitoring",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "FRONTEX Risk Analysis — Transit Route Intelligence Data",
        "metric": "irregular_border_crossing_detections",
        "value": "330,000+ irregular crossings at EU external borders (2023)",
        "year": 2023,
        "summary": "FRONTEX Risk Analysis identified 330,000+ irregular border crossings at EU external borders in 2023. Central Mediterranean route (Libya/Tunisia to Italy): 157,000. Western Balkans route: 26,000. Eastern Mediterranean (Turkey to Greece/Bulgaria): 14,000. Within these flows, FRONTEX estimates 15-20% of migrants may be trafficking victims. Top transit exploitation zones: Libyan detention centers, Turkish textile workshops, Balkan forest crossing points.",
        "source": "FRONTEX Risk Analysis / Europol EMSC",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Mixed Migration Centre 4Mi — Transit Exploitation Survey Data",
        "metric": "transit_exploitation_prevalence",
        "value": "31% of migrants on Eastern Route report exploitation in transit",
        "year": 2023,
        "summary": "Mixed Migration Centre 4Mi surveys of 30,000+ migrants and refugees across 15 countries (2023) found: Eastern Route (Horn of Africa to Gulf): 31% reported exploitation in transit; Central Mediterranean: 42% reported exploitation in Libya transit; Central America: 28% reported exploitation in Mexico transit. Most common transit exploitation: forced labor (34%), extortion (28%), sexual violence (18%), robbery (15%). Women and unaccompanied minors disproportionately affected. Transit exploitation correlates with number of countries crossed.",
        "source": "Mixed Migration Centre 4Mi / Danish Refugee Council",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "UNODC — Multi-Country Prosecution Success Rate",
        "metric": "cross_border_prosecution_rate",
        "value": "Less than 5% of cross-border trafficking cases prosecuted in multiple countries",
        "year": 2022,
        "summary": "UNODC analysis of trafficking prosecutions globally found that fewer than 5% of cases involving cross-border trafficking result in prosecution in more than one country. 78% of multi-country trafficking cases are prosecuted only in destination country. Transit country prosecution is virtually non-existent: less than 1% of identified cases. Primary barriers: MLAT processing delays (avg 12 months), evidentiary standard differences, resource constraints in transit countries, and lack of specialized cross-border units.",
        "source": "UNODC Global Report 2022 / Eurojust Report 2021",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Re-Trafficking Rates in Multi-Country Trafficking Victims",
        "metric": "re_trafficking_prevalence",
        "value": "22% of identified trafficking victims re-trafficked within 3 years",
        "year": 2021,
        "summary": "IOM study of 50,000+ assisted trafficking victims (2021) found that 22% were re-trafficked within 3 years of initial identification. Re-trafficking most common among victims who were trafficked across multiple countries (29% re-trafficking rate vs 16% for single-country cases). Factors: return to conditions of vulnerability, lack of safe migration pathways, inadequate reintegration support, and continued contact with trafficking networks. Re-trafficking often involves different countries than original route.",
        "source": "IOM Counter Trafficking Data Collaborative (CTDC)",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Europol — Joint Investigation Teams for Trafficking Cases",
        "metric": "JIT_formation_rate",
        "value": "85 JITs for trafficking formed in EU 2017-2022",
        "year": 2022,
        "summary": "Europol facilitated 85 Joint Investigation Teams (JITs) for cross-border trafficking cases 2017-2022, involving 23 EU member states plus 8 third countries. Average JIT duration: 24 months. JITs resulted in 1,200+ arrests and identification of 3,400+ victims. Most common JIT configurations: Romania-UK, Bulgaria-Germany, Nigeria-Italy. Despite increasing numbers, JITs cover only a small fraction of multi-country trafficking: estimated 2-3% of identified cross-border cases.",
        "source": "Europol / Eurojust Annual Report 2022",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "IOM Missing Migrants Project — Transit Route Mortality Data",
        "metric": "transit_route_deaths",
        "value": "28,000+ deaths recorded on migration routes 2014-2023",
        "year": 2023,
        "summary": "IOM Missing Migrants Project documented 28,000+ deaths on migration routes globally 2014-2023. Central Mediterranean (Libya/Tunisia to Italy): 16,000+. US-Mexico border: 4,500+. Sahara Desert: 3,800+ (likely undercount). Deaths are indicator of trafficking and exploitation in transit: victims who die during transit are rarely investigated as trafficking cases. Mortality data underestimates transit exploitation deaths due to remote locations and deliberate concealment by traffickers.",
        "source": "IOM Missing Migrants Project",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "UNODC — Traffickers Convicted Across Multiple Jurisdictions",
        "metric": "multi_jurisdiction_conviction_rate",
        "value": "Only 142 traffickers convicted in more than one country 2010-2022",
        "year": 2022,
        "summary": "UNODC identified only 142 known cases of traffickers convicted in more than one country globally between 2010 and 2022. This represents less than 0.5% of total trafficking convictions worldwide (~30,000 in the same period). Challenges include: double jeopardy protections, extradition treaty limitations, cost of international prosecution, and witness protection across borders. The EU European Investigation Order and Eurojust coordination have improved intra-EU multi-country prosecution but global mechanisms remain inadequate.",
        "source": "UNODC / INTERPOL / Eurojust",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Scam Compound Transit Victims Across Southeast Asia",
        "metric": "scam_compound_victims",
        "value": "220,000+ people estimated held in scam compounds across Myanmar and Cambodia",
        "year": 2023,
        "summary": "UN Human Rights Office estimated 120,000 people held in scam compounds in Myanmar and 100,000 in Cambodia as of 2023, with additional operations in Laos, Philippines, and UAE. Victims recruited from 50+ countries, with majority transiting through 2-3 countries before reaching compounds. Top origin countries: China, Vietnam, Indonesia, India, Malaysia. Multi-country transit deliberately used to complicate rescue and prosecution. Only 3,000+ victims rescued through embassy interventions 2022-2023.",
        "source": "UN Human Rights Office / UNODC 2023 report",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "INTERPOL — Blue Notice Requests for Multi-Country Traffickers",
        "metric": "blue_notice_trafficking_requests",
        "value": "380+ Blue Notices for suspected traffickers active across 3+ countries (2022)",
        "year": 2022,
        "summary": "INTERPOL processed 380+ Blue Notice requests (to collect information on individuals linked to criminal activities) for suspected traffickers operating across 3 or more countries in 2022. This represents a 45% increase from 2018. Top regions: West Africa-Europe route (28%), Southeast Asia (22%), Central America-US (18%). Despite Blue Notice circulation, arrest rates remain low: only 12% of subjects identified and arrested within 24 months. Multi-jurisdictional operations require sustained coordination that most national police forces cannot maintain.",
        "source": "INTERPOL / annual trafficking assessment",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Academic Research — Average Number of Countries in Trafficking Routes",
        "metric": "average_countries_per_route",
        "value": "2.8 countries average for cross-border trafficking routes",
        "year": 2021,
        "summary": "Meta-analysis of 120 trafficking studies (Zhang & Chin 2021, updated Cockbain & Bowers) found average cross-border trafficking route involves 2.8 countries (1 origin, 0.8 transit, 1 destination). Routes from Sub-Saharan Africa to Europe average 3.4 countries. Southeast Asia to Gulf average 2.6 countries. Central America to US average 2.3 countries. Number of transit countries positively correlated with severity of exploitation: each additional transit country adds 15% higher probability of forced labor indicators.",
        "source": "Journal of Human Trafficking / British Journal of Criminology",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Global Modern Slavery Prevalence Along Major Transit Routes",
        "metric": "transit_route_exploitation_density",
        "value": "12 identified high-exploitation-density transit corridors globally",
        "year": 2023,
        "summary": "Walk Free Foundation and IOM identified 12 transit corridors with highest exploitation density: (1) Libya (all routes), (2) Mexico southern border, (3) Thai-Myanmar border, (4) Niger (Agadez), (5) Turkish-Greek border, (6) Yemen coast, (7) Malaysia-Indonesia maritime, (8) Colombia-Panama (Darien), (9) Morocco-Spain, (10) India-Nepal border, (11) Sudan (Kassala), (12) Cambodia-Thailand border. Combined, these 12 corridors account for an estimated 60% of all transit exploitation globally. Each has documented patterns of trafficking network infiltration of migration flows.",
        "source": "Walk Free Foundation / IOM / UNODC",
    },
    # ════════════════════════════════════════════════════════════════════════
    # ADVISORIES
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "UNODC Toolkit on Joint Investigations in Trafficking Cases",
        "summary": "UNODC published comprehensive toolkit (2020) for law enforcement conducting multi-country trafficking investigations. Key components: (1) model JIT agreement templates, (2) evidence sharing protocols compatible with different legal traditions (common law, civil law), (3) witness protection across borders, (4) financial investigation coordination (asset tracing in multiple jurisdictions), (5) victim identification in transit settings. Toolkit adopted by 45+ countries. Practical limitation: requires political will and resource commitment that transit countries often lack.",
        "source": "UNODC",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "INTERPOL Notices on Active Transit Routes — Operation Liberterra",
        "summary": "INTERPOL conducts annual Operation Liberterra targeting multi-country trafficking networks. 2022 operation involved 45 countries, resulted in 240 arrests and identification of 3,200+ potential victims across transit routes. Key focus areas: airports (document fraud detection), maritime borders (fishing vessel inspections), and land crossings (vehicle inspections). INTERPOL issues Purple Notices on trafficking modus operandi including transit exploitation patterns. Real-time information sharing through I-24/7 communication network enables cross-border operational coordination during transit interceptions.",
        "source": "INTERPOL / Project ISON",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "IOM Transit Center Protection Guidance",
        "summary": "IOM operates transit centers and provides protection guidance at major transit points: Agadez (Niger), Obock (Djibouti), Hargeisa (Somalia), Moyale (Ethiopia-Kenya border), Tapachula (Mexico), Villahermosa (Mexico), Cox's Bazar (Bangladesh). Transit centers provide: temporary shelter, vulnerability screening, trafficking victim identification, voluntary return assistance, and information on safe migration. In 2022, IOM transit centers screened 180,000+ migrants and identified 4,500+ potential trafficking victims. Key challenge: migrants fear approaching centers due to potential deportation.",
        "source": "IOM / IOM Voluntary Return Programme",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Regional Early Warning Systems for Trafficking Route Changes",
        "summary": "UNODC and IOM operate regional early warning systems monitoring shifts in trafficking routes: (1) Horn of Africa-Arabian Peninsula (UNODC partnership with Djibouti, Ethiopia, Yemen, Somalia), (2) Southeast Asia Maritime (IOM flow monitoring Thailand, Indonesia, Malaysia), (3) Central Mediterranean (FRONTEX-Europol joint risk analysis), (4) Central America-Mexico (IOM regional monitoring). Systems track indicators: smuggling fee changes, new border crossing points, law enforcement disruptions causing route shifts. Real-time alerts shared with national authorities. Limitation: 2-4 week lag between route shift and detection.",
        "source": "UNODC / IOM / FRONTEX",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "OSCE Guidance on Identifying Trafficking Victims at Borders",
        "summary": "OSCE/ODIHR published guidelines (2022, updated) for border and immigration officers on identifying trafficking victims among migrants in transit. Indicators specific to transit exploitation: (1) person accompanied by controlling individual who speaks for them, (2) evidence of recent physical abuse, (3) inability to state destination or employer name, (4) possession of multiple countries' documents or no documents, (5) signs of recent confinement. Trained border officers in 30+ OSCE participating states. Effectiveness limited by officer turnover and prioritization of security over protection screening.",
        "source": "OSCE/ODIHR / OSCE Special Representative on Trafficking",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "ILO Fair Recruitment Initiative — Transit Country Safeguards",
        "summary": "ILO Fair Recruitment Initiative (2014, extended 2025) includes specific guidance on transit exploitation prevention. Key recommendations: (1) regulate transit agencies and sub-agents in transit countries, (2) require pre-departure orientation to include transit country rights information, (3) establish complaint mechanisms accessible from transit points, (4) mandate that recruitment fees cannot be increased during transit. Pilot programs in Nepal-India-Gulf corridor and Philippines-Singapore-Gulf corridor demonstrated 60% reduction in transit fee inflation when transit agents are licensed.",
        "source": "ILO Fair Recruitment Initiative / ILO REFRAME project",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "UNHCR Transit Country Protection Responsibilities Guidance",
        "summary": "UNHCR guidance note (2019) on protection responsibilities in transit countries establishes that: (1) refugees and asylum-seekers in transit retain full Convention rights, (2) transit states must provide access to asylum procedures, (3) trafficking screening must occur before any return or removal, (4) detention of trafficking victims in transit is prohibited. Particularly relevant for mixed migration flows where refugees and trafficking victims travel on same routes (Central Mediterranean, Eastern Route, Central America). Implementation remains inconsistent across major transit countries.",
        "source": "UNHCR / UNHCR Transit Country Protection Note",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Europol EMSC — Transit Route Intelligence Sharing Protocol",
        "summary": "European Migrant Smuggling Centre (EMSC) at Europol coordinates intelligence on transit routes used by trafficking and smuggling networks. Publishes quarterly Threat Assessment with route-specific analysis. Key intelligence products: (1) route mapping with exploitation hotspots, (2) network analysis of facilitators operating across multiple countries, (3) financial flow tracking along transit routes, (4) document fraud patterns by route. Shared with 40+ partner countries through Europol information exchange. Since 2016, EMSC contributed to 1,500+ cross-border investigations involving transit exploitation elements.",
        "source": "Europol European Migrant Smuggling Centre",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "FATF Guidance on Financial Flows Related to Multi-Country Trafficking",
        "summary": "Financial Action Task Force (FATF) published guidance (2018, updated 2023) on identifying financial indicators of multi-country trafficking. Key transit-related indicators: (1) hawala/informal value transfer between transit countries, (2) multiple small cash deposits in transit city branches, (3) mobile money transfers along known transit routes, (4) rental payments for safe houses in transit cities, (5) payment patterns matching known smuggling-trafficking fee structures. 12 countries implemented FATF-compliant anti-trafficking financial monitoring. Banks in transit hubs (Istanbul, Dubai, Nairobi, Mexico City) trained on trafficking-specific transaction monitoring.",
        "source": "FATF / Egmont Group / UNODC",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Global Compact on Migration — Transit Protection Provisions",
        "summary": "Global Compact for Safe, Orderly and Regular Migration (2018) includes specific provisions on transit country responsibilities. Objective 7: address vulnerabilities in migration including during transit. Objective 10: prevent and combat trafficking in transit. Objective 15: provide access to basic services in transit countries. Non-binding but adopted by 152 UN member states. Implementation via regional review forums. Criticized for lacking enforcement mechanism and for conflating transit migration management with border security. First review (2022 IMRF) found limited progress on transit protection.",
        "source": "UN General Assembly / IOM / IMRF 2022",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Santa Marta Group — Law Enforcement and Church Collaboration on Transit Routes",
        "summary": "Santa Marta Group (launched 2014, Vatican) brings together senior police officers and Catholic Church leaders to combat trafficking along transit routes. Operates in 35 countries. Church networks in transit countries (parish-level reporting, shelter provision, pastoral outreach) provide intelligence to law enforcement on trafficking patterns. Documented 400+ referrals from church networks to police in transit settings 2018-2023. Most effective in Latin America (Mexico transit) and Southeast Asia (Philippines-Malaysia corridor). Model for civil society-law enforcement cooperation on transit exploitation detection.",
        "source": "Santa Marta Group / Bishops' Conference of England and Wales",
    },
    # ════════════════════════════════════════════════════════════════════════
    # REGULATION CHANGE
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "regulation_change",
        "jurisdiction": "EU",
        "title": "EU Revised Anti-Trafficking Directive — Proposed 2023 Amendments",
        "summary": "European Commission proposed revision to Directive 2011/36/EU in December 2022 (adopted April 2024). Key additions relevant to transit routes: (1) forced criminality explicitly included as exploitation purpose (cannabis cultivation, pickpocketing), (2) knowingly using services of trafficking victims criminalized, (3) online exploitation platform responsibility, (4) mandatory national referral mechanisms with cross-border provisions. Requirement for member states to establish formal cooperation frameworks with transit countries outside EU. Expected to improve identification of victims exploited during transit through EU territory.",
        "source": "European Commission / EUR-Lex",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "TH",
        "title": "Thailand Anti-Trafficking Amendment — Transit Country Provisions 2019",
        "summary": "Thailand amended Anti-Trafficking in Persons Act (2019) to explicitly address its role as both destination and transit country. New provisions: (1) criminalize facilitation of transit trafficking even where exploitation occurs outside Thailand, (2) establish transit trafficking screening at major border crossings (Mae Sot, Aranyaprathet, Sadao), (3) create inter-agency coordination center for transit trafficking cases involving Myanmar, Cambodia, and Laos. Implementation supported by ILO and IOM. Results: 45 transit trafficking cases identified 2019-2022, up from zero previously.",
        "source": "Thailand Royal Gazette / ILO Bangkok / UNODC",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "MX",
        "title": "Mexico Transit Migration and Trafficking Reforms 2021-2023",
        "summary": "Mexico enacted reforms to General Law on Victims (2021) and Migration Law (2022) strengthening protections for trafficking victims in transit. Key changes: (1) humanitarian visa for trafficking victims identified in transit regardless of migration status, (2) specialized prosecutor units for transit trafficking in Chiapas, Tabasco, and Tamaulipas, (3) mandatory screening for trafficking at immigration checkpoints, (4) prohibition on detention of identified trafficking victims. Implementation challenged by resource constraints and corruption. INM (National Migration Institute) trained 2,000+ officers on transit trafficking identification 2022-2023.",
        "source": "Mexico DOF (Official Gazette) / CNDH Mexico / IOM Mexico",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "NE",
        "title": "Niger Anti-Smuggling Law 2015 — Impact on Transit Trafficking",
        "summary": "Niger's Loi 2015-36 criminalizing migrant smuggling had unintended consequences for transit trafficking. By driving smuggling underground, routes became more dangerous and trafficking more common. Before 2015: Agadez was open transit hub with some regulation. After 2015: clandestine routes through desert with higher mortality and exploitation. Mixed Migration Centre documented 50% increase in reported transit exploitation after law implementation. Niger revised approach in 2021 to distinguish between smuggling and trafficking, providing protection for trafficking victims while maintaining anti-smuggling enforcement.",
        "source": "Mixed Migration Centre / UNODC / Niger Ministry of Justice",
    },
    # ════════════════════════════════════════════════════════════════════════
    # ADDITIONAL CASE STUDIES — Emerging routes and patterns
    # ════════════════════════════════════════════════════════════════════════
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Indian Nationals Through Serbia and Bosnia to Western Europe",
        "route": "IN-RS-BA-HR-AT/DE",
        "transit_countries": ["RS", "BA", "HR"],
        "summary": "Emerging route since 2021: Indian nationals fly to Serbia (visa-free), then are smuggled through Bosnia-Herzegovina and Croatia into Austria or Germany. Workers promised IT or hospitality jobs but exploited in construction and agriculture. Serbian transit used because of visa-free access from India. Europol documented 45+ organized networks operating this route in 2023. Workers pay EUR 10,000-15,000 to smuggling-trafficking networks. Croatian police intercepted 3,500+ Indian migrants on this route in 2023 alone.",
        "source": "Europol / Croatian Border Police / IOM Belgrade",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Tunisian and Libyan Routes Through Turkey to Northern Europe",
        "route": "TN/LY-TR-BG/GR-DE/SE",
        "transit_countries": ["TR", "BG"],
        "summary": "Tunisian and Libyan nationals travel to Turkey (Istanbul) where they join established smuggling-trafficking routes into Bulgaria or Greece, then onward to Germany and Scandinavia. In Turkish transit, workers exploited in textile workshops and construction for weeks or months to fund onward journey. Bulgarian transit involves exploitation in agricultural labor near Harmanli and Sofia. UNHCR Bulgaria documented that 25% of asylum seekers entering through Turkey reported forced labor during Turkish transit phase (2022 data).",
        "source": "UNHCR Bulgaria / IOM Turkey / FRONTEX",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Ugandan Domestic Workers Through Kenya and UAE to Oman",
        "route": "UG-KE-AE-OM",
        "transit_countries": ["KE", "AE"],
        "summary": "Ugandan women recruited for domestic work in Oman transit through Kenya (Nairobi JKIA) and UAE (Dubai) where agents add fees and change contract terms. Workers arrive in Oman with debts of USD 2,000-4,000 and confiscated passports. Uganda's External Employment Unit documented 180+ complaints of multi-country transit exploitation on this route 2019-2023. Transit through UAE specifically used to circumvent Uganda's bilateral agreements with Oman which require direct deployment.",
        "source": "Uganda External Employment Unit / IOM Kampala / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Uyghur Forced Labor Through China-Central Asia Supply Chains",
        "route": "CN(XJ)-KZ/UZ-global",
        "transit_countries": ["KZ", "UZ"],
        "summary": "Products manufactured under conditions of forced labor in Xinjiang, China are transshipped through Kazakhstan and Uzbekistan to circumvent US Uyghur Forced Labor Prevention Act (UFLPA) import bans. Workers in Xinjiang internment-linked facilities produce cotton, polysilicon, and tomato products that enter global supply chains via Central Asian transshipment. US Customs and Border Protection issued 67 Withhold Release Orders related to Xinjiang goods 2021-2024. Central Asian transit obscures product origin, creating jurisdictional enforcement gaps for forced labor imports.",
        "source": "US CBP / Australian Strategic Policy Institute / Sheffield Hallam University",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Gender Disparities in Multi-Country Transit Exploitation",
        "metric": "gender_transit_exploitation_rate",
        "value": "Women 2.5x more likely to experience exploitation during multi-country transit",
        "year": 2022,
        "summary": "IOM Counter Trafficking Data Collaborative analysis (2022) of 150,000+ case records found women are 2.5 times more likely to experience exploitation during multi-country transit compared to men. Women transit victims: 68% experienced sexual exploitation (in addition to labor exploitation), vs 4% for men. Average transit duration for women (7.2 months) exceeds men (4.8 months). Women with children face highest vulnerability: 41% reported exploitation at every transit point. Unaccompanied minors (both genders) had 3.2x higher exploitation rate than adults.",
        "source": "IOM CTDC / UNODC Gender Report 2022",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "UNODC Model Legislative Provisions on Transit Country Obligations",
        "summary": "UNODC published Model Legislative Provisions against Trafficking in Persons (2020 update) including specific guidance on transit country legislation. Key recommendations: (1) criminalize transit facilitation as distinct offence with penalties proportionate to destination exploitation, (2) establish mandatory victim identification at border and immigration points, (3) provide temporary residence permits for trafficking victims identified in transit, (4) create bilateral protocols with neighboring origin and destination countries, (5) fund specialized transit trafficking investigation units. Only 18 countries have implemented all 5 recommended provisions as of 2024.",
        "source": "UNODC / Model Legislative Provisions",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "LY",
        "title": "Libya Anti-Trafficking Legislation Attempts and Enforcement Gaps",
        "summary": "Libya enacted Law No. 10 of 2013 on criminalizing trafficking in persons but enforcement has been virtually non-existent due to ongoing conflict and fragmented governance. Despite being the primary transit country for Central Mediterranean route (200,000+ migrants transit annually), Libya recorded zero trafficking convictions 2013-2023. UNSMIL documented that militia groups controlling detention centers commit trafficking with impunity. GNA (Government of National Accord) and DCIM (Directorate for Combating Illegal Migration) have been implicated in trafficking by UN Panel of Experts. International community has focused on upstream and downstream countries rather than addressing Libya's central role as transit exploitation hub.",
        "source": "UNSMIL / UN Panel of Experts on Libya / OHCHR",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Myanmar-Thailand-Japan Technical Intern Training Programme Exploitation",
        "route": "MM-TH-JP",
        "transit_countries": ["TH"],
        "summary": "Myanmar workers recruited for Japan's Technical Intern Training Programme (TITP) transit through Thailand where sending organizations inflate fees beyond Japanese government caps. Workers spend 2-8 weeks in Thai language and skills training centers where additional charges accumulate. Total debt on arrival in Japan: USD 7,000-12,000 (vs legal maximum of approximately USD 3,600). Japanese OTIT (Organization for Technical Intern Training) documented 150+ cases where Thai transit fees contributed to debt bondage conditions in Japan 2018-2023. Myanmar-Thailand open border complicates regulation of transit sending organizations.",
        "source": "Japan OTIT / ILO Tokyo / Issara Institute",
    },
]
