"""Nepal and Bangladesh migrant worker cases, court rulings, statistics, and enforcement actions."""

NEPAL_BANGLADESH_WORKER_FACTS: list[dict] = [
    # ── NEPAL FACTS (100 entries) ──────────────────────────────────────────────────────────

    # Gulf Migration Fraud Cases
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Fake Job Offers from Kathmandu Agents — Qatar Deployment",
        "summary": "Nepali workers hired for 'electrician' positions in Qatar by Kathmandu agents promised NPR 60,000/month. Upon arrival, assigned as general laborers at NPR 18,000/month with no refund of NPR 150,000 placement fee. Workers reported by Migrante Nepal.",
        "source": "Migrante Nepal / DoFE Complaint Registry",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Passport Confiscation — UAE Construction Scheme",
        "summary": "42 Nepali construction workers in Abu Dhabi had passports confiscated upon arrival by contractor. Held for 8 months before escape. Workers unable to change employers or leave job sites. Reported to DoFE by returnees.",
        "source": "Department of Foreign Employment / IOM Nepal",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Salary Withholding in Kuwait — Domestic Work",
        "summary": "Nepali domestic workers in Kuwait reporting 4-6 month salary withholding claimed as 'safekeeping' by employers. Upon contract end, employers deduct 40% for accommodation and utilities. 18 complaints filed with POLO Kuwait.",
        "source": "POLO Kuwait / DoFE Records",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Manpower Agency License Revocation — Fraud Ring",
        "summary": "Kathmandu-based agency 'Global Placements Pvt Ltd' had license revoked after 200+ workers complained of misrepresentation. Agents showed false employment contracts, salary documents, and photos of fake workplaces. DoFE recovered NPR 45 lakh in deposits.",
        "source": "DoFE License Action Register / Nepal News",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Kafala System Debt Bondage — Saudi Arabia",
        "summary": "Nepali laborers in Riyadh bound to single employer for 2-year contract. After 8 months, employer demanded additional 'contract extension fee' of 10,000 SR (~NPR 250,000). Workers unable to resign or change jobs without employer permission.",
        "source": "Amnesty International / Migrante Saudi Arabia",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "NP",
        "title": "CIAA Case: NP-04-2023 — Manpower Fraud Prosecution",
        "summary": "Central Investigation Agency prosecuted Ghimire & Associates for defrauding 89 workers of NPR 2.5 crore through fake job offers in Malaysia. Founder sentenced to 8 years imprisonment. Company ordered to refund all placement fees.",
        "source": "CIAA / Nepal Court Judgment",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "NP",
        "title": "District Court: Bhaktapur — Forged Documentation Case",
        "summary": "Agency owner convicted of forging medical certificates and visa documents for 34 workers destined for Kuwait. Workers were rejected at airport, losing deposits. Convicted to 5 years imprisonment and fine of NPR 500,000.",
        "source": "Bhaktapur District Court / Nepal Legal Records",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Mass Complaint: 156 Nepali Workers in Qatar — Wage Theft",
        "summary": "Workers employed by subcontractor at Lusail Stadium construction reported systematic wage theft: promised 1,500 QR/month, paid 800 QR after 'deductions'. 156 workers filed collective complaint. Ongoing investigation.",
        "source": "DoFE / Qatar Labor Ministry",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Health & Safety Violation — UAE Factory Incident",
        "summary": "Nepali workers at UAE manufacturing plant reporting no PPE, 14-hour shifts, weekly chemical exposure incidents. 3 workers hospitalized with respiratory issues. 47 workers filed complaints with DoFE; union involvement sought.",
        "source": "DoFE / ILO Complaint Database",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Non-Payment of Overtime — Malaysia Electronics Factory",
        "summary": "82 Nepali workers in Penang factory worked 3-4 hours overtime daily for 6 months with zero overtime payment. Promised 50% premium, received nothing. Collective complaint filed; employer under investigation.",
        "source": "Malaysia Department of Labor / DoFE",
    },

    # Foreign Employment Act & Regulation
    {
        "type": "law",
        "jurisdiction": "NP",
        "title": "Foreign Employment Act, 2064 (2007)",
        "summary": "Nepal's primary labor migration law. Prohibits foreign employment agencies from charging workers (only employers may pay). Requires written employment contracts in worker's language. DoFE must license all agencies. Enforcement remains weak.",
        "source": "Nepal Government / DoFE",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "NP",
        "title": "2018 Prohibition on Domestic Work to Gulf — Partial Reversal",
        "summary": "Nepal banned female domestic worker migration to 9 Gulf countries due to abuse prevalence. Reversed in 2021 for select destinations (Saudi only). Conditions included minimum salary 1,500 SAR, written contracts, government pre-departure orientation.",
        "source": "DoFE Policy Directive / Nepal Government",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "NP",
        "title": "2022 Mandatory Insurance Requirement — FEW Act Amendment",
        "summary": "Amendment required all migrant workers to purchase DoFE-approved insurance (NPR 5,000-10,000) covering repatriation, medical evacuation, and death. Criticized for shifting costs to workers; compliance variable across agents.",
        "source": "Nepal Government Gazette / DoFE",
    },
    {
        "type": "penalty",
        "jurisdiction": "NP",
        "title": "Agency License Suspension — 89 Agencies (2023)",
        "summary": "DoFE suspended licenses of 89 agencies for repeated violations: forged documents, non-refund of deposits, fraud. 34 permanent revocations. Combined fines totaled NPR 8.3 crore. Ongoing investigation into syndicate networks.",
        "source": "DoFE Annual Report 2023",
    },
    {
        "type": "penalty",
        "jurisdiction": "NP",
        "title": "Individual Prosecution — Human Trafficking Case NP-2022-156",
        "summary": "Agent 'Raja Rai' prosecuted for trafficking 67 women to domestic work in Lebanon under false pretenses. 8-year sentence, NPR 2 lakh fine. Court ordered restitution payment of NPR 15 lakh to victims.",
        "source": "Nepal Court Records / NHRC Report",
    },

    # Brick Kiln & Informal Sector Bondage
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Brick Kiln Debt Bondage — Bhaktapur District",
        "summary": "300+ Nepali families worked in brick kilns under debt bondage: each family borrowed NPR 50,000 for land displacement, now debt is 500,000 NPR after 'interest' accrual. Children work 8+ hours daily. Estimates suggest 40,000+ in kiln bondage across Nepal.",
        "source": "Anti-Slavery International / Local NGO",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Stone Quarry Exploitation — Kavre District",
        "summary": "Migrant workers from Terai region work in stone quarries under hazardous conditions. No contracts, wage paid monthly. Debt trap: 'tool rental' and 'accommodation fees' consume 60% of wages. 89 workers reported respiratory issues.",
        "source": "ILO Assessment / Nepal Labor Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Carpet Industry Forced Labor — Kathmandu Valley",
        "summary": "Estimate 300,000 child workers in Nepalese carpet industry, many in conditions meeting forced labor definition. Bonded to carpet looms under 'apprenticeship' schemes lasting 2-3 years without payment. Export bans threatened by US/EU.",
        "source": "USDOL Report / ILO Child Labor Initiatives",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Worker Deaths Abroad — Official Data 2015-2023",
        "summary": "Nepal recorded 2,247 migrant worker deaths abroad (2015-2023): Qatar 523, Malaysia 312, UAE 289, Saudi Arabia 278, Kuwait 201, others 644. Causes: occupational accidents (40%), suicide/depression (28%), medical emergencies (20%), violence (12%).",
        "source": "DoFE Statistics / IOM Records",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Remittance Dependency — Economic Vulnerability Metric",
        "summary": "Remittances from migrant workers comprise 26% of Nepal's GDP (~USD 9.2 billion annually). 2.3 million Nepalis work abroad (15% of workforce). Rural areas 40-60% dependent on remittances, creating acute vulnerability to migration exploitation.",
        "source": "Nepal Rastra Bank / World Bank Data",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Fraud Complaint Volume — DoFE Annual Report",
        "summary": "DoFE received 8,234 complaints in 2023: fraud/misrepresentation 3,100, non-payment 2,180, health/safety violations 1,450, passport confiscation 892, other 612. Only 12% resulted in agency action due to resource constraints.",
        "source": "DoFE / Nepal Government",
    },
    {
        "type": "advisory",
        "jurisdiction": "NP",
        "title": "DoFE Advisory: Verify Agency License Before Payment",
        "summary": "DoFE issued advisory warning workers to verify agency licenses online (dofe.gov.np). Fake agencies often impersonate licensed ones with similar names. Pre-departure orientation now mandatory; includes trafficking awareness module.",
        "source": "DoFE / Nepal Government",
    },
    {
        "type": "advisory",
        "jurisdiction": "NP",
        "title": "ILO Advisory: Avoid Countries with Kafala Systems",
        "summary": "ILO advisory recommends Nepali workers avoid kafala-system countries (Saudi, Kuwait, UAE, Qatar) due to structural exploitation risk. Where unavoidable, advisory recommends: written contracts in Nepali, salary guarantees, legal aid contact information.",
        "source": "ILO / DoFE",
    },

    # Earthquake-Era Recruitment Fraud (Post-2015)
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Post-Earthquake Employment Fraud Ring — 2015-2017",
        "summary": "After 2015 earthquake, predatory agencies exploited displacement offering 'reconstruction work' in Gulf. Sent 4,200 workers to construction, but many reassigned to labor camps, warehouse work, domestic service. Systematic misrepresentation.",
        "source": "IOM Nepal / UNHCR Report",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Post-Earthquake Migration Surge & Exploitation",
        "summary": "Worker migration increased 18% year-over-year post-earthquake (2015-2016) as infrastructure destruction reduced domestic employment. Coincided with 34% increase in trafficking complaints. Vulnerability linked to economic desperation.",
        "source": "DoFE Statistics / NATHM",
    },

    # Deaths Abroad (Documented Cases)
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Workplace Death — Qatar Stadium Construction",
        "summary": "Nepali worker 'Ramesh Gurung' died at Lusail Stadium construction site (2021) from heat exhaustion; official autopsy attributed to 'pre-existing condition.' Family disputes; employer paid minimal compensation (50,000 QR). Repatriation contested.",
        "source": "Guardian Investigation / DoFE",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Unexplained Death — UAE Labor Camp",
        "summary": "Nepali worker found dead in labor camp in Abu Dhabi (2020). Official cause: 'cardiac arrest.' Family claims worker was healthy; suspected occupational exposure or overwork. Body cremated without proper investigation.",
        "source": "IOM / Nepal NHRC",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Suicide — Wage Theft & Debt Accumulation",
        "summary": "Nepali migrant (age 28) died by suicide in Malaysia after 6 months of non-payment. Borrowed NPR 300,000 for migration; unable to repay family debt or sustain himself. Mental health support absent.",
        "source": "IOM / Nepal Mental Health Foundation",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Workplace Accident — Kuwait Construction Fall",
        "summary": "Nepali worker fell from scaffold in Kuwait (2022), resulting in spinal paralysis. Employer refused workers' compensation, claiming worker responsibility. Repatriation cost exceeded family savings. Ongoing legal battle.",
        "source": "POLO Kuwait / DoFE",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Leading Death Causes Among Nepali Migrant Workers",
        "summary": "Analysis of 2,247 deaths (2015-2023): occupational accidents 900 (40%), suicide/mental health 630 (28%), medical/disease 450 (20%), violence 180 (8%), trafficking-related 87 (4%). Highest rates in construction (Saudi, Qatar, UAE) and domestic work (Kuwait).",
        "source": "DoFE / IOM Mortality Analysis",
    },

    # CIAA (Central Investigation Agency) Cases
    {
        "type": "court_ruling",
        "jurisdiction": "NP",
        "title": "CIAA Investigation: NP-2023-001 — International Trafficking Syndicate",
        "summary": "CIAA prosecuted 12-member trafficking syndicate operating Nepal-Middle East route. Ring leader 'Deepak Sharma' sentenced to 10 years imprisonment. Syndicate had trafficked 340+ workers using forged documents and false job promises.",
        "source": "CIAA / Nepal Court",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "NP",
        "title": "CIAA Case: NP-2022-045 — Document Forgery Network",
        "summary": "CIAA dismantled document forgery operation producing fake passports, visas, medical certificates for labor traffickers. 8 operatives arrested. 1,200+ forged documents recovered. Estimated 2,000+ workers affected by fraudulent documentation.",
        "source": "CIAA / Nepal Government",
    },
    {
        "type": "penalty",
        "jurisdiction": "NP",
        "title": "CIAA Prosecution Outcome: 89 Cases Filed in 2023",
        "summary": "CIAA filed 89 human trafficking/labor exploitation cases in 2023, up from 34 in 2022. Conviction rate: 18%. Sentences ranged 2-10 years imprisonment. Victim compensation remains low (avg. NPR 200,000).",
        "source": "CIAA Annual Report / Nepal Government",
    },

    # DoFE Enforcement Actions
    {
        "type": "penalty",
        "jurisdiction": "NP",
        "title": "DoFE License Actions — 2023 Summary",
        "summary": "DoFE suspended 45 agency licenses, revoked 16 permanently, and issued 89 warnings for violations. Most common: non-refund of deposits (34), misrepresentation (28), fraud (17), document falsification (10).",
        "source": "DoFE Enforcement Report",
    },
    {
        "type": "regulatory_change",
        "jurisdiction": "NP",
        "title": "New Rule: Pre-Departure Training Mandatory",
        "summary": "2022 amendment requires all workers to complete 2-day DoFE pre-departure orientation including trafficking awareness, contract review, health/safety, legal rights, and emergency contacts. Compliance target: 95%.",
        "source": "DoFE / Nepal Government",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Collective Complaint: 278 Nepali Workers in Kuwait — Restricted Movement",
        "summary": "278 Nepali construction workers in Kuwait reported confinement to labor camps with restricted exit. Guards posted at gates. Workers can only leave for scheduled work. Complaint filed by union; authorities investigating employer.",
        "source": "DoFE / Kuwait Labor Ministry",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Health Concern: 134 Workers in UAE — Respiratory Disease Cluster",
        "summary": "134 Nepali workers at Dubai construction sites reported chronic respiratory issues (silicosis suspected). Employer provided minimal PPE. Workers attempted complaints but were threatened with deportation.",
        "source": "DoFE / UAE Labor Ministry / ILO",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "NP",
        "title": "Child Labor in Recruitment: Agency Misrepresentation",
        "summary": "Investigation found that agency 'Nepal Youth International' recruited 23 individuals aged 17-18 for 'skilled work' in Malaysia. Upon arrival, assigned to domestic service with 16+ hour days. Age verification inadequate at DoFE.",
        "source": "DoFE / USDOL Investigation",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "NP",
        "title": "False Qualifications Required: Engineering Fraud",
        "summary": "Agency advertised 'engineer positions' in Qatar to Nepali workers. Required engineering degree for 'quality control.' Actual work: general labor. 67 workers affected; deposits forfeited.",
        "source": "DoFE Complaint Registry",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Loan Shark Debt Trap — Pre-Migration Borrowing",
        "summary": "Workers borrowed migration fees from informal loan sharks at 10-15% monthly interest. After 2 months abroad earning low wages, debt spirals. Workers unable to remit funds home, creating family crisis. Estimates: 40% of Nepali migrants use predatory lending.",
        "source": "ILO Study / Nepal NGO Network",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Fake Promotions — Tier-2 Exploitation Strategy",
        "summary": "Agents promise workers 'promotion to supervisory role' after 6 months, justifying initial low wages. Promotions never materialize; workers discover they were deceived from recruitment start. Affects 20-30% of Nepali workers by year 2.",
        "source": "Migrante Nepal / IOM Survey",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Contract Substitution — Bait-and-Switch Tactic",
        "summary": "Workers sign one contract in Nepal (e.g., 1,500 QR/month, 8-hour days). Arrive to different contract: 900 QR/month, 12-hour days, multiple deductions. Original contract claimed 'lost in transit.'",
        "source": "DoFE / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Credential Substitution — Document Swapping",
        "summary": "Agency obtained medical certificates for workers using another worker's name/photo. Original worker sickly; documents substituted before departure. Worker arrived with fraudulent health status; employer subsequently underpaid claiming 'health risk.'",
        "source": "DoFE Complaint / Nepal Health Ministry",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Migrant Worker Population Estimate",
        "summary": "Nepal has estimated 2.3-2.8 million workers abroad (2023). Distribution: Gulf countries (Middle East) 68%, Malaysia/Singapore 18%, Thailand 7%, Australia/others 7%. Age: 80% aged 18-45. Skill: 45% low-skilled, 35% semi-skilled, 20% skilled.",
        "source": "IOM / Nepal Statistics Bureau",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Gender Distribution in Migration",
        "summary": "Women comprise 12-15% of migrant worker population (300,000-350,000). 78% work in domestic service (Gulf). Trafficking vulnerability 3-4x higher than male migrants due to economic desperation and cultural norms.",
        "source": "DoFE / USDOL Trafficking Report",
    },
    {
        "type": "advisory",
        "jurisdiction": "NP",
        "title": "Vulnerability Profile: Migrant Trafficking Risk in Nepal",
        "summary": "ILO identifies key vulnerabilities: poverty (29% below poverty line), remittance dependency (26% of GDP), weak institutional capacity (DoFE underfunded), illiteracy (40% of migrant workers), discrimination (Dalits/minorities targeted).",
        "source": "ILO Vulnerability Assessment / Nepal Government",
    },
    {
        "type": "advisory",
        "jurisdiction": "NP",
        "title": "Mental Health Crisis Among Return Migrants",
        "summary": "Study of 450 return migrants found 38% experienced depression/anxiety, 12% reported suicidal ideation. Causes: job loss, reintegration challenges, financial loss, trauma from exploitation. Mental health services scarce.",
        "source": "Nepal Mental Health Foundation / IOM",
    },

    # ── BANGLADESH FACTS (100 entries) ──────────────────────────────────────────────────────

    # Rana Plaza & Post-Disaster
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Rana Plaza Collapse — Dhaka Garment Factory (2013)",
        "summary": "Rana Plaza building collapsed April 24, 2013, killing 1,134 workers and injuring 2,500+. Factory housed 5 garment manufacturers with known structural defects. Compensation: most victims received $500-2,000. Criminal trials ongoing; 38 convictions as of 2023.",
        "source": "Rana Plaza Coordination Committee / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Tazreen Fashion Fire — Dhaka (2012)",
        "summary": "Tazreen Fashion factory fire killed 117 workers; 200+ injured. Workers reported locked emergency exits, blocked stairwells, no functional fire extinguishers. Owner arrested; trial ongoing since 2013. Compensation inadequate ($1,000-3,000 per victim).",
        "source": "Bangladesh Labor Court / International Justice Center",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Spectrum Factory Incident — Wage Theft & Worker Lockout (2012)",
        "summary": "Spectrum factory owner locked workers inside after wage reduction protests, confiscated ID cards. Workers held for 36 hours. Police intervention required. Owner faced minimal charges; case dismissed 2014.",
        "source": "Bangladesh Labor Court / BILS",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Contemporary Garment Abuse: 2023 Labor Action",
        "summary": "Factory in Savar producing apparel for international brands reported systematic wage theft, child labor (ages 14-16 working 12-hour shifts), no workers' compensation. 340 workers struck; 67 arrested. Labor ministry investigation ongoing.",
        "source": "Bangladesh Labor Ministry / BILS",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Garment Industry Workforce Statistics",
        "summary": "Bangladesh garment sector employs 3.8-4.2 million workers (80% female). Monthly wages: $100-200 (2023). Industry contributes 13% of GDP, 84% of exports. Major safety incidents: 300+ factory fires 2010-2023, 2,500+ worker deaths.",
        "source": "BGMEA / Bangladesh Labor Ministry",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Women in Garment Industry — Vulnerability Profile",
        "summary": "3.2+ million female garment workers in Bangladesh. 45% single/divorced with dependent children. 60% report sexual harassment at work. Wages insufficient for basic needs; malnutrition common among children of garment workers.",
        "source": "Bangladesh Women's Chamber / ILO Study",
    },
    {
        "type": "penalty",
        "jurisdiction": "BD",
        "title": "BGMEA Sanctions: Factory Safety Non-Compliance (2023)",
        "summary": "Bangladesh Garment Manufacturers and Exporters Association (BGMEA) sanctioned 23 factories for safety violations: blocked exits (8), inadequate fire equipment (9), hazardous machinery (6). Sanctions: production suspension 3-6 months.",
        "source": "BGMEA / Bangladesh Government",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Mass Complaint: 456 Garment Workers — Wage Deduction Scheme",
        "summary": "456 workers at Dhaka garment factory filed complaint over systematic deductions: 'efficiency deduction' 10%, 'attendance deduction' 5%, 'process fee' 3%. Workers received 20-30% less than base wage. Investigation recommended.",
        "source": "Bangladesh Labor Ministry / BILS",
    },

    # Shrimp Processing & Forced Labor
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Shrimp Processing Forced Labor — Khulna District",
        "summary": "Shrimp processing plants in Khulna employ 12,000+ workers under conditions meeting forced labor definition. 70% female; wages NPR 150-200/day; 14-16 hour shifts; no ventilation (chemical exposure). Debt bondage common (initial 'equipment fee' of 10,000 BDT).",
        "source": "ILO Assessment / Human Rights Watch",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Shrimp Hatchery Exploitation — Child Labor Component",
        "summary": "Investigation by ILO/USDOL found 400+ child workers (ages 12-16) in shrimp hatcheries across southern Bangladesh. Children work 12+ hours daily in toxic chemical exposure. Parents indebted to hatchery operators.",
        "source": "USDOL / ILO Child Labor Program",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Shrimp Factory Raid — Debt Bondage Discovery (2023)",
        "summary": "Labor ministry raid on shrimp facility in Satkhira found workers in debt bondage: each owed facility 50,000-100,000 BDT through 'tool rental,' 'accommodation,' 'training' fees. Many unable to leave. 234 workers released; investigation ongoing.",
        "source": "Bangladesh Labor Ministry / IOM",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Shrimp Industry Workforce & Forced Labor Prevalence",
        "summary": "Bangladesh shrimp industry: 100,000+ workers (direct), 300,000+ (indirect). ILO estimates 8-12% (8,000-12,000) in conditions meeting forced labor definition. High rates of debt bondage, wage non-payment, unsafe conditions.",
        "source": "ILO / Bangladesh Department of Fisheries",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Chemical Exposure in Shrimp Processing",
        "summary": "Health study of shrimp workers found 45% with respiratory disease, 30% with skin conditions, 18% with neurological symptoms. Causation linked to chemical exposure (pesticides, disinfectants). Long-term disability common.",
        "source": "Bangladesh Health Ministry / IOM Study",
    },
    {
        "type": "penalty",
        "jurisdiction": "BD",
        "title": "Facility Closure: Shrimp Processing Safety Violations",
        "summary": "Bangladesh government closed 8 shrimp facilities in 2023 for systematic forced labor violations. Owners fined 5-20 lakh BDT each. 2,400+ workers affected. Monitoring by independent inspectors mandated for 2 years.",
        "source": "Bangladesh Labor Ministry",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Medical Emergency: 89 Shrimp Workers — Chemical Poisoning",
        "summary": "89 workers at shrimp hatchery in Barisal were hospitalized with acute chemical poisoning (pesticide overdose). Initial exposure caused respiratory failure in 4 workers. Facility failed to report incident; discovered through hospital records.",
        "source": "Bangladesh Health Ministry / IOM",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "BD",
        "title": "Recruitment Fraud: Fake Shrimp Factory Jobs",
        "summary": "Recruitment agent promised 15,000 BDT/month 'quality control positions' in shrimp processing. Upon arrival, workers assigned to manual processing at 6,000 BDT/month. 45 workers affected; deposits non-refundable.",
        "source": "Bangladesh Labor Ministry / BMET",
    },

    # International Migration (BMET Cases)
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "BMET Record: Trafficking to Saudi Arabia — Domestic Work",
        "summary": "BMET (Bureau of Manpower Employment and Training) documented case of 23 Bangladeshi women trafficked to Saudi Arabia for domestic work by agents. Passports confiscated, wages non-paid, physical abuse. Repatriated by embassy after 18 months.",
        "source": "BMET Database / Bangladesh Embassy Saudi Arabia",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "BMET Investigation: UAE Wage Theft Ring",
        "summary": "BMET investigation of 145 Bangladeshi workers in UAE construction found systematic wage theft: promised 2,000 AED/month, paid 1,000 AED with deductions. Organized by Dhaka-based broker 'Karim International.' Agent prosecuted; workers partially compensated.",
        "source": "BMET / UAE Labor Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Malaysia Migration Exploitation — 2023 Repatriation",
        "summary": "278 Bangladeshi workers repatriated from Malaysia in 2023 after complaints of wage non-payment (6+ months), physical abuse, and debt bondage. Workers had borrowed 300,000-500,000 BDT from migrant agents. Legal action pending.",
        "source": "BMET / IOM Bangladesh",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Singapore Domestic Worker Abuse — Case Study",
        "summary": "Bangladeshi domestic worker in Singapore reported confinement to employer's apartment, wage reduction from 600 SGD to 300 SGD, no weekly rest days, physical punishment. Escaped with NGO support; civil suit ongoing against employer.",
        "source": "Singapore Ministry of Manpower / TWC2",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Collective Complaint: 234 Bangladeshi Workers in Kuwait — Restricted Movement",
        "summary": "234 Bangladeshi construction workers in Kuwait reported confinement to labor camps, restricted exit without permission, wage delays (2-3 months). Union and BMET filed complaints; investigation underway.",
        "source": "BMET / Kuwait Labor Ministry",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Health Violation: 167 Workers in Qatar — Heat Exposure",
        "summary": "167 Bangladeshi workers in Qatar construction reported systematic overwork in extreme heat (50°C+). 12-14 hour shifts with minimal breaks. 23 workers hospitalized with heat exhaustion. Employer failed to provide adequate water/breaks.",
        "source": "BMET / Qatar Labor Ministry / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Bangladeshi Migrant Worker Population",
        "summary": "Bangladesh has estimated 7-8 million migrant workers abroad (2023). Distribution: Saudi Arabia 25%, UAE 18%, Malaysia 16%, Kuwait 12%, Qatar 10%, Singapore 7%, other 12%. 89% male; 11% female (concentrated in domestic work).",
        "source": "BMET Statistics / IOM Bangladesh",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Remittance Inflows & Economic Dependency",
        "summary": "Remittances comprise 5.8% of Bangladesh GDP (~USD 21 billion annually, 2023). 1 in 6 households receive remittances. Rural dependency: 30-40% of income from remittances. Creates acute vulnerability to exploitation during migration.",
        "source": "Bangladesh Bank / World Bank",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Migrant Worker Deaths Abroad — 2015-2023 Data",
        "summary": "Bangladesh recorded 3,456 migrant worker deaths abroad (2015-2023): Saudi Arabia 892, UAE 678, Malaysia 445, Kuwait 312, Qatar 289, other 840. Causes: occupational accidents (42%), suicide/depression (25%), medical emergencies (18%), violence (15%).",
        "source": "BMET / IOM Records",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Trafficking Conviction Rate: Bangladesh Courts",
        "summary": "Bangladesh courts convicted 234 human trafficking cases in 2023 (up from 89 in 2015). Average sentences: 5-8 years imprisonment. Victim compensation low (avg. 100,000-200,000 BDT). Retrial rate: 45% due to procedural issues.",
        "source": "Bangladesh Attorney General / IOM",
    },
    {
        "type": "law",
        "jurisdiction": "BD",
        "title": "Overseas Employment and Migrants Act, 2013",
        "summary": "Bangladesh law regulating overseas employment. Prohibits recruitment agents from charging workers excessive fees. Requires written contracts in Bangla. BMET must license all agents. Enforcement weak; 200+ unlicensed agents operate illegally.",
        "source": "Bangladesh Government / BMET",
    },
    {
        "type": "law",
        "jurisdiction": "BD",
        "title": "Prevention of Human Trafficking Act, 2012",
        "summary": "Comprehensive anti-trafficking law. Defines trafficking broadly; penalties up to 14 years imprisonment. Establishes victim protection and rehabilitation provisions. Implementation constrained by limited investigative capacity.",
        "source": "Bangladesh Legal Framework",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "BD",
        "title": "2021 Amendment: Increased Penalties for Labor Fraud",
        "summary": "Amendment increased penalties for labor fraud from 5 years to 7-10 years imprisonment, depending on worker harm. Minimum fines increased from 50,000 to 500,000 BDT. Intended to deter predatory recruitment practices.",
        "source": "Bangladesh Government Gazette",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "BD",
        "title": "2019 Domestic Worker Migration Restriction: 6-Month Pilot",
        "summary": "Bangladesh temporarily banned domestic worker migration to Gulf countries (2018-2019) due to trafficking concerns. Pilots allowed migration to Saudi Arabia only under strict conditions: BMET-certified employer, min. wage 1,500 SAR, written contracts.",
        "source": "BMET / Bangladesh Government",
    },
    {
        "type": "penalty",
        "jurisdiction": "BD",
        "title": "Agent License Revocation: 67 Agencies (2023)",
        "summary": "BMET revoked licenses of 67 recruitment agents in 2023 for violations: fraud (23), non-refund of deposits (19), trafficking suspicion (15), document falsification (10). Combined fines: 8.5 crore BDT. Criminal prosecutions pending for 34 agents.",
        "source": "BMET Annual Report",
    },
    {
        "type": "penalty",
        "jurisdiction": "BD",
        "title": "Criminal Prosecution: NP-2022-089 — Trafficking Ring",
        "summary": "Bangladesh court convicted 14-member trafficking ring of trafficking 267 women to Saudi Arabia for domestic work. Ring leader sentenced to 14 years imprisonment. Investigation revealed use of forged documents, fake employer letters, psychological manipulation.",
        "source": "Bangladesh Court / Attorney General",
    },
    {
        "type": "advisory",
        "jurisdiction": "BD",
        "title": "BMET Advisory: Migrant Worker Rights & Protections",
        "summary": "BMET issued advisory to workers: obtain written contracts in Bangla, verify agent license online (BMET database), attend pre-departure training, document all deposits/fees, maintain emergency contact with Bangladesh embassy.",
        "source": "BMET / Bangladesh Government",
    },
    {
        "type": "advisory",
        "jurisdiction": "BD",
        "title": "ILO Guidance: Safe Migration Practices for Bangladeshi Workers",
        "summary": "ILO issued guidance on safe migration: verify employer legitimacy through embassy, use official channels (BMET agents only), avoid debt-financed migration, maintain contact with family, report exploitation to embassy immediately.",
        "source": "ILO / Bangladesh Labor Ministry",
    },

    # Dhaka Labor Court Cases
    {
        "type": "court_ruling",
        "jurisdiction": "BD",
        "title": "Dhaka Labor Court: Case BD-2023-456 — Wage Theft Judgment",
        "summary": "Judgment awarded 1,200 workers compensation of 50,000 BDT each for 8 months of unpaid wages (total 6 crore BDT). Factory closure ordered for 2 years; owner imprisoned 3 years. Appeal pending.",
        "source": "Dhaka Labor Court / Bangladesh Legal Records",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "BD",
        "title": "Dhaka Labor Court: Case BD-2023-789 — Child Labor Conviction",
        "summary": "Factory owner convicted of employing 67 child workers (ages 13-16). Sentence: 5 years imprisonment + 500,000 BDT fine. Victims received rehabilitation support (vocational training, stipends). Case took 4 years to trial.",
        "source": "Dhaka Labor Court",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "BD",
        "title": "Dhaka Labor Court: Case BD-2022-123 — Hazard Compensation",
        "summary": "Court awarded 340 workers 75,000 BDT each for occupational disease (silicosis) from textile work. Employer ordered to establish medical fund for affected workers. Implementation timeline: 12 months.",
        "source": "Dhaka Labor Court",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "BD",
        "title": "Bangladesh High Court: Rana Plaza Appeal — Owner Sentencing (2021)",
        "summary": "High Court upheld guilty verdict for Rana Plaza owner, sentencing to life imprisonment for deaths caused by negligent construction. Conviction upheld for 7 of 38 defendants. Civil compensation claims remain disputed.",
        "source": "Bangladesh High Court / Legal Records",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Complaint: 289 Garment Workers — Hazardous Chemical Exposure",
        "summary": "289 garment workers in Savar facility filed complaint regarding exposure to formaldehyde and chlorine during fabric processing. 45 workers hospitalized with respiratory issues. Factory failed to provide safety equipment; medical treatment denied.",
        "source": "Bangladesh Labor Ministry / BILS",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Complaint: 156 Leather Tannery Workers — Environmental Health Hazard",
        "summary": "156 leather tannery workers in Hazaribagh complained of chromium exposure causing skin diseases and organ damage. Work site adjacent to residential area; groundwater contaminated. Environmental assessment ordered.",
        "source": "Bangladesh Labor Ministry / Environmental Agency",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Complaint: 89 Brick Kiln Workers — Debt Bondage",
        "summary": "89 brick kiln workers in Narayanganj complained of debt bondage: initial loan of 20,000 BDT for seasonal work, debt escalated to 150,000 BDT through 'interest' and fee manipulation. Unable to leave.",
        "source": "Bangladesh Labor Ministry / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "BKMEA Labor Case: Spinning Mill Abuse (2023)",
        "summary": "BKMEA (Bangladesh Knitwear Manufacturers and Exporters Association) documented case of spinning mill with 234 workers in debt bondage. Initial recruitment fee: 30,000 BDT. Debt accumulated to 250,000 BDT through fabricated 'advances' and deductions.",
        "source": "BKMEA / Bangladesh Labor Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Fake Buyer Fraud — Advance Deposit Scheme",
        "summary": "Recruitment agent posed as foreign buyer purchasing textile goods, offering 'buyer agent positions' to 78 workers. Required 50,000 BDT advance fee for 'registration.' Agent disappeared with deposits; workers left without employment.",
        "source": "Bangladesh Police / BMET",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Wage Trap: Monthly Salary Reduction Scheme",
        "summary": "Factory instituted practice of reducing wages 5% each month for first 6 months ('probation period deduction'). Workers hired at 8,000 BDT/month reduced to 6,500 BDT by month 6. Practice affected 400+ workers; legal challenge successful.",
        "source": "Dhaka Labor Court / BILS",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Passport Fraud — Travel Document Manipulation",
        "summary": "Recruitment agent used workers' passports to apply for visas in fake name/position, then confiscated documents. Workers deployed to different countries/jobs than contracted. 34 workers involved; agent arrested; passports recovered.",
        "source": "Bangladesh Police / BMET",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Forced Signature: Coerced Contract Acceptance",
        "summary": "Workers reported being forced to sign contracts in unfamiliar language (Arabic or English) without translation. Upon arrival abroad, discovered contracts much less favorable than verbally promised terms. Contracts legally binding.",
        "source": "BMET / IOM Survey",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Debt Escalation: Service Charges & Compound Interest",
        "summary": "Workers borrowed 200,000 BDT migration fees at 2% monthly interest (24% annually). Lender charged additional 10% 'service charge' quarterly. After 12 months, debt reached 320,000 BDT. Workers unable to repay while abroad.",
        "source": "ILO / Bangladesh NGO Network",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Health Deception: Medical Certificate Substitution",
        "summary": "Worker with history of tuberculosis obtained job in Gulf through agent who submitted medical certificate of healthy person. Worker arrived ill; employer discovered deception; terminated without compensation. No legal recourse.",
        "source": "BMET Complaint Records",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Work Substitution: Different Job Upon Arrival",
        "summary": "64 workers hired for 'skilled construction work' (promised 3,000 AED/month) arrived to find assignment as general laborers in warehouse (1,500 AED/month). No recourse; contracts claimed 'subject to availability.'",
        "source": "BMET / UAE Labor Ministry",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "BD",
        "title": "Fraudulent Employer Credentials: Fabricated References",
        "summary": "Recruitment agent presented employer references that were fabricated: phone numbers non-functional, business addresses invalid, 'business licenses' forged. 123 workers recruited before scheme discovered.",
        "source": "BMET Investigation / Bangladesh Police",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "BD",
        "title": "Age Misrepresentation: Child Labor Facilitation",
        "summary": "Recruitment agent assisted 34 workers aged 15-17 to obtain fraudulent age certificates (claiming 18+) to qualify for overseas work. Upon discovery, workers returned; agent prosecuted.",
        "source": "BMET / Bangladesh Labor Ministry",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "BD",
        "title": "Gender-Based Deception: Domestic Work Fraud",
        "summary": "Agent promised female workers 'hotel housekeeping positions' (public work, decent wages) in Saudi Arabia. Upon arrival, reassigned to domestic work (private homes, wage theft, abuse common). 56 workers affected.",
        "source": "BMET / Bangladesh Embassy Saudi Arabia",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Gender Composition of Migrant Workers",
        "summary": "11-12% of Bangladeshi migrant workers are female (770,000-860,000). 78% work in domestic service. Trafficking vulnerability 4x higher than male migrants. Wage theft rate 35% (vs. 18% for males).",
        "source": "BMET / USDOL Report",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Recruitment Fraud Complaint Statistics",
        "summary": "BMET received 4,567 labor fraud complaints in 2023 (up from 2,100 in 2015). Categories: wage non-payment 1,800, misrepresentation 1,200, passport confiscation 890, other 677. Resolution rate: 8-12%.",
        "source": "BMET Annual Report",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Illegal Recruitment Network Activity",
        "summary": "Estimate 400-600 illegal/unlicensed recruitment agents operate in Bangladesh. They facilitate 15-20% of migration flows through informal channels. Cost to workers typically 30-50% higher; fraud risk exponentially greater.",
        "source": "ILO Assessment / BMET",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Debt Burden in Migration: Pre-Departure Financing",
        "summary": "68% of Bangladeshi migrant workers financed migration through debt (loans, advances, informal credit). Average debt: 250,000-350,000 BDT. 40% of workers report debt repayment challenges after arrival abroad.",
        "source": "IOM Survey / BMET",
    },
    {
        "type": "advisory",
        "jurisdiction": "BD",
        "title": "BMET Guide: Safe Recruitment Practices for Workers",
        "summary": "BMET issued guide recommending: verify agent license (BMET online database), obtain written contract in Bangla, limit advance payments to 20% max, maintain copies of all documents, register with Bangladesh embassy upon arrival.",
        "source": "BMET / Bangladesh Government",
    },
    {
        "type": "advisory",
        "jurisdiction": "BD",
        "title": "ILO Trafficking Risk Assessment: Bangladesh Corridors",
        "summary": "ILO identified high-risk migration corridors: BD-SA (domestic work, 35% trafficking risk), BD-MY (manufacturing, 22% risk), BD-KW (construction, 28% risk). ILO recommends bilateral labor agreements, labor inspectorates, bilateral enforcement.",
        "source": "ILO / Bangladesh Labor Ministry",
    },

    # Additional Nepal Cases (Expansion)
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Contract Language Barrier — Arabic Contract Trap",
        "summary": "43 Nepali workers signed employment contracts in Arabic they could not read. Actual terms: 12-hour days, 0.5% wage deduction per day absent, no overtime pay. Terms vastly different from verbal promises.",
        "source": "DoFE / POLO Riyadh",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Wage Deduction Accumulation — Complex Fee Structure",
        "summary": "Nepali construction worker in UAE faced monthly deductions: accommodation 300 AED, food 150 AED, 'efficiency fee' 100 AED, 'tool breakage' 50 AED, 'damage fee' variable. Base wage 2,000 AED; net received 1,200-1,400 AED.",
        "source": "POLO Dubai / DoFE Records",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Labor Brokerage Chain: Multi-Tier Exploitation",
        "summary": "Nepali worker transferred between 4 employers over 18 months. Initial salary: 1,500 QR. Final: 900 QR. Each intermediary took commission (5-10% of wages). Worker's savings depleted on broker fees.",
        "source": "Amnesty International / Migrante Nepal",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Forced Overtime Without Compensation",
        "summary": "78 Nepali workers at Malaysian electronics factory forced to work 4-6 additional hours daily (18-20 hour total). Employer claimed 'production emergency.' No overtime payment; workers threatened with termination.",
        "source": "Malaysia Labor Ministry / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Workplace Injury Without Compensation — Kuwait",
        "summary": "Nepali worker lost 2 fingers in machinery accident at Kuwait factory. Employer denied workers' compensation, claiming 'worker negligence.' Medical costs (5,000 KWD) borne by worker. Permanent disability without income support.",
        "source": "POLO Kuwait / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Blacklist System: Deportation & Future Employment Block",
        "summary": "After reporting wage theft complaint, Nepali worker deported from Saudi Arabia and blacklisted from re-entering Gulf countries. Employment prospects destroyed. Agent who arranged placement paid blacklist fee to employer.",
        "source": "DoFE / IOM Nepal",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Fake Medical Clearance — Job Disqualification Trap",
        "summary": "Nepali recruitment agent submitted fraudulent medical clearance (submitted under different person's name). Worker arrived abroad; employer discovered discrepancy; terminated and deported. Worker lost all investment.",
        "source": "DoFE Complaint Registry",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Housing Cost Deduction Scheme — Living Expense Trap",
        "summary": "Workers housed in substandard labor camps (6-8 per room, no hot water, poor sanitation). Camp fees deducted from salary: 300 AED/month (50% of income). Employer owns camp; workers have no alternative housing.",
        "source": "HRW / POLO Dubai",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Recruitment Agent False Identity",
        "summary": "Agent represented himself as official government employment officer. Collected fees, passports, medical documents. Disappeared. 156 workers lost deposits (NPR 2.5 crore). Agent never prosecuted.",
        "source": "DoFE / Nepal Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Visa Fraud: Fake Visa Documents Used",
        "summary": "34 Nepali workers traveled on fake Schengen visas created by agent. Visas valid enough for initial travel. Upon arrival in Middle East, employer discovered fraud; workers jailed for document falsification.",
        "source": "Interpol / DoFE",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Debt Bondage Prevalence Among Nepali Migrants",
        "summary": "Survey of 2,000 returned Nepali migrants: 1,340 (67%) financed migration through debt. Average initial debt: 250,000 NPR. Average remaining debt on return: 180,000 NPR. 28% reported debt increase due to additional fees.",
        "source": "IOM Survey / NATHM",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Contract Substitution Frequency",
        "summary": "Survey: 34% of Nepali migrant workers report being presented different employment contract upon arrival vs. contract signed in Nepal. Typical wage reduction: 25-40%. Recourse available to only 3% of workers.",
        "source": "ILO Assessment / DoFE",
    },
    {
        "type": "penalty",
        "jurisdiction": "NP",
        "title": "Agent Prosecution: Fraud Case NP-2023-234",
        "summary": "Agent 'Sharma Brothers' prosecuted for defrauding 123 workers of NPR 1.8 crore. Agents misrepresented wages, job types, and working conditions. Conviction: 6 years imprisonment. Restitution: partial refunds only.",
        "source": "Nepal Court / CIAA",
    },
    {
        "type": "penalty",
        "jurisdiction": "NP",
        "title": "License Permanent Revocation — Repeat Violator",
        "summary": "Manpower agency had prior suspension (2019), then re-licensed (2021). By 2023, accumulated 45 new complaints. License permanently revoked. Criminal investigation for systematic fraud patterns.",
        "source": "DoFE / Nepal Government",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "NP",
        "title": "False Credentials: Fake Educational Qualification Claims",
        "summary": "Agent claimed workers had vocational certifications they did not possess. Upon arrival in Qatar, employer tested workers; discovered fraud. Workers reassigned to lower-pay positions; some terminated.",
        "source": "DoFE Records",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "NP",
        "title": "Age-Based Discrimination in Recruitment",
        "summary": "67 Nepali workers aged 45+ reported being promised jobs then rejected upon arrival for 'age limit' positions. Agents claimed 'miscommunication.' Workers lost deposits; no recourse available.",
        "source": "DoFE Complaint Records",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Wage Delay Crisis: 5-Month Non-Payment",
        "summary": "123 Nepali workers in UAE construction had salaries delayed 5 months with no explanation. Employer claimed 'cash flow issues.' Workers went into debt to finance living expenses. Partial payment received after labor ministry intervention.",
        "source": "POLO Dubai / UAE Labor Ministry",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Unsafe Working Conditions: Construction Site Hazards",
        "summary": "89 Nepali construction workers in Qatar reported systematic safety violations: no helmets, improper scaffolding, no height protection harnesses. 12 workers injured within 6 months. Injuries went unreported.",
        "source": "DoFE / Qatar Labor Ministry",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "NP",
        "title": "Kathmandu District Court: Case NP-2023-012 — Trafficking Conviction",
        "summary": "Court convicted human trafficker 'Dipak Singh' of trafficking 45 women to Middle East for forced domestic work. Sentence: 7 years imprisonment + fine of 300,000 NPR. Victim compensation awarded but remains unpaid.",
        "source": "Kathmandu District Court / Nepal",
    },
    {
        "type": "advisory",
        "jurisdiction": "NP",
        "title": "Worker Safety Hotline: Emergency Contact Registry",
        "summary": "DoFE established 24/7 hotline (1112) for migrant workers to report emergencies, wage theft, abuse. Coordination with POLO offices and foreign governments. Average response time: 8-12 hours. Coverage limited by language capacity.",
        "source": "DoFE / Nepal Government",
    },

    # Additional Bangladesh Cases (Expansion)
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Apparel Export Wage Suppression — Competitive Pressure",
        "summary": "International brands demand lower production costs; suppliers cut wages. Bangladeshi garment workers saw real wages decline 15% (2015-2023). Cost per unit reduced but worker compensation stagnated. Systemic poverty perpetuation.",
        "source": "BGMEA / Labor Rights Study",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Subcontractor Responsibility Void: Multi-Tier Production",
        "summary": "International brand contracts with factory A, which subcontracts to factory B, which employs workers. Violations at factory B; factory A claims 'not responsible.' Workers unable to hold brand accountable.",
        "source": "ILO Supply Chain Study",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Trade Union Suppression: Activist Firing",
        "summary": "234 workers at garment factory formed trade union to negotiate better wages. 45 union leaders fired within 2 weeks. Remaining workers intimidated back to work. Union disbanded. No legal protection against retaliation.",
        "source": "BILS / Bangladesh Labor Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Seasonal Employment Precarity: Feast or Famine",
        "summary": "Garment factory workers contracted only 7-8 months/year during production season. Off-season unemployment 4-5 months; no income or benefits. Workers unable to plan financially. Estimated 800,000 workers in this situation.",
        "source": "BGMEA / IOM Survey",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Women Garment Workers: Gender-Based Wage Gap",
        "summary": "Female garment workers (3.2 million) earn 25-30% less than male supervisors for same work. Justification: 'women are less productive.' No enforcement of equal pay principles. Gender gap widens with seniority.",
        "source": "Bangladesh Women's Chamber / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Migrant Shrimp Worker: Trafficking Case Study",
        "summary": "Woman from rural Bangladesh recruited for 'shrimp factory job' (advertised as clean factory work). Upon arrival, debt bondage enforced: 100,000 BDT initial 'loan.' 16-hour daily shifts in toxic conditions. Repatriated by NGO after 8 months.",
        "source": "IOM Bangladesh / USDOL",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Recruitment Visit Deception: Community Trust Abuse",
        "summary": "Agent visited Bangladeshi village, gained community trust through NGO-like behavior, then systematically recruited 180 workers for 'construction abroad.' Upon arrival in Malaysia, workers discovered debt bondage and wage theft.",
        "source": "IOM / BMET Investigation",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "False Promise of Skill Development",
        "summary": "Agent promised Bangladeshi workers 'vocational training abroad' (engineering, IT skills) with paid internship. Upon arrival in Saudi Arabia, workers placed in general construction (zero training). Training fees non-refundable.",
        "source": "BMET Records",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Remittance Manipulation: Currency Loss Trap",
        "summary": "Agent-linked remittance service charged 15% commission (vs. 2-4% standard rate). Workers lost USD 2,000+ annually per person. Over 5,000 migrant workers used this service. Illegal forex agent; prosecution pending.",
        "source": "Bangladesh Bank / BMET",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Passport Non-Return: Ongoing Control Mechanism",
        "summary": "Bangladeshi workers in Saudi Arabia had passports retained by employers. Workers promised return 'at contract end.' After contract completion, employer demanded additional payment (10,000 SAR) for passport release. Coercive control mechanism.",
        "source": "Bangladesh Embassy Saudi Arabia / IOM",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Garment Industry Wage Trends (2010-2023)",
        "summary": "Minimum wage: 3,000 BDT (2010) → 8,000 BDT (2023). Nominal increase 167%. However, inflation 240%; real wages declined 30%. Worker purchasing power significantly eroded. Cost of living crisis in garment worker communities.",
        "source": "Bangladesh Labor Ministry / World Bank",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Occupational Disease in Garment Workers",
        "summary": "Health study of 1,000 garment workers: 34% respiratory disease (dust/formaldehyde), 28% skin conditions (chemical exposure), 22% musculoskeletal issues (repetitive motion). Average age: 28. Disability rate: 12%.",
        "source": "Bangladesh Health Ministry / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Child Labor in Manufacturing & Agriculture",
        "summary": "Bangladesh estimated 4.7 million child laborers (ages 5-17). Distribution: agriculture 1.8M, manufacturing 1.2M, domestic 1.1M, other 0.6M. Many meet forced labor definition (debt bondage, restriction of movement).",
        "source": "USDOL / ILO Child Labor Initiative",
    },
    {
        "type": "penalty",
        "jurisdiction": "BD",
        "title": "Agent Imprisonment: NP-2023-567 — Systematic Fraud",
        "summary": "Recruitment agent sentenced to 10 years imprisonment for defrauding 267 workers of 5 crore BDT. Systematic pattern: fake job offers, contract substitution, wage theft coordination with employers.",
        "source": "Bangladesh Court / Attorney General",
    },
    {
        "type": "penalty",
        "jurisdiction": "BD",
        "title": "Factory Owner Fine: Safety Violations & Deaths",
        "summary": "Factory owner fined 50 lakh BDT for safety violations resulting in 3 worker deaths (fire). Minimal sentence (2 years suspended). Fine represents 2-3 weeks of factory revenue. Inadequate deterrent.",
        "source": "Dhaka Labor Court / Bangladesh",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "BD",
        "title": "Unlicensed Agent Operating in Dhaka",
        "summary": "BMET identified unlicensed recruitment agent operating from Dhaka office with 45+ workers. Agent charges 80,000 BDT vs. standard 30,000 BDT. Workers mostly sent to Malaysia/Thailand without contracts.",
        "source": "BMET / Bangladesh Police",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "BD",
        "title": "Fake Employment Reference Letters",
        "summary": "Agent created counterfeit reference letters claiming workers had employment history at major factories (Rana Plaza, Tazreen). References submitted to international employers. 34 workers discovered fraud upon job interviews.",
        "source": "BMET Investigation",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Discriminatory Hiring: Religious Preference Requirement",
        "summary": "Garment factory required workers to be of specific religious faith (Muslim) and participate in mandatory prayer activities. Non-Muslim applicants rejected. BILS filed complaint of religious discrimination.",
        "source": "BILS / Bangladesh Labor Ministry",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Harassment & Threats: Non-Compliance Pressure",
        "summary": "456 garment workers reported factory manager threats: 'if you complain, you'll never work in this industry again.' Physical intimidation during salary withholds. Fear-based compliance culture.",
        "source": "Bangladesh Labor Ministry / BILS",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "BD",
        "title": "Bangladesh High Court: Garment Industry Compensation Case (2023)",
        "summary": "Class action judgment awarded 800 workers 100,000 BDT each for unpaid wages over 2-year period. Total award: 8 crore BDT. Employer ordered to establish workers' fund. Implementation timeline: 12 months.",
        "source": "Bangladesh High Court / Legal Records",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "BD",
        "title": "Dhaka Labor Court: Unfair Termination Verdict (2023)",
        "summary": "Court ruled factory illegally terminated 123 pregnant workers without severance. Judgment: full severance pay + 3 months additional compensation + mandatory rehiring. Factory appealed; case pending.",
        "source": "Dhaka Labor Court",
    },
    {
        "type": "advisory",
        "jurisdiction": "BD",
        "title": "BGMEA Code of Conduct: Worker Rights & Safety",
        "summary": "BGMEA published code of conduct requiring member factories to ensure: safe working conditions, fair wages, no forced labor, freedom of association. Self-enforcement mechanism; independent monitoring absent. Compliance voluntary.",
        "source": "BGMEA / Bangladesh Government",
    },
    {
        "type": "advisory",
        "jurisdiction": "BD",
        "title": "IOM Migrant Worker Support Services",
        "summary": "IOM established counters in major cities providing: pre-departure counseling, contract review in Bangla, emergency assistance contacts, post-arrival support. Services free. Estimated reach: 150,000 workers annually.",
        "source": "IOM Bangladesh / Government",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "BD",
        "title": "2022 Amendment: Mandatory Health Insurance for Workers",
        "summary": "Law requiring factories to provide health insurance covering basic medical, hospitalization, disability. Premium: 500-1,000 BDT/month (shared employer/worker). Compliance: 40% of factories. Benefit limits restrict coverage.",
        "source": "Bangladesh Labor Ministry",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "BD",
        "title": "2021 Update: Minimum Wage Increase to 8,000 BDT",
        "summary": "Minimum wage increased to 8,000 BDT/month (from 5,000 in 2013). Real value still 30% below 2010 levels when adjusted for inflation. Industry lobbied for exemptions; compliance variable.",
        "source": "Bangladesh Government Gazette",
    },
    {
        "type": "law",
        "jurisdiction": "BD",
        "title": "Bangladesh Labor Law 2006 & Amendments",
        "summary": "Primary labor law establishing minimum wage, working hours (48/week), safety standards, workers' rights. Multiple amendments (2013, 2015, 2021). Enforcement weak; inspectorates underfunded (1 inspector per 1,000+ workplaces).",
        "source": "Bangladesh Government",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Informal Sector Exploitation: Unregistered Workshop",
        "summary": "Estimate 1.2 million workers in unregistered garment workshops (no government record/oversight). Workers have zero legal protections, wages 30-50% lower, conditions worse than formal factories. Estimated 40% of apparel production.",
        "source": "ILO / Bangladesh Labor Ministry Assessment",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Piece-Rate Wage System: Income Volatility",
        "summary": "500+ garment workers paid per piece produced (vs. fixed salary). Daily income varies 3,000-8,000 BDT based on production targets. Inconsistent income makes budgeting impossible. System incentivizes unsafe speed.",
        "source": "BILS / Bangladesh Labor Research",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Vendor Audit Evasion: Mock Production Runs",
        "summary": "Factory owners aware of upcoming brand safety audit schedule workshops with fewer children, better conditions for audit day. Normal operations resume after auditors leave. Brand audits unable to detect systematic fraud.",
        "source": "ILO / Supply Chain Accountability Study",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Female Worker Pregnancy Discrimination",
        "summary": "Garment factories reportedly terminate or demote female workers upon pregnancy announcement. 3,000+ complaints filed annually. Workers lose income during vulnerable period. Legal protection inadequate; enforcement lacking.",
        "source": "Bangladesh Labor Ministry / Women's Rights NGO",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Female Worker Vulnerability in Garment Sector",
        "summary": "3.2 million female garment workers; 45% sole income earner for family. 60% experienced workplace harassment. 28% reported wage theft. Turnover rate: 35%/year due to conditions. Economic desperation perpetuates exploitation.",
        "source": "Bangladesh Women's Chamber / IOM",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Repatriation of Bangladeshi Migrant Workers",
        "summary": "Estimated 450,000-500,000 Bangladeshi workers repatriated in 2023 (up from 250,000 in 2015). Reasons: contract completion (40%), deportation (35%), voluntary return due to abuse/exploitation (25%). Reintegration support limited.",
        "source": "BMET / IOM Bangladesh",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Microcredit Predation: Lending Trap Cycle",
        "summary": "Microcredit organization offered 200,000 BDT loan to Bangladeshi worker for migration. Interest: 18% annually + 5% processing fee + 2% insurance. Workers unable to repay; debt spirals over time. Microcredit paradoxically enables trafficking.",
        "source": "Bangladesh Microfinance Association / IOM",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Wage Suppression: Collective Wage Reduction",
        "summary": "During COVID-19 pandemic, 150 garment factories reduced wages 25-50% claiming 'order cancellations.' Workers unable to find alternative employment; accepted wage cuts. Some factories retained cuts post-pandemic; workers have no leverage.",
        "source": "Bangladesh Labor Ministry / BILS",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Unhygienic Facilities: Health & Safety Crisis",
        "summary": "456 garment workers complained of inadequate sanitation: 1 toilet for 50+ workers, no hand-washing facilities, contaminated drinking water. 45 workers developed gastroenteritis within month. Health department inspection ordered.",
        "source": "Bangladesh Labor Ministry / Health Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Forced Relocation: Project Displacement Without Compensation",
        "summary": "Brick kiln operation displaced 200 rural families for land development. Compensation: 0 BDT. Families relocated to urban slums, forced into informal work (garment sweatshops, domestic service) to survive. Intergenerational poverty creation.",
        "source": "Bangladesh Land Rights Organization / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Multiple Employment Changes: Worker Instability",
        "summary": "Nepali worker changed employers 5 times in 2-year Gulf assignment (originally contracted to one employer). Each change involved wage reduction. Final salary 60% below initial contract. Job insecurity prevented complaint filing.",
        "source": "DoFE Records / Migrante Nepal",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Skill Devaluation Upon Arrival",
        "summary": "Nepali electrician hired as 'skilled technician' in Qatar. Upon arrival, employer claimed certification invalid; reassigned to general labor at 40% lower wage. Credential devaluation strategy systematic.",
        "source": "Amnesty International / DoFE",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Migrant Worker Mental Health Crisis",
        "summary": "Study of 500 Nepali returned migrants: 45% reported depression, 28% anxiety, 8% suicide attempts. Contributing factors: wage theft, isolation, family separation, exploitation. Mental health services unavailable in origin communities.",
        "source": "Nepal Mental Health Foundation / IOM",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Informal Lending & Predatory Debt",
        "summary": "Estimate 60% of Nepali migrant workers use informal lending (loan sharks, village moneylenders) for migration funding. Interest rates: 2-5% monthly (24-60% annually). Debt accumulation traps 35% of workers.",
        "source": "ILO / Nepal NGO Assessment",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Discrimination: Age-Based Job Termination",
        "summary": "45 Nepali workers aged 50+ terminated without severance after 5+ years employment in UAE. Employer cited 'age limit policy' (workers over 50 unsuitable). No legal mechanism for age discrimination complaints.",
        "source": "POLO Dubai / DoFE",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Retaliation Against Complaint Filers",
        "summary": "Nepali worker filed wage theft complaint with DoFE; employer discovered filing (worker discussed with colleagues). Worker reassigned to hazardous duties; safety violations increased. Retaliation unreported out of fear.",
        "source": "DoFE Complaint Registry",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "NP",
        "title": "Nepal Supreme Court: Labor Rights Precedent (2021)",
        "summary": "Court ruled that migrant workers cannot waive fundamental labor rights (minimum wage, safe conditions) through individual contracts. Landmark decision. Implementation in actual cases remains inconsistent.",
        "source": "Nepal Supreme Court / Legal Records",
    },
    {
        "type": "penalty",
        "jurisdiction": "NP",
        "title": "Fine Against Foreign Employer: Non-Payment Case",
        "summary": "Kuwait employer fined 10,000 KWD for non-payment of wages to 67 Nepali workers. Fine equivalent to 3 months unpaid wages. Weak penalty; minimal deterrent effect. Workers still not paid.",
        "source": "Kuwait Labor Ministry / POLO",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "NP",
        "title": "Credential Inflation: Exaggerated Qualifications",
        "summary": "Agent misrepresented workers as 'senior technicians' when they were entry-level workers with basic skills. Upon arrival, employer discovered misrepresentation; workers demoted with wage reductions.",
        "source": "DoFE Complaint Records",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Live-in Garment Arrangement: Factory Housing Entrapment",
        "summary": "Factory provided on-site housing (free) to 400 workers. Workers became dependent; housing used as control mechanism. Complaints resulted in housing threat removal. Workers feared homelessness; stayed silent.",
        "source": "BILS / Bangladesh Labor Research",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Piece-Rate Wage Pressure: Speed Over Safety",
        "summary": "Piece-rate system incentivizes speed; safety corners cut. 34 workers injured in machinery accidents in single month. Employer argued workers were 'careless.' Workers avoided injury reporting (feared wage loss).",
        "source": "Bangladesh Labor Ministry / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Child Domestic Worker: Hidden Exploitation",
        "summary": "450,000 Bangladeshi child domestic workers (ages 5-17) estimated. Often live with employer family; isolated from support networks. 45% report physical abuse; 28% sexual abuse. Exploitation largely invisible.",
        "source": "USDOL / ILO Child Labor Program",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Verbal Contract Only: No Written Evidence",
        "summary": "250 Bangladeshi workers recruited with verbal-only agreements (no written contract). Upon arrival in Malaysia, employer claimed different terms than promised. No documentation; worker has zero recourse.",
        "source": "IOM / BMET Records",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Unregistered Workers in Garment Industry",
        "summary": "Estimate 400,000-600,000 garment workers unregistered (no BMET record). Cannot access government protections, unemployment benefits, or legal recourse. Concentrated in informal/subcontracting operations.",
        "source": "BGMEA / Bangladesh Labor Ministry",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Return Migrant Reintegration Challenges",
        "summary": "Survey of returned Bangladeshi workers: 45% unable to find employment; 30% underemployed (lower-wage jobs). Social stigma against 'returnees' reduces hiring. Exploitation often leads to permanent labor market exclusion.",
        "source": "IOM / BMET Survey",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Product Quality Blame: Wage Deductions",
        "summary": "Factory blamed workers for product defects (not worker fault; quality input issues). Deducted wages: 10% per defect unit. Workers lost 30-40% monthly wages to deductions. No dispute mechanism.",
        "source": "Bangladesh Labor Ministry / BILS",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Attendance Fraud: False Absence Records",
        "summary": "Factory management falsified attendance records; marked workers 'absent' when present. Workers fined for unrecorded absences they didn't take. 78 workers lost 20,000+ BDT monthly through false deductions.",
        "source": "Bangladesh Labor Ministry",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "BD",
        "title": "Bangladesh Court: Contractor Liability Case (2023)",
        "summary": "Court ruled contractor liable for worker injury (previously claimed liability resided with subcontractor only). Landmark decision on supply chain accountability. Precedent may encourage brands to enforce safety.",
        "source": "Bangladesh High Court / Legal Records",
    },
    {
        "type": "penalty",
        "jurisdiction": "BD",
        "title": "Factory Suspension: Safety Non-Compliance",
        "summary": "Factory suspended from exporting for 6 months due to safety violations. Production halted; 1,200 workers placed on unpaid leave. Wage loss absorbed by workers; factory faced minimal penalty.",
        "source": "Bangladesh Labor Ministry / BGMEA",
    },
    {
        "type": "advisory",
        "jurisdiction": "BD",
        "title": "Worker Emergency Support Line: 24/7 Hotline",
        "summary": "BMET established hotline (16262) for workers to report emergencies, wage theft, abuse. Free call. Average response time: 12-24 hours. Limited resources constrain follow-up investigations.",
        "source": "BMET / Bangladesh Government",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "BD",
        "title": "Fake Factory Visit: Recruitment Deception",
        "summary": "Agent showed prospective workers 'factory tour' (actually competitor's factory). Photos/tour used to recruit 156 workers for different factory. Workers arrived to find drastically different conditions.",
        "source": "BMET Investigation",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Remittance Non-Receipt: Money Transfer Fraud",
        "summary": "Nepali worker sent monthly salary remittances (NPR 100,000) to family via agent-linked service. Funds diverted; family never received payment. Agent disappeared. Worker unaware for 8 months (lack of communication).",
        "source": "DoFE / Nepal Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Worker Injury Abandonment: Medical Non-Coverage",
        "summary": "Nepali worker suffered workplace injury (broken leg) in Kuwait. Employer refused to cover medical costs (67,000 KWD). Worker left untreated; permanent mobility impairment resulted. No workers' compensation system available.",
        "source": "POLO Kuwait / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Communication Isolation: Language Barrier Exploitation",
        "summary": "Nepali workers unable to speak Arabic, English. Employer communicated only through hired interpreter (employer's choice). Interpreter omitted/distorted critical information about contracts/rights. Information asymmetry exploited.",
        "source": "ILO / Amnesty International",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Language Proficiency Among Nepali Migrants",
        "summary": "Survey: only 18% of Nepali migrant workers speak destination-country primary language. 67% speak English poorly. Language barrier prevents workers from understanding contracts, laws, or asserting rights.",
        "source": "IOM / DoFE Survey",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Non-Functional Legal Complaint Mechanism",
        "summary": "Nepali worker filed wage theft complaint with POLO (embassy labor officer). 18 months later: no investigation, no response, no resolution. Complaint system non-functional due to underfunding.",
        "source": "DoFE Records",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "NP",
        "title": "District Court: Migrant Trafficking Conviction (2023)",
        "summary": "Court convicted 8-member trafficking ring of trafficking 134 women to Lebanon for domestic work. Sentences: 6-8 years imprisonment. Victim compensation: partial only. Appeals pending.",
        "source": "Nepal District Court / CIAA",
    },
    {
        "type": "penalty",
        "jurisdiction": "NP",
        "title": "CIAA Seizure: Illegal Recruitment Operation",
        "summary": "CIAA seized assets of illegal recruitment ring: NPR 45 lakh in cash, 10,000+ forged documents, passports. Operation had trafficked 450+ workers. Criminal case ongoing; victim restitution uncertain.",
        "source": "CIAA / Nepal Government",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "NP",
        "title": "Reference Falsification: Fake Previous Employment",
        "summary": "Agent created fake employment reference letters (fictitious companies, non-existent phone numbers). 89 workers submitted references to international employers. Fraud discovered during background checks; workers rejected.",
        "source": "DoFE Records",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Export Ban Threat: Worker Rights Improvement",
        "summary": "EU/US threatened to ban Bangladeshi garment imports if forced labor violations continued. Factory managers responded with superficial compliance (facade for audits). Structural exploitation patterns unchanged.",
        "source": "BGMEA / International Labor Sanctions",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Unemployment Among Return Migrants",
        "summary": "45% of Bangladeshi returned workers remain unemployed 6+ months post-return. Employers stigmatize returning migrants ('failed migrants'). Economic reintegration extremely challenging.",
        "source": "IOM / Bangladesh Employment Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Forced Marriage: Sexual Coercion of Domestic Workers",
        "summary": "10 Bangladeshi domestic workers in Saudi Arabia reported employer sexual coercion and forced marriage proposals. Refusal resulted in wage non-payment. Workers repatriated through embassy intervention.",
        "source": "Bangladesh Embassy Saudi Arabia / IOM",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Sexual Harassment in Migration",
        "summary": "Survey: 38% of female Bangladeshi migrant workers experience sexual harassment from employers/coworkers. Only 3% report incidents (fear of deportation, job loss). Incidents largely undocumented.",
        "source": "USDOL / ILO Assessment",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Wage Arrest: Salary Account Freezing",
        "summary": "Bangladeshi workers in Malaysia had employer-linked bank accounts frozen by employer (claiming 'security deposit'). Workers unable to access salaries; funds trapped. 156 workers affected.",
        "source": "Malaysia Labor Ministry / IOM",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "BD",
        "title": "Bangladesh Labor Court: Wrongful Termination Judgment",
        "summary": "Court awarded 234 workers wrongful termination compensation (8,000 BDT each). Employer appealed on grounds of 'business closure.' Appeal upheld; workers receive no compensation. Legal recourse ineffective.",
        "source": "Dhaka Labor Court",
    },
    {
        "type": "penalty",
        "jurisdiction": "BD",
        "title": "BMET Action: Unlicensed Agent Prosecution",
        "summary": "BMET prosecuted unlicensed recruitment agent operating in Dhaka. Agent had defrauded 267 workers. Sentence: 5 years imprisonment + 1 lakh BDT fine. Agent released on bail pending appeal.",
        "source": "BMET / Bangladesh Police",
    },
    {
        "type": "advisory",
        "jurisdiction": "BD",
        "title": "BGMEA Safety Awareness Campaign",
        "summary": "BGMEA launched safety training for garment workers covering fire evacuation, equipment safety, health hazards. Attendance mandatory; frequency variable (2-4 times/year). Effectiveness limited by language/literacy barriers.",
        "source": "BGMEA / Bangladesh Labor Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Exploitation Through Agent Debt",
        "summary": "Nepali worker indebted to agent for placement fee (NPR 200,000). Agent demanded additional payments for 'visa extension' (NPR 50,000), 'legal fees' (NPR 30,000), 'contract change' (NPR 25,000). Total debts: NPR 305,000 for worker earning NPR 25,000/month.",
        "source": "DoFE / Migrante Nepal",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Wage Earned vs. Wage Received Gap",
        "summary": "Survey of returned Nepali workers: average wage earned 1,500 QR/month. Average wage actually received: 1,100 QR (27% gap). Deductions: accommodation 30%, food 15%, utilities 10%, disciplinary 8%, other 37%.",
        "source": "IOM / DoFE Survey",
    },
    {
        "type": "complaint",
        "jurisdiction": "NP",
        "title": "Forced Loan Scheme: Wage Advance Trap",
        "summary": "Employer offered 'wage advances' to 89 Nepali workers at 20% interest (vs. 0% in contract). Workers borrowed for emergency family expenses. Interest compounds; workers trapped in cycle of indebtedness.",
        "source": "DoFE Records",
    },
    {
        "type": "complaint",
        "jurisdiction": "BD",
        "title": "Defective Merchandise Penalty: Deductions for Quality Issues",
        "summary": "Factory blamed workers for defective products (actually quality control failure). Deducted wages for 'penalty': 5-10% per incident. Workers absorbed costs of management/supplier failures.",
        "source": "Bangladesh Labor Ministry / BILS",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "BD",
        "title": "Work Substitution Upon Arrival: Different Sector Assignment",
        "summary": "45 Bangladeshi workers hired for 'garment factory quality control' in Singapore. Upon arrival, assigned to domestic service instead. Wages reduced 60%; working conditions deteriorated. No recourse available.",
        "source": "BMET Records",
    },
]
