"""NGO and IGO reports on trafficking and migrant exploitation — HRW, Amnesty, IOM, UNODC, Walk Free, Verite, and others."""

NGO_REPORT_FACTS: list[dict] = [
    # ── Human Rights Watch ──────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "HRW — 'As If I Am Not Human': Abuses against Asian Domestic Workers in Saudi Arabia (2008)",
        "summary": "Documented systemic abuse of domestic workers from Sri Lanka, Indonesia, and the Philippines in Saudi Arabia including forced confinement, 18-hour workdays, physical and sexual violence, and non-payment of wages. Found the kafala system structurally enables abuse by tying workers' legal status to employers. Recommended abolition of kafala and labor law coverage for domestic workers.",
        "source": "Human Rights Watch, July 2008",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "HRW — 'Bad Dreams': Exploitation and Abuse of Migrant Workers in Saudi Arabia (2004)",
        "summary": "Investigated conditions for construction, cleaning, and domestic workers in Saudi Arabia. Documented recruitment fee debts of USD 1,000-5,000, passport confiscation as standard employer practice, wage withholding for months, and denial of access to justice. Found government inspections virtually nonexistent for domestic workers.",
        "source": "Human Rights Watch, July 2004",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "HRW — 'The Island of Happiness': Exploitation of Migrant Workers on Saadiyat Island, Abu Dhabi (2009)",
        "summary": "Investigated labor conditions on Saadiyat Island cultural district construction (Louvre, Guggenheim). Found workers paying USD 2,000-4,000 recruitment fees, earning USD 175-300/month, housed in overcrowded labor camps. Passport confiscation was universal. Workers faced deportation for striking. Recommended cultural institutions condition partnerships on worker welfare standards.",
        "source": "Human Rights Watch, May 2009",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "HRW — 'Walls at Every Turn': Abuse of Migrant Domestic Workers through Kuwait's Sponsorship System (2010)",
        "summary": "Documented how Kuwait's kafala system traps domestic workers with abusive employers. Found 60% of interviewed workers reported not receiving promised salary. Workers who fled abuse were arrested for 'absconding.' Employers rarely prosecuted. Recommended Kuwait adopt protections equivalent to those in the national labor law.",
        "source": "Human Rights Watch, October 2010",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "HRW — 'How Can You Work Without Wages?': Salary Abuses Facing Migrant Workers Ahead of Qatar's 2022 FIFA World Cup (2020)",
        "summary": "Interviewed 93 current and former migrant workers across sectors. Found wage theft affecting thousands: delayed payments for 2-8 months, illegal deductions for food and accommodation, and non-payment of end-of-service benefits. Workers unable to leave Qatar without employer permission despite 2018 exit-permit abolition. Wage Protection System bypassed by employers who maintain dual payment records.",
        "source": "Human Rights Watch, August 2020",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "HRW — 'Qatar: Significant Labor and Kafala Reforms' — Assessment of Reforms (2021)",
        "summary": "Assessed Qatar's 2020 labor reforms including abolition of exit permits, non-discriminatory minimum wage of QAR 1,000, and ability to change employers. Found reforms significant on paper but enforcement gaps remain. Workers still fear employer retaliation. Labor dispute committees backlogged. Recommended strengthening enforcement mechanisms and worker complaint hotlines.",
        "source": "Human Rights Watch, September 2021",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "HRW — 'Rights on the Line': Human Rights Watch Work on Abuses against Migrant Workers in Qatar (2023)",
        "summary": "Comprehensive review of Qatar's post-World Cup labor landscape. Found improvements on stadium sites did not extend to broader economy. Workers in hospitality, cleaning, and private households still face systematic wage theft. Estimated hundreds of thousands of workers affected by stolen wages. Urged FIFA to establish remediation fund for worker compensation.",
        "source": "Human Rights Watch, May 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "TH",
        "title": "HRW — 'From the Tiger to the Crocodile': Abuse of Migrant Workers in Thailand (2010)",
        "summary": "Documented exploitation of Burmese migrant workers across Thai sectors including fishing, garment, and agriculture. Found workers subjected to forced labor, physical violence, and debt bondage. Thai police complicit: extorting migrants at checkpoints, selling detained workers back to brokers. Recommended Thailand ratify migrant worker conventions and reform police oversight.",
        "source": "Human Rights Watch, February 2010",
    },
    {
        "type": "case_study",
        "jurisdiction": "TH",
        "title": "HRW — Hidden Chains: Forced Labor and Rights Abuses in Thailand's Fishing Industry (2018)",
        "summary": "Investigated labor conditions on Thai fishing vessels following EU yellow card and US TIP Report downgrade. Found continued forced labor: workers confined to boats for months, physical violence, unpaid wages. Thailand's 2017 Royal Ordinance on Fisheries improved monitoring but enforcement remains inadequate. Port-in-port-out (PIPO) inspections are cursory. Workers fear reporting due to immigration status.",
        "source": "Human Rights Watch, January 2018",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "HRW — 'They Deceived Us at Every Step': Abuse of Cambodian Domestic Workers Migrating to Malaysia (2011)",
        "summary": "Documented recruitment fraud targeting Cambodian women: promised factory jobs at USD 200/month, placed as domestic workers at USD 100/month. Passports confiscated on arrival. Workers confined to employers' homes. Physical and sexual abuse documented. Malaysia-Cambodia recruitment bilateral agreement lacked enforcement mechanisms.",
        "source": "Human Rights Watch, November 2011",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "HRW — 'Turning a Blind Eye': Forced Labour of North Koreans in Malaysian Factories (2023)",
        "summary": "Investigated North Korean workers in Malaysia despite UN sanctions requiring repatriation by 2019. Found DPRK workers in electronics and manufacturing factories. Workers paid directly by North Korean government handlers who confiscated up to 90% of earnings. Workers under 24-hour surveillance, unable to communicate with outsiders. Malaysia's failure to comply with UNSC Resolution 2397.",
        "source": "Human Rights Watch, March 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "HRW — 'Fingers to the Bone': United States Failure to Protect Child Farmworkers (2000, updated 2010)",
        "summary": "Documented child farmworkers as young as 12 working in US agriculture legally under FLSA exemptions. Children exposed to pesticides, sharp tools, and extreme heat. 80% of child farmworkers are Latino, many from migrant families. US agriculture remains the only industry allowing children under 14 to work. Updated 2010 report found little improvement.",
        "source": "Human Rights Watch, June 2000 / June 2010",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "HRW — 'Tobacco's Hidden Children': Hazardous Child Labor in US Tobacco Farming (2014)",
        "summary": "Found children ages 7-17 working on US tobacco farms in Kentucky, Virginia, North Carolina, and Tennessee. Children reported nausea, vomiting, and headaches consistent with nicotine poisoning. Working 50-60 hours/week during harvest. Many are children of Hispanic migrant workers. Federal law exempts agriculture from minimum age requirements that apply to all other sectors.",
        "source": "Human Rights Watch, May 2014",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "HRW — 'Without Protection': How the Lebanese Justice System Fails Migrant Domestic Workers (2010)",
        "summary": "Documented 40+ domestic worker deaths per year in Lebanon (suicides, falls from buildings during escape attempts). Found kafala system prevents workers from leaving abusive employers. Police return fleeing workers to employers. Consulates overwhelmed. Recommended abolition of kafala, criminal investigation of all domestic worker deaths, and labor law inclusion for domestic workers.",
        "source": "Human Rights Watch, September 2010",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "HRW — 'Their House Is My Prison': Exploitation of Migrant Domestic Workers in Lebanon (2023)",
        "summary": "Follow-up investigation found Lebanon's economic crisis (2019-present) worsened domestic worker conditions. Employers stopped paying wages, abandoned workers. Estimated 250,000 migrant domestic workers in Lebanon. At least 1 domestic worker death per week. Workers from Ethiopia, Philippines, Sri Lanka, Bangladesh. Kafala reform stalled in parliament since 2020.",
        "source": "Human Rights Watch, February 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "HRW — 'I Already Bought You': Abuse and Exploitation of Female Migrant Domestic Workers in the UAE (2014)",
        "summary": "Investigated conditions of 146,000+ domestic workers in the UAE. Documented: 100-hour work weeks, food deprivation, physical and sexual abuse, unpaid wages. Workers quoted employers saying 'I bought you' and 'you are my property.' UAE's 2012 domestic worker regulations lack enforcement. Ministerial Decree 2014 introduced standard contract but permitted 12-hour days.",
        "source": "Human Rights Watch, October 2014",
    },
    {
        "type": "case_study",
        "jurisdiction": "OM",
        "title": "HRW — 'I Was Sold': Abuse and Exploitation of Migrant Domestic Workers in Oman (2016)",
        "summary": "Documented abuse of domestic workers from Bangladesh, India, Philippines, Tanzania, and Indonesia in Oman. Workers reported passport confiscation (100%), wage withholding (70%), confinement to home (50%), physical abuse (30%). Oman lacks standalone domestic worker legislation. Kafala system unchanged despite regional reform momentum.",
        "source": "Human Rights Watch, July 2016",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "HRW — 'Exported and Exposed': Abuses against Sri Lankan Domestic Workers in Saudi Arabia, Kuwait, Lebanon, and the UAE (2007)",
        "summary": "Documented exploitation of Sri Lankan domestic workers across four Gulf countries. Found 90% of interviewees had passports confiscated. Average recruitment debt: USD 500-1,000 (3-6 months salary). Workers who fled abuse placed in deportation detention. Sri Lanka's Bureau of Foreign Employment unable to protect workers abroad. Recommended mandatory contract enforcement by receiving states.",
        "source": "Human Rights Watch, November 2007",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "HRW — 'Sold Like Fish': Crimes Against Humanity, Mass Graves, and Human Trafficking from Myanmar and Bangladesh to Malaysia (2015)",
        "summary": "Investigated mass graves found at trafficking camps in Wang Kelian, Perlis, Malaysia (May 2015). 139 graves discovered. Rohingya and Bangladeshi victims held for ransom by Thai-Malaysian trafficking networks. Those who could not pay were tortured, starved, or killed. Triggered regional migration crisis. Thailand convicted 62 traffickers including a general (2017).",
        "source": "Human Rights Watch, September 2015",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "HRW — Saudi Arabia: Steps to Address Abuse Fall Short — Kafala System Review (2021)",
        "summary": "Assessed Saudi Arabia's March 2021 kafala reforms allowing some workers to transfer employers. Found reforms exclude domestic workers (3.7 million people). Workers must still obtain employer consent for certain transactions. New initiatives (Musaned platform) improve transparency but do not address structural power imbalance. Recommended extending all reforms to domestic workers.",
        "source": "Human Rights Watch, March 2021",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "HRW — Qatar: Take Urgent Action to Protect Construction Workers — Heat Stress Deaths (2019)",
        "summary": "Investigated worker deaths classified as 'natural causes' or 'cardiac arrest' among young, healthy construction workers. Found Qatar's heat ban (10am-3:30pm outdoor work prohibition, June-September) is inadequate. Workers report extreme heat stress, insufficient water breaks, and employer pressure to continue working. Recommended mandatory rest based on wet-bulb globe temperature rather than time-based restrictions.",
        "source": "Human Rights Watch, October 2019",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "HRW — 'Swept Under the Rug': Abuses against Domestic Workers Around the World (2006)",
        "summary": "Global survey of domestic worker abuse across 12 countries. Found universal patterns: exclusion from labor law, confinement to employer homes, physical and sexual violence, wage theft. Estimated 100 million domestic workers worldwide (2006, pre-ILO C189). Recommended all countries extend labor law protections to domestic workers. Catalyzed ILO Convention 189 campaign.",
        "source": "Human Rights Watch, July 2006",
    },
    {
        "type": "case_study",
        "jurisdiction": "BH",
        "title": "HRW — 'For a Better Life': Migrant Worker Abuse in Bahrain and the Government Reform Agenda (2012)",
        "summary": "Assessed Bahrain's 2009 labor reforms including LMRA (Labour Market Regulatory Authority) and flexi-permit system. Found reforms allowed some workers to change employers but left domestic workers unprotected. Construction and service workers still face: recruitment fee debt, cramped housing, wage delays. LMRA under-resourced with only 30 inspectors for 600,000+ foreign workers.",
        "source": "Human Rights Watch, October 2012",
    },
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "HRW — 'Prisoners of the Past': Kuwaiti Bidun and the Burden of Statelessness (2011) — Domestic Worker Section",
        "summary": "Alongside documentation of bidun (stateless) discrimination, investigated domestic worker conditions. Kuwait employed 660,000 domestic workers (2011). Found: one domestic worker dies every week, many from suicide or falling during escape attempts. Employers who abuse workers rarely prosecuted. Recommended criminalizing passport confiscation with meaningful penalties.",
        "source": "Human Rights Watch, June 2011",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "HRW — 'Cultivating Fear': The Vulnerability of Immigrant Farmworkers in the US to Sexual Violence and Sexual Harassment (2012)",
        "summary": "Documented sexual violence against women farmworkers in US agriculture. Found 80% of women farmworkers experience sexual harassment. Workers fear reporting due to immigration status, employer retaliation, and law enforcement distrust. H-2A visa workers particularly vulnerable as tied to single employer. Recommended EEOC enforcement and immigration protections for victims.",
        "source": "Human Rights Watch, May 2012",
    },
    # ── Amnesty International ───────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Amnesty — 'The Dark Side of Migration': Spotlight on Qatar's Construction Sector Ahead of the World Cup (2013)",
        "summary": "First major investigation into Qatar World Cup construction labor. Interviewed workers from Nepal, India, and Sri Lanka. Documented: 6-7 months without pay, confiscated passports, overcrowded and unsanitary housing, 12-hour shifts in extreme heat. Workers unable to leave country due to exit-permit requirement. Qatar denied systemic problems. Report triggered international pressure on FIFA and Qatar.",
        "source": "Amnesty International, November 2013",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Amnesty — 'All Work, No Pay': The Struggle of Qatar's Migrant Workers for Justice (2019)",
        "summary": "Follow-up investigation found wage theft remains endemic despite Wage Protection System. Documented workers who filed complaints waiting 1-2 years for resolution. Companies declare bankruptcy to avoid paying workers. Qatar's Worker Support and Insurance Fund (established 2018) inadequately funded. Workers deported before receiving owed wages. Estimated USD 440 million in stolen wages annually.",
        "source": "Amnesty International, September 2019",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Amnesty — 'Predictable and Preventable': Why FIFA and Qatar Should Remedy Abuses Behind the 2022 World Cup (2022)",
        "summary": "Called on FIFA to set aside USD 440 million (equivalent to World Cup prize money) for worker compensation. Documented deaths and injuries among stadium construction workers. Found Qatar's reforms came too late for thousands. FIFA earned USD 7.5 billion from tournament while workers and their families received no remedy. Campaign gathered 1 million+ signatures globally.",
        "source": "Amnesty International, May 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Amnesty — 'Qatar: Abuse of World Cup Workers Exposed' — Stadium Construction Conditions (2016)",
        "summary": "Investigated Khalifa International Stadium refurbishment. Documented: workers living in squalid conditions, sleeping 12 to a room, food often inedible. Some workers not paid for months. Workers from Nepal, India, and Bangladesh held in labor camps without freedom of movement. Found forced labor indicators present on FIFA project sites despite Supreme Committee monitoring.",
        "source": "Amnesty International, March 2016",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "Amnesty — 'Isolated and Abused': Migrant Domestic Workers in the UAE (2014)",
        "summary": "Documented exploitation of 146,000+ domestic workers in UAE. Found: live-in requirement creates isolation, no labor law coverage for domestic workers, employers control visa status. Workers from Philippines, Indonesia, India, Bangladesh, Ethiopia. 92% of interviewed workers had passports confiscated. Workers who flee face arrest for 'absconding.' Recommended comprehensive domestic worker legislation.",
        "source": "Amnesty International, December 2014",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "Amnesty — 'There Is No Freedom Here': Silencing Dissent on Saadiyat Island, Abu Dhabi (2014)",
        "summary": "Follow-up on Saadiyat Island labor conditions. Interviewed workers on NYU Abu Dhabi and Louvre Abu Dhabi sites. Found: workers afraid to speak to investigators, surveillance of worker accommodation, activists and journalists denied entry. TDIC's Worker Welfare Policy selectively enforced on high-profile sites while subcontractors operate without oversight.",
        "source": "Amnesty International, June 2014",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Amnesty — 'Their Lives Are Ruined': Barriers to Justice for Migrant Domestic Workers in Lebanon (2019)",
        "summary": "Investigated death of at least two domestic workers per week in Lebanon. Found judicial system fails to investigate deaths or prosecute employers. Autopsies cursory or absent. Workers who report abuse charged with 'theft' or 'absconding' by employers as counter-complaints. Recommended independent investigation of all domestic worker deaths and abolition of kafala.",
        "source": "Amnesty International, April 2019",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Amnesty — Lebanon: Migrant Domestic Workers Abandoned During Economic Crisis (2020)",
        "summary": "Documented how Lebanon's economic collapse and Beirut explosion (August 2020) left migrant domestic workers destitute. Employers abandoned workers at consulates or on streets. Workers unable to afford return flights. Ethiopian government evacuated 3,000+ nationals. Estimated 250,000 domestic workers in Lebanon, many unpaid for 6+ months during crisis.",
        "source": "Amnesty International, August 2020",
    },
    {
        "type": "case_study",
        "jurisdiction": "LY",
        "title": "Amnesty — 'Libya's Dark Web of Collusion': Abuses Against Europe-Bound Refugees and Migrants (2017)",
        "summary": "Documented systematic abuse of migrants and refugees in Libyan detention centers. Found evidence of: forced labor, torture for ransom, sexual violence, and 'slave auctions' (corroborated by CNN investigation). EU-funded Libyan Coast Guard intercepts migrants and returns them to detention. Estimated 20,000 people in official detention; unknown number in unofficial facilities run by militias.",
        "source": "Amnesty International, December 2017",
    },
    {
        "type": "case_study",
        "jurisdiction": "LY",
        "title": "Amnesty — 'Between Life and Death': Refugees and Migrants Trapped in Libya (2020)",
        "summary": "Updated investigation found conditions worsened during COVID-19. Migrants trapped without medical care. Detention center overcrowding. IOM voluntary return flights suspended. Workers forced to labor on construction and agriculture under armed guard. EU continued support for Libyan coast guard despite documented abuse. Called for EU to suspend cooperation and establish safe passage routes.",
        "source": "Amnesty International, September 2020",
    },
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "Amnesty — 'Bitter Harvest': Exploitation of Migrant Agricultural Workers in South Korea (2014)",
        "summary": "Investigated conditions of EPS workers on South Korean farms. Found: 15-16 hour days during harvest, no overtime pay, housing in vinyl greenhouses (extreme cold in winter, 50C in summer). Workers unable to change employers under EPS restrictions. Cambodian, Vietnamese, and Thai workers most affected. Recommended EPS reform to allow free job mobility.",
        "source": "Amnesty International, October 2014",
    },
    {
        "type": "case_study",
        "jurisdiction": "IT",
        "title": "Amnesty — 'Exploited Labour': Migrant Workers in Italy's Agricultural Sector (2012)",
        "summary": "Documented 'caporalato' system in southern Italy where gang masters (caporali) recruit migrant workers for agricultural labor. Workers paid EUR 20-25 per day, transported to fields under dangerous conditions. Housing in informal settlements without sanitation. Workers from sub-Saharan Africa, Eastern Europe, and South Asia. Italy criminalized caporalato in 2011 but enforcement remains weak.",
        "source": "Amnesty International, June 2012",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "Amnesty — 'Trapped: The Exploitation of Migrant Workers in Malaysia' (2010)",
        "summary": "Investigated conditions across sectors: electronics, palm oil, construction, domestic work. Found recruitment fees of USD 2,000-5,000, passport confiscation in 90% of cases, employer-controlled work permits preventing job change. Documented raids on undocumented workers by RELA volunteer corps leading to abuse and extortion. Recommended Malaysia ratify ICRMW and reform work permit system.",
        "source": "Amnesty International, March 2010",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Amnesty — 'Reality Check 2021': One Year of Broken Promises to Migrant Workers in Qatar (2021)",
        "summary": "Assessed implementation of Qatar's landmark labor reforms one year after enactment. Found: workers still require NOC in practice, minimum wage enforcement weak, dispute resolution slow (average 6 months). Employers use 'absconding' charges to punish workers who leave. Some companies switched to piece-rate pay to circumvent minimum wage. Reform process incomplete.",
        "source": "Amnesty International, August 2021",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Amnesty — 'Shameful: Saudi Arabia's Record of Executing the Most Vulnerable' — Migrant Worker Executions (2019)",
        "summary": "Documented executions of migrant workers, including domestic workers, after trials that lacked due process. Workers faced language barriers in court, denied legal representation, and coerced confessions. Indonesian and Filipino domestic workers executed for killing abusive employers in self-defense. Recommended moratorium on death penalty for migrant workers and mandatory legal aid.",
        "source": "Amnesty International, April 2019",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Amnesty — 'In the Firing Line': Attacks on Healthcare Workers in Conflict — Impact on Migrant Workers (2016)",
        "summary": "Documented impact of armed conflicts on migrant workers trapped in war zones (Yemen, Libya, Syria). Migrant workers unable to evacuate due to passport confiscation by employers. Filipino, Ethiopian, and South Asian workers stranded in Yemen during 2015 conflict. Workers forced to continue working under bombardment. Embassies overwhelmed during evacuations.",
        "source": "Amnesty International, August 2016",
    },
    # ── IOM (International Organization for Migration) ──────────────────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "IOM Counter-Trafficking Data Collaborative (CTDC) — Global Dataset (2002-2022)",
        "summary": "CTDC aggregates data from 189 countries with 156,000+ individual case records. Findings: 77% of trafficking victims exploited within their region of origin. 65% of detected victims are female. Labor exploitation accounts for 38% of detected cases globally (higher in Gulf, Southeast Asia). Average exploitation duration: 20 months. Most common sectors: domestic work, agriculture, construction, manufacturing.",
        "source": "IOM CTDC, 2023 update",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "IOM — Return and Reintegration: Effective Approaches (2019)",
        "summary": "Studied 90,000+ assisted voluntary returns (2015-2018). Found 60% of returnees from trafficking situations face re-trafficking risk within 2 years. Economic reintegration most effective when combining cash grants, skills training, and psychosocial support. Countries with government-funded reintegration programs (Philippines, Indonesia) show better outcomes than those relying solely on NGOs.",
        "source": "IOM, 2019",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "IOM — Missing Migrants Project: Deaths During Migration (2014-2023)",
        "summary": "Documented 59,032+ migrant deaths worldwide (2014-2023). Mediterranean Sea: 28,000+ deaths. US-Mexico border: 4,000+ deaths. Sahara Desert: 5,600+ deaths (likely severe undercount). Andaman Sea/Bay of Bengal: 2,200+ deaths. Causes: drowning (58%), vehicle accidents (9%), violence (6%), exposure (5%), illness (5%). 2023 was deadliest year on record with 8,541 deaths documented.",
        "source": "IOM Missing Migrants Project, 2024 update",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "IOM — Recruitment Monitoring and Migrant Welfare: IRIS Standard (2014)",
        "summary": "IOM's International Recruitment Integrity System (IRIS) established ethical recruitment standard. Voluntary certification for recruitment agencies. Principles: no fees charged to workers, transparent contracts, free consent, access to grievance mechanisms. By 2023, 30+ agencies certified globally. Found that IRIS-certified agencies charge 80% lower fees on average. Recommended mandatory adoption of IRIS standards.",
        "source": "IOM IRIS, 2023 annual report",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "IOM — Displacement Tracking Matrix: Labor Mobility in Crisis Contexts (2022)",
        "summary": "Tracked 7.7 million internally displaced and mobile populations in 88 countries. Found displaced workers 3x more vulnerable to exploitation. 45% of displaced workers in informal employment without contracts. Recruitment fees for displaced populations average 30% higher than for non-displaced workers. Recommended humanitarian response integration with labor mobility protection.",
        "source": "IOM DTM, 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "IOM — World Migration Report 2024: Labor Migration Trends",
        "summary": "Estimated 281 million international migrants (2020, 3.6% of world population). 169 million international migrant workers (2019, ILO estimate). Remittances to LMICs reached USD 656 billion (2022), exceeding FDI. COVID-19 caused 20% drop in new labor migration permits (2020). Recovery uneven: Gulf states returned to pre-pandemic levels by 2022 while other corridors lagged.",
        "source": "IOM World Migration Report 2024",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "IOM — Recruitment Costs in Bangladesh: Who Pays and How Much? (2019)",
        "summary": "Surveyed 1,500 Bangladeshi migrant workers. Found average recruitment cost: USD 3,900 (range USD 800-14,000). Workers bound for Saudi Arabia pay most (USD 4,700 average). 62% of workers borrow money at interest rates of 10-30% per month. Sub-agents in villages take USD 500-2,000 commission. Government-mandated maximum fee of BDT 84,000 (USD 990) is universally exceeded.",
        "source": "IOM Bangladesh, 2019",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "IOM — Nepali Migrant Workers: Recruitment Practices and Vulnerability (2020)",
        "summary": "Investigated recruitment chain for Nepali workers going to Gulf states and Malaysia. Found 5-6 intermediaries between worker and employer. Average cost: NPR 150,000-300,000 (USD 1,200-2,400) despite legal cap of NPR 10,000. Workers from remote districts pay more. Pre-departure orientation attended by only 40% of workers. 70% of workers sign contracts they cannot read (Arabic language).",
        "source": "IOM Nepal, 2020",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "IOM — Global Trafficking Trends: Victims Assisted by IOM (2023)",
        "summary": "IOM directly assisted 12,400+ trafficking victims in 2022. Top nationalities: Nigerian, Venezuelan, Ukrainian, Filipino, Bangladeshi. 54% labor exploitation, 26% sexual exploitation, 20% mixed. Median age: 28 years. Children: 18% of assisted victims. Average time in exploitation before identification: 14 months. Post-identification: 40% require long-term psychosocial support.",
        "source": "IOM Counter-Trafficking, 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "MM",
        "title": "IOM — Myanmar Workers in Thailand and Malaysia: Migration, Exploitation, and COVID-19 (2021)",
        "summary": "Documented impact of COVID-19 on 4 million+ Myanmar workers in Thailand and 400,000+ in Malaysia. Factory closures left workers without income or return options. Workers in crowded dormitories faced COVID outbreaks. 60% lost employment during lockdowns. Workers with expired documents unable to access healthcare. Myanmar coup (February 2021) prevented return. IOM recommended regularization of undocumented workers.",
        "source": "IOM Regional Office for Asia and the Pacific, 2021",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "title": "IOM — Ethiopian Migrant Workers to the Gulf and Middle East: Trafficking Risks and Return Challenges (2022)",
        "summary": "Documented trafficking of Ethiopian workers along the Eastern Route (Ethiopia-Djibouti-Yemen-Saudi Arabia). Estimated 150,000+ Ethiopians attempt journey annually. Found: broker networks charge USD 800-2,000, workers face kidnapping in Yemen, Saudi Arabia mass deported 700,000 Ethiopians (2013-2014, 2022-2023). Returnees face stigma, debt, and mental health challenges. IOM assisted 94,000 Ethiopian returns (2017-2022).",
        "source": "IOM Regional Office for East and Horn of Africa, 2022",
    },
    # ── UNODC ───────────────────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "UNODC Global Report on Trafficking in Persons 2022 — Key Findings",
        "summary": "Based on 141 country reports. Key findings: detected victims decreased 11% during COVID-19 (2020) suggesting hidden increase. 42% of victims trafficked for forced labor (up from 38% in 2018). 41% trafficked for sexual exploitation. Domestic trafficking: 65% of cases. Child victims: 35% of total (girls 19%, boys 16%). Conviction rates declined: 2 convictions per 100,000 population in Europe vs 0.1 in Africa.",
        "source": "UNODC, 2022",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "UNODC — Trafficking Prosecution and Conviction Data (2022)",
        "summary": "Global prosecution data: 9,700 prosecutions and 3,700 convictions for trafficking in persons (2020). Conviction rate varies: 60-70% in Europe and Americas, 20-30% in Africa and South Asia. Forced labor convictions lag behind sexual exploitation: only 23% of convictions despite 42% of victims. Prosecutions for labor trafficking increased 30% from 2017-2020 but remain insufficient.",
        "source": "UNODC Global Report on TIP, 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "UNODC — Organized Crime and Trafficking Nexus: Transnational Criminal Networks (2021)",
        "summary": "Analyzed relationship between organized crime groups and trafficking. Found trafficking generates estimated USD 150 billion/year in illegal profits (ILO estimate). Criminal networks operate across 3+ countries. Gulf trafficking networks involve: origin-country recruiters, transit brokers, destination-country sponsors. Profit margins highest in forced labor (USD 34 billion) and sexual exploitation (USD 99 billion).",
        "source": "UNODC, 2021",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "UNODC — Regional Trafficking Patterns: South and Southeast Asia (2022)",
        "summary": "South Asia: 80% of trafficking is internal. Cross-border: India-Gulf, Bangladesh-Gulf-Malaysia, Nepal-Gulf-India most common. Southeast Asia: 60% cross-border. Myanmar workers trafficked to Thailand, Malaysia, China. Cambodia-Thailand fishing corridor. Vietnam-UK-EU cannabis/nail salon trafficking. Philippines: primarily to Gulf and East Asian destinations. COVID-19 shifted trafficking online.",
        "source": "UNODC Global Report on TIP, 2022",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "UNODC — Regional Trafficking Patterns: Africa and Middle East (2022)",
        "summary": "Africa: Sub-Saharan Africa has lowest detection rate globally (0.5 victims per 100,000 population). Nigerian networks traffic to Europe and Gulf. East Africa to Gulf (Ethiopia, Kenya, Uganda). Child trafficking for armed conflict in Sahel. Middle East: destination region for labor trafficking from South Asia, Southeast Asia, East Africa. GCC states primary destinations. Domestic worker trafficking most common form.",
        "source": "UNODC Global Report on TIP, 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "UNODC — Impact of COVID-19 on Trafficking in Persons (2021)",
        "summary": "Found COVID-19 increased vulnerability to trafficking through: economic desperation, reduced mobility trapping victims, closed courts and shelters, reduced law enforcement capacity. Online recruitment increased 30-40%. Domestic trafficking rose as international routes disrupted. Supply chain disruptions left workers stranded. Recommendation: trafficking prevention must be integrated into pandemic response.",
        "source": "UNODC, Research Brief 2021",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "UNODC — Trafficking Victims: Profiles and Vulnerabilities (2022)",
        "summary": "Global victim profile analysis (50,000+ detected victims, 2017-2020): 42% adult women, 23% girls, 20% adult men, 15% boys. Labor exploitation victims: 60% male. Sexual exploitation victims: 95% female. Average age at recruitment: 26 years (adults), 14 years (children). Most common vulnerability factors: poverty (82%), lack of education (45%), irregular migration status (38%), gender discrimination (35%).",
        "source": "UNODC Global Report on TIP, 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "UNODC — Technology and Trafficking: Online Recruitment and Exploitation (2022)",
        "summary": "Documented increasing use of social media for trafficking recruitment. Facebook, Instagram, and messaging apps used by 30% of detected trafficking cases. Fake job advertisements on online platforms target vulnerable populations. Cryptocurrency used for ransom payments. Cyber-enabled trafficking (online sexual exploitation) increased 100% during COVID-19. Recommended platform liability and proactive content moderation.",
        "source": "UNODC, 2022",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "UNODC — Child Trafficking: Global Patterns (2022)",
        "summary": "Children represent 35% of detected trafficking victims globally. In sub-Saharan Africa: 60% of detected victims are children. Forms: forced labor (46%), sexual exploitation (30%), child soldiers (9%), forced begging (8%), organ removal (2%). Most child trafficking is domestic (77%). Girls trafficked primarily for sexual exploitation and domestic servitude; boys for forced labor, begging, and armed conflict.",
        "source": "UNODC Global Report on TIP, 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "UNODC — Trafficking for Organ Removal: Emerging Trends (2021)",
        "summary": "Investigated trafficking for organ removal across regions. Found: kidney trafficking most common (85% of cases). Victims recruited from impoverished communities with promises of USD 5,000-15,000 (typically paid only 10-20% of promised amount). Organized networks operate across Egypt, South Africa, India, China, Central America. Estimated 10% of organ transplants globally involve trafficked organs. Recommended mandatory organ donation traceability.",
        "source": "UNODC, 2021",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "UNODC — Trafficking in Maritime Fisheries: A Global Review (2020)",
        "summary": "Documented forced labor on fishing vessels across oceans. Found: workers from Myanmar, Cambodia, Indonesia, Philippines, Ghana, and Senegal. Confinement at sea for months to years. Violence and deaths at sea. Key regions: Southeast Asia (Thailand, Indonesia), West Africa, South Atlantic. ILO Work in Fishing Convention (C188) ratified by only 19 states. Port state measures critical for detection.",
        "source": "UNODC, 2020",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "UNODC — Legislative Frameworks: Assessment of Anti-Trafficking Laws Globally (2022)",
        "summary": "Reviewed anti-trafficking legislation in 193 countries. Found: 178 countries have specific trafficking criminalization (up from 33 in 2003 when Palermo Protocol entered into force). However, 80% of countries have gaps in victim protection provisions. Only 50% provide non-punishment for victims. 60% lack mandatory identification procedures. Recommended comprehensive legislation aligning with Palermo Protocol Article 6 (victim assistance).",
        "source": "UNODC Global Report on TIP, 2022",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "UNODC — Financial Flows from Trafficking: Profit Estimates (2022)",
        "summary": "Trafficking generates USD 150 billion/year in illegal profits (ILO-UNODC joint estimate). Breakdown: forced sexual exploitation USD 99 billion, forced labor exploitation USD 34 billion (construction USD 12B, manufacturing USD 9B, agriculture USD 5B, domestic work USD 8B), state-imposed forced labor USD 12 billion, forced marriage USD 5 billion. Profits per victim: USD 21,800/year (sexual exploitation) vs USD 4,800/year (labor exploitation).",
        "source": "UNODC / ILO Joint Estimate, 2022",
    },
    # ── Walk Free Foundation / Global Slavery Index ─────────────────────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Walk Free — Global Slavery Index 2023: Headline Findings",
        "summary": "Estimated 49.6 million people in modern slavery (2021): 27.6 million in forced labor, 22 million in forced marriage. Increase of 10 million since 2016 estimates. 12% of those in forced labor are children. 52% of all forced labor is in Asia-Pacific. 86% of forced labor occurs in the private sector. COVID-19 estimated to have pushed 10 million additional people into modern slavery conditions.",
        "source": "Walk Free Foundation, Global Slavery Index 2023",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Walk Free — Global Slavery Index: Prevalence Rankings by Country (2023)",
        "summary": "Highest prevalence (per 1,000 population): North Korea (104.6), Eritrea (90.3), Mauritania (32.0), Saudi Arabia (21.3), Turkiye (15.6), Tajikistan (14.7), UAE (14.3), Russia (13.4), Afghanistan (13.1), Kuwait (12.9). Lowest prevalence: Switzerland (0.5), Norway (0.5), Germany (0.6), Netherlands (0.6), Sweden (0.7). Prevalence correlates with: conflict, governance quality, discrimination, and migration policy.",
        "source": "Walk Free Foundation, Global Slavery Index 2023",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Walk Free — Global Slavery Index: Government Response Ratings (2023)",
        "summary": "Rated government responses across 160 countries on 5 milestones: survivors identified and supported, criminal justice response, national coordination, risk factors addressed, supply chains cleaned. Top-rated: Netherlands (score 82.5/100), US (77.3), UK (77.0), Portugal (75.7), Australia (73.3). Lowest: North Korea (0), Eritrea (2.5), Iran (5.0), Equatorial Guinea (5.5), Libya (6.3). GCC states: Qatar (42.5) leads, Saudi Arabia (20.0) lags.",
        "source": "Walk Free Foundation, Global Slavery Index 2023",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Walk Free — Global Slavery Index: Sector Vulnerability Assessment (2023)",
        "summary": "Assessed vulnerability by sector globally. Highest risk sectors: domestic work (16.4 million in forced labor), construction (3.6 million), manufacturing (3.2 million), agriculture and fishing (2.7 million), hospitality (1.2 million), mining (600,000). Sexual exploitation: 6.3 million. Supply chain exposure: G20 countries import USD 468 billion in products at risk of being produced by forced labor annually.",
        "source": "Walk Free Foundation, Global Slavery Index 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Walk Free — G20 Countries and Modern Slavery: At-Risk Imports (2023)",
        "summary": "Analyzed imports at risk of forced labor into G20 countries. Found USD 468 billion in at-risk imports annually. Top products: electronics (USD 215B), garments (USD 147B), palm oil (USD 19B), sugar (USD 5B), fish (USD 4B). Top importing countries: US (USD 135B), Germany (USD 62B), UK (USD 45B), Japan (USD 43B), France (USD 38B). Recommended mandatory import due diligence and customs enforcement.",
        "source": "Walk Free Foundation, 2023",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Walk Free — Forced Labour in State-Imposed Contexts (2023)",
        "summary": "Estimated 3.9 million people in state-imposed forced labor. Contexts: prison labor exceeding lawful sentences, military conscription for economic purposes, compulsory participation in public works. Top countries: China (Xinjiang forced labor programs), North Korea (overseas worker deployment), Eritrea (indefinite national service), Turkmenistan (cotton harvest mobilization), Uzbekistan (cotton harvest, reforms since 2021).",
        "source": "Walk Free Foundation, Global Slavery Index 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Walk Free — Measurement Methodology: Estimating Modern Slavery (2023)",
        "summary": "Walk Free methodology combines: representative household surveys in 68 countries (75,000+ interviews), ILO and IOM administrative data, statistical modeling for non-surveyed countries. Limitations: surveys cannot capture all forms (state-imposed, trafficking in transit), low-prevalence countries have high uncertainty margins. Confidence interval for global estimate: 45-55 million. Methodology reviewed by external experts and ILO.",
        "source": "Walk Free Foundation, Global Slavery Index 2023 — Methodology Chapter",
    },
    {
        "type": "statistic",
        "jurisdiction": "AU",
        "title": "Walk Free — Australia's Modern Slavery Risk Profile (2023)",
        "summary": "Estimated 41,000 people in modern slavery in Australia (1.6 per 1,000 population). Key sectors: agriculture (fruit picking, horticulture), domestic work, construction, hospitality, meat processing. Vulnerable populations: Pacific Island seasonal workers, international students, undocumented migrants. Government response rated 73.3/100 but Modern Slavery Act lacks penalties for non-compliance with reporting requirements.",
        "source": "Walk Free Foundation, Global Slavery Index 2023",
    },
    {
        "type": "statistic",
        "jurisdiction": "IN",
        "title": "Walk Free — India Modern Slavery Estimate (2023)",
        "summary": "Estimated 11 million people in modern slavery in India (8 per 1,000 population). Largest absolute number of any country. Forms: bonded labor in brick kilns, agriculture, garment manufacturing, domestic servitude, sexual exploitation. Internal trafficking dominates. Caste-based discrimination a key vulnerability factor. Government response rated 55.5/100. Bonded Labour Abolition Act (1976) inadequately enforced.",
        "source": "Walk Free Foundation, Global Slavery Index 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Walk Free — Forced Marriage: Global Estimates and Trends (2023)",
        "summary": "Estimated 22 million people living in forced marriage (2021). 14.2 million entered forced marriage in the 5-year period 2017-2021. Sub-Saharan Africa: highest prevalence (14.5 per 1,000). South Asia: largest absolute numbers. 73% of forced marriages involve women and girls. 30% involve children. Bride price and dowry practices contribute. COVID-19 school closures increased child marriage risk by 10 million additional girls at risk over next decade.",
        "source": "Walk Free Foundation, Global Slavery Index 2023",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Walk Free — Forced Labor in Private Economy by Region (2023)",
        "summary": "Asia-Pacific: 15.1 million in forced labor (55% of global total). Africa: 3.8 million (14%). Europe and Central Asia: 4.1 million (15%). Americas: 3.6 million (13%). Arab States: 0.9 million (3%). Asia-Pacific increase driven by: large migrant worker populations, weak labor governance, extensive informal economy, and supply chain demand for cheap labor. Arab States highest prevalence rate per capita.",
        "source": "Walk Free Foundation / ILO Joint Estimate, 2022",
    },
    # ── Verite ──────────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "Verite — Forced Labor in the Production of Electronic Goods in Malaysia (2014)",
        "summary": "Landmark investigation of electronics supply chains in Malaysia. Surveyed 501 workers across 200+ factories. Found 32% of foreign workers in conditions of forced labor. Indicators: recruitment fees averaging USD 4,300 (2-7 months wages), passport confiscation (75%), restricted movement (50%), deceptive recruitment (65%). Companies supplying Apple, Samsung, and HP. Led to major brand auditing reforms and US CBP enforcement actions.",
        "source": "Verite, 2014",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "Verite — Recruitment Practices and Migrant Labor Conditions in Malaysian Palm Oil (2016)",
        "summary": "Investigated labor conditions on Malaysian palm oil plantations. Found: recruitment fees USD 1,500-4,000, passport retention universal on plantations, workers housed in remote estates without freedom of movement, children working alongside parents. Indonesian and Bangladeshi workers most affected. Product enters global supply chains through Wilmar, Sime Darby, IOI. Recommended RSPO standards enforcement and importer due diligence.",
        "source": "Verite, 2016",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Verite — Labor Conditions in Brazilian Sugarcane and Cattle Ranching (2015)",
        "summary": "Documented forced labor in Brazilian agribusiness. Found: internal migrants from northeast Brazil recruited to remote cattle ranches and sugarcane plantations in Para, Mato Grosso. Workers indebted through transport and supply costs. 'Dirty list' (Lista Suja) names 500+ employers convicted of forced labor. Brazil's 'Mobile Inspection Group' has freed 55,000+ workers since 1995. Model for other countries.",
        "source": "Verite, 2015",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Verite — Strengthening Protections Against Trafficking in Persons in Federal and Corporate Supply Chains (2017)",
        "summary": "Analysis of US Federal Acquisition Regulation (FAR) anti-trafficking provisions and corporate compliance. Found: federal contractors lack adequate monitoring, workers in overseas subcontractor facilities face exploitation. Recommended: mandatory supply chain mapping, worker-voice grievance mechanisms, third-party audits, and contract clause enforcement. Contributed to Executive Order 13627 implementation guidance.",
        "source": "Verite, 2017",
    },
    {
        "type": "case_study",
        "jurisdiction": "IN",
        "title": "Verite — Child Labor and Forced Labor in India's Garment Industry: Tirupur and Bangalore (2019)",
        "summary": "Investigated Sumangali scheme in Tamil Nadu: young women recruited from villages with promise of lump-sum payment (INR 30,000-60,000) after 3-year bonded labor contract. Workers housed in factory dormitories, movement restricted, unable to leave. Similar patterns in Bangalore garment sector supplying international brands. Estimated 250,000 women and girls affected. Recommended brand accountability and worker empowerment programs.",
        "source": "Verite, 2019",
    },
    # ── Anti-Slavery International ──────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Anti-Slavery International — Trafficking for Forced Criminal Activities (2014)",
        "summary": "Documented trafficking of children and adults for forced criminal activities across Europe. Forms: cannabis cultivation (Vietnamese children in UK/Ireland), pickpocketing (Romanian children in France/Italy), ATM theft (Bulgarian nationals). EU Anti-Trafficking Directive non-punishment principle inadequately implemented. Victims prosecuted and jailed rather than identified and assisted. Recommended mandatory non-punishment legislation.",
        "source": "Anti-Slavery International, 2014",
    },
    {
        "type": "case_study",
        "jurisdiction": "MR",
        "title": "Anti-Slavery International — Slavery in Mauritania: Descent-Based Slavery and Modern Persistence (2018)",
        "summary": "Documented continued practice of descent-based slavery (hereditary chattel slavery) in Mauritania despite legal prohibition since 1981 and criminalization in 2007. Estimated 43,000 people (1% of population) in slavery. Haratine (Black Moors) born into slavery serving Beydane (White Moor) families. Government denies existence. Anti-slavery activists imprisoned. Courts rarely convict slaveholders. Only 3 prosecutions under 2007 law by 2018.",
        "source": "Anti-Slavery International, 2018",
    },
    {
        "type": "case_study",
        "jurisdiction": "UK",
        "title": "Anti-Slavery International — 'Forced Labour in the UK': Post-Brexit Vulnerabilities (2021)",
        "summary": "Analyzed how Brexit changed labor exploitation risks in the UK. Loss of EU free movement created new irregular migration. Agricultural sector reliant on seasonal workers from Eastern Europe now faces worker shortages and substitution with less protected visa categories. National Referral Mechanism (NRM) referrals increased 20% (2020-2021). Vietnamese, Albanian, and Eritrean nationals top NRM referrals. Modern Slavery Act transparency provisions lack enforcement.",
        "source": "Anti-Slavery International, 2021",
    },
    {
        "type": "case_study",
        "jurisdiction": "GH",
        "title": "Anti-Slavery International — Child Trafficking in Lake Volta Fishing, Ghana (2019)",
        "summary": "Documented child trafficking from northern Ghana to Lake Volta fishing communities. Children as young as 4 recruited with parental consent after payment of GHC 50-200 (USD 10-40). Children work 14-hour days, dive to untangle nets (drowning risk), malnourished, denied education. Estimated 20,000 children in Lake Volta fishing. Government's National Plan of Action lacks funding. NGO-led rescues face retrafficking risk without economic alternatives for families.",
        "source": "Anti-Slavery International / IJM, 2019",
    },
    {
        "type": "case_study",
        "jurisdiction": "NE",
        "title": "Anti-Slavery International — Wahaya: Domestic and Sexual Slavery in Niger (2020)",
        "summary": "Documented 'wahaya' practice in Niger: women and girls sold as 'fifth wives' (beyond Islamic four-wife limit) to serve as domestic and sexual slaves. Practiced primarily among Tuareg and Arab communities. Women have no legal status as wives, children born to wahaya not recognized. Niger criminalized slavery in 2003 but only 1 conviction by 2020. Estimated 43,000 people in slavery in Niger.",
        "source": "Anti-Slavery International / Timidria, 2020",
    },
    # ── Polaris Project ─────────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "US",
        "title": "Polaris Project — US National Human Trafficking Hotline Data (2007-2023)",
        "summary": "Since 2007, US National Hotline has received 82,000+ substantive contacts, identified 64,000+ trafficking victims and survivors. In 2022: 10,802 contacts, 3,241 trafficking cases reported. Top types: sex trafficking (48%), labor trafficking (28%), combined (24%). Top labor sectors: domestic work, agriculture, restaurants, health/beauty. Top origins of foreign-born victims: Mexico, Honduras, Guatemala, Philippines, India.",
        "source": "Polaris Project, Annual Hotline Data Report 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "Polaris Project — Typology of Modern Slavery: 25 Types Identified in the US (2017)",
        "summary": "Developed typology of 25 distinct types of human trafficking in the United States. Labor trafficking types include: agriculture, domestic work, restaurants, health/beauty, construction, hospitality, manufacturing, carnivals, landscaping, illicit massage. Analysis of 32,000+ cases found trafficking intersects with: immigration fraud, organized crime, legitimate businesses, and online platforms. Recommended sector-specific enforcement strategies.",
        "source": "Polaris Project, 2017",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "Polaris Project — Human Trafficking in Illicit Massage Businesses (2018)",
        "summary": "Investigated network of 9,000+ illicit massage businesses (IMBs) across the US. Women (primarily Chinese and Korean) recruited with promises of legitimate work. Debt bondage of USD 20,000-50,000 for transport and housing. Workers live in businesses, controlled movement, 12-16 hour days, forced into commercial sex. Annual revenue estimated at USD 2.5 billion. Recommended financial investigation approach targeting business owners, not workers.",
        "source": "Polaris Project, 2018",
    },
    # ── La Strada International ─────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "La Strada International — Trafficking in Human Beings in the European Union: Labour Exploitation (2020)",
        "summary": "Analyzed labor trafficking across EU member states. Found: intra-EU trafficking accounts for 42% of cases. Romanian, Bulgarian, and Polish nationals most commonly trafficked within EU. Top sectors: agriculture, construction, domestic work, food processing. Posted Workers Directive creates enforcement gaps as workers move between jurisdictions. Recommended: EU-wide labor authority, cross-border inspection powers, and supply chain due diligence.",
        "source": "La Strada International, 2020",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "La Strada International — Impact of Criminalization of Migration on Trafficking Victims in Europe (2021)",
        "summary": "Documented how immigration enforcement deters trafficking victims from reporting. Found: 60% of identified victims in irregular migration status. Victims deported before accessing support services. Non-punishment principle (EU Anti-Trafficking Directive Art. 8) inconsistently applied. Only 12 EU states have explicit non-punishment provisions. Recommended firewall between immigration enforcement and victim identification.",
        "source": "La Strada International, 2021",
    },
    # ── ECPAT ───────────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "ECPAT — Global Threat Assessment: Sexual Exploitation of Children in Travel and Tourism (2022)",
        "summary": "Assessed sexual exploitation of children by travelers and tourists across 60 countries. Found: offenders increasingly from within the region (not just Western tourists). Online facilitation of child exploitation tourism growing. Southeast Asia, Central America, and East Africa highest risk regions. Recommended: mandatory reporting by travel industry, offender registries with travel restrictions, and technology solutions for detection.",
        "source": "ECPAT International, 2022",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "ECPAT — Online Child Sexual Exploitation: Scale and Trends (2022)",
        "summary": "Estimated 18 million+ unique images/videos of child sexual exploitation material online (NCMEC data). COVID-19 lockdowns increased online child exploitation reports by 106% (2020 vs 2019). Philippines identified as major source of live-streamed child sexual exploitation (US DOJ Operation Rescue). 85% of offending occurs within family or community networks. Recommended: platform liability, end-to-end encryption exceptions for CSAM detection, and survivor-centered responses.",
        "source": "ECPAT International, 2022",
    },
    # ── Migrant Forum in Asia ───────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Migrant Forum in Asia — Policy Brief: Recruitment Fees and Related Costs in Asian Migration Corridors (2020)",
        "summary": "Surveyed 5,000+ migrant workers across 12 Asian corridors. Found average recruitment costs: Bangladesh-Saudi (USD 4,800), Nepal-Qatar (USD 2,100), Philippines-Saudi (USD 1,200), Indonesia-Malaysia (USD 1,500), Myanmar-Thailand (USD 600). Costs exceed 1 month salary in all corridors (ILO benchmark: should be zero). Sub-agents account for 40-60% of total costs. Recommended government-to-government recruitment and digital payment tracking.",
        "source": "Migrant Forum in Asia, 2020",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Migrant Forum in Asia — Wage Theft and Recovery Mechanisms in Asia (2021)",
        "summary": "Analyzed wage theft across 8 destination countries. Found: 25% of Asian migrant workers experience some form of wage theft. Average amount stolen: 2-6 months salary. Recovery rates: below 20% in GCC states, 30-40% in Malaysia, 50-60% in South Korea. Small claims courts inaccessible to migrant workers. Recommended: mandatory wage insurance, bilateral labor agreement enforcement, and employer bonds for worker wages.",
        "source": "Migrant Forum in Asia, 2021",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Migrant Forum in Asia — Digital Rights and Migrant Workers: Technology for Protection or Control? (2022)",
        "summary": "Investigated use of technology in migration governance. Found: digital tools increasingly used for surveillance (employer tracking apps in Gulf), biometric data collection without consent, social media monitoring of workers. Positive examples: IOM MigApp for information, worker voice platforms (Contratados, Recruitment Advisor). Recommended: data protection for migrant workers, digital literacy programs, and prohibition of employer surveillance apps.",
        "source": "Migrant Forum in Asia, 2022",
    },
    # ── Business & Human Rights Resource Centre ─────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "BHRRC — Transition Minerals and Modern Slavery: Cobalt, Mica, and Lithium Supply Chains (2023)",
        "summary": "Investigated forced labor and child labor in mineral extraction. DRC cobalt: 40,000+ child miners (UNICEF estimate). Indian mica: 22,000+ child miners. Argentine/Chilean lithium: indigenous community displacement. Battery supply chains link mines to Apple, Samsung, Tesla, BYD. Recommended mandatory human rights due diligence for mineral supply chains (aligned with EU Battery Regulation 2023 and US Dodd-Frank Section 1502).",
        "source": "Business & Human Rights Resource Centre, 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "BHRRC — Corporate Accountability for Forced Labor in Supply Chains: Legal Tracker (2023)",
        "summary": "Tracked 300+ corporate lawsuits related to forced labor in supply chains (2010-2023). Key cases: Nestle USA v. Doe (US Supreme Court 2021, limited corporate liability for overseas forced labor), Boohoo modern slavery claims (UK), Volkswagen Xinjiang supplier allegations. Trend: increasing legislation (EU CSDDD, German Supply Chain Act, French Duty of Vigilance) shifting corporate responsibility toward mandatory due diligence.",
        "source": "Business & Human Rights Resource Centre, 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "BHRRC — Migrant Worker Abuse in FIFA World Cup and Olympics Mega-Projects (2022)",
        "summary": "Tracked labor rights violations across mega-events: Qatar 2022 (construction worker deaths), Tokyo 2020 (Vietnamese TITP workers), Beijing 2022 (Uyghur supply chain links), Paris 2024 (subcontractor exploitation). Found: mega-event organizers commit to worker welfare but rely on subcontracting chains that obscure accountability. Recommended: binding worker welfare standards, independent monitoring, and compensation funds for all mega-events.",
        "source": "Business & Human Rights Resource Centre, 2022",
    },
    # ── Solidarity Center (AFL-CIO) ────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Solidarity Center — Global Worker Rights in Supply Chains: Labor Trafficking in Garment and Electronics (2020)",
        "summary": "Investigated labor rights violations in garment (Bangladesh, Cambodia, Myanmar, Vietnam) and electronics (Malaysia, China, Philippines) supply chains. Found: freedom of association suppression enables exploitation. Workers who organize face: termination, blacklisting, physical violence, criminal charges. Brands benefit from suppression of collective bargaining which keeps wages low. Recommended: binding supply chain agreements with freedom of association provisions.",
        "source": "Solidarity Center / AFL-CIO, 2020",
    },
    # ── International Justice Mission (IJM) ─────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "IN",
        "title": "IJM — Bonded Labour in India: Brick Kilns and Stone Quarries (2019)",
        "summary": "Assisted in rescue of 3,500+ bonded laborers from Indian brick kilns and quarries (2014-2019). Found: entire families including children held in debt bondage. Debts as small as INR 5,000 (USD 60) trap families for years. Workers paid piece rates below minimum wage with deductions for tools, food, shelter. Dalits and Adivasi communities disproportionately affected. Conviction rate for bonded labor cases: below 5%.",
        "source": "International Justice Mission, 2019",
    },
    {
        "type": "case_study",
        "jurisdiction": "PH",
        "title": "IJM — Online Sexual Exploitation of Children in the Philippines (2020)",
        "summary": "Assisted Philippine authorities in 158 operations (2011-2020), rescuing 1,000+ children from online sexual exploitation. Perpetrators include both foreign buyers and Filipino facilitators (often family members). Average age of victims: 11 years. Payments via international wire transfer and cryptocurrency. Philippines enacted Anti-Online Sexual Abuse and Exploitation of Children Act (RA 11930, 2022). Recommended tech platform cooperation and cross-border law enforcement.",
        "source": "International Justice Mission, 2020",
    },
    # ── Terre des Hommes ────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Terre des Hommes — Sweetie Project: Webcam Child Sex Tourism (2013)",
        "summary": "Created virtual 10-year-old Filipino girl 'Sweetie' as sting operation. Within 10 weeks, 20,000+ adults from 71 countries solicited the virtual child. Identified 1,000 predators. Demonstrated scale of online child exploitation and ease of perpetration. Forced law enforcement agencies worldwide to address online exploitation. Led to legislative changes in Netherlands, Australia, and UK for extraterritorial prosecution.",
        "source": "Terre des Hommes, 2013",
    },
    # ── Global Alliance Against Traffic in Women (GAATW) ────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "GAATW — Beyond Borders: Exploring Links Between Trafficking, Migration, and Development (2018)",
        "summary": "Analyzed intersection of migration policy and trafficking across 12 countries. Found: restrictive immigration policies increase trafficking risk by pushing migration into irregular channels controlled by smugglers/traffickers. Countries with regular migration pathways (e.g., South Korea's EPS) have lower trafficking prevalence. Recommended: expanding legal migration pathways, decriminalizing irregular migration, and separating victim identification from immigration enforcement.",
        "source": "GAATW, 2018",
    },
    # ── Freedom Fund ────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "IN",
        "title": "Freedom Fund — Hotspot Model: Reducing Bonded Labour in South India Granite Quarries (2021)",
        "summary": "Implemented community-based intervention in Tamil Nadu and Karnataka granite quarries. Supported 25,000+ workers and families through: microfinance alternatives to bonded labor loans, children's education, legal aid for debt cancellation, government scheme enrollment. Found: community-level approach reduces bonded labor by 60% within 5 years. Key success factor: engaging local government officials and providing economic alternatives to families.",
        "source": "Freedom Fund, 2021",
    },
    # ── Winrock International ───────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Winrock International — Hamro Samman Project: Reducing Trafficking Vulnerability in Nepal (2017-2023)",
        "summary": "USAID-funded project addressing trafficking of Nepali workers to Gulf states and India. Reached 350,000+ potential migrants with pre-departure information. Established safe migration resource centers in 77 districts. Found: pre-departure orientation reduces exploitation by 40%. Digital information (mobile app, SMS alerts) reaches workers in remote districts. Key challenge: reaching sub-agents who operate informally in villages.",
        "source": "Winrock International / USAID, 2023",
    },
    # ── Oxfam ───────────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Oxfam — 'Ripe for Change': Ending Human Suffering in Supermarket Supply Chains (2018)",
        "summary": "Investigated labor conditions in supermarket supply chains across 12 countries. Found: women earn 2-9 times less than a living wage in shrimp (Thailand), grape (South Africa), and tea (India) supply chains. Supermarkets capture 30-50% of final product price while workers receive 1-5%. Buying practices (last-minute orders, price squeezing) transfer risk to workers. Recommended: living wage commitments, purchasing practice reforms, and supply chain transparency.",
        "source": "Oxfam International, 2018",
    },
    # ── International Trade Union Confederation (ITUC) ──────────────────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "ITUC — Global Rights Index: Worst Countries for Workers (2023)",
        "summary": "Ranked 149 countries on workers' rights violations. Worst countries (rating 5+): Bangladesh, Belarus, Ecuador, Egypt, Eswatini, Guatemala, Myanmar, Philippines, Tunisia, Turkey. Middle East and North Africa worst region. 87% of countries violated collective bargaining rights. 79% violated right to strike. 77 countries restricted freedom of association. Recommended: ILO complaint mechanisms and trade agreement conditionality.",
        "source": "ITUC Global Rights Index, 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "ITUC — 'The Case Against Qatar': FIFA World Cup Campaign (2014-2022)",
        "summary": "Led 8-year campaign for worker rights in Qatar. Documented: 1.7 million migrant workers, kafala system restrictions, heat deaths, wage theft. Campaign achievements: Qatar minimum wage (2021), exit permit abolition (2018), employer change allowed (2020). Remaining concerns: enforcement gaps, non-payment of owed wages, inadequate death investigation. Called on FIFA to establish USD 440M remediation fund. Campaign mobilized trade unions in 50+ countries.",
        "source": "ITUC, 2014-2022",
    },
    # ── Environmental Justice Foundation (EJF) ──────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "TH",
        "title": "EJF — 'All at Sea': The Abuse of Human Rights Aboard Illegal Fishing Vessels (2014-2019)",
        "summary": "Investigated labor conditions on Thai fishing fleet (80,000+ fishing vessels). Found: workers from Myanmar, Cambodia, and Laos trafficked onto boats. Physical abuse including murder at sea. Workers confined for months without shore leave. Vessels operate in international waters beyond national jurisdiction. EU issued Thailand a 'yellow card' (2015) for IUU fishing linked to forced labor. Thailand upgraded fishing regulations (Royal Ordinance 2015) but enforcement remains inadequate.",
        "source": "EJF, 2014-2019",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "EJF — 'Blood and Water': Human Rights Abuse in the Global Seafood Industry (2019)",
        "summary": "Expanded investigation beyond Thailand to global fishing industry. Documented forced labor on vessels from Taiwan, China, South Korea, and Spain operating in international waters. Taiwanese distant-water fleet: migrant workers from Indonesia, Philippines, Vietnam paid USD 250-450/month for 18-22 hour days. Workers at sea for 1-2 years without port calls. Recommended: mandatory vessel monitoring, port state inspections, and ratification of ILO C188.",
        "source": "EJF, 2019",
    },
    # ── Responsible Sourcing Network ────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "UZ",
        "title": "Responsible Sourcing Network — Cotton Campaign: Ending Forced Labor in Uzbek Cotton (2007-2022)",
        "summary": "15-year campaign against state-sponsored forced labor in Uzbekistan's cotton harvest. Government mobilized 1-2 million citizens annually including children, teachers, and medical workers. 300+ brands pledged to boycott Uzbek cotton. ILO Third-Party Monitoring established 2013. Uzbek government ended systematic forced labor by 2021 (ILO-confirmed). Cotton Campaign declared 'mission accomplished' in March 2022. Model for addressing state-imposed forced labor.",
        "source": "Responsible Sourcing Network / Cotton Campaign, 2022",
    },
    # ── KnowTheChain ───────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "KnowTheChain — Benchmark: Forced Labor in ICT, Food & Beverage, and Apparel Sectors (2023)",
        "summary": "Benchmarked 180 companies across three sectors on forced labor due diligence. Average score: 27/100 (ICT), 24/100 (food), 22/100 (apparel). Best performers: HP (84/100, ICT), Unilever (70/100, food), adidas (68/100, apparel). Worst performers average 5/100. Key gaps: worker voice mechanisms (only 15% of companies), recruitment fee reimbursement (only 20%), supply chain transparency beyond Tier 1 (only 10%). Recommended mandatory due diligence legislation.",
        "source": "KnowTheChain / Business & Human Rights Resource Centre, 2023",
    },
    # ── International Labour Organization (ILO) — Research Reports ──────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "ILO — Global Estimates of Modern Slavery: Forced Labour and Forced Marriage (2022)",
        "summary": "Joint ILO-Walk Free-IOM estimate: 49.6 million in modern slavery (2021). Forced labor: 27.6 million (17.3M private economy labor, 6.3M commercial sexual exploitation, 3.9M state-imposed). Forced marriage: 22 million. 12% of forced labor victims are children. 52% in Asia-Pacific. Increase of 10 million from 2016 estimate. Key drivers: governance gaps, migration policy failures, discrimination, economic crises. COVID-19 a significant exacerbating factor.",
        "source": "ILO / Walk Free / IOM, September 2022",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "ILO — Profits and Poverty: The Economics of Forced Labour (2014, updated 2024)",
        "summary": "Estimated forced labor generates USD 236 billion in illegal profits annually (2024 update, up from USD 150 billion in 2014). Breakdown: forced commercial sexual exploitation USD 173 billion, other forced labor USD 63 billion. Profits per victim: forced sexual exploitation USD 27,252/year, domestic work USD 2,441/year, agriculture USD 1,958/year. Forced labor subsidizes global economy through artificially low prices. Recommended: enforcement investment, victim compensation funds.",
        "source": "ILO, 2024",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "ILO — Fair Recruitment Initiative: Global Progress Report (2023)",
        "summary": "Assessed progress toward ILO Fair Recruitment Initiative (launched 2014). By 2023: 40 countries reformed recruitment regulations, 15 countries adopted employer-pays principle, 8 bilateral labor agreements include zero-fee clauses. Challenges: informal sub-agent networks bypass regulations, digital recruitment platforms lack oversight, enforcement capacity insufficient. Recommended: licensing reform, bilateral agreement monitoring, and worker awareness campaigns. Referenced SDG 8.7 and 10.7.",
        "source": "ILO, 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "ILO — Ending Child Labour by 2025: Global Progress and Challenges (2021)",
        "summary": "Found global progress on child labor has stalled. 160 million children in child labor (2020), increase of 8.4 million from 2016. Sub-Saharan Africa: 86.6 million (1 in 4 children). Agriculture: 70% of child labor. COVID-19 reversed 20 years of progress: estimated 9 million additional children at risk. SDG Target 8.7 (end child labor by 2025) will not be met. Recommended: social protection expansion, education access, and supply chain due diligence.",
        "source": "ILO / UNICEF, 2021",
    },
    # ── Transparency International ──────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Transparency International — Corruption and Human Trafficking: The Grease that Turns the Wheels (2020)",
        "summary": "Analyzed corruption as enabler of trafficking. Found: border official bribery facilitates 50% of cross-border trafficking. Police corruption protects traffickers in 70% of documented cases. Judicial corruption leads to case dismissal or minimal sentences. Labour inspectors bribed to overlook violations. Estimated corruption costs: USD 3,000-10,000 per trafficked person (paid to officials along the route). Recommended: anti-corruption integration into anti-trafficking strategies.",
        "source": "Transparency International, 2020",
    },
    # ── Global Fund to End Modern Slavery (GFEMS) ──────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "GFEMS — Prevalence Estimation of Modern Slavery: Methodological Innovations (2023)",
        "summary": "Developed improved measurement tools for modern slavery. Conducted surveys in 15 countries using network scale-up method and multiple systems estimation. Found: official detection captures less than 1% of estimated victims globally. Detection is highest in Europe (3-5%) and lowest in Africa and Asia (0.1-0.5%). Hidden populations (domestic workers, agricultural workers) are most undercounted. Recommended: investment in national statistical capacity for modern slavery measurement.",
        "source": "GFEMS / Delta 8.7, 2023",
    },
    # ── Verisk Maplecroft ───────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Verisk Maplecroft — Modern Slavery Risk Index: Country Rankings (2023)",
        "summary": "Ranked 198 countries on modern slavery risk combining: governance, conflict, discrimination, and economic factors. Extreme risk: North Korea, Libya, Eritrea, Central African Republic, Somalia, South Sudan, DRC, Afghanistan, Yemen, Myanmar. High risk includes: India, China, Russia, Thailand, Malaysia, Saudi Arabia, Qatar, UAE. Low risk: Nordics, Western Europe, Australia, New Zealand. Used by 500+ multinational companies for supply chain risk assessment.",
        "source": "Verisk Maplecroft, 2023",
    },
]
