"""Policy updates, labour reforms, and recent regulatory changes (2020-2026)."""

POLICY_UPDATE_FACTS: list[dict] = [
    {
        "type": "policy_update",
        "jurisdiction": "QA",
        "title": "Qatar Kafala System Abolition — Comprehensive Reform Package",
        "year": 2020,
        "summary": "Law No. 18/2020 (minimum wage QAR 1,000 + allowances) and Law No. 19/2020 (removal of employer NOC for job transfer). Combined with earlier exit permit abolition (2018). Most comprehensive Gulf kafala reform. ILO technical assistance. Workers can change jobs without employer consent after serving notice. Implementation gaps remain: some employers still obstruct transfers, file absconding charges.",
        "source": "Qatar Ministry of Labour / ILO",
    },
    {
        "type": "policy_update",
        "jurisdiction": "SA",
        "title": "Saudi Arabia Labour Reform Initiative (LRI, 2021)",
        "summary": "March 2021 reforms: workers can transfer between employers without sponsor consent (after 1 year or if wages unpaid 3+ months), exit/re-entry visa no longer requires employer approval, exit visa validity extended. Applies to private sector workers (7M+). Domestic workers: limited transferability via Musaned platform. Implementation: MOHRE electronic portal for transfers. Challenges: employer resistance, system delays.",
        "source": "Saudi MOHRE",
        "year": 2021,
    },
    {
        "type": "policy_update",
        "jurisdiction": "PH",
        "title": "Philippines Department of Migrant Workers Creation (RA 11641, 2022)",
        "year": 2022,
        "summary": "Republic Act 11641 created Department of Migrant Workers (DMW) consolidating: POEA (regulatory), OWWA (welfare), NRCO (reintegration). Full department status elevates migrant worker issues to cabinet level. DMW Secretary: cabinet member. Budget: PHP 8.8B (2023). One-stop migrant services centers. Criticism: bureaucratic merger challenges, some POEA functions weakened during transition.",
        "source": "Philippine Congress / DMW",
    },
    {
        "type": "policy_update",
        "jurisdiction": "MY",
        "title": "Malaysia Anti-Trafficking Amendments (ATIPSOM, 2022)",
        "year": 2022,
        "summary": "Amendments to Anti-Trafficking in Persons and Anti-Smuggling of Migrants Act (ATIPSOM): increased penalties, expanded victim protection, mandatory victim screening for arrested undocumented workers, non-punishment principle for victims. Aims to address US TIP Report Tier 3 downgrade (2021). Implementation: training for enforcement officers, inter-agency committee. Effectiveness: limited prosecutions despite amendments.",
        "source": "Malaysia Ministry of Home Affairs / US TIP Report",
    },
    {
        "type": "policy_update",
        "jurisdiction": "AE",
        "title": "UAE Labour Market Reforms (2022-2023)",
        "year": 2022,
        "summary": "Package of reforms: 6-month grace period after contract termination to find new employer, freelance visa (self-sponsorship), golden visa for skilled workers (10-year residency), minimum 30 days annual leave for all workers, new anti-discrimination provisions in Federal Decree-Law 33/2021. Domestic workers: standard contract (2017) updated with rest hour provisions. Enforcement: MOHRE smart inspection system.",
        "source": "UAE MOHRE / Federal Authority for Identity",
    },
    {
        "type": "policy_update",
        "jurisdiction": "ID",
        "title": "Indonesia BNP2MI Zero-Cost Migration Policy (2020)",
        "year": 2020,
        "summary": "BNP2MI (National Agency for the Placement and Protection of Indonesian Migrant Workers) mandated zero-cost placement: all recruitment fees to be paid by employer or government. Replaced BP2MI. Implementation: government-to-government placement for key corridors. Challenges: enforcement limited, private agencies continue charging, workers paying via third-party 'training' fees. Applies to formal channel only.",
        "source": "BNP2MI / Indonesia MoMP",
    },
    {
        "type": "policy_update",
        "jurisdiction": "JP",
        "title": "Japan TITP Replacement — New Training and Employment System (2024+)",
        "year": 2024,
        "summary": "Japan abolishing TITP (criticized for exploitation since 1993) and creating new 'Training and Employment' system. Key changes: workers can change employers after 1-2 years (was impossible under TITP), path to SSW status, reduced broker fees, Japanese language support. Implementation: phased from 2024. Affected workers: 350,000+ current TITP trainees. Critics: reforms insufficient, transition period creates confusion.",
        "source": "Japan Ministry of Justice / JITCO",
    },
    {
        "type": "policy_update",
        "jurisdiction": "EU",
        "title": "EU Corporate Sustainability Due Diligence Directive (CSDDD, 2024)",
        "year": 2024,
        "summary": "Requires large companies to identify, prevent, mitigate adverse human rights impacts (including forced labour) throughout value chains. Applies to: EU companies with 1,000+ employees and EUR 450M+ turnover. Non-EU companies: EUR 450M+ EU turnover. Civil liability for failures. Member states transpose by 2026. Covers forced labour, child labour, trafficking in supply chains. Strongest EU human rights due diligence legislation.",
        "source": "European Commission / European Parliament",
    },
    {
        "type": "policy_update",
        "jurisdiction": "US",
        "title": "US Uyghur Forced Labor Prevention Act Implementation (2022+)",
        "year": 2022,
        "summary": "UFLPA enforcement began June 2022. Rebuttable presumption: goods from Xinjiang made with forced labour unless importer proves otherwise with 'clear and convincing evidence.' DHS Forced Labor Enforcement Task Force coordinates. Blocked USD 2B+ in goods (2022-2024): cotton, apparel, polysilicon, tomatoes, PVC. Entity List: 60+ companies. Importers must provide complete supply chain mapping to challenge presumption.",
        "source": "US DHS / CBP",
    },
    {
        "type": "policy_update",
        "jurisdiction": "KR",
        "title": "South Korea EPS Expansion and Reforms (2022-2024)",
        "year": 2022,
        "summary": "EPS quota increased: 69,000 (2022) → 110,000 (2023) to address labour shortages. New sending countries added. Seasonal Worker Program launched (E-8 visa). Workplace change: expanded grounds for transfer. Agriculture sector improvements: mandatory housing standards. Fisheries sector: ILO C188 implementation. Criticized for: insufficient quota to meet demand (pushing irregular migration), no permanent residency path.",
        "source": "Korea HRD Service / Korea Ministry of Employment and Labour",
    },
    {
        "type": "policy_update",
        "jurisdiction": "TH",
        "title": "Thailand Fishing Industry Reforms — Post-IUU Card (2015-2023)",
        "year": 2015,
        "summary": "EU yellow card (2015) triggered: Command Centre for Combating Illegal Fishing (CCCIF), vessel monitoring system (VMS) for all commercial vessels, port-in-port-out (PIPO) inspections, crew registration database. Yellow card lifted 2019. Ongoing: Royal Ordinance on Fisheries (2015, amended), labour protection for fishing workers, MOU-based recruitment from Myanmar and Cambodia. Challenges: continued exploitation in small-scale fisheries, pre-processing sector less monitored.",
        "source": "Thailand Department of Fisheries / EU DG MARE / EJF",
    },
    {
        "type": "policy_update",
        "jurisdiction": "AU",
        "title": "Australia Modern Slavery Act Review and Strengthening (2023+)",
        "year": 2023,
        "summary": "Independent review of Australian MSA (2018) by Professor John McMillan. Key recommendations: mandatory due diligence requirements, penalties for non-compliance (currently none), anti-slavery commissioner, high-risk sector focus. Government response: commitment to establish Anti-Slavery Commissioner (2024). Current: 7,000+ reporting entities, varied quality of statements. Threshold: AUD 100M consolidated revenue.",
        "source": "Australian Government / Walk Free",
    },
    {
        "type": "policy_update",
        "jurisdiction": "KW",
        "title": "Kuwait Domestic Workers Shelter and Protection (2022+)",
        "year": 2022,
        "summary": "Kuwait established government-run shelter for abused domestic workers (2022). Capacity: 500 workers. Services: temporary housing, legal assistance, medical care, repatriation support. Workers can access shelter after filing complaint with PAM or police. Previously: workers relied on embassy shelters (overcrowded). Criticism: shelter sometimes used to detain workers awaiting deportation rather than provide protection.",
        "source": "Kuwait Public Authority of Manpower",
    },
    {
        "type": "policy_update",
        "jurisdiction": "BH",
        "title": "Bahrain Flexi-Permit Expansion and LMRA Reforms",
        "year": 2017,
        "summary": "Bahrain flexi-permit allows migrant workers to self-sponsor: BHD 300/year (USD 795). Workers can work for any employer, change jobs freely. 70,000+ workers on flexi-permits (2023). LMRA reforms: electronic complaint system, automated WPS monitoring, employer rating system. Most progressive Gulf reform but criticized: workers bear all costs, no employer-provided benefits, two-tier labour market.",
        "source": "Bahrain LMRA",
    },
    {
        "type": "policy_update",
        "jurisdiction": "JO",
        "title": "Jordan Unified Contract for Domestic Workers (2022 Update)",
        "year": 2022,
        "summary": "Jordan updated unified standard contract for domestic workers: 10-hour workday (was unregulated), weekly rest day, 14 days annual leave, minimum wage JOD 150/month (USD 210). Contract in Arabic + worker's language. Registration at Ministry of Labour mandatory. Enforcement: labour inspectors can enter homes (with limitations). 50,000+ domestic workers (Filipino, Sri Lankan, Bangladeshi). Implementation patchy.",
        "source": "Jordan Ministry of Labour / Tamkeen",
    },
    {
        "type": "policy_update",
        "jurisdiction": "PH",
        "title": "Philippines POGO Ban (2024)",
        "year": 2024,
        "summary": "President Marcos ordered complete ban on Philippine Offshore Gaming Operators (POGOs) by end of 2024. Triggered by: raid on Bamban compound (trafficking, scam operations, mayor complicity), Porac compound (kidnapping, torture), Senate investigations revealing systematic trafficking. PAGCOR to cancel all licenses. Affected: 400+ POGO operations, 40,000+ Chinese workers (many trafficked), 10,000+ Filipino workers. Operations relocating to Cambodia, Myanmar, Laos.",
        "source": "Philippine Senate / PAGCOR / Philippine National Police",
    },
    {
        "type": "policy_update",
        "jurisdiction": "EU",
        "title": "EU Forced Labour Product Ban Regulation (2024)",
        "year": 2024,
        "summary": "EU regulation prohibiting products made with forced labour (including child labour) from being placed on EU market. Covers domestic production and imports. Risk-based enforcement: competent authorities prioritize investigations based on geographic and sectoral risk indicators. Products can be detained at borders. Companies can be required to withdraw products. Builds on US Section 307 model but with broader scope.",
        "source": "European Commission / European Parliament",
    },
]
