"""Recruitment violation patterns and documented enforcement cases."""

RECRUITMENT_FACTS: list[dict] = [
    {
        "type": "recruitment_violation",
        "jurisdiction": "PH",
        "title": "Sub-Agent Overcharging in Manila Recruitment Pipeline",
        "violation_type": "excessive_fees",
        "corridor": "PH-SA",
        "summary": "Sub-agents charge PHP 80,000-150,000 for Saudi domestic worker placements despite zero-fee policy. Fees disguised as 'training,' 'medical,' and 'processing' costs. DMW enforcement limited to licensed agencies; sub-agents operate informally.",
        "source": "DMW enforcement reports",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "PH",
        "title": "Fake Job Order Schemes — Philippines",
        "violation_type": "fraud",
        "corridor": "PH-AE",
        "summary": "Unlicensed agencies create fake employer demand letters and job orders. Workers pay PHP 50,000-200,000. Arrive at destination to find no employer or different job. DMW blacklists agencies but new ones emerge quickly.",
        "source": "DMW / NBI Anti-Human Trafficking Division",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "BD",
        "title": "Dalal Networks in Bangladeshi Recruitment",
        "violation_type": "unlicensed_recruitment",
        "corridor": "BD-SA",
        "summary": "Informal brokers (dalals) operate in rural areas, charging BDT 300,000-600,000 for Gulf placements. Chain: dalal → sub-agent → licensed agency. Each layer adds fees. BMET unable to regulate sub-agent networks.",
        "source": "BMET / ILO Dhaka",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "NP",
        "title": "Document Falsification by Nepali Agencies",
        "violation_type": "document_fraud",
        "corridor": "NP-QA",
        "summary": "Agencies falsify medical certificates, skills assessments, and age documents. Workers sent abroad with inflated qualifications. Discovered at destination: reassigned to lower-paying work. Agency faces no consequences.",
        "source": "Nepal Foreign Employment Board / Pourakhi",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Bait-and-Switch Employer Assignments",
        "violation_type": "contract_substitution",
        "summary": "Worker signs contract for Employer A at good salary. Upon arrival, transferred to Employer B at lower salary and worse conditions. Original contract used only for visa processing. Pervasive in SA, QA, AE corridors.",
        "source": "ILO / Migrant Forum in Asia",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "ID",
        "title": "Indonesian Training Centre Exploitation",
        "violation_type": "excessive_fees",
        "corridor": "ID-SG",
        "summary": "Mandatory pre-departure training centres in Batam, Bekasi, and Surabaya charge IDR 15-25 million. Workers held for 3-6 months. Training quality minimal. Fees deducted from first 8-10 months' salary. BNP2MI crackdown ongoing.",
        "source": "BNP2MI / HOME Singapore",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Forced Salary Kickbacks to Recruitment Agencies",
        "violation_type": "wage_theft",
        "summary": "Workers forced to pay 20-50% of first 6-12 months' salary to agency as 'post-placement service fee'. Deducted directly or via employer arrangement. Violation of ILO C181 zero-fee principle. Common in PH, ID, BD corridors.",
        "source": "ILO / Fair Recruitment Initiative",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "BD",
        "title": "Pre-Departure Loan Schemes at Usurious Rates",
        "violation_type": "debt_bondage",
        "corridor": "BD-MY",
        "summary": "Workers take loans from agencies or money lenders at 30-60% annual interest to pay recruitment fees. Collateral: family land or house. Default leads to asset seizure. Creates debt bondage before departure.",
        "source": "BRAC / IOM Dhaka",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Social Media Recruitment Scams (Facebook/TikTok)",
        "violation_type": "fraud",
        "summary": "Recruiters use Facebook groups, TikTok, and WhatsApp to advertise high-paying jobs. Fake testimonials. Victims pay deposits for non-existent jobs. Difficult to trace or prosecute across borders. PH, NP, KH most targeted.",
        "source": "UNODC / IOM",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "PH",
        "title": "Reprocessing Fee Extortion for Contract Renewals",
        "violation_type": "excessive_fees",
        "corridor": "PH-HK",
        "summary": "Agencies charge PHP 30,000-60,000 for contract renewal processing that should be free. Workers unable to refuse: losing renewal means losing income. HK agencies may separately charge prohibited fees.",
        "source": "Mission for Migrant Workers / POLO Hong Kong",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "PH",
        "title": "Agency Closure and Fund Disappearance",
        "violation_type": "fraud",
        "summary": "Pattern: agency collects fees from 50-200 workers, then closes before deployment. Owners reopen under new name. DMW escrow fund (PHP 1M) insufficient to refund all workers. Criminal prosecution rare.",
        "source": "DMW Anti-Illegal Recruitment Branch",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "MM",
        "title": "Cross-Border Broker Networks — Myanmar to Thailand",
        "violation_type": "unlicensed_recruitment",
        "corridor": "MM-TH",
        "summary": "Informal broker networks operate along Myanmar-Thailand border (Myawaddy-Mae Sot, Ranong-Kawthaung). Workers pay THB 15,000-40,000 for border crossing and job placement. No contracts, no protections. Fishing and agriculture sectors.",
        "source": "Migrant Working Group Thailand / ILO",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "KH",
        "title": "Cambodian Workers Deceived into Online Scam Operations",
        "violation_type": "fraud",
        "corridor": "KH-KH",
        "summary": "Workers recruited for 'call centre' or 'tech' jobs in Sihanoukville/Phnom Penh casinos. Actually forced into online fraud/scam operations. Passports taken, physical violence for low performance. Rescued by police raids.",
        "source": "UNODC / Cambodian National Police / ABC News",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "VN",
        "title": "Vietnamese Sending Organization Fee Overcharging — Japan TITP",
        "violation_type": "excessive_fees",
        "corridor": "VN-JP",
        "summary": "Vietnamese sending organizations charge USD 5,000-10,000 for TITP placements despite DOLAB cap of USD 3,600. Excess disguised as 'Japanese language training' and 'document processing'. DOLAB enforcement inconsistent.",
        "source": "DOLAB / OTIT Japan / ILO Hanoi",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "NP",
        "title": "Manpower Agency Collusion with Destination Employers",
        "violation_type": "contract_substitution",
        "corridor": "NP-SA",
        "summary": "Nepali agencies collude with Saudi employers: worker recruited for factory job at SAR 2,000/month, deployed to construction at SAR 1,000. Agency and employer split the difference. Worker has no recourse.",
        "source": "Nepal Foreign Employment Board",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "ET",
        "title": "Ethiopian Workers Trafficked Through Djibouti-Yemen Route",
        "violation_type": "trafficking",
        "corridor": "ET-SA",
        "summary": "Workers travel overland to Djibouti, by boat to Yemen, then walk to Saudi border. Smugglers charge USD 600-1,500. Violence, starvation, and sexual assault en route. Arrive in Saudi as undocumented workers with no protections.",
        "source": "IOM / UNHCR / Mixed Migration Centre",
    },
    # ── Additional Recruitment Violations (expanded) ─────────────────
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Licensed vs Unlicensed Agency Enforcement Gap",
        "violation_type": "regulatory_failure",
        "summary": "Licensing systems exist in all major origin countries (PH DMW, BD BMET, NP DFE, ID BNP2MI) but enforcement is weak. For every licensed agency: estimated 2-5 unlicensed sub-agents. Annual license revocations: PH ~50-100, BD ~20-30, NP ~10-20, ID ~10-15. Penalties insufficient to deter. Sub-agents operate through personal networks in rural areas, unreachable by regulators.",
        "source": "ILO / National regulatory agencies",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Recruiter Blacklists — Limited Effectiveness",
        "violation_type": "regulatory_failure",
        "summary": "Origin countries maintain blacklists of sanctioned agencies (PH: DMW suspended list, BD: BMET revocation list). Limitations: blacklisted operators reopen under new names, sub-agents are not tracked, cross-border coordination absent (agency blacklisted in PH can recruit for same employer via BD agency). Workers rarely check blacklist before engaging agent. Digital verification systems exist but adoption low.",
        "source": "ILO / Migrant Forum in Asia",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "KR",
        "title": "South Korea EPS — Government-to-Government Model",
        "violation_type": "good_practice",
        "summary": "Korea EPS eliminates private recruitment: government agencies in origin countries manage applications, testing, and deployment. Total cost: USD 900-1,000 (lowest among major corridors). No private brokers, no sub-agents. Korean language test (EPS-TOPIK) as selection mechanism. 16 sending countries. Annual quota: 110,000 (2023). Criticism: limited workplace mobility, no permanent residency. Still widely regarded as international best practice.",
        "source": "Korea HRD Service / ILO / World Bank",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "IOM IRIS Ethical Recruitment Certification",
        "violation_type": "good_practice",
        "summary": "IOM International Recruitment Integrity System (IRIS): voluntary standard for ethical recruitment agencies. Principles: zero fees to workers, transparent contracts, informed consent, grievance mechanisms. 60+ agencies engaged, handful fully certified. Limitation: voluntary, covers minority of recruitment market, no enforcement for non-certified. Used by some multinational companies as supplier selection criteria.",
        "source": "IOM IRIS",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Dhaka Principles and Leadership Group for Responsible Recruitment",
        "violation_type": "good_practice",
        "summary": "Leadership Group for Responsible Recruitment: coalition of major brands (HP, Coca-Cola, IKEA, Unilever, etc.) committed to 'employer pays' principle. Dhaka Principles (IHRB): 10 principles for migration with dignity. Brands require suppliers to reimburse worker-paid fees. Impact: USD 30M+ reimbursed to workers since 2017. Gap: covers <5% of global recruitment market.",
        "source": "IHRB / Leadership Group / KnowTheChain",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Agency Bond and Escrow Requirements — Effectiveness",
        "violation_type": "regulatory_failure",
        "summary": "Origin countries require agencies to post bonds: PH PHP 1M (~USD 17,000), BD BDT 1M (~USD 9,100), NP NPR 3M (~USD 22,500). Intended as guarantee fund for defrauded workers. Limitations: bond amount insufficient to cover 50-200 defrauded workers, bond recovery process takes years, agencies forfeit bond and reopen under new name. Effective bond would need to be 10-20x current levels.",
        "source": "ILO / National regulatory agencies",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Digital Recruitment Platform Risks — Job Portals",
        "violation_type": "fraud",
        "summary": "Online job portals (Bayt.com, GulfTalent, Facebook groups) used by both legitimate and fraudulent recruiters. Fake job listings with established company names. Workers pay 'processing fees' for non-existent positions. Platform liability unclear. ILO-IOM guidelines for responsible online recruitment exist but adoption minimal. AI-generated fake company websites increasing.",
        "source": "ILO / IOM / UNODC",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Returning Worker Re-Recruitment Exploitation",
        "violation_type": "excessive_fees",
        "summary": "Workers returning to same destination/employer charged new recruitment fees by agencies. Agencies argue: 'new contract requires new processing.' Workers pay 50-100% of original fees for contract renewal. Some employers collude: terminate worker at contract end, worker must go through agency again (with new fees) for same job. Creates recurring debt cycles. Philippine DMW policy: no fees for contract renewal; widely violated.",
        "source": "DMW / ILO / Migrant Forum in Asia",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Recruitment Industry Size and Revenue",
        "violation_type": "systemic",
        "summary": "Global private recruitment industry worth USD 20B+ annually. ILO estimates workers pay USD 8-12B in recruitment fees annually. Revenue per worker: agencies earn USD 500-3,000 per placement. Sub-agent networks earn additional USD 500-5,000. In corridors with high fees (VN-JP, BD-SA), recruitment revenue exceeds worker's first-year earnings. Industry lobbies against zero-fee regulations.",
        "source": "ILO / World Employment Confederation",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "PH",
        "title": "Philippine Medical Tourism Recruitment Scam",
        "violation_type": "fraud",
        "corridor": "PH-international",
        "summary": "Fake agencies advertise nursing/caregiver positions in US, UK, Canada, Australia. Workers pay PHP 200,000-500,000 for visa processing, credential evaluation, and English testing. Visas never materialize; agencies close. Some workers sent to incorrect destinations or different job categories. POEA/DMW delisting insufficient as operators reopen. Pattern recurring since 2000s.",
        "source": "DMW / Philippine Nurses Association",
    },
    {
        "type": "recruitment_violation",
        "jurisdiction": "international",
        "title": "Wage Advance from Recruiter as Debt Trap",
        "violation_type": "debt_bondage",
        "summary": "Recruiters offer 'advance' on first month salary to seal deal with hesitant workers. Advance treated as high-interest loan. Worker arrives at destination already in debt to recruiter AND employer. Double debt servicing from single salary. Common in BD-SA, NP-QA corridors. Advances sometimes disbursed to worker's family (emotional pressure to repay). No written loan terms.",
        "source": "ILO / BRAC / Pourakhi",
    },
]
