"""Remedy and compensation mechanisms — worker redress, compensation funds, and access to justice."""

REMEDIATION_COMPENSATION_FACTS: list[dict] = [
    # ── International Frameworks ────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Guiding Principles on Business and Human Rights — Pillar 3 (Remedy)",
        "summary": "UNGPs Pillar 3 requires effective remedy for victims of business-related human rights abuses. State duty to provide access to judicial and non-judicial mechanisms. Corporate responsibility to establish operational-level grievance mechanisms. Effectiveness criteria: legitimate, accessible, predictable, equitable, transparent, rights-compatible. Most migrant worker grievance mechanisms fail on accessibility and equity criteria.",
        "source": "UN OHCHR / UNGPs (2011)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Protocol P029 — Right to Compensation for Forced Labour Victims",
        "summary": "ILO Protocol of 2014 (P029) to the Forced Labour Convention requires states to: ensure victims have access to compensation regardless of presence or legal status in country, provide legal assistance, enable victims to seek remedies from perpetrators, establish compensation funds or mechanisms. 63 ratifications as of 2024. Key innovation: legal status cannot be used to deny remedy.",
        "source": "ILO NORMLEX / 50 for Freedom Campaign",
    },
    # ── National Compensation Mechanisms ─────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "US",
        "title": "US Trafficking Victims Protection Act — Restitution Provisions",
        "summary": "TVPA (2000, reauthorised 2022) mandates restitution to trafficking victims from convicted traffickers. Victims can also pursue civil claims under 18 USC § 1595 for actual damages, punitive damages, and attorneys' fees. Mandatory restitution: back wages, value of labour, medical costs. Average civil settlement: USD 1-5M. Challenge: many traffickers are judgment-proof (unable to pay).",
        "source": "US DOJ / Polaris Project",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US — Signal International Case (Record Trafficking Judgment)",
        "sector": "construction",
        "exploitation_type": "debt_bondage",
        "summary": "Signal International recruited 500+ Indian workers for Gulf Coast shipyard repair after Hurricane Katrina (2006). Workers paid USD 10,000-20,000 recruitment fees, promised green cards. Confined to guarded labour camps, passports confiscated. SPLC filed suit. Jury awarded USD 14M in damages (2015). Signal International bankrupted. Federal criminal conviction of recruiter. Case set precedent for H-2B trafficking liability.",
        "source": "Southern Poverty Law Center / US DOJ",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "UK",
        "title": "UK — Modern Slavery Compensation Orders",
        "summary": "UK Modern Slavery Act (2015) Section 8 enables courts to make slavery and trafficking reparation orders against convicted offenders. Victims can apply through Criminal Injuries Compensation Authority (CICA) for up to GBP 44,000. National Referral Mechanism (NRM) provides 45-day recovery period with accommodation and support. Challenges: low conviction rates (only 119 convictions in 2022), CICA awards modest, immigration enforcement during NRM.",
        "source": "UK Home Office / Modern Slavery and Human Rights Policy Centre",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "QA",
        "title": "Qatar — Workers' Support and Insurance Fund",
        "summary": "Qatar established Workers' Support and Insurance Fund (2019) to compensate workers for unpaid wages when employer defaults. Fund disburses within 1 month of verified claim. QAR 358M disbursed to 36,000 workers (2019-2022). Covers: unpaid wages (up to 3 months), end-of-service benefits, work injury compensation. Funded by government. First of its kind in Gulf states. Gap: does not cover informal sector or undocumented workers.",
        "source": "Qatar Ministry of Labour / ILO Qatar",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Qatar — Labour Dispute Resolution Committees",
        "exploitation_type": "abuse_of_vulnerability",
        "summary": "Qatar established Labour Dispute Resolution Committees (2018) for expedited wage claims. Committees process cases within 3-6 weeks (vs. 6-12 months in courts). Workers can file complaints without employer consent. 35,000+ cases resolved (2018-2023), QAR 800M+ in awards. Challenges: workers deported before resolution, language barriers, no legal aid for complex cases, committee decisions not always enforced against employers.",
        "source": "ILO Qatar / Qatar Ministry of Labour",
    },
    # ── Corporate Remediation ───────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Apple — Largest Corporate Recruitment Fee Repayment (USD 32.4M)",
        "sector": "manufacturing",
        "exploitation_type": "debt_bondage",
        "summary": "Apple's Supplier Code of Conduct requires zero-fee recruitment. Since 2008, Apple has required suppliers to repay USD 32.4M in excessive recruitment fees to 36,599 workers across 20+ countries. Largest single repayment: USD 3.9M by supplier in Malaysia. Process: Apple audits identify overcharges, supplier required to repay within 90 days or lose Apple business. Demonstrates corporate leverage can drive remediation at scale.",
        "source": "Apple Supplier Responsibility Report (2023)",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "Top Glove — USD 33M Remediation After WRO",
        "sector": "manufacturing",
        "exploitation_type": "debt_bondage",
        "summary": "Top Glove Corporation (Malaysia) paid USD 33M in remediation payments to 13,000+ migrant workers after US CBP Withhold Release Order (2021). Payments covered: recruitment fee reimbursement, back wages, improved accommodation. WRO lifted Sep 2021 after verification. Demonstrates trade sanctions as effective remedy catalyst. Workers received average USD 2,500 each. Company restructured recruitment process to employer-pays model.",
        "source": "US CBP / Top Glove Annual Report / Reuters",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Barriers to Worker Remedy — Structural Obstacles",
        "summary": "Key barriers to remedy for migrant workers: (1) deportation before claim resolution, (2) employer files counter-complaint (absconding/theft), (3) lack of legal aid in destination language, (4) burden of proof on worker, (5) small claims not economically viable to litigate, (6) employer bankruptcy shields assets, (7) cross-border enforcement of judgments impossible, (8) bilateral agreements lack remedy provisions. ILO estimates less than 5% of forced labour victims access any remedy.",
        "source": "ILO / FairSquare Projects / La Strada International",
    },
    # ── Access to Justice ───────────────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Firewall Between Labour Exploitation Reporting and Immigration Enforcement",
        "summary": "Critical remedy gap: in most countries, migrant workers who report exploitation risk immigration enforcement (detention, deportation). 'Firewall' principle: immigration enforcement should be separated from labour rights enforcement. Implemented in: US (T-visa for trafficking victims), Canada (open work permit for abused workers), Thailand (reflection period). Not implemented in: GCC states, Malaysia, Singapore (where reporting exploitation can trigger deportation).",
        "source": "PICUM / ILO / IOM",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "US",
        "title": "US T-Visa — Immigration Relief for Trafficking Victims",
        "summary": "US T-visa (created by TVPA 2000) provides trafficking victims: temporary immigration status, work authorisation, access to public benefits, and path to permanent residency. Annual cap: 5,000 visas (never reached — average 1,500 issued/year). Requirements: present in US, compliance with law enforcement investigation. Challenge: victims must cooperate with prosecution, which deters reporting if trafficker is also from victim's community.",
        "source": "US DOJ / USCIS / Polaris Project",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Singapore — Temporary Job Flexibility Scheme for Exploitation Victims",
        "exploitation_type": "abuse_of_vulnerability",
        "summary": "Singapore MOM's Temporary Job Flexibility Scheme (TJFS) allows migrant workers with pending employment claims or police reports to seek temporary employment while case is resolved. Prevents destitution during proceedings. Criticism: scheme poorly publicised, processing delays (3-6 months), workers must prove 'salary grievance' (narrow definition), does not cover all exploitation types. Alternative: Special Pass (restricted to case duration, no work authorisation).",
        "source": "Singapore MOM / HOME / TWC2",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Remedy Gap — Forced Labour Victims Accessing Compensation",
        "metric": "remedy_access_rate",
        "value": "less than 5%",
        "summary": "ILO estimates fewer than 5% of forced labour victims worldwide access any form of compensation or remedy. Of those who access judicial proceedings, average case duration: 2-4 years. Compensation amounts: typically 20-40% of wages owed. Worker attrition (returning home before case concludes): 60-70%. Cross-border enforcement of judgments: near zero outside EU/US mutual legal assistance frameworks.",
        "source": "ILO / La Strada International / Anti-Slavery International",
    },
    # ── Innovative Mechanisms ───────────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Migrant Worker Insurance Schemes — Emerging Models",
        "summary": "Emerging insurance-based remedy: Philippines OWWA (death/disability benefits), Nepal Foreign Employment Insurance (mandatory), Sri Lanka SLBFE welfare fund, Bangladesh Wage Earners' Welfare Fund. Combined coverage: 5M+ workers. Limitations: modest payouts (USD 3,000-10,000 death benefit), complex claims process, undocumented workers excluded. ILO recommends mandatory employer-funded insurance in bilateral agreements.",
        "source": "ILO / IOM / World Bank",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "National Rapporteur Mechanisms and Remedy Coordination",
        "summary": "21 countries have established National Rapporteurs on Trafficking (as recommended by Palermo Protocol). Rapporteurs coordinate identification, referral, and remedy access. Netherlands model (2000): independent rapporteur reports to parliament, monitors compensation, tracks remedy outcomes. Most effective: Netherlands, Finland, Sweden. Challenge: many rapporteurs lack enforcement power, under-resourced, focus on criminal justice rather than labour exploitation.",
        "source": "OSCE / European Commission / GRETA",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Australia — National Compensation Scheme for Trafficking Victims",
        "exploitation_type": "multiple",
        "summary": "Australia's Support for Trafficked People Program (STPP) provides: 45-day reflection period (extendable to 90 days), accommodation, living allowance, legal aid, interpreting services. Victims on Criminal Justice Stay Visa can work. Victims of Crime Compensation: varies by state (AUD 10,000-100,000). Federal court civil claims possible under Criminal Code Act. Anti-Slavery Commissioner (est. 2023) to coordinate national response. 300+ referrals per year.",
        "source": "Australian Federal Police / Anti-Slavery Commissioner / Red Cross Australia",
    },
]
