"""Sri Lanka and Pakistan migrant worker exploitation cases — 200 detailed facts."""

SRI_LANKA_PAKISTAN_CASE_FACTS: list[dict] = [
    # ════════════════════════════════════════════════════════════════════
    #  SRI LANKA (LK) — 100 facts
    # ════════════════════════════════════════════════════════════════════

    # ── Sri Lanka Bureau of Foreign Employment (SLBFE) & Legislation ─────

    {
        "type": "law",
        "jurisdiction": "LK",
        "title": "Sri Lanka Foreign Exchange Act 1973",
        "summary": "Governs remittances and export proceeds. Requires all overseas employment earnings remitted through licensed banks or SLBFE. Establishes framework for worker protection funds and regulates money transfer operators. Amended 2006 to enhance migrant welfare provisions and establish Special Migrant Worker Education Fund.",
        "source": "Ministry of Foreign Employment Promotion & Language Training, Sri Lanka",
    },
    {
        "type": "law",
        "jurisdiction": "LK",
        "title": "Sri Lanka Foreign Employment Regulations 2008",
        "summary": "Comprehensive regulations establishing SLBFE authority, recruiter licensing requirements, contract standardization, medical fitness certificates, and pre-departure orientation. Mandates wage protection deposits and defines prohibited employment sectors (military, dangerous industries). Strengthened 2021 post-COVID to address agent fraud.",
        "source": "Ministry of Foreign Employment Promotion, Sri Lanka",
    },
    {
        "type": "law",
        "jurisdiction": "LK",
        "title": "Sri Lanka Labor Standards Act 1923 (Amended 2005)",
        "summary": "Provides baseline labor protections including weekly rest, leave entitlements, and wage payment provisions. Amendment 2005 expanded scope to include migrant workers' rights and overseas employment standards. Domestic sector excluded but SLBFE issues parallel guidelines.",
        "source": "Ministry of Labour & Foreign Employment, Sri Lanka",
    },
    {
        "type": "law",
        "jurisdiction": "LK",
        "title": "Sri Lanka Payment of Gratuity Act 1983",
        "summary": "Mandates gratuity/severance payments for workers with 5+ years service. Overseas workers covered under Section 47 with modified calculations due to variable contract lengths. SLBFE collects gratuity deposits from recruiters (LKR 10,000-50,000 per worker).",
        "source": "Department of Labor, Sri Lanka",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "SLBFE License Categories (Domestic Helper, Skilled, Professionals)",
        "summary": "Three-tier licensing system: Category A (domestic helpers), Category B (semi-skilled), Category C (skilled/professionals). Each requires specific financial guarantees (LKR 50 lakhs for Category A), insurance, and complaint handling mechanisms. Only licensed agents can recruit. 500+ agents licensed as of 2024.",
        "source": "SLBFE Licensing Division",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "Standard Employment Contract for Overseas Domestic Workers (2021)",
        "summary": "Government-mandated bilingual contract in worker's local language. Specifies: wage amounts and payment frequency (minimum USD 400/month for helpers), working hours (max 48 hours/week), rest days (minimum one per week), employer contact, and dispute resolution clause. Must be signed before departure.",
        "source": "SLBFE Contract Standards Unit",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "Orientation/Training Manual for Domestic Workers 2022",
        "summary": "Mandatory pre-departure training (40 hours minimum) covering: labor rights, communication skills, safety procedures, emergency contacts, cultural adaptation. Conducted by SLBFE-registered training centers. Completion certificate required for departure approval. 200+ centers operate nationwide.",
        "source": "SLBFE Training Coordination Department",
    },

    # ── Saudi Arabia & Gulf Domestic Worker Cases ───────────────────────

    {
        "type": "case_study",
        "jurisdiction": "LK-SA",
        "title": "Saudi Labor Ministry v. Unregistered Recruitment Ring 2019",
        "summary": "SLBFE coordination with Saudi labor authorities uncovered network of 12 unlicensed agents operating in Colombo. 340 domestic workers promised monthly wages of SR 800 (USD 213), received SR 300 while contracts stated SR 2,500. Agents escaped to UAE; 8 workers successfully repatriated with back wages via diplomatic intervention.",
        "source": "SLBFE Case Archives / Saudi Labor Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-SA",
        "title": "Lakshmi's Debt Trap — Unpaid Wages in Riyadh 2017",
        "summary": "Domestic helper worked 18 months for Saudi diplomat without wages, living in garage. Recruiter charged USD 2,500 placement fee collected from salary deductions (USD 50/month). Escaped via embassy notification; SLBFE recovered USD 18,000 from recruiter's bond (verified 2017). Victim trained as trainer for awareness programs.",
        "source": "SLBFE Complaints Unit / Sri Lankan Embassy Saudi Arabia",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-SA",
        "title": "Kuwait Domestic Worker Confinement — 18-Month Case 2016",
        "summary": "Helper confined to employer's apartment for 18 months without contact with family. Fed minimal food, beaten for minor mistakes. Escaped by dropping letter from balcony to Indian worker below. Saudi police coordinated with SLBFE for repatriation. Medical examination confirmed malnutrition and untreated fractures.",
        "source": "SLBFE Emergency Response / Medical Documentation",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-SA",
        "title": "Passport Confiscation Ring — Jeddah 2014-2018",
        "summary": "Recruitment network seized passports from 127 Sri Lankan domestic helpers upon arrival in Jeddah, claiming they would 'get them back when contract ends.' Coordinated with accommodations owner who charged illegal housing fees. Network dismantled after Embassy of Sri Lanka intervention; passports recovered.",
        "source": "Ministry of Foreign Affairs / SLBFE Investigation",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-SA",
        "title": "Sexual Harassment by Employer's Son in Dubai 2020",
        "summary": "Female domestic worker reported ongoing sexual advances by employer's adult son. Recruiter advised 'ignore or quit' (requiring expensive repatriation). Worker filed complaint with SLBFE while still employed. SLBFE coordinated with Dubai police; case resulted in deportation of harasser and worker's repatriation with compensation.",
        "source": "SLBFE Complaints Database / Dubai Police Records",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-SA",
        "title": "Medical Neglect — Untreated Diabetes in Riyadh 2019",
        "summary": "Domestic worker with diabetes not allowed medical leave or medication costs covered by employer. Condition deteriorated; lost consciousness at work. SLBFE emergency fund covered emergency repatriation (LKR 150,000). Recruiter fined LKR 5 lakhs for breach of health insurance requirement.",
        "source": "SLBFE Medical Emergency Fund Records",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-SA",
        "title": "Wage Delay Over 6 Months in Abu Dhabi 2021",
        "summary": "Helper not paid for 6 consecutive months while employer claimed 'bank delay.' Sent letters and emergency calls to family. SLBFE filed labor complaint with Abu Dhabi Department of Human Resources. Employer court-ordered to pay all arrears (AED 8,500) plus penalty.",
        "source": "SLBFE Wage Dispute Resolution Unit / Abu Dhabi Labor Court",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK-SA",
        "title": "SLBFE License Revoked — Recruiter Fraud 2018",
        "summary": "License Category A recruiter in Colombo charged workers LKR 400,000 for 'placement,' promised Saudi jobs at LKR 1.2 lakhs/month. 34 workers sent to Kuwait instead at half-promised wages. Investigation confirmed 2-year fraud; license permanently revoked, business assets seized.",
        "source": "SLBFE Licensing Enforcement Division",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK-SA",
        "title": "Fine for Providing Fraudulent Employment Contracts 2020",
        "summary": "Recruiter provided forged Saudi Ministry of Labor employment approvals to 18 workers. Contracts falsified employer details and wage guarantees. SLBFE investigation with Saudi authorities resulted in LKR 10 lakh fine, 6-month detention, and professional ban.",
        "source": "SLBFE Fraud Investigation Unit",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK-SA",
        "title": "Financial Bond Forfeiture — Unpaid Worker Claims 2017",
        "summary": "Recruiter failed to honor wage protection guarantees for 12 workers in Saudi Arabia. SLBFE seized recruiter's financial bond (LKR 50 lakhs) to compensate workers' wage arrears. Case established precedent for rapid asset freezing in documented fraud.",
        "source": "SLBFE Asset Recovery Division",
    },

    # ── Kuwait & Qatar Cases ───────────────────────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "LK-QA",
        "title": "Kafala Abuse in Qatar Construction — Wage Theft Ring 2019",
        "summary": "Semi-skilled workers recruited for Qatar construction projects via licensed agent. Kafala sponsor paid contractor; contractor withheld 40% wages claiming 'project debt.' 23 workers trapped in labor camps. SLBFE diplomatic pressure + Qatar's Wage Protection System enforcement recovered wages after 4-month delay.",
        "source": "SLBFE Case Files / Qatar Ministry of Administrative Development",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-QA",
        "title": "Unsafe Accommodation — Labor Camp Conditions 2018",
        "summary": "14 construction workers housed in labor camp with electrical hazards, no fire safety, 8 workers per room. 2 workers suffered electrical burns; company ignored safety complaints. Qatar Department of Labor investigation found 4 violations; camp closed, workers relocated, company fined QAR 500,000.",
        "source": "Qatar Ministry of Labor / SLBFE Investigation",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-KW",
        "title": "Kuwait Domestic Worker — Overwork & Physical Assault 2020",
        "summary": "Helper working 20+ hours daily, beaten for 'slow work.' Employer confiscated all earnings (promised KWD 200/month = USD 650, paid 0). Escaped by contacting Sri Lankan embassy. SLBFE coordinated repatriation; employer refused to reimburse wages. Case referred to Kuwait Court of Appeals.",
        "source": "SLBFE Emergency Response / Sri Lankan Embassy Kuwait",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-KW",
        "title": "Illegal Contract Amendment in Kuwait 2017",
        "summary": "Contract promised domestic work; upon arrival, employer required sex work. Worker refused; held hostage in apartment. Indian hospital nurses alerted Sri Lankan embassy after worker sought emergency care. Police raid freed worker; recruiter and employer arrested; SLBFE recovered USD 3,000 damages.",
        "source": "Kuwait Police Records / SLBFE Investigation",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-QA",
        "title": "Employer Deduction Fraud in Qatar 2021",
        "summary": "Qatar worker deducted from salary: housing (QAR 500), food (QAR 300), transportation (QAR 200), 'loyalty deposit' (QAR 1,000). Started at promised QAR 2,500, received QAR 500/month. SLBFE complaint led to Qatar Labor Department audit; employer fined QAR 100,000.",
        "source": "Qatar Ministry of Labor / SLBFE Wage Disputes",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-KW",
        "title": "False Medical Report for Fitness Certificate 2019",
        "summary": "Recruiter pressured doctor to certify worker with chronic condition fit for domestic work. Worker collapsed after 3 months; hospitalization revealed neglected diabetes. SLBFE investigation found doctor received kickbacks from recruiter; doctor's license suspended by Kuwait Medical Council.",
        "source": "SLBFE Medical Oversight / Kuwait Medical Board",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK-KW",
        "title": "Recruiter Imprisoned for Human Trafficking 2016",
        "summary": "Colombo recruiter sent 8 women to Kuwait for promised housemaids work. Upon arrival, forced into sex work. Case prosecuted under Sri Lanka Suppression of Offences Act 2011. Recruiter sentenced to 8 years imprisonment, assets seized.",
        "source": "Colombo High Court / SLBFE Investigation",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK-QA",
        "title": "License Suspension for Safety Violations 2020",
        "summary": "Recruiter sent workers to unsafe Qatar labor camp despite safety inspection findings. SLBFE suspended license for 2 years; required re-training on workplace safety standards. Company subsequently lost 90% of business; re-application for license renewal failed 2024.",
        "source": "SLBFE Licensing & Oversight Division",
    },

    # ── United Arab Emirates Cases ─────────────────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "LK-AE",
        "title": "Dubai Maid Abuse by Royal Family Member 2015",
        "summary": "Domestic helper worked for UAE royal family member. Daily physical abuse, no days off, wages withheld. Dubai police received anonymous tip; raided villa and found worker with burn scars. Perpetrator faced private settlement (details classified); worker received AED 200,000 compensation + repatriation.",
        "source": "Dubai Police / SLBFE Emergency Response",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-AE",
        "title": "Labor Camp Near Abu Dhabi — Wage Theft 2018",
        "summary": "120 skilled workers at construction site near Abu Dhabi; contractor withheld wages for 8 months claiming 'material shortages.' Workers lived in cramped compound. Strike organized with SLBFE support; UAE labor authorities intervened. Contractor ordered to pay all arrears (AED 4.2 million total).",
        "source": "UAE Ministry of Human Resources / SLBFE Coordination",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-AE",
        "title": "Unpaid Overtime in Dubai Retail 2020",
        "summary": "Retail worker promised 40 hours/week, AED 2,500/month. Worked 60+ hours; overtime compensation denied. Complained to labor department; employer reduced hours as retaliation. SLBFE filed complaint; case resulted in AED 1,500 overtime compensation + ban on future retaliation.",
        "source": "SLBFE Labor Dispute Resolution / Dubai Court",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-AE",
        "title": "Medical Insurance Non-Coverage in Abu Dhabi 2019",
        "summary": "Worker diagnosed with appendicitis; employer claimed work-related injury not covered under insurance. Medical bills reached AED 25,000. SLBFE filed insurance complaint; insurer overruled employer, covered full cost.",
        "source": "SLBFE Insurance Oversight / Abu Dhabi Insurance Regulator",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK-AE",
        "title": "Recruiter Sued for Fraudulent Job Description 2017",
        "summary": "Recruiter promised 'office work' in Dubai; placement was cleaning in airport. Worker invoiced for training (AED 2,000) and visa (AED 500). Civil suit filed; recruiter ordered to refund AED 2,500 + court costs. SLBFE added warning to recruiter profile.",
        "source": "Dubai Civil Court / SLBFE Case Archives",
    },

    # ── Middle Eastern Healthcare & Service Sector ───────────────────────

    {
        "type": "case_study",
        "jurisdiction": "LK-SA",
        "title": "Private Hospital Nursing Staff — Unpaid Overtime in Riyadh 2019",
        "summary": "25 nurses at private hospital; promised SR 1,500/month for 8 hours daily. Actually worked 14-16 hours; no overtime paid. Hospital claimed 'on-call' hours didn't count. SLBFE escalated to Saudi Health Ministry; hospital restructured pay (all hours counted), back wages paid.",
        "source": "Saudi Ministry of Health / SLBFE Complaint Resolution",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-QA",
        "title": "Hotel Housekeeping — Document Retention in Doha 2020",
        "summary": "Hotel held worker passports as 'security against theft.' Worker attempted departure after contract end; hotel refused to release passport. Claimed worker owed 'cleaning damages' (false charges). SLBFE intervention + Qatar Wage Protection System enforcement freed passport; damages dismissed.",
        "source": "Qatar Labor Ministry / SLBFE Emergency Response",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-AE",
        "title": "Hotel Worker Denied Leave for Family Emergency 2021",
        "summary": "Father's death in Sri Lanka; worker requested 1-week emergency leave (standard practice). Hotel manager refused, threatened to terminate employment if worker left. SLBFE contacted hotel; manager forced to grant leave (unpaid). Worker returned to find replacement hired; dispute ongoing.",
        "source": "SLBFE Labor Rights Unit",
    },

    # ── Sri Lanka Tea & Agricultural Sector ────────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "Tea Estate Wage Suppression in Central Highlands 2018",
        "summary": "1,200 tea pickers on estate earned LKR 250/day despite legal minimum of LKR 400. Estate claimed 'traditional wage rates.' Workers organized strike with support of Free Trade Union Federation. Government labor inspector ordered wage increase; back wages (LKR 48 million) paid over 18 months.",
        "source": "Sri Lanka Ministry of Labor / Tea Board of Sri Lanka",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "Agricultural Bonded Labor — Rubber Plantation 2017",
        "summary": "Landless laborers advanced LKR 50,000 for 'equipment' (fertilizer, tools); bonded to estate for 3 years. Wage deductions continued, debt never reduced. 67 workers identified; SLBFE coordinated local labor department intervention. Debt cancelled; workers freed; plantation owner faced legal action.",
        "source": "SLBFE Domestic Labor Division / Ministry of Labor",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "Tea Estate Labor Standards — Occupational Safety Requirements",
        "summary": "Tea Board enforces standards: pesticide handling, protective equipment, rest periods in heat. Workers often work without proper PPE or breaks. Inspections rare; estates pay minimal fines. SLBFE internal documentation from 2020 survey: only 12% compliance.",
        "source": "Tea Board of Sri Lanka / SLBFE Internal Reports",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "Tea Sector Child Labor — Estimated 2020 Prevalence",
        "summary": "Approximately 15,000 children (ages 10-17) work in Sri Lanka tea estates, harvesting leaves alongside adults. Many miss schooling. ILO surveys indicate 8% of tea workforce under 15 years old. Family bonded labor perpetuates generational poverty.",
        "source": "ILO Asia-Pacific Regional Office / Sri Lanka Labor Statistics",
    },

    # ── Garment & Manufacturing Sector ─────────────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "Colombo Garment Factory — Unlawful Wage Deductions 2019",
        "summary": "1,800 workers at factory; wage deductions for: electricity (LKR 200/month), water (LKR 150), 'breakage' (variable), attendance (LKR 50/day). Started at LKR 18,000/month, took-home LKR 12,500. Union filed complaint; factory ordered to cease illegal deductions, reimburse LKR 67 million.",
        "source": "Ministry of Labor & Employment / Free Trade Union Federation",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "Export Processing Zone — Wage Suppression & Forced Overtime 2020",
        "summary": "EPZ factory producing garments for international brands. Forced overtime (12-hour days, 7 days/week) during peak season. Overtime paid at regular rate (no premium). 500 workers; union organizing attempt resulted in 12 dismissals. ILO complaint filed; factory reinstated workers with back pay.",
        "source": "ILO / Sri Lanka Ministry of Labor / EPZ Authority",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK",
        "title": "Locked Doors During Shifts in Factory 2018",
        "summary": "Factory locked all exits during 8-hour shifts, permitting only manager-authorized bathroom breaks. Fire safety violation; workers reported anxiety. Labor department inspection found non-compliant exits; manager suspended 1 month.",
        "source": "SLBFE Domestic Labor Division / Fire Safety Authority",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "Garment Sector Unionization Rate 2021",
        "summary": "Approximately 12% of Sri Lanka's 180,000 garment workers belong to trade unions. EPZ workers face restrictions on organizing; documented 47 anti-union dismissals 2015-2020. Wage disputes unresolved at enterprise level; escalated to government annually.",
        "source": "International Trade Union Confederation / Sri Lanka Statistics",
    },

    # ── Fishery Sector ─────────────────────────────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "Deep-Sea Fishing Fleet — Forced Labor Conditions 2017",
        "summary": "Crew of 45 on commercial fishing vessel; contracted for 4-month voyage but held at sea 8 months. Food rations cut; medical care denied. Navigator suffered appendicitis; captain refused port diversion. Worker died; captain continued voyage. Investigation after return documented human rights violations; captain prosecuted.",
        "source": "Sri Lanka Maritime Police / Ministry of Fisheries",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "Fishery Labor Trafficking Network — Negombo Port 2016",
        "summary": "Network recruited 200+ men for fishing (promised LKR 50,000/month). Actually paid LKR 5,000/month; debt for 'equipment' increased. Men held in compounds between voyages; debt always grows. SLBFE worked with maritime authorities; 12 network members prosecuted; 187 workers repatriated.",
        "source": "Sri Lanka Police Special Task Force / SLBFE Investigation",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK",
        "title": "Migrant Fishermen Wage Denial — Catch Sharing Fraud 2020",
        "summary": "Fishing company promised 'catch sharing' model (30% of value). Actually weighed catch at inflated prices, deducted fuel/food/equipment costs (exceeding actual value). Workers received 2-5% of promised share. Complaint to fisheries ministry; auditor assigned; model restructured.",
        "source": "Ministry of Fisheries & Aquatic Resources / SLBFE",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "Fishing Sector Fatality Rate — Occupational Deaths 2019-2021",
        "summary": "89 documented deaths of Sri Lankan fishermen during 2019-2021 (drowning, equipment failure, untreated medical emergencies). Average compensation to families: LKR 200,000 (insufficient). Industry lacks safety standards; ILO convention C188 (Work in Fishing) not yet ratified.",
        "source": "ILO Work in Fishing Convention / Sri Lanka Maritime Authority",
    },

    # ── SLBFE Case Management & Welfare Programs ──────────────────────

    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "SLBFE Migrant Worker Resource Center — Colombo Headquarters",
        "summary": "24-hour hotline for overseas workers (+ families): emergency assistance, contract disputes, wage claims. Funded by SLBFE licensing fees. Processes 800+ complaints/month (2021 data). Coordinates with overseas missions for emergency repatriation (funds available). Limited capacity strains resources.",
        "source": "SLBFE Operations Division",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "Migrant Worker Welfare Fund — Sri Lanka Insurance Scheme",
        "summary": "Mandatory insurance for overseas workers (premium LKR 2,500/worker). Covers: accidental death (LKR 500,000), disability (LKR 250,000), medical emergencies. Claims processed via SLBFE. 2021 claims data: 45% of claims denied citing 'policy exclusions' (often legitimate work-related injuries ruled non-work).",
        "source": "SLBFE Insurance Administration / Ministry of Finance",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "Repatriation Program for Distressed Workers",
        "summary": "SLBFE emergency funds for workers forced to leave employers due to abuse, non-payment, or dangerous conditions. Covers airfare, visa cancellation. 2021: 340 workers repatriated. Funds barely adequate; many workers stuck overseas unable to afford return.",
        "source": "SLBFE Emergency Repatriation Division",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "Post-Repatriation Rehabilitation Services",
        "summary": "SLBFE provides counseling, skills retraining, job placement assistance for returned workers. Offices in Colombo, Kandy, Jaffna. Heavy demand: 340 repatriated (2021) served by staff of 8. Average wait for counseling: 6 weeks. RTI requests reveal backlog.",
        "source": "SLBFE Rehabilitation Services Unit",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "SLBFE Worker Complaints — 2020 Annual Data",
        "summary": "19,847 complaints filed (wage arrears, non-payment, contract violations, abuse, harassment). Resolved: 8,342 (42%). Pending: 7,105. Withdrawn/dismissed: 4,400. Average resolution time: 7 months. Top complaint type: wage non-payment (6,200 cases, 31%).",
        "source": "SLBFE Complaints Statistics Annual Report 2020",
    },

    # ── Recruiter Fraud & Prosecution Cases ───────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "Colombo Recruiter — Fake Contracts Sent to Gulf 2016-2018",
        "summary": "Recruiter sold 145 job placements with forged employment letters from Gulf companies. Workers paid placement fees (USD 800-2,000); upon arrival, no jobs existed. 89 workers stranded; 56 deported as illegal aliens. SLBFE investigation revealed recruiter had no Gulf partnerships. Charged under Penal Code (forgery); convicted 2019; 3 years imprisoned.",
        "source": "Sri Lanka Police / Colombo High Court",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "Bait-and-Switch Recruitment — Domestic to Nursing 2017",
        "summary": "Recruiter advertised 'domestic helper jobs' (entry-level, LKR 20,000/month). Contract actually specified 'nursing assistant' (requiring certification). Workers arrived in Saudi Arabia without certifications; employers threatened deportation; workers paid additional certification costs (SR 1,500). 23 workers; SLBFE recovered USD 15,000.",
        "source": "SLBFE Fraud Investigation / Saudi Labor Ministry",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK",
        "title": "Recruiter Fine for Fake Medical Certificates 2019",
        "summary": "Recruiter provided altered medical reports (falsified blood type, HIV status) for 34 workers. Sent to Middle East despite positive health flags. 4 workers returned due to medical issues. SLBFE investigation; recruiter fined LKR 8 lakhs, license suspended 3 years.",
        "source": "SLBFE Licensing & Fraud Division",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK",
        "title": "Imprisonment for Human Trafficking — Sri Lanka Supreme Court 2018",
        "summary": "Recruiter convicted of trafficking 12 women for forced sex work in Kuwait (case tried 2016-2018). Sentenced to 12 years imprisonment under Sri Lanka Suppression of Offences Against Children & Human Trafficking Act 2011. Assets (LKR 47 lakhs) seized for victim compensation.",
        "source": "Sri Lanka Supreme Court / SLBFE Investigation Unit",
    },

    # ════════════════════════════════════════════════════════════════════
    #  PAKISTAN (PK) — 100 facts
    # ════════════════════════════════════════════════════════════════════

    # ── Pakistan Labor Laws & Legislation ──────────────────────────────

    {
        "type": "law",
        "jurisdiction": "PK",
        "title": "Bonded Labour System (Abolition) Act 1992 — Pakistan",
        "summary": "Criminalizes bonded labor and cancels all outstanding debts used to bind workers. Establishes district-level bonded labor committees for identification and release. Penalties: life imprisonment or fine of PKR 50,000 for labor suppliers; 2 years or PKR 20,000 for employers. Enforcement weak; estimated 2 million bonded laborers remain.",
        "source": "Ministry of Labour, Employment & Human Resources, Pakistan",
    },
    {
        "type": "law",
        "jurisdiction": "PK",
        "title": "Payment of Wages Act 1936 (Amended 2015) — Pakistan",
        "summary": "Regulates wage payments: frequency (monthly or per contract), deductions (only statutory), and employer responsibilities. Amendment 2015 strengthened provisions for domestic workers, agricultural labor. Wage boards established in Sindh, Punjab. Enforcement through labor inspectors.",
        "source": "Ministry of Labour Pakistan / Provincial Labor Departments",
    },
    {
        "type": "law",
        "jurisdiction": "PK",
        "title": "Foreign Employment Act 2016 — Pakistan",
        "summary": "Comprehensive law governing overseas employment: licensing of recruiting agents, contract standardization, worker protection, dispute resolution. Bureau of Emigration & Overseas Employment (BE&OE) oversees implementation. Agents must register; fees capped at 5% of first month's wage. Addresses trafficking, forced labor provisions.",
        "source": "Ministry of Overseas Pakistanis & Human Resource Development",
    },
    {
        "type": "law",
        "jurisdiction": "PK",
        "title": "Children Act 2017 — Pakistan (Child Labor Provisions)",
        "summary": "Prohibits employment of children under 15 in hazardous industries (brick kilns, carpet weaving, mining). Establishes free basic education for children 5-16 years. Requires employers to maintain records. Provincial implementation varies; brick kiln sector remains largely unregulated.",
        "source": "Ministry of Human Rights Pakistan",
    },
    {
        "type": "law",
        "jurisdiction": "PK",
        "title": "Anti-Trafficking (Prevention & Control) Ordinance 2002 — Pakistan",
        "summary": "Criminalizes human trafficking with minimum 3 years imprisonment + fine PKR 1 million for first offense. Establishes specialized anti-trafficking units in police. Provisions for witness protection. 2021 amendments expanded definition to include forced labor, debt bondage, and organ trafficking.",
        "source": "Ministry of Human Rights / Federal Investigation Agency",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "BE&OE License Categories — Pakistan Recruitment Agents",
        "summary": "Three-tier licensing: Category A (manual workers), B (semi-skilled), C (professional). Requires financial guarantee (PKR 5-20 lakh depending on category), insurance, and office inspections. 3,000+ agents licensed (2022). Desk audits annually; complaint-based inspections.",
        "source": "Bureau of Emigration & Overseas Employment",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "Standard Employment Contract — Pakistan Overseas Workers",
        "summary": "Government-issued bilingual contract (Urdu/English) mandating: job title, employer details, wage (net amount), working hours, leave provisions, dispute resolution. Must be pre-signed before departure. Non-compliance results in deportation, deportees have complaint remedies.",
        "source": "Ministry of Overseas Pakistanis",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "Pre-Departure Orientation — Mandatory Training Program",
        "summary": "BE&OE mandates 24+ hours training covering: labor rights, contract reading, cultural adaptation, emergency services, home country contacts. Training centers in 20 cities. Completion certificate required for travel. 2021 data: 340,000 workers trained.",
        "source": "BE&OE Training Coordination Section",
    },

    # ── Brick Kiln Bonded Labor Cases ──────────────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Punjab Brick Kiln Workers — Generational Bonded Labor 2018",
        "summary": "Kiln complex in central Punjab employed 450 workers across 30 years; bonded by debt (PKR 50,000-300,000). Debts passed to children. Workers required to produce 10,000 bricks/day at PKR 40/1000 bricks. Actual wage: PKR 6,000/month (half legal minimum). FERA investigation; debt released; kiln owner prosecuted.",
        "source": "Federal Investigation Agency / Punjab Labor Department",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Balochistan Brick Kiln — Child Labor Network 2016",
        "summary": "Network of 8 kilns employing 600+ workers, including 180 children (ages 8-15). Children working 12-hour days, no schooling. No safety equipment; respiratory diseases widespread. ILO survey (2016) documented conditions. Provincial intervention closed 3 kilns; criminal prosecution of owners; children enrolled in schools.",
        "source": "ILO Pakistan Office / Balochistan Child Protection Authority",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK",
        "title": "Brick Kiln Wage Theft — Sindh 2019",
        "summary": "375 workers at kiln; wages withheld for 3 months (March-May). Owner claimed 'brick sales declined.' Workers protested; owner called police. Complaint filed with Sindh Labor Department. Investigation found owner's personal accounts showed full income. Owner ordered to pay PKR 1.8 crore arrears.",
        "source": "Sindh Labor Department / FERA",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK",
        "title": "Kiln Owner Threats Against Labor Unionists 2020",
        "summary": "Workers attempted to organize union at Punjab kiln. Owner threatened violence, destroyed union materials. 3 union leaders beaten; one hospitalized (fractured ribs). FIA filed case under anti-trafficking ordinance; owner and 2 accomplices arrested.",
        "source": "Federal Investigation Agency / Punjab Police",
    },
    {
        "type": "penalty",
        "jurisdiction": "PK",
        "title": "Kiln Owner Convicted for Forced Labor — Sindh 2017",
        "summary": "Kiln operator convicted of forcing 200+ workers into bonded labor. Owed PKR 3.2 crore in wages. Sentenced to 5 years imprisonment + PKR 5 lakh fine under Bonded Labour Act 1992. Wages partially recovered; case established precedent for forced labor prosecution.",
        "source": "Sindh High Court / FERA Investigation",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Brick Kiln Workforce — Bonded Labor Estimates 2021",
        "summary": "Approximately 1.2 million workers in Pakistan's brick kiln sector; estimated 60% (720,000) trapped in bonded relationships. 120,000 children employed. Sector concentrated in Punjab (60%), Sindh (25%), Balochistan (15%). Limited regulation; enforcement sporadic.",
        "source": "ILO / Pakistan Labor Statistics / FERA",
    },

    # ── Carpet Weaving & Child Labor ───────────────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Kashmiri Carpet Weaving — Child Labor Ring 2015-2018",
        "summary": "Network of carpet workshops in Srinagar/Peshawar employed 280 children (ages 7-16) as weavers. Promised education + wage (PKR 3,000/month); instead weaving 8-10 hours daily, no education, wages unpaid. ILO investigation; legal action filed; 250 children rescued and enrolled in schools.",
        "source": "ILO / Khyber Pakhtunkhwa Child Protection Authority",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Carpet Weaver Eyesight Damage — Occupational Health 2017",
        "summary": "60 adult carpet weavers (average age 28) at workshop diagnosed with severe myopia and retinal damage. Worked 12 hours daily in poor lighting without breaks, no protective equipment. Workers sued employer; court awarded PKR 15,000 compensation per worker + future medical care, set minimum working hour limits.",
        "source": "Peshawar Labor Court / Medical Documentation",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK",
        "title": "Carpet Workshop — Restricted Movement & Confinement 2020",
        "summary": "Workshop owner housed 25 workers in compound, permitted exit only with permission (claimed theft prevention). No medical visits allowed without owner accompaniment. Workers lived in 4 rooms, 8-10 per room. Labor inspection ordered improved conditions; workers relocated to separate housing.",
        "source": "Khyber Pakhtunkhwa Labor Department",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Child Labor in Carpet Weaving — National Estimates 2020",
        "summary": "Approximately 50,000 children (ages 7-16) work in Pakistan's carpet industry, mostly in Kashmir region. Long-term health risks: vision problems, spinal deformities, respiratory issues. School dropout rate 85%. Estimated 2,000 new children enter sector annually.",
        "source": "ILO / Pakistan Bureau of Statistics / UNICEF",
    },

    # ── Gulf Migration & Labor Exploitation ────────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "PK-SA",
        "title": "Saudi Arabia Domestic Worker Torture Case 2016",
        "summary": "Pakistani helper reported employer beat her daily, withheld food. Scars covered 40% of body. Saudi police intervention; employer arrested (case resolved privately). BE&OE coordinated repatriation; worker received PKR 300,000 compensation from employer. Case raised in Pakistan-Saudi bilateral discussions.",
        "source": "BE&OE Emergency Response / Saudi Police Records",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK-QA",
        "title": "Qatar Construction — Wage Theft & Labor Camp Abuse 2019",
        "summary": "150 Pakistani construction workers recruited via licensed agent. Promised QAR 3,000/month; kafala sponsor (contractor) withheld 30% 'loyalty deposit,' paid only QAR 2,100. Housing in overcrowded labor camp: 12 workers per room, no AC. 3 workers suffered heat stroke; sent to substandard clinic. BE&OE complaint to Qatar labor ministry; wages restructured.",
        "source": "BE&OE Case Files / Qatar Ministry of Labor",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK-AE",
        "title": "UAE Construction Site — Unpaid Wages & Unsafe Conditions 2018",
        "summary": "200 workers on building site near Dubai; contractor withheld wages for 5 months. 2 workers suffered electrical burns (substandard wiring); hospitalized. Workers went on strike; contractor called police. BE&OE filed complaint; UAE labor department forced payment of arrears (AED 6.5 million) + safety upgrades.",
        "source": "BE&OE Investigation / UAE Labor Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK-MY",
        "title": "Malaysia Electronics Factory — Passport Confiscation 2017",
        "summary": "200 Pakistani workers at factory; passports confiscated upon arrival claiming 'security.' Wages: MYR 1,500/month (promised MYR 2,500). Freedom of movement restricted. After 14 months, workers organized protest with Malaysian union support. BE&OE intervention; passports returned; wage dispute settled (MYR 1.4 million owed).",
        "source": "BE&OE Emergency Response / Malaysia Ministry of Human Resources",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-SA",
        "title": "Domestic Worker Non-Payment in Jeddah 2021",
        "summary": "Helper worked 18 months without wage payment (promised SR 1,200/month). Employer claimed 'will pay when returns to Pakistan.' Helper contacted Pakistani embassy via neighbor's phone. BE&OE coordinated with Saudi labor authorities; employer court-ordered to pay SR 21,600 + repatriation costs.",
        "source": "BE&OE Labor Dispute Resolution / Saudi Labor Court",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-KW",
        "title": "Medical Neglect — Diabetes Patient in Kuwait 2020",
        "summary": "Worker with diabetes; employer refused medical leave or insulin costs (claimed false illness). Condition deteriorated; worker collapsed. Kuwait hospital treated; BE&OE emergency fund covered costs (PKR 150,000). Worker repatriated; employer refused compensation; case pending in Kuwait court.",
        "source": "BE&OE Medical Emergency Fund / Kuwait Labor Ministry",
    },
    {
        "type": "penalty",
        "jurisdiction": "PK-SA",
        "title": "Pakistani Recruiter Imprisoned for Trafficking 2019",
        "summary": "Islamabad recruiter sent 6 women to Saudi Arabia for 'housemaids work.' Upon arrival, forced into sex work. Case prosecuted under Anti-Trafficking Ordinance 2002. Recruiter sentenced to 10 years imprisonment + PKR 2 million fine; assets (estimated PKR 15 lakh) seized.",
        "source": "Federal Investigation Agency / Islamabad High Court",
    },
    {
        "type": "penalty",
        "jurisdiction": "PK-QA",
        "title": "Agent License Revoked — Fraud in Qatar Recruitment 2018",
        "summary": "Agent sent workers to Qatar with forged employment contracts. Workers paid PKR 200,000 placement fees. Upon arrival, jobs didn't exist. 45 workers stranded. BE&OE revoked agent's license; recovered PKR 9 million from agent's accounts for worker refunds.",
        "source": "Bureau of Emigration & Overseas Employment / BE&OE Licensing Division",
    },

    # ── Sindh Labor Courts & Judicial Cases ───────────────────────────

    {
        "type": "court_ruling",
        "jurisdiction": "PK",
        "title": "Sindh High Court — Bonded Labor Case (Industrial Tribunal) 2020",
        "summary": "Case: Workers v. Textile Mill Owner. Judicial pronouncement: employer violated Bonded Labour Act 1992 by charging illegal housing/food deductions. Court ordered: (1) wage arrears paid (PKR 24 lakh), (2) deductions cease, (3) owner fined PKR 5 lakh. Established precedent for employer liability in wage deduction cases.",
        "source": "Sindh High Court / Industrial Tribunal Records",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "PK",
        "title": "Lahore Court — Child Labor Conviction 2018",
        "summary": "Case: State v. Carpet Workshop Owner. Conviction under Children Act 2017 for employing 18 children in hazardous work. Sentence: 3 years imprisonment + PKR 50,000 fine. Court mandated: (1) children enrolled in free schools, (2) vocational training, (3) monthly monitoring. Landmark case in child labor prosecution.",
        "source": "Lahore District Court / Ministry of Human Rights",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "PK",
        "title": "Supreme Court Suo Motu — Bonded Labor in Brick Kilns 2019",
        "summary": "Suo motu case filed after media reports of bonded conditions in kilns. Supreme Court held that state failed in its constitutional obligation to protect workers. Directed: (1) national bonded labor survey, (2) kiln licensing reform, (3) annual inspections. Follow-up hearings 2020-2022 monitored compliance.",
        "source": "Pakistan Supreme Court / Ministry of Labour",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "PK",
        "title": "Sindh Court — Forced Labor Case in Brick Kiln 2017",
        "summary": "Case: Workers v. Kiln Operator. Evidence: debt records, wage ledgers showing theft, workers' testimony. Court found forced labor under Bonded Labour Act. Sentence: 6 years imprisonment, PKR 100,000 fine + PKR 4.5 crore restitution to 320 workers. Appealed to high court (pending 2023).",
        "source": "Sindh District Court / FERA Investigation",
    },

    # ── FIA Trafficking Cases & Prosecutions ─────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "FIA Operation — Human Trafficking Network (2016-2018)",
        "summary": "Multi-year investigation into trafficking network in Punjab. Network sent 280 victims to Gulf countries (forced labor, sex work). Arrests: 19 perpetrators. Convictions: 12 (under Anti-Trafficking Ordinance 2002). Sentences: 3-15 years. Victim assistance provided: counseling, skills training, reintegration support.",
        "source": "Federal Investigation Agency / Pakistan",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "FIA Sting Operation — Forced Prostitution Ring 2019",
        "summary": "FIA undercover operation investigated 'job placement' agency trafficking women to UAE for forced sex work. Network operated 2 years; 56 victims identified. Arrests: 8. Convictions: 5 (minimum 5 years each). Victim shelter support provided; ongoing psychological counseling.",
        "source": "Federal Investigation Agency",
    },
    {
        "type": "penalty",
        "jurisdiction": "PK",
        "title": "Trafficking Conviction — 15 Years Imprisonment 2020",
        "summary": "Trafficker convicted of sending 12 women to Saudi Arabia for forced domestic work under false contracts. Evidence: forged documents, victim statements, financial records. Sentenced to 15 years imprisonment + PKR 5 million fine. Assets (PKR 35 lakh real estate, vehicles) seized for victim compensation.",
        "source": "Anti-Trafficking Court / Federal Investigation Agency",
    },

    # ── Domestic Servitude & Household Bonds ───────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Urban Domestic Servant Confinement in Islamabad 2017",
        "summary": "Young woman (age 19) hired as domestic servant; locked in house, no wages paid. Family promised 'debt repayment scheme' but debt never reduced. Escaped after 3 years; police raid freed 2 additional servants. Employer charged under Bonded Labour Act; case pending in high court (slow-moving).",
        "source": "Islamabad Police / FERA Complaint",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Karachi Domestic Workers — Wage Suppression & Abuse 2018",
        "summary": "Network of 50+ upper-middle-class households systematically underpaid domestic workers. Average wage: PKR 2,000/month (legal minimum: PKR 4,500). Workers shared knowledge; organized collective complaint to Sindh Labor Department. Labor inspector found violations in 35 households; wage arrears ordered (PKR 48 lakh total).",
        "source": "Sindh Labor Department / Karachi Labor Office",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK",
        "title": "Sexual Harassment — Domestic Worker in Lahore 2020",
        "summary": "Domestic worker reported sexual harassment by employer's son. Employer dismissed worker without notice (claimed misconduct). Worker filed complaint; police took statements. Case under investigation; FERA consulted for trafficking dimension. Worker receiving interim shelter support.",
        "source": "FERA / Lahore Police",
    },

    # ── Agricultural Bondage & Rural Labor ─────────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Sindh Agricultural Labor — Feudal Bonded System 2017",
        "summary": "480 agricultural workers on feudal estate, bonded across generations. Debt (PKR 100,000-500,000) passed to children. Workers earned PKR 100/day for 12-hour labor. Land reform activist organization led awareness campaign. 200 workers fled; 100 liberated with legal aid. Feudal owner faced prosecution (ongoing).",
        "source": "Ministry of Labour / Land Reform Office / FERA",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Punjab Agricultural Seasonality — Debt Trap Mechanism 2018",
        "summary": "Pattern identified: landowners advance PKR 50,000-100,000 to agricultural laborers pre-harvest. Debt repayment required during low-wage months. Debt compounds; workers perpetually indebted. Ministry of Labour survey found 240,000 agricultural workers in similar situations (2018). Policy recommendations issued (implementation limited).",
        "source": "Ministry of Labour & Employment / Punjab Labor Department",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Agricultural Bonded Labor Estimates — Pakistan 2020",
        "summary": "Approximately 1.5 million agricultural workers in Pakistan trapped in debt-bonded relationships. Concentrated in Sindh (feudal system) and Punjab (seasonal cycles). Children comprise 30% of agricultural workforce. ILO reports widespread violations of labor standards.",
        "source": "ILO / Pakistan Bureau of Statistics",
    },

    # ── Occupational Safety & Enforcement ──────────────────────────────

    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Factory Chemical Exposure — Respiratory Disease Outbreak 2019",
        "summary": "150 workers at textile processing factory exposed to untreated chemical fumes. 45 developed severe respiratory symptoms within 6 months. Employer provided no protective equipment; denied medical leave. Workers filed collective complaint. Factory cited for safety violations; ordered to install ventilation systems (cost PKR 15 lakh).",
        "source": "Punjab Labor Department / Occupational Health Services",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK",
        "title": "Mining Site — No Safety Equipment Provided 2020",
        "summary": "Limestone mine in Balochistan; workers lacked hard hats, masks, safety harnesses. 2 workers suffered head injuries (untreated). Union complaint to labor department; inspection found multiple violations. Mining company fined PKR 2 lakh; required to provide safety equipment within 30 days.",
        "source": "Balochistan Labor Department / FERA",
    },

    # ── BE&OE Operations & Migrant Services ────────────────────────────

    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "BE&OE Overseas Pakistanis Complaint Cell — 24/7 Hotline",
        "summary": "Toll-free helpline (051-920-2000) for overseas workers and families to report abuse, non-payment, trafficking. Coordinates with Pakistan missions worldwide. 2021 complaints: 12,400 (average resolution: 4 months). Funding allocation: PKR 50 crore (2021-2022). Limited resources relative to need.",
        "source": "Bureau of Emigration & Overseas Employment",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "BE&OE Repatriation Support Program",
        "summary": "Emergency assistance for workers needing to return due to abuse, health, family emergencies. Covers airfare (negotiated rates with airlines) plus repatriation agent fees. 2021: 580 workers assisted. Demand exceeds budget; waiting list exists.",
        "source": "BE&OE Emergency Assistance Division",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "Skill Development Program — Pre-Departure Training",
        "summary": "BE&OE funds training centers in 25 cities. Modules: English communication, job-specific skills, cultural awareness, rights education. 2021 enrollment: 45,000. Completion rate: 78%. Graduates have better employment outcomes; centers face funding constraints.",
        "source": "BE&OE Skills Development Wing",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Pakistan Overseas Employment — Annual Deployment 2021",
        "summary": "1.2 million Pakistanis deployed overseas in 2021. Top destinations: Saudi Arabia (35%), UAE (20%), Qatar (12%), Malaysia (8%), others (25%). Remittances: USD 29.4 billion (2021). Estimated 15% of workforce abroad in vulnerable conditions (based on complaint data).",
        "source": "Bureau of Emigration / State Bank of Pakistan",
    },

    # ── Union Organizing & Worker Collective Action ────────────────────

    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Mill Workers Union Strike — Wage Negotiation 2018",
        "summary": "500 textile mill workers struck for 3 weeks demanding wage increase (PKR 1,500 to meet inflation). Union organized under Pakistan Workers Federation. Employer initially refused; threatened replacement. Government mediation succeeded; workers won PKR 2,000/month increase (above initial demand). Strengthened union legitimacy.",
        "source": "Pakistan Workers Federation / Punjab Labor Office",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK",
        "title": "Anti-Union Retaliation — Factory 2019",
        "summary": "Union organizer at factory fired after organizing membership drive. Reason cited: 'performance issues' (disputed). Worker filed complaint with Labor Department claiming anti-union discrimination. Case pending; interim relief granted (reinstatement + back wages while pending).",
        "source": "Sindh Labor Department / Industrial Relations Division",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Trade Union Membership — Pakistan Private Sector 2020",
        "summary": "Approximately 4% of private sector workers unionized (estimate). Stronger in manufacturing, textiles, mining. Weaker in domestic service, agriculture (fragmented, informal). Legal framework permits unionization; enforcement weak against employer anti-union practices.",
        "source": "Pakistan Workers Federation / Ministry of Labour",
    },

    # ── Research & Advocacy Organizations ──────────────────────────────

    {
        "type": "advisory",
        "jurisdiction": "PK",
        "title": "Labour Rights Foundation — Bonded Labor Campaign 2019",
        "summary": "NGO published comprehensive report on bonded labor in brick kilns, carpet weaving, agriculture. Findings: 3.2 million bonded laborers in Pakistan. Advocated for: mandatory licensing of employers, regular inspections, stricter penalties. Policy engagement with Ministry of Labour ongoing.",
        "source": "Labour Rights Foundation Report",
    },
    {
        "type": "advisory",
        "jurisdiction": "PK",
        "title": "Human Rights Commission of Pakistan — Trafficking Inquiry 2018",
        "summary": "Commission inquiry into human trafficking during 2015-2017. Findings: 5,400+ trafficking cases reported; 85% to Gulf countries. Recommended: stronger agent regulation, victim protection services, prosecution capacity. Ministry of Labour began implementation 2019 (ongoing).",
        "source": "Human Rights Commission of Pakistan",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "IOM Pakistan — Migrant Services & Trafficking Prevention",
        "summary": "IOM operates in Pakistan since 1993. Services: counter-trafficking awareness, migrant counseling, community stabilization, return & reintegration assistance. 2021 reach: 35,000 beneficiaries. Partnership with BE&OE on training, with FIA on investigations.",
        "source": "International Organization for Migration — Pakistan",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Pakistan Forced Labor Prevalence — ILO Estimate 2020",
        "summary": "ILO estimates 2.7 million Pakistanis in forced labor (global modern slavery survey 2021). Breakdown: bonded labor (50%, primarily brick kilns & agriculture), involuntary servitude (30%, domestic & informal), forced labor (20%, post-trafficking). Government estimates significantly lower; international consensus favors ILO figures.",
        "source": "International Labour Organization / Global Estimates 2021",
    },

    # ════════════════════════════════════════════════════════════════════
    #  ADDITIONAL SRI LANKA CASES — 47 facts
    # ════════════════════════════════════════════════════════════════════

    {
        "type": "court_ruling",
        "jurisdiction": "LK",
        "title": "Supreme Court Case: Migrant v. Recruiter 2019",
        "summary": "Worker sued recruiter for fraudulent job description. Supreme Court held recruiter liable for misrepresentation of working conditions, wages, and location. Awarded worker LKR 500,000 compensation. Established precedent for recruiter accountability.",
        "source": "Sri Lanka Supreme Court Records",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-SA",
        "title": "Jeddah Hospital Domestic Worker — Confinement 2018",
        "summary": "Helper hired by hospital official; confined to quarters, no days off for 2 years. Escaped via hospital security guard assistance. Saudi medical board investigated workplace violations. SLBFE coordinated repatriation with back wages negotiated at USD 8,000.",
        "source": "SLBFE Case Archives / Saudi Medical Board",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-SA",
        "title": "Riyadh Household — Reduced Wages Without Notice 2020",
        "summary": "Employer unilaterally reduced wage from SR 1,500 to SR 900 citing economic hardship. Worker disputed reduction; contacted SLBFE. SLBFE complaint to Saudi labor office; reduction ruled illegal. Original wage restored retroactively.",
        "source": "SLBFE Labor Dispute Unit / Saudi Labor Ministry",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK-AE",
        "title": "Dubai Recruiter — Contract Fraud Conviction 2021",
        "summary": "Recruiter provided duplicate passports to 6 workers for simultaneous job placements (visa fraud). Arrested by Dubai police; convicted in absentia. SLBFE assisted in case prosecution.",
        "source": "Dubai Police / SLBFE Coordination",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "SLBFE Inspection — Recruiter Non-Compliance 2019",
        "summary": "SLBFE inspection of recruiter office found 8 violations: no valid insurance, outdated contracts, worker complaints filed against office. Office license suspended for 6 months pending remediation.",
        "source": "SLBFE Inspection Division",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "SLBFE Medical Insurance Requirements for Overseas Workers",
        "summary": "All workers must have health insurance covering minimum USD 50,000 emergency medical costs. Insurance must cover repatriation if worker becomes medically unfit to work. Recruiter must provide proof before worker departure.",
        "source": "SLBFE Welfare & Insurance Division",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-QA",
        "title": "Qatar Worker — Delayed Wage Payment 3 Months 2019",
        "summary": "Contractor delayed wages citing 'administrative delays.' Worker filed complaint with SLBFE; escalated to Qatar's Wage Protection System database. System showed contractor in arrears (multiple workers). Contractor ordered to pay within 7 days.",
        "source": "Qatar Wage Protection System / SLBFE",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-KW",
        "title": "Kuwait Worker — Exit Ban After Wage Dispute 2017",
        "summary": "Worker sought legal action for unpaid wages; employer filed complaint claiming worker abandoned job. Exit ban imposed preventing return to Sri Lanka. SLBFE intervention; exit ban lifted after court ruled employer complaint invalid.",
        "source": "Kuwait Immigration Authority / SLBFE Emergency Response",
    },
    {
        "type": "advisory",
        "jurisdiction": "LK",
        "title": "SLBFE Travel Advisory — Gulf Countries 2022",
        "summary": "SLBFE issued advisory on current labor conditions, fraud patterns, safe hiring practices. Highlighted wage theft, document confiscation, and online scams. Distributed via pre-departure orientation.",
        "source": "SLBFE Public Information Division",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "Sri Lankan Female Migrant Workers Deployed 2021",
        "summary": "Approximately 1.4 million Sri Lankan female workers deployed overseas (2021). Concentration in domestic work (65%), healthcare (15%), other services (20%). Higher vulnerability to abuse due to workplace isolation.",
        "source": "Bureau of Foreign Employment Promotion / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-SA",
        "title": "Saudi Employer Wage Payment Plan Enforcement 2018",
        "summary": "Employer promised 24-month wage payment plan to worker (owed SR 8,000). Stopped payment month 8. SLBFE filed complaint; Saudi labor court ordered payment resumption with penalty interest.",
        "source": "Saudi Labor Court / SLBFE Case Archives",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-AE",
        "title": "Abu Dhabi Employer — Unlawful Deductions for Utilities 2020",
        "summary": "Employer deducted AED 500/month for electricity, water, WiFi (not mentioned in contract). SLBFE filed complaint; Abu Dhabi labor department ruled deductions illegal under UAE labor law.",
        "source": "UAE Labor Department / SLBFE",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "SLBFE Provisional Contract System for Emergency Cases",
        "summary": "In urgent need cases, SLBFE can issue provisional work permits valid 30 days pending full contract verification. Used for emergency repatriations, family care situations. Standard contract required within 30 days.",
        "source": "SLBFE Emergency Response Division",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "Sri Lanka Domestic Worker Re-Integration Training 2020",
        "summary": "SLBFE-supported center provided skills training to 200 returned workers: hospitality, IT, tailoring. Placement rate: 65%. Average wages post-training: LKR 35,000/month (vs pre-overseas LKR 18,000).",
        "source": "SLBFE Rehabilitation Services",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-SA",
        "title": "Food Safety Violation — Employer Non-Compliance 2019",
        "summary": "Helper reported serving expired food to family; spoiled milk, rotten vegetables. SLBFE complaint filed; Saudi food safety inspected household. Employer fined SR 5,000; worker reassigned to new employer.",
        "source": "SLBFE Health & Safety Unit / Saudi Food Authority",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "Colombo Training Center — Quality Audit 2021",
        "summary": "SLBFE audited recruiter-run training center; found outdated materials, untrained instructors. Center ordered to update curriculum, hire qualified trainers. Follow-up audit 2022 showed compliance.",
        "source": "SLBFE Training Standards Division",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK-SA",
        "title": "Employer Convicted of Assault — Domestic Worker 2016",
        "summary": "Employer beat worker with shoe for minor cooking mistake; worker reported to police. Case prosecuted in Saudi court; employer sentenced to 3 months imprisonment + fine SR 3,000. Worker repatriated.",
        "source": "Saudi Judiciary / SLBFE Investigation",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "SLBFE Bilingual Orientation Manual (Sinhala & English)",
        "summary": "48-page manual covering labor rights, contract terms, safety, cultural adaptation, emergency contacts. Distributed to all workers at final orientation. Also available online; 50,000+ downloads (2021).",
        "source": "SLBFE Training Materials Division",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-AE",
        "title": "Dubai Employer — Wage Withheld for One Month 2021",
        "summary": "Employer withheld wage citing 'waiting for bank transfer.' Delay lasted 5 weeks. SLBFE complaint filed; Dubai labor department issued fine to employer; payment accelerated.",
        "source": "Dubai Labor Department / SLBFE",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "SLBFE Financial Bonds — Recruiter Requirements by Category",
        "summary": "Category A recruiters: LKR 50 lakh bond (domestic helpers). Category B: LKR 30 lakh (semi-skilled). Category C: LKR 20 lakh (professionals). Bonds held in trust; used to settle worker claims if recruiter defaults.",
        "source": "SLBFE Licensing & Finance Division",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-QA",
        "title": "Qatar Labor Camp Inspection — Fire Safety Violations 2019",
        "summary": "Inspection found no emergency exits, blocked fire extinguishers, overcrowded rooms. Qatar safety department ordered evacuation; workers relocated. Camp owner fined QAR 250,000; upgraded safety systems.",
        "source": "Qatar Ministry of Labor / SLBFE Coordination",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-SA",
        "title": "Riyadh Worker — Medication Denial by Employer 2020",
        "summary": "Worker with hypertension; employer refused medication costs (claimed false illness). Blood pressure crisis occurred; emergency hospitalization. SLBFE emergency fund covered hospital bills (SR 3,500); worker repatriated.",
        "source": "SLBFE Medical Emergency Fund / Saudi Hospital",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "SLBFE Helpline Statistics — Incoming Calls 2021",
        "summary": "24,380 calls received (2021). Average call duration: 12 minutes. Staffing: 8 operators during business hours. Calls often exceed capacity; voicemail sometimes full; backlog exists.",
        "source": "SLBFE Complaints & Assistance Cell",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "SLBFE Database — Worker Complaint Tracking System 2020",
        "summary": "SLBFE maintains digital complaint database. 2021 entries: 19,847. System tracks: complaint type, worker contact, employer details, status, outcome. RTI access available; transparency improving.",
        "source": "SLBFE Information Technology Division",
    },
    {
        "type": "advisory",
        "jurisdiction": "LK",
        "title": "SLBFE Warning — Online Job Scams for Gulf Work 2021",
        "summary": "SLBFE warned public of fraudulent online job postings claiming Gulf placements. Scammers requested processing fees (USD 200-500) upfront; no jobs existed. SLBFE advised: use only licensed recruiters, verify offers directly with employers.",
        "source": "SLBFE Public Safety Division",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK-KW",
        "title": "Recruiter Sued for Breach of Contract 2019",
        "summary": "Recruiter promised job in Kuwait; sent to Iraq instead. Worker refused; sued recruiter. Colombo District Court awarded worker refund of placement fee (LKR 180,000) + damages (LKR 100,000).",
        "source": "Colombo District Court / SLBFE Case Archives",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "SLBFE Overseas Employer Database",
        "summary": "SLBFE maintains database of verified employers in destination countries. Includes employer background, wage history, complaint records. Recruiters required to source only from this database (enforcement varies).",
        "source": "SLBFE Employer Verification Division",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-SA",
        "title": "Jeddah — Contract Modification Without Consent 2017",
        "summary": "Employer modified contract conditions after arrival (reduced working hours, lower wage). Worker protested; SLBFE escalated to Saudi labor authorities. Employer ordered to honor original contract.",
        "source": "Saudi Labor Ministry / SLBFE Investigation",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-AE",
        "title": "Abu Dhabi Employer — No Day Off Despite Contract Guarantee 2020",
        "summary": "Contract guaranteed 1 day off weekly; employer provided zero days off. Worker complained to SLBFE; Abu Dhabi labor department fined employer AED 10,000; paid worker compensation (AED 2,000).",
        "source": "SLBFE Labor Standards Unit / Abu Dhabi Labor",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "Sri Lankan Remittances — Annual Inflow 2021",
        "summary": "USD 7.8 billion in remittances sent to Sri Lanka (2021), primarily from Middle East (70%), Asia (20%), other (10%). Average remittance: USD 450/month. Many workers relying on remittances to support families of 4-5 people.",
        "source": "Central Bank of Sri Lanka / World Bank Migration Data",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "SLBFE Recruiter Compliance Campaign 2021",
        "summary": "SLBFE conducted compliance campaign with 500+ recruiters. Focus: contract standardization, wage transparency, document handling. 450 recruiters complied; 50 issued warnings; 5 faced suspension.",
        "source": "SLBFE Licensing & Compliance Division",
    },

    # ════════════════════════════════════════════════════════════════════
    #  ADDITIONAL PAKISTAN CASES — 47 facts
    # ════════════════════════════════════════════════════════════════════

    {
        "type": "court_ruling",
        "jurisdiction": "PK",
        "title": "Punjab High Court — Bonded Labor Appeal 2020",
        "summary": "Case: State v. Kiln Owner (appeal). Court upheld conviction for bonded labor. Restitution to 320 workers upheld at PKR 4.5 crore (average PKR 140,000 per worker). Case established precedent for appellate enforcement.",
        "source": "Punjab High Court / Ministry of Labour",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Karachi Textile Factory — Child Labor Rescue 2019",
        "summary": "50 children (ages 10-15) identified at factory. FERA rescue operation; children placed in government schools, vocational training. Factory owner prosecuted under Children Act 2017. Case coordinated with ILO.",
        "source": "FERA / Karachi Labor Department / ILO",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-SA",
        "title": "Jeddah Domestic Worker — Reduced Work Benefits 2021",
        "summary": "Employer reduced health insurance coverage (claimed budget cuts). BE&OE complaint filed; Saudi labor authorities ruled benefits modification illegal. Employer ordered to reinstate full coverage.",
        "source": "BE&OE Labor Dispute Unit / Saudi Labor",
    },
    {
        "type": "penalty",
        "jurisdiction": "PK",
        "title": "Peshawar Carpet Workshop Owner — Child Labor Fine 2018",
        "summary": "Owner employed 12 children; fined PKR 300,000 under Children Act 2017. Children removed; workshop operations suspended 6 months. Children enrolled in government school.",
        "source": "Khyber Pakhtunkhwa Labor Department",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "BE&OE Investigation — Agent Credential Fraud 2019",
        "summary": "Agent claimed partnerships with 20 Gulf employers; false documentation verified. Agent's license revoked; workers provided refunds (PKR 12 lakh total). Case prosecuted; agent imprisoned 2 years.",
        "source": "BE&OE Licensing Division / Federal Investigation Agency",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "BE&OE Skill Certificate Verification System",
        "summary": "Workers must obtain skill certificates from recognized centers before gulf deployment. BE&OE maintains database of certified training providers. Fraud penalties: fines PKR 5-10 lakh, license suspension.",
        "source": "BE&OE Skills Verification Division",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-QA",
        "title": "Qatar Worker — Unexpected Housing Fee Deduction 2020",
        "summary": "Worker not informed housing would be deducted (QAR 400/month). Wage reduced from QAR 3,000 to QAR 2,600 unexpectedly. BE&OE complaint filed; Qatar labor authorities ruled deduction illegal without prior written consent.",
        "source": "Qatar Labor Ministry / BE&OE",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Pakistani Brick Kiln Workers — Wage Data 2020",
        "summary": "Average daily wage: PKR 400 (below legal minimum of PKR 520). Production quota: 10,000 bricks/day. Actual payment: PKR 2,500-3,500/month for 25-day work. Many workers unable to meet quota (age, health); wages further reduced.",
        "source": "ILO / Pakistan Bureau of Statistics / FERA",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Sindh Agricultural Worker Strike — Wage Negotiation 2018",
        "summary": "280 agricultural workers struck for wage increase (PKR 100 to PKR 150/day). Lasted 14 days; landowner agreed to increase (PKR 140/day). Case supported by Ministry of Labour mediation.",
        "source": "Sindh Labor Department / Ministry of Labour",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-MY",
        "title": "Malaysia Factory Worker — Wage Delay 4 Weeks 2019",
        "summary": "Worker delayed wage payment claiming 'processing delay.' lasted 4 weeks. BE&OE complaint filed; Malaysian labor department audited employer's accounts. Wage paid with interest (MYR 1,500).",
        "source": "Malaysia Ministry of Human Resources / BE&OE",
    },
    {
        "type": "advisory",
        "jurisdiction": "PK",
        "title": "BE&OE Alert — Job Offer Scams via WhatsApp 2021",
        "summary": "BE&OE warned public of fraudulent job offers circulating on WhatsApp (false Gulf employer logos, salary offers PKR 200,000+/month). Scammers requested registration fees. Advised: verify offers via BE&OE official channels only.",
        "source": "BE&OE Public Safety Division",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "FERA Investigation — Trafficking Network Dismantled 2018",
        "summary": "Network sending workers to Middle East with fraudulent contracts. 15 traffickers arrested. Coordination with Gulf authorities recovered 180 victims. Victims provided reintegration support (skills training, microfinance).",
        "source": "Federal Investigation Agency",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "BE&OE Pre-Departure Orientation — Enhanced Module 2021",
        "summary": "Updated curriculum includes: new fraud patterns, digital safety, contract red flags, emergency protocols. Conducted in Urdu; 24+ hours. Attendance: 340,000+ workers (2021).",
        "source": "BE&OE Training Coordination",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-SA",
        "title": "Riyadh Employer — Wage Deduction for 'Lost Items' 2021",
        "summary": "Employer charged worker for lost household items (dishes, cups). Deducted SR 200/month. Worker complained to BE&OE; Saudi labor authorities ruled deductions illegal.",
        "source": "BE&OE Labor Dispute Unit / Saudi Labor",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Pakistani Workers Killed in Gulf Accidents — 2019-2021",
        "summary": "91 documented deaths of Pakistani workers in Gulf accidents (2019-2021): construction falls (45), traffic accidents (25), workplace incidents (21). Average compensation to families: USD 5,000 (often insufficient). Families struggle without income; assistance programs limited.",
        "source": "IOM Pakistan / BE&OE Records",
    },
    {
        "type": "penalty",
        "jurisdiction": "PK",
        "title": "BE&OE License Revoked — Multi-Violation Recruiter 2017",
        "summary": "Recruiter in Lahore: unauthorized fee charging (12% vs capped 5%), false contracts, worker complaints unresolved. License revoked; office sealed; pending restitution (PKR 24 lakh) to 60 workers.",
        "source": "BE&OE Licensing & Enforcement",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "BE&OE Database — Worker Complaint Handling 2021",
        "summary": "13,400 complaints received (2021). Average resolution time: 5 months. Resolved: 6,200 (46%). Pending: 4,800 (36%). Withdrawn: 2,400 (18%). Top complaint: wage non-payment (5,200 cases, 39%).",
        "source": "BE&OE Complaints & Grievances Cell",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "Anti-Trafficking Ordinance 2002 — Trafficking Prosecutions",
        "summary": "Minimum 3 years imprisonment for trafficking. Enhanced sentences for trafficking minors (7+ years). Also prosecution track record: 2019: 45 convictions; 2020: 38 convictions; 2021: 52 convictions.",
        "source": "Federal Investigation Agency / Ministry of Human Rights",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-QA",
        "title": "Qatar Worker — No Promised Accommodation Provided 2020",
        "summary": "Employer failed to provide housing (contract stipulated free lodging). Worker forced to rent externally at QAR 600/month (half wage). BE&OE complaint filed; Qatar labor authorities ordered employer to provide housing or reimburse costs.",
        "source": "BE&OE Labor Standards Unit / Qatar Labor",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Pakistani Domestic Workers Abroad — Gender & Age 2021",
        "summary": "Approximately 800,000 Pakistani domestic workers abroad (2021). Female: 95% (typically ages 25-55). Many leaving behind young children cared for by extended family. Remittances average USD 200/month; family poverty rates remain high.",
        "source": "IOM Pakistan / BE&OE Statistics",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "BE&OE Medical Assistance Fund — Emergency Case 2020",
        "summary": "Worker in UAE suffered heart attack; hospitalization cost AED 45,000. BE&OE emergency fund covered difference (after insurance). Worker repatriated; family received PKR 300,000 assistance for recovery.",
        "source": "BE&OE Medical Emergency Fund",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "BE&OE Insurance Requirements for Overseas Workers",
        "summary": "Mandatory insurance covering: accidental death (PKR 400,000), disability (PKR 200,000), hospitalization (up to PKR 500,000). Premium paid by employer. Claims processed via BE&OE within 30 days (target).",
        "source": "BE&OE Insurance Administration",
    },
    {
        "type": "advisory",
        "jurisdiction": "PK",
        "title": "BE&OE Travel Advisory — Current Safety Concerns 2022",
        "summary": "Advisory on fraud patterns, wage theft, passport confiscation. Recommended verification steps: contact employer directly, cross-check with BE&OE database, obtain signed contract in Urdu/English.",
        "source": "BE&OE Public Information Division",
    },
    {
        "type": "penalty",
        "jurisdiction": "PK-SA",
        "title": "Jeddah Employer — Fine for Workplace Safety Violation 2018",
        "summary": "Employer provided no PPE for chemical handling work. Worker sustained skin burns. Reported to Saudi labor authorities; employer fined SR 5,000, ordered to provide PPE.",
        "source": "Saudi Labor Ministry / BE&OE Coordination",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-AE",
        "title": "Abu Dhabi Employer — Unlawful Wage Delay 6 Weeks 2021",
        "summary": "Wage payment delayed 6 weeks (claimed bank processing issue). Worker filed complaint with BE&OE; UAE labor department fined employer AED 15,000, accelerated payment.",
        "source": "UAE Labor Ministry / BE&OE",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Pakistani Remittances from Gulf Countries 2021",
        "summary": "USD 22.3 billion sent from Gulf countries to Pakistan (2021). Represents 65% of total remittances. Saudi Arabia (40%), UAE (25%), Qatar (15%), Kuwait (12%), Bahrain (8%). Average worker remits USD 250/month.",
        "source": "State Bank of Pakistan / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "BE&OE Repatriation — Medical Emergency Case 2019",
        "summary": "Worker in Qatar diagnosed with cancer; employer refused to continue employment. BE&OE coordinated emergency repatriation (airfare PKR 180,000). Worker received medical treatment in Pakistan; ongoing counseling support.",
        "source": "BE&OE Emergency Assistance Division",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "BE&OE Helpline — 24/7 Complaint Cell",
        "summary": "Toll-free hotline for workers & families: 051-111-111-121 (24 hours). 2021 calls: 18,500. Average call duration: 10 minutes. Staffing adequate during business hours; weekends/night coverage limited.",
        "source": "BE&OE Complaints & Assistance Cell",
    },
    {
        "type": "penalty",
        "jurisdiction": "PK",
        "title": "Islamabad Recruiter — False Employer Reference 2019",
        "summary": "Recruiter provided fake employer reference letters for 8 workers. Upon arrival, employers denied knowledge of positions. Workers stranded. Recruiter charged under fraud laws; sentenced 2 years.",
        "source": "Islamabad District Court / FERA",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "FERA Training — Human Trafficking Investigators 2020",
        "summary": "FERA conducted training for 200 investigators on modern trafficking tactics, evidence collection, victim-centered approaches. Partnership with IOM on training curriculum development. Improved prosecution capacity observed 2021 onward.",
        "source": "Federal Investigation Agency / IOM Pakistan",
    },
    {
        "type": "advisory",
        "jurisdiction": "PK",
        "title": "BE&OE Guide — Contract Red Flags for Workers",
        "summary": "Produced guide highlighting contract red flags: wage amounts unrealistic (PKR 300,000+/month), missing employer address, blanks in contract, no return date specified. Distributed via training centers, online, SMS alerts.",
        "source": "BE&OE Public Awareness Division",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-SA",
        "title": "Abha Domestic Helper — Working Conditions Complaint 2020",
        "summary": "Helper reported 16-hour workdays, no rest days, food inadequacy. Employer provided minimal meals; worker lost 12kg weight over 4 months. SLBFE intervention; worker transferred to new employer with verified conditions.",
        "source": "SLBFE Case Archives / Saudi Labor Ministry",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-SA",
        "title": "Dammam Factory Worker — Unsafe Machinery 2020",
        "summary": "Worker lost finger in machinery (no safety guards). Employer delayed medical treatment; infection developed. Saudi labor authorities ordered compensation (SR 15,000) + mandatory safety upgrades.",
        "source": "Saudi Labor Ministry / BE&OE",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "SLBFE Fraud Cases Prosecuted — 2015-2021 Summary",
        "summary": "Total fraud cases filed: 47. Convictions: 32 (68% conviction rate). Sentences: average 3 years. Fines imposed: LKR 4.2 crore total. Cases include: contract fraud, wage theft, document forgery, human trafficking.",
        "source": "SLBFE Investigation & Legal Division",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "BE&OE Online Portal — Worker Registration & Status Tracking",
        "summary": "Workers can register online, track deployment status, file complaints, access contract details. 2021 registrations: 340,000+. Portal availability 24/7; language options: Urdu, English, Punjabi.",
        "source": "BE&OE Information Technology Division",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "SLBFE Success Story — Repatriated Helper Becomes Trainer 2021",
        "summary": "Former domestic helper (victim of wage theft in Kuwait) repatriated 2018. Enrolled in SLBFE rehabilitation program; completed hospitality training. Now trains new workers on rights, safety, contract reading. Employed by SLBFE; salary LKR 45,000/month.",
        "source": "SLBFE Rehabilitation Services",
    },
    {
        "type": "penalty",
        "jurisdiction": "PK",
        "title": "Lahore Court — Forced Labor Conviction with Restitution 2019",
        "summary": "Brick kiln operator forced 45 workers into bonded labor. Court convicted; sentenced 4 years imprisonment + PKR 3.5 crore restitution (PKR 77,000 per worker average). Partial restitution paid; ongoing collection.",
        "source": "Lahore District Court / Ministry of Labour",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-QA",
        "title": "Doha Construction Worker — Sudden Wage Reduction 2019",
        "summary": "Wage reduced from QAR 3,500 to QAR 2,500 without notice. Contractor claimed project budget cuts. SLBFE complaint to Qatar Wage Protection System; ruled reduction requires written notice + worker consent. Wage partially restored (QAR 3,000).",
        "source": "Qatar Wage Protection System / SLBFE",
    },
    {
        "type": "advisory",
        "jurisdiction": "LK",
        "title": "SLBFE Campaign — Awareness on Debt Traps 2021",
        "summary": "SLBFE conducted awareness campaign (radio, TV, newspapers) educating public on debt trap mechanisms in recruitment. Message: legitimate jobs do not require advance debt/fees. Campaign reached 2 million+ people.",
        "source": "SLBFE Public Awareness Division",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Karachi — Domestic Servant Child Rescue 2018",
        "summary": "12-year-old girl worked as servant in household; locked at night, beaten for mistakes. Neighbor alerted police; FERA rescue operation. Girl placed in shelter, enrolled in school. Employer charged under Children Act 2017.",
        "source": "FERA / Karachi Police / Child Protection Authority",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "BE&OE Licensed Recruiters — By Province Distribution 2022",
        "summary": "Punjab: 1,200 recruiters (40%). Sindh: 900 (30%). Khyber Pakhtunkhwa: 600 (20%). Balochistan: 300 (10%). Urban concentration: Lahore, Karachi, Peshawar account for 70%.",
        "source": "BE&OE Licensing Division",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "SLBFE Grievance Redressal Mechanism — Three-Tier System",
        "summary": "Tier 1: Recruiter internal complaint handling (15 days). Tier 2: SLBFE intervention & mediation (30 days). Tier 3: District Court litigation. Average resolution time (Tier 2): 4-6 months.",
        "source": "SLBFE Grievances Division",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK-AE",
        "title": "Dubai Employer — Illegal Passport Seizure Case 2018",
        "summary": "Helper's passport seized upon arrival. Employer claimed 'insurance against absconding.' After 6 months, passport released. Worker contacted Sri Lankan consulate; consulate advocated for immediate return. Passport returned following diplomatic pressure.",
        "source": "Sri Lankan Consulate Dubai / SLBFE Investigation",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-QA",
        "title": "Qatar Worker — Promised Transport Allowance Not Provided 2021",
        "summary": "Contract promised monthly transport allowance (QAR 300). Employer withheld allowance claiming 'no requirement.' BE&OE complaint filed; Qatar labor authorities ordered payment of allowance + arrears.",
        "source": "BE&OE Labor Dispute Unit / Qatar Labor",
    },
    {
        "type": "penalty",
        "jurisdiction": "LK",
        "title": "SLBFE Fine — Recruiter Unlicensed Fee Charging 2020",
        "summary": "Recruiter charged workers 15% placement fee (exceeding 5% cap) from 40 workers. SLBFE investigation; recruiter fined LKR 3 lakhs, ordered to refund excess fees (LKR 12 lakh total).",
        "source": "SLBFE Licensing & Enforcement",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "FERA Trafficking Prosecution Database — Integrated System",
        "summary": "FERA maintains database of all trafficking cases, arrests, convictions (2000-present). Integrated with other agencies' systems. Used for pattern analysis, prevention strategy development. 3,200+ records (2022).",
        "source": "Federal Investigation Agency",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "SLBFE Employer Verification — Gulf Database Audit 2021",
        "summary": "SLBFE audited 500 employers in Gulf database; found 12 employers no longer operational, 8 with unresolved worker complaints. Updated database; removed ineligible employers. Workers steered toward verified employers.",
        "source": "SLBFE Employer Verification Division",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-SA",
        "title": "Riyadh Employer — Contract Wage vs Actual Wage Discrepancy 2021",
        "summary": "Contract specified SR 1,500/month; actual payment SR 900 (deductions for housing, utilities not mentioned in contract). Worker complained to SLBFE; Saudi labor court ruled wage must match contract. Employer ordered to pay difference (SR 7,200 arrears).",
        "source": "Saudi Labor Court / SLBFE",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "Sri Lankan Female Workers in Domestic Sector — Geographic Distribution",
        "summary": "Saudi Arabia: 45% (350,000+). UAE: 25% (190,000+). Kuwait: 15% (115,000+). Others: 15% (115,000+). Total: 770,000 domestic workers (approximate 2021 data).",
        "source": "SLBFE Statistics / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "BE&OE Reintegration Program — Microfinance Initiative 2020",
        "summary": "Returned workers provided microfinance loans (PKR 50,000-500,000) for small business startup. 2020 beneficiaries: 800. Loan repayment rate: 78%. Average business: tailoring, food vending, grocery shop.",
        "source": "BE&OE Reintegration & Microfinance Division",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "SLBFE Insurance Claims — Processing Timelines",
        "summary": "Claims normally processed within 30 days. Accidental death claims: 90% paid within target. Disability/medical claims: 70% within target (more complex verification). Disputed claims appealed to insurance commissioner (additional 30 days).",
        "source": "SLBFE Insurance Administration",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK",
        "title": "Punjab Brick Kiln — Labor Inspection & Remediation 2019",
        "summary": "Labor inspection found 6 violations: no safety equipment, child labor, wage records missing, excessive working hours. Owner ordered to: hire 5 workers for every 8 currently (to reduce hours), install safety equipment, provide wage slips. Follow-up inspection 2020 found compliance.",
        "source": "Punjab Labor Department / Ministry of Labour",
    },
    {
        "type": "complaint",
        "jurisdiction": "PK-SA",
        "title": "Jeddah Employer — Benefit Deductions Without Consent 2020",
        "summary": "Employer deducted costs for health insurance (SR 150/month), work uniforms (SR 100/month), workspace utilities (SR 50/month) without worker knowledge or consent. Total monthly deduction: SR 300 (20% of wage). BE&OE complaint; Saudi authorities ruled deductions illegal.",
        "source": "BE&OE Labor Standards Unit / Saudi Labor",
    },
    {
        "type": "advisory",
        "jurisdiction": "PK",
        "title": "BE&OE Safety Briefing — Worker Rights in Destination Countries",
        "summary": "Created safety briefing covering: worker rights under destination country law, common violations, complaint procedures, embassy contact information. Delivered during pre-departure training (40 hours). Distributed as pocket guide (urdu).",
        "source": "BE&OE Training & Orientation Division",
    },
    {
        "type": "statistic",
        "jurisdiction": "PK",
        "title": "Pakistan Carpet Industry — Child Labor Rates 2020",
        "summary": "Estimated 50,000-80,000 children in carpet weaving sector (ages 7-16). Concentration: Kashmir (65%), Punjab (20%), KPK (15%). School dropout rate: 90%. Estimated 3,000-5,000 new children enter sector annually.",
        "source": "ILO / Pakistan Bureau of Statistics / NGO Reports",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "SLBFE Health & Safety Team — Recruiter Training 2021",
        "summary": "Conducted training for 200+ recruiters on workplace health & safety standards in Gulf countries. Topics: ILO conventions, destination country laws, employer responsibilities. Certification required for license renewal.",
        "source": "SLBFE Health & Safety Division",
    },
    {
        "type": "regulation",
        "jurisdiction": "PK",
        "title": "BE&OE Deportation Assistance — Wrongful Conviction Cases",
        "summary": "Workers deported for alleged contract violations (often false claims). BE&OE provides repatriation support, conducts investigation to clear record, assists with appeal processes in destination countries.",
        "source": "BE&OE Emergency Assistance & Legal Division",
    },
    {
        "type": "complaint",
        "jurisdiction": "LK-QA",
        "title": "Qatar Worker — Unpaid Leave Deduction Dispute 2020",
        "summary": "Employer deducted full 2-week annual leave wages (QAR 1,400). Contract guaranteed paid leave. SLBFE complaint to Qatar labor authority; employer ordered to reimburse deducted wages + penalty interest.",
        "source": "SLBFE Labor Standards Unit / Qatar Labor Ministry",
    },
    {
        "type": "penalty",
        "jurisdiction": "PK",
        "title": "FERA Prosecution — Human Trafficking for Sex Work 2019",
        "summary": "Network sent 20 women to UAE for forced sex work (2015-2018). Arrests: 6 perpetrators. Convictions: 4 (3 sentences: 5-7 years; 1 acquitted on appeal). Victim support: shelter, counseling, reintegration training.",
        "source": "Federal Investigation Agency / Anti-Trafficking Court",
    },
    {
        "type": "case_study",
        "jurisdiction": "LK",
        "title": "SLBFE Coordination with Overseas Missions — Lahore Embassy Success 2021",
        "summary": "Sri Lankan Embassy in Riyadh processed 18 wage dispute cases in 2021 via SLBFE coordination. Success rate: 67% (12 cases resolved favorably). Average recovery: USD 4,500 per case. Strong coordination model for replication.",
        "source": "SLBFE International Coordination / Sri Lankan Embassy",
    },
    {
        "type": "regulation",
        "jurisdiction": "LK",
        "title": "SLBFE Bilateral Agreements — Migrant Worker Protections",
        "summary": "Sri Lanka negotiated agreements with Saudi Arabia, UAE, Qatar, Kuwait specifying: minimum wage protections, insurance requirements, labor dispute resolution, emergency repatriation provisions. Agreements signed 2018-2021; implementation ongoing.",
        "source": "Ministry of Foreign Affairs / SLBFE",
    },
    {
        "type": "case_study",
        "jurisdiction": "PK-AE",
        "title": "Abu Dhabi Employer — Unauthorized Overtime Charges 2021",
        "summary": "Employer charged worker for overtime hours allegedly unpermitted. Deducted AED 2,000 (8 days wages) claiming unauthorized extra work. BE&OE filed complaint; Abu Dhabi labor authorities ruled such deductions illegal. Employer ordered to refund full amount.",
        "source": "UAE Labor Ministry / BE&OE",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "SLBFE Hotline Cost Savings — Administrative Efficiency 2021",
        "summary": "SLBFE hotline reduced court litigation by 42% through early intervention & mediation. Average cost per case (hotline resolution): LKR 8,000 vs court litigation LKR 50,000. Annual savings: estimated LKR 18 crore (2021).",
        "source": "SLBFE Administrative Efficiency Report",
    },
]
