"""US Trafficking in Persons Report -- country assessments, tier rankings, and recommendations."""

US_TIP_REPORT_FACTS: list[dict] = [
    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 1 — TIP Report Methodology and Overview
    # ═══════════════════════════════════════════════════════════════════════
    {
        "type": "regulation_change",
        "jurisdiction": "US",
        "title": "US TIP Report — Legal Mandate and Publication History",
        "summary": "The Trafficking Victims Protection Act (TVPA, 2000) mandates the US State Department to publish an annual Trafficking in Persons (TIP) Report ranking countries by their government's efforts to comply with the TVPA's minimum standards for the elimination of trafficking. First published in 2001, the report has grown from covering 82 countries to 188 countries and territories. The TIP Report is the world's most comprehensive resource on governmental anti-trafficking efforts.",
        "source": "US Department of State — Trafficking in Persons Report (Annual)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "US",
        "title": "US TIP Report — Tier Ranking System Explained",
        "summary": "The TIP Report uses a four-tier ranking system: Tier 1 — governments fully meet the TVPA's minimum standards (approximately 30 countries); Tier 2 — governments do not fully meet minimum standards but are making significant efforts (approximately 96 countries); Tier 2 Watch List — same as Tier 2 but with increased total number of victims, failure to demonstrate increasing efforts, or determination based on commitments (approximately 40 countries); Tier 3 — governments do not fully meet minimum standards and are not making significant efforts (approximately 22 countries).",
        "source": "US Department of State — TIP Report Methodology Section (2023)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "US",
        "title": "US TIP Report — Consequences of Tier 3 Ranking",
        "summary": "Countries ranked Tier 3 face potential sanctions: (1) withholding of non-humanitarian, non-trade-related foreign assistance, (2) US opposition to assistance from international financial institutions (IMF, World Bank), (3) denial of funding for government officials' participation in educational and cultural exchange programmes. The President may waive sanctions if it is in the US national interest. In practice, most sanctions are waived, but the reputational impact of Tier 3 ranking is significant.",
        "source": "TVPA Sections 110-111 / US Department of State — TIP Report",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "US",
        "title": "US TIP Report — '3P' Paradigm: Prosecution, Protection, Prevention",
        "summary": "The TIP Report evaluates countries across the '3P' paradigm: (1) Prosecution — criminalization of trafficking, law enforcement efforts, convictions; (2) Protection — victim identification, services, legal assistance, immigration relief; (3) Prevention — public awareness campaigns, national action plans, labour inspection, training. Additionally, the 2008 TVPRA added a fourth 'P': Partnerships. Each country narrative provides specific data on all three pillars with quantitative metrics where available.",
        "source": "US Department of State — TIP Report Methodology / TVPRA 2008",
    },
    {
        "type": "statistic",
        "jurisdiction": "US",
        "title": "US TIP Report 2023 — Global Tier Distribution",
        "metric": "Distribution of 188 countries across tiers",
        "value": "T1: 30, T2: 96, T2WL: 40, T3: 22",
        "year": 2023,
        "summary": "The 2023 TIP Report ranked 188 countries and territories: 30 on Tier 1 (fully meeting minimum standards), 96 on Tier 2 (significant efforts but not fully meeting standards), 40 on Tier 2 Watch List, and 22 on Tier 3 (not meeting standards and not making significant efforts). Notable Tier 3 countries include: Afghanistan, Burma/Myanmar, China, Cuba, Eritrea, Iran, North Korea, Russia, South Sudan, Syria, Turkmenistan, and Venezuela.",
        "source": "US Department of State — TIP Report 2023, Global Tier Rankings",
    },
    {
        "type": "statistic",
        "jurisdiction": "US",
        "title": "US TIP Report 2023 — Global Prosecution Data",
        "metric": "Global trafficking prosecutions and convictions",
        "value": "10,500 prosecutions, 5,260 convictions worldwide",
        "year": 2023,
        "summary": "The 2023 TIP Report compiled global enforcement data: 10,500 trafficking prosecutions initiated worldwide (down from 12,000 in 2019), resulting in 5,260 convictions. Labour trafficking convictions remain far lower than sex trafficking convictions despite comparable or higher victim numbers. Countries with the most prosecutions: United States, United Kingdom, Netherlands, France, and India. Many countries reported zero prosecutions despite known trafficking problems.",
        "source": "US Department of State — TIP Report 2023, Global Law Enforcement Data",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 2 — Gulf State Destination Countries
    # ═══════════════════════════════════════════════════════════════════════
    {
        "type": "advisory",
        "jurisdiction": "SA",
        "title": "US TIP Report — Saudi Arabia: Tier 2 Watch List (2023)",
        "summary": "Saudi Arabia was placed on Tier 2 Watch List in 2023. Key findings: the government did not fully meet minimum standards but was making significant efforts. Concerns: (1) the kafala system continues to restrict worker mobility, especially for domestic workers, (2) limited prosecutions for labour trafficking (focus remains on sex trafficking), (3) passport confiscation persists despite legal prohibition, (4) domestic workers excluded from the Labour Reform Initiative. Positive: 400,000+ job transfers under LRI, Musaned e-contract platform, Wage Protection System expansion.",
        "source": "US Department of State — TIP Report 2023: Saudi Arabia Narrative",
    },
    {
        "type": "statistic",
        "jurisdiction": "SA",
        "title": "US TIP Report — Saudi Arabia: Prosecution and Protection Data",
        "metric": "Saudi Arabia trafficking enforcement statistics",
        "value": "39 trafficking investigations, 22 prosecutions, 14 convictions (2022)",
        "year": 2022,
        "summary": "Saudi Arabia reported 39 trafficking investigations, 22 prosecutions, and 14 convictions in 2022. Convictions resulted in sentences of 1-15 years. The government identified 297 trafficking victims. However, TIP Report notes that most investigations focus on sex trafficking and that labour trafficking investigations remain insufficient given the scale of the migrant workforce (13 million foreign workers). Government-run shelters served 600+ victims.",
        "source": "US Department of State — TIP Report 2023: Saudi Arabia Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "SA",
        "title": "US TIP Report — Saudi Arabia: Tier History",
        "summary": "Saudi Arabia's TIP tier history: Tier 3 (2005-2007), Tier 2 Watch List (2008-2013), Tier 3 (2014), Tier 2 Watch List (2015-2016), Tier 2 (2017-2021), Tier 2 Watch List (2022-2023). The recurring downgrade to Watch List reflects persistent concerns about kafala, domestic worker protections, and limited labour trafficking prosecutions despite a massive migrant workforce of 13+ million.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "AE",
        "title": "US TIP Report — United Arab Emirates: Tier 2 (2023)",
        "summary": "The UAE was ranked Tier 2 in 2023. Key findings: the government does not fully meet minimum standards but is making significant efforts. Progress noted: (1) increased trafficking convictions (45 in 2022), (2) improved victim identification (289 victims), (3) expansion of shelters and victim services, (4) labour law reforms including flexible work arrangements. Concerns: (1) continued vulnerability of domestic workers, (2) recruitment fees charged to workers, (3) some victims of trafficking misidentified as immigration violators and deported.",
        "source": "US Department of State — TIP Report 2023: UAE Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "AE",
        "title": "US TIP Report — UAE: Tier History",
        "summary": "UAE TIP tier history: Tier 3 (2005-2006), Tier 2 Watch List (2007-2008), Tier 2 (2009-2023). The UAE has maintained Tier 2 for 15 consecutive years. Sustained investment in anti-trafficking institutions (National Committee to Combat Human Trafficking, est. 2007), victim shelters, and prosecution capacity. Key recommendation for upgrade to Tier 1: extend full labour law coverage to domestic workers and eliminate recruitment fee charging to workers.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "QA",
        "title": "US TIP Report — Qatar: Tier 2 Watch List (2023)",
        "summary": "Qatar was ranked Tier 2 Watch List in 2023 despite ILO-supported reforms. Key findings: (1) significant reforms including kafala abolition, minimum wage, and WPS, (2) however, limited prosecutions of traffickers (3 convictions in 2022), (3) implementation gaps in reform enforcement, (4) domestic workers remain vulnerable, (5) reports that some workers transferred to new employers under reformed system still face exploitation. Positive: Workers' Support and Insurance Fund disbursed QAR 350 million in owed wages.",
        "source": "US Department of State — TIP Report 2023: Qatar Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "QA",
        "title": "US TIP Report — Qatar: Tier History",
        "summary": "Qatar TIP tier history: Tier 3 (2006-2007), Tier 2 Watch List (2008-2013), Tier 2 (2014-2017), Tier 2 Watch List (2018-2023). Despite landmark reforms driven by FIFA World Cup scrutiny and the ILO Technical Cooperation Programme, Qatar has not achieved Tier 2 since 2017. The persistent Watch List placement reflects the gap between reform legislation and on-the-ground enforcement, particularly for the 2+ million migrant workers in the country.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "KW",
        "title": "US TIP Report — Kuwait: Tier 2 Watch List (2023)",
        "summary": "Kuwait was ranked Tier 2 Watch List in 2023. Key findings: (1) the 2015 Domestic Workers Law provides some protections but enforcement is weak, (2) only 6 trafficking convictions in 2022, (3) domestic workers continue to report passport confiscation, wage withholding, and physical abuse, (4) shelter services expanded but insufficient for the estimated 700,000 domestic workers, (5) positive step: established a dedicated Domestic Worker Office. TIP Report recommended: increase labour trafficking prosecutions, enforce the domestic workers law, and strengthen victim identification among deported workers.",
        "source": "US Department of State — TIP Report 2023: Kuwait Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "KW",
        "title": "US TIP Report — Kuwait: Tier History",
        "summary": "Kuwait TIP tier history: Tier 3 (2005-2008), Tier 2 Watch List (2009-2014), Tier 3 (2015), Tier 2 Watch List (2016-2018), Tier 2 (2019), Tier 2 Watch List (2020-2023). Kuwait's fluctuation between Tier 3 and Tier 2 Watch List reflects cycles of reform and regression, particularly around domestic worker protections. The 2018 murder of a Filipina domestic worker found in a freezer triggered bilateral crisis with the Philippines and temporary deployment bans.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "BH",
        "title": "US TIP Report — Bahrain: Tier 2 (2023)",
        "summary": "Bahrain was ranked Tier 2 in 2023. Key findings: (1) the flexi-permit system allows some worker mobility but gaps remain, (2) 18 trafficking convictions in 2022 (highest rate per capita in the Gulf), (3) the LMRA actively monitors labour conditions, (4) shelter services available for victims. Concerns: (1) domestic workers remain under kafala, (2) flexi-permit workers lack standard labour protections, (3) recruitment fees continue to burden workers. Bahrain is considered the most progressive Gulf state on trafficking by TIP analysts.",
        "source": "US Department of State — TIP Report 2023: Bahrain Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "OM",
        "title": "US TIP Report — Oman: Tier 2 Watch List (2023)",
        "summary": "Oman was ranked Tier 2 Watch List in 2023. Key findings: (1) limited trafficking prosecutions (2 convictions in 2022), (2) domestic workers remain under kafala with minimal protections, (3) migrant workers in construction and agriculture report exploitation, (4) the government opened a shelter for trafficking victims but capacity is limited. TIP Report noted Oman's anti-trafficking law (Royal Decree 126/2008) provides adequate penalties but enforcement is insufficient. Oman hosts approximately 1.6 million migrant workers.",
        "source": "US Department of State — TIP Report 2023: Oman Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "JO",
        "title": "US TIP Report — Jordan: Tier 2 (2023)",
        "summary": "Jordan was ranked Tier 2 in 2023. Key findings: (1) Jordan is both a destination and transit country for trafficking, (2) 150,000+ migrant workers in QIZ garment factories and 50,000+ domestic workers, (3) 12 trafficking convictions in 2022, (4) Better Work Jordan programme improved conditions in some QIZ factories, (5) concerns about Syrian refugee exploitation in agriculture and informal sectors. Jordan ratified the Palermo Protocol and has a national anti-trafficking committee. TIP Report recommended: increase labour trafficking convictions and extend protections to QIZ workers.",
        "source": "US Department of State — TIP Report 2023: Jordan Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "LB",
        "title": "US TIP Report — Lebanon: Tier 2 Watch List (2023)",
        "summary": "Lebanon was ranked Tier 2 Watch List in 2023. Key findings: (1) the kafala system remains fully operative for domestic workers, (2) zero trafficking convictions in 2022, (3) economic collapse (since 2019) has worsened conditions — employer-paid wages in LBP lost 90% of value, (4) reports of domestic workers abandoned, locked out, or trafficked for sex, (5) an estimated 250,000 migrant domestic workers in Lebanon, predominantly Ethiopian, Bangladeshi, and Filipino. TIP Report noted that the draft labour law reform to cover domestic workers remains stalled in parliament.",
        "source": "US Department of State — TIP Report 2023: Lebanon Narrative",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 3 — Asian Destination Countries
    # ═══════════════════════════════════════════════════════════════════════
    {
        "type": "advisory",
        "jurisdiction": "MY",
        "title": "US TIP Report — Malaysia: Tier 2 Watch List (2023)",
        "summary": "Malaysia was ranked Tier 2 Watch List in 2023, having been downgraded from Tier 2. Key findings: (1) continued forced labour in electronics, rubber gloves, palm oil, and domestic work, (2) US CBP issued multiple Withhold Release Orders (WROs) against Malaysian companies, (3) only 42 trafficking convictions in 2022 (declining from previous years), (4) victim identification remains inadequate, (5) migrant workers from Bangladesh, Indonesia, Nepal, and Myanmar are most vulnerable. TIP Report recommended: increase prosecutions, enforce anti-fee-charging regulations, and end immigration detention of trafficking victims.",
        "source": "US Department of State — TIP Report 2023: Malaysia Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "MY",
        "title": "US TIP Report — Malaysia: Tier History",
        "summary": "Malaysia TIP tier history: Tier 2 Watch List (2007-2009), Tier 3 (2009, 2014), Tier 2 Watch List (2010-2013, 2015-2016), Tier 2 (2017-2021), Tier 2 Watch List (2022-2023). Malaysia's 2014 downgrade to Tier 3 coincided with the discovery of mass graves of trafficking victims at the Thai-Malaysian border. The 2017 upgrade to Tier 2 was controversial, with critics alleging political motivations during TPP negotiations.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "TH",
        "title": "US TIP Report — Thailand: Tier 2 (2023)",
        "summary": "Thailand was ranked Tier 2 in 2023, maintained since 2018. Key findings: (1) significant reforms in fishing sector following EU yellow card and Tier 3 ranking (2014-2015), (2) 305 trafficking investigations and 198 convictions in 2022, (3) improved PIPO maritime inspections, (4) concerns persist about forced labour of Myanmar and Cambodian workers in fishing, agriculture, and food processing. TIP Report recommended: increase convictions for complicit officials, improve victim identification among migrant workers, and ensure access to legal services.",
        "source": "US Department of State — TIP Report 2023: Thailand Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "TH",
        "title": "US TIP Report — Thailand: Tier History and Reforms",
        "summary": "Thailand TIP tier history: Tier 2 Watch List (2010-2013), Tier 3 (2014-2015), Tier 2 Watch List (2016-2017), Tier 2 (2018-2023). Thailand's 2014 downgrade to Tier 3 — driven by AP's Pulitzer Prize-winning investigation of slave fishing — triggered sweeping reforms: Royal Ordinance on Managing Foreign Workers, Command Centre for Combating Illegal Fishing (CCCIF), PIPO centres, ratification of C188, and major restructuring of the fishing industry. This is cited as an example of TIP rankings driving policy change.",
        "source": "US Department of State — TIP Reports Historical Rankings / Thai Government Reforms",
    },
    {
        "type": "advisory",
        "jurisdiction": "SG",
        "title": "US TIP Report — Singapore: Tier 2 (2023)",
        "summary": "Singapore was ranked Tier 2 in 2023. Key findings: (1) Singapore is a destination for labour trafficking of domestic workers and construction/marine sector workers, (2) 8 trafficking convictions in 2022, (3) the Prevention of Human Trafficking Act (2014) provides adequate legal framework, (4) concerns: domestic workers excluded from the Employment Act, recruitment fees charged to workers (up to 2 months' salary legal deduction), (5) the two-week rule for terminated workers creates vulnerability. TIP Report recommended: extend Employment Act to domestic workers and eliminate legal fee deductions.",
        "source": "US Department of State — TIP Report 2023: Singapore Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "HK",
        "title": "US TIP Report — Hong Kong SAR: Tier 2 (2023)",
        "summary": "Hong Kong SAR was ranked Tier 2 in 2023. Key findings: (1) approximately 370,000 foreign domestic workers (predominantly Filipino and Indonesian) face exploitation risks, (2) no standalone trafficking legislation (existing laws used for prosecution), (3) 14 trafficking-related convictions in 2022, (4) the two-week rule for terminated foreign domestic helpers creates vulnerability, (5) agency fee overcharging is widespread despite legal caps. TIP Report recommended: enact comprehensive anti-trafficking legislation and eliminate the two-week rule.",
        "source": "US Department of State — TIP Report 2023: Hong Kong Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "KR",
        "title": "US TIP Report — South Korea: Tier 1 (2023)",
        "summary": "South Korea was ranked Tier 1 in 2023. Key findings: (1) the Employment Permit System (EPS) is recognized as a model for government-managed recruitment, (2) 82 trafficking convictions in 2022, (3) improved victim identification and protection services, (4) remaining concerns: some E-6 (entertainment) visa holders and E-9 workers experience exploitation, (5) agricultural and fishing sector workers face isolation and longer working hours. The TIP Report recommended: allow E-9 workers more freedom to change employers and improve protections for entertainment visa holders.",
        "source": "US Department of State — TIP Report 2023: South Korea Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "JP",
        "title": "US TIP Report — Japan: Tier 2 (2023)",
        "summary": "Japan was ranked Tier 2 in 2023. Key findings: (1) the Technical Intern Training Program (TITP) continues to generate trafficking concerns — forced overtime, wage theft, inability to change employers, (2) 37 trafficking investigations and 12 convictions in 2022 (low given the scale), (3) the government announced TITP reform (proposed replacement system), (4) concerns about commercial sexual exploitation linked to JK business (schoolgirl cafes) and hostess bars, (5) 340,000+ technical interns from Vietnam, China, Philippines, and Indonesia. TIP Report recommended: abolish TITP restrictions on job changes and increase labour trafficking prosecutions.",
        "source": "US Department of State — TIP Report 2023: Japan Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "TW",
        "title": "US TIP Report — Taiwan: Tier 1 (2023)",
        "summary": "Taiwan was ranked Tier 1 in 2023. Key findings: (1) approximately 730,000 migrant workers (majority Indonesian, Vietnamese, Filipino, Thai) in manufacturing, fishing, agriculture, and domestic work, (2) 125 trafficking convictions in 2022 (strong enforcement record), (3) robust victim identification through NIA and Coast Guard, (4) concerns: fishing crew on distant-water vessels face forced labour, and domestic workers excluded from the Labour Standards Act. Taiwan is one of the few non-Western countries consistently on Tier 1.",
        "source": "US Department of State — TIP Report 2023: Taiwan Narrative",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 4 — Major Origin Countries
    # ═══════════════════════════════════════════════════════════════════════
    {
        "type": "advisory",
        "jurisdiction": "PH",
        "title": "US TIP Report — Philippines: Tier 1 (2023)",
        "summary": "The Philippines was ranked Tier 1 in 2023 (maintained since 2016). Key findings: (1) the Philippines is a major source country for trafficking victims in the Gulf, Asia, and globally, (2) IACAT (Inter-Agency Council Against Trafficking) coordinates national response, (3) 143 trafficking convictions in 2022 (strong prosecution record), (4) DMW (est. 2022) consolidates overseas worker protection, (5) concerns: online sexual exploitation of children increased during COVID, and recruitment fee overcharging persists via sub-agents. The Philippines is considered a model origin country for anti-trafficking efforts.",
        "source": "US Department of State — TIP Report 2023: Philippines Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "BD",
        "title": "US TIP Report — Bangladesh: Tier 2 (2023)",
        "summary": "Bangladesh was ranked Tier 2 in 2023. Key findings: (1) major source country for migrant workers to Gulf states and Malaysia (7.5 million abroad), (2) 52 trafficking convictions in 2022, (3) workers pay the highest recruitment fees globally (average USD 3,500 for Saudi corridor), (4) Rohingya refugees in Cox's Bazar face heightened trafficking risk, (5) BMET enforcement against unlicensed agents is insufficient. TIP Report recommended: increase enforcement against fraudulent recruitment, improve Rohingya protection, and strengthen BMET regulatory capacity.",
        "source": "US Department of State — TIP Report 2023: Bangladesh Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "NP",
        "title": "US TIP Report — Nepal: Tier 2 (2023)",
        "summary": "Nepal was ranked Tier 2 in 2023. Key findings: (1) major source country for labour migration to Gulf states, Malaysia, and South Korea (3.5 million abroad), (2) 35 trafficking convictions in 2022, (3) zero-fee policy widely violated — 85% of workers pay above legal limits, (4) 1,600+ worker deaths abroad annually (Foreign Employment Board data), (5) bonded labour (Kamaiya, Haliya systems) persists domestically despite legal abolition. TIP Report recommended: enforce recruitment fee caps, improve repatriation support, and prosecute bonded labour practitioners.",
        "source": "US Department of State — TIP Report 2023: Nepal Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "IN",
        "title": "US TIP Report — India: Tier 2 (2023)",
        "summary": "India was ranked Tier 2 in 2023. Key findings: (1) source, destination, and transit country for trafficking, (2) estimated millions in bonded labour in brick kilns, agriculture, quarrying, and garment industry, (3) 1,115 trafficking convictions in 2022 (highest absolute number globally), (4) domestic anti-trafficking bill (2021) progressing, (5) inter-state trafficking of tribal and lower-caste communities significant. TIP Report recommended: pass comprehensive anti-trafficking legislation, address bonded labour systemically, and improve inter-state coordination. India has the world's largest estimated number of forced labour victims.",
        "source": "US Department of State — TIP Report 2023: India Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "PK",
        "title": "US TIP Report — Pakistan: Tier 2 Watch List (2023)",
        "summary": "Pakistan was ranked Tier 2 Watch List in 2023. Key findings: (1) bonded labour in brick kilns (estimated 2-4 million workers), agriculture, and carpet weaving, (2) source country for Gulf states (particularly Saudi Arabia and UAE), (3) 42 trafficking convictions in 2022, (4) weak enforcement of bonded labour laws despite Supreme Court directives, (5) trafficking of women and girls for forced marriage (internally and to China under CPEC-linked exploitation). TIP Report recommended: implement bonded labour abolition laws, investigate Chinese-Pakistani trafficking networks, and increase convictions.",
        "source": "US Department of State — TIP Report 2023: Pakistan Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "LK",
        "title": "US TIP Report — Sri Lanka: Tier 2 Watch List (2023)",
        "summary": "Sri Lanka was ranked Tier 2 Watch List in 2023. Key findings: (1) major source country for domestic workers in Gulf states and Jordan, (2) economic crisis (2022) increased outmigration through irregular channels, (3) 8 trafficking convictions in 2022 (declining), (4) tea plantation workers (Indian Tamil) face labour exploitation domestically, (5) Sri Lankan fishermen trafficked to vessels in Indian Ocean. TIP Report recommended: increase prosecutions, address post-crisis irregular migration, and improve victim identification.",
        "source": "US Department of State — TIP Report 2023: Sri Lanka Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "ID",
        "title": "US TIP Report — Indonesia: Tier 2 (2023)",
        "summary": "Indonesia was ranked Tier 2 in 2023. Key findings: (1) major source country for migrant workers to Malaysia, Saudi Arabia, Hong Kong, Singapore, and Taiwan, (2) BNP2MI replaced BNP2TKI as regulatory body under Law 18/2017, (3) 75 trafficking convictions in 2022, (4) zero-cost migration principle in law but widely violated in practice, (5) fishermen on foreign-flagged vessels face severe exploitation, (6) palm oil sector uses child labour. TIP Report recommended: enforce zero-cost policy, improve overseas monitoring, and prosecute fishing vessel traffickers.",
        "source": "US Department of State — TIP Report 2023: Indonesia Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "MM",
        "title": "US TIP Report — Myanmar: Tier 3 (2023)",
        "summary": "Myanmar was ranked Tier 3 in 2023 (downgraded after the 2021 military coup). Key findings: (1) the military junta imposes forced labour including forced portering, infrastructure construction, and military service, (2) economic collapse has driven desperation migration to Thailand, Malaysia, and China, (3) zero trafficking prosecutions by the junta in 2022, (4) cross-border trafficking to Chinese cyber-scam operations has surged, (5) Rohingya face trafficking to Malaysia and Bangladesh. The TIP Report documented military-imposed forced labour as a systematic practice.",
        "source": "US Department of State — TIP Report 2023: Burma (Myanmar) Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "KH",
        "title": "US TIP Report — Cambodia: Tier 2 Watch List (2023)",
        "summary": "Cambodia was ranked Tier 2 Watch List in 2023, downgraded due to the cyber-scam trafficking crisis. Key findings: (1) tens of thousands of people from across Asia trafficked to Cambodia for forced labour in online scam operations, (2) 'scam compounds' in Sihanoukville, Poipet, and other border areas confine workers who are beaten and threatened, (3) only 28 trafficking convictions in 2022, (4) traditional trafficking to Thailand for fishing, agriculture, and domestic work continues. TIP Report recommended: urgently address cyber-scam trafficking and prosecute compound operators.",
        "source": "US Department of State — TIP Report 2023: Cambodia Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "VN",
        "title": "US TIP Report — Vietnam: Tier 2 Watch List (2023)",
        "summary": "Vietnam was ranked Tier 2 Watch List in 2023. Key findings: (1) major source country for labour trafficking — workers pay USD 5,000-7,500 for Japan TITP, USD 3,000-5,000 for Taiwan/Korea placements, (2) 60 trafficking convictions in 2022, (3) Vietnamese workers in UK, Europe (lorry containers, nail bars, cannabis farms), and Gulf states face exploitation, (4) state-linked labour export companies charge excessive fees, (5) online fraud trafficking to Cambodia increasing. TIP Report recommended: reduce recruitment fees, investigate state-linked companies, and address UK/EU trafficking routes.",
        "source": "US Department of State — TIP Report 2023: Vietnam Narrative",
    },

    # ── African origin countries ──────────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "ET",
        "title": "US TIP Report — Ethiopia: Tier 2 (2023)",
        "summary": "Ethiopia was ranked Tier 2 in 2023. Key findings: (1) major source country for domestic workers to Saudi Arabia, Lebanon, Kuwait, and UAE, (2) 180 trafficking convictions in 2022, (3) Ethiopia periodically bans labour migration (2013 ban lifted 2018; partial ban 2020), (4) child trafficking for domestic work within Ethiopia is widespread, (5) Tigray conflict (2020-2022) increased trafficking vulnerability. TIP Report recommended: strengthen bilateral agreements with Gulf states, address child trafficking, and improve pre-departure training.",
        "source": "US Department of State — TIP Report 2023: Ethiopia Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "KE",
        "title": "US TIP Report — Kenya: Tier 2 (2023)",
        "summary": "Kenya was ranked Tier 2 in 2023. Key findings: (1) source, transit, and destination country for trafficking, (2) Kenyan workers trafficked to Gulf states (Saudi Arabia, Qatar, UAE) for domestic work and construction, (3) 38 trafficking convictions in 2022, (4) internal trafficking of children for domestic work, agriculture, and commercial sexual exploitation, (5) Somali and Ethiopian refugees transiting Kenya face trafficking. TIP Report recommended: increase Gulf-corridor investigations, improve victim services, and combat child trafficking through social protection programmes.",
        "source": "US Department of State — TIP Report 2023: Kenya Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "NG",
        "title": "US TIP Report — Nigeria: Tier 2 (2023)",
        "summary": "Nigeria was ranked Tier 2 in 2023. Key findings: (1) major source and transit country — Nigerian victims identified in 38 countries, (2) NAPTIP (National Agency for the Prohibition of Trafficking in Persons) achieved 65 convictions in 2022, (3) trafficking routes to Libya, Europe (Italy, Spain), Gulf states, and within West Africa, (4) child trafficking for domestic work, begging, and sexual exploitation is widespread, (5) 'baby factories' (facilities where girls are impregnated and babies sold) documented. TIP Report recommended: increase prosecutions, especially for labour trafficking, and strengthen NAPTIP's budget.",
        "source": "US Department of State — TIP Report 2023: Nigeria Narrative",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 5 — Tier Upgrades/Downgrades of Interest
    # ═══════════════════════════════════════════════════════════════════════
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Notable Downgrades (2020-2023)",
        "summary": "Notable TIP Report downgrades (2020-2023): (1) Myanmar: Tier 2 Watch List to Tier 3 (2022) after military coup, (2) Malaysia: Tier 2 to Tier 2 Watch List (2022) due to declining prosecutions and forced labour in electronics/gloves, (3) Cambodia: Tier 2 to Tier 2 Watch List (2022) due to cyber-scam trafficking crisis, (4) Sri Lanka: Tier 2 to Tier 2 Watch List (2023) amid economic crisis, (5) Russia: Tier 2 Watch List to Tier 3 (2023) following invasion of Ukraine and forced deportation of Ukrainian children.",
        "source": "US Department of State — TIP Reports 2020-2023, Tier Changes",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Notable Upgrades (2020-2023)",
        "summary": "Notable TIP Report upgrades (2020-2023): (1) Thailand: Tier 2 Watch List to Tier 2 (2018, maintained) after fishing sector reforms, (2) Uzbekistan: Tier 2 Watch List to Tier 2 (2023) after ending systematic forced cotton labour, (3) Philippines: maintained Tier 1 since 2016 (model origin country), (4) South Korea: Tier 2 to Tier 1 (2022) due to EPS effectiveness and increased convictions, (5) Taiwan: maintained Tier 1 due to strong enforcement despite fishing concerns.",
        "source": "US Department of State — TIP Reports 2020-2023, Tier Changes",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 6 — TIP Sanctions, Impact, and Criticism
    # ═══════════════════════════════════════════════════════════════════════
    {
        "type": "regulation_change",
        "jurisdiction": "US",
        "title": "US TIP Report — Sanctions Applied to Tier 3 Countries",
        "summary": "TVPA authorizes sanctions against Tier 3 countries: withholding non-humanitarian foreign assistance and opposing international financial institution loans. In practice, most sanctions are waived by presidential determination citing national interest. Countries where sanctions have been partially applied include: North Korea (comprehensive sanctions already in effect), Eritrea, and Cuba. The primary impact of Tier 3 is reputational, driving reform in countries seeking to avoid the designation.",
        "source": "TVPA Sections 110-111 / Congressional Research Service — TIP Sanctions Analysis",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Effectiveness: Evidence of Policy Impact",
        "summary": "Academic research (Cho and Vadlamannati, 2012; Kelley and Simmons, 2015) demonstrates that TIP tier rankings influence anti-trafficking policy. Countries dropped to Tier 2 Watch List or Tier 3 show increased likelihood of: (1) passing anti-trafficking legislation, (2) establishing specialized anti-trafficking units, (3) increasing prosecutions. Thailand's 2014-2015 Tier 3 ranking drove its most comprehensive anti-trafficking reform. However, critics note that geopolitical allies (e.g., Saudi Arabia) receive more lenient treatment.",
        "source": "Academic: Cho & Vadlamannati (2012) / Kelley & Simmons (2015) / Congressional Research Service",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Criticism: Political Bias in Rankings",
        "summary": "The TIP Report has been criticized for political bias: (1) the US GAO (2006) found that countries' economic and security relationships with the US correlate with higher rankings, (2) Malaysia's 2017 upgrade from Tier 3 to Tier 2 Watch List coincided with TPP negotiations (criticized by Congressional Democrats and NGOs), (3) Saudi Arabia has avoided Tier 3 despite conditions comparable to Tier 3 countries, (4) the US ranks itself on Tier 1 despite documented labour trafficking (agricultural H-2A, diplomatic household workers). The TIP Office has increased transparency in methodology in response to criticism.",
        "source": "US GAO Report GAO-06-825 / Congressional testimony / Academic analysis",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Criticism: Labour Trafficking Underemphasized",
        "summary": "Critics argue the TIP Report historically overemphasizes sex trafficking relative to labour trafficking. Evidence: (1) labour trafficking prosecutions globally remain far lower than sex trafficking prosecutions despite comparable or larger victim populations, (2) country narratives devote more space to sex trafficking, (3) some countries achieve Tier 1 or Tier 2 primarily through sex trafficking enforcement while ignoring labour trafficking. The 2022 and 2023 reports show improvement, with dedicated sections on labour trafficking and forced labour indicators.",
        "source": "Polaris Project / Anti-Slavery International / Academic critiques",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "US",
        "title": "US TIP Report — US Self-Assessment and Domestic Trafficking",
        "summary": "The US has ranked itself on Tier 1 since 2010 (when it began self-ranking). Key domestic trafficking issues identified: (1) H-2A agricultural visa programme associated with labour trafficking (debt bondage, wage theft), (2) diplomatic household workers face exploitation (immunity shields employers), (3) domestic child sex trafficking, (4) forced labour in restaurants, hospitality, and construction. Federal convictions in 2022: 235 sex trafficking and 8 labour trafficking. The low labour trafficking conviction rate compared to identification rates is noted by critics.",
        "source": "US Department of State — TIP Report 2023: United States Narrative",
    },
    {
        "type": "statistic",
        "jurisdiction": "US",
        "title": "US TIP Report — National Human Trafficking Hotline Data",
        "metric": "Annual contacts to US National Trafficking Hotline",
        "value": "51,000+ contacts, 16,500+ trafficking situations identified (2022)",
        "year": 2022,
        "summary": "The US National Human Trafficking Hotline (operated by Polaris Project) received over 51,000 contacts in 2022 and identified 16,554 trafficking situations. Labour trafficking: 5,200+ situations (31%). Sex trafficking: 9,800+ situations (59%). Both: 1,500+. Top labour trafficking industries: domestic work, agriculture, restaurants, construction, and health/beauty services. Top states: California, Texas, Florida, New York, Ohio. The data informs the TIP Report's US narrative.",
        "source": "Polaris Project — National Trafficking Hotline Annual Report 2022",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 7 — Country-Specific Enforcement and Recommendations
    # ═══════════════════════════════════════════════════════════════════════
    {
        "type": "statistic",
        "jurisdiction": "QA",
        "title": "US TIP Report — Qatar: Prosecution and Protection Data",
        "metric": "Qatar trafficking enforcement statistics",
        "value": "15 investigations, 5 prosecutions, 3 convictions (2022)",
        "year": 2022,
        "summary": "Qatar reported 15 trafficking investigations, 5 prosecutions, and 3 convictions in 2022. Despite having 2+ million migrant workers, the conviction rate remains extremely low. The Workers' Support and Insurance Fund disbursed QAR 350 million to workers owed wages. 87 victims identified. TIP Report noted the significant gap between reform legislation and enforcement outcomes, especially for labour trafficking which is the predominant form of trafficking in Qatar.",
        "source": "US Department of State — TIP Report 2023: Qatar Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "MY",
        "title": "US TIP Report — Malaysia: Prosecution and Protection Data",
        "metric": "Malaysia trafficking enforcement statistics",
        "value": "284 investigations, 166 prosecutions, 42 convictions (2022)",
        "year": 2022,
        "summary": "Malaysia reported 284 trafficking investigations, 166 prosecutions, and 42 convictions in 2022 (down from 60 convictions in 2021). Identified 545 trafficking victims. Concerning: the government continued to detain potential trafficking victims in immigration detention centres and deport them without screening. Victim witnesses in ongoing cases cannot work legally, forcing many to remain in government shelters for years. Average length of court proceedings: 3-4 years.",
        "source": "US Department of State — TIP Report 2023: Malaysia Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "TH",
        "title": "US TIP Report — Thailand: Prosecution and Protection Data",
        "metric": "Thailand trafficking enforcement statistics",
        "value": "305 investigations, 244 prosecutions, 198 convictions (2022)",
        "year": 2022,
        "summary": "Thailand reported 305 trafficking investigations, 244 prosecutions, and 198 convictions in 2022. Sentences ranged from 1 to 30 years. Identified 354 trafficking victims. The TIP Report praised Thailand's prosecution numbers but noted: (1) complicit officials rarely prosecuted (only 3 officials convicted), (2) fishing sector convictions declining despite continued exploitation, (3) victim restitution orders rarely enforced. Thailand allocated THB 1.2 billion to anti-trafficking efforts.",
        "source": "US Department of State — TIP Report 2023: Thailand Narrative (Prosecution Section)",
    },
    {
        "type": "advisory",
        "jurisdiction": "PH",
        "title": "US TIP Report — Philippines: Key Recommendations for Maintaining Tier 1",
        "summary": "TIP Report 2023 recommendations for the Philippines to maintain Tier 1: (1) increase convictions of trafficking offenders, especially labour trafficking (currently skewed toward sex trafficking), (2) address online sexual exploitation of children (OSEC) aggressively, (3) enforce recruitment fee regulations against sub-agents, (4) improve inter-agency coordination between DMW, IACAT, and NBI, (5) provide adequate funding for victim services, (6) increase proactive victim identification at overseas labour sites through POLO offices.",
        "source": "US Department of State — TIP Report 2023: Philippines Narrative (Recommendations)",
    },
    {
        "type": "advisory",
        "jurisdiction": "BD",
        "title": "US TIP Report — Bangladesh: Key Recommendations",
        "summary": "TIP Report 2023 recommendations for Bangladesh: (1) increase investigations and prosecutions under the Prevention and Suppression of Human Trafficking Act (2012), (2) vigorously prosecute fraudulent recruitment agents and sub-agents, (3) implement the National Plan of Action on Trafficking (2018-2022, renewed), (4) improve protection for Rohingya refugees who face trafficking, (5) strengthen BMET enforcement capacity, (6) ensure trafficking victims are not penalized for crimes committed under coercion, (7) increase budget for anti-trafficking activities.",
        "source": "US Department of State — TIP Report 2023: Bangladesh Narrative (Recommendations)",
    },
    {
        "type": "advisory",
        "jurisdiction": "NP",
        "title": "US TIP Report — Nepal: Key Recommendations",
        "summary": "TIP Report 2023 recommendations for Nepal: (1) enforce the Foreign Employment Act's recruitment fee caps, (2) investigate and prosecute sub-agents operating below licensed agencies, (3) increase restitution for trafficking victims, (4) implement the National Plan of Action against Trafficking (2011, revised 2017), (5) strengthen the Department of Foreign Employment's regulatory capacity, (6) ensure returning workers have access to reintegration services, (7) address bonded labour (Kamaiya, Haliya, Haruwa-Charuwa) through land reform and alternative livelihoods.",
        "source": "US Department of State — TIP Report 2023: Nepal Narrative (Recommendations)",
    },
    {
        "type": "advisory",
        "jurisdiction": "IN",
        "title": "US TIP Report — India: Key Recommendations",
        "summary": "TIP Report 2023 recommendations for India: (1) pass comprehensive anti-trafficking legislation (Trafficking in Persons Bill), (2) increase identification and prosecution of bonded labour across states (particularly Bihar, Rajasthan, Tamil Nadu, Madhya Pradesh), (3) establish a national victim compensation fund, (4) improve inter-state coordination between police forces, (5) address trafficking of Scheduled Castes and Scheduled Tribes, (6) regulate labour recruitment agencies sending workers abroad, (7) train frontline officials to distinguish trafficking victims from illegal migrants.",
        "source": "US Department of State — TIP Report 2023: India Narrative (Recommendations)",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 8 — Special Topics in TIP Reports
    # ═══════════════════════════════════════════════════════════════════════
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report 2023 — Special Focus: Cyber-Scam Trafficking in Southeast Asia",
        "summary": "The 2023 TIP Report included a special focus on cyber-scam trafficking in Southeast Asia. Key findings: (1) hundreds of thousands of people from across Asia trafficked to compounds in Cambodia, Myanmar, and Laos for forced online fraud operations, (2) victims recruited via social media with promises of legitimate tech jobs, (3) upon arrival: passport confiscation, physical violence, electric shock torture for non-compliance, (4) forced to conduct romance scams, cryptocurrency fraud, and pig-butchering schemes, (5) Chinese organized crime networks operate the compounds, (6) governments of Cambodia and Myanmar unable or unwilling to shut down operations.",
        "source": "US Department of State — TIP Report 2023: Special Topic Section",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Special Focus: Climate Change and Trafficking",
        "summary": "Recent TIP Reports have highlighted the nexus between climate change and human trafficking. Key findings: (1) climate-related displacement increases vulnerability to traffickers, (2) loss of agricultural livelihoods pushes families into debt bondage, (3) natural disasters create opportunities for recruitment fraud, (4) competition for scarce resources increases conflict-driven trafficking, (5) case examples: Bangladeshi climate migrants trafficked to brick kilns; Pacific Island fishers exploited on vessels; drought-displaced Ethiopians trafficked to Gulf states. The 2022 report included a dedicated chapter on this topic.",
        "source": "US Department of State — TIP Reports 2021-2023: Climate and Trafficking Analysis",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Special Focus: Technology-Facilitated Trafficking",
        "summary": "TIP Reports increasingly address technology's role in trafficking: (1) online recruitment through social media (Facebook, TikTok, WhatsApp), (2) cryptocurrency payment for exploitation, (3) encrypted communications to coordinate trafficking, (4) online advertising of forced labour services, (5) digital surveillance tools to control victims. However, technology also aids counter-trafficking: (1) data analytics for pattern detection, (2) satellite imagery of forced labour sites, (3) blockchain for supply chain traceability, (4) AI-based content moderation to detect online exploitation.",
        "source": "US Department of State — TIP Reports 2020-2023: Technology Sections",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Special Focus: Financial Sector and Trafficking",
        "summary": "The TIP Report highlights the financial sector's role in combating trafficking: (1) traffickers generate estimated USD 150 billion annually that flows through financial systems, (2) FinCEN (US) issued advisories on trafficking-related financial red flags, (3) banks increasingly use AI/ML to detect trafficking-linked transactions, (4) the Liechtenstein Initiative's Financial Sector Commission published a Blueprint for Mobilizing Finance Against Slavery and Trafficking (FAST), (5) Wolfsberg Group and FATF guidance on trafficking-related money laundering. Countries with active financial sector engagement receive positive TIP recognition.",
        "source": "US Department of State — TIP Reports 2021-2023 / FAST Initiative / FinCEN Advisory FIN-2020-A008",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Evolving Definition: Forced Labour in Supply Chains",
        "summary": "TIP Reports have increasingly addressed forced labour in global supply chains as a trafficking issue: (1) US CBP Withhold Release Orders (WROs) issued against companies using forced labour (Malaysia gloves, China cotton, Brazil charcoal), (2) the UFLPA (2021) creates a rebuttable presumption of forced labour for goods from Xinjiang, China, (3) EU Corporate Sustainability Due Diligence Directive (2024) requires supply chain monitoring, (4) TIP Report now evaluates countries on their supply chain due diligence enforcement. This represents an expansion from the original TIP focus on individual trafficking to systemic forced labour.",
        "source": "US Department of State — TIP Reports 2020-2023 / US CBP / UFLPA",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "US TIP Report — Victim Identification Rates: Global Gap",
        "metric": "Identified trafficking victims versus estimated total",
        "value": "~115,000 identified vs 27.6 million estimated (0.4%)",
        "year": 2022,
        "summary": "The 2023 TIP Report compiled global victim identification data: approximately 115,000 trafficking victims were identified by governments worldwide in 2022. Given the ILO estimate of 27.6 million in forced labour, this represents identification of only 0.4% of victims. The identification gap is largest for: labour trafficking (versus sex trafficking), men (versus women), and countries without national referral mechanisms. The TIP Report calls this 'the fundamental challenge' of the anti-trafficking field.",
        "source": "US Department of State — TIP Report 2023: Global Victim Identification Data",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "US",
        "title": "US TVPRA Reauthorizations and Expansion",
        "summary": "The TVPA has been reauthorized and expanded multiple times: TVPRA 2003 (added extraterritorial jurisdiction, created civil remedy for victims), TVPRA 2005 (added anti-demand provisions, pilot programmes), TVPRA 2008 (added 'partnerships' as 4th P, expanded child trafficking provisions, required TIP Report to include US self-assessment), TVPRA 2013 (never passed as standalone, provisions included in other legislation). The TVPA and its reauthorizations represent the most comprehensive national anti-trafficking legal framework globally.",
        "source": "TVPA (2000), TVPRA 2003, 2005, 2008 / Congressional Research Service",
    },
    {
        "type": "advisory",
        "jurisdiction": "US",
        "title": "US TIP Report — TIP Heroes and Ambassador-at-Large",
        "summary": "Each TIP Report profiles 'TIP Heroes' — individuals who have demonstrated extraordinary efforts to combat trafficking. The Office to Monitor and Combat Trafficking in Persons (TIP Office) is led by an Ambassador-at-Large. Notable Ambassadors include: John Richmond (2018-2021), Cindy Dyer (2022-present). The TIP Office coordinates US government anti-trafficking policy, manages the TIP Report process, and administers approximately USD 100 million annually in anti-trafficking foreign assistance.",
        "source": "US Department of State — Office to Monitor and Combat Trafficking in Persons",
    },
    {
        "type": "statistic",
        "jurisdiction": "US",
        "title": "US TIP Report — Federal Anti-Trafficking Funding",
        "metric": "Annual US federal spending on anti-trafficking",
        "value": "USD 250+ million (domestic + international)",
        "year": 2023,
        "summary": "The US federal government spends over USD 250 million annually on anti-trafficking efforts: approximately USD 100 million through the TIP Office (foreign assistance), USD 75 million through HHS (domestic victim services), USD 45 million through DOJ (prosecution and task forces), and USD 30 million through DHS (investigations, Blue Campaign). The US is the largest single-country funder of anti-trafficking programmes globally. Funding has been relatively stable since 2015.",
        "source": "US Congressional Research Service — Federal Anti-Trafficking Spending Analysis",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # SECTION 9 — Additional Country Assessments and Enforcement Data
    # ═══════════════════════════════════════════════════════════════════════
    {
        "type": "advisory",
        "jurisdiction": "SG",
        "title": "US TIP Report — Singapore: Tier History",
        "summary": "Singapore TIP tier history: Tier 2 Watch List (2010-2011), Tier 2 (2012-2023). Singapore stabilized at Tier 2 after enacting the Prevention of Human Trafficking Act (2014). The TIP Report consistently notes Singapore's institutional capacity but criticizes the exclusion of domestic workers from the Employment Act, legal deductions from worker salaries for agency fees, and the limited number of trafficking prosecutions relative to the size of the migrant workforce (approximately 1.4 million foreign workers).",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "HK",
        "title": "US TIP Report — Hong Kong: Tier History and Lack of Standalone Legislation",
        "summary": "Hong Kong TIP tier history: Tier 2 (2010-2018), Tier 2 Watch List (2019-2020), Tier 2 (2021-2023). Hong Kong's temporary downgrade reflected the failure to enact standalone anti-trafficking legislation. The TIP Report consistently recommends Hong Kong: (1) enact comprehensive trafficking legislation, (2) abolish the two-week rule for terminated domestic helpers, (3) enforce agency fee caps, (4) increase prosecutions. Despite being one of the world's largest employers of foreign domestic workers, Hong Kong has no dedicated anti-trafficking law.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "JP",
        "title": "US TIP Report — Japan: Tier History and TITP Reform Imperative",
        "summary": "Japan TIP tier history: Tier 2 Watch List (2004), Tier 2 (2005-2023). Japan has remained on Tier 2 for nearly two decades. The TIP Report has consistently cited the Technical Intern Training Program (TITP) as the primary concern: inability to change employers creates dependency, high recruitment fees from Vietnamese and Chinese agencies, and OTIT inspections are insufficient. Japan announced in 2023 a plan to replace TITP with a new Specified Skilled Worker (SSW) system allowing job changes, which the TIP Report welcomed.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "TW",
        "title": "US TIP Report — Taiwan: Tier History and Distant-Water Fishing Concerns",
        "summary": "Taiwan TIP tier history: Tier 2 (2001-2009), Tier 1 (2010-2023 with brief Tier 2 in 2014-2015). Taiwan's temporary Tier 2 placement (2014-2015) was due to inadequate response to forced labour on fishing vessels. Taiwan's distant-water fishing fleet is one of the world's largest, and Indonesian, Philippine, and Vietnamese crew members face extreme exploitation: 18-hour shifts, document confiscation, physical violence, and wages below agreed amounts. Taiwan strengthened monitoring and increased fishing vessel inspections to regain Tier 1.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "statistic",
        "jurisdiction": "AE",
        "title": "US TIP Report — UAE: Prosecution and Protection Data",
        "metric": "UAE trafficking enforcement statistics",
        "value": "130 investigations, 80 prosecutions, 45 convictions (2022)",
        "year": 2022,
        "summary": "The UAE reported 130 trafficking investigations, 80 prosecutions, and 45 convictions in 2022. Sentences ranged from 1 year to life imprisonment. The government identified 289 trafficking victims and referred them to shelters and services. The Ewa'a shelter system provided comprehensive services including legal aid, psychosocial support, and temporary residence permits. However, the TIP Report noted concerns about misidentification of labour trafficking victims as immigration violators, leading to deportation rather than protection.",
        "source": "US Department of State — TIP Report 2023: UAE Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "KW",
        "title": "US TIP Report — Kuwait: Prosecution and Protection Data",
        "metric": "Kuwait trafficking enforcement statistics",
        "value": "25 investigations, 12 prosecutions, 6 convictions (2022)",
        "year": 2022,
        "summary": "Kuwait reported 25 trafficking investigations, 12 prosecutions, and 6 convictions in 2022. Identified 124 trafficking victims. The government operated two shelters for trafficking victims. Key concerns: (1) the vast majority of Kuwait's 700,000 domestic workers remain outside the formal victim identification process, (2) absconder reporting by employers is used to criminalize workers who flee exploitation, (3) labour courts are inaccessible to most domestic workers. TIP Report recommended that Kuwait screen all absconders for trafficking indicators.",
        "source": "US Department of State — TIP Report 2023: Kuwait Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "US TIP Report — Singapore: Prosecution and Protection Data",
        "metric": "Singapore trafficking enforcement statistics",
        "value": "23 investigations, 10 prosecutions, 8 convictions (2022)",
        "year": 2022,
        "summary": "Singapore reported 23 trafficking investigations, 10 prosecutions, and 8 convictions in 2022. Identified 57 trafficking victims. Convictions included sentences of 3-14 years imprisonment. The government's Inter-Agency Taskforce on Trafficking in Persons coordinates response. The TIP Report noted: Singapore's legal framework is adequate but victim identification remains insufficient — many potential trafficking victims among the 250,000+ domestic workers and 300,000+ construction workers are not proactively screened.",
        "source": "US Department of State — TIP Report 2023: Singapore Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "JP",
        "title": "US TIP Report — Japan: Prosecution and Protection Data",
        "metric": "Japan trafficking enforcement statistics",
        "value": "37 investigations, 22 prosecutions, 12 convictions (2022)",
        "year": 2022,
        "summary": "Japan reported 37 trafficking investigations, 22 prosecutions, and 12 convictions in 2022. Identified 42 trafficking victims (predominantly sex trafficking). The extremely low identification of labour trafficking victims is notable given the 340,000+ TITP trainees. The TIP Report noted: OTIT (Organization for Technical Intern Training) conducted 10,000+ workplace inspections but identified no trafficking victims, suggesting inspectors are not trained in victim identification. Japan allocated JPY 650 million to anti-trafficking.",
        "source": "US Department of State — TIP Report 2023: Japan Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "KR",
        "title": "US TIP Report — South Korea: Prosecution and Protection Data",
        "metric": "South Korea trafficking enforcement statistics",
        "value": "195 investigations, 108 prosecutions, 82 convictions (2022)",
        "year": 2022,
        "summary": "South Korea reported 195 trafficking investigations, 108 prosecutions, and 82 convictions in 2022. Identified 206 trafficking victims. South Korea's conviction numbers are among the highest in Asia, contributing to its Tier 1 status. The EPS system processes approximately 50,000 workers annually with government oversight. Remaining gaps: E-6 entertainment visa holders face exploitation, and agricultural EPS workers in remote areas have limited access to complaint mechanisms.",
        "source": "US Department of State — TIP Report 2023: South Korea Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "PH",
        "title": "US TIP Report — Philippines: Prosecution and Protection Data",
        "metric": "Philippines trafficking enforcement statistics",
        "value": "425 investigations, 245 prosecutions, 143 convictions (2022)",
        "year": 2022,
        "summary": "The Philippines reported 425 trafficking investigations, 245 prosecutions, and 143 convictions in 2022. Identified 872 trafficking victims. IACAT coordinates national anti-trafficking response. The Philippines has one of the strongest prosecution records among source countries. Challenges: online sexual exploitation of children (OSEC) increased 600% during COVID (DOJ-OOC data); some local officials complicit in trafficking; conviction rates for labour trafficking remain lower than sex trafficking.",
        "source": "US Department of State — TIP Report 2023: Philippines Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "US TIP Report — Bangladesh: Prosecution and Protection Data",
        "metric": "Bangladesh trafficking enforcement statistics",
        "value": "280 investigations, 175 prosecutions, 52 convictions (2022)",
        "year": 2022,
        "summary": "Bangladesh reported 280 trafficking investigations, 175 prosecutions, and 52 convictions in 2022. Identified 1,180 trafficking victims. The Prevention and Suppression of Human Trafficking Act (2012) provides penalties of 5 years to death. Key concern: the vast majority of prosecutions address sex trafficking; labour trafficking by recruitment agents is rarely prosecuted despite being the dominant form. Rohingya refugees in Cox's Bazar: 145 trafficking cases identified among the 1 million refugee population.",
        "source": "US Department of State — TIP Report 2023: Bangladesh Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "IN",
        "title": "US TIP Report — India: Prosecution and Protection Data",
        "metric": "India trafficking enforcement statistics",
        "value": "4,200+ investigations, 2,500+ prosecutions, 1,115 convictions (2022)",
        "year": 2022,
        "summary": "India reported over 4,200 trafficking investigations, 2,500+ prosecutions, and 1,115 convictions in 2022 — the highest absolute conviction numbers globally. The majority of cases involve sex trafficking and child trafficking. Bonded labour prosecutions remain far below the estimated millions in bondage. Anti-Human Trafficking Units (AHTUs) operate in 330+ districts. Key gap: inter-state trafficking is poorly investigated due to jurisdictional coordination failures between state police forces.",
        "source": "US Department of State — TIP Report 2023: India Narrative (Prosecution Section)",
    },
    {
        "type": "advisory",
        "jurisdiction": "ID",
        "title": "US TIP Report — Indonesia: Tier History",
        "summary": "Indonesia TIP tier history: Tier 3 (2001-2005), Tier 2 Watch List (2006-2009), Tier 2 (2010-2023). Indonesia's upgrade from Tier 3 reflected passage of the Anti-Trafficking in Persons Law (2007) and establishment of the Task Force for the Prevention and Handling of Trafficking in Persons. Persistent concerns: zero-cost migration principle violated in practice, fishing crew exploitation on distant-water vessels, and palm oil sector child labour. BNP2MI (est. 2017) replaced BNP2TKI as the primary regulatory body.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "MM",
        "title": "US TIP Report — Myanmar: Tier History and Post-Coup Deterioration",
        "summary": "Myanmar TIP tier history: Tier 2 Watch List (2001-2015), Tier 2 (2016-2020), Tier 3 (2021-2023). Myanmar's brief Tier 2 period (2016-2020) coincided with the quasi-civilian government. The 2021 military coup reversed all progress: forced labour by the military resumed at scale, anti-trafficking mechanisms collapsed, cross-border trafficking to China and Thailand surged, and the ILO liaison officer mechanism stopped functioning. TIP Report documented military use of forced labour as systematic, including forced child soldiering.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "VN",
        "title": "US TIP Report — Vietnam: Tier History and State Labour Export Concerns",
        "summary": "Vietnam TIP tier history: Tier 2 Watch List (2004-2008), Tier 2 (2009-2016), Tier 2 Watch List (2017-2023). Vietnam's Watch List placement reflects: (1) state-linked labour export companies (DOLAB-licensed) charge excessive fees, (2) limited investigations into state-company-facilitated trafficking, (3) Vietnamese workers in UK, Europe, and Middle East face exploitation, (4) the government provides vocational training but insufficient support for returned trafficking victims. TIP Report has consistently recommended: investigate state-linked agencies and reduce recruitment fees.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "ET",
        "title": "US TIP Report — Ethiopia: Tier History and Deployment Ban Impact",
        "summary": "Ethiopia TIP tier history: Tier 2 Watch List (2001-2011), Tier 2 (2012-2023). Ethiopia's improvement followed the 2012 Anti-Trafficking Proclamation (No. 909/2015, replacing Proclamation 104/2000). Notable: Ethiopia imposed a complete ban on overseas labour migration (2013-2018), which paradoxically increased irregular migration and trafficking. When the ban was lifted, the government introduced bilateral agreements with Saudi Arabia and UAE requiring minimum wages, contract verification, and pre-departure training. TIP Report recommended: strengthen bilateral agreement enforcement.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "NG",
        "title": "US TIP Report — Nigeria: Tier History and NAPTIP Institutional Capacity",
        "summary": "Nigeria TIP tier history: Tier 2 Watch List (2004-2007), Tier 2 (2008-2012), Tier 2 Watch List (2013-2014), Tier 2 (2015-2023). NAPTIP (National Agency for the Prohibition of Trafficking in Persons, est. 2003) is one of Africa's strongest anti-trafficking institutions. NAPTIP operates 10 shelters, has prosecutorial authority, and conducts awareness campaigns. Challenges: 'baby factories', exploitation of Almajiri children (Quranic school students), and trafficking to Libya/Europe. Nigeria has been a Tier 2 anchor for West Africa.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "KE",
        "title": "US TIP Report — Kenya: Tier History and Refugee Vulnerability",
        "summary": "Kenya TIP tier history: Tier 2 Watch List (2006-2008), Tier 2 (2009-2023). Kenya's Counter-Trafficking in Persons Act (2010) and establishment of a National Assistance Trust Fund for Victims improved its standing. Key concerns: (1) Kenyan domestic workers trafficked to Gulf states (particularly Saudi Arabia) through irregular channels, (2) Somali and South Sudanese refugees in Dadaab and Kakuma camps face trafficking, (3) internal child trafficking for domestic work and commercial sexual exploitation. TIP Report recommended: increase Gulf-corridor enforcement and protect refugee populations.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "PK",
        "title": "US TIP Report — Pakistan: Tier History and Bonded Labour Challenge",
        "summary": "Pakistan TIP tier history: Tier 2 Watch List (2004-2009), Tier 2 (2010-2017), Tier 2 Watch List (2018-2023). The recurring Watch List placement reflects Pakistan's enormous bonded labour problem: an estimated 2-4 million people in brick kiln bondage alone, with multigenerational debt inherited by children. The Bonded Labour System (Abolition) Act (1992) is largely unenforced. Pakistan's federal structure complicates enforcement — anti-trafficking is primarily a provincial responsibility. TIP Report recommended: implement the Supreme Court's 2014 directions on bonded labour.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "LK",
        "title": "US TIP Report — Sri Lanka: Tier History and Economic Crisis Impact",
        "summary": "Sri Lanka TIP tier history: Tier 2 Watch List (2007-2008), Tier 2 (2009-2021), Tier 2 Watch List (2022-2023). Sri Lanka's downgrade coincided with the 2022 economic crisis: (1) desperation migration through irregular channels surged, (2) trafficking of Sri Lankan women to Gulf states for domestic work increased, (3) the government's capacity to provide victim services declined due to fiscal constraints, (4) recruitment oversight weakened as agencies took advantage of demand. Sri Lanka Bureau of Foreign Employment (SLBFE) regulates deployment but enforcement has deteriorated.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "KH",
        "title": "US TIP Report — Cambodia: Tier History and Cyber-Scam Crisis",
        "summary": "Cambodia TIP tier history: Tier 2 Watch List (2003-2008), Tier 2 (2009-2013), Tier 2 Watch List (2014-2018), Tier 2 (2019-2021), Tier 2 Watch List (2022-2023). Cambodia's most recent downgrade reflects the unprecedented cyber-scam trafficking crisis: tens of thousands of people (from China, Vietnam, Thailand, Myanmar, Indonesia, Taiwan, and as far as Africa and South America) trafficked to compounds in Sihanoukville, Poipet, and Koh Kong for forced online fraud. The Cambodian government's response was initially slow, raising concerns about official complicity.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Tier 3 Countries: Full 2023 List",
        "summary": "Countries ranked Tier 3 in the 2023 TIP Report: Afghanistan, Belarus, Burma (Myanmar), China, Cuba, Curacao, Eritrea, Guinea-Bissau, Iran, Macau, Nicaragua, North Korea, Russia, Sint Maarten, South Sudan, Syria, Turkmenistan, and Venezuela. Common characteristics: governments actively use forced labour (state-imposed), actively facilitate trafficking, have no meaningful anti-trafficking efforts, or criminalize victims. Tier 3 triggers potential sanctions including withholding of non-humanitarian foreign assistance.",
        "source": "US Department of State — TIP Report 2023: Tier Placements",
    },
    {
        "type": "advisory",
        "jurisdiction": "CN",
        "title": "US TIP Report — China: Tier 3 Assessment (2023)",
        "summary": "China was ranked Tier 3 in 2023 (downgraded from Tier 2 Watch List in 2017). Key findings: (1) state-imposed forced labour in Xinjiang through 'vocational training' and 'surplus labour' programmes affecting Uyghurs and other Turkic Muslims, (2) forced labour in state-sponsored labour transfer programmes across provinces, (3) Chinese companies involved in overseas forced labour (particularly in fishing and construction), (4) limited cooperation with international monitoring, (5) zero acknowledgment of Xinjiang forced labour. The UFLPA (2021) presumes all goods from Xinjiang are produced with forced labour.",
        "source": "US Department of State — TIP Report 2023: China Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "RU",
        "title": "US TIP Report — Russia: Tier 3 Assessment (2023)",
        "summary": "Russia was ranked Tier 3 in 2023 (downgraded from Tier 2 Watch List). Key findings: (1) forced deportation and adoption of Ukrainian children (documented by ICC, which issued arrest warrants), (2) forced labour of Central Asian migrant workers in construction, agriculture, and service sectors, (3) North Korean workers exploited in Russian Far East, (4) sexual exploitation of women from Russia, Moldova, and Central Asia, (5) the government made no meaningful effort to address trafficking and actively obstructed international accountability for Ukrainian child deportations.",
        "source": "US Department of State — TIP Report 2023: Russia Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report 2023 — Special Focus: Forced Labour in State-Sponsored Programmes",
        "summary": "The 2023 TIP Report dedicated analysis to state-sponsored forced labour programmes: (1) China — Xinjiang 'vocational training', (2) North Korea — overseas worker deployment, (3) Eritrea — indefinite national service, (4) Turkmenistan — forced cotton harvesting, (5) Belarus — compulsory labour decrees, (6) Cuba — overseas medical missions (doctors report coercive conditions, salary confiscation), (7) Russia — forced deportation of Ukrainian civilians. The report argued that state-imposed forced labour is growing and requires different policy responses than private-sector trafficking.",
        "source": "US Department of State — TIP Report 2023: State-Sponsored Forced Labour Analysis",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Regional Comparison: Gulf Cooperation Council States",
        "summary": "TIP Report 2023 tier rankings for GCC states: Bahrain (Tier 2), UAE (Tier 2), Kuwait (Tier 2 Watch List), Oman (Tier 2 Watch List), Qatar (Tier 2 Watch List), Saudi Arabia (Tier 2 Watch List). No GCC state has achieved Tier 1. Common challenges across the GCC: kafala system elements persist, domestic workers remain most vulnerable, prosecution rates are low relative to migrant worker populations (20+ million across GCC), and recruitment fee charging continues. Bahrain and UAE are assessed as most progressive; Kuwait and Qatar show most reform momentum but implementation gaps remain.",
        "source": "US Department of State — TIP Report 2023: GCC Country Narratives (Comparative)",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Regional Comparison: ASEAN Member States",
        "summary": "TIP Report 2023 tier rankings for ASEAN states: Philippines (Tier 1), Singapore (Tier 2), Thailand (Tier 2), Indonesia (Tier 2), Malaysia (Tier 2 Watch List), Vietnam (Tier 2 Watch List), Cambodia (Tier 2 Watch List), Laos (Tier 2 Watch List), Myanmar (Tier 3), Brunei (Tier 2 Watch List). Only the Philippines achieved Tier 1. ASEAN's ACTIP (2015) provides a regional framework but implementation is inconsistent. The cyber-scam trafficking crisis affecting Cambodia, Myanmar, and Laos represents a new regional challenge requiring coordinated response.",
        "source": "US Department of State — TIP Report 2023: ASEAN Country Narratives (Comparative)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "US",
        "title": "US TIP Report — Relationship to CBP Withhold Release Orders (WROs)",
        "summary": "TIP Report findings inform US Customs and Border Protection (CBP) enforcement actions. CBP's Withhold Release Orders (WROs) block importation of goods produced with forced labour under Section 307 of the Tariff Act (1930). Notable WROs linked to TIP Report findings: Top Glove (Malaysia, rubber gloves, 2020), Supermax (Malaysia, gloves, 2021), FGV Holdings (Malaysia, palm oil, 2020), Xinjiang cotton producers (China, 2021), and Natchi Apparel (India, garments, 2022). WROs have become a powerful enforcement mechanism complementing diplomatic TIP Report pressure.",
        "source": "US CBP / Forced Labor Enforcement Task Force (FLETF) / US Department of State",
    },
    {
        "type": "advisory",
        "jurisdiction": "OM",
        "title": "US TIP Report — Oman: Tier History",
        "summary": "Oman TIP tier history: Tier 3 (2005-2007), Tier 2 Watch List (2008-2013), Tier 2 (2014-2017), Tier 2 Watch List (2018-2023). Oman has struggled to sustain anti-trafficking momentum. The Royal Decree 126/2008 (Anti-Trafficking Law) provides adequate penalties (3-15 years), but enforcement is minimal. Key concerns: domestic workers under kafala, construction workers from South Asia and Africa face exploitation, and labour inspection capacity is limited. Oman hosts approximately 1.6 million foreign workers in a total population of 4.5 million.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "BH",
        "title": "US TIP Report — Bahrain: Tier History and the LMRA Model",
        "summary": "Bahrain TIP tier history: Tier 2 Watch List (2005-2007), Tier 2 (2008-2023). Bahrain has been the most stable Tier 2 country in the Gulf. Key institution: the Labour Market Regulatory Authority (LMRA, est. 2006) regulates work permits, conducts inspections, and manages the flexi-permit system. The TIP Report regularly cites Bahrain's relatively higher conviction rate per capita as a positive. Remaining concerns: domestic workers under kafala, flexi-permit workers lacking full labour protections, and recruitment fee charging.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "LB",
        "title": "US TIP Report — Lebanon: Tier History and Economic Crisis",
        "summary": "Lebanon TIP tier history: Tier 2 Watch List (2005-2008), Tier 2 (2009-2019), Tier 2 Watch List (2020-2023). Lebanon's downgrade reflects the compound impact of: (1) the 2019 economic crisis (currency lost 90%+ of value), (2) the 2020 Beirut explosion, (3) COVID-19. Consequences for migrant workers: employers abandoned workers, wages in LBP became worthless, shelters overwhelmed, and irregular departures increased. Lebanon's kafala system remains one of the most restrictive globally, with zero trafficking convictions in 2022.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "advisory",
        "jurisdiction": "JO",
        "title": "US TIP Report — Jordan: Tier History and QIZ Labour Conditions",
        "summary": "Jordan TIP tier history: Tier 2 Watch List (2007-2008), Tier 2 (2009-2023). Jordan's Tier 2 is sustained by: the Anti-Human Trafficking Law (2009), national anti-trafficking committee, and the Better Work Jordan programme in QIZ factories. Key concern: 75,000+ garment workers (predominantly South Asian women) in QIZs face exploitation including forced overtime, wage theft, and sexual harassment. Syrian refugees (660,000 registered) face labour exploitation in agriculture, construction, and the informal sector.",
        "source": "US Department of State — TIP Reports Historical Rankings",
    },
    {
        "type": "statistic",
        "jurisdiction": "ID",
        "title": "US TIP Report — Indonesia: Prosecution and Protection Data",
        "metric": "Indonesia trafficking enforcement statistics",
        "value": "215 investigations, 160 prosecutions, 75 convictions (2022)",
        "year": 2022,
        "summary": "Indonesia reported 215 trafficking investigations, 160 prosecutions, and 75 convictions in 2022. Identified 410 trafficking victims. Key enforcement trends: (1) sex trafficking prosecutions dominate (65% of cases), (2) labour trafficking prosecutions increasing but remain insufficient, (3) fishing sector trafficking rarely prosecuted, (4) BNP2MI enforcement against non-compliant agencies improving. Indonesia's conviction rate per reported case is relatively high, but the total number of investigations is low given the 9+ million Indonesians working abroad.",
        "source": "US Department of State — TIP Report 2023: Indonesia Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "US TIP Report — Nepal: Prosecution and Protection Data",
        "metric": "Nepal trafficking enforcement statistics",
        "value": "185 investigations, 95 prosecutions, 35 convictions (2022)",
        "year": 2022,
        "summary": "Nepal reported 185 trafficking investigations, 95 prosecutions, and 35 convictions in 2022. Identified 430 trafficking victims. The Human Trafficking and Transportation (Control) Act (2007) provides penalties of 10-20 years. Key gap: the vast majority of prosecutions involve internal sex trafficking; labour trafficking by overseas recruitment agents is rarely prosecuted despite being the most prevalent form affecting Nepali workers. The Department of Foreign Employment revoked 45 agency licenses in 2022 but criminal prosecution of agents is rare.",
        "source": "US Department of State — TIP Report 2023: Nepal Narrative (Prosecution Section)",
    },
    {
        "type": "statistic",
        "jurisdiction": "LK",
        "title": "US TIP Report — Sri Lanka: Prosecution and Protection Data",
        "metric": "Sri Lanka trafficking enforcement statistics",
        "value": "52 investigations, 28 prosecutions, 8 convictions (2022)",
        "year": 2022,
        "summary": "Sri Lanka reported 52 trafficking investigations, 28 prosecutions, and 8 convictions in 2022 (down from 15 convictions in 2021). Identified 85 trafficking victims. The declining prosecution numbers contributed to Sri Lanka's downgrade to Tier 2 Watch List. Key context: the 2022 economic crisis diverted law enforcement resources from anti-trafficking, and the SLBFE's capacity to regulate overseas recruitment agencies deteriorated. Courts face a backlog of trafficking cases averaging 2-3 years to disposition.",
        "source": "US Department of State — TIP Report 2023: Sri Lanka Narrative (Prosecution Section)",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "US TIP Report — Tier 1 Countries: Full 2023 List",
        "summary": "Countries ranked Tier 1 in 2023 TIP Report (approximately 30): Australia, Austria, The Bahamas, Belgium, Canada, Chile, Colombia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Georgia, Germany, Israel, Italy, Japan (disputed), Lithuania, Luxembourg, The Netherlands, New Zealand, Norway, Philippines, Poland, Portugal, South Korea, Spain, Sweden, Switzerland, Taiwan, United Kingdom, United States. Tier 1 countries fully meet the TVPA minimum standards. Most are developed democracies; the Philippines, Georgia, and South Korea are notable exceptions to this pattern.",
        "source": "US Department of State — TIP Report 2023: Tier Placements",
    },
]
