"""Visa and sponsorship systems, kafala variants, and work permit mechanisms."""

VISA_SYSTEM_FACTS: list[dict] = [
    # ── Kafala System Variants ───────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "SA",
        "title": "Saudi Arabia Kafala System — Current Status",
        "summary": "Kafala reformed March 2021: workers can transfer employers without sponsor consent (after 1 year or unpaid wages for 3+ months), exit/re-entry visa no longer requires sponsor approval, extended exit visa validity. Domestic workers still under stricter rules. Musaned platform for domestic worker contracts. In practice, many employers still confiscate passports and threaten absconding charges.",
        "source": "Saudi Ministry of Human Resources / Migrant-Rights.org",
    },
    {
        "type": "advisory",
        "jurisdiction": "QA",
        "title": "Qatar Kafala System — Post-Reform Status",
        "summary": "Major reforms 2020-2021: exit permit abolished (Law 13/2018 implemented), employer NOC removed for job changes, minimum wage QAR 1,000 (non-discriminatory). Workers can change jobs without employer consent after notice period. LDRC for disputes. In practice: some employers still obstruct transfers, file absconding charges, or refuse to sign cancellation documents.",
        "source": "Qatar Ministry of Labour / ILO",
    },
    {
        "type": "advisory",
        "jurisdiction": "AE",
        "title": "UAE Sponsorship System — Reforms and Gaps",
        "summary": "UAE reforms: 6-month grace period after contract termination to find new employer (2022), golden visa for skilled workers, freelance visa options. However: domestic workers still require employer NOC for transfer in some emirates, absconding law still active, employer can cancel visa unilaterally. Free zone workers have different rules than mainland workers. 88% of population are foreign nationals.",
        "source": "UAE MOHRE / Migrant-Rights.org",
    },
    {
        "type": "advisory",
        "jurisdiction": "KW",
        "title": "Kuwait Kafala System — Partial Reforms",
        "summary": "Kuwait Domestic Workers Law 68/2015 provides some protections: 12-hour workday limit, weekly rest day, 30 days annual leave. But: no minimum wage enforcement mechanism, domestic workers must obtain sponsor permission to leave country, transfer requires employer NOC (unless abuse proven). Multiple origin countries have deployment bans due to abuse (PH, ET, ID intermittently).",
        "source": "Kuwait Public Authority of Manpower",
    },
    {
        "type": "advisory",
        "jurisdiction": "LB",
        "title": "Lebanon Kafala System — Unreformed",
        "summary": "Lebanon kafala largely unreformed. Domestic workers excluded from Labour Code. Employer controls worker's legal status. Worker must obtain employer consent to leave, change employer, or exit country. 250,000+ domestic workers (Ethiopian, Filipino, Bangladeshi, Sri Lankan). NGO-drafted unified contract (2009) rarely enforced. Economic crisis (2020+) led to mass abandonment of workers by employers.",
        "source": "ILO / Anti-Racism Movement Lebanon / HRW",
    },
    {
        "type": "advisory",
        "jurisdiction": "JO",
        "title": "Jordan Kafala System — Unified Contract",
        "summary": "Jordan Regulation 90/2009 provides some domestic worker protections: unified employment contract, 10-hour workday, weekly rest, 14 days annual leave. But: tied to employer sponsorship, no minimum wage, limited enforcement. 50,000+ domestic workers (Filipino, Sri Lankan, Indonesian, Bangladeshi). Anti-trafficking law (2009) exists but few trafficking prosecutions.",
        "source": "Jordan Ministry of Labour / Tamkeen",
    },
    {
        "type": "advisory",
        "jurisdiction": "OM",
        "title": "Oman Kafala System — Limited Visibility",
        "summary": "Oman kafala system largely intact. 1.9M foreign workers (44% of population). Royal Decree 2003 governs labour. Workers need employer NOC for transfer and exit. No minimum wage for migrant workers. Limited labour inspection capacity. Complaints can be filed with MoMP but process is slow. Fewer international studies compared to other Gulf states.",
        "source": "Oman Ministry of Manpower / US TIP Report",
    },
    {
        "type": "advisory",
        "jurisdiction": "BH",
        "title": "Bahrain Flexi-Permit System — Alternative to Kafala",
        "summary": "Bahrain's flexi-permit (2017) allows migrant workers to self-sponsor: BHD 300/year (USD 795). Workers can work for any employer, change jobs freely, and sponsor themselves without employer. 70,000+ workers on flexi-permits. Criticized: workers must pay own visa costs, no employer-provided housing/benefits, creates two-tier system. Still, most progressive Gulf reform.",
        "source": "Bahrain LMRA",
    },
    # ── Specific Visa Mechanisms ─────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "HK",
        "title": "Hong Kong Two-Week Rule — Vulnerability Creation",
        "summary": "Foreign domestic helpers (FDHs) must find new employer or leave Hong Kong within 14 days of contract termination. Creates extreme vulnerability: workers accept abusive conditions rather than risk 14-day clock, employers use termination threat as control. Workers who file complaints may lose immigration status before case resolved. Advocacy groups call for abolition or extension to 3 months.",
        "source": "Justice Centre Hong Kong / Mission for Migrant Workers",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Absconding Laws as Worker Control Mechanism",
        "summary": "Gulf states criminalize workers who leave employers without permission ('absconding'). Employers can file absconding report, making worker immediately undocumented. Penalties: fines, detention, deportation ban. Used to: retaliate against workers who complain, prevent workers from leaving abusive situations, avoid paying end-of-service benefits. QA and SA reformed but charges still common in KW, OM, LB.",
        "source": "ILO / Migrant-Rights.org / Amnesty International",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Visa Trading and Free Visa Exploitation",
        "summary": "'Free visa' (SA: tasheerat hurra): employer obtains work visas with no actual job, sells to workers for USD 1,000-5,000. Worker arrives, has visa but no employer. Must find own work while technically illegal. Employer collects annual 'renewal fee.' If caught, worker is deported; visa trader rarely prosecuted. Creates large undocumented workforce. Estimated 500,000+ workers on 'free visas' in Saudi Arabia alone.",
        "source": "Saudi Ministry of Labour / ILO",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Visit Visa Conversion as Trafficking Pathway",
        "summary": "Workers enter destination on tourist/visit visa, then 'converted' to work visa by employer. During conversion period (weeks to months), worker has no legal work status, no protections, no contract. Employer exploits limbo status. Common in AE, KW, OM. If conversion fails, worker becomes undocumented but already indebted. Pattern also documented in UK (student visa exploitation).",
        "source": "ILO / IOM / Anti-trafficking organizations",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Overstay Criminalization and Deportation Vulnerability",
        "summary": "Workers whose visas expire (often due to employer failure to renew) face criminal penalties: fines (accumulating daily), detention, deportation, re-entry bans. Creates leverage for employers: threat of reporting undocumented worker to authorities. Amnesty programs (SA: periodic campaigns, MY: rehiring program) offer temporary relief but workers must pay fines and exit. Cycle of irregular status and exploitation.",
        "source": "IOM / Migrant-Rights.org",
    },
    # ── Work Permit Comparison ───────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "KR",
        "title": "South Korea Employment Permit System (EPS) — Model Program",
        "summary": "Government-to-government recruitment (no private brokers). Transparent fees (USD 900-1,000 total). Workers can change employer up to 3 times. 4 years 10 months maximum stay. 16 sending countries. 60,000 annual quota. Criticized for: limited workplace mobility, employer consent required for some transfers, no path to permanent residency, language test barrier (TOPIK). Still considered international best practice.",
        "source": "Korea HRD Service / ILO",
    },
    {
        "type": "advisory",
        "jurisdiction": "JP",
        "title": "Japan TITP vs SSW — Visa System Comparison",
        "summary": "TITP (Technical Intern Training Program, 1993): 3-5 year placement, cannot change employer, high fees (USD 5,000-10,000 via Vietnamese/Chinese sending orgs), exploitation widely documented. SSW (Specified Skilled Worker, 2019): allows job change within sector, lower fees, 5-year stay, path to SSW-2 (permanent). Japan transitioning TITP→new 'Training and Employment' system (2024+) after decade of criticism.",
        "source": "Japan Ministry of Justice / OTIT / ILO",
    },
    {
        "type": "advisory",
        "jurisdiction": "US",
        "title": "US H-2A/H-2B Temporary Worker Visa Vulnerabilities",
        "summary": "H-2A (agricultural) and H-2B (non-agricultural seasonal) visas tie worker to specific employer. Workers pay USD 1,000-10,000 in recruitment fees to labour contractors despite FLSA prohibition. If fired, must leave US within 30 days. Employer controls housing (H-2A: must provide). Retaliation for complaints = termination = deportation. DOL enforcement limited. 300,000+ H-2A visas/year.",
        "source": "US DOL / Centro de los Derechos del Migrante / Polaris Project",
    },
    {
        "type": "advisory",
        "jurisdiction": "UK",
        "title": "UK Seasonal Worker Visa — Exploitation Patterns",
        "summary": "UK Seasonal Workers Pilot (2019+, expanded to 45,000 visas/year): 6-month visa for agricultural work, tied to licensed sponsor. Workers from non-EU countries pay GBP 500-3,000 in recruitment fees. Tied to specific farm/gangmaster. If placement fails, no alternative employment allowed. Reports of underpayment, excessive accommodation deductions (GBP 50-70/week), and lack of guaranteed hours.",
        "source": "GLAA / Focus on Labour Exploitation (FLEX)",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Employer-Tied Housing as Control and Exploitation",
        "summary": "Visa systems requiring employer-provided housing create dependency: worker cannot leave employment without losing housing, employer controls living conditions, housing costs deducted from wages (often inflated). Gulf construction: 8-12 workers per room in labour camps. HK FDHs: must live in employer's home ('live-in requirement'). SG: employer-provided accommodation for work permit holders. Creates 24/7 employer control.",
        "source": "ILO / BWI / Justice Centre Hong Kong",
    },
    {
        "type": "advisory",
        "jurisdiction": "TW",
        "title": "Taiwan Work Permit System and Broker Dependency",
        "summary": "Taiwan Employment Service Act allows migrant workers via licensed brokers. 710,000+ migrant workers (Indonesian, Vietnamese, Filipino, Thai). Workers pay NTD 50,000-150,000 (USD 1,600-4,800) to brokers. 3-year contracts, renewable to 12 years total. Can change employer only under specific conditions. Broker dependency: annual service fees NTD 1,500-1,800/month deducted from salary for entire stay.",
        "source": "Taiwan Ministry of Labor / Serve the People Association",
    },
    {
        "type": "advisory",
        "jurisdiction": "MY",
        "title": "Malaysia Work Permit System — Employer Control",
        "summary": "Malaysia work permits tied to specific employer and sector. Workers cannot change employer without new permit (difficult, expensive). Levy system: employer pays annual levy (MYR 1,850-2,500 depending on sector) but often passes cost to worker via salary deduction. Permit renewal at employer discretion. Large undocumented workforce (2-4M) due to permit barriers. Periodic crackdowns create mass detention.",
        "source": "Malaysia Ministry of Human Resources / Tenaganita",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Passport Confiscation Despite Legal Prohibition",
        "summary": "Passport confiscation illegal in virtually all destination countries yet remains pervasive. SA: Royal Decree prohibits confiscation (penalty SAR 2,000); 90%+ of workers report confiscation. QA: Law prohibits confiscation; 60-70% report confiscation. HK: Immigration Ordinance Cap. 115 §42 criminalizes confiscation; 20-30% of FDHs report confiscation. Enforcement: near-zero prosecutions in any jurisdiction.",
        "source": "ILO / Migrant-Rights.org / National surveys",
    },
]
