"""Australian modern slavery cases, Fair Work enforcement, and Pacific labour mobility."""

AUSTRALIA_CASE_FACTS: list[dict] = [
    # ── Landmark Criminal Cases ────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v Tang [2008] HCA 39 — First High Court Slavery Conviction",
        "summary": "Wei Tang, Melbourne brothel owner, convicted of slavery offences involving five Thai women brought to Australia on contract and tourist visas. Women held in sexual servitude, required to work off debt of AUD 45,000 each through sex work. High Court established the legal test for slavery: the exercise of powers attaching to the right of ownership. Sentenced to 10 years imprisonment (reduced on appeal to 9 years). The first slavery conviction in Australian legal history and the first High Court interpretation of slavery under Division 270 of the Criminal Code Act 1995.",
        "source": "High Court of Australia / Commonwealth DPP",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v Wei Tang — Legal Test for Slavery in Australia",
        "summary": "The High Court in R v Tang established that slavery under s270.1 of the Criminal Code requires proof of the exercise of 'any or all of the powers attaching to the right of ownership' over a person. This includes the power to use a person's labour, control their movement, and effectively reduce them to property. The court rejected the argument that modern slavery requires formal legal ownership. This test has been applied in all subsequent Australian slavery prosecutions.",
        "source": "High Court of Australia [2008] HCA 39",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v Kovacs [2008] — First Labour Trafficking Conviction",
        "summary": "Melita Kovacs convicted in the County Court of Victoria for trafficking Hungarian men to Australia for construction work. Workers recruited in Hungary with promises of high wages and permanent residency. On arrival, passports confiscated, housed in employer-controlled accommodation, wages paid to trafficker. Workers charged inflated airfare and housing costs creating debt bondage. First Australian conviction for labour trafficking (as opposed to sexual exploitation). Demonstrated that developed-country construction sectors are sites of trafficking.",
        "source": "County Court of Victoria / AFP / Commonwealth DPP",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "Commonwealth v David Shuyu Li [2017] — Filipino Worker Exploitation",
        "summary": "David Shuyu Li convicted of forced labour and deceptive recruiting under Division 270-271 of the Criminal Code. Recruited Filipino workers for a Newcastle restaurant through deceptive job offers. Workers paid below minimum wage (AUD 5-8/hour versus AUD 21+ award rate), required to work 14-16 hour days, had passports confiscated, and were threatened with deportation if they complained. Sentenced to 6 years imprisonment. Case demonstrated application of forced labour provisions to hospitality sector exploitation.",
        "source": "Newcastle Local Court / AFP / Commonwealth DPP",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v Netthip [2010] — Thai Massage Worker Sexual Servitude",
        "summary": "Watcharaporn Netthip convicted in NSW District Court for sexual servitude offences against Thai women brought to Sydney on tourist visas to work in massage parlours. Women owed AUD 30,000-50,000 debt each. Required to perform sexual services to repay debt. Passports confiscated. Workers controlled through threats of exposure to police as visa overstayers. Sentenced to 6 years imprisonment. Case highlighted exploitation in the massage industry beyond traditional brothel settings.",
        "source": "NSW District Court / AFP / Commonwealth DPP",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v McIvor and Tanuchit [2010] — Thai Worker Agricultural Exploitation",
        "summary": "Michael McIvor and his Thai wife Kanokwan Tanuchit convicted of slavery and trafficking offences against Thai workers exploited in their business in Victoria. Workers from Thailand were held in conditions of slavery, subjected to physical abuse, had identity documents confiscated, and were required to work excessive hours without adequate pay. McIvor sentenced to 6 years, Tanuchit to 4 years. Case demonstrated rural and agricultural exploitation patterns.",
        "source": "County Court of Victoria / AFP",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v Dobie [2009] — Pacific Islander Domestic Servitude",
        "summary": "Keith Alan Dobie convicted of slavery offences against a Fijian woman brought to Queensland as a domestic worker. Victim confined to household, worked 16+ hours daily, never paid, physically abused, and told she would be deported if she left. Case was among the first domestic servitude prosecutions in Australia. Sentenced to 4 years imprisonment. Highlighted vulnerability of Pacific Islander women in domestic work arrangements outside formal visa pathways.",
        "source": "Queensland District Court / AFP",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v Trivedi [2014] — Indian Cook Forced Labour",
        "summary": "Chintan Trivedi convicted in Victorian Magistrates Court of forced labour offences against an Indian cook brought to Melbourne on a sponsored 457 visa. Worker was paid AUD 5/hour (instead of contracted AUD 18/hour), worked 80+ hours per week, passport confiscated, and threatened with visa cancellation and deportation if he complained. Case became a template for 457 visa worker exploitation prosecutions. Demonstrated how employer-sponsored visa systems create vulnerability.",
        "source": "Victorian Magistrates Court / AFP",
    },
    # ── Fair Work Ombudsman Enforcement ─────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "7-Eleven Franchise Wage Theft Scandal (2015-2016)",
        "summary": "Four Corners/Fairfax investigation (2015) exposed systematic underpayment of international students at 7-Eleven franchise stores across Australia. Workers (primarily from India, Pakistan, China) paid AUD 10-15/hour (award rate AUD 24+). Workers required to work 50+ hours/week but pay records falsified to show 20 hours (visa limit). Franchisees threatened deportation if workers complained. 7-Eleven established AUD 173 million back-pay program. FWO recovered AUD 150+ million for over 4,000 workers. Multiple franchisees prosecuted.",
        "source": "Fair Work Ombudsman / ABC Four Corners / Fairfax Media",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Fair Work Ombudsman v Caltex — Franchise Underpayment",
        "summary": "FWO investigation (2017-2019) found systematic underpayment across Caltex service station franchises nationally. Workers (international students on 482/500 visas) paid AUD 12-16/hour versus AUD 24+ award rate. Cash-back schemes: workers paid correct rate electronically then required to return cash to franchisee. Caltex assessed AUD 20 million in back-pay liability. FWO pursued franchise model accountability, arguing head franchisors bear responsibility for franchisee labour law compliance.",
        "source": "Fair Work Ombudsman / ABC / The Age",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Horticulture Sector Exploitation — Backpacker and Pacific Islander Workers",
        "summary": "Systematic exploitation in Australian horticulture documented across multiple investigations (2015-2023). Workers (WHM visa holders, Pacific Islanders, undocumented) picking fruit and vegetables paid piece rates below minimum wage (AUD 5-12/hour effective). Labour hire contractors charge workers for transport (AUD 5-10/day), accommodation (AUD 120-200/week in overcrowded share houses), and 'admin fees.' Workers from Pacific Island nations under SWP report better conditions than backpackers but still face debt to agents in home countries. FWO Harvest Trail inquiry (2018) found non-compliance in 44 percent of audited farms.",
        "source": "Fair Work Ombudsman / National Farmers Federation / ABC",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Fair Work Ombudsman v Hu and Ors [2019] — Chinese Restaurant Exploitation",
        "summary": "Federal Circuit Court ordered AUD 486,000 in penalties against Melbourne restaurant operators who underpaid Chinese visa holders working as cooks and waitstaff. Workers paid AUD 8-12/hour for 50+ hour weeks. Threats of visa cancellation used to prevent complaints. Sham contracting arrangements to disguise employment relationship. FWO obtained accessorial liability orders against company directors personally. Case part of broader FWO campaign targeting food services sector exploitation.",
        "source": "Fair Work Ombudsman / Federal Circuit Court",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Meat Processing Worker Exploitation — Visa Worker Underpayment",
        "summary": "Australian meat processing sector employs 15,000+ temporary visa holders (417, 482, Pacific Labour Scheme). FWO and ABCC investigations documented: underpayment of AUD 5-10/hour below award, unpaid overtime, unsafe working conditions (repetitive strain injuries, knife injuries), inadequate PPE, employer-controlled accommodation with excessive deductions. Labour hire companies operate as intermediaries between meatworks and workers, creating accountability gaps. FWO recovered AUD 12 million in back-pay from meat processing sector (2019-2023).",
        "source": "Fair Work Ombudsman / United Workers Union / ABC",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Cleaning Industry Exploitation — Sham Contracting",
        "summary": "Australian cleaning industry widely uses sham contracting to classify workers as independent contractors, denying minimum wage, superannuation, workers compensation, and leave entitlements. Affected workers predominantly from India, China, Nepal, and Philippines on student and temporary visas. FWO and ACTU documented: effective hourly rate AUD 10-15 (versus AUD 24+ as employee), 12-14 hour shifts, provision of own equipment and transport. FWO brought sham contracting proceedings against major cleaning companies contracted to shopping centres, universities, and government buildings.",
        "source": "Fair Work Ombudsman / ACTU / Unions NSW",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Nail Salon Exploitation — Vietnamese Worker Underpayment",
        "summary": "FWO investigations (2018-2023) documented systematic underpayment in nail salons across Sydney, Melbourne, and Brisbane. Workers (primarily Vietnamese women on temporary visas) paid AUD 8-14/hour for 10-12 hour days. Sham contracting and cash payments to avoid record-keeping. Workers exposed to toxic chemicals without PPE. FWO conducted Operation Vanguard (2019): 80+ nail salons audited, 65 percent non-compliant. Penalties limited by small business size. Workers deterred from complaints by fear of visa cancellation.",
        "source": "Fair Work Ombudsman / SBS Vietnamese / The Guardian",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Construction Sector Exploitation — 457/482 Visa Worker Abuse",
        "summary": "Temporary skilled visa holders (subclass 457, replaced by 482 in 2018) in construction exploited through: wages below nominated occupation rate, employer requiring workers to refund portion of salary, employers failing to provide contracted hours then threatening visa cancellation, workers charged for accommodation and transport. Construction unions (CFMMEU) documented cases of workers on building sites earning AUD 15-20/hour while Australians on same site earned AUD 40+. FWO and ABF joint operations identified 500+ non-compliant sponsors (2019-2022).",
        "source": "Fair Work Ombudsman / CFMMEU / Australian Border Force",
    },
    {
        "type": "statistic",
        "jurisdiction": "AU",
        "title": "Fair Work Ombudsman — Enforcement Statistics (2022-2023)",
        "summary": "FWO annual report 2022-2023: recovered AUD 532 million in unpaid wages and entitlements for workers. Commenced 75 litigations. Secured AUD 18.5 million in court-ordered penalties. Completed 24,000+ dispute resolutions. Visa holder workers accounted for 17 percent of all complaints but received 23 percent of recovered wages. Top non-compliant sectors: food services (22 percent), retail (15 percent), accommodation (12 percent), agriculture (10 percent), cleaning (8 percent). FWO operates Migrant Worker Taskforce established in 2016.",
        "source": "Fair Work Ombudsman Annual Report 2022-2023",
    },
    # ── Pacific Labour Schemes ─────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Pacific Labour Scheme (PLS) — Exploitation Cases",
        "summary": "Australia's Pacific Labour Scheme (renamed Pacific Australia Labour Mobility, PALM, in 2022) brings workers from Pacific Island Countries and Timor-Leste for up to 4 years in low/semi-skilled sectors. By 2023, 35,000 workers under PALM. Documented exploitation: excessive accommodation deductions (AUD 150-250/week for shared rooms), labour hire intermediaries taking 15-25 percent of wages, insufficient working hours (workers guaranteed 30 hours but sometimes receive 15-20), isolation in rural areas, inadequate pastoral care. PALM scheme redesigned welfare requirements in 2022.",
        "source": "DFAT / FWO / Pacific Islands Forum Secretariat / ABC",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Seasonal Worker Programme — Wage Deduction Exploitation",
        "summary": "Australia's Seasonal Worker Programme (SWP, merged into PALM 2022) brought workers from Pacific Islands and Timor-Leste for up to 9 months in agriculture and accommodation sectors. Key exploitation documented: workers paid piece rates effectively below minimum wage, accommodation deductions of AUD 100-200/week for crowded conditions, transport deductions of AUD 50-100/week, workers arriving in debt to origin-country agents. Net take-home wages sometimes AUD 200-400/week after deductions (versus AUD 800+ gross). Joint Standing Committee on Migration inquiry (2020) recommended deduction caps.",
        "source": "Joint Standing Committee on Migration / DFAT / Pacific Labour Facility",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "PALM Scheme Worker Deaths — Accommodation and Transport Safety",
        "summary": "Multiple PALM scheme worker deaths raised safety concerns. 2022-2023: Vanuatu worker died in house fire in rural Queensland (substandard employer-provided accommodation, no smoke alarms). Two Tongan workers killed in workplace vehicle accident (inadequate training, unlicensed vehicle). One Fijian worker died of heat stroke picking tomatoes in 40-degree heat (no heat stress policy). DEWR review recommended mandatory accommodation standards, vehicle safety audits, and heat management plans. Approved employers now subject to enhanced welfare checks.",
        "source": "DEWR / ABC / Pacific Labour Facility / Vanuatu Daily Post",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "PALM Worker Recruitment — Origin Country Agent Fees",
        "summary": "Despite the PALM scheme being government-to-government (no private recruitment fees in Australia), workers report paying fees to facilitators, agents, and community leaders in origin countries. Documented fees: Vanuatu VUV 50,000-150,000 (AUD 600-1,800), Tonga TOP 1,000-3,000 (AUD 600-1,800), Samoa WST 1,500-4,000 (AUD 800-2,200). Workers borrow from family or take loans to pay fees. Debt creates pressure to accept exploitative conditions in Australia to ensure return on investment. Australia's Labour Mobility Assistance Program does not monitor origin-country charges.",
        "source": "Pacific Labour Facility / World Bank / Lowy Institute",
    },
    # ── Modern Slavery Act and Reporting ─────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "AU",
        "title": "Modern Slavery Act 2018 (Cth) — Mandatory Reporting Regime",
        "summary": "Australia enacted the Modern Slavery Act 2018 (Commonwealth) requiring entities with annual consolidated revenue of AUD 100 million+ to submit annual Modern Slavery Statements describing: supply chain risks, actions taken to assess and address risks, and effectiveness of those actions. By December 2023, over 7,000 statements lodged with the Australian Border Force Modern Slavery Register. Act does not include penalties for non-compliance with reporting (unlike UK MSA 2015 which includes financial penalties). Review (2023) recommended: penalties for non-reporting, due diligence obligations, independent commissioner.",
        "source": "Australian Border Force / Modern Slavery Act Review 2023 / ACSI",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "AU",
        "title": "Modern Slavery Act Review 2023 — Recommended Reforms",
        "summary": "Professor John McMillan's statutory review of the Modern Slavery Act (published March 2023) made 30 recommendations including: introduce penalties for failure to report (up to AUD 1.1 million), establish an independent Anti-Slavery Commissioner, require due diligence not just reporting, extend to entities with AUD 50 million revenue, establish a list of high-risk goods and countries, require reporting on remediation provided to victims. Government accepted in-principle all recommendations. Legislative amendments expected 2025-2026.",
        "source": "Modern Slavery Act Review 2023 / Attorney-General's Department",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "AU",
        "title": "NSW Modern Slavery Act 2018 — State-Level Legislation",
        "summary": "New South Wales enacted its own Modern Slavery Act 2018 (NSW) with stronger provisions than the Commonwealth Act: Anti-Slavery Commissioner established (Professor Jennifer Burn appointed 2022), supply chain due diligence requirements for government procurement, penalties for non-compliance, and focus on labour exploitation in high-risk sectors. NSW Commissioner published reports identifying high-risk sectors: cleaning, construction, horticulture, food processing, and domestic work. Victoria considering similar state legislation.",
        "source": "NSW Anti-Slavery Commissioner / NSW Parliament",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "AU",
        "title": "Australian Anti-Slavery Commissioner Establishment (2023)",
        "summary": "Commonwealth government announced establishment of the Australian Anti-Slavery Commissioner in December 2023, following the Modern Slavery Act Review. Commissioner to: monitor compliance with reporting obligations, support businesses in addressing modern slavery, coordinate victim support, and conduct inquiries. Dr. James Cockayne appointed as inaugural Commissioner (January 2024). Office established with AUD 8 million annual budget. Commissioner has investigation and inquiry powers but not prosecution authority (remains with AFP/CDPP).",
        "source": "Attorney-General's Department / Anti-Slavery Commissioner Office",
    },
    # ── Visa Worker Exploitation Patterns ──────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Student Visa (Subclass 500) Worker Exploitation — Systemic Pattern",
        "summary": "Australia hosts 600,000+ international students, most with work rights limited to 48 hours per fortnight. Systematic exploitation documented: students work 50-80 hours/fortnight for AUD 10-15/hour in cash-economy jobs (restaurants, convenience stores, delivery). Employers threaten visa cancellation for complaints. Students from India, China, Nepal, Bangladesh most affected. FWO's Overseas Workers Program received 5,000+ student visa holder complaints annually (2019-2023). Changes to work hour limits (temporarily uncapped during COVID, permanently increased to 48 hours from July 2023) had mixed impact.",
        "source": "Fair Work Ombudsman / Migrant Workers Taskforce / Universities Australia",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Working Holiday Maker (417/462) Exploitation — 88-Day Requirement",
        "summary": "Working Holiday Makers (WHM) from 40+ countries can extend their visa by completing 88 days of specified work in regional Australia (agriculture, construction, mining). This requirement creates vulnerability: workers accept exploitative conditions to obtain employer-signed evidence of 88 days. Documented exploitation: sub-minimum wages, sexual harassment, unsafe accommodation, fabricated records (workers pay AUD 2,000-5,000 for fake 88-day evidence). FWO Harvest Trail inquiry (2018) recommended removing the 88-day requirement. Government reduced to 60 days for some countries but maintained the system.",
        "source": "Fair Work Ombudsman / National Farmers Federation / Backpacker advocacy groups",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Temporary Skill Shortage (482) Visa — Employer Dependency",
        "summary": "Subclass 482 (TSS) visa holders tied to nominating employer. Workers who leave or are dismissed have 60 days to find new sponsor or leave Australia. This creates structural dependency: workers accept underpayment, excessive hours, and poor conditions rather than risk unemployment and deportation. FWO and ABF documented: 30+ percent of 482 sponsors non-compliant with nomination obligations. Workers report salary rates AUD 10,000-30,000 below market rate. 2023 reforms increased portability (90-day transfer window) but employer sponsorship model maintained.",
        "source": "Fair Work Ombudsman / Home Affairs / Migration Council Australia",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Labour Hire Licensing — State Schemes and Gaps",
        "summary": "Victoria (2018), Queensland (2018), and South Australia (2017) introduced labour hire licensing schemes to address exploitation by intermediaries. Schemes require: financial viability, fit-and-proper-person test, compliance with workplace laws. Victoria's scheme (Labour Hire Authority) licensed 4,500+ providers. However, unlicensed operators continue, cross-border enforcement is weak, and NSW (largest market) has no scheme. FWO coordination with state schemes remains limited. Workers employed through labour hire earn 15-30 percent less than directly employed workers on same tasks.",
        "source": "Victorian Labour Hire Authority / QLD Office of Industrial Relations / FWO",
    },
    # ── Sector-Specific Cases ──────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Fair Work v Maroochy Sunshine Pty Ltd — Farm Worker Exploitation",
        "summary": "Federal Court ordered AUD 380,000 penalties against Maroochy Sunshine (strawberry farm, Queensland) for underpaying 152 Malaysian, Taiwanese, and Korean workers on Working Holiday visas. Workers paid AUD 4-8/hour (piece rates well below minimum). Workers housed in on-farm accommodation with AUD 100/week deductions. Working 10-12 hour days in heat with limited water. Workers recruited through backpacker hostel networks. Court imposed personal penalties on director. Case part of FWO's Harvest Trail enforcement priority.",
        "source": "Federal Court of Australia / Fair Work Ombudsman",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Fair Work v Ezy Accounting — Sham Arrangement Penalty",
        "summary": "FWO successfully prosecuted Ezy Accounting for operating a sham contracting arrangement in the food delivery sector. Filipino workers classified as independent contractors but controlled in manner of employees. Workers earned AUD 8-12/hour after expenses. No superannuation, leave, or workers compensation. Federal Circuit Court imposed AUD 250,000 in penalties. Case established precedent for challenging gig-economy misclassification of vulnerable visa workers.",
        "source": "Fair Work Ombudsman / Federal Circuit Court",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Mornington Peninsula Vineyard Worker Exploitation (2021)",
        "summary": "ABC investigation revealed vineyard and farm workers in Mornington Peninsula (Victoria) paid AUD 3-5/hour through labour hire companies. Workers predominantly from Malaysia, Taiwan, and Pacific Islands on working holiday and seasonal worker visas. Labour hire operators charged workers AUD 150-200/week for overcrowded accommodation (10+ per house). Workers transported in unregistered vehicles. Some workers paid nothing for weeks due to 'deductions exceeding earnings.' Victorian Labour Hire Authority revoked 3 licences.",
        "source": "ABC / Victorian Labour Hire Authority / Fair Work Ombudsman",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Taiwanese Meat Processing Workers — Forced Labour Indicators",
        "summary": "AFP and FWO joint investigation (2020) into labour exploitation of Taiwanese workers at a NSW meat processing facility. Workers recruited in Taiwan with promises of AUD 25/hour. On arrival, paid AUD 12-15/hour under sham contracting. Accommodation provided at AUD 200/week (market rate AUD 100). Workers who complained had visa cancellation threatened by labour hire company. AFP found forced labour indicators (deception, coercion, debt bondage through accommodation charges) but prosecution did not proceed due to evidentiary challenges.",
        "source": "AFP / Fair Work Ombudsman / Anti-Slavery Australia",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Domestic Worker Exploitation — Diplomatic Household Cases",
        "summary": "Anti-Slavery Australia documented cases of domestic workers exploited in diplomat households in Canberra and Sydney. Workers brought on A-1 or A-2 (diplomatic) visas with no work rights outside the employing household. Documented: 18-hour workdays, no day off, below minimum wage (AUD 3-5/hour), passport confiscation, isolation. Workers cannot bring claims under Fair Work Act (diplomatic immunity). Government introduced Domestic Worker Visa (subclass 426) with some protections but enforcement remains difficult due to diplomatic immunity conventions.",
        "source": "Anti-Slavery Australia / DFAT / Salvation Army",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Aged Care Worker Exploitation — Filipino Visa Workers",
        "summary": "Filipino workers on 482 visas in aged care sector reported: wages AUD 3-5 below award rate, unpaid overtime for documentation tasks, employer-controlled accommodation with above-market rent deductions, and threats of visa cancellation. Aged care sector employed 15,000+ temporary visa holders (2022). Royal Commission into Aged Care (2021) noted workforce vulnerability but focused on care quality rather than worker exploitation. United Workers Union campaign (2022) secured back-pay for 500+ aged care visa workers. FWO issued compliance notices to 30+ aged care providers.",
        "source": "United Workers Union / FWO / Royal Commission into Aged Care",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Ride-Share and Food Delivery Worker Exploitation — Gig Economy",
        "summary": "Gig economy platforms (Uber, DoorDash, Menulog, Deliveroo) in Australia employ large numbers of temporary visa holders. Transport Workers Union research (2021): average delivery rider earned AUD 10.42/hour after expenses (minimum wage AUD 21.38). 6 food delivery riders died in 3 months in late 2020. Workers classified as independent contractors, excluded from Fair Work Act protections. Workers from India, China, Brazil disproportionately represented. NSW legislative inquiry (2022) recommended employee-like protections. Federal government passed closing loopholes legislation (2024) extending some protections.",
        "source": "Transport Workers Union / Senate Select Committee / FWO",
    },
    # ── Trafficking and Slavery Investigations ─────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "AU",
        "title": "AFP Human Trafficking Investigations — Annual Data (2022-2023)",
        "summary": "Australian Federal Police (AFP) received 340 referrals for human trafficking and slavery offences in 2022-2023. Active investigations: 130. New investigations commenced: 69. Prosecution briefs to CDPP: 12. Trafficking types: forced labour (45 percent), sexual servitude (30 percent), forced marriage (15 percent), other (10 percent). Victim nationalities: Philippines, Thailand, India, China, Fiji, Malaysia, Korea. AFP operates Human Trafficking Teams in Sydney, Melbourne, Brisbane, and Canberra. Support to Trafficking Victims Program (STVP) assisted 250+ victims.",
        "source": "AFP Annual Report 2022-2023 / IDCARE / Australian Red Cross",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Forced Marriage in Australia — Criminal Code Division 270",
        "summary": "Australia criminalized forced marriage in 2013 (Crimes Legislation Amendment). AFP has investigated 200+ forced marriage referrals (2013-2023). Convictions remain low (fewer than 10 total). Most cases involve Australian citizens or permanent residents threatened with overseas marriage. AFP's support program provides crisis intervention. Australian Red Cross administers the Support for Trafficked People program providing 45-90 day assessment period, housing, counselling, and legal assistance. Forced marriage referrals increasing annually (80+ in 2022-2023).",
        "source": "AFP / Australian Red Cross / Attorney-General's Department",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Support for Trafficked People Program (STPP) — Victim Support Data",
        "summary": "Australian Red Cross operates the STPP on behalf of the Commonwealth government. Program provides: 45-day initial assessment, extended support for those assisting police (up to 2 years), housing, medical care, counselling, legal assistance, income support. 2022-2023: 83 new clients (40 forced labour, 18 sexual servitude, 15 forced marriage, 10 other). Total active clients: 250. 65 percent of clients are women. Criticism: support conditional on cooperation with law enforcement, creating disincentive for victims who fear police or immigration consequences.",
        "source": "Australian Red Cross / Home Affairs / Anti-Slavery Australia",
    },
    # ── Additional Fair Work and Sector Cases ──────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Fair Work v CFMG Pty Ltd [2022] — Strawberry Farm Penalties",
        "summary": "Federal Court imposed AUD 1.2 million penalties against Queensland strawberry farm operator CFMG for underpaying 66 workers from Malaysia, Korea, and Taiwan on Working Holiday visas. Workers paid flat rate of AUD 100/day for 10-12 hour days (effective rate AUD 8-10/hour). FWO investigation triggered by worker tip-off. Court found the exploitation was deliberate, systemic, and involved falsification of pay records. Largest single FWO penalty in horticulture sector at that time. Director personally liable for AUD 240,000.",
        "source": "Federal Court of Australia / Fair Work Ombudsman",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Supermarket Supply Chain Labour Exploitation — Fresh Produce",
        "summary": "Major supermarkets (Coles, Woolworths, Aldi) sourced fresh produce from farms with documented worker exploitation. Senate inquiry (2015) heard evidence of workers paid AUD 3-8/hour in supply chains of major retailers. Woolworths and Coles published modern slavery statements acknowledging risk but relied on supplier self-assessment. Ethical trade initiatives (SEDEX, BSCI) provided limited assurance. ABC investigation (2019) showed berries sold in Coles picked by workers earning AUD 5/hour. Supermarkets introduced supplier codes of conduct but enforcement audits remain infrequent.",
        "source": "Senate Education and Employment References Committee / ABC / Coles / Woolworths",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Restaurant and Hospitality Underpayment — Cash Economy Pattern",
        "summary": "FWO identified food services as the highest non-compliance sector nationally. Pattern: international student and visa workers employed in restaurants, cafes, and takeaway shops for AUD 10-16/hour in cash. Workers from China, India, Nepal, Korea, and Japan most affected. Cash payments avoid tax and superannuation obligations. Workers unable to prove employment relationship without payslips. FWO data: 40+ percent of hospitality businesses audited found non-compliant. Criminal underpayment provisions (wage theft) enacted in multiple states (Victoria 2020, Queensland 2020) and federally (2024).",
        "source": "Fair Work Ombudsman / Restaurant & Catering Association",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Migration Agent Exploitation — Unlicensed Migration Advice",
        "summary": "Workers exploited through unlicensed migration agents who facilitate visa fraud and create dependency. Pattern: agent arranges visa (student, 482, partner), charges AUD 5,000-30,000 in fees, connects worker with exploitative employer, threatens to report visa fraud if worker complains. Migration Agents Registration Authority (MARA) cancelled 50+ registrations for misconduct (2019-2023). Unregistered agents (operating outside MARA jurisdiction) are widespread in South Asian and Chinese communities. Workers who paid for fraudulent visas fear approaching authorities.",
        "source": "MARA / ABF / Anti-Slavery Australia",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Undocumented Workers in Australia — Exploitation Without Recourse",
        "summary": "An estimated 60,000-100,000 undocumented workers in Australia (visa overstayers and unlawful non-citizens). Sectors: construction, hospitality, agriculture, cleaning, sex work. Workers paid AUD 5-15/hour with no entitlements. Employers use immigration status as coercion tool. Workers cannot access FWO, Medicare, or workers compensation. Amnesty proposals debated but not implemented. ABF workplace compliance operations (2022-2023): 5,000+ visa cancellations for working illegally. Workers deported without opportunity to pursue wage claims.",
        "source": "ABF / Unions NSW / ACTU / Refugee Council of Australia",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Fair Work Amendment (Protecting Vulnerable Workers) Act 2017",
        "summary": "Landmark legislative reform introduced after 7-Eleven scandal. Key provisions: increased penalties for serious contraventions (up to AUD 630,000 per contravention for individuals), franchisor liability for franchisee wage theft, holding company liability for subsidiary exploitation, prohibition of pay-back schemes, FWO power to compel production of documents. Applied to exploitation involving visa holders. FWO secured first franchisor liability penalties in 2020. Act significantly enhanced enforcement tools but penalties still considered insufficient deterrent by unions.",
        "source": "Parliament of Australia / Fair Work Ombudsman / ACTU",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Wage Theft Criminalization — Federal and State Legislation",
        "summary": "Victoria became the first state to criminalize wage theft (Wage Theft Act 2020): imprisonment up to 10 years for dishonest underpayment. Queensland followed (Criminal Code amendment 2020). Federal government enacted criminal wage theft provisions in the Fair Work Legislation Amendment (Closing Loopholes) Act 2024: dishonest underpayment attracts imprisonment. These provisions particularly relevant to migrant worker exploitation where employers deliberately falsify records. First prosecutions expected 2025-2026. Employer groups argued provisions duplicate existing civil enforcement.",
        "source": "Parliament of Australia / Victorian Parliament / FWO",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Assurance of Support Exploitation — Sponsored Family Members",
        "summary": "Migrant workers sponsoring family members on Assurance of Support (AoS) arrangements face exploitation by sponsors who use the financial guarantee as leverage. Pattern: AoS holder requires sponsored person to work in their business for free or below minimum wage, threatening to withdraw support. Anti-Slavery Australia documented cases of AoS holders exploiting sponsored spouses and relatives in family businesses (restaurants, farms, cleaning companies). Workers feel unable to report due to immigration dependency. Issue falls between family law and employment law jurisdictions.",
        "source": "Anti-Slavery Australia / Services Australia / UTS",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Darwin and Northern Territory Farm Worker Exploitation",
        "summary": "Northern Territory agriculture employs Pacific Island, Southeast Asian, and backpacker workers in mango, melon, and banana farming. Remote locations create isolation and employer dependency. Documented exploitation (2019-2023): workers in Katherine and Darwin regions paid AUD 5-12/hour, housed in containers and sheds without adequate facilities, temperatures exceeding 40 degrees with no heat management. FWO conducted targeted compliance visits: 55 percent of farms non-compliant. NT WorkSafe issued improvement notices for accommodation standards.",
        "source": "Fair Work Ombudsman / NT WorkSafe / ABC Rural",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Sex Industry Worker Exploitation — Trafficking and Visa Fraud",
        "summary": "AFP documented trafficking for sexual exploitation involving women from Thailand, China, Korea, and Malaysia. Pattern: women recruited with promises of waitressing or massage jobs, arrive to find sex work expected, debt of AUD 30,000-60,000 imposed. AFP Human Trafficking Teams investigate 20-30 sexual servitude cases annually. Convictions: 3-5 per year. Project Respect (NGO) provides outreach to 600+ sex industry workers annually in Melbourne. Scarlet Alliance advocates decriminalization to improve worker safety and reduce trafficking vulnerability.",
        "source": "AFP / Project Respect / Scarlet Alliance / Anti-Slavery Australia",
    },
    {
        "type": "statistic",
        "jurisdiction": "AU",
        "title": "Modern Slavery Statements Analysis — Quality Assessment",
        "summary": "Australian Council of Superannuation Investors (ACSI) analysis of Modern Slavery Statements (2023) found: only 25 percent of statements adequately described supply chain risks, 15 percent provided meaningful effectiveness metrics, 40 percent failed to describe any actions taken beyond risk assessment, and fewer than 5 percent described remediation provided to identified victims. ASX 200 companies performed better than smaller entities. Finance sector statements were particularly weak on non-financial supply chains (cleaning, security, catering). ACSI recommended mandatory due diligence legislation.",
        "source": "ACSI / Walk Free Foundation / Australian Border Force",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "COVID-19 Impact on Migrant Worker Exploitation in Australia",
        "summary": "COVID-19 exacerbated migrant worker exploitation in Australia. 2020-2021: temporary visa holders excluded from JobKeeper (AUD 1,500/fortnight wage subsidy). An estimated 500,000 temporary visa holders had no income support. Workers accepted exploitative conditions out of desperation. FWO documented spike in complaints from agriculture and food delivery sectors. Some workers became undocumented as visas expired with no flights available. Government eventually provided limited support but most temporary visa holders relied on charity and community organizations.",
        "source": "FWO / Refugee Council of Australia / UTS / Migration Council",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Migrant Workers Taskforce — Interdepartmental Coordination",
        "summary": "The Migrant Workers Taskforce (established 2016, expanded 2019) coordinates FWO, ABF, ATO, AFP, and Home Affairs to address migrant worker exploitation. Key initiative: FWO assurance protocol guaranteeing visa holders who report exploitation will not face immigration enforcement during investigation. By 2023, over 2,000 visa holders used the protocol to report exploitation without fear of deportation. Taskforce also produced educational materials in 30 languages. However, awareness of the protocol among migrant communities remains low (estimated 15-20 percent awareness).",
        "source": "Migrant Workers Taskforce / Fair Work Ombudsman / ABF",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Walk Free Foundation — Global Slavery Index Australia Chapter",
        "summary": "Walk Free Foundation (Perth-based) estimated 41,000 people in conditions of modern slavery in Australia (Global Slavery Index 2023). Prevalence: 1.6 per 1,000 population. Forms: forced labour (60 percent), forced marriage (25 percent), sexual exploitation (15 percent). High-risk sectors: agriculture, construction, domestic work, hospitality, cleaning. Risk factors: temporary visa dependency, cash economy, geographic isolation, language barriers. Australia ranked 5th among G20 countries for government response but criticized for weak enforcement and lack of mandatory due diligence.",
        "source": "Walk Free Foundation / Global Slavery Index 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Fair Work v Yonghe Pty Ltd [2023] — Deliberate Exploitation Pattern",
        "summary": "Federal Court imposed AUD 750,000 in penalties against Sydney restaurant group for deliberately exploiting Chinese and Korean visa workers. Workers paid AUD 10-14/hour for 50+ hour weeks. Pay records falsified. Workers recruited through WeChat and KakaoTalk communities targeting newly arrived visa holders. Court found exploitation was a business model: lower labour costs funded expansion to 5 outlets. Director banned from managing a corporation for 5 years. FWO cited case as evidence of deliberate, profit-driven exploitation requiring criminal prosecution tools.",
        "source": "Federal Court of Australia / Fair Work Ombudsman",
    },
    # ── Additional Australian Cases ────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "AU",
        "title": "R v Pulini [2019] — Fijian Domestic Servitude in Queensland",
        "summary": "Fijian woman Ratu Pulini convicted in Brisbane District Court of holding a Fijian domestic worker in servitude. Victim brought from Fiji on tourist visa to work in household. Worked 16-18 hours daily, never paid, beaten, confined to house, not permitted to contact family. Victim rescued after neighbour reported concerns to police. Pulini sentenced to 4 years imprisonment. Case demonstrated that servitude occurs within diaspora community networks, not only through organized trafficking rings.",
        "source": "Brisbane District Court / AFP / Commonwealth DPP",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Blueberry and Strawberry Farm Exploitation — Coffs Harbour Region",
        "summary": "Coffs Harbour (NSW) blueberry and strawberry farms employed thousands of Working Holiday Makers and Pacific Islanders. ABC investigation (2018) documented: workers paid AUD 3-7/hour on piece rates, housed in overcrowded caravan parks at AUD 180/week, labour hire companies taking 20-30 percent of wages as 'management fees.' Workers from Taiwan, Korea, Hong Kong, and Pacific Islands. FWO Operation Outreach (2019) audited 60+ farms in the region, finding 50 percent non-compliant. Multiple compliance notices and penalties issued.",
        "source": "ABC / Fair Work Ombudsman / Coffs Harbour Advocate",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Fair Work v South Jin Pty Ltd [2015] — Korean Restaurant Chain",
        "summary": "Federal Circuit Court imposed AUD 370,000 in penalties against South Jin Pty Ltd (Korean restaurant chain in Sydney and Melbourne). Company systematically underpaid Korean and Japanese workers on student and working holiday visas: AUD 10-13/hour for 50+ hour weeks, no penalty rates, no superannuation. Company used Korean-language advertisements specifically targeting newly arrived visa holders unfamiliar with Australian workplace rights. Director held personally liable.",
        "source": "Federal Circuit Court / Fair Work Ombudsman",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Griffith and Riverina Agricultural Exploitation — Citrus and Wine",
        "summary": "Agricultural workers in Griffith and Riverina (NSW) — major citrus, wine grape, and vegetable growing regions — report systematic underpayment. Workers (WHM visa holders, undocumented, and PALM scheme) picking citrus earn AUD 5-12/hour on piece rates. Labour hire contractors charge for transport to remote farms (AUD 10/day each way) and accommodation (AUD 150-200/week in shared housing). Workers from Malaysia, Vietnam, and Pacific Islands most affected. FWO and NSW SafeWork conducted joint inspections (2021-2023) finding 45 percent non-compliance.",
        "source": "Fair Work Ombudsman / NSW SafeWork / SBS",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Sunraysia Grape Industry — Table Grape Picking Exploitation",
        "summary": "Mildura-Sunraysia region (Victoria) is Australia's largest table grape growing area, employing 5,000+ seasonal workers. Workers report piece rates of AUD 60-80 per bin for work requiring 10+ hours (effective AUD 6-8/hour). Labour hire companies (100+ registered in the region) compete on price, driving down worker compensation. Workers housed in overcrowded properties with 15-20 per house. Victorian Labour Hire Authority suspended 12 licences in the region (2020-2023). National Farmers Federation advocated for piece rate minimum floor.",
        "source": "Victorian Labour Hire Authority / ABC Rural / National Farmers Federation",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "AU",
        "title": "Fair Work Legislation Amendment (Closing Loopholes) Act 2024",
        "summary": "Landmark reform addressing multiple exploitation pathways: criminal wage theft (imprisonment for dishonest underpayment), same job same pay (labour hire workers paid at host employer rates), gig worker protections (minimum standards orders for employee-like workers), right to disconnect, and strengthened casual conversion rights. Particularly significant for migrant workers exploited through labour hire intermediaries and gig platforms. Employer groups challenged provisions as overreach. Implementation phased through 2024-2025.",
        "source": "Parliament of Australia / FWO / ACTU",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Indian International Student Worker Exploitation — Systematic Pattern",
        "summary": "India is the largest source of international students in Australia (140,000+ enrolments in 2023). Systematic exploitation documented: Indian-owned businesses specifically recruit Indian students, paying AUD 10-15/hour in cash. Students exceed work hour limits to survive (rent in Sydney/Melbourne AUD 250-400/week). Employers hold leverage through work hour violations. FWO data: Indian visa holders lodged 4,500+ complaints in 2022-2023 (highest single nationality). Community organizations (Federation of Indian Associations) established worker rights hotlines.",
        "source": "Fair Work Ombudsman / Federation of Indian Associations / SBS Hindi",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Poultry Processing Worker Exploitation — South East Queensland",
        "summary": "Poultry processing plants in South East Queensland employed Pacific Island and Malaysian workers through labour hire companies. Documented exploitation (2020-2022): workers on PALM scheme paid award rates but charged excessive accommodation (AUD 200/week for shared rooms), transport (AUD 80/week), and equipment deductions. Net take-home pay: AUD 300-450/week despite working 38+ hours. Workers who complained to labour hire company threatened with contract termination and repatriation. DEWR issued compliance notices to 5 approved employers.",
        "source": "DEWR / United Workers Union / Pacific Labour Facility",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Disability Support Worker Exploitation — NDIS Sector",
        "summary": "National Disability Insurance Scheme (NDIS) sector employs 20,000+ temporary visa holders. Exploitation documented: workers on 482 visas paid AUD 5-10 below Social, Community, Home Care and Disability Services (SCHADS) Award rates, expected to work unpaid 'trial shifts' of 4-8 hours, required to use personal vehicles without mileage reimbursement, employer-arranged accommodation with above-market deductions. Workers afraid to complain due to visa dependency. NDIS Quality and Safeguards Commission received 1,500+ worker-related complaints (2022-2023).",
        "source": "NDIS Quality and Safeguards Commission / Health Services Union / FWO",
    },
    {
        "type": "statistic",
        "jurisdiction": "AU",
        "title": "Australian Federal Police — Trafficking Conviction Statistics (2004-2023)",
        "summary": "Since Division 270/271 of the Criminal Code came into force (2005): AFP has investigated 700+ trafficking referrals, CDPP has prosecuted 30+ individuals, 20+ convictions obtained. Average sentence: 4-8 years imprisonment. Types: sexual servitude (50 percent), forced labour (30 percent), slavery (15 percent), deceptive recruiting (5 percent). Victim nationalities: Thailand, Philippines, Korea, Malaysia, India, Fiji, China. Low conviction rate (under 5 percent of referrals) attributed to: evidentiary challenges, victim reluctance to cooperate, and threshold for criminal prosecution.",
        "source": "AFP / Commonwealth DPP / Anti-Slavery Australia",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Fair Work v Galati Constructions [2022] — Construction Visa Worker Case",
        "summary": "FWO prosecuted Galati Constructions (Perth) for underpaying 25 workers on 482 and 457 visas. Workers from Philippines and India paid AUD 18-22/hour versus Building and Construction General On-site Award rate of AUD 28-35/hour. Workers also denied penalty rates for weekend and overtime work. Total underpayment: AUD 680,000. Federal Circuit Court imposed AUD 420,000 in penalties. Director required to undergo workplace relations training. Case part of FWO's construction sector compliance priority.",
        "source": "Federal Circuit Court / Fair Work Ombudsman",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Pacific Australia Labour Mobility (PALM) — Welfare Framework Reform",
        "summary": "Following worker deaths and exploitation reports, DEWR implemented the PALM Scheme Worker Wellbeing Framework (2022): mandatory accommodation inspections (minimum standards for bedrooms, bathrooms, kitchen, fire safety), maximum accommodation deduction caps (AUD 175/week metro, AUD 125/week regional), pastoral care officers appointed by approved employers, wellbeing checks every 6 months, worker grievance mechanism independent of employer. By 2023, 50+ approved employers suspended or deregistered for non-compliance.",
        "source": "DEWR / Pacific Labour Facility / Pacific Islands Forum",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Tomato and Capsicum Farm Exploitation — Bundaberg Region",
        "summary": "Bundaberg (Queensland) tomato and capsicum farms documented as persistent exploitation sites. Multiple FWO investigations (2016-2023) found: piece rates of AUD 0.50-1.50 per bucket (effective AUD 5-10/hour), workers from Taiwan, Korea, and Vanuatu housed in containers and sheds, no access to adequate sanitation, heat stress exposure (40+ degree days), labour hire operators absconding with workers' accumulated pay. Three labour hire operators in the region convicted of workplace law breaches totalling AUD 900,000 in penalties.",
        "source": "Fair Work Ombudsman / ABC Rural / Queensland Government",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Fair Work v Epping Restaurant Group [2021] — Cash-Back Scheme",
        "summary": "FWO prosecuted an Epping (Melbourne) restaurant group for operating a 'cash-back' scheme: workers paid correct award wages electronically (to satisfy record-keeping) then required to return 30-50 percent in cash to the employer. Scheme targeted Chinese and Indian student visa workers. Total underpayment: AUD 380,000 affecting 40 workers. Federal Circuit Court described the scheme as 'deliberate and cynical.' Penalties: AUD 550,000. Case demonstrated sophistication of wage theft methods used to evade WPS-style monitoring.",
        "source": "Federal Circuit Court / Fair Work Ombudsman",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Car Wash Industry Exploitation — Melbourne and Sydney",
        "summary": "FWO and ABF joint investigations (2019-2021) found systematic exploitation in hand car wash operations. Workers predominantly from India, Nepal, and Sri Lanka on student visas. Paid AUD 8-12/hour in cash, working 10-12 hour shifts. Sham contracting used to avoid employment obligations. Workers exposed to chemicals without PPE. 60+ car wash operators audited: 70 percent non-compliant. ABF identified 200+ workers in breach of visa conditions. Workers reluctant to report due to fear of visa cancellation.",
        "source": "Fair Work Ombudsman / Australian Border Force / The Age",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Abalone and Seafood Processing — Regional Victoria Exploitation",
        "summary": "Seafood processing in regional Victoria (Portland, Warrnambool) employed workers from Timor-Leste, Kiribati, and Vanuatu under PALM scheme. Workers reported: accommodation in converted sheds (10+ per room), transport to remote processing plants with no public transport alternative, piece rates below minimum wage during slow season, social isolation in small regional towns with no community networks. Pacific Labour Facility conducted compliance review (2022) and required 3 approved employers to improve housing and welfare services.",
        "source": "Pacific Labour Facility / ABC Ballarat / United Workers Union",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Massage Industry Exploitation — Beyond Nail Salons",
        "summary": "FWO investigations (2019-2023) documented exploitation in massage industry extending beyond sexual servitude cases. Legitimate massage businesses employing Thai, Chinese, and Korean workers on student and partner visas. Workers paid AUD 10-15/hour for 10+ hour shifts with no breaks. Some workers required to live on premises. Sham contracting arrangements (worker classified as 'booth renter' but controlled as employee). FWO conducted Operation Thai Wave (2020): 45 businesses audited, 30 non-compliant. AUD 2.5 million in back-pay recovered.",
        "source": "Fair Work Ombudsman / AFP",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Security Industry Worker Exploitation — Subcontracting Chains",
        "summary": "Security industry employs 30,000+ temporary visa holders in Australia. Exploitation through subcontracting chains: main security company contracts to subcontractor, which sub-contracts to another. Each layer takes margin. Final workers (from India, Nepal, Fiji) paid AUD 15-20/hour versus Security Services Industry Award rate of AUD 25-30. Workers required to hold security licence (cost AUD 600-1,000) but receive below-award wages. FWO and state police conducted joint operations targeting shopping centres and event venues. 40 percent non-compliance rate in audited subcontractors.",
        "source": "Fair Work Ombudsman / United Workers Union / Security Providers Association",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Childcare and Early Childhood Education — Visa Worker Exploitation",
        "summary": "Childcare sector experiencing workforce shortages employs 10,000+ temporary visa holders. Workers on 482 and student visas report: below-award wages (AUD 20-23/hour versus AUD 27+ award), unpaid training and documentation time, excessive child-to-carer ratios, employer threatening visa cancellation for complaints. Some workers recruited overseas with promises of permanent residency pathway that did not materialize. United Workers Union documented 500+ underpayment complaints from childcare visa workers (2021-2023).",
        "source": "United Workers Union / FWO / ACECQA",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Regional Accommodation Exploitation — PALM Worker Housing",
        "summary": "PALM scheme workers in regional Australia housed in substandard accommodation by approved employers. Documented issues (2021-2023): converted shipping containers as bedrooms, insufficient heating in cold climates (Tasmania, southern Victoria), no internet or phone coverage, 6+ workers sharing one bathroom, pest infestations, accommodation 30+ minutes from town with no transport provided on days off. Workers charged AUD 100-175/week for these conditions. DEWR conducted 800+ accommodation inspections in 2023, issuing 150+ improvement notices.",
        "source": "DEWR / Pacific Labour Facility / Vanuatu Daily Post / ABC",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Uber Eats Rider Deaths — Gig Worker Safety Crisis (2020)",
        "summary": "Five food delivery riders (4 working for Uber Eats, 1 for DoorDash) died on Australian roads between September and November 2020. All were international students or temporary visa holders from India, Pakistan, and Brazil. Deaths exposed: lack of workers compensation coverage for gig workers, no safety training or equipment provided, piece-rate payment creating incentive to rush in traffic, platform deactivation for slow delivery without appeal process. TWU campaigned for industrial manslaughter charges. NSW and federal inquiries commenced.",
        "source": "Transport Workers Union / Senate Select Committee / NSW Coroner",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Cotton Farming Exploitation — Northern NSW and Queensland",
        "summary": "Cotton harvesting in northern NSW (Moree, Narrabri, Walgett) and Queensland (St George, Emerald) employs seasonal workers including Pacific Islanders and backpackers. Documented exploitation: workers paid by weight of cotton picked (AUD 30-50 per bale), effective hourly rate AUD 6-12 during poor crop years, extreme heat exposure (40+ degrees), accommodation in old farm buildings without air conditioning, and 5-hour round trips to nearest medical facility. FWO Harvest Trail investigation found 50 percent of cotton farms using labour hire with non-compliant pay practices.",
        "source": "Fair Work Ombudsman / ABC Rural / Cotton Australia",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Anti-Slavery Australia Legal Centre — Victim Advocacy",
        "summary": "Anti-Slavery Australia (based at UTS, Sydney) is the only specialist legal centre for trafficking victims in Australia. Provides: free legal representation, research and policy advocacy, community education. Represented victims in 200+ cases since 2003. Key achievements: successful constitutional challenge to offshore processing (with others), advocacy for Modern Slavery Act, legal representation in landmark trafficking prosecutions. Annual caseload: 50-80 active clients. Identified key gap: no independent mechanism for visa holders to report exploitation without fear of immigration consequences.",
        "source": "Anti-Slavery Australia / UTS / Attorney-General's Department",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Salvation Army Safe House Network — Trafficking Victim Accommodation",
        "summary": "Salvation Army operates safe houses in Sydney, Melbourne, Brisbane, and Perth for trafficking victims as part of the STPP. Houses provide: secure accommodation (address confidential), case management, counselling, life skills, and employment support. Average stay: 3-12 months. Clients: 80 percent female, primary nationalities Thai, Filipino, Chinese, Malaysian. Houses accommodate 6-10 residents each. Salvation Army noted increasing referrals for forced labour (versus historical focus on sexual exploitation), with 60 percent of new referrals in 2023 involving labour exploitation.",
        "source": "Salvation Army / Australian Red Cross STPP / Home Affairs",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Truck Driving Industry — Visa Worker Exploitation and Safety",
        "summary": "Trucking industry employs 5,000+ temporary visa holders, primarily from India, Pakistan, and the Philippines. Transport Workers Union documented: drivers paid per trip rather than hourly (effective rate AUD 12-18/hour after fuel and maintenance), expected to drive 14+ hours per day (Chain of Responsibility laws limit to 12), accommodation in truck cabins, employer threatening visa cancellation for refusing unsafe loads. Three visa holder truck drivers killed in fatigue-related crashes (2021-2023). National Heavy Vehicle Regulator investigations into sponsoring companies insufficient.",
        "source": "Transport Workers Union / National Heavy Vehicle Regulator / FWO",
    },
    {
        "type": "statistic",
        "jurisdiction": "AU",
        "title": "Temporary Visa Holders in Australian Workforce — Scale of Vulnerability",
        "summary": "Australia has approximately 2.2 million temporary visa holders at any time (2023), of whom an estimated 1.5 million have work rights. Breakdown: international students 600,000+, Working Holiday Makers 150,000+, temporary skilled workers (482) 200,000+, PALM scheme 35,000+, bridging visas 300,000+, other temporary visas 200,000+. FWO estimates 15-25 percent of temporary visa workers experience some form of underpayment. Total estimated wage theft from temporary visa workers: AUD 1-2 billion annually. Scale of exploitation makes Australia one of the largest developed-country markets for migrant worker exploitation.",
        "source": "Home Affairs / FWO / Grattan Institute / ABS",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Almond Harvesting Exploitation — Riverland South Australia",
        "summary": "Almond orchards in Riverland (SA) and Sunraysia (VIC) employ 3,000+ seasonal workers during harvest (February-April). Workers report: piece rates of AUD 40-80 per bin (effective AUD 6-10/hour for inexperienced workers), extreme heat exposure during peak harvest, accommodation in converted sheds and garages, transport deductions of AUD 10-15/day for bus to remote orchards. SA Employment Tribunal received 150+ complaints from almond workers (2022-2023). Labour hire companies registered in different states to avoid state licensing requirements.",
        "source": "SA Employment Tribunal / FWO / ABC",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Hospitality Trainee Visa Exploitation — Cookery and Baking Sector",
        "summary": "Workers on training visas (subclass 407) in hospitality report systematic exploitation. Pattern: migration agents in India, Nepal, and Bangladesh arrange training placements with Australian restaurants and bakeries. Workers pay AUD 5,000-15,000 to agents. On arrival, workers perform productive work (not training) at AUD 10-15/hour. Training plans are fabricated. Workers who complain risk visa cancellation by sponsor. ABF cancelled 200+ training visa sponsors for non-compliance (2020-2023). Workers deported without opportunity to recover agency fees.",
        "source": "ABF / Fair Work Ombudsman / Migration Institute of Australia",
    },
]
