"""Bilateral labour agreements between origin and destination countries."""

BILATERAL_FACTS: list[dict] = [
    # ── Existing ──────────────────────────────────────────────────────
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-SA",
        "corridor": "PH-SA",
        "title": "Philippines-Saudi Arabia Bilateral Labour Agreement (2017)",
        "summary": "Covers domestic workers: standard employment contract, employer-pays recruitment, minimum wage SAR 1,500/month, weekly rest day, end-of-service benefits. Disputes via labour court.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-QA",
        "corridor": "PH-QA",
        "title": "Philippines-Qatar Labour Cooperation Agreement",
        "summary": "Covers recruitment, contract verification, and worker protection. Qatar reformed kafala in 2020 allowing job mobility. Joint committee monitors implementation.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-MY",
        "corridor": "NP-MY",
        "title": "Nepal-Malaysia MOU on Recruitment of Workers",
        "summary": "Government-to-government recruitment with target zero cost for workers. Covers manufacturing, plantation, and services sectors. Nepal Foreign Employment Board monitors compliance.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-MY",
        "corridor": "BD-MY",
        "title": "Bangladesh-Malaysia G2G Recruitment System",
        "summary": "Eliminates private recruitment agencies. Government-to-government system with fixed costs. Workers recruited through BMET (Bureau of Manpower, Employment and Training).",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-KR",
        "corridor": "ID-KR",
        "title": "Indonesia-Korea EPS (Employment Permit System) Agreement",
        "summary": "Korea's EPS is a model government-managed system. Workers apply through BNP2MI. Total cost capped at ~USD 1,000. Korean Language Test (EPS-TOPIK) required. 3-year contracts.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-JP",
        "corridor": "VN-JP",
        "title": "Vietnam-Japan TITP/SSW Framework",
        "summary": "Technical Intern Training Program (TITP) and Specified Skilled Worker (SSW) frameworks. SSW allows direct employment and job changes. Vietnam sending organizations regulated by DOLAB.",
    },

    # ── New ───────────────────────────────────────────────────────────
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-KR",
        "corridor": "PH-KR",
        "title": "Philippines-Korea EPS Agreement",
        "summary": "Government-to-government recruitment via EPS. Workers pass EPS-TOPIK Korean language test. Max stay 4 years 10 months. Sectors: manufacturing, agriculture, fishing, construction, services.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-JP",
        "corridor": "PH-JP",
        "title": "Philippines-Japan Economic Partnership Agreement (JPEPA) Labour Provisions",
        "summary": "Allows deployment of Filipino nurses and caregivers to Japan. Must pass Japanese national exams within 3-4 years. Also covers TITP technical interns and SSW specified skilled workers.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-HK",
        "corridor": "PH-HK",
        "title": "Philippines-Hong Kong Standard Employment Contract for FDHs",
        "summary": "Mandatory standard contract: minimum HKD 4,870/month, free accommodation, free food (or HKD 1,236 allowance), rest days, annual leave, return airfare. POLO Hong Kong verifies all contracts.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-SA",
        "corridor": "ID-SA",
        "title": "Indonesia-Saudi Arabia MOU on Domestic Worker Protection (2014)",
        "summary": "Standard employment contract, employer-pays recruitment, rest days, salary payment through bank. Indonesia suspended deployment multiple times (2009, 2011, 2015) over abuse cases.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-MY",
        "corridor": "ID-MY",
        "title": "Indonesia-Malaysia MOU on Recruitment and Placement of Workers",
        "summary": "Covers domestic, plantation, manufacturing, and construction workers. Employer-pays principle. Standard employment contract. Indonesia suspended deployment in 2009 over abuse cases; resumed 2011.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-JP",
        "corridor": "ID-JP",
        "title": "Indonesia-Japan TITP/SSW MOU",
        "summary": "Covers Technical Intern Training and Specified Skilled Worker programs. Japanese Language Proficiency Test required. BNP2MI manages sending. 14 eligible sectors for SSW.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-SA",
        "corridor": "BD-SA",
        "title": "Bangladesh-Saudi Arabia Labour Agreement",
        "summary": "Covers recruitment of construction, domestic, and service workers. BMET manages sending side. Standard contract with SAR-denominated wages. Employer-pays recruitment target, poorly enforced.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-QA",
        "corridor": "BD-QA",
        "title": "Bangladesh-Qatar Labour MOU",
        "summary": "Government-to-government recruitment framework. Covers construction, services, and domestic workers. Qatar's 2020 reforms allow job mobility. Employer-pays principle for recruitment costs.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-QA",
        "corridor": "NP-QA",
        "title": "Nepal-Qatar Bilateral Labour Agreement",
        "summary": "Free-visa free-ticket policy: employer bears all recruitment costs. Covers construction, hospitality, and domestic work. Nepal Foreign Employment Board verifies demand letters.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-KR",
        "corridor": "NP-KR",
        "title": "Nepal-Korea EPS Agreement",
        "summary": "Government-managed recruitment. EPS-TOPIK Korean language test required. Total cost ~USD 850. No private agency involvement. Manufacturing, agriculture, and construction sectors.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ET-SA",
        "corridor": "ET-SA",
        "title": "Ethiopia-Saudi Arabia Labour Agreement (2017)",
        "summary": "Resumed after 2013 ban. Standard contract for domestic workers: SAR 1,500/month, employer-paid recruitment, medical insurance. Enforcement challenges: sub-agents in Addis Ababa.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MM-TH",
        "corridor": "MM-TH",
        "title": "Myanmar-Thailand MOU on Labour Cooperation",
        "summary": "Covers fishing, agriculture, manufacturing, construction, and domestic work. Zero-cost recruitment target. Nationality verification process for undocumented workers. Border cooperation on trafficking.",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "KH-TH",
        "corridor": "KH-TH",
        "title": "Cambodia-Thailand MOU on Labour Cooperation",
        "summary": "Covers agriculture, construction, fishing, and domestic work. MOU-based recruitment through government channels. In practice: informal border crossing via brokers remains dominant.",
    },
]
