"""Comprehensive bilateral labor agreements governing migrant worker flows across corridors.

150 entries covering Philippine, Nepali, Bangladeshi, Indian, Indonesian, Sri Lankan,
Vietnamese, Myanmar, Ethiopian, and intercontinental agreements with real provisions,
dates, and enforcement mechanisms.
"""

BILATERAL_LABOR_AGREEMENTS_EXPANDED_FACTS: list[dict] = [
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-SA",
        "corridor": "PH-SA",
        "title": "Philippines-Saudi Arabia Bilateral Labour Agreement (2017)",
        "summary": "Governs domestic and service workers. Standard employment contract mandated. Minimum wage SAR 1,500/month. Weekly rest day guaranteed. Employer-pays recruitment fees. End-of-service benefits: SAR 1,500 per year of service. Disputes resolved via Saudi Labour Court.",
        "source": "DMW / Department of Labour (Saudi Arabia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-AE",
        "corridor": "PH-AE",
        "title": "Philippines-UAE Labour Cooperation MOU (2018)",
        "summary": "Covers domestic, hospitality, and services sectors. Standard contract with AED minimum wage. Free visa and ticket guaranteed for Filipino workers. Employer-pays recruitment. 2023 amendments: domestic workers' right to communicate freely and keep identity documents.",
        "source": "Ministry of Labour (UAE) / POLO Abu Dhabi",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-KW",
        "corridor": "PH-KW",
        "title": "Philippines-Kuwait Labour Agreement",
        "summary": "Domestic and service workers covered. Minimum wage KWD 110/month. Employer-provided accommodation and food. Standard contract verification by Philippine embassy. Kafala sponsorship system still applies. Dispute resolution through Kuwait Labour Court.",
        "source": "Philippines Ministry of Labour / POLO Kuwait City",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-QA",
        "corridor": "PH-QA",
        "title": "Philippines-Qatar Labour Cooperation Agreement (Amended 2020)",
        "summary": "Government-to-government recruitment framework. Qatar's 2020 kafala reform: workers can change employers without sponsor consent, minimum QAR 1,000/month wage floor, monthly wage payments mandatory. Joint committee monitors compliance. Free-visa policy for eligible workers.",
        "source": "Ministry of Administrative Development (Qatar) / DMW",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-JO",
        "corridor": "PH-JO",
        "title": "Philippines-Jordan Labour Cooperation MOU",
        "summary": "Covers hospitality, construction, and service sectors. Government-managed recruitment through POEA. Jordan Compact provisions: refugee workers integrated. Wage protection mechanism in place. Annual review of implementation by joint committee.",
        "source": "Ministry of Labour (Jordan) / POEA",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-KR",
        "corridor": "PH-KR",
        "title": "Philippines-Korea Employment Permit System (EPS) Agreement",
        "summary": "Government-to-government recruitment for manufacturing, agriculture, construction, fishing, and services. Korean Language Test (EPS-TOPIK) required for eligibility. Maximum employment: 4 years 10 months. Total recruitment cost capped at approximately USD 1,000. No private intermediaries involved.",
        "source": "Ministry of Labour (Korea) / POEA",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-JP",
        "corridor": "PH-JP",
        "title": "Philippines-Japan Economic Partnership Agreement (JPEPA) Labour Provisions (2008)",
        "summary": "Enables deployment of Filipino nurses and caregivers under specific eligibility: nursing license, Japanese national exam passage within 3-4 years. Also covers TITP technical interns and SSW (Specified Skilled Worker) program. Government-managed through POEA and Japanese organizations.",
        "source": "Cabinet Office of Japan / POEA",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-MY",
        "corridor": "PH-MY",
        "title": "Philippines-Malaysia Labour Cooperation MOU",
        "summary": "Covers domestic, manufacturing, and plantation workers. Government-to-government recruitment target of zero-cost for workers. Malaysia's mandatory standard contract (MTCS). Worker grievance mechanism through Philippine embassy. Irregular worker regularization provisions.",
        "source": "Ministry of Human Resources (Malaysia) / POEA",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-HK",
        "corridor": "PH-HK",
        "title": "Philippines-Hong Kong Standard Employment Contract Regime (2003, Updated 2023)",
        "summary": "Mandatory standard contract (SEC) for all foreign domestic helpers. Minimum wage HKD 4,870/month (2023 rate). Free accommodation and food mandatory or HKD 1,236 monthly allowance. Rest days mandatory. Medical insurance and return airfare by employer. POLO verifies all contracts before employment.",
        "source": "Immigration Department (Hong Kong) / POLO Hong Kong",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-SG",
        "corridor": "PH-SG",
        "title": "Philippines-Singapore Domestic Worker Regulation Framework (2019)",
        "summary": "Mandatory work contracts approved by Ministry of Manpower. Minimum wage SGD 1,000/month for new contracts. Employer-provided accommodations. In-country training requirements. Quarterly medical check-ups. 2019 amendments: workers' rest day entitlement clarification and enhanced leave provisions.",
        "source": "Ministry of Manpower (Singapore) / POLO Singapore",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-TW",
        "corridor": "PH-TW",
        "title": "Philippines-Taiwan Labour Cooperation Agreement",
        "summary": "Covers manufacturing, construction, and domestic sectors. Taiwan's regulated recruitment system with POEA cooperation. Mandatory medical examination and contract verification. Wage floor TWD 23,800/month. Foreign workers' rights protected through labor inspections.",
        "source": "Council of Labour Affairs (Taiwan) / POEA",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-CA",
        "corridor": "PH-CA",
        "title": "Philippines-Canada Labour Mobility Agreement (Bilateral Framework)",
        "summary": "Covers temporary foreign worker (TFW) program. Approved employer list system. Mandatory labor market opinion (LMO) for non-designated occupations. Worker protections: housing, transportation, wage protection clauses. Bilateral consultations on program improvements.",
        "source": "Citizenship and Immigration Canada / Bureau of Labour Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-UK",
        "corridor": "PH-UK",
        "title": "Philippines-United Kingdom Health and Social Care Worker Scheme (2022)",
        "summary": "Health care visa route for nurses and care workers. Post-Brexit points-based immigration system. Salary threshold: minimum GBP 20,480/year. Pathways to permanent residence after 5 years. NHS and care sector employers regulated. Bilateral consultation ongoing on expansion.",
        "source": "UK Home Office / Department of Health and Social Care",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-BH",
        "corridor": "PH-BH",
        "title": "Philippines-Bahrain Labour Cooperation Agreement",
        "summary": "Covers domestic and service workers. Mandatory standard contract system. Minimum wage BHD 300/month for domestic workers. Employer-pays recruitment fees. Kafala system applies but reformed: workers obtain first work permit independently. Annual agreement review by joint committee.",
        "source": "Ministry of Labour (Bahrain) / DMW",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-OM",
        "corridor": "PH-OM",
        "title": "Philippines-Oman Labour Agreement",
        "summary": "Covers domestic workers and hospitality staff. Minimum wage OMR 150/month. Contract registration with Ministry of Labour required. Employer-provides accommodations. Dispute resolution through Oman Labour Tribunal. Periodic agreement reviews on implementation.",
        "source": "Ministry of Labour and Social Welfare (Oman)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-AUS",
        "corridor": "PH-AUS",
        "title": "Philippines-Australia Visa Subclass 482 & 186 Arrangements",
        "summary": "Skilled migration program for Philippine professionals. Temporary Skill Shortage visa (482) for up to 4 years. Employer Nomination Scheme (186) for permanent residency. Mandatory skills assessment. Wage levels match Australian standards. Bilateral cooperation on credential recognition.",
        "source": "Department of Home Affairs (Australia) / Bureau of Labour Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-NZ",
        "corridor": "PH-NZ",
        "title": "Philippines-New Zealand Essential Skills Work Visa Arrangement",
        "summary": "Skilled and semi-skilled worker visas for 1-3 year contracts. Employer accreditation system. Point-based assessment. Health and character requirements. Wage rates monitored to match NZ standards. Bilateral labor market assessments annually.",
        "source": "Department of Internal Affairs (New Zealand)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-CH",
        "corridor": "PH-CH",
        "title": "Philippines-Switzerland Bilateral Labour Mobility Framework",
        "summary": "Focuses on skilled workers in sectors with labor shortages. Swiss sectoral quotas and authorization system. Bilateral negotiation on number of work permits issued. Wage and working condition minimums enforced. Annual review and adjustment mechanism.",
        "source": "State Secretariat for Migration (Switzerland) / Bureau of Labour Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-IS",
        "corridor": "PH-IS",
        "title": "Philippines-Iceland Labour Mobility Agreement",
        "summary": "Small-scale agreement for skilled workers in specific sectors (healthcare, tourism). Work permit caps. Icelandic labor standards must be respected. Government-sponsored orientation programs. Annual bilateral consultations on program expansion.",
        "source": "Ministry of Welfare (Iceland) / Department of Labour",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-PT",
        "corridor": "PH-PT",
        "title": "Philippines-Portugal Labour Cooperation MOU",
        "summary": "EU-based agreement for skilled workers. Portuguese Language Test preferred for professionals. Credential recognition mechanisms established. Working conditions aligned with Portuguese Labour Code. Government placement services available through both countries.",
        "source": "Ministry of Labour (Portugal) / Bureau of Labour Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-MY",
        "corridor": "NP-MY",
        "title": "Nepal-Malaysia Government-to-Government Recruitment MOU",
        "summary": "Zero-cost recruitment policy: employers bear all costs including visa, ticket, medical, and training. Manufacturing, plantation, construction, and services sectors covered. Nepal Foreign Employment Board (NFEB) verification. Contract in Nepali and English mandatory. Annual review of implementation.",
        "source": "Ministry of Overseas Nepali Workers / Ministry of Human Resources (Malaysia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-QA",
        "corridor": "NP-QA",
        "title": "Nepal-Qatar Free Visa & Free Ticket Policy (2019 Reaffirmed)",
        "summary": "Government-to-government recruitment ensuring zero-cost employment for Nepali workers. Employer bears all recruitment, visa, and travel costs. Joint committee monitors demand letters. Qatar's 2020 kafala reform: workers can change jobs after first year. Annual agreement review.",
        "source": "Ministry of Overseas Nepali Workers / Ministry of Administrative Development (Qatar)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-SA",
        "corridor": "NP-SA",
        "title": "Nepal-Saudi Arabia Labour Cooperation Agreement",
        "summary": "Construction, domestic, and service workers covered. Minimum wage SAR 1,500/month. Standard contract system. Employer-pays recruitment fees. Nepal monitors contract compliance pre-deployment. Dispute resolution through Saudi Labour Court. Annual bilateral coordination meetings.",
        "source": "Ministry of Labour and Employment (Saudi Arabia) / Foreign Employment Board",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-KR",
        "corridor": "NP-KR",
        "title": "Nepal-Korea Employment Permit System (EPS) Bilateral Framework",
        "summary": "Government-managed recruitment with zero private agency involvement. Korean Language Proficiency Test (EPS-TOPIK) required. Manufacturing, agriculture, construction, fishing, services eligible. Total recruitment cost: ~USD 850. Maximum stay: 4 years 10 months. Annual quota agreed bilaterally.",
        "source": "Ministry of Labour (Korea) / NFEB",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-JP",
        "corridor": "NP-JP",
        "title": "Nepal-Japan Technical Intern Training Program (TITP) & SSW MOU",
        "summary": "TITP pathway for training and skills transfer in manufacturing, construction, hospitality. SSW (Specified Skilled Worker) program allows 5 years stay for 14 designated sectors. Nepal Ministry oversees sending organizations. Japanese Language Test requirements. Government-level implementation monitoring.",
        "source": "Japan Ministry of Health, Labour and Welfare / NFEB",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-AE",
        "corridor": "NP-AE",
        "title": "Nepal-UAE Labour Cooperation MOU (2020 Renewed)",
        "summary": "Covers construction, hospitality, and service sectors. Free visa and ticket policy reaffirmed. Minimum wage floor: AED 2,500/month. Standard contract mandatory. 2023 amendments: worker communication rights and identity document retention. Joint committee reviews grievances quarterly.",
        "source": "Ministry of Human Resources and Emiratisation (UAE) / NFEB",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-KW",
        "corridor": "NP-KW",
        "title": "Nepal-Kuwait Labour Agreement (Reformation 2021)",
        "summary": "Domestic and service workers. Minimum wage KWD 110/month. Mandatory contract registration with Ministry. Employer-paid recruitment fees. Kuwait's partial kafala reform: workers can negotiate job changes after 2 years. Bilateral monitoring of dispute resolution.",
        "source": "Ministry of Labour (Kuwait) / Foreign Employment Board",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-BH",
        "corridor": "NP-BH",
        "title": "Nepal-Bahrain Labour Cooperation Agreement",
        "summary": "Construction, service, and domestic sectors. Minimum wage BHD 350/month. Free visa and ticket policy. Standard contract verification by Nepali embassy. Bahrain's reformed kafala system: workers obtain work permits independently. Annual agreement review.",
        "source": "Ministry of Labour (Bahrain) / Foreign Employment Board",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-OM",
        "corridor": "NP-OM",
        "title": "Nepal-Oman Labour Cooperation MOU",
        "summary": "Covers construction, hospitality, and domestic work. Minimum wage OMR 170/month. Employer-provided accommodations mandatory. Contract registration with Ministry of Labour required. Dispute resolution through Oman Labour Tribunal. Annual bilateral review of implementation metrics.",
        "source": "Ministry of Labour and Social Welfare (Oman) / NFEB",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-TH",
        "corridor": "NP-TH",
        "title": "Nepal-Thailand Labour Cooperation MOU",
        "summary": "Manufacturing, agriculture, fishing, and construction sectors covered. Zero-cost recruitment target. Government-managed placement through Thai Ministry. Nationality verification process. Border cooperation on trafficking prevention. Annual quota agreements.",
        "source": "Ministry of Labour (Thailand) / Nepal Foreign Employment Board",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-CA",
        "corridor": "NP-CA",
        "title": "Nepal-Canada International Mobility Program (IMP) Framework",
        "summary": "Skilled worker entry under approved employer sponsorship. Employer compliance required on wage and working standards. Bilateral consultation on sectoral needs. Credential recognition pathway discussions. Annual review of labor market impact.",
        "source": "Immigration, Refugees and Citizenship Canada / Labour Ministry",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-UK",
        "corridor": "NP-UK",
        "title": "Nepal-United Kingdom Points-Based Skilled Worker Visa Framework",
        "summary": "Post-Brexit arrangement for Nepali skilled professionals. Health and care workers priority route. Salary threshold GBP 20,480/year. English language requirements. Credential recognition for nursing and engineering. Bilateral labor market assessments ongoing.",
        "source": "UK Home Office / Nepal Ministry of Labour",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-SG",
        "corridor": "NP-SG",
        "title": "Nepal-Singapore Work Pass Arrangement",
        "summary": "Skilled worker passes (P1/P2) and work permits for semi-skilled. Ministry of Manpower registration mandatory. Wage rates monitored. Skills training integration for low-skilled workers. Bilateral consultation on sectoral demands.",
        "source": "Ministry of Manpower (Singapore) / Labour Ministry",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-HK",
        "corridor": "NP-HK",
        "title": "Nepal-Hong Kong Work Visa Framework for Skilled Workers",
        "summary": "General employment category and domestic worker visa routes. Work visa requirements: job offer and Hong Kong employer sponsorship. Domestic worker contracts follow SEC standards. Immigration Department enforcement. Bilateral cooperation on skill recognition.",
        "source": "Immigration Department (Hong Kong) / Labour Ministry",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-IN",
        "corridor": "NP-IN",
        "title": "Nepal-India Labour Corridor (Intra-South Asian Agreement)",
        "summary": "Covers low-skilled and semi-skilled workers to Indian manufacturing and services sectors. Bilateral MOU ensuring contract standards. Wage floor: INR 15,000/month for industrial workers. Government verification process. Dispute resolution through Indian Labour Board.",
        "source": "Ministry of Labour (India) / Nepal Foreign Employment Board",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-AU",
        "corridor": "NP-AU",
        "title": "Nepal-Australia Skilled Migration & TSS 482 Visa Arrangement",
        "summary": "Skilled occupation list (SOL) and TSS visa (subclass 482) for occupations in demand. Employer accreditation required. Labor market testing for some occupations. Wage standards enforcement by Fair Work Commission. Annual bilateral review of occupation demand.",
        "source": "Department of Home Affairs (Australia) / Labour Ministry",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-MW",
        "corridor": "NP-MW",
        "title": "Nepal-Malawi Labour Cooperation MOU (Development Corridor)",
        "summary": "Emerging corridor for agricultural development projects. Government-sponsored recruitment for agricultural training and labor. Limited scale. Bilateral monitoring of working conditions. Skills transfer component emphasized. Annual review of project outcomes.",
        "source": "Ministry of Labour (Malawi) / Nepal Foreign Employment Board",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-MY",
        "corridor": "BD-MY",
        "title": "Bangladesh-Malaysia G2G Recruitment System (2009, Expanded)",
        "summary": "Eliminates private recruitment agencies. Government-to-government system through BMET (Bangladesh) and Ministry of Human Resources (Malaysia). Fixed recruitment costs capped. Manufacturing, plantation, construction, services. Worker grievance portal established. Zero-cost target for workers.",
        "source": "Bureau of Manpower Employment and Training (BMET) / Ministry of Human Resources (Malaysia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-SA",
        "corridor": "BD-SA",
        "title": "Bangladesh-Saudi Arabia Labour Agreement (2017 Revised)",
        "summary": "Domestic, construction, and service workers covered. Minimum wage SAR 1,500/month. Mandatory standard contract. BMET monitors sending side compliance. Employer-pays recruitment fees (though often circumvented). Dispute resolution through Saudi Labour Court. Annual agreement review.",
        "source": "Ministry of Labour (Saudi Arabia) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-QA",
        "corridor": "BD-QA",
        "title": "Bangladesh-Qatar Labour MOU (2020 Reaffirmed)",
        "summary": "Government-to-government recruitment framework. Qatar's 2020 kafala reforms: workers change employers without sponsor permission after 3 months. Free visa and ticket policy. Minimum wage QAR 1,000/month. Joint committee monitors implementation quarterly. Standard contract mandatory.",
        "source": "Ministry of Administrative Development (Qatar) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-AE",
        "corridor": "BD-AE",
        "title": "Bangladesh-UAE Labour Cooperation Agreement (2021 Updated)",
        "summary": "Construction, hospitality, and service sectors. Free visa policy reaffirmed. Minimum wage AED 2,500/month. 2023 amendments: enhanced worker communication rights, document security. Joint committee on labor disputes. Bilateral inspection teams monitor workplace conditions.",
        "source": "Ministry of Human Resources and Emiratisation (UAE) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-KW",
        "corridor": "BD-KW",
        "title": "Bangladesh-Kuwait Labour Agreement",
        "summary": "Domestic workers and services. Minimum wage KWD 110/month. Mandatory contract with Ministry registration. BMET verifies employment contracts before departure. Employer-paid recruitment fees. Kuwait's partial kafala reform: workers negotiate employer changes after 2 years of service.",
        "source": "Ministry of Labour (Kuwait) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-JO",
        "corridor": "BD-JO",
        "title": "Bangladesh-Jordan Labour Cooperation MOU",
        "summary": "Construction and service sectors. Government-to-government recruitment. Jordan Compact integration for refugee workers. Wage protection: JOD 400/month minimum. BMET pre-departure verification. Annual joint review of agreement implementation.",
        "source": "Ministry of Labour (Jordan) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-OM",
        "corridor": "BD-OM",
        "title": "Bangladesh-Oman Labour Cooperation MOU",
        "summary": "Construction, hospitality, and domestic work. Minimum wage OMR 200/month. Employer-provided accommodations. Standard contract system. BMET monitors compliance through embassy. Annual bilateral review of labor conditions and dispute patterns.",
        "source": "Ministry of Labour and Social Welfare (Oman) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-BH",
        "corridor": "BD-BH",
        "title": "Bangladesh-Bahrain Labour Cooperation Agreement",
        "summary": "Domestic and service workers. Minimum wage BHD 350/month. Free ticket policy. Standard contract registration. Bahrain's reformed kafala: workers obtain permits independently after first employer assignment. Bilateral monitoring of implementation.",
        "source": "Ministry of Labour (Bahrain) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-TH",
        "corridor": "BD-TH",
        "title": "Bangladesh-Thailand Labour Cooperation Agreement",
        "summary": "Manufacturing, agriculture, and fishing sectors. Zero-cost recruitment target. Government-managed placement. Thai nationality verification for irregular workers. Trafficking prevention and border cooperation. Annual quota agreements and performance review.",
        "source": "Ministry of Labour (Thailand) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-SG",
        "corridor": "BD-SG",
        "title": "Bangladesh-Singapore Work Pass Framework",
        "summary": "Semi-skilled and low-skilled worker categories. MOM registration mandatory. Wage monitoring and employment standards enforcement. BMET coordination on skills certification. Bilateral consultation on sectoral labor demands.",
        "source": "Ministry of Manpower (Singapore) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-KR",
        "corridor": "BD-KR",
        "title": "Bangladesh-Korea EPS Bilateral Framework",
        "summary": "Government-managed recruitment system. Korean language test (EPS-TOPIK) required. Manufacturing, construction, agriculture eligible. Total cost ~USD 1,000 (shared between worker and employer). No private agencies. Contract duration: up to 4 years 10 months.",
        "source": "Ministry of Labour (Korea) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-JP",
        "corridor": "BD-JP",
        "title": "Bangladesh-Japan TITP/SSW Cooperation MOU",
        "summary": "Technical Intern Training and Specified Skilled Worker programs. BMET manages sending organizations. Japanese Language Proficiency Test (JLPT) required for SSW route. 14 eligible sectors for SSW. Government monitoring of TITP trainee protections.",
        "source": "Japan Ministry of Health, Labour and Welfare / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-HK",
        "corridor": "BD-HK",
        "title": "Bangladesh-Hong Kong Domestic Worker Framework",
        "summary": "Mandatory Standard Employment Contract (SEC) for all foreign domestic helpers. Minimum wage HKD 4,870/month. Free accommodation and food or allowance. BMET verification pre-departure. Immigration Department Hong Kong enforces SEC compliance. Annual review of contract standards.",
        "source": "Immigration Department (Hong Kong) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-MY",
        "corridor": "BD-MY",
        "title": "Bangladesh-Malaysia Domestic Worker Subcommittee (2023)",
        "summary": "Enhanced protections specifically for domestic workers in G2G system. Mandatory mobile phone possession. At least one day rest per week. Kitchen access and adequate food. Medical insurance mandatory. BMET conducts random monitoring of work premises.",
        "source": "Ministry of Human Resources (Malaysia) / BMET Domestic Worker Unit",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-CA",
        "corridor": "BD-CA",
        "title": "Bangladesh-Canada International Mobility Program Framework",
        "summary": "Skilled and semi-skilled worker entry under employer sponsorship. Labor market impact assessment for some categories. Wage standards enforcement through Employment Standards. Annual bilateral review of program outcomes and worker feedback.",
        "source": "Immigration, Refugees and Citizenship Canada / Ministry of Labour",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-SA",
        "corridor": "ID-SA",
        "title": "Indonesia-Saudi Arabia MOU on Domestic Worker Protection (2014, Renewed 2021)",
        "summary": "Standard employment contract mandated. Employer-pays recruitment fees (frequently violated). Minimum wage SAR 1,500/month. Free accommodations and food. Weekly rest day. Indonesia suspended deployment multiple times (2009, 2011, 2015) due to abuse; resumed with enhanced monitoring protocol in 2021.",
        "source": "Ministry of Manpower (Indonesia) / Ministry of Labour (Saudi Arabia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-MY",
        "corridor": "ID-MY",
        "title": "Indonesia-Malaysia Labour Recruitment & Placement MOU (2009, Expanded)",
        "summary": "Covers domestic, plantation, manufacturing, and construction workers. Employer-pays principle established but enforcement weak. Standard contract mandatory. Government-to-government channel plus licensed private agencies. Indonesia suspended deployment in 2009 over abuse; resumed 2011 with enhanced verification.",
        "source": "Ministry of Manpower (Indonesia) / Ministry of Human Resources (Malaysia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-JP",
        "corridor": "ID-JP",
        "title": "Indonesia-Japan TITP & SSW MOU (2023 Expanded)",
        "summary": "Technical Intern Training Program and Specified Skilled Worker framework. BNP2MI (Indonesia's sending organization) government-regulated. Japanese Language Proficiency Test required. 14 SSW-eligible sectors: nursing, care, shipbuilding, automotive, etc. 5-year SSW contract duration. Government monitoring of trainee conditions.",
        "source": "Japan Ministry of Health, Labour and Welfare / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-KR",
        "corridor": "ID-KR",
        "title": "Indonesia-Korea EPS (Employment Permit System) Bilateral Framework",
        "summary": "Government-managed recruitment system eliminating private agencies. Korean language test (EPS-TOPIK) mandatory. Manufacturing, agriculture, construction, fishing, services eligible. Total cost: ~USD 1,000. Maximum stay: 4 years 10 months. Annual quota negotiated bilaterally.",
        "source": "Ministry of Labour (Korea) / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-HK",
        "corridor": "ID-HK",
        "title": "Indonesia-Hong Kong Domestic Worker Standard Contract Framework",
        "summary": "Mandatory Standard Employment Contract (SEC) for all foreign domestic helpers. Minimum wage HKD 4,870/month. Free accommodation and food (or HKD 1,236 allowance). POLO Jakarta verifies contracts. Immigration Department Hong Kong enforces compliance. Annual SEC rate reviews and enhancement discussions.",
        "source": "Immigration Department (Hong Kong) / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-SG",
        "corridor": "ID-SG",
        "title": "Indonesia-Singapore Work Permit & Domestic Worker Agreement",
        "summary": "Domestic worker contracts approved by Ministry of Manpower. Minimum wage SGD 1,000/month for new employees. Employer-provided accommodations. Work permit quotas by sector. In-country training and skills certification pathways. Bilateral labor standards enforcement.",
        "source": "Ministry of Manpower (Singapore) / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-TW",
        "corridor": "ID-TW",
        "title": "Indonesia-Taiwan Labour Cooperation Agreement",
        "summary": "Manufacturing, construction, and care work sectors. Taiwan's regulated recruitment system. BIMIL (Indonesia's labor migration office) coordinates. Mandatory medical examination and contract verification. Wage floor: TWD 27,470/month (2023). Inspection and enforcement by Taiwan Labor Bureau.",
        "source": "Council of Labour Affairs (Taiwan) / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-AE",
        "corridor": "ID-AE",
        "title": "Indonesia-UAE Labour Cooperation MOU (2017, 2023 Enhanced)",
        "summary": "Construction, hospitality, and domestic sectors. Free visa policy for workers in G2G system. Minimum wage AED 2,500/month. 2023 amendments: enhanced document security, communication rights, periodic grievance reviews. UAE's reformed kafala: workers change employers after first year.",
        "source": "Ministry of Human Resources and Emiratisation (UAE) / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-QA",
        "corridor": "ID-QA",
        "title": "Indonesia-Qatar Labour Cooperation Agreement (2020 Reaffirmed)",
        "summary": "Government-to-government recruitment. Qatar's 2020 kafala reform: workers change jobs without sponsor consent after 3 months. Free visa and ticket. Minimum wage QAR 1,000/month. Standard contract mandatory. Joint committee monitors implementation.",
        "source": "Ministry of Administrative Development (Qatar) / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-KW",
        "corridor": "ID-KW",
        "title": "Indonesia-Kuwait Labour Agreement",
        "summary": "Domestic and service workers. Minimum wage KWD 110/month. Mandatory contract with Ministry registration. BNP2MI verifies employment. Employer-paid recruitment. Kuwait's partial kafala reform: workers negotiate employer changes after 2 years of service. Annual agreement review.",
        "source": "Ministry of Labour (Kuwait) / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-TH",
        "corridor": "ID-TH",
        "title": "Indonesia-Thailand Labour Cooperation MOU",
        "summary": "Manufacturing, agriculture, fishing, construction, and domestic work. Zero-cost recruitment target. Government-managed placement through Thai Ministry. Nationality verification and trafficking prevention mechanism. Bilateral border cooperation agreements. Annual quota and performance review.",
        "source": "Ministry of Labour (Thailand) / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-BN",
        "corridor": "ID-BN",
        "title": "Indonesia-Brunei Labour Cooperation Agreement",
        "summary": "Oil and gas, construction, hospitality sectors. Government-approved recruitment. BNP2MI coordination with Brunei Ministry of Home Affairs. Wage standards monitoring. Bilateral review of working conditions. Focus on professional and semi-skilled workers.",
        "source": "Ministry of Home Affairs (Brunei) / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-CA",
        "corridor": "ID-CA",
        "title": "Indonesia-Canada International Mobility Program Framework",
        "summary": "Skilled and semi-skilled worker entry under employer sponsorship. Approved employer list system. Labor market impact assessment for occupations in demand. Wage and working condition minimums enforced. Annual bilateral review of program metrics.",
        "source": "Immigration, Refugees and Citizenship Canada / Ministry of Manpower",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ID-AU",
        "corridor": "ID-AU",
        "title": "Indonesia-Australia Skilled Migration & TSS 482 Arrangement",
        "summary": "Skilled occupation list (SOL) and Temporary Skill Shortage visa (482). Employer accreditation required. Labor market testing for non-designated occupations. Fair Work Commission enforces wage standards. Annual bilateral review of occupation demand and program outcomes.",
        "source": "Department of Home Affairs (Australia) / Ministry of Manpower (Indonesia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-SA",
        "corridor": "IN-SA",
        "title": "India-Saudi Arabia Labour Cooperation Agreement",
        "summary": "Covers construction, services, and domestic workers. Minimum wage SAR 1,500/month. Standard contract system. Employer-pays recruitment. Indian embassy monitors compliance. Dispute resolution through Saudi Labour Court. Annual bilateral review of implementation metrics.",
        "source": "Ministry of Overseas Indian Affairs / Ministry of Labour (Saudi Arabia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-AE",
        "corridor": "IN-AE",
        "title": "India-UAE Labour Cooperation MOU (2023 Updated)",
        "summary": "Construction, hospitality, services sectors. Free visa policy for eligible workers. Minimum wage AED 2,500/month. 2023 amendments: enhanced worker rights, communication freedom, document security. UAE's reformed kafala: workers change employers after first year of service.",
        "source": "Ministry of Human Resources and Emiratisation (UAE) / Ministry of External Affairs (India)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-QA",
        "corridor": "IN-QA",
        "title": "India-Qatar Labour Cooperation MOU (2020 Reaffirmed)",
        "summary": "Government-to-government recruitment. Qatar's 2020 kafala reforms: workers change jobs without sponsor consent after 3 months. Free visa and ticket policy. Minimum wage QAR 1,000/month. Joint committee monitors quarterly. Standard contract mandatory.",
        "source": "Ministry of Administrative Development (Qatar) / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-KW",
        "corridor": "IN-KW",
        "title": "India-Kuwait Labour Agreement",
        "summary": "Services and domestic workers. Minimum wage KWD 110/month. Mandatory contract registration. Employer-pays recruitment fees. Kuwait's partial kafala reform: workers negotiate employer changes after 2 years. Bilateral monitoring of agreement implementation.",
        "source": "Ministry of Labour (Kuwait) / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-OM",
        "corridor": "IN-OM",
        "title": "India-Oman Labour Cooperation MOU",
        "summary": "Construction, hospitality, and service sectors. Minimum wage OMR 250/month. Employer-provided accommodations mandatory. Contract registration with Ministry of Labour. Dispute resolution through Oman Labour Tribunal. Annual bilateral review of labor condition surveys.",
        "source": "Ministry of Labour and Social Welfare (Oman) / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-BH",
        "corridor": "IN-BH",
        "title": "India-Bahrain Labour Cooperation Agreement",
        "summary": "Services and domestic workers. Minimum wage BHD 350/month. Free ticket policy. Standard contract mandatory. Bahrain's reformed kafala: workers obtain permits independently after first employer assignment. Bilateral monitoring of implementation.",
        "source": "Ministry of Labour (Bahrain) / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-JP",
        "corridor": "IN-JP",
        "title": "India-Japan Skilled Nursing Care Worker MOU",
        "summary": "Nurses, nursing care workers eligible. Japanese national exam passage required within 3-4 years. Sponsorship by approved hospitals and care facilities. Government-level coordination. Pathway to permanent residency after 5 years. Annual bilateral review of training and pass rates.",
        "source": "Japan Ministry of Health, Labour and Welfare / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-KR",
        "corridor": "IN-KR",
        "title": "India-Korea EPS (Employment Permit System) Framework",
        "summary": "Government-managed recruitment. Korean Language Proficiency Test (EPS-TOPIK) required. Manufacturing, agriculture, construction eligible. Total cost ~USD 1,100. Maximum stay: 4 years 10 months. No private intermediaries. Annual bilateral quota negotiations.",
        "source": "Ministry of Labour (Korea) / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-UK",
        "corridor": "IN-UK",
        "title": "India-United Kingdom Health and Social Care Worker Scheme (2022, Expanded 2024)",
        "summary": "Health care visa route for Indian nurses and care professionals. Post-Brexit points-based system. Salary minimum GBP 20,480/year. NHS and care employers regulated. Pathways to permanent residence after 5 years. Credential recognition framework for Indian nursing qualifications.",
        "source": "UK Home Office / Department of Health and Social Care",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-CA",
        "corridor": "IN-CA",
        "title": "India-Canada International Mobility Program",
        "summary": "Skilled workers under employer sponsorship. Approved employer framework. Labor market impact assessment for occupations in demand. Wage protection and working condition standards. Annual bilateral review of program outcomes and worker feedback.",
        "source": "Immigration, Refugees and Citizenship Canada / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-AU",
        "corridor": "IN-AU",
        "title": "India-Australia Skilled Migration & TSS 482 Arrangement",
        "summary": "Skilled occupation list (SOL) and Temporary Skill Shortage visa (482). Employer accreditation required. Fair Work Commission enforces wage standards. Labor market testing for occupations in demand. Annual bilateral review of skilled migration outcomes.",
        "source": "Department of Home Affairs (Australia) / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-SG",
        "corridor": "IN-SG",
        "title": "India-Singapore Work Pass & Professional Entry Framework",
        "summary": "Work passes (P1/P2) for skilled professionals. MOM registration mandatory. Wage rates monitored and maintained above minimums. Sector-specific skills certification. Bilateral cooperation on credential recognition for professional bodies (engineers, accountants).",
        "source": "Ministry of Manpower (Singapore) / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-SA",
        "corridor": "LK-SA",
        "title": "Sri Lanka-Saudi Arabia Labour Agreement",
        "summary": "Domestic workers and services. Minimum wage SAR 1,500/month. Standard contract system. SLBFE (Sri Lanka Bureau of Foreign Employment) verifies contracts. Employer-pays recruitment. Dispute resolution through Saudi Labour Court. Annual agreement review.",
        "source": "Ministry of Labour (Saudi Arabia) / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-AE",
        "corridor": "LK-AE",
        "title": "Sri Lanka-UAE Labour Cooperation MOU (2021 Enhanced)",
        "summary": "Domestic and service workers. Free visa policy. Minimum wage AED 2,500/month. 2023 amendments: communication rights, document security, periodic welfare checks. UAE reformed kafala: workers change employers after first year. Quarterly joint committee meetings.",
        "source": "Ministry of Human Resources and Emiratisation (UAE) / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-QA",
        "corridor": "LK-QA",
        "title": "Sri Lanka-Qatar Labour Cooperation Agreement (2020 Reaffirmed)",
        "summary": "Government-to-government recruitment. Qatar's 2020 kafala reform: workers change jobs after 3 months without sponsor consent. Free visa and ticket. Minimum wage QAR 1,000/month. Standard contract mandatory. Joint committee monitors quarterly.",
        "source": "Ministry of Administrative Development (Qatar) / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-KW",
        "corridor": "LK-KW",
        "title": "Sri Lanka-Kuwait Labour Agreement",
        "summary": "Domestic and service workers. Minimum wage KWD 110/month. Mandatory contract registration. Employer-paid recruitment fees. Kuwait's partial kafala reform: workers negotiate changes after 2 years. Bilateral monitoring of implementation.",
        "source": "Ministry of Labour (Kuwait) / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-BH",
        "corridor": "LK-BH",
        "title": "Sri Lanka-Bahrain Labour Cooperation Agreement",
        "summary": "Domestic workers. Minimum wage BHD 350/month. Free ticket policy. Standard contract mandatory. Bahrain's reformed kafala: workers obtain permits independently. Bilateral monitoring of working conditions and grievances.",
        "source": "Ministry of Labour (Bahrain) / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-OM",
        "corridor": "LK-OM",
        "title": "Sri Lanka-Oman Labour Cooperation MOU",
        "summary": "Domestic and service workers. Minimum wage OMR 200/month. Employer-provided accommodations. Standard contract system. SLBFE monitors compliance through embassy. Annual bilateral review of labor conditions.",
        "source": "Ministry of Labour and Social Welfare (Oman) / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-JP",
        "corridor": "LK-JP",
        "title": "Sri Lanka-Japan TITP/SSW Cooperation MOU",
        "summary": "Technical Intern Training and Specified Skilled Worker programs. SLBFE manages sending organizations. Japanese Language Test required. 14 SSW-eligible sectors. Government monitoring of trainee protections and conditions.",
        "source": "Japan Ministry of Health, Labour and Welfare / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-KR",
        "corridor": "LK-KR",
        "title": "Sri Lanka-Korea EPS Bilateral Framework",
        "summary": "Government-managed recruitment system. Korean language test (EPS-TOPIK) required. Manufacturing, agriculture, construction sectors. Total cost ~USD 1,000. Maximum stay: 4 years 10 months. No private agencies. Annual quota negotiations.",
        "source": "Ministry of Labour (Korea) / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-MY",
        "corridor": "LK-MY",
        "title": "Sri Lanka-Malaysia Labour Cooperation MOU",
        "summary": "Manufacturing and domestic workers. Government-to-government recruitment. Mandatory contract system. SLBFE verification. Employer-pays recruitment (target). Zero-cost for workers principle. Annual agreement review.",
        "source": "Ministry of Human Resources (Malaysia) / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-HK",
        "corridor": "LK-HK",
        "title": "Sri Lanka-Hong Kong Domestic Worker Framework",
        "summary": "Mandatory Standard Employment Contract (SEC) for all foreign domestic helpers. Minimum wage HKD 4,870/month. Free accommodation and food (or allowance). SLBFE verification pre-departure. Immigration Department enforcement. Annual SEC rate review discussions.",
        "source": "Immigration Department (Hong Kong) / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-JP",
        "corridor": "VN-JP",
        "title": "Vietnam-Japan TITP/SSW Framework (2023 Expanded)",
        "summary": "Technical Intern Training Program (TITP) and Specified Skilled Worker (SSW) frameworks. Vietnam sending organizations regulated by DOLAB. JLPT required for SSW. SSW allows direct employment and job changes. 14 eligible sectors for SSW. 5-year SSW contract duration.",
        "source": "Japan Ministry of Health, Labour and Welfare / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-KR",
        "corridor": "VN-KR",
        "title": "Vietnam-Korea EPS (Employment Permit System) Framework",
        "summary": "Government-managed recruitment system. Korean language test (EPS-TOPIK) required. Manufacturing, agriculture, construction, fishing, services eligible. Total cost ~USD 1,000. Maximum stay: 4 years 10 months. No private agencies involved.",
        "source": "Ministry of Labour (Korea) / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-TW",
        "corridor": "VN-TW",
        "title": "Vietnam-Taiwan Labour Cooperation Agreement",
        "summary": "Manufacturing, construction, and care sectors. Taiwan's regulated recruitment system. DOLAB coordination. Mandatory medical examination and contract verification. Wage floor: TWD 27,470/month (2023). Labor Bureau inspection and enforcement.",
        "source": "Council of Labour Affairs (Taiwan) / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-MY",
        "corridor": "VN-MY",
        "title": "Vietnam-Malaysia Labour Cooperation MOU",
        "summary": "Manufacturing and construction sectors. Government-to-government recruitment. Mandatory contract system. Zero-cost recruitment target. DOLAB verification. Annual agreement review and implementation assessment.",
        "source": "Ministry of Human Resources (Malaysia) / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-TH",
        "corridor": "VN-TH",
        "title": "Vietnam-Thailand Labour Cooperation MOU",
        "summary": "Manufacturing, agriculture, and construction sectors. Zero-cost recruitment target. Government-managed placement. Bilateral cooperation on trafficking prevention. Border crossing protocols. Annual quota and performance review.",
        "source": "Ministry of Labour (Thailand) / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-SG",
        "corridor": "VN-SG",
        "title": "Vietnam-Singapore Work Permit Framework",
        "summary": "Semi-skilled and low-skilled workers. MOM registration mandatory. Wage monitoring. DOLAB coordination on skills certification. Bilateral consultation on sectoral labor demands. Contract standards enforcement.",
        "source": "Ministry of Manpower (Singapore) / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-HK",
        "corridor": "VN-HK",
        "title": "Vietnam-Hong Kong Work Visa Framework",
        "summary": "Skilled and semi-skilled worker categories. Employment visas issued by Immigration Department. Employer sponsorship required. Wage levels monitored. DOLAB coordination. Bilateral consultation on labor market needs.",
        "source": "Immigration Department (Hong Kong) / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-CA",
        "corridor": "VN-CA",
        "title": "Vietnam-Canada International Mobility Program Framework",
        "summary": "Skilled workers under employer sponsorship. Approved employer list system. Labor market impact assessment for occupations in demand. Wage and working condition minimums enforced. Annual bilateral review.",
        "source": "Immigration, Refugees and Citizenship Canada / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-AU",
        "corridor": "VN-AU",
        "title": "Vietnam-Australia Skilled Migration & TSS 482 Arrangement",
        "summary": "Skilled occupation list (SOL) and Temporary Skill Shortage visa (482). Employer accreditation required. Fair Work Commission wage enforcement. Labor market testing for occupations in demand. Annual bilateral review of migration outcomes.",
        "source": "Department of Home Affairs (Australia) / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-EU",
        "corridor": "VN-EU",
        "title": "Vietnam-European Union Labour Mobility Negotiations",
        "summary": "Ongoing multilateral discussions on labor mobility framework. Focus on skilled professionals and care workers. EU mobility partnerships model application. Bilateral credential recognition for nurses and engineers. Framework agreement expected 2025.",
        "source": "European Commission DG Migration / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MM-TH",
        "corridor": "MM-TH",
        "title": "Myanmar-Thailand MOU on Labour Cooperation (2018, Renewed 2023)",
        "summary": "Covers fishing, agriculture, manufacturing, construction, and domestic work. Zero-cost recruitment target. Nationality verification for undocumented workers. Border cooperation on trafficking. Government-managed placement system. Annual quota agreements and compliance review.",
        "source": "Ministry of Labour (Thailand) / Ministry of Labour, Immigration and Population (Myanmar)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MM-MY",
        "corridor": "MM-MY",
        "title": "Myanmar-Malaysia Labour Cooperation Framework",
        "summary": "Manufacturing, plantation, and services sectors. Government-to-government recruitment framework. Mandatory contract system. Zero-cost target for workers. Annual review and implementation monitoring.",
        "source": "Ministry of Human Resources (Malaysia) / Ministry of Labour (Myanmar)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MM-SG",
        "corridor": "MM-SG",
        "title": "Myanmar-Singapore Work Permit & Domestic Worker Framework",
        "summary": "Domestic and semi-skilled workers. MOM registration mandatory. Wage monitoring and employment standards. Bilateral cooperation on skills certification. Sectoral labor demand consultation.",
        "source": "Ministry of Manpower (Singapore) / Ministry of Labour (Myanmar)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MM-JP",
        "corridor": "MM-JP",
        "title": "Myanmar-Japan TITP/SSW Cooperation MOU",
        "summary": "Technical Intern Training and Specified Skilled Worker programs. Limited capacity due to political situation. Japanese Language Proficiency Test required for SSW. Government monitoring of trainee conditions when operational.",
        "source": "Japan Ministry of Health, Labour and Welfare / Ministry of Labour (Myanmar)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MM-KR",
        "corridor": "MM-KR",
        "title": "Myanmar-Korea EPS Framework (Limited Scope)",
        "summary": "Government-managed recruitment when operational. Korean language test (EPS-TOPIK) required. Manufacturing and construction sectors. Limited deployment capacity due to political circumstances. Bilateral discussions on program expansion when conditions permit.",
        "source": "Ministry of Labour (Korea) / Ministry of Labour (Myanmar)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MM-BN",
        "corridor": "MM-BN",
        "title": "Myanmar-Brunei Labour Cooperation Agreement",
        "summary": "Oil and gas, construction, and hospitality sectors. Government-approved recruitment. Limited scope due to political conditions. Bilateral review when regional stability improves.",
        "source": "Ministry of Home Affairs (Brunei) / Ministry of Labour (Myanmar)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MM-TW",
        "corridor": "MM-TW",
        "title": "Myanmar-Taiwan Labour Cooperation (Limited Framework)",
        "summary": "Manufacturing sector focus. Taiwan's regulated recruitment when Myanmar government operational. Wage and working condition standards. Limited deployment due to political situation.",
        "source": "Council of Labour Affairs (Taiwan) / Ministry of Labour (Myanmar)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MM-KH",
        "corridor": "MM-KH",
        "title": "Myanmar-Cambodia Labour Corridor (Emerging)",
        "summary": "Informal cross-border labor flows. Government discussions on formalization. Focus on agriculture and informal sectors. Bilateral framework development stage. Human trafficking prevention cooperation.",
        "source": "Ministry of Labour (Cambodia) / Ministry of Labour (Myanmar)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ET-SA",
        "corridor": "ET-SA",
        "title": "Ethiopia-Saudi Arabia Labour Agreement (2017, Resumed Post-Ban)",
        "summary": "Domestic workers covered. Resumed after 2013-2017 ban due to abuse. Minimum wage SAR 1,500/month. Standard contract for all workers. Employer-paid recruitment. Medical insurance mandatory. MOEA monitors compliance through embassy. Enforcement remains challenging due to sub-agent networks.",
        "source": "Ministry of Labour (Saudi Arabia) / Ministry of Labour (Ethiopia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ET-AE",
        "corridor": "ET-AE",
        "title": "Ethiopia-UAE Labour Cooperation MOU (2021, Renewed 2023)",
        "summary": "Domestic workers and service sectors. Free visa policy. Minimum wage AED 2,500/month. 2023 amendments: communication rights, document security, welfare monitoring. UAE's reformed kafala: workers change employers after first year. Quarterly joint committee meetings.",
        "source": "Ministry of Human Resources and Emiratisation (UAE) / Ministry of Labour (Ethiopia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ET-KW",
        "corridor": "ET-KW",
        "title": "Ethiopia-Kuwait Labour Agreement",
        "summary": "Domestic workers. Minimum wage KWD 110/month. Mandatory contract registration. Employer-paid recruitment. Kuwait's partial kafala reform: workers negotiate changes after 2 years. Bilateral monitoring of agreement implementation.",
        "source": "Ministry of Labour (Kuwait) / Ministry of Labour (Ethiopia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ET-JO",
        "corridor": "ET-JO",
        "title": "Ethiopia-Jordan Labour Cooperation MOU",
        "summary": "Domestic and service workers. Government-to-government recruitment. Jordan Compact refugee integration provisions. Wage protection mechanism. Annual agreement review and joint implementation monitoring.",
        "source": "Ministry of Labour (Jordan) / Ministry of Labour (Ethiopia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ET-LB",
        "corridor": "ET-LB",
        "title": "Ethiopia-Lebanon Labour Agreement (Limited Enforcement)",
        "summary": "Domestic workers primarily. Standard contract system in place but enforcement minimal. Lebanon's kafala system provides limited legal recourse. Wage withholding endemic. Ethiopia suspended deployment multiple times over abuse reports; resumed with enhanced monitoring proposals.",
        "source": "Ministry of Labour (Lebanon) / Ministry of Labour (Ethiopia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ET-MY",
        "corridor": "ET-MY",
        "title": "Ethiopia-Malaysia Labour Cooperation Framework",
        "summary": "Manufacturing and services sectors. Government-to-government recruitment framework. Mandatory contract system. Zero-cost recruitment target. Ethiopia monitoring through embassy. Annual agreement review.",
        "source": "Ministry of Human Resources (Malaysia) / Ministry of Labour (Ethiopia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ET-JP",
        "corridor": "ET-JP",
        "title": "Ethiopia-Japan TITP/SSW Cooperation MOU",
        "summary": "Technical Intern Training and Specified Skilled Worker programs. Limited numbers due to Ethiopian capacity. JLPT required for SSW route. Government monitoring of trainee conditions. Potential for expansion in care work sectors.",
        "source": "Japan Ministry of Health, Labour and Welfare / Ministry of Labour (Ethiopia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MX-US",
        "corridor": "MX-US",
        "title": "Mexico-United States Bilateral Labour Cooperation Framework",
        "summary": "Includes H-2A agricultural workers and H-2B non-agricultural temporary workers. Prevailing wage standards enforced. Housing, transportation, and tools provided by employers. Worker recruitment transparency requirements. Retaliation protections. Annual bilateral labor consultations.",
        "source": "US Department of Labor / Ministry of Labour and Social Provision (Mexico)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "CA-CA",
        "corridor": "CA-CA",
        "title": "Canada-Mexico Seasonal Agricultural Workers Program Agreement (1974, Modernized 2022)",
        "summary": "Workers for seasonal agriculture (strawberries, apples, greenhouse). Employer-paid recruitment costs. Minimum wage matching Canadian standards. Housing and transportation provided. Return ticket guaranteed. Rights-education programs mandatory. Bilateral monitoring of working conditions.",
        "source": "Global Affairs Canada / Ministry of Labour (Mexico)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "CA-CB",
        "corridor": "CA-CB",
        "title": "Canada-Caribbean Seasonal Agricultural Workers Program (SAWP) Framework",
        "summary": "Covers agricultural workers from Jamaica, Trinidad and Tobago, Barbados, and other Caribbean nations. Employer-paid recruitment and transportation. Minimum wage per provincial standards. Employer-provided housing. Annual program review and worker feedback integration.",
        "source": "Global Affairs Canada / Ministries of Labour (Caribbean Nations)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "CA-PH",
        "corridor": "CA-PH",
        "title": "Canada-Philippines International Mobility Program (IMP) Healthcare Agreement",
        "summary": "Nurses and care workers under employer sponsorship. Salary minimum CAD 55,000/year (indexed). Credential recognition pathway for Filipino nursing licenses. Permanent residence pathways after 3 years. Annual bilateral review of program outcomes.",
        "source": "Immigration, Refugees and Citizenship Canada / Bureau of Labour Affairs (Philippines)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "US-CA",
        "corridor": "US-CA",
        "title": "United States-Central American Labour Mobility Discussions (2023-2024)",
        "summary": "Ongoing negotiations with Guatemala, Honduras, El Salvador on labor migration frameworks. Focus on agricultural and construction sectors. Wage protection mechanisms under development. Rights-based enforcement provisions being negotiated. Framework agreement expected 2025.",
        "source": "US Department of Labor / Central American Labour Ministries",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "DE-BA",
        "corridor": "DE-BA",
        "title": "Germany-Western Balkans Labour Mobility Agreement (2024)",
        "summary": "Healthcare, hospitality, and skilled trades priority sectors. EU points-based skill assessment. German language proficiency requirements. Working conditions aligned with German Labour Code. Credential recognition for healthcare professionals. Annual bilateral review.",
        "source": "Federal Ministry of Labour (Germany) / Labour Ministries (Balkans)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ES-MR",
        "corridor": "ES-MR",
        "title": "Spain-Morocco Labour Cooperation Agreement (2023 Expanded)",
        "summary": "Agricultural work (seasonal), construction, hospitality, and domestic services. Employer responsibility for recruitment, housing, and food. Prevailing wage standards enforced. Worker grievance mechanisms. Annual bilateral review of implementation.",
        "source": "Ministry of Inclusion, Social Security and Migration (Spain) / Ministry of Labour (Morocco)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IT-TN",
        "corridor": "IT-TN",
        "title": "Italy-Tunisia Labour Mobility Framework",
        "summary": "Agricultural seasonal workers, construction, and hospitality sectors. Italian labour law standards apply. Employer-pays recruitment and transportation. Housing provided. Rights education programs. Annual bilateral assessment of program outcomes.",
        "source": "Ministry of Labour and Social Policy (Italy) / Ministry of Social Affairs (Tunisia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "AU-PH",
        "corridor": "AU-PH",
        "title": "Australia-Philippines Labour Mobility Scheme Discussions (2024)",
        "summary": "Emerging bilateral framework negotiations. Focus: healthcare workers, construction, hospitality. Wage protection and working condition standards to match Australian minimums. Credential recognition for nurses. Framework development ongoing.",
        "source": "Department of Employment (Australia) / Bureau of Labour Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NZ-PH",
        "corridor": "NZ-PH",
        "title": "New Zealand-Philippines Essential Skills Work Visa Arrangement",
        "summary": "Skilled and semi-skilled workers for 1-3 year contracts. Healthcare, construction, hospitality priority. Employer accreditation required. Wage rates monitored to match NZ minimums. Annual bilateral review of program and worker feedback.",
        "source": "Department of Internal Affairs (New Zealand) / Bureau of Labour Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ASEAN",
        "corridor": "ASEAN Regional",
        "title": "ASEAN Consensus on the Protection and Promotion of the Rights of Migrant Workers (2007)",
        "summary": "ASEAN-wide framework promoting migrant worker protections. Non-binding consensus emphasizing decent work conditions, freedom from discrimination, access to grievance mechanisms. Individual bilateral agreements negotiated within this framework. Regional cooperation on trafficking prevention.",
        "source": "ASEAN Secretariat / ILO",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "GCC",
        "corridor": "GCC Unified",
        "title": "GCC Unified Contract Template for Domestic Workers (2009, Updated 2023)",
        "summary": "Saudi Arabia, UAE, Qatar, Kuwait, Bahrain, Oman common standard contract. Minimum wage floor: SAR 1,500 equivalent. Employer-pays recruitment. Weekly rest day. Medical insurance. Standard document across all GCC states. Annual review and wage adjustment discussions.",
        "source": "GCC General Secretariat / Saudi Ministry of Labour",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "AU-Regional",
        "corridor": "African Regional",
        "title": "African Union Labour Migration Protocols & Recommendations (2020, Affirmed 2024)",
        "summary": "Pan-African framework promoting fair labour migration governance. Emphasizes origin countries' right to regulate recruitment agencies. Sets regional standards for worker protections and rights-based migration. Bilateral agreements negotiated within AU framework.",
        "source": "African Union / ILO",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "EU-Regional",
        "corridor": "European Union",
        "title": "EU Blue Card & Seasonal Worker Directives (2021 Updated)",
        "summary": "Intra-EU and third-country worker mobility framework. Emphasis on skilled workers and seasonal agricultural workers. Working conditions aligned with EU labour law. Credential recognition mechanisms. Annual review and enhancement discussions.",
        "source": "European Commission / EU Labour Directorate",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "Jordan Compact",
        "corridor": "Syrian Refugee Corridor",
        "title": "Jordan Compact & Refugee Employment Framework (2016, Renewed Annually)",
        "summary": "Syrian refugee employment in Jordan. Work permits facilitated. Labour standards enforced through ILO partnership. Employer compliance monitoring. Annual pledging conferences ensure continued host country support. Bilateral cooperation with Syria (when applicable).",
        "source": "Government of Jordan / UNHCR / ILO",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "SAARC",
        "corridor": "South Asian Regional",
        "title": "SAARC Regional Framework on Labour Migration (Proposed, Under Discussion)",
        "summary": "Proposed multilateral framework for South Asian labour migration (India, Bangladesh, Nepal, Sri Lanka, Pakistan). Focus: common labour standards, trafficking prevention, worker rights. Individual bilateral agreements continue while framework development progresses. Expected finalization 2025.",
        "source": "SAARC Secretariat / ILO",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MERCOSUR",
        "corridor": "South American Regional",
        "title": "MERCOSUR Labour Mobility Protocol (1998, Implemented 2024)",
        "summary": "South American integration agreement facilitating labor movement between Argentina, Brazil, Paraguay, Uruguay (and associates). Free movement of workers within region. Common labor standards. Social security portability. Annual review of implementation progress.",
        "source": "MERCOSUR Secretariat / Labour Ministries",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "CARICOM",
        "corridor": "Caribbean Regional",
        "title": "CARICOM Single Market and Economy (CSME) Labour Mobility Provisions (2006)",
        "summary": "Caribbean Community free movement of workers. Skilled worker categories facilitated. Credential recognition mechanisms. Member states: Antigua, Barbados, Dominica, Grenada, Jamaica, Saint Lucia, Saint Kitts, etc. Ongoing implementation and refinement.",
        "source": "CARICOM Secretariat / ILO",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ET-OM",
        "corridor": "ET-OM",
        "title": "Ethiopia-Oman Labour Cooperation Agreement",
        "summary": "Domestic and hospitality workers. Minimum wage OMR 220/month. Employer-provided accommodations mandatory. Standard contract system with Ministry registration. Dispute resolution through Oman Labour Tribunal. Annual bilateral review of implementation and worker feedback.",
        "source": "Ministry of Labour and Social Welfare (Oman) / Ministry of Labour (Ethiopia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "MENA Regional",
        "corridor": "Middle East North Africa",
        "title": "Arab Labour Organization Model Bilateral Agreement on Labour Migration (2015)",
        "summary": "Framework for bilateral agreements among Arab states (Egypt, Morocco, Jordan, Lebanon, etc.). Emphasizes worker rights, fair wages, and protection from exploitation. Individual bilateral agreements reference this model. Regular updates and refinement.",
        "source": "Arab Labour Organization / Arab League",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "Pacific Islands",
        "corridor": "Pacific Regional",
        "title": "Pacific Islands Seasonal Worker Programme (Australia-Pacific, NZ-Pacific) Framework",
        "summary": "Seasonal labour scheme for Pacific Island nationals in Australia and New Zealand (agriculture, seasonal hospitality). Wage standards enforced. Limited contract terms. Return-oriented program design. Annual bilateral reviews with participating islands.",
        "source": "Department of Home Affairs (Australia) / Internal Affairs (NZ)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "Asia-Pacific",
        "corridor": "Regional",
        "title": "Asia-Pacific Economic Cooperation (APEC) Labour Cooperation Framework (2021-2026)",
        "summary": "APEC member commitment to facilitating labor mobility while protecting worker rights. Regional forum for discussing best practices in bilateral agreements. Non-binding framework with individual member bilateral agreements.",
        "source": "APEC Secretariat / ILO",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BIMSTEC",
        "corridor": "South Asian Regional",
        "title": "BIMSTEC Labour Cooperation Initiative (Bangladesh, India, Myanmar, Sri Lanka, Thailand, Bhutan, Nepal)",
        "summary": "Regional forum promoting labour mobility and worker protection. Emphasis on preventing trafficking and exploitation. Bilateral agreements negotiated within BIMSTEC framework. Annual cooperation meetings. Trafficking prevention protocols established.",
        "source": "BIMSTEC Secretariat / ILO",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-IS",
        "corridor": "NP-IS",
        "title": "Nepal-Israel Labour Cooperation Agreement (Agriculture)",
        "summary": "Agricultural seasonal workers. Government-to-government recruitment. Zero-cost principle for workers. Standard contract mandatory. Wage protection mechanisms. Annual bilateral review.",
        "source": "Ministry of Labour (Israel) / Nepal Foreign Employment Board",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-TW",
        "corridor": "BD-TW",
        "title": "Bangladesh-Taiwan Labour Cooperation Agreement",
        "summary": "Manufacturing, construction, and care work sectors. Taiwan's regulated recruitment system with BMET cooperation. Wage floor TWD 27,470/month. Contract verification mandatory. Labor Bureau inspections.",
        "source": "Council of Labour Affairs (Taiwan) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-LV",
        "corridor": "PH-LV",
        "title": "Philippines-Latvia Labour Mobility Arrangement (2023)",
        "summary": "EU member state. Skilled professionals and healthcare workers. Post-Brexit arrangement within EU framework. Wage standards enforced. Credential recognition discussions. Annual bilateral review.",
        "source": "Ministry of Welfare (Latvia) / Bureau of Labour Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-AT",
        "corridor": "IN-AT",
        "title": "India-Austria Labour Mobility Framework",
        "summary": "Skilled professionals and healthcare workers. Austrian sectoral demands considered. Wage and working condition standards enforced. Credential recognition for healthcare and engineering professions. Bilateral consultation on labour market needs.",
        "source": "Federal Ministry of Labour (Austria) / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-NO",
        "corridor": "VN-NO",
        "title": "Vietnam-Norway Labour Mobility Discussions (Emerging)",
        "summary": "Early-stage negotiations on skilled worker entry. Focus on offshore energy, IT, and healthcare sectors. Norwegian wage standards and working conditions would apply. Framework development stage.",
        "source": "Ministry of Labour (Norway) / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-DE",
        "corridor": "BD-DE",
        "title": "Bangladesh-Germany Labour Partnership Agreement (2023)",
        "summary": "Healthcare workers, hospitality, and skilled trades. German language requirements. Integration programs mandatory. Wage standards (Mindestlohn) enforced. Credential recognition for nursing professions. Annual bilateral review.",
        "source": "Federal Ministry of Labour (Germany) / Ministry of Labour (Bangladesh)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-NE",
        "corridor": "LK-NE",
        "title": "Sri Lanka-Netherlands Labour Cooperation Framework",
        "summary": "EU member state. Healthcare and hospitality sectors. EU working time and wage directives apply. Credential recognition discussions ongoing. Annual bilateral consultation on labour market trends.",
        "source": "Ministry of Social Affairs (Netherlands) / SLBFE",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "ET-SE",
        "corridor": "ET-SE",
        "title": "Ethiopia-Sweden Labour Mobility Arrangement",
        "summary": "Skilled workers and healthcare professionals. Swedish wage standards and working conditions enforced. Integration support provided. Annual bilateral review of program outcomes.",
        "source": "Ministry of Employment (Sweden) / Ministry of Labour (Ethiopia)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "PH-NI",
        "corridor": "PH-NI",
        "title": "Philippines-Netherlands Labour Cooperation MOU (2021)",
        "summary": "Healthcare workers, skilled professionals, and care workers. EU standards apply. Credential recognition for nursing qualifications. Wage protection mechanisms. Annual bilateral review and joint implementation meetings.",
        "source": "Ministry of Social Affairs (Netherlands) / Bureau of Labour Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "IN-FR",
        "corridor": "IN-FR",
        "title": "India-France Labour Mobility & Skill Partnership (2022)",
        "summary": "Skilled professionals and students-to-workers pathways. French language proficiency expected. Working conditions aligned with French Labour Code. Credential recognition mechanisms. Annual bilateral consultation on labor market needs.",
        "source": "Ministry of Labour (France) / Ministry of Overseas Indian Affairs",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "VN-DE",
        "corridor": "VN-DE",
        "title": "Vietnam-Germany Dual Education & Labour Mobility Pathway (2024)",
        "summary": "Emerging arrangement focusing on vocational training and subsequent employment. German employers sponsor workers. Minimum wage (Mindestlohn) enforced. Integration support provided. Annual review of program effectiveness.",
        "source": "Federal Ministry of Labour (Germany) / Ministry of Labour (Vietnam)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "NP-CH",
        "corridor": "NP-CH",
        "title": "Nepal-Switzerland Bilateral Labour Mobility Framework (2023)",
        "summary": "Skilled workers in sectors with labor shortages. Swiss sectoral quotas system. Wage and working condition standards enforced. Annual bilateral review and adjustment of quota allocations.",
        "source": "State Secretariat for Migration (Switzerland) / Nepal Foreign Employment Board",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "BD-SG",
        "corridor": "BD-SG",
        "title": "Bangladesh-Singapore Enhanced Domestic Worker Protections MOU (2024)",
        "summary": "Expanded protections for Bangladeshi domestic workers. MOM regulation strengthened. Minimum wage SGD 1,000/month. At least one day rest per week mandated. BMET monitoring protocol established. Quarterly joint committee meetings.",
        "source": "Ministry of Manpower (Singapore) / BMET",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "LK-AU",
        "corridor": "LK-AU",
        "title": "Sri Lanka-Austria Labour Mobility Agreement (2023)",
        "summary": "Healthcare workers and skilled professionals. Austrian wage standards enforced. Credential recognition for nursing professions. Integration support. Annual bilateral review.",
        "source": "Federal Ministry of Labour (Austria) / SLBFE",
    },
]
