"""Child labour facts, worst forms, age verification, and sector data."""

CHILD_LABOUR_FACTS: list[dict] = [
    # ── Global Statistics ────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Global Child Labour Estimates",
        "metric": "child_labour_total",
        "value": "160M children",
        "year": 2020,
        "details": "160M children (63M girls, 97M boys) in child labour globally (ILO-UNICEF 2020). 79M in hazardous work. First increase in 20 years (8.4M more than 2016). Sub-Saharan Africa: 86.6M (23.9% of children). COVID-19 projected to push 8.9M additional children into child labour by end of 2022.",
        "source": "ILO-UNICEF Child Labour: Global Estimates 2020",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Child Trafficking — Global Estimates",
        "metric": "child_trafficking",
        "value": "1 in 4 trafficking victims are children",
        "year": 2022,
        "details": "Children constitute 27% of all detected trafficking victims globally (UNODC). Girls: 29% of victims. Boys: 9%. Children increasingly trafficked for forced labour (not just sexual exploitation). Online recruitment of children growing. Orphanage trafficking documented in 20+ countries. Conflict and displacement increase child trafficking risk 5-fold.",
        "source": "UNODC Global Report on Trafficking in Persons 2022",
    },
    # ── Legal Frameworks ─────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 182 — Worst Forms of Child Labour (1999)",
        "law": "ILO C182",
        "year": 1999,
        "summary": "First ILO convention to achieve universal ratification (187 countries by 2020). Prohibits: slavery, trafficking, debt bondage, forced recruitment into armed conflict, prostitution, pornography, drug trafficking, and hazardous work for children under 18. Requires immediate and effective measures for elimination. National hazardous work lists required.",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 138 — Minimum Age for Employment (1973)",
        "law": "ILO C138",
        "year": 1973,
        "summary": "Sets minimum working age at 15 (or 14 for developing countries). Light work permitted from 13 (12 in developing countries). Hazardous work: minimum 18. 175 ratifications. Many countries set higher minimums for specific sectors. Enforcement varies widely. Key gaps: domestic work, family agriculture, informal sector largely unregulated in many jurisdictions.",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Convention on the Rights of the Child (CRC, 1989)",
        "law": "UNCRC Art. 32, 34, 35, 36",
        "year": 1989,
        "summary": "Most widely ratified human rights treaty (196 parties, all UN members except US). Art. 32: protection from economic exploitation and hazardous work. Art. 34: protection from sexual exploitation. Art. 35: prevention of trafficking. Art. 36: protection from all other forms of exploitation. Optional Protocol on Sale of Children (2000) adds enforcement obligations.",
    },
    # ── Sector-Specific Child Labour ─────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Child Labour in Agriculture — 70% of All Child Labour",
        "sector": "agriculture",
        "exploitation_type": "child_labour",
        "summary": "112M children in agricultural child labour (70% of total). Cocoa (West Africa), coffee (Central America, East Africa), tobacco (Malawi, Indonesia), sugar (Brazil, Philippines), palm oil (Indonesia), tea (India, Sri Lanka), cotton (Uzbekistan, India). Children exposed to pesticides, sharp tools, heavy loads. Often family-based, making detection and intervention complex.",
        "source": "ILO / US DOL ILAB / FAO",
    },
    {
        "type": "case_study",
        "jurisdiction": "CD",
        "title": "Cobalt Mining Child Labour — Democratic Republic of Congo",
        "sector": "mining",
        "exploitation_type": "child_labour",
        "summary": "40,000+ children in artisanal cobalt mining in southern DRC (Amnesty International). Children as young as 6 wash and sort cobalt ore. Tunnel collapses, toxic exposure, musculoskeletal damage. Cobalt enters supply chains of Apple, Samsung, Tesla via intermediary traders. DRC produces 70% of global cobalt. Artisanal mining provides 15-30% of DRC cobalt output.",
        "source": "Amnesty International / Siddharth Kara / UNICEF DRC",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Child Domestic Workers — 11.5M Globally",
        "sector": "domestic_work",
        "exploitation_type": "child_labour",
        "summary": "11.5M children in domestic work globally, majority girls. Hidden in private homes, invisible to labour inspectors. Hours: 12-16/day. No education access. Physical and sexual abuse documented. Restavèk system (Haiti): 300,000 children as domestic servants. Vidomègon (Benin/Togo): children sent to urban relatives for 'education' but used as servants. Child domestic work often not legally recognized as employment.",
        "source": "ILO / UNICEF / Anti-Slavery International",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Children in Fishing Industry — Forced Labour at Sea",
        "sector": "fishing",
        "exploitation_type": "restriction_of_movement",
        "summary": "Children trafficked onto fishing vessels in Ghana (Lake Volta: 20,000+ children), Southeast Asia (Thai fishing fleet), and West Africa. Children as young as 5 used for diving (untangling nets underwater). Drowning deaths common. Isolated at sea for months. Physical punishment for mistakes. Sold by impoverished families for USD 20-200 per year. Education completely denied.",
        "source": "IJM / Environmental Justice Foundation / IOM",
    },
    # ── Specific Systems of Child Exploitation ───────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Orphanage Trafficking — Exploitation Through 'Voluntourism'",
        "sector": "multiple",
        "exploitation_type": "deception",
        "summary": "Children deliberately recruited into orphanages (despite having living parents) to attract foreign donations and volunteer tourists. Documented in Cambodia, Nepal, Haiti, Ghana, Uganda, Indonesia. 80% of children in orphanages have living parent(s). Children kept in poor conditions to elicit sympathy. Orphanage tourism industry worth millions. Australia criminalized orphanage trafficking (2019).",
        "source": "Lumos Foundation / UNICEF / Australian Federal Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Talibé System — Forced Begging in West Africa",
        "sector": "begging",
        "exploitation_type": "child_labour",
        "summary": "100,000+ Talibé children (Quranic students) in Senegal, Guinea, Guinea-Bissau, Mali, Gambia forced to beg by Quranic teachers (marabouts). Children aged 5-15 must bring daily quota (CFA 300-500, USD 0.50-0.85). Failure punished with beatings. Children sleep in overcrowded rooms, malnourished. Senegalese law prohibits (Art. 245 Penal Code) but enforcement near-zero due to religious sensitivities.",
        "source": "HRW / UNICEF / Senegalese Ministry of Justice",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Child Camel Jockeys — Historical Gulf Practice",
        "sector": "sports",
        "exploitation_type": "child_labour",
        "summary": "Children (some as young as 2-3) from South Asia and East Africa trafficked as camel jockeys in UAE, QA, SA, OM. Practice peaked 1970s-2000s. Children kept underweight, suffered injuries and deaths. UAE ban (2005) + robot jockey replacement. UNICEF repatriation program returned 1,000+ children. QA ban (2005), SA ban (2007). Legacy: demonstrates that targeted legislation + technology can eliminate exploitative practice.",
        "source": "UNICEF / HRW / Anti-Slavery International",
    },
    {
        "type": "case_study",
        "jurisdiction": "MW",
        "title": "Child Labour in Malawi Tobacco — Tenancy System",
        "sector": "agriculture",
        "exploitation_type": "child_labour",
        "summary": "78,000 children in Malawi tobacco farming (US DOL). Tenancy system: families work land owned by estate, paid by weight of tobacco produced. Children work alongside parents to meet quotas. Nicotine poisoning (Green Tobacco Sickness) from handling wet leaves. No protective equipment. Tobacco produced for major international brands. Plan International and others advocate for monitoring systems.",
        "source": "US DOL / Plan International / HRW",
    },
    # ── Age Verification and Documentation ───────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Age Falsification in Cross-Border Recruitment",
        "summary": "Recruitment agencies falsify age documents for underage workers: birth certificates altered, medical age assessments manipulated, identity documents from other family members used. Countries with weak civil registration systems most vulnerable: NP, BD, MM, KH, ET, West African states. Destination countries rarely verify age independently. ILO recommends bone density testing as backup verification.",
        "source": "ILO / IOM / UNICEF",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Minimum Working Ages by Key Jurisdiction",
        "summary": "General minimum: BD 14, NP 14, ID 15, PH 15, MM 14, KH 15, VN 15, ET 14, IN 14. Hazardous work minimum: most countries 18. Domestic work: PH 15, ID 18 (2017 law), BD 14 (no specific domestic provision), SA no explicit minimum. Light work: many countries allow from 12-13 for non-hazardous family work. Enforcement gaps in all origin and destination countries.",
        "source": "ILO NORMLEX / US DOL ILAB",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Education Deprivation as Child Labour Indicator",
        "summary": "ILO indicator: children not attending school due to work obligations. 28% of children aged 5-11 in child labour do not attend school. 40% of children aged 12-14 in child labour are out of school. Working children who attend school perform worse and drop out earlier. Education deprivation is both consequence and perpetuator of child labour cycle. School-to-work transition programs needed.",
        "source": "ILO-UNICEF 2020 / UNESCO",
    },
    # ── US DOL List ──────────────────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "US",
        "title": "US DOL List of Goods Produced by Child Labour or Forced Labour",
        "summary": "US DOL TVPRA List identifies 159 goods from 78 countries produced with child labour or forced labour (2024 update). Top goods: sugarcane (17 countries), bricks (14), gold (13), coffee (11), tobacco (9), cotton (8), fish (7), cocoa (5). Used for supply chain due diligence and import enforcement under 19 USC §1307. Updated biennially since 2009.",
        "source": "US DOL Bureau of International Labor Affairs (ILAB)",
    },
    {
        "type": "case_study",
        "jurisdiction": "IN",
        "title": "India — Bonded Child Labour in Brick Kilns and Agriculture",
        "sector": "construction",
        "exploitation_type": "debt_bondage",
        "summary": "Estimated 10M+ children in child labour in India (ILO). Brick kilns: entire families including children bonded for season. Advance payment creates debt. Children aged 5-14 mold, carry, and stack bricks. Agriculture: children in cotton seed pollination (Andhra Pradesh), sugarcane cutting (Maharashtra), carpet weaving (UP/Rajasthan). Bonded Labour Abolition Act (1976) rarely enforced at state level.",
        "source": "India NHRC / ILO / Bachpan Bachao Andolan (Kailash Satyarthi)",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Online Child Sexual Exploitation Material Production Under Coercion",
        "sector": "digital_fraud",
        "exploitation_type": "sexual_violence",
        "summary": "Children forced to produce CSAM (child sexual abuse material) for online distribution. Philippines identified as major production hub ('cybersex dens'). Children as young as 2 exploited. Adults (often family members) facilitate in exchange for payment (USD 20-100 per session). Live-streaming technology enables real-time abuse to order. IJM operations in Philippines: 900+ children rescued since 2016.",
        "source": "IJM / ECPAT / WeProtect Global Alliance",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Child Labour in Hazardous Work",
        "metric": "hazardous_child_labour",
        "value": "79M children",
        "year": 2020,
        "details": "79M children (ages 5-17) in hazardous work globally. Agriculture: 56.6M (71% of hazardous child labour). Industry: 10.3M. Services: 12.1M. Boys: 56%, Girls: 44%. Children under 12 in hazardous work: 6.4M. Hazardous work defined by ILO C182: work likely to harm health, safety, or morals. Includes night work, exposure to toxic substances, heavy loads, sexual exploitation.",
        "source": "ILO-UNICEF 2020",
    },
]
