"""Hotlines, embassies, agencies, and support organizations for migrant workers."""

CONTACT_FACTS: list[dict] = [
    # ── Philippines ───────────────────────────────────────────────────
    {
        "type": "contact",
        "jurisdiction": "PH",
        "title": "OWWA 24/7 Hotline for Distressed OFWs",
        "organization": "Overseas Workers Welfare Administration",
        "contact_type": "hotline",
        "details": "1348 (local), +63 2 1348 (international). 24/7 assistance for Filipino workers in distress abroad. Repatriation, legal aid, medical assistance, financial aid.",
    },
    {
        "type": "contact",
        "jurisdiction": "PH",
        "title": "DMW Complaint and Action Center",
        "organization": "Department of Migrant Workers",
        "contact_type": "complaint_center",
        "details": "Hotline 8722-1144 / 8722-1155. Online portal: dmw.gov.ph. Handles illegal recruitment complaints, contract verification, agency violations. POLO offices in 34 countries.",
    },
    {
        "type": "contact",
        "jurisdiction": "PH",
        "title": "IACAT Anti-Trafficking Tip Line",
        "organization": "Inter-Agency Council Against Trafficking",
        "contact_type": "tip_line",
        "details": "1343 Action Line. Report trafficking cases, suspicious recruitment, or exploitation. Coordinates with NBI, PNP, DOJ. Operates 24/7.",
    },

    # ── Hong Kong ─────────────────────────────────────────────────────
    {
        "type": "contact",
        "jurisdiction": "HK",
        "title": "Hong Kong Labour Department Complaints Hotline",
        "organization": "Labour Department, HKSAR",
        "contact_type": "hotline",
        "details": "2717 1771 (complaints), 2157 9537 (employment agencies). Handles wage disputes, underpayment, illegal working conditions. Tagalog and Bahasa interpreters available.",
    },
    {
        "type": "contact",
        "jurisdiction": "HK",
        "title": "Justice Centre Hong Kong",
        "organization": "Justice Centre Hong Kong",
        "contact_type": "ngo",
        "details": "6312 4948 (helpline). Legal aid, shelter referral, psychosocial support for trafficking victims and asylum seekers. Research and advocacy on forced labour in HK.",
    },
    {
        "type": "contact",
        "jurisdiction": "HK",
        "title": "Mission for Migrant Workers (MFMW)",
        "organization": "Mission for Migrant Workers",
        "contact_type": "ngo",
        "details": "2522 8264. Shelter, legal aid, counseling for migrant domestic workers. Walk-in center in Central. Crisis intervention for abuse cases. Operates since 1981.",
    },
    {
        "type": "contact",
        "jurisdiction": "HK",
        "title": "PathFinders — Support for Migrant Mothers",
        "organization": "PathFinders",
        "contact_type": "ngo",
        "details": "5190 4553 (helpline). Supports pregnant migrant domestic workers and their children in Hong Kong. Legal advice, shelter, medical referral, documentation assistance.",
    },

    # ── Singapore ─────────────────────────────────────────────────────
    {
        "type": "contact",
        "jurisdiction": "SG",
        "title": "MOM Helpline for Foreign Workers",
        "organization": "Ministry of Manpower, Singapore",
        "contact_type": "hotline",
        "details": "6438 5122 (general), 1800 339 5505 (toll-free from SG). Report salary non-payment, abuse, unsafe conditions. Multi-language support. Online form: mom.gov.sg.",
    },
    {
        "type": "contact",
        "jurisdiction": "SG",
        "title": "TWC2 — Transient Workers Count Too",
        "organization": "Transient Workers Count Too",
        "contact_type": "ngo",
        "details": "6247 7001. Free meals (Sunday), legal clinic, social work support, salary claim assistance. The Cuff Road Project provides temporary shelter. Research and advocacy for migrant worker rights.",
    },
    {
        "type": "contact",
        "jurisdiction": "SG",
        "title": "HOME — Humanitarian Organisation for Migration Economics",
        "organization": "HOME",
        "contact_type": "ngo",
        "details": "6341 5535 (helpline). Shelter for trafficked and abused workers, legal aid, employment assistance. Handles 5,000+ cases annually. Walk-in center at Rowell Road.",
    },

    # ── Gulf States ───────────────────────────────────────────────────
    {
        "type": "contact",
        "jurisdiction": "QA",
        "title": "Qatar Workers' Support and Insurance Fund (WSIF)",
        "organization": "Ministry of Labour, Qatar",
        "contact_type": "government",
        "details": "Hotline 16008. Provides temporary accommodation, emergency financial aid, and supports wage claims for workers awaiting dispute resolution. Established 2018.",
    },
    {
        "type": "contact",
        "jurisdiction": "SA",
        "title": "Saudi Musaned Platform — Domestic Worker Complaint System",
        "organization": "Ministry of Human Resources and Social Development, Saudi Arabia",
        "contact_type": "government",
        "details": "Musaned.com.sa and mobile app. Contract management, complaint filing, employer evaluation. Workers can file electronic complaints about wage non-payment and abuse.",
    },
    {
        "type": "contact",
        "jurisdiction": "AE",
        "title": "UAE MOHRE Worker Protection Hotline",
        "organization": "Ministry of Human Resources and Emiratisation, UAE",
        "contact_type": "hotline",
        "details": "600 590 000. Multilingual support: Arabic, English, Hindi, Urdu, Tagalog. Labour complaints, wage disputes, contract issues. MOHRE app for complaint tracking.",
    },

    # ── International ─────────────────────────────────────────────────
    {
        "type": "contact",
        "jurisdiction": "US",
        "title": "US National Human Trafficking Hotline",
        "organization": "Polaris Project",
        "contact_type": "hotline",
        "details": "1-888-373-7888 (24/7). Text 233733. Chat at humantraffickinghotline.org. Multi-language. Reports to law enforcement when appropriate. Serves US-based victims and tipsters.",
    },
    {
        "type": "contact",
        "jurisdiction": "UK",
        "title": "UK Modern Slavery Helpline",
        "organization": "Unseen UK",
        "contact_type": "hotline",
        "details": "08000 121 700 (24/7, free from UK). Online form: modernslaveryhelpline.org. Supports victims, receives tips, connects to National Referral Mechanism for formal identification.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "ILO Helpdesk for Business on International Labour Standards",
        "organization": "International Labour Organization",
        "contact_type": "advisory",
        "details": "assistance@ilo.org. Free and confidential service for companies and workers' organizations. Guidance on forced labour prevention, due diligence, and remediation.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "IOM Counter-Trafficking Assistance",
        "organization": "International Organization for Migration",
        "contact_type": "advisory",
        "details": "IOM operates counter-trafficking programs in 100+ countries. Direct assistance: voluntary return, reintegration, shelter, legal aid. Contact via nearest IOM office: iom.int/contacts.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "Migrant Forum in Asia (MFA)",
        "organization": "Migrant Forum in Asia",
        "contact_type": "network",
        "details": "Network of 200+ organizations across Asia. Coordinates cross-border case referrals, policy advocacy, and migrant worker support. mfasia.org. Based in Quezon City, Philippines.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "La Strada International — European Anti-Trafficking Network",
        "organization": "La Strada International",
        "contact_type": "network",
        "details": "Network of 8 European anti-trafficking organizations. Operates national hotlines in NL, CZ, PL, UA, BY, BG, MD, MK. Referral network for cross-border cases. lastradainternational.org.",
    },
    # ── Additional Contacts (expanded) ───────────────────────────────
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "GAATW — Global Alliance Against Traffic in Women",
        "organization": "GAATW",
        "contact_type": "network",
        "details": "Alliance of 80+ organizations worldwide. Human rights-based approach to trafficking. Research, advocacy, and direct assistance. Secretariat in Bangkok. gaatw.org.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "Walk Free Foundation — Research and Advocacy",
        "organization": "Walk Free Foundation",
        "contact_type": "research",
        "details": "Publishes Global Slavery Index (estimates of modern slavery by country). Funds Minderoo Foundation research. Provides data for policy-makers, businesses, and civil society. walkfree.org.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "Verité — Fair Labour Standards Research",
        "organization": "Verité",
        "contact_type": "research",
        "details": "Research and advisory organization on forced labour in supply chains. Conducts factory assessments, corridor research, and capacity building. Key publications on electronics, agriculture, and fishing forced labour. verite.org.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "Anti-Slavery International — Oldest Human Rights Organization",
        "organization": "Anti-Slavery International",
        "contact_type": "ngo",
        "details": "Founded 1839. Works on forced labour, debt bondage, trafficking, child labour globally. Campaigns, research, legal assistance. UK Charity. antislavery.org. Key programs in South Asia (bonded labour), West Africa (child labour), Gulf states (migrant workers).",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "CARAM Asia — Health and Migration",
        "organization": "CARAM Asia",
        "contact_type": "network",
        "details": "Coalition of 40+ organizations across Asia working on health rights of migrant workers. Focus: occupational health, reproductive health, mental health, access to healthcare. Research, advocacy, community education. caramasia.org.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "IDWF — International Domestic Workers Federation",
        "organization": "International Domestic Workers Federation",
        "contact_type": "union",
        "details": "Global federation representing 590,000 domestic workers in 63 affiliates across 54 countries. Advocacy for ILO C189 ratification, worker organizing, rights education. Founded 2013. idwfed.org. Headquarters in Hong Kong.",
    },
    {
        "type": "contact",
        "jurisdiction": "MY",
        "title": "Tenaganita — Malaysian Migrant Worker Support",
        "organization": "Tenaganita",
        "contact_type": "ngo",
        "details": "Malaysian NGO providing: legal aid, shelter, counselling, rights education for migrant workers, refugees, and trafficking survivors. Drop-in centres in KL and Penang. Hotline: +60-3-2691-3691. Documentation and advocacy on palm oil, electronics, and domestic worker exploitation. tenaganita.net.",
    },
    {
        "type": "contact",
        "jurisdiction": "TH",
        "title": "MAP Foundation — Migrant Assistance in Thailand",
        "organization": "MAP Foundation",
        "contact_type": "ngo",
        "details": "Thai NGO supporting Myanmar migrant workers in Chiang Mai. Services: legal aid, labour rights education, community organizing, women's empowerment. Drop-in centre. Multilingual hotline (Myanmar, Thai, English). mapfoundationcm.org. Partner of Migrant Working Group Thailand.",
    },
    {
        "type": "contact",
        "jurisdiction": "TH",
        "title": "LPN — Labour Protection Network Thailand",
        "organization": "Labour Protection Network",
        "contact_type": "ngo",
        "details": "Thai NGO focused on fishing and seafood processing sector workers. Services: rescue operations, legal assistance, shelter (Samut Sakhon province), rights education. Key partner for fishing industry reform. Thai language hotline. Works with migrant workers from Myanmar and Cambodia.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "BWI — Building and Wood Workers' International",
        "organization": "BWI",
        "contact_type": "union",
        "details": "Global union federation representing 12M workers in construction, building materials, wood, forestry, and allied sectors. Campaigns on migrant worker rights in Gulf mega-projects. FIFA World Cup Qatar monitoring. Safety training materials in 20+ languages. bwint.org.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "IJM — International Justice Mission",
        "organization": "International Justice Mission",
        "contact_type": "ngo",
        "details": "Largest anti-trafficking NGO globally. Conducts rescue operations in partnership with local law enforcement. Presence in 30+ countries. Key operations: Philippines (online sexual exploitation of children), India (bonded labour), Ghana (child labour in fishing), Cambodia (sex trafficking). Rescued 60,000+ people since 1997. ijm.org.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "ECPAT International — End Child Exploitation",
        "organization": "ECPAT International",
        "contact_type": "network",
        "details": "Network of organizations in 104 countries fighting sexual exploitation of children. Focus: online child exploitation, child trafficking, child sex tourism. Research, advocacy, direct services. Headquarters in Bangkok. ecpat.org. Key partner for Philippines OSEC (online sexual exploitation of children) response.",
    },
    {
        "type": "contact",
        "jurisdiction": "international",
        "title": "EJF — Environmental Justice Foundation",
        "organization": "Environmental Justice Foundation",
        "contact_type": "ngo",
        "details": "Campaigns on environmental and human rights in fishing industry. Investigations into IUU fishing and forced labour. Published reports on Thai, Ghanaian, and Chinese distant-water fishing fleets. Operates drones and vessel tracking for monitoring. ejfoundation.org.",
    },
    {
        "type": "contact",
        "jurisdiction": "PH",
        "title": "Migrante International — Filipino Migrant Workers Alliance",
        "organization": "Migrante International",
        "contact_type": "network",
        "details": "Alliance of Filipino migrant organizations worldwide. Chapters in: Hong Kong, Singapore, Japan, Korea, Taiwan, Middle East, Europe, North America. Advocacy, legal assistance, community organizing. Campaigns against deployment to high-risk countries. mifrante.org.",
    },
    {
        "type": "contact",
        "jurisdiction": "NP",
        "title": "Pourakhi Nepal — Returned Women Migrant Workers",
        "organization": "Pourakhi",
        "contact_type": "ngo",
        "details": "Nepali NGO supporting returned women migrant workers. Services: counselling, legal aid, reintegration support, skill training, microfinance. Operates in 5 districts. Hotline: +977-1-5536812. Research on Nepal-Gulf corridors. pourakhi.org.np.",
    },
]
