"""Debt bondage mechanisms, recruitment fee structures, and financial exploitation."""

DEBT_BONDAGE_FACTS: list[dict] = [
    # ── Recruitment Fee Structures by Corridor ───────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Global Recruitment Fee Burden — ILO Fair Recruitment Initiative",
        "sector": "multiple",
        "exploitation_type": "debt_bondage",
        "summary": "ILO employer-pays principle (C181) widely violated. Workers pay average 4-9x monthly salary in recruitment fees. Creates debt bondage before employment begins. Global recruitment industry worth USD 20B+. 73% of migrant workers pay some form of recruitment fee. Fair recruitment remains aspirational in most corridors.",
        "source": "ILO Fair Recruitment Initiative / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "NP",
        "title": "Nepal-Qatar Construction Recruitment Fee Structure",
        "corridor": "NP-QA",
        "sector": "construction",
        "exploitation_type": "debt_bondage",
        "summary": "Typical fee chain: village broker (NPR 30,000) → district agent (NPR 80,000) → Kathmandu agency (NPR 50,000) → Qatar employer (NPR 0, should pay). Total: NPR 160,000+ (USD 1,200+). Worker earns QAR 1,000/month (USD 275). Fee = 4-5 months salary. Loans at 36-48% annual interest. Repayment takes 12-18 months.",
        "source": "Pourakhi Nepal / ILO Kathmandu",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Bangladesh-Saudi Arabia Recruitment Fee Escalation",
        "corridor": "BD-SA",
        "sector": "construction",
        "exploitation_type": "debt_bondage",
        "summary": "Official BMET-approved fee: BDT 84,000 (USD 770). Actual fees paid: BDT 300,000-600,000 (USD 2,750-5,500). 4-7x legal limit. Chain: local dalal → sub-agent → licensed agency → Saudi employer. Each layer adds margin. Workers take loans against family land. Default = land seizure. Average repayment: 18-24 months of salary.",
        "source": "BMET / ILO Dhaka / BRAC",
    },
    {
        "type": "case_study",
        "jurisdiction": "ID",
        "title": "Indonesia-Malaysia Plantation Worker Fee Structure",
        "corridor": "ID-MY",
        "sector": "palm_oil",
        "exploitation_type": "debt_bondage",
        "summary": "Indonesian workers pay IDR 15-30M (USD 950-1,900) for Malaysian palm oil placement. Fees include: training centre (IDR 8-15M), documents (IDR 3-5M), transport (IDR 2-5M), agent commission (IDR 2-5M). BNP2MI zero-cost policy (2020) not enforced for plantation sector. Salary MYR 1,200-1,500/month. Fee = 8-15 months salary.",
        "source": "BNP2MI / Tenaganita Malaysia",
    },
    {
        "type": "case_study",
        "jurisdiction": "VN",
        "title": "Vietnam-Japan TITP Recruitment Fee Inflation",
        "corridor": "VN-JP",
        "sector": "manufacturing",
        "exploitation_type": "debt_bondage",
        "summary": "DOLAB cap: USD 3,600 for 3-year placement. Actual fees: USD 5,000-10,000. Excess disguised as 'Japanese language training,' 'skills certification,' 'guarantee deposit.' Sending organizations collude with supervising organizations in Japan. Workers locked into employer for 3 years, cannot transfer. Running away forfeits deposit.",
        "source": "DOLAB / OTIT Japan / ILO Hanoi",
    },
    {
        "type": "case_study",
        "jurisdiction": "ET",
        "title": "Ethiopia-Saudi Arabia Irregular Migration Fee Structure",
        "corridor": "ET-SA",
        "sector": "domestic_work",
        "exploitation_type": "debt_bondage",
        "summary": "Irregular route (Djibouti-Yemen-Saudi overland): USD 600-1,500 to smugglers. Regular route (via agency): USD 1,000-3,000. Workers arrive undocumented with no employer contract. Accept any work at any wage. Debt to smuggler/agent repaid by family in Ethiopia. Domestic workers earn SAR 800-1,200/month. Fee = 3-12 months salary.",
        "source": "IOM / Mixed Migration Centre / UNHCR",
    },
    {
        "type": "case_study",
        "jurisdiction": "MM",
        "title": "Myanmar-Thailand Border Crossing Fee Structure",
        "corridor": "MM-TH",
        "sector": "fishing",
        "exploitation_type": "debt_bondage",
        "summary": "Border broker fee: THB 15,000-40,000 (USD 430-1,150). Includes border crossing, transport to employer, initial accommodation. Workers earn THB 300-350/day (minimum wage). Fee = 1.5-4 months salary. No contract, no work permit, no protections. Employers may add 'accommodation' and 'food' deductions, extending effective bondage period.",
        "source": "Migrant Working Group Thailand / ILO GMS Triangle",
    },
    # ── Debt Mechanisms ──────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Interest Rate Exploitation in Recruitment Loans",
        "sector": "multiple",
        "exploitation_type": "debt_bondage",
        "summary": "Informal money lenders charge 30-60% annual interest on recruitment loans. Some use flat-rate calculations that effectively double the rate. Compound interest adds 50-200% to principal over typical 2-3 year repayment. Bangladesh dalal loans: 60-120% effective rate. Nepal: 36-48%. Philippines: 20-36% (5-6 lending). Microfinance rates (12-24%) rarely available for migration loans.",
        "source": "ILO / World Bank / BRAC research",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Collateral Seizure and Family Liability in Debt Bondage",
        "sector": "multiple",
        "exploitation_type": "debt_bondage",
        "summary": "Workers pledge family assets as loan collateral: agricultural land (NP, BD, MM), house deeds (BD, PK), gold jewelry (IN, LK), livestock (ET, NP). Default triggers asset seizure by money lender. Family members (spouse, parents) become co-guarantors. Creates triple pressure: worker abroad cannot leave job, family at home faces destitution if worker returns early.",
        "source": "ILO / Verité / Anti-Slavery International",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Salary Deduction Schedules as Debt Bondage Mechanism",
        "sector": "domestic_work",
        "exploitation_type": "withholding_wages",
        "summary": "Employers or agencies deduct 20-50% of monthly salary for first 6-12 months as 'placement fee recovery.' Worker receives reduced wage but full fee is charged. In HK: agencies deduct HKD 4,870/month (entire salary) for first month despite legal cap. In SG: 8 months salary deduction common for Indonesian domestic workers. Creates period of effective bonded labour.",
        "source": "HOME Singapore / Justice Centre Hong Kong / TWC2",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Debt Inflation After Arrival at Destination",
        "sector": "multiple",
        "exploitation_type": "debt_bondage",
        "summary": "Original recruitment debt inflated at destination through: accommodation charges (USD 100-300/month deducted), food charges (USD 50-150/month), uniform/tool costs, medical exam fees, visa renewal fees, 'insurance' fees, transport to worksite. Worker arrives owing USD 2,000, told debt is now USD 4,000-6,000. No written accounting. Debt can grow faster than salary.",
        "source": "ILO / Verité / sector investigations",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Advance Payment Systems as Debt Creation",
        "sector": "construction",
        "exploitation_type": "debt_bondage",
        "summary": "Employers provide 'advance' payment to cover worker's initial expenses or send to family. Advance treated as interest-bearing loan against future wages. Worker cannot leave until advance repaid. Common in Gulf construction: SAR 2,000-5,000 advance, deducted SAR 500/month from salary. Creates 4-10 month bondage period in addition to recruitment fee bondage.",
        "source": "ILO / BWI / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Bond and Guarantee Forfeiture Mechanisms",
        "sector": "multiple",
        "exploitation_type": "debt_bondage",
        "summary": "Workers required to pay 'guarantee deposits' (USD 500-2,000) held by agency or employer. Forfeited if worker: leaves before contract end, files complaint, is terminated, 'runs away.' Some agencies require family members to sign guarantee bonds. Deposit rarely returned even after successful contract completion. Creates financial penalty for asserting rights.",
        "source": "ILO / Migrant Forum in Asia",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Debt Transfer Between Employers",
        "sector": "multiple",
        "exploitation_type": "debt_bondage",
        "summary": "When workers are transferred or 'sold' between employers (common in Gulf kafala systems), recruitment debt transfers with them — often increased. New employer pays transfer fee to old employer, adds it to worker's debt. Worker restarts bondage period. Documented in SA construction, QA domestic work, MY plantation sectors. Some workers transferred 3-4 times, each time increasing debt.",
        "source": "ILO / BWI / Anti-Slavery International",
    },
    # ── Legal Frameworks ─────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Definition of Debt Bondage (Supplementary Convention 1956)",
        "law": "Supplementary Convention on the Abolition of Slavery 1956, Art. 1(a)",
        "year": 1956,
        "summary": "Debt bondage: 'the status or condition arising from a pledge by a debtor of his personal services or of those of a person under his control as security for a debt, if the value of those services as reasonably assessed is not applied towards the liquidation of the debt or the length and nature of those services are not respectively limited and defined.' Binding on 124 state parties.",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Protocol to Prevent Trafficking — Debt Bondage as Exploitation",
        "law": "Palermo Protocol Art. 3(a)",
        "year": 2000,
        "summary": "Palermo Protocol defines trafficking to include exploitation through 'debt bondage' as a form of servitude or forced labour. 178 state parties. Establishes that consent of victim is irrelevant when means (deception, coercion, abuse of vulnerability) are used. Recruitment fee-induced debt bondage qualifies.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Debt Bondage Prevalence in Forced Labour",
        "metric": "prevalence",
        "value": "50%",
        "year": 2022,
        "details": "ILO estimates debt bondage is the primary means of coercion in 50% of all forced labour cases in the private economy. Higher in certain corridors: South Asia to Gulf (70%), Southeast Asia construction/fishing (65%), domestic work globally (45%). Average duration of debt bondage: 20 months before escape or debt repayment.",
        "source": "ILO Global Estimates of Modern Slavery 2022",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Average Recruitment Fees by Corridor (USD)",
        "metric": "recruitment_fees",
        "value": "varies by corridor",
        "year": 2023,
        "details": "BD-SA: USD 2,750-5,500. NP-QA: USD 1,200-2,400. PH-SA: USD 600-1,200 (lower due to zero-fee policy enforcement). ID-MY: USD 950-1,900. VN-JP: USD 5,000-10,000 (highest). MM-TH: USD 430-1,150. ET-SA: USD 600-3,000. ID-HK: USD 1,800-3,200. KH-TH: USD 200-600 (lowest, informal border crossing).",
        "source": "ILO / IOM / Corridor-specific research",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "ILO Indicator: Debt Bondage — Operational Guidance",
        "summary": "Key sub-indicators: worker paid recruitment fee exceeding legal limit or 1 month salary; salary deductions for fees exceed 10% of monthly pay; worker cannot leave until debt repaid; debt increases after deployment; interest charged on recruitment loan; family assets pledged as collateral; worker penalized financially for complaint or early termination. Presence of 2+ sub-indicators = strong indicator.",
        "source": "ILO Indicators of Forced Labour (2012, revised)",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Loan Shark Networks Servicing Migration Debt",
        "sector": "multiple",
        "exploitation_type": "debt_bondage",
        "summary": "Informal money lenders (loan sharks) operate in origin communities specializing in migration loans. Often connected to recruitment agencies (kickbacks for referrals). Use social pressure, community shame, and threats to enforce repayment. In Nepal: 'sahukars.' In Bangladesh: 'mahajans.' In Philippines: '5-6' lenders (borrow 5, repay 6). Criminal prosecution rare; seen as legitimate business.",
        "source": "ILO / BRAC / Microfinance research",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Debt Bondage Duration and Exit Pathways",
        "sector": "multiple",
        "exploitation_type": "debt_bondage",
        "summary": "Average duration of debt bondage: 18-24 months for Gulf construction, 8-12 months for domestic work (HK, SG), 24-36 months for fishing (TH), 12-18 months for manufacturing (MY). Exit pathways: complete repayment, employer intervention, NGO rescue, contract expiry, escape (risky: becomes undocumented). Only 15-20% of bonded workers receive full wages after debt cleared.",
        "source": "ILO / Verité / Anti-Slavery International",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Intergenerational Debt Bondage in South Asia",
        "sector": "agriculture",
        "exploitation_type": "debt_bondage",
        "summary": "In South Asian brick kilns, agriculture, and quarries, debt passes between generations. Parents' debt inherited by children. Families bonded for decades. India: 8-18M in bonded labour (Bonded Labour Abolition Act 1976, poorly enforced). Nepal: Kamaiya system (abolished 2000, persists informally). Pakistan: brick kiln families, haris (bonded tenant farmers). Children work alongside parents to service debt.",
        "source": "ILO / Walk Free / Anti-Slavery International / India NHRC",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Early Termination Penalties as Bondage Mechanism",
        "sector": "domestic_work",
        "exploitation_type": "debt_bondage",
        "summary": "Employment contracts include early termination penalties: worker must repay proportional recruitment costs if leaving before 2-year contract end. Penalties: USD 500-3,000. Combined with passport retention, makes leaving financially impossible. Some agencies add 'training cost recovery' clause. Workers who flee forfeit final salary, guarantee deposit, and face penalty claims.",
        "source": "HOME Singapore / Justice Centre Hong Kong / Migrant Forum in Asia",
    },
]
