"""East Asian migrant worker systems — South Korea EPS, Japan TITP, Taiwan fishing, China."""

EAST_ASIA_FACTS: list[dict] = [
    # =====================================================================
    # SOUTH KOREA (KR) — Employment Permit System & Migrant Worker Issues
    # =====================================================================

    # ── EPS Structure ───────────────────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "Employment Permit System (EPS) — Act on Foreign Workers' Employment (2003)",
        "summary": "Korea enacted the Act on Foreign Workers' Employment, Etc. (2003, effective 2004) creating the Employment Permit System. EPS replaced the scandal-ridden Industrial Trainee System. Government-to-government recruitment eliminates private brokers. Workers enter on E-9 (non-professional) visa for up to 4 years 10 months, renewable once for a total of 9 years 8 months.",
        "source": "Korea Ministry of Employment and Labor / ILO",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "EPS Sending Country MOUs — 16 Bilateral Agreements",
        "summary": "Korea has signed MOUs with 16 sending countries for EPS: Philippines, Thailand, Sri Lanka, Vietnam, Mongolia, Indonesia, Uzbekistan, Pakistan, Cambodia, China, Bangladesh, Nepal, Myanmar, Timor-Leste, Laos, and Kyrgyzstan. Each MOU designates a government sending agency responsible for worker selection, pre-departure orientation, and cost control. Korea periodically suspends or adjusts quotas per country based on compliance.",
        "source": "Korea HRD Service / ILO bilateral MOU registry",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "EPS Korean Language Proficiency Test (EPS-TOPIK)",
        "summary": "All EPS applicants must pass the EPS-TOPIK (Test of Proficiency in Korean) administered by Korea HRD Service in sending countries. Test covers listening and reading. Pass rate varies (20-40% depending on country). Costs approximately USD 25-40. Prevents broker manipulation since test is government-administered. However, private tutoring industry in sending countries can inflate worker preparation costs.",
        "source": "Korea HRD Service / IOM assessment of EPS",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "EPS Total Migration Cost Cap — ILO Model",
        "summary": "EPS caps total worker-borne migration costs at approximately USD 927-1,100 (varies by country), covering medical exam, EPS-TOPIK, training, airfare, and insurance. Compared to private recruitment corridors where costs can exceed USD 5,000-15,000. ILO and World Bank cite EPS as best-practice model for low-cost migration. However, unofficial costs (private tutoring, document preparation) can double official figures.",
        "source": "ILO / World Bank Global Knowledge Partnership on Migration and Development",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "EPS Workplace Change Provisions — 3-Time Limit",
        "summary": "EPS workers may change employers up to 3 times during their permit period, but only for qualifying reasons: employer bankruptcy, wage non-payment, workplace closure, physical/sexual violence, breach of employment conditions, or employer's refusal to renew contract. Burden of proof falls on the worker. Processing takes 2-3 months during which the worker is in limbo. If unable to find a new employer within 3 months, the worker must depart Korea.",
        "source": "Korea Ministry of Employment and Labor / NHRCK",
    },
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "EPS Workplace Change Denials — Structural Coercion",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "National Human Rights Commission of Korea (NHRCK) documented pattern: employers refuse to sign transfer consent ('workplace change agreement'), trapping workers in exploitative conditions. Workers who leave without consent become undocumented and subject to deportation. 3-change limit creates structural coercion: workers tolerate abuse rather than exhaust limited transfers. NHRCK recommended removing employer consent requirement.",
        "source": "NHRCK / Migrants' Trade Union (MTU)",
    },

    # ── KR Agricultural Sector ──────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "Agricultural Sector Exploitation — Korea's Greenhouse Farms",
        "exploitation_type": "abusive_working_conditions",
        "sector": "agriculture",
        "summary": "EPS agricultural workers (E-9 visa) face: extreme heat in vinyl greenhouses (50C+), pesticide exposure without PPE, housing in shipping containers or greenhouse annexes, 12-16 hour workdays during harvest with no overtime pay. Workers cannot easily change employers due to rural isolation and 3-transfer limit. Multiple deaths from heatstroke documented (2020-2024). Cambodian worker death in Pocheon (2020) triggered national outcry.",
        "source": "NHRCK / Korea National Agricultural Cooperative / Asan Migrant Worker Center",
    },
    {
        "type": "statistic",
        "jurisdiction": "KR",
        "title": "EPS Agricultural Worker Deaths in Korea (2020-2024)",
        "metric": "Documented migrant worker deaths in Korean agriculture",
        "value": "30+",
        "year": 2024,
        "details": "At least 30 EPS agricultural workers died in Korea between 2020-2024, primarily from heatstroke, pesticide exposure, and workplace accidents in greenhouses. Cambodian and Vietnamese workers disproportionately affected. Death certificates often list cardiac arrest without investigating occupational causes.",
        "source": "NHRCK / Asan Migrant Worker Center / Hankyoreh newspaper",
    },
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "Pocheon Greenhouse Deaths — Cambodian Worker Exploitation (2020)",
        "exploitation_type": "abusive_working_conditions",
        "sector": "agriculture",
        "corridor": "KH-KR",
        "summary": "Cambodian EPS worker Sokkheng died of suspected heatstroke in Pocheon strawberry greenhouse (Dec 2020). Found dead in unheated shipping container housing (-18C outside). Second Cambodian worker in same region died weeks later. Investigations revealed: 14-hour workdays, no heating in accommodation, no access to medical care. Cases triggered protests and National Assembly investigation into agricultural worker conditions.",
        "source": "Hankyoreh / NHRCK investigation / Korea Times",
    },

    # ── KR Fishing Sector ───────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "Korean Fishing Vessel Exploitation — E-10 Visa Workers",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "Migrant fishers on Korean vessels (E-10 visa, separate from EPS) face: confinement to vessel during port stays, 18-20 hour workdays, physical violence, wage withholding. Workers from Vietnam, Indonesia, Philippines. Unlike E-9 workers, E-10 fishers have weaker labour law protections — excluded from Labour Standards Act. Vessel owners control accommodation and movement. Multiple deaths documented, including drownings and suicides.",
        "source": "Korea Seafarers' Union / ILO / Advocates for Public Interest Law",
    },
    {
        "type": "statistic",
        "jurisdiction": "KR",
        "title": "Migrant Fisher Deaths on Korean Vessels (2017-2023)",
        "metric": "Documented E-10 visa worker deaths on Korean fishing vessels",
        "value": "86+",
        "year": 2023,
        "details": "At least 86 migrant fishers died on Korean vessels (2017-2023) per Coast Guard data. Causes include drowning, falls overboard, hypothermia, illness without medical treatment, and suspected suicides. Vietnamese and Indonesian workers account for 70%+ of deaths. Vessel operators rarely prosecuted.",
        "source": "Korea Coast Guard / NHRCK / Global Seafood Alliance",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "Korea Distant-Water Fisheries Act Amendments (2022)",
        "summary": "Amendments strengthened monitoring of Korean distant-water fishing vessels after IUU fishing and forced labour allegations. Requirements: electronic monitoring, crew rest periods, mandatory port calls. However, enforcement remains limited for vessels operating in distant waters (South Pacific, Indian Ocean). Korea has 210+ distant-water vessels employing 3,000+ migrant crew.",
        "source": "Korea Ministry of Oceans and Fisheries / EJF",
    },

    # ── KR Construction ─────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "Construction Sector Exploitation — EPS Workers in Korea",
        "exploitation_type": "excessive_overtime",
        "sector": "construction",
        "summary": "EPS construction workers in Korea face: 60-80 hour weeks, dangerous site conditions (falls, electrocution), unpaid overtime hidden as 'all-inclusive' salary. Subcontracting chains (main contractor to 2nd/3rd tier) obscure employer accountability. Workers report wage theft when subcontractor disappears. 52-hour workweek cap routinely violated. Construction accounts for 30%+ of EPS workplace fatalities.",
        "source": "Korea Occupational Safety and Health Agency / MTU",
    },

    # ── KR Manufacturing ────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "Small Manufacturing Factory Exploitation — EPS Realities",
        "exploitation_type": "withholding_wages",
        "sector": "manufacturing",
        "summary": "Small Korean manufacturing firms (under 30 employees) employ majority of EPS workers. Common issues: unpaid overtime (50-70 hours/week with only base 40 hours compensated), late salary payments, deductions for accommodation exceeding legal limits, verbal abuse. Workers fear complaint will lead to contract non-renewal and deportation. Labour inspections of small firms are infrequent.",
        "source": "Korea Ministry of Employment and Labor inspections / NHRCK",
    },
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "EPS Dormitory Fire Deaths — Industrial Zone Housing",
        "exploitation_type": "abusive_working_conditions",
        "sector": "manufacturing",
        "summary": "Multiple fatal fires in EPS worker dormitories attached to or near factories (Gimpo 2020, Pocheon 2021, Hwaseong 2024). Housing: vinyl greenhouses converted to accommodation, shipping containers, or factory annexes with no fire safety. 2024 Hwaseong lithium battery factory fire killed 23 workers (17 migrant workers from China, Laos, Thailand). No fire escapes or sprinklers. Emergency instructions in Korean only.",
        "source": "Yonhap News / Korea Times / NHRCK",
    },

    # ── KR Statistics & Policy ──────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "KR",
        "title": "Annual EPS Worker Intake (2023)",
        "metric": "EPS E-9 visa workers admitted per year",
        "value": "110,000 quota (2023)",
        "year": 2023,
        "details": "Korea set EPS quota at 110,000 for 2023, up from 69,000 in 2022 — largest increase ever. Driven by severe labour shortages in manufacturing, agriculture, fishing, construction. Total foreign workers in Korea: 860,000+ (registered) as of mid-2023.",
        "source": "Korea Ministry of Employment and Labor / Korea Immigration Service",
    },
    {
        "type": "statistic",
        "jurisdiction": "KR",
        "title": "Undocumented Migrant Workers in Korea (2023)",
        "metric": "Irregular foreign workers in Korea",
        "value": "415,000+",
        "year": 2023,
        "details": "Korea Immigration Service estimates 415,000+ undocumented foreign workers (2023). Many are former EPS workers who overstayed after permits expired — driven by high wages (compared to home countries) and difficulty returning under EPS. Undocumented workers have zero labour protections and are subject to crackdowns and deportation.",
        "source": "Korea Immigration Service / Ministry of Justice statistics",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "Korea Seasonal Worker Programme (E-8 Visa) Expansion",
        "summary": "Korea expanded the E-8 seasonal agricultural worker visa programme from pilot (2015) to nationwide deployment (2023). Allows up to 5 months work per year. Workers return home during off-season. 30,000+ seasonal workers in 2023. Reduces pressure on E-9 system. However, reports of similar exploitation: container housing, excessive hours, wage deductions for food/accommodation.",
        "source": "Korea Ministry of Employment and Labor / Rural Economic Institute",
    },
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "Discrimination Against Migrant Workers in Korea",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "NHRCK surveys document: 78% of migrant workers experienced discrimination in Korea. Forms include: racial slurs at workplace, denial of workplace injury compensation, exclusion from company events, landlord refusal to rent apartments, hospital staff refusing treatment, police dismissing complaints from foreign workers. Southeast Asian workers report higher discrimination than Chinese-Korean (Joseonjok) workers.",
        "source": "NHRCK annual migrant worker surveys / Amnesty International Korea",
    },
    {
        "type": "statistic",
        "jurisdiction": "KR",
        "title": "Migrant Worker Workplace Deaths in Korea (2019-2023)",
        "metric": "Foreign worker occupational fatalities annually",
        "value": "80-100+/year",
        "year": 2023,
        "details": "Korea Occupational Safety and Health Agency reports 80-100+ foreign worker deaths annually (2019-2023). Foreign workers die at 2-3x the rate of Korean workers. Agriculture, fishing, and construction account for 70%+. Investigations often cursory. Families in home countries receive limited compensation.",
        "source": "Korea Occupational Safety and Health Agency / NHRCK",
    },

    # ── KR NHRCK & Civil Society ────────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "KR",
        "title": "NHRCK Recommendations on EPS Reform (2023)",
        "summary": "National Human Rights Commission of Korea issued comprehensive EPS reform recommendations (2023): (1) remove employer consent for workplace change, (2) abolish 3-transfer limit, (3) extend agricultural worker protections equal to manufacturing, (4) mandate fire-safe housing standards, (5) create independent complaint mechanism. Government partially accepted items 4 and 5, rejected items 1-3 citing employer concerns.",
        "source": "National Human Rights Commission of Korea (NHRCK)",
    },
    {
        "type": "contact",
        "jurisdiction": "KR",
        "title": "Korea Migrant Worker Support Organizations",
        "summary": "Key support organizations: Migrants' Trade Union (MTU, Seoul), Asan Migrant Worker Center, Korea Migrant Workers' Human Rights Center, Ansan Foreign Workers' Center, Catholic Archdiocese of Seoul Migrant Pastoral Center. MTU is not officially recognized by Korean government as a legal union but operates as de facto representative. Korea 1345 immigration helpline (multi-language).",
        "source": "MTU / NHRCK directory / IOM Korea",
    },

    # ── KR Foreign Workforce Policy ─────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "Korea Foreign Workforce Policy Committee Reforms (2024)",
        "summary": "Korea's Foreign Workforce Policy Committee announced 2024 reforms: (1) sector-specific quota allocation (manufacturing 60%, agriculture 15%, fishing 10%, construction 15%), (2) pilot programme for mid-level skilled worker visa (E-7-4), (3) expanded Korean language training in-country, (4) electronic wage payment mandate for all EPS employers. Implementation timeline: 2024-2025.",
        "source": "Korea Ministry of Employment and Labor / Korea Herald",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "Korea Anti-Discrimination Legislation Stalled (2024)",
        "summary": "Comprehensive anti-discrimination bill covering race, nationality, and migration status has been proposed in Korean National Assembly repeatedly (2007, 2013, 2017, 2020, 2024) but never passed. Conservative opposition cites religious freedom and employer concerns. Without it, migrant workers have limited legal recourse against workplace discrimination. NHRCK can investigate but not compel remedies.",
        "source": "Korea National Assembly records / NHRCK / Amnesty International Korea",
    },

    # =====================================================================
    # JAPAN (JP) — TITP, SSW, and Labour Exploitation
    # =====================================================================

    # ── TITP Structure ──────────────────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "JP",
        "title": "Technical Intern Training Programme (TITP) — Structural Overview",
        "summary": "Japan's TITP (Ginou Jisshu Seido, established 1993) brings foreign workers as 'trainees' for skills transfer. Duration: up to 5 years (Technical Intern No. 1: 1 year, No. 2: 2 years, No. 3: 2 years). 90+ job categories across agriculture, fisheries, construction, food manufacturing, textiles, and more. Workers tied to single employer/supervising organization. Transfer only permitted in extraordinary circumstances. Despite 'training' designation, workers perform regular production labour.",
        "source": "Japan Ministry of Justice / JITCO / ILO",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "JP",
        "title": "TITP Supervision Structure — OTIT and Supervising Organizations",
        "summary": "TITP operates through: (1) OTIT (Organization for Technical Intern Training, established 2017) — government oversight body, (2) JITCO (Japan International Cooperation Organization) — advisory/support, (3) Supervising Organizations (Kanri Dantai) — ~3,400 licensed intermediaries that place interns with employers. Supervising Organizations often have financial ties to employers, creating conflict of interest in monitoring. OTIT conducts inspections but staff-to-intern ratio is severely inadequate.",
        "source": "OTIT / JITCO / Immigration Services Agency of Japan",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "TITP Exploitation Pattern — 'Training' as Cheap Labour",
        "exploitation_type": "deception",
        "sector": "manufacturing",
        "summary": "Systematic pattern documented by Japan Federation of Bar Associations: TITP trainees perform identical work to Japanese employees but at lower wages (minimum wage or below). 'Training plans' exist on paper but actual skills transfer is minimal. Trainees are production workers classified as students. Employers save 30-50% on labour costs. US State Department TIP Report repeatedly classifies TITP as having forced labour indicators.",
        "source": "Japan Federation of Bar Associations / US State Dept TIP Report",
    },

    # ── TITP Missing/Runaway Interns ────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "JP",
        "title": "TITP Missing Interns — Annual Disappearances",
        "metric": "Technical interns who left designated workplace (shissou)",
        "value": "9,006 (2023)",
        "year": 2023,
        "details": "9,006 TITP interns went missing (shissou/disappeared) from employers in 2023 per Immigration Services Agency data. 2018 peak: 9,052. Majority are Vietnamese (60%+), followed by Chinese and Indonesian. Interns leave due to: unpaid wages, excessive overtime, physical abuse, isolation. Once they leave, they become undocumented and vulnerable to further exploitation in underground economy.",
        "source": "Immigration Services Agency of Japan / NHK",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "Runaway TITP Interns — Underground Economy",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Interns who flee abusive employers become undocumented. Many find work in cash-economy jobs: construction day labour, food processing, hostess bars. Subject to wage theft (no legal recourse), arrest and deportation, and exploitation by criminal intermediaries (yakuza-linked labour brokers). Some Vietnamese former interns form communities in rural industrial areas (Gunma, Ibaraki, Chiba), working in agriculture under exploitative conditions.",
        "source": "NHK special investigations / Solidarity Network with Migrants Japan",
    },

    # ── TITP by Nationality ─────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "corridor": "VN-JP",
        "title": "Vietnamese TITP Interns — Largest National Group",
        "exploitation_type": "debt_bondage",
        "sector": "multiple",
        "summary": "Vietnamese comprise 55%+ of all TITP interns (~200,000). Vietnamese trainees pay USD 5,000-10,000 to Vietnamese brokers (despite Japan's ban on fees exceeding USD 3,600). Debt repaid over 2-3 years from minimum wage earnings. Brokers in Vietnam are politically connected, making regulation difficult. Workers endure exploitation to repay debt. Vietnamese government (DOLAB) nominally oversees sending agencies but enforcement is weak.",
        "source": "OTIT / Vietnam DOLAB / NHK / Nikkei Asia",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "corridor": "CN-JP",
        "title": "Chinese TITP Interns — Declining Numbers, Persistent Issues",
        "exploitation_type": "withholding_wages",
        "sector": "textiles",
        "summary": "Chinese TITP interns were the largest group until Vietnamese surpassed them (~2015). Still ~50,000 in Japan. Chinese interns in textile/sewing factories face: piece-rate pay below minimum wage, 14-16 hour workdays during peak production, dormitory confinement, confiscation of bankbooks. Chinese sending organizations (CHINTCO network) charge USD 3,000-8,000. Workers are older (30-40s) and more likely to have family debt pressure.",
        "source": "OTIT / Solidarity Network with Migrants Japan / Mainichi Shimbun",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "corridor": "ID-JP",
        "title": "Indonesian TITP Interns — Agricultural and Fisheries Exploitation",
        "exploitation_type": "isolation",
        "sector": "agriculture",
        "summary": "Indonesian TITP interns (~30,000 in Japan) concentrated in agriculture and fisheries in rural Hokkaido, Tohoku, and Kyushu. Extreme isolation: single intern in remote farm, no other Indonesian speakers, limited transport, nearest city hours away. Cultural and language barriers prevent complaint. Some farmers house interns in unheated sheds during winter (-10C). Physical abuse documented in Hokkaido fishing processing plants.",
        "source": "OTIT / Indonesian Embassy Tokyo / Hokkaido Shinbun",
    },

    # ── TITP Sectors ────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "TITP Textile Sector — Sewing Factory Sweatshops",
        "exploitation_type": "excessive_overtime",
        "sector": "textiles",
        "summary": "Textile/sewing factories in Gifu, Aichi, Shizuoka employ thousands of TITP interns. Documented: piece-rate pay of JPY 200-400/hour (minimum wage: JPY 1,002+), 12-16 hour days, forced overtime recorded as 'voluntary training', locked dormitories, passport retention. NHK investigation (2019) found factories paying JPY 300/hour. Many small operations fall below OTIT inspection threshold.",
        "source": "NHK / Gifu Labour Standards Inspection Office / JFBA",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "TITP Construction Sector — Fukushima and Olympic Projects",
        "exploitation_type": "deception",
        "sector": "construction",
        "summary": "TITP construction interns used for Fukushima nuclear decontamination work and 2020 Tokyo Olympic venue construction. Workers reported: being told work was 'construction training' but assigned to radiation zone cleanup, inadequate radiation monitoring, threats of deportation for refusing hazardous work. Fukushima exposure cases documented by Japan Federation of Bar Associations. Olympic construction complaints received by OTIT.",
        "source": "JFBA / Reuters / OTIT annual reports",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "TITP Fishing Sector — Coastal Vessel Exploitation",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "TITP fishing interns (5,000+) on Japanese coastal vessels face: 4am-8pm workdays, meals of fish scraps, sleeping on vessel, physical violence by captains, no days off during fishing season (2-3 months continuous). Interns from Indonesia, Vietnam, Philippines. Cannot leave vessel without captain's permission. OTIT inspections of vessels are rare due to logistical difficulty. Several interns found dead on vessels with inconclusive investigations.",
        "source": "OTIT / Japan Fisheries Agency / EJF Japan assessment",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "TITP Food Processing — Meat and Seafood Plants",
        "exploitation_type": "excessive_overtime",
        "sector": "food_processing",
        "summary": "TITP interns in food processing (meat packing, seafood processing, bento production) face: 12-14 hour shifts in cold/wet environments, repetitive strain injuries, chemical exposure (cleaning agents), forced overtime during peak production periods. Wage records falsified to show compliance. Workers in rural Hokkaido and Tohoku seafood plants particularly isolated. Vietnamese and Chinese workers predominate.",
        "source": "OTIT / Hokkaido Labour Bureau / Solidarity Network with Migrants Japan",
    },

    # ── TITP Wage Theft & Court Cases ───────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "JP",
        "title": "TITP Wage Theft — Gifu Sewing Factory Prosecution (2019)",
        "court": "Gifu District Court",
        "year": 2019,
        "summary": "Gifu sewing factory owner convicted of paying Chinese TITP interns JPY 300/hour (minimum wage JPY 851 at time). 150+ hours monthly overtime, unrecorded. Workers confined to dormitory, passports held by employer. Court ordered back-pay of JPY 18 million. Rare criminal prosecution — most wage theft cases settled at Labour Standards Inspection Offices without criminal charges.",
        "source": "Gifu District Court / Mainichi Shimbun / JFBA",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "TITP Physical Abuse Documentation — OTIT Findings",
        "exploitation_type": "physical_violence",
        "sector": "multiple",
        "summary": "OTIT annual reports document 200+ cases of physical abuse against TITP interns annually. Forms: hitting, kicking, throwing objects, burning with cigarettes, forcing interns to stand outside in cold. Employers rarely prosecuted — OTIT can revoke training plans but criminal referrals are uncommon. Supervising organizations that report abuse lose employers (and income), creating perverse incentive to conceal.",
        "source": "OTIT annual reports / Japan Federation of Bar Associations",
    },

    # ── Ikusei Shuro / TITP Reform ──────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "JP",
        "title": "Ikusei Shuro (Ikusei Employment) System — TITP Replacement (2024)",
        "summary": "Japan's Expert Panel recommended replacing TITP with 'Ikusei Shuro' (Ikusei Employment/Nurturing Employment) system effective 2027. Key changes: (1) workers can change employers after 1-2 years (major reform), (2) explicit aim is labour supply (not skills transfer fiction), (3) pathway to Specified Skilled Worker visa, (4) improved supervision. Critics note: employer change still restricted, sending-country broker fees unaddressed, implementation details pending.",
        "source": "Japan Immigration Services Agency / Advisory Panel Final Report (2024)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "JP",
        "title": "Specified Skilled Worker (SSW) Visa — Tokutei Ginou (2019)",
        "summary": "Japan created SSW visa category (2019) to address labour shortages: SSW-1 (14 sectors, up to 5 years, no family) and SSW-2 (construction and shipbuilding, renewable, family allowed). Target: 345,000 SSW workers by 2024. As of mid-2023: 170,000+ SSW holders. Workers can change employers within same sector. Many are former TITP interns. SSW does not require supervising organization intermediary. However, broker exploitation in sending countries persists.",
        "source": "Japan Immigration Services Agency / JICA",
    },

    # ── ILO Observations on Japan ───────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "JP",
        "title": "ILO Committee of Experts — Observations on Japan TITP (2023)",
        "summary": "ILO Committee of Experts on the Application of Conventions has repeatedly noted concerns about Japan's TITP: (1) indicators of forced labour present (employer-tied status, debt, document retention), (2) insufficient labour inspections, (3) complaints mechanism inadequate, (4) criminal prosecutions of employers rare. Japan asked to report on TITP reforms under Forced Labour Convention (C29). ILO welcomes Ikusei Shuro proposal but awaits implementation details.",
        "source": "ILO CEACR observations on Japan / C29 application reports",
    },
    {
        "type": "advisory",
        "jurisdiction": "JP",
        "title": "US TIP Report on Japan — Tier 2 Watch List History",
        "summary": "US State Department TIP Report has placed Japan on Tier 2 (not fully meeting minimum standards) for years, citing TITP forced labour indicators. Specific concerns: government complicity through inadequate oversight, failure to prosecute supervising organizations, victim identification among undocumented workers insufficient. Japan has never been Tier 1 since TITP evaluation began.",
        "source": "US State Department Trafficking in Persons Report (annual)",
    },

    # ── Japan Statistics ────────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "JP",
        "title": "Total TITP Interns in Japan (2023)",
        "metric": "Active TITP technical interns",
        "value": "358,000+",
        "year": 2023,
        "details": "358,000+ active TITP interns as of end-2023. By nationality: Vietnamese (55%), Indonesian (12%), Philippines (8%), Chinese (7%), Myanmar (5%), others (13%). By sector: food manufacturing (19%), construction (17%), agriculture (12%), machine/metal (10%), textiles (8%).",
        "source": "Immigration Services Agency of Japan / OTIT statistics",
    },
    {
        "type": "statistic",
        "jurisdiction": "JP",
        "title": "TITP Labour Standards Violations — Inspection Results",
        "metric": "Percentage of inspected TITP employers with violations",
        "value": "70.4% (2022)",
        "year": 2022,
        "details": "Ministry of Health, Labour and Welfare inspected 9,829 TITP workplaces in 2022. 70.4% (6,913) had violations: unpaid overtime (24%), unsafe work conditions (22%), excessive hours (19%), illegal wage deductions (15%). Only 41 cases referred for criminal prosecution. Inspection coverage: ~10% of all TITP workplaces annually.",
        "source": "Japan Ministry of Health, Labour and Welfare / Labour Standards Inspection Offices",
    },
    {
        "type": "statistic",
        "jurisdiction": "JP",
        "title": "TITP Intern Deaths in Japan (2019-2023)",
        "metric": "Reported TITP intern deaths",
        "value": "174 (5 years)",
        "year": 2023,
        "details": "Immigration Services Agency reported 174 TITP intern deaths (2019-2023). Causes: workplace accident (34%), suicide (20%), illness (26%), drowning (8%), traffic accident (8%), other (4%). Vietnamese interns account for largest share. Suicide rate among TITP interns is significantly higher than Japanese working-age population. Many deaths not investigated as workplace incidents.",
        "source": "Immigration Services Agency of Japan / JFBA / Nikkei Asia",
    },

    # =====================================================================
    # TAIWAN (TW) — Migrant Workers and Exploitation Patterns
    # =====================================================================

    # ── Taiwan Legal Framework ──────────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "TW",
        "title": "Employment Service Act — Taiwan's Migrant Worker Framework",
        "summary": "Taiwan's Employment Service Act (1992, amended) governs foreign worker employment. Permits employer-tied work permits in: manufacturing, construction, agriculture, fishing, domestic care, institutional care. Workers cannot freely change employers (exceptions for employer fault). Maximum stay: 12 years (extended from 9 in 2012). Broker system legally permitted — Taiwan is one of few countries that formally allows private brokers to charge workers recruitment fees.",
        "source": "Taiwan Ministry of Labor / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "TW",
        "title": "Taiwan Migrant Worker Population (2024)",
        "metric": "Total migrant workers in Taiwan",
        "value": "753,000+",
        "year": 2024,
        "details": "753,000+ migrant workers in Taiwan as of mid-2024. By nationality: Indonesian (37%), Vietnamese (35%), Philippine (10%), Thai (18%). By sector: manufacturing (42%), domestic/institutional care (30%), fishing (2%), agriculture (3%), construction (3%), others (20%). Growth driven by aging population and declining Taiwanese birth rate.",
        "source": "Taiwan Ministry of Labor Workforce Development Agency statistics",
    },

    # ── Taiwan Broker System ────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Taiwan Broker System — Legalized Recruitment Fees",
        "exploitation_type": "debt_bondage",
        "sector": "multiple",
        "summary": "Taiwan's legal broker system allows agencies to charge workers: up to 1 month's salary per year of contract as 'service fee' plus sending-country fees. Total worker-borne cost: USD 3,000-7,000 for Indonesian workers, USD 2,000-5,000 for Vietnamese, USD 2,000-4,000 for Filipinos, USD 3,000-6,000 for Thais. First 1-2 years of wages go to debt repayment. Brokers control employer placement, renewal, and transfer — creating dependency.",
        "source": "Taiwan International Workers' Association (TIWA) / ILO",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "TW",
        "title": "Taiwan Direct Hiring Joint Service Center (DHJSC)",
        "summary": "Taiwan established the Direct Hiring Joint Service Center (2008) to allow employers to hire migrant workers without broker intermediaries. Government-managed process reduces costs. However, adoption remains low: less than 5% of migrant workers hired through DHJSC. Brokers lobby against expansion, employers prefer broker convenience, workers in home countries have limited access to DHJSC channels.",
        "source": "Taiwan Ministry of Labor / TIWA / IOM",
    },

    # ── Taiwan Fishing Sector ───────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Taiwan Distant-Water Fishing Fleet — Forced Labour at Sea",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "Taiwan operates 1,100+ distant-water fishing vessels (world's 2nd largest fleet). Employ 20,000+ migrant crew (primarily Indonesian, Filipino, Vietnamese). Workers face: 18-22 hour workdays, 1-2 years at sea without port call, physical violence, food deprivation, wage withholding (USD 300-450/month, often unpaid). Documented murders of crew by captains. Workers recruited through manning agencies in home countries — not covered by Taiwan Labour Standards Act.",
        "source": "Greenpeace / EJF / Taiwan Fisheries Agency",
    },
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Fong Chun Formosa No. 368 — Fishing Vessel Abuse Case (2020)",
        "exploitation_type": "physical_violence",
        "sector": "fishing",
        "summary": "Indonesian crew on Taiwanese vessel Fong Chun Formosa No. 368 documented severe abuse via smartphone video: captain beating crew with metal pipe, food restrictions (rice and salt only), 20-hour workdays, crew member thrown overboard. Video went viral (2020). Taiwan Fisheries Agency revoked vessel license. Captain fined but not imprisoned. Highlighted gap between Taiwanese and international waters regulations.",
        "source": "EJF / Greenpeace / Taiwan Fisheries Agency investigation",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "TW",
        "title": "Taiwan Action Plan for Fisheries and Human Rights (2022)",
        "summary": "Following EU IUU yellow card warning (2015, lifted 2019) and US TIP Report Tier 2 Watch List placement, Taiwan adopted Action Plan for Fisheries and Human Rights (2022): mandatory CCTV on distant-water vessels, electronic reporting, port state inspections, Wi-Fi for crew communication, minimum rest hours. Implementation mixed — vessel owners resist CCTV, Wi-Fi often non-functional. Coastal vessels under separate (weaker) regime.",
        "source": "Taiwan Fisheries Agency / Control Yuan audit / Greenpeace",
    },
    {
        "type": "statistic",
        "jurisdiction": "TW",
        "title": "Deaths and Disappearances on Taiwanese Fishing Vessels (2017-2023)",
        "metric": "Documented crew deaths/disappearances on Taiwan-flagged vessels",
        "value": "60+",
        "year": 2023,
        "details": "At least 60 crew members died or disappeared from Taiwan-flagged distant-water fishing vessels (2017-2023) per Taiwan Fisheries Agency and NGO tracking. Indonesian and Filipino crew account for 80%+. Causes: falls overboard (often under suspicious circumstances), illness without medical treatment, violence. Only 3 criminal prosecutions in this period.",
        "source": "EJF / Greenpeace / Taiwan Fisheries Agency",
    },

    # ── Taiwan Factory Workers ──────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Taiwan Factory Worker Exploitation — Manufacturing Sector",
        "exploitation_type": "excessive_overtime",
        "sector": "manufacturing",
        "summary": "Migrant workers in Taiwan's manufacturing sector (280,000+, primarily Vietnamese and Indonesian) face: forced overtime (60-80 hours/month, often unrecorded), wage deductions for dormitory and food (USD 100-200/month), movement restrictions in employer-controlled dormitories, broker threats of repatriation for complaining. Workers must pay broker 'service fees' from salary for entire employment period. Changing employers requires broker cooperation.",
        "source": "TIWA / Serve the People Association (SPA) / Taiwan Ministry of Labor inspections",
    },
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Taiwan Electronics Factory — Migrant Worker Conditions",
        "exploitation_type": "withholding_wages",
        "sector": "manufacturing",
        "summary": "Taiwan's electronics manufacturing (PCB, semiconductors, components) employs 60,000+ migrant workers. Reports of: base wage paid at minimum but overtime calculated at lower rate, mandatory 'savings' deducted and held by employer, dormitory deposits forfeited for minor rule infractions. Workers producing for global supply chains (Apple, Dell, HP via Foxconn, Pegatron, Wistron). Some improvements after brand audits, but small-to-mid suppliers less scrutinized.",
        "source": "Electronics Watch / SPA / Taiwan Ministry of Labor",
    },

    # ── Taiwan Domestic Caregivers ──────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Taiwan Domestic Caregiver Exploitation — 24-Hour On-Call",
        "exploitation_type": "excessive_overtime",
        "sector": "domestic_work",
        "summary": "220,000+ migrant caregivers in Taiwan (primarily Indonesian and Filipino) care for elderly/disabled persons. Excluded from Labour Standards Act — no maximum hours, no mandatory rest day, no overtime pay. Workers effectively on-call 24 hours. Average work: 15-18 hours/day. Minimum wage applies (TWD 20,000/month) but no overtime compensation. Employer may assign household chores beyond caregiving. Broker system makes escape difficult as workers owe ongoing fees.",
        "source": "TIWA / Amnesty International / Taiwan Control Yuan investigation",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "TW",
        "title": "Taiwan Labour Standards Act — Domestic Worker Exclusion",
        "summary": "Taiwan's Labour Standards Act explicitly excludes domestic workers (including migrant caregivers). Despite decades of advocacy by TIWA and other NGOs, a standalone Domestic Workers Protection Act has failed to pass the Legislative Yuan. Current protections: minimum wage only (no hours cap, no mandatory rest, no overtime). Taiwan remains the only developed Asian economy without comprehensive domestic worker legislation. ILO C189 (Domestic Workers Convention) not ratified.",
        "source": "Taiwan Legislative Yuan records / TIWA / ILO C189 ratification tracker",
    },

    # ── Taiwan by Worker Nationality ────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Indonesian Workers in Taiwan — Broker Fee Crisis",
        "exploitation_type": "debt_bondage",
        "sector": "multiple",
        "corridor": "ID-TW",
        "summary": "Indonesian workers pay highest broker fees for Taiwan: USD 4,000-7,000 (sending + receiving side). Indonesia's BNP2MI sets maximum fees but enforcement is weak. Workers sign debt agreements before departure. First 14-18 months of wages go to debt repayment. Indonesian government has periodically threatened moratoriums on Taiwan deployment over fee issues (most recently 2022). Taiwan and Indonesia signed updated MOU (2023) with fee caps, but implementation remains unclear.",
        "source": "BNP2MI / TIWA / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Vietnamese Workers in Taiwan — Growing Population, Persistent Issues",
        "exploitation_type": "deception",
        "sector": "manufacturing",
        "corridor": "VN-TW",
        "summary": "Vietnamese migrant workers in Taiwan (~260,000) are now the second-largest group. Issues: contract substitution (promised factory work, assigned to caregiving or fishing), broker fees of USD 4,000-6,000 to Vietnamese agencies, limited Chinese language skills impeding complaint, Vietnamese brokers operating illegally in Taiwan. Vietnamese workers have highest rate of running away from employers (2,000+/year) indicating systemic dissatisfaction.",
        "source": "Taiwan Ministry of Labor / Vietnamese Workers' Union in Taiwan / TIWA",
    },
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Filipino Workers in Taiwan — Declining Numbers, Better Protections",
        "exploitation_type": "withholding_wages",
        "sector": "manufacturing",
        "corridor": "PH-TW",
        "summary": "Filipino workers in Taiwan (~77,000) have declined from peak as Philippines directs deployment to higher-wage destinations. Filipino workers benefit from: Manila Economic and Cultural Office (MECO) oversight, English language advantage for complaint, Philippine government intervention on wage disputes. However, factory workers still report: 12-hour shifts, deductions for dormitory at above-market rates, restricted movement. MECO processes 3,000+ labour complaints annually.",
        "source": "MECO / Philippine Department of Migrant Workers / TIWA",
    },

    # ── Taiwan Hotline & Support ────────────────────────────────────────
    {
        "type": "contact",
        "jurisdiction": "TW",
        "title": "Taiwan 1955 Migrant Worker Hotline",
        "summary": "Taiwan's 1955 hotline (established 2009) provides 24-hour multilingual assistance for migrant workers in Indonesian, Vietnamese, Thai, Filipino, and English. Services: labour complaint intake, emergency rescue, shelter referral, legal aid referral. Receives 200,000+ calls annually. Operated by Ministry of Labor. Effective for crisis intervention but systemic issues (broker fees, employer-tied permits) persist despite individual case resolution.",
        "source": "Taiwan Ministry of Labor / 1955 hotline annual reports",
    },

    # ── Taiwan Runaway Workers ──────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "TW",
        "title": "Runaway Migrant Workers in Taiwan (2023)",
        "metric": "Migrant workers who left designated employers",
        "value": "55,000+ (cumulative undocumented)",
        "year": 2023,
        "details": "Taiwan has an estimated 55,000+ undocumented migrant workers who left designated employers, as of 2023. Annual runaways: 15,000-20,000. Vietnamese workers account for 60%+. Causes: broker debt pressure, employer abuse, desire for higher-wage informal work. Undocumented workers face: no labour protections, exploitation in informal economy, arrest and deportation. Taiwan conducts periodic crackdowns.",
        "source": "Taiwan National Immigration Agency / Taiwan Ministry of Labor",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "TW",
        "title": "Taiwan Migrant Worker Employment Gold Card Pilot (2023)",
        "summary": "Taiwan piloted new measures to reduce runaway worker numbers: (1) expanded employer change channels, (2) shortened transfer processing time to 14 days, (3) language-friendly complaint QR codes in dormitories, (4) broker penalty escalation for fee violations. Early results: 10% reduction in runaways in pilot areas. Scaled to nationwide in 2024. However, fundamental broker fee structure unchanged.",
        "source": "Taiwan Ministry of Labor / Workforce Development Agency",
    },

    # =====================================================================
    # CHINA (CN) — State-Imposed and Systemic Labour Exploitation
    # =====================================================================

    # ── Xinjiang ────────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "Xinjiang Uyghur Forced Labour — State-Imposed Programme",
        "exploitation_type": "state_imposed",
        "sector": "manufacturing",
        "summary": "Chinese government operates 'surplus labour transfer' programmes relocating Uyghurs and other Turkic minorities from Xinjiang to factories across China. Workers under constant surveillance (cameras, minders, political sessions), cannot leave or communicate freely, earn below minimum wage with deductions for 'training'. 80,000+ transferred to factories in eastern China (2017-2020). Products enter global supply chains in textiles, electronics, automotive, and solar panels.",
        "source": "ASPI / Sheffield Hallam University / US State Department",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "US",
        "title": "US Uyghur Forced Labor Prevention Act (UFLPA) — 2021",
        "summary": "UFLPA (signed Dec 2021, effective June 2022) creates rebuttable presumption that goods from Xinjiang or produced by entities on UFLPA Entity List are made with forced labour. US Customs and Border Protection (CBP) must detain such imports. By 2024: 8,500+ shipments detained/denied, valued at USD 2.8 billion+. Commodities: cotton, polysilicon, tomato products, seafood, PVC. Forced companies to audit Xinjiang supply chain links.",
        "source": "US CBP / Congressional Research Service / UFLPA entity list",
    },
    {
        "type": "statistic",
        "jurisdiction": "CN",
        "title": "Xinjiang Internment and Labour Transfer Estimates",
        "metric": "Uyghurs in detention/forced labour programmes",
        "value": "1-1.8 million (detention), 80,000+ (transferred)",
        "year": 2023,
        "details": "Estimates of Uyghurs in internment: 1-1.8 million (ASPI, 2020). Labour transfer programmes: 80,000+ to factories outside Xinjiang, 500,000+ within Xinjiang agriculture (cotton picking, tomato harvesting). 83 brands linked to Uyghur forced labour supply chains per ASPI. China denies forced labour, calls facilities 'vocational training centres'.",
        "source": "ASPI / Adrian Zenz research / OHCHR Xinjiang report (2022)",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "OHCHR Assessment of Xinjiang Human Rights (2022)",
        "summary": "UN High Commissioner for Human Rights released assessment (Aug 2022) finding: serious human rights violations in Xinjiang that may constitute crimes against humanity. Documented: torture, arbitrary detention, forced labour, forced sterilization, cultural destruction. China rejected findings. Assessment was final act of HC Michelle Bachelet's tenure. Recommended China release all arbitrarily detained individuals.",
        "source": "OHCHR Assessment of Human Rights Concerns in Xinjiang (2022)",
    },

    # ── Hukou System ────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "Hukou System — Internal Migration Exploitation",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "China's hukou (household registration) system ties social services (healthcare, education, housing) to birthplace registration. 280+ million internal rural-to-urban migrants lack urban hukou, creating second-class workforce. Consequences: no access to urban public schools (children left behind in villages), no urban healthcare coverage, employer exploitation (no recourse without local registration), discrimination in housing and services. Reforms incremental.",
        "source": "China National Bureau of Statistics / ILO China / UNDP China",
    },
    {
        "type": "statistic",
        "jurisdiction": "CN",
        "title": "China Internal Migrant Worker Population",
        "metric": "Rural-to-urban migrant workers in China",
        "value": "296 million (2023)",
        "year": 2023,
        "details": "296 million rural migrant workers (nongmingong) in China (2023). Average monthly income: CNY 4,780 (USD 660). Work in: construction (19%), manufacturing (27%), services (30%), mining, transport. 60% have no written employment contract. Wage arrears affect 2-5 million workers annually. Construction sector has worst wage arrears problem.",
        "source": "China National Bureau of Statistics / China Labour Bulletin",
    },
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "Construction Wage Arrears Crisis — China's Internal Migrants",
        "exploitation_type": "withholding_wages",
        "sector": "construction",
        "summary": "China's construction sector has endemic wage arrears: developers pay contractors, contractors pay subcontractors, but workers at the bottom may go months or years without full payment. 'Year-end wage rush' before Chinese New Year is annual crisis. Government campaigns recover billions annually but problem persists. In 2022, CNY 64.7 billion recovered for 6.14 million workers. Some workers protest on buildings or cranes, facing arrest.",
        "source": "China Ministry of Human Resources / China Labour Bulletin / Caixin",
    },

    # ── China Distant-Water Fishing ─────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "Chinese Distant-Water Fishing Fleet — Forced Labour at Sea",
        "exploitation_type": "restriction_of_movement",
        "sector": "fishing",
        "summary": "China operates the world's largest distant-water fishing fleet (2,600+ vessels, some estimates 17,000+ including grey fleet). Indonesian, Filipino, and Chinese crew (from poor inland provinces) face: 22-hour workdays, months at sea without port, physical abuse, wage withholding. Manning agencies in Indonesia and Philippines charge USD 500-1,500 for placement. Sea-based transfer between vessels prevents shore leave. Bodies reportedly thrown overboard. EJF, Greenpeace, AP, and The Outlaw Ocean Project investigations.",
        "source": "EJF / Greenpeace / The Outlaw Ocean Project / UNODC",
    },
    {
        "type": "statistic",
        "jurisdiction": "CN",
        "title": "Chinese Distant-Water Fleet Scale and Crew",
        "metric": "Chinese distant-water fishing vessels and crew",
        "value": "2,600+ (official) to 17,000+ (estimated total)",
        "year": 2023,
        "details": "China's official distant-water fleet: 2,600+ vessels (Ministry of Agriculture). Estimated total including sub-contracted, joint venture, and unregistered vessels: 6,000-17,000 (Overseas Development Institute/Global Fishing Watch). Crew: 50,000-200,000, including Chinese nationals from Shandong, Fujian provinces and Southeast Asian crew hired through manning agencies. Operations in South Pacific, Indian Ocean, West Africa, South Atlantic.",
        "source": "Global Fishing Watch / ODI / China Ministry of Agriculture",
    },

    # ── Belt and Road Labour ────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Belt and Road Initiative — Chinese Labour Export Issues",
        "exploitation_type": "deception",
        "sector": "construction",
        "summary": "China's Belt and Road Initiative (BRI) deploys Chinese workers to infrastructure projects across Asia, Africa, and Latin America. Issues: workers promised high wages but arrive to find contract substitution, passport confiscation by Chinese construction companies, 16-hour workdays, deductions for food and housing, remote project locations preventing escape. Documented in: Pakistan (CPEC), Sri Lanka (Hambantota), Indonesia, Laos, Ethiopia, Nigeria. Workers' complaints suppressed by Chinese embassy intervention.",
        "source": "China Labour Bulletin / Business & Human Rights Resource Centre / WSJ",
    },
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "BRI Worker Exploitation in Africa — Chinese-on-Chinese Labour Abuse",
        "exploitation_type": "withholding_wages",
        "sector": "construction",
        "summary": "Chinese construction workers in Africa (Algeria, Ethiopia, Nigeria, Angola) recruited by labour brokers in Sichuan, Henan, and Hebei provinces. Workers pay CNY 20,000-50,000 to brokers for placement. Arrive to find: lower wages than promised, shared dormitories in isolated compounds, passport retention by company, 12-hour workdays in extreme heat, medical care denied. Workers who protest face repatriation at own expense. Hundreds of cases documented.",
        "source": "China Labour Bulletin / Global Construction Review / Caixin",
    },

    # ── North Korean Workers in China ───────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "North Korean Workers in China — State-Sponsored Forced Labour",
        "exploitation_type": "state_imposed",
        "sector": "manufacturing",
        "summary": "An estimated 20,000-50,000 North Korean workers in China (primarily Liaoning, Jilin provinces bordering DPRK). Work in: restaurants, textiles, seafood processing, construction. Up to 90% of wages confiscated by DPRK minders. Workers under constant surveillance, cannot defect, severe punishment for violations. UN Security Council Resolution 2397 (2017) required repatriation by Dec 2019 — China has not fully complied. Workers generate estimated USD 200-500 million annually for DPRK regime.",
        "source": "UN Panel of Experts on DPRK / Database Center for NK Human Rights / Associated Press",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "CN",
        "title": "UNSC Resolution 2397 — North Korean Worker Repatriation Deadline",
        "summary": "UN Security Council Resolution 2397 (Dec 2017) required all UN member states to repatriate North Korean workers by 22 December 2019. China and Russia (largest hosts) reported partial compliance. Evidence suggests thousands of DPRK workers remain, relabelled as 'trainees', 'students', or using fraudulent documentation. China blocks independent monitoring. Workers have no ability to seek asylum or report exploitation.",
        "source": "UN Security Council / Panel of Experts on DPRK sanctions",
    },

    # ── China Technology Sector ─────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "Foxconn and Electronics Manufacturing — Student Worker Exploitation",
        "exploitation_type": "excessive_overtime",
        "sector": "manufacturing",
        "summary": "Foxconn (Apple's primary assembler) and other electronics manufacturers use 'student internship' programmes: vocational school students aged 16-18 required to work 6-12 month factory placements as condition of graduation. Work: assembly line production identical to regular workers. Schools receive per-student payments from factories. Students cannot refuse or choose factory. Documented: 12-hour shifts, night work, exposure to chemicals. Apple and other brands audit but practice persists at supplier level.",
        "source": "China Labor Watch / SACOM (Students and Scholars Against Corporate Misbehaviour) / Reuters",
    },
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "Forced Labour in Chinese Polysilicon — Solar Panel Supply Chain",
        "exploitation_type": "state_imposed",
        "sector": "manufacturing",
        "summary": "Xinjiang produces 35-45% of world's polysilicon (key solar panel material). Four major producers (Daqo, GCL, East Hope, Xinte) operate in Xinjiang region. Evidence of Uyghur forced labour in: quartz mining, polysilicon production, and auxiliary factory operations. Sheffield Hallam University report (2021) documented supply chain links to major global solar panel brands. UFLPA enforcement led to seizure of solar panel shipments. Industry scrambling to diversify supply chains away from Xinjiang.",
        "source": "Sheffield Hallam University / Solar Energy Industries Association / US CBP UFLPA data",
    },

    # =====================================================================
    # ADDITIONAL SOUTH KOREA (KR) FACTS
    # =====================================================================
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "EPS Insurance System — Departure Guarantee Insurance",
        "exploitation_type": "withholding_wages",
        "sector": "multiple",
        "summary": "EPS workers pay into mandatory Departure Guarantee Insurance (KRW ~400,000/year) and Return Cost Insurance. Funds accumulated over employment period meant to be returned upon departure. However, workers who overstay or whose employers fail to file proper paperwork cannot claim insurance. An estimated KRW 120 billion in unclaimed departure guarantee funds (2010-2022). System designed to incentivize return but effectively withholds earned savings from workers.",
        "source": "Seoul Guarantee Insurance / MTU / Korea Ministry of Employment and Labor",
    },
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "Korean Language Barrier — Workplace Safety Fatalities",
        "exploitation_type": "abusive_working_conditions",
        "sector": "construction",
        "summary": "Korean language barrier contributes to workplace fatalities: safety instructions in Korean only, emergency procedures not translated, warning signs not multilingual. KOSHA (Korea Occupational Safety and Health Agency) found 80%+ of EPS workplace accidents involved communication failures. Workers unable to read chemical labels, machine operating instructions, or evacuation procedures. Multilingual workplace safety mandate issued 2023 but compliance low in small firms.",
        "source": "KOSHA / NHRCK / Korea Ministry of Employment and Labor",
    },
    {
        "type": "statistic",
        "jurisdiction": "KR",
        "title": "EPS Worker Nationalities — Top Sending Countries (2023)",
        "metric": "EPS workers by sending country",
        "value": "16 countries, led by Vietnam and Cambodia",
        "year": 2023,
        "details": "Top EPS sending countries (2023 quota allocation): Vietnam (largest), Cambodia, Nepal, Indonesia, Philippines, Thailand, Myanmar, Sri Lanka, Bangladesh, Uzbekistan, Mongolia, Pakistan, China, Timor-Leste, Laos, Kyrgyzstan. Vietnam and Cambodia together account for ~40% of new entries. Country quotas adjusted annually based on: return rates, compliance, bilateral relationship quality.",
        "source": "Korea HRD Service / Korea Ministry of Employment and Labor",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "Korea Anti-Trafficking Law — Act on Prevention of Trafficking in Persons (2023)",
        "summary": "Korea enacted the Act on Prevention of Trafficking in Persons and Protection of Victims (Dec 2023, effective 2024). For the first time, Korea has a standalone anti-trafficking law (previously relied on patchwork of criminal and immigration provisions). Establishes: legal definition of trafficking aligned with Palermo Protocol, victim identification mechanism, protection provisions, National Anti-Trafficking Committee. US TIP Report welcomed the legislation but noted implementation pending.",
        "source": "Korea National Assembly / US State Dept TIP Report / NHRCK",
    },
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "Hwaseong Lithium Battery Factory Fire — 23 Deaths (2024)",
        "exploitation_type": "abusive_working_conditions",
        "sector": "manufacturing",
        "summary": "Fire at Aricell lithium battery factory in Hwaseong, Gyeonggi Province (June 2024) killed 23 workers — 17 were migrant workers from China (12), Laos (3), and Thailand (2). Workers were on E-9 EPS visas and dispatch worker contracts. Investigation found: no fire suppression system, locked emergency exits, lithium batteries improperly stored, workers not trained in fire response. Emergency announcements in Korean only. Triggered national debate on migrant worker industrial safety.",
        "source": "Yonhap News / Korea Ministry of Employment and Labor / Korea Times",
    },
    {
        "type": "case_study",
        "jurisdiction": "KR",
        "title": "Migrant Workers' Trade Union (MTU) — Legal Status Battle",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "The Migrants' Trade Union (MTU), founded 2005, fought for legal recognition as a union for over a decade. Korea's Supreme Court ruled (2015) that undocumented workers have the right to form a union, but the Ministry of Employment and Labor continued to deny MTU registration citing inclusion of undocumented members. MTU finally registered (2024) after excluding undocumented members — controversial compromise. MTU represents 2,000+ EPS workers and advocates for: workplace change reform, safety improvements, anti-discrimination.",
        "source": "MTU / Korea Supreme Court ruling 2015Du39361 / Korea Herald",
    },

    # ── Additional Japan (JP) Facts ─────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "TITP Pregnancy and Maternity — Forced Abortions and Deportation",
        "exploitation_type": "physical_sexual_violence",
        "sector": "multiple",
        "summary": "Female TITP interns who become pregnant face: employer demands for abortion, termination of training contract, forced return home. Contracts sometimes explicitly prohibit pregnancy. Cases documented of employers and supervising organizations arranging abortions without worker consent. A Vietnamese intern convicted of abandoning a stillborn baby (later overturned on appeal, 2021) highlighted the desperation of pregnant interns with no support. OTIT guidelines prohibit pregnancy-based dismissal but enforcement is rare.",
        "source": "JFBA / NHK / Solidarity Network with Migrants Japan / Nagoya High Court (2021 appeal)",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "TITP Agricultural Worker Exploitation — Ibaraki and Chiba",
        "exploitation_type": "excessive_overtime",
        "sector": "agriculture",
        "summary": "Ibaraki and Chiba prefectures (near Tokyo) host thousands of TITP agricultural interns growing vegetables and flowers. Workers report: 5am-7pm shifts (14 hours), pay below minimum wage when calculated hourly, deductions for accommodation in agricultural sheds, exposure to pesticides without training or PPE, no heating in winter housing. Vietnamese and Chinese interns predominate. Labour Standards Inspection Office finds violations in 60%+ of inspected agricultural TITP workplaces.",
        "source": "OTIT / Ibaraki Labour Standards Inspection Office / JA (Japan Agricultural Cooperatives)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "JP",
        "title": "Japan Immigration Act Amendment — Enhanced Immigration Enforcement (2023)",
        "summary": "Japan amended the Immigration Control and Refugee Recognition Act (2023), allowing: expedited deportation of repeat immigration offenders, immigration detention without time limit (controversial), designation of 'supervisory accommodation' (alternatives to detention). UNHCR and NGOs criticized provisions as targeting vulnerable populations including TITP runaways. Act also established: complementary protection status (for non-refugee humanitarian cases), quasi-asylum provisions. Mixed impact on migrant worker protection.",
        "source": "Japan Ministry of Justice / UNHCR Japan / Japan Lawyers Network for Refugees",
    },
    {
        "type": "statistic",
        "jurisdiction": "JP",
        "title": "Total Foreign Workers in Japan (2023)",
        "metric": "Foreign workers in Japan by visa category",
        "value": "2.05 million (record high, Oct 2023)",
        "year": 2023,
        "details": "Japan reached record 2.05 million foreign workers (Oct 2023). Categories: TITP 358,000 (17%), SSW 194,000 (9%), permanent/long-term residents 596,000 (29%), part-time students 344,000 (17%), professional/technical 596,000 (29%). By nationality: Vietnamese (26%), Chinese (19%), Filipino (11%), Nepali (7%), Indonesian (6%). Government projects need for 6.74 million foreign workers by 2040.",
        "source": "Japan Ministry of Health, Labour and Welfare / Immigration Services Agency",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "TITP Supervising Organization Corruption — Profit-Driven Exploitation",
        "exploitation_type": "deception",
        "sector": "multiple",
        "summary": "Supervising organizations (kanri dantai) collect monthly management fees from employers (JPY 25,000-50,000 per intern). With 358,000+ interns, the industry generates JPY 100+ billion annually. OTIT revoked licenses of 40+ organizations (2017-2023) for: failing to investigate abuse complaints, colluding with employers on wage fraud, charging interns illegal fees, providing false training plans. However, 3,400+ organizations remain, many small operators with minimal oversight. System creates intermediary with financial incentive to maintain employer relationships, not protect workers.",
        "source": "OTIT / JITCO / Japan Ministry of Justice statistics",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "Vietnamese Community Mutual Aid — Informal Support Networks",
        "exploitation_type": "abuse_of_vulnerability",
        "sector": "multiple",
        "summary": "Vietnamese community in Japan (500,000+, largest foreign population) has developed informal mutual aid networks: Facebook groups for TITP workers sharing abuse information, Vietnamese temple networks providing shelter, community organizations (Tomo no Kai) offering legal consultation, food banks for unemployed workers. These networks partially compensate for inadequate government support but also expose workers to: unlicensed labour brokers, fake visa services, and exploitation by Vietnamese criminal networks operating in Japan.",
        "source": "NHK / Solidarity Network with Migrants Japan / Vietnamese community organizations",
    },

    # ── Additional Taiwan (TW) Facts ────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Taiwan Coastal Fishing — Different Regime, Same Exploitation",
        "exploitation_type": "excessive_overtime",
        "sector": "fishing",
        "summary": "Taiwan's 20,000+ coastal fishing vessels employ migrant fishers under regulations separate from (and weaker than) distant-water fleet rules. Coastal fishers (primarily Indonesian and Vietnamese) face: same exploitation patterns (long hours, low wages, violence) without distant-water fleet's post-reform monitoring (CCTV, electronic reporting). Hired through local brokers in port towns. Not covered by Labour Standards Act. Minimum wage: TWD 20,000/month but often unpaid. Port-based so no at-sea isolation, but workers live on vessels.",
        "source": "Taiwan Fisheries Agency / Yilan Migrant Fishermen Union / Greenpeace Taiwan",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "TW",
        "title": "Taiwan Long-Term Care 2.0 Policy — Migrant Caregiver Demand",
        "summary": "Taiwan's Long-Term Care 2.0 plan (2017-2026) aims to build community-based care infrastructure. However, institutional care capacity insufficient — 220,000+ families rely on migrant live-in caregivers instead. Government cannot restrict migrant caregiver hiring without providing alternative care. This dependency makes reform of caregiver labour conditions politically difficult: any regulation (hours caps, rest days) would increase costs for ageing families. Taiwan's over-65 population projected to reach 41% by 2070.",
        "source": "Taiwan Ministry of Health and Welfare / National Development Council population projections",
    },
    {
        "type": "case_study",
        "jurisdiction": "TW",
        "title": "Thai Workers in Taiwan — Declining but Trapped",
        "exploitation_type": "debt_bondage",
        "sector": "manufacturing",
        "corridor": "TH-TW",
        "summary": "Thai workers in Taiwan (~133,000) have been declining as Thailand's economy improves and alternative destinations emerge. Remaining workers are often: longer-term residents (8-12 years), working in manufacturing, locked into broker fee repayment cycles. Thai brokers charge USD 4,000-6,000. Thai workers report: less access to support networks than Indonesian or Vietnamese workers, language barrier (Thai interpreters scarce in Taiwan), aging workforce with health issues and limited healthcare access.",
        "source": "Taiwan Ministry of Labor / Thai Workers' Association in Taiwan / IOM",
    },
    {
        "type": "statistic",
        "jurisdiction": "TW",
        "title": "Taiwan Migrant Worker Labour Complaints (2023)",
        "metric": "Formal labour complaints filed by migrant workers",
        "value": "28,000+ (2023)",
        "year": 2023,
        "details": "Migrant workers in Taiwan filed 28,000+ formal complaints (2023) through 1955 hotline and labour bureaus. Top issues: wage disputes (35%), broker fee disputes (20%), working conditions (15%), employer abuse (10%), workplace transfer (10%), other (10%). Resolution: 60% settled through mediation, 20% referred to labour inspection, 10% to courts, 10% dropped. Average resolution time: 45-90 days.",
        "source": "Taiwan Ministry of Labor / 1955 hotline statistics / Workforce Development Agency",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "TW",
        "title": "Taiwan Immigration Act Amendment — Permanent Residency for Blue-Collar Workers (2023)",
        "summary": "Taiwan amended the Immigration Act (2023) to allow 'intermediate skilled' migrant workers a pathway to permanent residency after meeting criteria: 6+ years of work, Chinese language proficiency, skills certification, and employer sponsorship. Previously, blue-collar migrant workers had no path to permanent residence regardless of years worked. Initial implementation limited — few workers meet all criteria simultaneously. Advocacy groups call it a step forward but note employer sponsorship requirement maintains power imbalance.",
        "source": "Taiwan National Immigration Agency / Taiwan Ministry of Labor / TIWA",
    },

    # ── Additional China (CN) Facts ─────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "Xinjiang Cotton Production — Forced Labour in Agriculture",
        "exploitation_type": "state_imposed",
        "sector": "agriculture",
        "summary": "Xinjiang produces 85% of China's cotton (20% of world supply). 'Surplus labour' transfers and 'mutual pairing' programmes mobilize Uyghur and other Turkic minority workers for cotton harvesting. 570,000+ workers transferred to cotton fields during peak season under government quotas. Workers in groups under surveillance, political study sessions mandatory, inability to refuse. Better Cotton Initiative withdrew Xinjiang certification (2020). US, UK, EU import restrictions on Xinjiang cotton.",
        "source": "Adrian Zenz / ASPI / Center for Global Policy / Better Cotton Initiative",
    },
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "Chinese Workers in Illegal Gold Mines — Domestic Trafficking",
        "exploitation_type": "restriction_of_movement",
        "sector": "mining",
        "summary": "Domestic trafficking in China includes: workers from rural Yunnan, Guizhou, and Sichuan provinces recruited by labour brokers for illegal gold mines in remote mountainous areas. Workers: confined to mine sites, paid in scrip (not cash), accommodation deducted, no safety equipment, injuries untreated. China Labour Bulletin documented cases of workers held for months in illegal mines. Local police sometimes complicit. Distinct from international trafficking but meeting ILO forced labour indicators.",
        "source": "China Labour Bulletin / Caixin investigative reports / China Ministry of Emergency Management",
    },
    {
        "type": "statistic",
        "jurisdiction": "CN",
        "title": "China Left-Behind Children — Hukou System Impact",
        "metric": "Children of migrant workers left in rural areas",
        "value": "66 million (2020 census estimate)",
        "year": 2020,
        "details": "An estimated 66 million children in China are 'left behind' in rural areas while parents work in cities. Hukou system prevents children from attending urban schools. Children raised by grandparents or relatives, facing: educational disadvantage, psychological harm, vulnerability to exploitation. Number declining from peak of 90 million (2010) as some cities relax hukou rules, but remains a massive social issue directly linked to internal migration exploitation system.",
        "source": "China National Bureau of Statistics / UNICEF China / All-China Women's Federation",
    },
    {
        "type": "case_study",
        "jurisdiction": "JP",
        "title": "TITP Intern Suicides — Mental Health Crisis",
        "exploitation_type": "isolation",
        "sector": "multiple",
        "summary": "TITP intern suicides represent a silent crisis: Immigration Services Agency data shows suicide accounts for 20% of intern deaths. Contributing factors: extreme isolation (single foreign worker in rural area), inability to change employers, debt pressure from home country, language barrier preventing help-seeking, cultural stigma around mental health. No mandatory mental health screening or support. JFBA recommended: mandatory mental health check-ups, multilingual counselling hotlines, peer support networks. Government response limited to a pamphlet.",
        "source": "Immigration Services Agency of Japan / JFBA / Solidarity Network with Migrants Japan",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "Korea Housing Standards for Migrant Workers (2024)",
        "summary": "Following the Hwaseong fire and Pocheon deaths, Korea's Ministry of Employment and Labor issued mandatory housing standards for EPS workers (2024): minimum 4.95 sqm per person, fire detection and suppression systems, heating/cooling requirements, separation from workplace/factory, fire escape routes, multilingual emergency instructions. Applies to employer-provided accommodation. Penalties: KRW 30 million fine and potential EPS employer permit revocation. Compliance deadline: December 2025. Advocacy groups welcome standards but note enforcement capacity concerns.",
        "source": "Korea Ministry of Employment and Labor / NHRCK / Korea Times",
    },
]
