"""Placement fee caps and zero-cost policies by migration corridor."""

FEE_CAP_FACTS: list[dict] = [
    # ── Existing corridors ────────────────────────────────────────────
    {
        "type": "fee_cap",
        "jurisdiction": "HK",
        "corridor": "PH-HK",
        "title": "Hong Kong Placement Fee Cap for Foreign Domestic Helpers",
        "amount": "HKD 4,630",
        "details": "Maximum 10% of first month's salary for each year of contract (standard 2-year contract). Employment Agencies Ordinance (Cap. 57). Agencies exceeding cap face license revocation.",
        "law": "Employment Ordinance Cap. 57",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "PH",
        "corridor": "PH-SA",
        "title": "Philippines Zero Placement Fee Policy for Saudi Arabia",
        "amount": "PHP 0",
        "details": "DMW/POEA mandates zero placement fee for domestic workers deployed to Saudi Arabia. All costs to be borne by employer. Violations: agency license suspension/cancellation.",
        "law": "DMW Memorandum Circular",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "SG",
        "corridor": "PH-SG",
        "title": "Singapore MOM Prohibition on Worker-Paid Fees",
        "amount": "SGD 0",
        "details": "MOM prohibits employment agencies from charging foreign domestic workers placement fees. Maximum 1 month salary for other work permit holders. EA licence conditions.",
        "law": "Employment Agencies Act",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "NP",
        "corridor": "NP-QA",
        "title": "Nepal Fee Cap for Qatar-Bound Workers",
        "amount": "NPR 10,000",
        "details": "Foreign Employment Act 2007 caps service charge at NPR 10,000. Qatar bilateral agreement aims for zero-cost recruitment (employer-pays model). Gap between law and practice persists.",
        "law": "Foreign Employment Act 2007",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "BD",
        "corridor": "BD-MY",
        "title": "Bangladesh-Malaysia Employer-Pays Recruitment",
        "amount": "BDT 0",
        "details": "G2G bilateral agreement mandates employer-pays model. In practice, workers still report paying BDT 200,000-400,000 to sub-agents. Government crackdowns ongoing.",
        "law": "BD-MY Bilateral Agreement",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "ID",
        "corridor": "ID-HK",
        "title": "Indonesia BNP2MI Zero-Cost Policy for Hong Kong",
        "amount": "IDR 0",
        "details": "BNP2MI (formerly BNP2TKI) mandates zero-cost placement for Indonesian domestic workers to Hong Kong. In practice, illegal deductions and training-fee overcharges persist.",
        "law": "BNP2MI Regulation",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "ET",
        "corridor": "ET-SA",
        "title": "Ethiopia MoLSA Zero Placement Fee Directive",
        "amount": "ETB 0",
        "details": "Ministry of Labour and Social Affairs directive prohibits placement fees for Ethiopian domestic workers deployed abroad. Employer pays all costs including visa, travel, medical exam.",
        "law": "MoLSA Directive",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "MM",
        "corridor": "MM-TH",
        "title": "Myanmar-Thailand MOU Zero-Fee Recruitment",
        "amount": "THB 0",
        "details": "Bilateral MOU sets zero recruitment fee target. In practice, brokers charge MMK 500,000-1,500,000. Most recruitment for fishing, agriculture, and manufacturing sectors.",
        "law": "MM-TH Bilateral MOU",
    },

    # ── New corridors ─────────────────────────────────────────────────
    {
        "type": "fee_cap",
        "jurisdiction": "AE",
        "corridor": "PH-AE",
        "title": "Philippines Zero Placement Fee Policy for UAE",
        "amount": "PHP 0",
        "details": "DMW mandates zero placement fee for domestic workers to UAE. Employer-pays principle. POLO Abu Dhabi/Dubai verifies contract terms. Violations: agency suspension.",
        "law": "DMW Circular",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "KW",
        "corridor": "PH-KW",
        "title": "Philippines Zero Placement Fee Policy for Kuwait",
        "amount": "PHP 0",
        "details": "Zero-fee policy for domestic workers to Kuwait. Standard employment contract required. POLO Kuwait verifies terms. Deployment temporarily banned multiple times due to abuse cases.",
        "law": "DMW Administrative Order",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "QA",
        "corridor": "PH-QA",
        "title": "Philippines Fee Cap for Qatar-Bound Workers",
        "amount": "PHP 0",
        "details": "Zero placement fee for domestic workers. For skilled workers: maximum one month salary. Qatar's employer-pays model reinforced by 2020 labour reforms.",
        "law": "DMW/POEA Rules",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "KR",
        "corridor": "PH-KR",
        "title": "Philippines-Korea EPS Fee Structure",
        "amount": "USD 927",
        "details": "Government-managed recruitment: EPS-TOPIK test (PHP 3,400), Skills test, PDOS, medical exam. Total ~USD 927. No private agency fees. Managed by HRD Korea + POEA/DMW.",
        "law": "EPS Act / DMW Guidelines",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "JP",
        "corridor": "PH-JP",
        "title": "Philippines-Japan TITP/SSW Fee Cap",
        "amount": "PHP 50,000-100,000",
        "details": "Maximum service charge for TITP: one month salary equivalent. SSW (Specified Skilled Worker): similar cap. Sending organizations registered with POEA. Japanese supervising organizations share costs.",
        "law": "TITP Act / DMW Guidelines",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "SA",
        "corridor": "ID-SA",
        "title": "Indonesia Zero-Cost Policy for Saudi Arabia",
        "amount": "IDR 0",
        "details": "BNP2MI zero-cost placement. In practice, workers report paying IDR 5-15 million to sub-agents for 'training,' medical exams, and document processing. Government crackdowns underway.",
        "law": "BNP2MI Ministerial Regulation",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "SG",
        "corridor": "ID-SG",
        "title": "Indonesia-Singapore Zero Placement Fee Target",
        "amount": "IDR 0 / SGD 0",
        "details": "Both Indonesia (BNP2MI) and Singapore (MOM) mandate zero worker-paid fees. Illegal deductions via training centers in Batam/Java remain common. MOM audits agencies.",
        "law": "BNP2MI Regulation / MOM EA Licence",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "MY",
        "corridor": "ID-MY",
        "title": "Indonesia-Malaysia Fee Cap",
        "amount": "IDR 0",
        "details": "Zero-cost migration target under bilateral MOU. Workers in palm oil, manufacturing, and domestic sectors. Actual costs: IDR 7-20 million via sub-agents in Java and Kalimantan.",
        "law": "ID-MY Labour MOU",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "KR",
        "corridor": "ID-KR",
        "title": "Indonesia-Korea EPS Government-Managed Fees",
        "amount": "USD 1,050",
        "details": "Total government-set cost: Korean Language Test, medical, skills test, PDOS. ~USD 1,050 total. No private agency involvement. BNP2MI manages sending side.",
        "law": "EPS Act",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "SA",
        "corridor": "NP-SA",
        "title": "Nepal Fee Cap for Saudi Arabia-Bound Workers",
        "amount": "NPR 10,000",
        "details": "Foreign Employment Act cap applies. Employer-pays principle for domestic workers. In practice: workers pay NPR 100,000-300,000 via sub-agents in Kathmandu and border towns.",
        "law": "Foreign Employment Act 2007",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "MY",
        "corridor": "NP-MY",
        "title": "Nepal Fee Cap for Malaysia-Bound Workers",
        "amount": "NPR 10,000",
        "details": "Official cap under Foreign Employment Act. G2G system aims to eliminate private fees. Workers report paying NPR 150,000-500,000. Manufacturing and plantation sectors.",
        "law": "Foreign Employment Act 2007 / NP-MY MOU",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "KR",
        "corridor": "NP-KR",
        "title": "Nepal-Korea EPS Fee Structure",
        "amount": "USD 850",
        "details": "Government-managed: EPS-TOPIK Korean language test, medical, skills assessment. Total ~USD 850. One of the most transparent corridors globally. No private agency fees.",
        "law": "EPS Act / Foreign Employment Act",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "SA",
        "corridor": "BD-SA",
        "title": "Bangladesh Fee Guidelines for Saudi Arabia",
        "amount": "BDT 84,000",
        "details": "BMET-set maximum: BDT 84,000 (~USD 770). In practice: workers pay BDT 300,000-600,000 via dalals (sub-agents). Construction and domestic work sectors.",
        "law": "BMET Circular",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "QA",
        "corridor": "BD-QA",
        "title": "Bangladesh-Qatar Zero-Cost Recruitment Target",
        "amount": "BDT 0",
        "details": "Bilateral agreement targets employer-pays model. Qatar requires employers to pay recruitment costs. In practice: Bangladeshi workers pay BDT 200,000-400,000. Construction sector dominant.",
        "law": "BD-QA Bilateral Agreement",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "SG",
        "corridor": "BD-SG",
        "title": "Bangladesh-Singapore Fee Cap",
        "amount": "BDT 84,000 / SGD 0",
        "details": "Bangladesh caps at BDT 84,000. Singapore prohibits worker-paid fees for domestic workers. Other sectors: max 1 month salary. Enforcement gaps on Bangladesh sending side.",
        "law": "BMET / MOM EA Licence",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "SA",
        "corridor": "LK-SA",
        "title": "Sri Lanka Fee Cap for Saudi Arabia-Bound Workers",
        "amount": "LKR 0",
        "details": "Sri Lanka Bureau of Foreign Employment (SLBFE) mandates zero-cost for domestic workers. Employer-pays principle. Workers report paying LKR 50,000-200,000 to sub-agents.",
        "law": "SLBFE Circular",
    },
    {
        "type": "fee_cap",
        "jurisdiction": "TH",
        "corridor": "KH-TH",
        "title": "Cambodia-Thailand MOU Recruitment Costs",
        "amount": "USD 0",
        "details": "Bilateral MOU targets zero-cost recruitment. In practice: Cambodian workers pay USD 300-700 to brokers for border crossing, work permit, and transport. Fishing and agriculture sectors.",
        "law": "KH-TH Labour MOU",
    },
]
