"""Gulf state (GCC) labor exploitation cases, enforcement actions, and reform tracking."""

GULF_STATE_CASE_FACTS: list[dict] = [
    # ── Qatar — FIFA World Cup & Construction ──────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "FIFA World Cup 2022 — Migrant Worker Death Toll Investigation",
        "summary": "The Guardian documented 6,500+ migrant worker deaths in Qatar between 2010 and 2020 using embassy data from Nepal, India, Bangladesh, Sri Lanka, and Pakistan. Causes included heat-related cardiac arrest, falls from height, and vehicle accidents. Qatar's Supreme Committee reported only 37 non-work-related deaths on stadium sites. ILO and Amnesty International called for independent investigation and compensation fund. FIFA rejected responsibility despite profiting USD 7.5 billion from the tournament.",
        "source": "The Guardian / Amnesty International / ITUC",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Qatar Workers' Support and Insurance Fund — Unpaid Wages Recovery",
        "summary": "Qatar established the Workers' Support and Insurance Fund (WSIF) in 2018 to pay workers owed wages by employers. By 2023, the fund disbursed QAR 1.8 billion (USD 500 million) to over 36,000 workers. Fund covers wages, end-of-service benefits, and return airfare when employers default. ILO praised the mechanism but noted delays and gaps in coverage for domestic workers.",
        "source": "ILO Qatar Office / Qatar Ministry of Labour",
    },
    {
        "type": "statistic",
        "jurisdiction": "QA",
        "title": "Qatar Labour Dispute Resolution Committees — Case Volume (2021-2023)",
        "summary": "Labour Dispute Resolution Committees processed over 35,000 cases between 2021 and 2023, with a median resolution time of 3 weeks. Recovered QAR 1.8 billion in unpaid wages. Committees are accessible to all workers including domestic workers. However, workers must still be in-country to file, creating barriers for those already repatriated. ILO recommended expanding post-departure complaint mechanisms.",
        "source": "ILO Qatar Office / Qatar Ministry of Labour Annual Report 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Qatar Construction Workers — Heat-Related Deaths Investigation",
        "summary": "Lancet Planetary Health study (2019) found 571 of 1,300 Nepali migrant deaths in Qatar (2009-2017) attributable to heat stress, classified as cardiovascular disease on death certificates. Workers performing outdoor construction in temperatures exceeding 45 degrees Celsius during summer months. Qatar's heat work ban (11:30am-3pm, June 15-September 15) extended in 2021 but enforcement gaps persist. ILO recommended elimination of heat stress through mandatory WBGT monitoring.",
        "source": "The Lancet Planetary Health / Amnesty International / ILO",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "QA",
        "title": "Qatar Kafala Reform — Law No. 18 of 2020 (Minimum Wage)",
        "summary": "Qatar enacted the first non-discriminatory minimum wage in the GCC: QAR 1,000/month basic salary plus QAR 300 food allowance and QAR 500 housing allowance (if employer does not provide). Effective March 2021. Applied to all nationalities and sectors including domestic workers. ILO noted this was a major reform but monitoring compliance remains challenging, especially for domestic workers in private households.",
        "source": "Qatar Official Gazette / ILO",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "QA",
        "title": "Qatar Abolition of Exit Permit — Law No. 13 of 2018",
        "summary": "Qatar abolished the exit permit requirement (NOC) for most workers in 2018, with Ministerial Decision No. 95 of 2019 extending it to all workers from January 2020. Workers can leave the country without employer permission. In practice, some employers still delay or obstruct departure. ILO reported improved freedom of movement but noted 'absconding' charges still used as retaliation against workers who leave without employer consent.",
        "source": "Qatar Ministry of Labour / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "QA",
        "title": "Qatar Employer Transfer Statistics Post-Reform (2020-2023)",
        "summary": "Following the abolition of the NOC requirement for job changes (Ministerial Decision No. 51 of 2020), over 350,000 workers changed employers between September 2020 and December 2023. The ILO noted this was a fundamental shift from the kafala system but reported ongoing barriers: some employers filed absconding charges against departing workers, and processing delays discouraged transfers.",
        "source": "ILO Qatar Office Progress Report 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Qatar World Cup Stadium Workers — Wage Theft Pattern",
        "summary": "Amnesty International documented cases of workers on World Cup stadium projects who went months without pay. Al Bandary Engineering and Contracting and Qatar Meta Coats among companies named. Workers reported wage delays of 3-7 months. Supreme Committee's Worker Welfare Standards were better enforced on stadium sites than on transport and hotel infrastructure. Post-tournament layoffs left thousands without end-of-service benefits.",
        "source": "Amnesty International / BWI / Supreme Committee for Delivery & Legacy",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Qatar Passport Confiscation — Persistent Practice Despite Ban",
        "summary": "Qatar criminalized passport confiscation in 2011 (Law No. 15 of 2011) but practice persists. ILO surveys (2019-2020) found approximately 60 percent of migrant workers had passports held by employer. Workers reported passports kept in company offices with access only during holidays. Penalties (QAR 25,000 fine) rarely enforced. ILO recommended increased inspections and public awareness campaigns.",
        "source": "ILO / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Qatar Domestic Workers — Exclusion from Labour Protections",
        "summary": "Qatar's Domestic Workers Law (No. 15 of 2017) set a maximum 10-hour workday, weekly day off, and 3 weeks annual leave. But enforcement is minimal due to the private household setting. ILO reported domestic workers unable to access dispute committees without employer cooperation. Live-in requirement creates dependency. Absconding charges deter complaints. Philippine and Indonesian embassies operate shelters for escaped domestic workers.",
        "source": "ILO / HRW / Amnesty International",
    },
    # ── Saudi Arabia ───────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "NEOM Construction — Worker Death Reports and Wage Withholding",
        "summary": "Saudi Arabia's NEOM mega-project (USD 500 billion) employed over 100,000 construction workers by 2023. The Guardian reported 21 Nepali worker deaths between 2022 and 2023, with death certificates listing 'natural causes' or 'cardiac arrest' despite heat exposure. Workers reported 10-14 hour shifts, 3-6 month wage delays, crowded camps, and movement restrictions. Saudi authorities denied systemic issues. ALQST for Human Rights called for independent investigation.",
        "source": "The Guardian / ALQST / BWI",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SA",
        "title": "Saudi Decision No. 310 — Domestic Worker Regulation",
        "summary": "Ministerial Decision No. 310 (2009, updated 2013) established regulations for domestic workers including: 9-hour daily rest, salary payment by end of each Hijri month, prohibition of passport confiscation, medical care. However, domestic workers remain excluded from the Labour Law (Royal Decree M/51). Enforcement relies on complaint-based system. Saudi HRC received over 3,000 domestic worker complaints annually (2019-2022).",
        "source": "Saudi Ministry of Human Resources / Saudi HRC",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Nitaqat System — Impact on Migrant Worker Vulnerability",
        "summary": "Saudi Saudization program (Nitaqat) categorizes companies by Saudi national employment ratios. Companies failing quotas face penalties including visa block. This creates incentives for contract substitution (workers brought as domestic but deployed in companies) and 'free visa' arrangements where workers pay sponsors SAR 12,000-24,000/year. Workers on free visas are undocumented, vulnerable to arrest under Article 39 violations, and unable to access labour courts.",
        "source": "ILO / Migrant Forum in Asia / US TIP Report",
    },
    {
        "type": "statistic",
        "jurisdiction": "SA",
        "title": "Saudi Wage Protection System — Coverage and Violations",
        "summary": "Saudi WPS (launched 2013) requires electronic salary payment for all private sector workers. By 2023, covered 8 million workers. Ministry data shows 15,000+ violations detected annually. However, WPS does not cover domestic workers, agricultural workers, or companies with fewer than 5 employees. Workers report employers requiring them to sign receipts for amounts higher than actually paid. Penalties: SAR 10,000 per worker for late payment.",
        "source": "Saudi Ministry of Human Resources / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Heat Work Ban Violations — Outdoor Labour Deaths",
        "summary": "Saudi heat work ban prohibits outdoor labour from 12pm-3pm during June-September. Despite this, construction and agricultural workers routinely work during banned hours. Al Watan newspaper (2023) reported 14 heat-related deaths in Makkah and Madinah construction projects in a single summer. Penalties for violation (SAR 3,000 per worker per incident) rarely enforced due to insufficient inspectors. ILO recommended WBGT-based thresholds rather than fixed hours.",
        "source": "Al Watan / Saudi Ministry of Human Resources / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Absconding Charges — Tool of Worker Control",
        "summary": "Saudi employers can file 'absconding' (huroob) reports against workers who leave employment. Absconding status renders the worker undocumented, subject to arrest, detention, and deportation. In 2022, Saudi Arabia reported 150,000 absconding cases. HRW documented employers filing huroob charges against workers who filed salary complaints as retaliation. Ministry reformed the system in 2021 to allow workers to transfer sponsors within 60 days of leaving, but employers can still contest the transfer.",
        "source": "HRW / Saudi Ministry of Human Resources / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Domestic Worker Deaths — Philippine Embassy Records",
        "summary": "Philippine Overseas Labor Office (POLO) in Riyadh and Jeddah documented an average of 30-50 distress calls per day from Filipino domestic workers (2019-2022). Common complaints: salary non-payment (45 percent), physical abuse (25 percent), excessive work (20 percent), sexual abuse (10 percent). POLO shelters housed 300-500 workers at any given time awaiting repatriation. Deaths of Filipino workers in Saudi Arabia averaged 700-900 per year (all causes) according to DFA records.",
        "source": "DMW / POLO Riyadh / Philippine DFA",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SA",
        "title": "Saudi Labour Reform Initiative — Employer Transfer Without Consent (2021)",
        "summary": "Labour Reform Initiative (March 2021) allows private sector workers to: change employers without NOC after contract expiry, transfer during valid contract with notice, obtain exit/re-entry and final exit visas without employer approval. Covers workers under Labour Law but excludes domestic workers, government employees, and agricultural workers. Ministry reported 200,000+ transfers in first year. However, employers can contest transfers, creating delays.",
        "source": "Saudi Ministry of Human Resources / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Construction Safety — Fall-From-Height Fatalities",
        "summary": "Saudi Ministry of Human Resources data (2022) recorded 358 workplace fatalities, with construction accounting for 62 percent. Fall-from-height was the leading cause. GOSI (General Organization for Social Insurance) reported 69,000 work-related injuries in 2022. ILO noted that many smaller companies operate without safety equipment or training. Workers from South Asia and Africa disproportionately affected due to deployment in high-risk roles.",
        "source": "Saudi Ministry of Human Resources / GOSI / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Contract Substitution — Recruitment Deception Pattern",
        "summary": "Systematic pattern documented by HRW and Migrant Forum in Asia: workers sign contracts in origin country for specific salary and position, arrive in Saudi Arabia to find different employer, lower salary, and different job. Agents in Philippines, Bangladesh, and India collude with Saudi sponsors. Workers who refuse substituted contract face 'absconding' charges if they leave the employer. Saudi recruitment regulation (2014 reform) requires contract verification but enforcement is inconsistent.",
        "source": "HRW / Migrant Forum in Asia / BNP2MI",
    },
    {
        "type": "statistic",
        "jurisdiction": "SA",
        "title": "Saudi Musaned Platform — Domestic Worker Recruitment Digitization",
        "summary": "Saudi Arabia launched Musaned platform (2014, expanded 2019) for domestic worker recruitment: online contract, salary escrow, complaint mechanism. By 2023, over 2 million contracts processed through the platform. However, POLO reported that many domestic workers remain recruited through informal channels (estimated 30-40 percent). Musaned complaints averaged 15,000/month but resolution rates were not publicly disclosed.",
        "source": "Saudi Ministry of Human Resources / POLO Riyadh",
    },
    # ── United Arab Emirates ───────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "Saadiyat Island — Louvre and Guggenheim Worker Exploitation",
        "summary": "Construction of Louvre Abu Dhabi, Guggenheim Abu Dhabi, and NYU Abu Dhabi on Saadiyat Island employed tens of thousands of South Asian workers. HRW (2009, 2012, 2015) documented: recruitment fees USD 2,000-4,000, passport confiscation, cramped labour camps (8-12 per room), wage withholding, 12-hour shifts in extreme heat. TDIC (Tourism Development and Investment Company) implemented Worker Welfare Policy with independent monitoring. Conditions improved on monitored sites but violations persisted on subcontracted work.",
        "source": "HRW / Amnesty International / NYU investigators / TDIC",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "AE",
        "title": "UAE Federal Decree-Law No. 33 of 2021 — Labour Relations Law",
        "summary": "Replaced Federal Law No. 8 of 1980. Key changes: prohibition of forced labour (Article 9), non-discrimination in wages (Article 4), prohibition of sexual harassment (Article 14), flexible work arrangements including part-time, temporary, and freelance contracts, 30-day grace period after termination to find new employment, and whistleblower protections. Effective February 2022. Domestic workers remain covered by separate Federal Law No. 10 of 2017.",
        "source": "UAE Official Gazette / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "Dubai Labour Camps — Living Conditions Investigation",
        "summary": "Over 1.5 million construction workers in Dubai housed in labour camps in industrial zones (Sonapur, Al Quoz, Jebel Ali). HRW and Vice News documented: 8-12 workers per room, remote locations (1-2 hour bus commute), employer-controlled housing, inadequate ventilation, no recreational facilities, curfew enforcement, and restricted media access. Some camps improved after Expo 2020 scrutiny but systematic conditions persist in older camps. Workers pay AED 100-300/month for camp accommodation deducted from wages.",
        "source": "HRW / Vice News / The Guardian",
    },
    {
        "type": "statistic",
        "jurisdiction": "AE",
        "title": "UAE MOHRE Wage Protection System — Compliance Statistics",
        "summary": "UAE Wage Protection System (WPS) covers over 5 million private sector workers. MOHRE data (2023) shows 95 percent compliance rate for timely salary payment among registered companies. However, WPS does not cover domestic workers (estimated 750,000 in UAE). Companies with fewer than 50 employees have lower compliance rates. MOHRE imposed AED 5,000 per worker fines for WPS violations and suspended labour permits for repeat offenders.",
        "source": "UAE Ministry of Human Resources and Emiratisation (MOHRE)",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE Domestic Worker Exploitation — Embassy Shelter Data",
        "summary": "Philippine Embassy Abu Dhabi and Consulate Dubai operated shelters housing 200-400 distressed Filipino domestic workers at any given time (2019-2023). Indian Embassy similarly assisted 1,500-2,000 domestic workers annually. Common complaints: non-payment of wages (50 percent), physical abuse (20 percent), contract substitution (15 percent), excessive working hours (15 percent). UAE Federal Law No. 10 of 2017 (Domestic Workers Law) provides 12 hours rest, weekly day off, and 30 days annual leave, but enforcement in private households remains weak.",
        "source": "Philippine Embassy Abu Dhabi / Indian Embassy Abu Dhabi / MOHRE",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "Dubai Construction Worker Deaths — Expo 2020 Infrastructure",
        "summary": "Construction for Dubai Expo 2020 (held 2021-2022) employed over 40,000 workers. Three worker deaths confirmed on Expo site. Amnesty International reported broader infrastructure deaths exceeded 100 annually across all Expo-related projects (roads, metro extensions, hotels). Expo authorities implemented safety standards above national requirements but subcontractors on ancillary projects operated with less oversight.",
        "source": "Amnesty International / Expo 2020 Sustainability Report / BWI",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "AE",
        "title": "UAE Midday Work Ban — Implementation and Violations",
        "summary": "UAE prohibits outdoor work from 12:30pm-3pm during June 15-September 15. Violations carry fines of AED 5,000 per worker per incident, plus potential facility closure. MOHRE reported 9,000+ inspections during summer 2023, with 542 violations detected (6 percent violation rate). However, workers report that employers sometimes require clock-out during the ban period while continuing work. Construction unions (not permitted in UAE) have no mechanism to report violations anonymously.",
        "source": "MOHRE / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE Free Zone Worker Exploitation — JAFZA and SAIF Zone",
        "summary": "Workers in UAE free zones (JAFZA, SAIF Zone, RAK FTZ) reported weaker protections than mainland workers. Free zone authorities have their own labour regulations and inspection regimes. Documented issues: lower wages than mainland equivalents, longer hours, employer-tied housing with deductions, and limited access to MOHRE complaint mechanisms. Some free zone workers reported being unable to change employers even after the 2022 labour law reform.",
        "source": "Migrant-Rights.org / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE Recruitment Fee Prohibition — Enforcement Gap",
        "summary": "UAE Ministerial Decree No. 1283 of 2020 prohibits employers and recruitment agencies from charging workers any fees. However, recruitment fees continue to be charged in origin countries (India, Pakistan, Bangladesh, Philippines) by local sub-agents. Average fees paid by workers: USD 1,500-4,000. UAE MOHRE has limited jurisdiction over origin-country agents. ILO recommended bilateral enforcement agreements with origin countries.",
        "source": "ILO / Verité / Migrant-Rights.org",
    },
    # ── Kuwait ─────────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "Kuwait Domestic Worker Deaths — Filipino and Ethiopian Cases",
        "summary": "Philippines temporarily banned deployment of domestic workers to Kuwait in February 2018 after Joanna Demafelis was found dead in a freezer in a Kuwait apartment. Her employers (Lebanese-Syrian couple) had fled to Syria. Kuwait extradited the wife who was sentenced to death (later commuted). Pattern: multiple Filipino domestic worker deaths annually (15-25 per year, DMW records). Ethiopia and Philippines have intermittently banned domestic worker deployment to Kuwait.",
        "source": "DMW / Philippine Embassy Kuwait / CNN Philippines / Kuwait Times",
    },
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "Kuwait Domestic Worker Shelter System — Capacity and Conditions",
        "summary": "Kuwait operates government shelters for abused domestic workers through the Domestic Labour Office. Philippine Embassy shelter in Kuwait housed 500-700 workers at any given time (2019-2023). Indian Embassy shelter capacity: 100-150. Workers wait 2-6 months for case resolution and repatriation. Shelter conditions criticized by HRW: overcrowding, inadequate food, restricted movement. Sheltered workers cannot work or earn income while awaiting resolution.",
        "source": "HRW / Philippine Embassy Kuwait / Indian Embassy Kuwait",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KW",
        "title": "Kuwait Domestic Workers Law No. 68 of 2015",
        "summary": "Kuwait enacted the first dedicated domestic worker law in the GCC (Law No. 68 of 2015): 12-hour daily rest, weekly day off, 30 days annual leave, end-of-service indemnity, prohibition of passport confiscation. Established Domestic Labour Office for disputes. However, enforcement remains weak: workers must leave employer to file complaint, creating homelessness risk. Kuwait HRC reported 5,000+ domestic worker complaints annually but prosecution rates below 5 percent.",
        "source": "Kuwait Official Gazette / ILO / HRW",
    },
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "Kuwait Kafala Reform — Partial Employer Transfer System",
        "summary": "Kuwait introduced limited employer transfer rights for private sector workers (2016 amendment to Labour Law No. 6 of 2010): workers can transfer after 3 years with current employer or 1 year if employer violates contract. Domestic workers can transfer under Law No. 68. However, workers report difficulty obtaining release letters. PAM (Public Authority for Manpower) processed 75,000 transfer applications in 2022 with 60 percent approval rate. Denied workers face absconding charges if they leave.",
        "source": "PAM Kuwait / ILO / Migrant-Rights.org",
    },
    {
        "type": "statistic",
        "jurisdiction": "KW",
        "title": "Kuwait Absconding Cases — Deportation Statistics",
        "summary": "Kuwait Ministry of Interior reported 30,000-40,000 absconding cases filed annually (2019-2022). Workers reported as absconding face arrest, detention, and deportation. MOI amnesty periods (2018, 2020, 2022) allowed 70,000+ irregular workers to depart without penalty. HRW noted that many absconding reports are retaliatory: filed after workers complain about salary non-payment or abuse.",
        "source": "Kuwait Ministry of Interior / HRW",
    },
    # ── Bahrain ────────────────────────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "BH",
        "title": "Bahrain Flexi-Permit System — Self-Sponsorship for Migrants",
        "summary": "Bahrain introduced the Flexi-Permit (2017) allowing irregular workers to regularize status and work without a sponsor for 2 years (renewable). Workers pay BHD 79/month. By 2023, over 80,000 permits issued. ILO praised the system as an alternative to kafala but noted: workers bear full costs (no employer contribution to health insurance or housing), limited social protections, and risk of exploitation by informal employers who avoid labour law obligations.",
        "source": "LMRA Bahrain / ILO",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "BH",
        "title": "Bahrain Employer Mobility — First GCC Country to Allow Free Transfer",
        "summary": "Bahrain abolished the NOC requirement for employer transfer in 2009 (Resolution No. 79 of 2009), becoming the first GCC country to do so. Workers can change employers after 1 year or immediately if employer violates contract. LMRA processes transfers. By 2023, approximately 30,000 transfers annually. However, domestic workers excluded until 2022 amendment. Bahrain's reforms are considered the most progressive in the GCC by the ILO.",
        "source": "LMRA Bahrain / ILO / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "BH",
        "title": "Bahrain Construction Worker Exploitation — Company Collapse Cases",
        "summary": "Pattern documented by LMRA and Indian Embassy: construction companies in Bahrain collapse or go bankrupt owing months of wages to workers. Workers stranded without valid visa, housing, or income. LMRA's anti-trafficking unit reported handling 200-300 such cases annually. India's Protector of Emigrants issued advisories against 15+ Bahrain-based companies. Workers in company collapse situations face difficulty accessing the Flexi-Permit system due to outstanding employer obligations.",
        "source": "LMRA Bahrain / Indian Embassy Manama / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "BH",
        "title": "Bahrain National Referral Mechanism — Trafficking Victim Identification",
        "summary": "Bahrain's National Referral Mechanism (NRM) for trafficking victims identified 105 potential victims in 2022 (LMRA data). Of these, 72 were confirmed as trafficking victims and provided shelter, legal assistance, and temporary residency. Bahrain's shelter capacity: 60 beds. Types of exploitation: forced labour (65 percent), domestic servitude (25 percent), sexual exploitation (10 percent). US TIP Report has maintained Bahrain at Tier 2 since 2019.",
        "source": "LMRA Bahrain / US TIP Report 2023",
    },
    # ── Oman ───────────────────────────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "OM",
        "title": "Oman Labour Law Reform — Royal Decree 53/2023",
        "summary": "Oman enacted a new Labour Law (Royal Decree 53/2023) replacing the 2003 law. Key changes: prohibition of forced labour, prohibition of passport confiscation, right to retain travel documents, enhanced termination protections, and establishment of collective bargaining framework. Domestic workers remain under separate regulation. ILO noted the law is progressive but implementation capacity needs strengthening, with only 200 labour inspectors for 1.8 million private sector workers.",
        "source": "Oman Official Gazette / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "OM",
        "title": "Oman Employer Transfer — Limited Mobility for Workers",
        "summary": "Oman introduced employer transfer rights in 2021 (Ministerial Decision 235/2021): workers can change employers after 2 years or upon contract expiry without NOC. However, workers must obtain Ministry approval and the transfer process takes 2-4 weeks during which the worker cannot work. Employers can contest transfers. Ministry of Labour processed 15,000 transfer applications in 2022 with 70 percent approval. Workers denied transfer face deportation if they leave employment.",
        "source": "Oman Ministry of Labour / ILO / Migrant-Rights.org",
    },
    {
        "type": "case_study",
        "jurisdiction": "OM",
        "title": "Oman Domestic Worker Exploitation — Tanzanian and Ethiopian Workers",
        "summary": "Oman employs approximately 170,000 domestic workers, primarily from Tanzania, Ethiopia, India, and the Philippines. ILO and HRW documented: 16-18 hour workdays, confinement to households, salary withholding for 3-6 months, physical abuse. Oman's domestic worker regulation (Ministerial Decision 189/2004) provides minimal protections. No mandatory day off or maximum working hours until the 2023 law reform. Ethiopian Embassy in Muscat reported receiving 500+ distress calls annually.",
        "source": "ILO / HRW / Ethiopian Embassy Muscat",
    },
    {
        "type": "statistic",
        "jurisdiction": "OM",
        "title": "Oman WPS Implementation — Coverage Gaps",
        "summary": "Oman launched its Wage Protection System in 2014, with electronic salary payment required for companies with 50+ employees. Extended to companies with 10+ employees in 2019. Coverage: approximately 60 percent of private sector workers. Domestic workers, agricultural workers, and workers in companies under 10 employees excluded. Ministry of Labour data (2022) detected 3,000+ violations. Companies with 3+ months of wage delays face licence suspension.",
        "source": "Oman Ministry of Labour / ILO",
    },
    # ── Jordan ─────────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "JO",
        "title": "Jordan QIZ Garment Factories — Foreign Worker Exploitation",
        "summary": "Jordan's Qualifying Industrial Zones employ 75,000+ garment workers, predominantly women from Sri Lanka, Bangladesh, India, Myanmar, and Madagascar. Documented exploitation: forced overtime (72+ hours/week), wage theft, sexual harassment, passport confiscation, locked dormitories at night. NLC (National Labor Committee) exposed Classic Fashion factory conditions (2011). Better Work Jordan program improved conditions in participating factories but coverage is not universal. ILO Better Work covers 89 factories employing 65,000 workers.",
        "source": "Better Work Jordan / NLC / BWI / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "JO",
        "title": "Jordan Domestic Workers — Exclusion from Labour Law",
        "summary": "Jordan employs approximately 70,000 domestic workers, primarily from the Philippines, Sri Lanka, and Ethiopia. Domestic workers excluded from Labour Law until 2008 amendment (Regulation No. 90 of 2009) which set minimum standards: 10-hour workday, weekly day off, minimum wage (JOD 150/month). However, enforcement in private households is nearly impossible. Anti-Trafficking Unit identified 30-50 domestic worker trafficking cases annually. Jordan's shelter (Dar Karama) houses 40-60 women at a time.",
        "source": "ILO / Tamkeen Fields for Aid / Jordanian Anti-Trafficking Unit",
    },
    {
        "type": "case_study",
        "jurisdiction": "JO",
        "title": "Jordan Syrian Refugee Labour Exploitation",
        "summary": "An estimated 200,000 Syrian refugees work in Jordan's informal sector (agriculture, construction, services), most without valid work permits. Documented exploitation: wages 50-60 percent below Jordanian minimum wage, no social insurance, 12-14 hour days, child labour (estimated 30,000 Syrian children working). Jordan issued 200,000 work permits to Syrians under the Jordan Compact (2016) but uptake was limited due to employer reluctance and bureaucratic barriers. ILO estimated only 40,000 permits actively used.",
        "source": "ILO / UNHCR / Tamkeen Fields for Aid",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "JO",
        "title": "Jordan Anti-Trafficking Law No. 9 of 2009 — Enforcement Data",
        "summary": "Jordan enacted the Prevention of Human Trafficking Law (No. 9 of 2009, amended 2021). Anti-Trafficking Unit (ATU) in PSD investigated 120-150 cases annually (2019-2023). Convictions: 15-25 per year, primarily for labour trafficking of domestic workers. Penalties: 6 months to 10 years imprisonment. US TIP Report rated Jordan Tier 2 Watch List due to insufficient convictions and victim identification. Victims eligible for 6-month temporary residency for case cooperation.",
        "source": "Jordanian Anti-Trafficking Unit / US TIP Report",
    },
    # ── Lebanon ────────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon Kafala System — Systemic Domestic Worker Abuse",
        "summary": "Lebanon employs approximately 250,000 migrant domestic workers from Ethiopia, Philippines, Bangladesh, and Sri Lanka under the kafala system. HRW documented: passport confiscation (universal), 18-20 hour workdays, confinement to household, physical and sexual abuse, salary withholding for months, workers thrown from balconies (suicide or murder disputed). An average of 2 domestic workers died per week (This Is Lebanon campaign statistics). Lebanon's Labour Law explicitly excludes domestic workers.",
        "source": "HRW / This Is Lebanon / Anti-Slavery International / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon Domestic Worker Deaths — Investigation Patterns",
        "summary": "Between 2016 and 2021, at least 100 domestic worker deaths were reported annually in Lebanon (embassy data from Ethiopia, Philippines, Bangladesh). Causes listed: suicide (30 percent), falling from buildings (25 percent), natural causes (25 percent), accident (15 percent), homicide (5 percent). Rights groups contested the high suicide/falling classification, noting that workers who were pushed or driven to jump were classified as suicides. Forensic investigations were rare. Employer prosecutions rarer still.",
        "source": "This Is Lebanon / ARM (Anti-Racism Movement) / ILO / embassy records",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon Economic Crisis — Impact on Migrant Domestic Workers",
        "summary": "Lebanon's economic crisis (2019-present) devastated migrant domestic workers. Currency collapse (LBP lost 90 percent of value) meant workers paid in LBP received a fraction of contracted USD salary. Employers abandoned workers: thousands left without pay, housing, or return tickets. Ethiopian Embassy assisted 5,000+ stranded workers (2020-2021). IOM organized repatriation flights for 10,000+ workers. General Security crackdown detained workers whose employers failed to renew residency.",
        "source": "IOM / Ethiopian Embassy Beirut / HRW / Amnesty International",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "LB",
        "title": "Lebanon Standard Unified Contract — Failed Implementation",
        "summary": "Lebanon's Ministry of Labour introduced a Standard Unified Contract (SUC) for domestic workers in September 2020: right to terminate contract, keep passport and phone, 48-hour weekly rest, maximum 10 working hours per day. However, the Shura Council (highest administrative court) suspended the contract in October 2020 after recruitment agencies challenged it. As of 2023, the SUC remains suspended. Lebanon continues without enforceable domestic worker protections.",
        "source": "Lebanon Ministry of Labour / HRW / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon Freelance Visa for Domestic Workers — Alternative to Kafala",
        "summary": "Lebanon introduced a 'freelance' visa option (2020) allowing domestic workers to work for multiple employers rather than being tied to one sponsor. General Security processes applications. By 2022, fewer than 2,000 workers obtained freelance status, primarily because: workers must exit kafala arrangement first (requiring employer consent), fees of USD 1,000+ for visa processing, and lack of awareness among workers. HRW noted the initiative was well-intentioned but structurally inaccessible.",
        "source": "HRW / General Security Lebanon / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "LB",
        "title": "Lebanon Domestic Worker Complaint Statistics",
        "summary": "Lebanon's General Directorate of General Security received 7,000-10,000 domestic worker-related complaints annually (2018-2022). Categories: contract disputes (40 percent), salary non-payment (30 percent), physical abuse (15 percent), sexual abuse (5 percent), document retention (10 percent). Criminal complaints filed in fewer than 5 percent of cases. Employers convicted in fewer than 1 percent. Workers who filed complaints had residency cancelled and faced deportation if employer counter-filed an absconding report.",
        "source": "General Security Lebanon / Kafa (Enough) Violence & Exploitation / ILO",
    },
    # ── Cross-GCC Issues ───────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "GCC Recruitment Fee Charging — Sub-Agent Chain Pattern",
        "summary": "Across all GCC states, migrant workers pay recruitment fees to origin-country agents despite destination-country bans. Structure: licensed agency in GCC contracts with origin-country agency, which sub-contracts to village-level agents. Each layer adds fees. Nepali workers pay NPR 50,000-250,000 for Qatar, Bangladeshi workers pay BDT 200,000-500,000 for Saudi/UAE. Workers take high-interest loans (24-48 percent) from local moneylenders. Debt repayment takes 8-18 months of salary, creating debt bondage for the initial contract period.",
        "source": "ILO Fair Recruitment Initiative / Verité / Open Working Group on Labour Migration",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "GCC Exit Permit and NOC Violations — Persistent Despite Reforms",
        "summary": "Despite Qatar (2018), Saudi Arabia (2021), and UAE (2022) reforming exit permit requirements, violations persist. Workers report employers retaining exit permits, delaying NOC processing, and refusing to approve transfers. Bahrain leads in implementation (abolished NOC in 2009). Kuwait maintains partial NOC system. Lebanon and Jordan have no reform timeline. ILO documented that 15-25 percent of workers seeking to leave GCC countries face employer-imposed delays.",
        "source": "ILO / Migrant-Rights.org / US TIP Reports",
    },
    {
        "type": "statistic",
        "jurisdiction": "QA",
        "title": "GCC Migrant Worker Population — Demographic Overview",
        "summary": "GCC states host approximately 30 million migrant workers (2023 estimates): Saudi Arabia 13 million, UAE 8.7 million, Kuwait 3.2 million, Qatar 2.1 million, Oman 2.0 million, Bahrain 0.8 million. Migrants constitute 30-90 percent of the population (Qatar 88 percent, UAE 85 percent, Kuwait 70 percent, Bahrain 55 percent, Oman 45 percent, Saudi 38 percent). Major origin countries: India, Pakistan, Bangladesh, Philippines, Nepal, Sri Lanka, Egypt, Ethiopia.",
        "source": "ILO / Gulf Labour Markets and Migration (GLMM) / UN DESA",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "GCC Wage Protection Systems — Cross-Country Comparison",
        "summary": "All six GCC states have implemented electronic WPS: Saudi (2013), UAE (2009), Qatar (2015), Kuwait (2015), Bahrain (2013), Oman (2014). Coverage varies: UAE and Saudi cover 90+ percent of private sector workers, while Oman and Kuwait cover 60-70 percent. None cover domestic workers. Common gaps: employers require workers to sign for higher amounts than paid, multiple-account workarounds, and companies with fewer than 5-10 employees excluded. ILO recommended extending WPS to all workers including domestics.",
        "source": "ILO / GLMM / respective Ministries of Labour",
    },
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "GCC Worker Complaint Hotlines — Accessibility and Effectiveness",
        "summary": "GCC complaint hotlines: Saudi 19911, UAE MOHRE 600-590-000, Qatar 16008, Kuwait 24844700, Bahrain LMRA 17103103, Oman 80077700. Languages vary: UAE operates in 18 languages, Saudi in 9, others in 4-6. Annual call volumes (2022): Saudi 500,000+, UAE 300,000+, Qatar 50,000+. Resolution rates: UAE reports 85 percent within 14 days, Qatar 70 percent within 21 days. However, workers report fear of retaliation (absconding charges) when using hotlines. Anonymity not guaranteed in smaller countries.",
        "source": "Respective Ministries of Labour / ILO / Migrant-Rights.org",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "GCC Construction Safety Records — Injury and Death Data Gaps",
        "summary": "Accurate construction worker death statistics across the GCC remain unavailable. Saudi GOSI reported 358 workplace deaths (2022) but does not disaggregate by nationality. UAE does not publish fatality statistics. Qatar reported 50 work-related deaths in 2020 but NGOs estimated 400+. Bahrain and Oman provide no public data. ILO noted that origin-country embassy data (Nepal 600-800 deaths/year in GCC, India 2,000+/year) significantly exceeds destination-country figures, suggesting underreporting.",
        "source": "ILO / GLMM / respective embassies / The Guardian",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "ILO Qatar Office — Technical Cooperation Programme Assessment",
        "summary": "ILO opened a project office in Qatar in 2018 under a 3-year technical cooperation agreement (extended through 2024). Key achievements: minimum wage law, exit permit abolition, employer transfer reform, WSIF establishment, Labour Dispute Committees. Criticism: ILO perceived as giving Qatar legitimacy without ensuring enforcement. ITUC and BWI argued ILO should be more critical. ILO published annual progress reports acknowledging both reforms and 'significant implementation gaps.'",
        "source": "ILO Qatar Office / ITUC / BWI",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Ethiopian Domestic Workers Stranded During COVID-19",
        "summary": "During COVID-19 (2020-2021), thousands of Ethiopian domestic workers were abandoned by employers in Saudi Arabia. An estimated 30,000 Ethiopian workers were detained in Riyadh detention centres in overcrowded conditions. Saudi authorities deported 16,000 Ethiopians (March-April 2020), many by charter flights. Workers reported beatings in detention, forced deportation without collecting wages, and confiscation of belongings. IOM assisted with voluntary repatriation of 10,000+ workers.",
        "source": "HRW / IOM / Sunday Telegraph / Ethiopian Ministry of Foreign Affairs",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE Camel Jockey Trafficking — Historical Enforcement Action",
        "summary": "UAE historically used child camel jockeys (boys aged 4-8 from South Asia and Sudan). UNICEF estimated 40,000 children trafficked for camel racing across the GCC. UAE banned child jockeys in 2005 (Federal Law No. 15 of 2005) and introduced robot jockeys. Compensation fund established: UAE paid USD 9 million to 1,072 identified victims (2006-2009). Some former child jockeys never identified or compensated. Practice effectively ended in UAE but reports of continued use in Sudan and Somalia.",
        "source": "UNICEF / US TIP Report / Ansar Burney Trust",
    },
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "Kuwait Bidoon Exploitation — Stateless Workers in Labour Market",
        "summary": "Kuwait's estimated 100,000 Bidoon (stateless residents) face unique labour exploitation. Lacking citizenship, Bidoon receive temporary security cards restricting employment to private sector. Documented exploitation: lower wages than citizens for equivalent work, inability to own businesses, restricted professions, deportation threats (to countries they have no connection to). Central Agency for Bidoon Affairs controls documentation. UNHCR and HRW advocated for naturalization pathway.",
        "source": "HRW / UNHCR / Kuwait Society for Human Rights",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE Sharjah Industrial Zone — Worker Accommodation Standards",
        "summary": "Sharjah industrial zones house approximately 200,000 workers in labour accommodations. Sharjah Municipality Resolution No. 87 of 2009 set standards: maximum 8 workers per room, minimum 3 sqm per person, recreational facilities, kitchen and dining areas. Inspections (2022) found 35 percent of accommodations non-compliant. Common violations: overcrowding, fire safety, sanitation. Workers pay AED 100-250/month through wage deductions. Some workers live in partitioned warehouses not designed for habitation.",
        "source": "Sharjah Municipality / Migrant-Rights.org",
    },
    {
        "type": "case_study",
        "jurisdiction": "JO",
        "title": "Jordan Agricultural Workers — Undocumented Egyptian Labour",
        "summary": "Jordan's agriculture sector employs 50,000+ Egyptian workers, many on expired or informal visas. Workers in the Jordan Valley face: 12-14 hour days during harvest, no contracts, piece-rate wages below minimum wage (JOD 260/month), no health insurance, employer-provided housing in temporary shelters without sanitation. Workers cannot file labour complaints due to irregular status. MOL inspections in agriculture: fewer than 100 annually for the entire sector.",
        "source": "ILO / Tamkeen Fields for Aid / Jordanian Ministry of Labour",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon Recruitment Agency Practices — Agency Warehousing",
        "summary": "Lebanese recruitment agencies engage in 'warehousing': newly arrived domestic workers held in agency offices for days or weeks until placed with employers. Workers sleep on floors, phones confiscated, movement restricted. Agencies charge employers USD 2,000-4,000 and offer '3-month guarantees' (employer can return worker for replacement). Workers returned to agency face cycle of re-placement with no wages for period between employers. General Security regulates agencies but inspections are infrequent.",
        "source": "Kafa / HRW / ILO / ARM Lebanon",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Worker Protest Crackdowns and Deportation",
        "summary": "Workers who organize protests in Saudi Arabia face arrest and deportation. In November 2013, Saudi authorities arrested 4,000+ undocumented workers in Riyadh's Manfouha district during a crackdown. Ethiopian and Somali workers clashed with police. Two Ethiopian workers and one Saudi security officer killed. 150,000+ workers deported in subsequent months. ILO noted that criminalization of worker protest deters legitimate complaints about wage theft and abuse.",
        "source": "HRW / Al Jazeera / Ethiopian Ministry of Foreign Affairs",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Qatar Worker Accommodation Standards — Supreme Committee vs General",
        "summary": "Qatar Supreme Committee for Delivery and Legacy (World Cup) implemented Worker Welfare Standards (WWS) on designated projects: maximum 4 workers per room, minimum 6 sqm per person, recreational facilities, health checks, ethical recruitment audits. Standards significantly higher than national requirements. However, WWS applied only to the 8 stadiums and immediate infrastructure (30,000 workers). The remaining 2+ million migrant workers lived under general regulations with weaker standards and enforcement.",
        "source": "SC / Amnesty International / ILO / BWI",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE Employment Ban as Punishment — Absconding System",
        "summary": "UAE employers can file absconding reports through MOHRE's Tasheel system. Workers reported as absconding receive 1-year employment ban and must leave the country within 30 days. Workers can contest the report but the process takes 2-4 weeks during which they cannot work. MOHRE data (2022): 50,000+ absconding complaints filed. Workers' rights groups reported that 30-40 percent of absconding reports were retaliatory, filed after workers complained about salary or conditions.",
        "source": "MOHRE / Migrant-Rights.org / HRW",
    },
    {
        "type": "case_study",
        "jurisdiction": "BH",
        "title": "Bahrain Anti-Trafficking Prosecution — Landmark Cases",
        "summary": "Bahrain's Anti-Trafficking Unit (part of LMRA) investigated 35-50 cases annually (2019-2023). Notable convictions: employer convicted of trafficking 8 Bangladeshi workers for restaurant work under forced conditions (2021, 10 years imprisonment); recruitment agent convicted of trafficking 15 Ethiopian domestic workers (2022, 7 years). Sentences among the most severe in the GCC. Bahrain's trafficking law (Law No. 1 of 2008) provides penalties of 3-15 years imprisonment.",
        "source": "LMRA Bahrain / US TIP Report / UNODC",
    },
    {
        "type": "case_study",
        "jurisdiction": "OM",
        "title": "Oman Fishing Sector — Migrant Worker Exploitation",
        "summary": "Oman's fishing sector employs approximately 40,000 workers, with Indian, Bangladeshi, and Pakistani nationals comprising 60 percent. ILO documented: 14-18 hour workdays during fishing season, wages paid as share of catch (often below minimum wage), no contracts, employer-controlled housing on boats or near ports, movement restricted in remote coastal areas. Workers brought on visit visas and employed informally. Ministry of Agriculture and Fisheries has separate inspection regime from Ministry of Labour.",
        "source": "ILO / Indian Embassy Muscat / Migrant Forum in Asia",
    },
    {
        "type": "case_study",
        "jurisdiction": "JO",
        "title": "Jordan Better Work Programme — Factory Monitoring Impact",
        "summary": "ILO Better Work Jordan (launched 2008) monitors 89 garment factories employing 65,000+ workers. Compliance improvements documented: forced overtime dropped from 80 to 25 percent of factories (2008-2023), regular wage payment increased from 55 to 92 percent, passport confiscation dropped from 50 to 10 percent. However, Better Work does not cover non-garment sectors, domestic work, or agriculture. Workers in non-monitored factories continue to face high rates of exploitation.",
        "source": "ILO Better Work Jordan Annual Report / BWI",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon General Security — Kafala Enforcement Complicity",
        "summary": "Lebanon's General Security (Directorate General of General Security) administers residency for migrant domestic workers. HRW and Kafa documented that General Security routinely: sides with employers in disputes, deports workers who file complaints, requires employer consent for visa renewal, and fails to investigate deaths. Workers overstaying visas face LBP 300,000/month penalty (pre-crisis), leading to accumulated fines that prevent legal departure. System creates structural dependence on employers.",
        "source": "HRW / Kafa / ARM / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Domestic Worker App-Based Hiring (Musaned / Ajeer)",
        "summary": "Saudi Arabia introduced app-based platforms for domestic worker hire: Musaned (permanent contracts) and Ajeer (temporary hourly hire). Ajeer allows part-time domestic work at SAR 30-50/hour, processed through individual sponsors' accounts. Workers report Ajeer employers sometimes extend hourly engagements into 12+ hour unpaid work. No in-person inspection for Ajeer jobs. Platform reviews insufficient to detect abuse. By 2023, 1.5 million Ajeer transactions processed.",
        "source": "Saudi Ministry of Human Resources / Migrant-Rights.org",
    },
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "Kuwait Indian Embassy — Worker Rescue and Repatriation Operations",
        "summary": "Indian Embassy Kuwait operates one of the most active labour welfare systems in the GCC. Community Welfare Fund assists 3,000-5,000 distressed Indian workers annually. Open houses receive 100+ workers/week seeking assistance. Cases: unpaid wages (40 percent), contract disputes (25 percent), work injuries (15 percent), abuse (10 percent), death cases (10 percent). Embassy repatriated 7,000+ workers during COVID-19 (Vande Bharat Mission). Community Welfare Wing mediates 2,000+ salary disputes annually.",
        "source": "Indian Embassy Kuwait / MEA India / Community Welfare Fund",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Qatar — Nepali Worker Death Investigation Failures",
        "summary": "Nepal Foreign Employment Board data showed 1,641 Nepali workers died in Qatar between 2010 and 2020. Most death certificates listed 'sudden cardiac arrest' or 'natural causes.' Nepali government commissioned study (Mandal Committee, 2018) found most deaths were of young, apparently healthy men. Inadequate post-mortem examinations: autopsies performed in fewer than 15 percent of cases. Families in Nepal received death benefits of NPR 700,000-1,000,000 but no explanation of cause. Qatar rejected calls for independent investigation.",
        "source": "Nepal Foreign Employment Board / Amnesty International / The Guardian",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE Fishing Vessel Workers — Stranded at Sea",
        "summary": "Indian, Pakistani, and Bangladeshi workers on UAE-registered fishing vessels reported being stranded at sea for 6-12 months without shore leave. Workers paid monthly salary of AED 700-1,000 (below minimum for other sectors). Passports held by boat captain. Workers unable to contact embassies. ILO C188 (Work in Fishing Convention) not ratified by UAE. Abu Dhabi Maritime Authority has limited jurisdiction over fishing labour conditions. Indian Embassy Consulate Dubai rescued 200+ stranded fishermen (2019-2023).",
        "source": "Indian Consulate Dubai / ILO / Migrant-Rights.org",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Filipino Overseas Worker Deaths Pattern Analysis",
        "summary": "Philippine DFA data shows an average of 800-1,000 Filipino workers die annually in Saudi Arabia (2018-2023, all causes including natural death). Of these, 150-200 involve distress cases (abuse, overwork, suicide). DMW POLO Riyadh and POLO Jeddah handle 50-80 death cases per year involving suspected foul play or workplace negligence. Saudi authorities rarely share autopsy results with families or embassies. Repatriation of remains costs PHP 150,000-300,000, often borne by families.",
        "source": "Philippine DFA / DMW / POLO Riyadh / POLO Jeddah",
    },
    {
        "type": "case_study",
        "jurisdiction": "JO",
        "title": "Jordan Domestic Worker Trafficking — Shelter System",
        "summary": "Jordan operates Dar Karama shelter (est. 2014) for trafficking victims and abused domestic workers. Capacity: 50 beds. Run by Ministry of Social Development with IOM support. Shelter houses 40-60 women at any time, primarily Ethiopian, Filipino, and Bangladeshi. Average stay: 3-6 months. Services: legal aid, psychosocial support, repatriation assistance. Jordan Anti-Trafficking Unit refers 30-50 cases annually to the shelter. Workers face deportation if they refuse to cooperate with prosecution.",
        "source": "Jordanian Ministry of Social Development / IOM / UNODC",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon — Migrant Domestic Worker COVID-19 Abandonment Crisis",
        "summary": "During Lebanon's combined economic and COVID-19 crisis (2020-2021), an estimated 10,000 domestic workers were abandoned by employers. Workers left on streets or outside embassy buildings with packed bags. Ethiopian, Bangladeshi, and Filipino embassies overwhelmed. Lebanese General Security detained workers with expired residency rather than penalizing abandoning employers. IOM organized emergency flights: 15,000+ workers repatriated by end of 2021. Some workers had wages owed for 3-12 months with no recovery mechanism.",
        "source": "IOM / HRW / This Is Lebanon / embassy records",
    },
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "Kuwait Filipino Domestic Worker Deployment Ban (2018-2020)",
        "summary": "Philippines imposed a total deployment ban to Kuwait in February 2018 after domestic worker Joanna Demafelis was found dead in a freezer. Ban lifted in May 2018 under bilateral agreement establishing: domestic worker hotline, mandatory bank account for salary, right to keep passport and phone, employer must provide suitable accommodation, standard employment contract. By 2020, deployment resumed fully. Compliance monitoring found 60-70 percent of employers adhering to new terms. Workers whose employers violated terms could request POLO-assisted transfer.",
        "source": "DMW / Philippine Embassy Kuwait / Kuwait PAM",
    },
    {
        "type": "case_study",
        "jurisdiction": "BH",
        "title": "Bahrain Construction Worker Wage Theft — Cement and Steel Sector",
        "summary": "Bahrain's construction sector employs approximately 80,000 migrant workers. LMRA data (2022) documented 2,500 wage-related complaints. Common pattern: subcontractors fail to pay workers when main contractor withholds payment due to project delays. Workers go unpaid for 3-6 months while company disputes are resolved in commercial courts. LMRA's anti-trafficking team intervened in 45 cases involving 20+ workers each (mass wage theft). Indian and Bangladeshi workers disproportionately affected.",
        "source": "LMRA Bahrain / Indian Embassy Manama / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "OM",
        "title": "Oman Construction Safety — Worker Falls and Injuries",
        "summary": "Oman reported 2,500+ workplace injuries annually (Ministry of Manpower, 2021). Construction sector accounted for 45 percent. Falls from height leading cause of death (40 percent of fatalities). Workers reported lack of safety equipment (harnesses, helmets), inadequate training in Arabic or English (workers speak Hindi, Bengali, Nepali), and pressure to work at height without safety measures. Oman ratified ILO C155 (Occupational Safety) but enforcement lags behind standards.",
        "source": "Oman Ministry of Manpower / ILO / Muscat Daily",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Domestic Worker Loan-Out Practice",
        "summary": "Pattern documented by DMW and HRW: employers 'loan out' domestic workers to relatives, friends, or neighbours for days, weeks, or months. Workers receive no additional pay and have no contract with the borrowing household. Workers in loan-out situations report higher rates of abuse due to lack of accountability. Practice violates Saudi Domestic Worker Regulation but enforcement is negligible. POLO Riyadh received 200+ loan-out complaints annually (2019-2023).",
        "source": "DMW / POLO Riyadh / HRW",
    },
    {
        "type": "statistic",
        "jurisdiction": "QA",
        "title": "Qatar WPS Compliance — Electronic Salary Payment Monitoring",
        "summary": "Qatar's Wage Protection System (WPS), operational since 2015, monitors salary payments for 2 million workers in the private sector. Ministry of Labour data (2023): 97 percent compliance rate for registered companies. However, WPS detects only whether money was transferred, not whether workers received the full amount. Workers report employers requiring partial salary return in cash after electronic deposit. WPS does not cover domestic workers or workers in companies with fewer than 5 employees.",
        "source": "Qatar Ministry of Labour / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE Domestic Worker Trafficking — Abu Dhabi Judicial Precedent",
        "summary": "Abu Dhabi Criminal Court convicted an employer of trafficking a Filipino domestic worker in 2019: confined worker for 2 years without day off, confiscated phone and passport, withheld 8 months of wages, physical abuse documented by medical examination. Employer sentenced to 3 years imprisonment and AED 100,000 fine. Worker awarded AED 50,000 compensation. Case cited as precedent by MOHRE for strengthening domestic worker protections under Federal Law No. 10 of 2017.",
        "source": "Abu Dhabi Judicial Department / MOHRE / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "JO",
        "title": "Jordan Garment Worker Sexual Harassment — Endemic Pattern",
        "summary": "Better Work Jordan assessments (2018-2023) documented sexual harassment in 15-20 percent of assessed factories. Pattern: male supervisors targeting female migrant workers (Sri Lankan, Bangladeshi) with threats to contracts, overtime assignments, or deportation if complaints filed. Factories with functioning worker committees reported lower harassment rates. Jordanian Penal Code criminalized sexual harassment (2017 amendment) but factory-level enforcement relies on internal grievance mechanisms. Few criminal prosecutions.",
        "source": "Better Work Jordan / Tamkeen / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon — Ethiopian Embassy Worker Rescue Operations",
        "summary": "Ethiopian Embassy Beirut conducted emergency rescue operations for domestic workers in distress. Between 2019 and 2022, the embassy received 15,000+ distress calls. Embassy shelter (Badaro area) housed 200-300 women at peak occupancy. Consular staff personally retrieved workers from abusive households. Embassy documented: physical abuse (30 percent), salary non-payment (40 percent), sexual abuse (10 percent), confinement (20 percent). Post-crisis, Ethiopia suspended deployment to Lebanon in 2020.",
        "source": "Ethiopian Embassy Beirut / IOM / HRW",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Worker Deportation During Hajj Crackdowns",
        "summary": "Saudi authorities conduct annual security operations before and during Hajj season targeting undocumented workers in Makkah and Madinah. Operations in 2022-2023 arrested and deported 100,000+ workers. Workers apprehended without valid iqama (residency) face detention in overcrowded facilities, administrative processing (4-8 weeks), and deportation without opportunity to collect unpaid wages or personal belongings. Indian, Ethiopian, and Nigerian workers most commonly affected.",
        "source": "Saudi Ministry of Interior / HRW / Indian Embassy Jeddah",
    },
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "Kuwait — Domestic Worker Run-Away Shelters and Services",
        "summary": "Kuwait's government shelter for domestic workers (operated by Kuwait Society for Human Rights with MOSA support) provides temporary housing for 80-100 women. Services include legal aid, medical care, and repatriation coordination. Average processing time: 2-4 months. Workers in shelter cannot work or earn income, creating financial hardship. Filipino, Indian, Sri Lankan, and Ethiopian workers comprise 80 percent of shelter residents. Kuwait HRC documented 2,000+ shelter requests annually with only 100 beds available.",
        "source": "Kuwait Society for Human Rights / MOSA / Philippine Embassy Kuwait",
    },
    {
        "type": "case_study",
        "jurisdiction": "BH",
        "title": "Bahrain National Committee to Combat Trafficking — Coordination Mechanism",
        "summary": "Bahrain established the National Committee to Combat Trafficking in Persons (2008, chaired by LMRA CEO). Committee coordinates: victim identification (NRM), prosecution referral, shelter provision, prevention campaigns. Published national strategy 2022-2024. Identified 105 potential victims in 2022. Strengths: integrated data system, trained front-line officers. Weaknesses: low conviction rate (5-10 per year), limited restitution to victims, domestic worker exploitation underidentified. US TIP Report rated Bahrain Tier 2.",
        "source": "LMRA Bahrain / US TIP Report / UNODC",
    },
    {
        "type": "case_study",
        "jurisdiction": "OM",
        "title": "Oman — Employer-Provided Housing Standards Violation",
        "summary": "Oman requires employers to provide housing or housing allowance for migrant workers (Ministerial Decision 222/2020). In practice, workers in construction, agriculture, and fishing sectors housed in overcrowded accommodations: 12-20 workers per room, shared bathrooms (1 per 20+ workers), no cooling in summer (temperatures exceeding 45 degrees). Workers pay OMR 15-30/month through deductions despite employer obligation. Ministry inspections: 500+ housing violations cited in 2022 but penalties (OMR 100-500) insufficient to deter.",
        "source": "Oman Ministry of Manpower / ILO / Indian Embassy Muscat",
    },
    {
        "type": "case_study",
        "jurisdiction": "JO",
        "title": "Jordan — Migrant Worker Access to Healthcare Barriers",
        "summary": "Jordan's Social Security Corporation (SSC) covers formal sector workers including migrants with valid permits. However, 60+ percent of migrant workers in Jordan lack formal contracts and thus lack SSC coverage. Workers in domestic, agricultural, and construction sectors must pay out-of-pocket for medical care. Documented barriers: employer confiscating health insurance cards, language barriers at hospitals, fear of deportation when seeking emergency care with expired visa. MOH provides emergency care regardless of status but non-emergency care requires payment.",
        "source": "ILO / Tamkeen / Jordan Ministry of Health",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon — Domestic Worker Social Media Trafficking",
        "summary": "BBC Arabic investigation (2019) documented domestic workers being bought and sold on Instagram and Facebook in Lebanon. Employers posted advertisements offering to 'sell' or 'transfer' workers with photos and descriptions. Some posts included age, nationality, and 'negotiable' prices (USD 1,000-3,000). Meta removed thousands of posts after BBC report but new accounts continued. Lebanese authorities took no legal action against advertisers. Practice reflects commodification of workers under kafala system.",
        "source": "BBC Arabic / HRW / Kafa",
    },
    {
        "type": "case_study",
        "jurisdiction": "QA",
        "title": "Qatar — Amnesty International Legacy Compensation Campaign",
        "summary": "Amnesty International launched the #PayUp campaign (2022) demanding FIFA and Qatar establish a USD 440 million compensation fund (matching FIFA's World Cup prize money) for migrant workers who suffered human rights abuses during World Cup preparations. FIFA rejected the demand in its official response. By 2023, no comprehensive compensation mechanism was established. Qatar's WSIF addressed wage theft but not injury, death, or recruitment fee compensation. Five national football federations (Australia, France, Germany, Belgium, Netherlands) supported the campaign.",
        "source": "Amnesty International / FIFA / ITUC / BWI",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE — Begging and Street Vendor Worker Trafficking",
        "summary": "UAE anti-trafficking authorities identified cases of organized begging rings trafficking workers from South Asia and East Africa. Victims brought on visit visas and forced to beg at traffic intersections and shopping centres, with earnings confiscated by traffickers. Dubai Police anti-trafficking unit reported 50-100 cases annually. Victims face deportation as immigration violators rather than identification as trafficking victims. UAE National Committee to Combat Trafficking acknowledged the issue in 2022 strategy but victim identification remains inadequate.",
        "source": "Dubai Police / UAE National Committee to Combat Trafficking / US TIP Report",
    },
    {
        "type": "statistic",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Labour Inspection Capacity and Coverage",
        "summary": "Saudi Ministry of Human Resources employs approximately 2,500 labour inspectors for 8 million private sector workers (ratio 1:3,200). Inspections (2022): 400,000+ visits, 120,000+ violations cited. Top violations: WPS non-compliance (30 percent), safety (25 percent), contract violations (20 percent), housing standards (15 percent), working hours (10 percent). Penalties: SAR 3,000-100,000 per violation. However, inspectors rarely access domestic worker employers' homes and cannot enter without judicial warrant.",
        "source": "Saudi Ministry of Human Resources / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "KW",
        "title": "Kuwait — Worker Suicides and Mental Health Crisis",
        "summary": "Indian Embassy Kuwait documented 40-60 Indian worker deaths by suicide annually (2018-2023). Factors: debt burden from recruitment fees, isolation, wage theft, inability to return home, poor living conditions. Filipino and Bangladeshi embassies reported similar patterns. Kuwait has no migrant worker mental health services. No psychological first aid in labour camps. Embassy-operated help lines are the only support. POLO Kuwait added mental health component to pre-departure orientation but post-arrival services remain absent.",
        "source": "Indian Embassy Kuwait / POLO Kuwait / IOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "BH",
        "title": "Bahrain LMRA — Proactive Labour Inspection Model",
        "summary": "Bahrain's Labour Market Regulatory Authority (LMRA) conducts proactive inspections targeting high-risk sectors: construction, hospitality, cleaning, and retail. Inspection teams include multilingual staff (Arabic, Hindi, Bengali, Tagalog). 2022 data: 15,000 workplace inspections, 3,500 violations detected, 200 companies penalized, 150 employment bans issued. LMRA operates joint inspections with anti-trafficking unit. ILO cited Bahrain's inspection model as GCC best practice but noted limited reach to domestic work sector.",
        "source": "LMRA Bahrain / ILO / US TIP Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "OM",
        "title": "Oman — Free Visa (Tasheet) System Exploitation",
        "summary": "Oman's informal 'free visa' system (tasheet) involves employers selling sponsorship visas to workers for OMR 500-1,500/year. Workers operate independently, often in taxi driving, small trade, or manual labour. Workers are undocumented with respect to actual employment and vulnerable to arrest. Royal Oman Police conducted crackdowns deporting 50,000+ workers annually on visa violations. Tasheet workers have no access to labour courts, WPS, or health insurance. System constitutes structural trafficking per ILO definitions.",
        "source": "ILO / Oman Ministry of Manpower / Migrant-Rights.org",
    },
    {
        "type": "case_study",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Bilateral Labour Agreements Assessment",
        "summary": "Saudi Arabia has signed bilateral labour agreements with: Philippines (2013, updated 2017), Indonesia (2014), India (2014), Sri Lanka (2014), Bangladesh (2015), Kenya (2020), Uganda (2021). Key provisions: standard contracts, salary escrow, recruitment fee regulation, joint monitoring committees. Implementation varies: Philippines-Saudi agreement considered most enforceable (POLO monitoring). Bangladesh-Saudi agreement lacks effective joint committee. ILO assessed that bilateral agreements improve standards where both governments actively engage but most lack binding enforcement mechanisms.",
        "source": "ILO / respective Ministries of Labour / bilateral agreement texts",
    },
]
