"""Occupational health and safety risks for migrant workers — deaths, injuries, and protections."""

HEALTH_AND_SAFETY_FACTS: list[dict] = [
    # ── Gulf Construction Deaths ────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "QA",
        "title": "Qatar — Migrant Worker Deaths During World Cup Construction",
        "metric": "worker_deaths",
        "value": "6,500+",
        "summary": "The Guardian investigation found 6,500+ migrant workers from India, Pakistan, Nepal, Bangladesh, and Sri Lanka died in Qatar between 2010-2020 during the World Cup construction period. Qatar classifies most deaths as 'natural causes' or 'cardiac arrest' without autopsy. Families receive minimal or no compensation. True toll disputed — likely higher due to unreported deaths.",
        "source": "The Guardian / Amnesty International",
    },
    {
        "type": "statistic",
        "jurisdiction": "QA",
        "title": "Qatar — Heat-Related Worker Deaths",
        "metric": "heat_related_mortality",
        "value": "571 (2012-2020)",
        "summary": "Vital Signs Partnership analysis of Nepali worker deaths in Qatar (2012-2020) found 571 died from 'cardiac arrest' or 'natural causes' — conditions strongly associated with heat stroke. Workers exposed to temperatures exceeding 45°C in summer. Qatar's outdoor work ban (11:30am-3pm June-August) insufficient: wet-bulb globe temperature (WBGT) exceeds safe thresholds outside ban hours.",
        "source": "Vital Signs Partnership / British Journal of Sports Medicine",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "QA",
        "title": "Qatar — Ministerial Decision No. 17 of 2021 (Heat Protections)",
        "summary": "Qatar expanded outdoor work ban (Decision No. 17 of 2021): June 1 – September 15, 10:00am-3:30pm. Added WBGT monitoring requirement — work stops if WBGT exceeds 32.1°C regardless of time. Employers must provide shade, water, rest areas. Annual heat stress awareness training required. Penalty: temporary or permanent site closure.",
        "source": "Qatar Ministry of Labour / ILO Qatar",
    },
    # ── Saudi Arabia ────────────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Annual Migrant Worker Deaths",
        "metric": "annual_migrant_deaths",
        "value": "10,000+ estimated",
        "summary": "Saudi Arabia does not publish comprehensive migrant worker mortality data. Indian Embassy (2022) reported 4,400 Indian worker deaths in Saudi Arabia over 5 years. Extrapolating across all nationalities, total annual migrant deaths estimated at 10,000+. Construction, heat exposure, road accidents are leading causes. Kidney disease linked to chronic dehydration prevalent among outdoor workers.",
        "source": "Indian Embassy Riyadh / Amnesty International / FairSquare Projects",
    },
    {
        "type": "advisory",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Heat Exposure Risks for Outdoor Workers",
        "summary": "Saudi Arabia's outdoor work ban (Royal Decree): noon-3pm, June-August. Temperatures regularly exceed 50°C. Workers in construction, agriculture, and waste collection face chronic dehydration, heat stroke, and kidney damage. Study in Annals of Work Exposures and Health (2021) found 25% of construction workers showed signs of chronic kidney disease linked to occupational heat exposure.",
        "source": "Saudi Ministry of Labour / Annals of Work Exposures and Health",
    },
    # ── Fishing / Maritime ──────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "TH",
        "title": "Thailand — Fishing Vessel Worker Deaths and Injuries",
        "sector": "fishing",
        "exploitation_type": "abusive_conditions",
        "summary": "ILO study (2018) of Thai fishing sector found: 37% of surveyed fishers reported witnessing death of fellow crew member, 83% reported injuries on board, 47% worked 14+ hour shifts. Myanmar and Cambodian workers most affected. Vessels stay at sea for months — injuries untreated. Bodies disposed of at sea in extreme cases.",
        "source": "ILO / Environmental Justice Foundation",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "ILO — Fishing as Most Dangerous Occupation",
        "metric": "fishing_fatality_rate",
        "value": "80 deaths per 100,000 workers",
        "summary": "ILO estimates fishing has a fatality rate of 80 per 100,000 workers — among the highest of any occupation globally. For migrant fishers in forced labour, risk is amplified: no safety equipment, unseaworthy vessels, no medical access, inability to refuse dangerous work. ILO Work in Fishing Convention (C188) ratified by only 19 countries.",
        "source": "ILO / FAO",
    },
    # ── Domestic Work ───────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon — Domestic Worker Deaths from Falling",
        "sector": "domestic_work",
        "exploitation_type": "abusive_conditions",
        "summary": "Human Rights Watch documented pattern of domestic worker deaths in Lebanon from falling from balconies — averaging 2 per month. Authorities classify as suicide or accident. Evidence suggests many result from: forced window cleaning without safety equipment, workers attempting to escape locked apartments, or employer violence. Ethiopian and Filipina workers most affected.",
        "source": "Human Rights Watch / This Is Lebanon campaign",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Domestic Worker Injury Rates — Global Estimate",
        "metric": "domestic_worker_injury_prevalence",
        "value": "35-40%",
        "summary": "ILO estimates 35-40% of domestic workers experience work-related injuries or illness. Common injuries: burns (cooking/ironing), chemical exposure (cleaning products), musculoskeletal disorders (heavy lifting), psychological trauma. Live-in workers face 24-hour exposure. Most excluded from occupational health and safety regulations and workers' compensation schemes.",
        "source": "ILO Policy Brief on Domestic Workers (2021)",
    },
    # ── Construction ────────────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Construction Sector — Migrant Worker Fatality Rates",
        "metric": "construction_migrant_fatalities",
        "value": "60,000+ annually",
        "summary": "ILO estimates 60,000+ fatal construction accidents globally per year, with migrant workers disproportionately represented. Migrants assigned most dangerous tasks (height work, demolition, excavation). Language barriers prevent understanding safety instructions. Workers fear reporting hazards due to immigration status. Safety equipment often inadequate or absent for migrant crew.",
        "source": "ILO / Building and Wood Workers' International (BWI)",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "Malaysia — Construction Site Safety Violations Affecting Migrants",
        "sector": "construction",
        "exploitation_type": "abusive_conditions",
        "summary": "DOSH Malaysia (2023) reported 200+ construction fatalities annually, disproportionately affecting undocumented migrant workers from Indonesia, Bangladesh, and Myanmar. Workers lack safety training in their language, are denied PPE, and fear reporting injuries. Undocumented workers cannot access SOCSO compensation. Employers face minimal penalties — fines averaging MYR 20,000.",
        "source": "DOSH Malaysia / Malaysian Trades Union Congress",
    },
    # ── Agriculture ─────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "USA — Heat Deaths Among Agricultural Migrant Workers",
        "sector": "agriculture",
        "exploitation_type": "abusive_conditions",
        "summary": "CDC data shows farmworkers die from heat-related causes at 20x the rate of all US workers. California, Florida, and Washington report highest rates. H-2A visa workers vulnerable: tied to single employer, fear retaliation for stopping work, may lack water/shade access. OSHA proposed federal heat standard (2023) but implementation delayed. 2,300+ workers died from heat exposure 1992-2017.",
        "source": "CDC / OSHA / National COSH",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Pesticide Exposure Among Migrant Agricultural Workers",
        "summary": "Migrant farmworkers face elevated pesticide exposure: inadequate PPE, instructions in unfamiliar language, employer pressure to continue working during/after spraying, housing near treated fields. WHO estimates 385M annual pesticide poisoning cases globally. Chronic exposure linked to cancer, neurological damage, reproductive harm. Workers fear reporting due to immigration status.",
        "source": "WHO / Pesticide Action Network / ILO",
    },
    # ── Mental Health ───────────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Forced Labour and Mental Health Outcomes",
        "metric": "ptsd_prevalence_trafficking_survivors",
        "value": "77%",
        "summary": "Systematic review (Lancet, 2023) found PTSD prevalence of 77% among trafficking survivors, depression 71%, anxiety 63%. Migrant workers in forced labour show elevated suicidality: Nepal reported 1,600+ migrant worker suicides (2008-2021), many in Gulf states. Post-rescue mental health support severely lacking in most origin and destination countries.",
        "source": "The Lancet / IOM / Nepal Foreign Employment Board",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Barriers to Healthcare Access for Migrant Workers",
        "summary": "Barriers to health access: (1) employer controls health insurance card, (2) fear of deportation if seeking emergency care, (3) cost deducted from wages, (4) language barriers with providers, (5) remote work locations (fishing, agriculture, construction camps), (6) working hours prevent clinic visits, (7) undocumented status bars access entirely in some jurisdictions.",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "QA",
        "title": "Qatar — Workers' Health Insurance and Compensation Reforms",
        "summary": "Qatar introduced mandatory health insurance for all workers including migrants (2022). Employers must provide health cards. Workers' compensation fund established for occupational injuries. Death benefits of QAR 50,000-200,000 paid to families. However, 'natural cause' death classifications deprive many families of compensation — reclassification efforts ongoing with ILO support.",
        "source": "Qatar Ministry of Public Health / ILO",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Occupational Safety and Health Convention (C155)",
        "summary": "ILO Convention C155 (1981) requires states to formulate national OSH policy covering all workers. Supplemented by C187 (Promotional Framework, 2006). As of 2024, C155 ratified by 74 countries, many GCC and SE Asian destination countries not parties. ILO General Conference (2022) declared safe and healthy working environment a fundamental principle — binding on all ILO members regardless of ratification.",
        "source": "ILO NORMLEX / ILO Declaration June 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "COVID-19 Impact on Migrant Worker Health and Safety",
        "sector": "multiple",
        "exploitation_type": "abusive_conditions",
        "summary": "COVID-19 exposed extreme vulnerability: cramped dormitories (Singapore: 300,000+ workers in camps, 60% infection rate), loss of employment without repatriation (Lebanon, GCC), forced to continue working without PPE (meat processing, agriculture), barriers to vaccination, excluded from social protection. Malaysia: 600+ workers per dormitory room. Qatar construction camps: shared sanitation for 100+ workers.",
        "source": "ILO / IOM / Lancet Migration",
    },
]
