"""International legal instruments — treaties, conventions, protocols, and soft law on trafficking and forced labor."""

INTERNATIONAL_INSTRUMENT_FACTS: list[dict] = [
    # ══════════════════════════════════════════════════════════════════════
    # UN INSTRUMENTS
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Protocol to Prevent, Suppress and Punish Trafficking in Persons, Especially Women and Children (Palermo Protocol, 2000)",
        "summary": "Supplementary protocol to the UN Convention against Transnational Organized Crime. Article 3(a) defines trafficking as: recruitment, transportation, transfer, harbouring, or receipt of persons by means of threat, force, coercion, abduction, fraud, deception, abuse of power, or payments to a controlling person, for exploitation. Exploitation includes forced labor, slavery, servitude, and organ removal. Entered into force 2003. 180 state parties as of 2024.",
        "source": "United Nations, A/RES/55/25, Annex II (2000)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Protocol against the Smuggling of Migrants by Land, Sea and Air (2000)",
        "summary": "Supplementary protocol to UNTOC. Distinguishes smuggling (consent-based, ends at destination) from trafficking (coercion-based, ongoing exploitation). Criminalizes migrant smuggling when done for financial or material benefit. Requires states to protect smuggled migrants' rights. States must address root causes of smuggling including poverty and underdevelopment. 150 state parties.",
        "source": "United Nations, A/RES/55/25, Annex III (2000)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Convention against Transnational Organized Crime (UNTOC, 2000)",
        "summary": "Parent convention for both trafficking and smuggling protocols. Establishes framework for international cooperation against organized crime. Requires criminalization of participation in organized criminal groups, money laundering, corruption, and obstruction of justice. Provides for extradition, mutual legal assistance, and joint investigations. 190 state parties. Palermo Protocol must be read in conjunction with UNTOC.",
        "source": "United Nations, A/RES/55/25 (2000)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ICCPR Article 8 — Prohibition of Slavery, Servitude, and Forced Labour",
        "summary": "International Covenant on Civil and Political Rights Article 8: (1) No one shall be held in slavery; slavery and the slave trade are prohibited. (2) No one shall be held in servitude. (3) No one shall be required to perform forced or compulsory labour. Exceptions: prison labor under court sentence, military service, community service in emergencies. 173 state parties. Non-derogable right under Article 4(2).",
        "source": "United Nations, ICCPR (1966), entered into force 1976",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ICESCR Articles 6-8 — Right to Work and Just Conditions",
        "summary": "International Covenant on Economic, Social and Cultural Rights: Article 6 (right to work, freely chosen), Article 7 (just and favourable conditions including fair wages, safe working conditions, equal opportunity, rest and leisure), Article 8 (right to form and join trade unions, right to strike). 171 state parties. CESCR General Comment 18 (2005) elaborates that work must be freely chosen or accepted, not forced.",
        "source": "United Nations, ICESCR (1966), entered into force 1976",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "CEDAW — Convention on the Elimination of All Forms of Discrimination Against Women (1979)",
        "summary": "Article 6 requires states to suppress all forms of trafficking in women and exploitation of prostitution of women. General Recommendation 26 (2008) specifically addresses women migrant workers: pre-departure protections, transit protections, and destination country protections. Identifies domestic workers, entertainment workers, and mail-order brides as particularly vulnerable. 189 state parties. Optional Protocol allows individual complaints.",
        "source": "United Nations, CEDAW (1979)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "CRC — Convention on the Rights of the Child (1989)",
        "summary": "Article 32: right to protection from economic exploitation and harmful work. Article 34: protection from sexual exploitation. Article 35: states shall prevent abduction, sale, or traffic in children. Article 36: protection from all forms of exploitation. Optional Protocol on the Sale of Children (2000) criminalizes sale, child prostitution, and child pornography. 196 state parties (universal ratification). CRC Committee monitors implementation.",
        "source": "United Nations, CRC (1989)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "CRC Optional Protocol on the Sale of Children, Child Prostitution and Child Pornography (2000)",
        "summary": "Supplements CRC Articles 34-35. Requires states to criminalize: sale of children (for sexual exploitation, organ transfer, or forced labor), child prostitution, and child pornography. Covers acts committed domestically or transnationally. Requires extradition for these offenses. Mandates protection and support for child victims in criminal proceedings. 178 state parties.",
        "source": "United Nations, A/RES/54/263 (2000)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ICRMW — International Convention on the Protection of the Rights of All Migrant Workers and Members of Their Families (1990)",
        "summary": "Most comprehensive treaty on migrant worker rights. Covers: freedom of movement, prohibition of forced labor, equal treatment in employment, right to transfer earnings, right to information about conditions of admission and employment, protection against arbitrary expulsion, right to recourse to courts. Only 58 ratifications as of 2024 — NO major destination country has ratified (not US, EU, GCC, UK, Australia, Canada, Japan). Significant ratification gap undermines effectiveness.",
        "source": "United Nations, A/RES/45/158 (1990), entered into force 2003",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Supplementary Convention on the Abolition of Slavery, the Slave Trade, and Institutions and Practices Similar to Slavery (1956)",
        "summary": "Expands 1926 Slavery Convention to cover: debt bondage (pledging personal services as security for debt where service value is not applied to liquidating the debt), serfdom, forced marriage for payment, and child delivery for exploitation. First international instrument to explicitly define and prohibit debt bondage. 124 state parties. Foundational treaty for modern anti-trafficking framework.",
        "source": "United Nations, 1956",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Slavery Convention (1926) and 1953 Amending Protocol",
        "summary": "First international treaty prohibiting slavery. Defines slavery as 'the status or condition of a person over whom any or all of the powers attaching to the right of ownership are exercised.' Requires states to prevent and suppress the slave trade and to bring about the complete abolition of slavery. 1953 Protocol transferred functions from League of Nations to United Nations. 99 state parties.",
        "source": "United Nations / League of Nations, 1926 / 1953",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Global Compact for Safe, Orderly and Regular Migration (GCM, 2018)",
        "summary": "Non-binding framework adopted by 152 UN member states (US, Hungary, and others voted against). 23 objectives including: minimize factors that compel migration, ensure migrants have proof of legal identity, enhance availability of regular migration pathways, facilitate fair and ethical recruitment, address vulnerabilities in migration. Objective 6 specifically addresses recruitment fees (employer-pays principle). Objective 10 addresses trafficking. Implementation reviewed through International Migration Review Forum.",
        "source": "United Nations, A/RES/73/195 (2018)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Guiding Principles on Business and Human Rights (UNGPs, 2011)",
        "summary": "Endorsed by UN Human Rights Council. Three-pillar framework: (1) State duty to protect human rights, (2) Corporate responsibility to respect human rights, (3) Access to remedy for victims. Applies to all businesses including in supply chains. Requires human rights due diligence: assess impacts, integrate findings, track response, communicate. Foundational document for mandatory due diligence legislation (EU CSDDD, German Supply Chain Act, French Duty of Vigilance). Not legally binding but increasingly referenced in national legislation and court rulings.",
        "source": "United Nations, A/HRC/RES/17/4 (2011) — John Ruggie",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Global Plan of Action to Combat Trafficking in Persons (2010, reviewed 2017)",
        "summary": "General Assembly resolution establishing UN-wide framework against trafficking. Creates UN Voluntary Trust Fund for Victims of Trafficking. Calls for: national action plans, national rapporteurs, victim identification procedures, non-criminalization of victims, demand reduction. Reviews trafficking as development issue (SDG linkage). 2017 political declaration reaffirmed commitments. Trust Fund has supported 200+ projects in 60 countries.",
        "source": "United Nations, A/RES/64/293 (2010)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Sustainable Development Goals — Targets 8.7 and 16.2 on Modern Slavery and Child Exploitation",
        "summary": "SDG Target 8.7: 'Take immediate and effective measures to eradicate forced labour, end modern slavery and human trafficking, and secure the prohibition and elimination of the worst forms of child labour by 2025.' SDG Target 16.2: 'End abuse, exploitation, trafficking and all forms of violence against and torture of children.' Alliance 8.7 coordinates global action. Progress off-track: modern slavery increased 10 million (2016-2021). Child labor target 8.7 will not be met by 2025.",
        "source": "United Nations, A/RES/70/1 (2015)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Voluntary Principles on Security and Human Rights (2000)",
        "summary": "Multi-stakeholder initiative for extractive and energy sectors. Principles guide companies in maintaining security while respecting human rights. Relevant to trafficking through: private security force oversight, community impact assessment, and grievance mechanisms for affected communities including migrant workers. 13 governments, 40+ companies, 14+ NGOs participate. Voluntary but increasingly referenced in project finance standards.",
        "source": "Voluntary Principles Initiative, 2000 (updated 2023)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UDHR Article 4 — Prohibition of Slavery and Servitude",
        "summary": "Universal Declaration of Human Rights Article 4: 'No one shall be held in slavery or servitude; slavery and the slave trade shall be prohibited in all their forms.' Article 23: right to work, free choice of employment, just and favourable conditions, and equal pay. Article 24: right to rest and leisure. While non-binding, UDHR is accepted as customary international law and the prohibition of slavery is a jus cogens norm (non-derogable).",
        "source": "United Nations, A/RES/217(III) (1948)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Convention on the Rights of Persons with Disabilities — Article 16 and 27 (2006)",
        "summary": "Article 16: freedom from exploitation, violence, and abuse, including gender-based aspects. Article 27: right to work on an equal basis. Persons with disabilities disproportionately vulnerable to trafficking and forced labor. CRPD Committee has addressed: institutionalization as form of forced labor, sheltered workshops paying below minimum wage, and exploitation of persons with intellectual disabilities. 186 state parties.",
        "source": "United Nations, CRPD (2006)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Convention Relating to the Status of Refugees (1951) and 1967 Protocol — Intersection with Trafficking",
        "summary": "While focused on refugees, directly relevant to trafficking: asylum seekers trafficked en route, refugees in camps vulnerable to exploitation, and trafficking victims may qualify for refugee status (UNHCR Guidelines on International Protection: trafficking as persecution). 1967 Protocol removes geographic and temporal limitations. 149 state parties to Convention, 146 to Protocol. Non-refoulement principle protects trafficking victims from return to countries where they face trafficking risk.",
        "source": "United Nations, 1951 Convention / 1967 Protocol",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Principles and Guidelines on Human Rights and Human Trafficking (2002)",
        "summary": "OHCHR-developed recommended principles. Key principles: primacy of human rights (over immigration enforcement), non-criminalization of trafficked persons, non-detention of trafficking victims, right to adequate remedy, state responsibility for failure to protect. 17 guidelines covering: identification, protection, criminalization, prevention, and cooperation. Referenced by courts and national action plans worldwide. Non-binding but highly authoritative.",
        "source": "OHCHR, E/2002/68/Add.1 (2002)",
    },
    # ══════════════════════════════════════════════════════════════════════
    # ILO INSTRUMENTS
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 29 — Forced Labour Convention (1930)",
        "summary": "First binding international instrument on forced labor. Defines forced or compulsory labour as 'all work or service which is exacted from any person under the menace of any penalty and for which the said person has not offered himself voluntarily.' Excludes: military service, civic obligations, prison labor, emergency work, minor communal services. 179 ratifications. One of ILO's most ratified conventions. Supplemented by Protocol of 2014 (P029).",
        "source": "ILO, C029 (1930)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Protocol of 2014 to the Forced Labour Convention (P029)",
        "summary": "Supplements C029 with modern obligations: (1) Prevention: national policy and plan of action, educate vulnerable groups, due diligence in supply chains, protect migrants during recruitment. (2) Protection: identify and release victims, provide support and remedies. (3) Remedies: ensure victims have access to compensation regardless of immigration status. Entered into force 9 November 2016. 67 ratifications as of 2024. Accompanied by ILO Recommendation 203.",
        "source": "ILO, P029 (2014)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 105 — Abolition of Forced Labour Convention (1957)",
        "summary": "Prohibits forced labor in five specific contexts: (a) political coercion or education, (b) economic development mobilization, (c) labour discipline, (d) punishment for strikes, (e) racial, social, national or religious discrimination. 176 ratifications. Complements C029: while C029 addresses forced labor generally, C105 targets state-imposed forced labor for specific purposes. China ratified in 2022 (significant given Xinjiang concerns).",
        "source": "ILO, C105 (1957)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 97 — Migration for Employment Convention (Revised) (1949)",
        "summary": "Requires states to: maintain free public employment services for migrant workers, provide accurate information on migration conditions, ensure adequate medical attention during transit, apply no less favorable treatment than nationals regarding: remuneration, working hours, overtime, holidays, minimum age, apprenticeship, trade union membership, social security, legal proceedings. 50 ratifications. Key gap: not ratified by GCC states, Malaysia, Thailand, or most Asian destination countries.",
        "source": "ILO, C097 (1949)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 143 — Migrant Workers (Supplementary Provisions) Convention (1975)",
        "summary": "Part I: suppression of clandestine migration and illegal employment of migrants. Part II: equality of opportunity and treatment for migrant workers and their families in: employment, trade union activities, cultural rights, individual and collective freedoms. Requires states to detect illegal employment and prosecute organizers of illicit migration. 25 ratifications (low uptake). Considered aspirational standard for migration governance.",
        "source": "ILO, C143 (1975)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 181 — Private Employment Agencies Convention (1997)",
        "summary": "Regulates operation of private employment agencies. Article 7(1): agencies shall not charge directly or indirectly, in whole or in part, any fees or costs to workers. Article 7(2) allows exceptions for certain worker categories after consultation with social partners. Requires adequate protection regarding: minimum wages, working time, occupational safety, social security, maternity protection. 37 ratifications. Foundation for 'employer pays' principle. Many Gulf and Asian states have not ratified.",
        "source": "ILO, C181 (1997)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 189 — Domestic Workers Convention (2011)",
        "summary": "First binding instrument specifically for domestic workers. Requires: written contracts, working time limits, minimum wage coverage, weekly rest (at least 24 consecutive hours), annual leave, freedom to reach agreement on live-in arrangements, protection from abuse and harassment, freedom to keep identity documents, regulation of private employment agencies. 36 ratifications. Notable non-ratifiers: all GCC states, Singapore, Hong Kong, Malaysia, Lebanon.",
        "source": "ILO, C189 (2011)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 182 — Worst Forms of Child Labour Convention (1999)",
        "summary": "Requires immediate prohibition and elimination of: slavery, trafficking, debt bondage, serfdom, forced recruitment for armed conflict, use of children for prostitution or pornography, use for illicit activities (drug trafficking), and hazardous work. Universal ratification achieved in 2020 (187 countries) — first ILO convention to achieve this. Accompanied by Recommendation 190 listing hazardous work categories.",
        "source": "ILO, C182 (1999)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 138 — Minimum Age Convention (1973)",
        "summary": "Sets minimum age for employment: not less than age of compulsory schooling and not less than 15 years (13 for light work). Developing countries may set at 14 (12 for light work). Hazardous work: minimum age 18. 175 ratifications. Countries must specify minimum age at ratification. Critical for preventing child trafficking and forced child labor. Accompanied by Recommendation 146.",
        "source": "ILO, C138 (1973)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 188 — Work in Fishing Convention (2007)",
        "summary": "Addresses forced labor on fishing vessels. Minimum requirements for: work agreements, minimum age (16, or 18 for hazardous work), medical certification, manning and hours of rest, crew list, repatriation, recruitment agencies, payment of fishers, accommodation and food, medical care, occupational safety, social security. 21 ratifications (critically low for sector with widespread forced labor). Thailand ratified in 2019 post-EU yellow card pressure.",
        "source": "ILO, C188 (2007)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Recommendation 203 — Forced Labour (Supplementary Measures) Recommendation (2014)",
        "summary": "Accompanies P029. Recommends: national action plans, labor inspection strengthening, due diligence for businesses, protection of workers (especially migrants) from fraudulent recruitment, access to education and training for victims, legal aid regardless of immigration status, compensation through judicial or administrative mechanisms, establishment of compensation funds, simplified procedures for victim claims, non-prosecution of victims for offenses committed as direct consequence of trafficking.",
        "source": "ILO, R203 (2014)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Declaration on Fundamental Principles and Rights at Work (1998, amended 2022)",
        "summary": "Declares all ILO member states are bound by fundamental principles regardless of ratification: (a) freedom of association and collective bargaining, (b) elimination of forced or compulsory labour, (c) abolition of child labour, (d) elimination of discrimination. 2022 amendment added: (e) safe and healthy working environment. Mandatory obligations for all 187 ILO member states. Provides basis for ILO supervisory mechanisms including article 26 complaints.",
        "source": "ILO, 1998 (amended 2022)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO General Principles and Operational Guidelines for Fair Recruitment and Definition of Recruitment Fees (2019)",
        "summary": "Non-binding guidelines establishing: no recruitment fees or related costs should be charged to workers. Defines recruitment fees comprehensively: payments for recruitment services, referral fees, payments made during the hiring process, and costs related to medical exams, skills testing, training, documentation, travel, and accommodation. Covers all workers including migrant workers. Adopted after tripartite consultations. Referenced in ILO IRIS standard and national legislations.",
        "source": "ILO, 2019",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Multilateral Framework on Labour Migration (2006)",
        "summary": "Non-binding principles and guidelines organized into nine themes: decent work for all, governance of labour migration, international cooperation, protection of migrant workers, prevention and protection against abusive migration practices, social integration, migration and development, promoting return and reintegration, and rights-based approach. First comprehensive ILO framework specifically on labor migration. Referenced in UN GCM and national migration policies.",
        "source": "ILO, 2006",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Indicators of Forced Labour (2012)",
        "summary": "Operational tool defining 11 indicators of forced labor: (1) abuse of vulnerability, (2) deception, (3) restriction of movement, (4) isolation, (5) physical and sexual violence, (6) intimidation and threats, (7) retention of identity documents, (8) withholding of wages, (9) debt bondage, (10) abusive working and living conditions, (11) excessive overtime. Presence of one strong indicator or several weaker indicators may indicate forced labor. Used by labor inspectors, law enforcement, researchers, and companies for supply chain due diligence. Foundation for this testing framework.",
        "source": "ILO Special Action Programme to Combat Forced Labour, 2012",
    },
    # ══════════════════════════════════════════════════════════════════════
    # REGIONAL INSTRUMENTS — EUROPE
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "EU",
        "title": "EU Directive 2011/36/EU — Preventing and Combating Trafficking in Human Beings",
        "summary": "Comprehensive EU anti-trafficking directive. Criminalizes trafficking with minimum penalties: 5 years imprisonment (10 years for aggravated circumstances). Requires victim identification, support, and protection. Article 8: non-prosecution of victims. Article 11: victim assistance regardless of cooperation with prosecution. Establishes EU Anti-Trafficking Coordinator. Requires National Rapporteurs. All 27 EU member states must transpose. Replaced 2002 Framework Decision.",
        "source": "European Union, 2011/36/EU (2011)",
    },
    {
        "type": "law",
        "jurisdiction": "EU",
        "title": "EU Directive 2009/52/EC — Employers Sanctions Directive",
        "summary": "Prohibits employment of illegally staying third-country nationals. Requires employers to: verify right to work, notify authorities of hiring. Penalties for employers: fines, criminal sanctions for severe cases. Article 6(1): employers liable for wage payments including back pay. Article 13: mechanism for migrant workers to lodge complaints and receive back pay regardless of immigration status. Key for addressing demand-side of trafficking.",
        "source": "European Union, 2009/52/EC (2009)",
    },
    {
        "type": "law",
        "jurisdiction": "EU",
        "title": "EU Corporate Sustainability Due Diligence Directive (CSDDD, 2024)",
        "summary": "Requires large EU companies and non-EU companies with significant EU turnover to: identify, prevent, mitigate, and account for adverse human rights and environmental impacts in their operations and supply chains. Covers: forced labor, child labor, trafficking, freedom of association. Companies must establish complaints mechanisms and develop transition plans. Civil liability for failure to exercise due diligence. Phase-in: 2027-2029. Covers estimated 13,000 EU and 4,000 non-EU companies.",
        "source": "European Union, CSDDD (2024)",
    },
    {
        "type": "law",
        "jurisdiction": "EU",
        "title": "EU Forced Labour Regulation (2024)",
        "summary": "Prohibits placement and making available on the EU market of products made with forced labor. Applies to domestic production and imports. Competent authorities can investigate and issue orders to withdraw products. Risk-based approach: focus on high-risk sectors, geographies, and product types. Database of forced-labor risk areas and products to be established. Complements CSDDD by addressing product level rather than corporate level. Modeled on US UFLPA approach.",
        "source": "European Union, 2024",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Council of Europe Convention on Action against Trafficking in Human Beings (Warsaw Convention, 2005)",
        "summary": "Strongest regional anti-trafficking instrument. Key provisions: victim identification through National Referral Mechanism (Article 10), recovery and reflection period of at least 30 days (Article 13), residence permit for victims (Article 14), compensation including from state fund (Article 15), non-punishment of victims (Article 26), independent monitoring by GRETA (Group of Experts on Action against Trafficking). 47 state parties (all CoE members plus Belarus). GRETA conducts country evaluation rounds every 4-5 years.",
        "source": "Council of Europe, CETS 197 (2005)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "European Convention on Human Rights — Article 4: Prohibition of Slavery and Forced Labour",
        "summary": "Article 4(1): No one shall be held in slavery or servitude. Article 4(2): No one shall be required to perform forced or compulsory labour. Absolute prohibition (non-derogable under Article 15). European Court of Human Rights landmark cases: Siliadin v. France (2005) — domestic servitude, Rantsev v. Cyprus and Russia (2010) — trafficking as Article 4 violation, Chowdury v. Greece (2017) — forced labor on strawberry farm. Positive obligations on states to prevent, investigate, and punish.",
        "source": "Council of Europe, ECHR Article 4 (1950)",
    },
    {
        "type": "law",
        "jurisdiction": "EU",
        "title": "EU Seasonal Workers Directive 2014/36/EU",
        "summary": "Establishes conditions for entry and stay of third-country seasonal workers. Maximum stay: 5-9 months per 12-month period. Requires: written work contract, adequate accommodation, equal treatment with nationals in working conditions. Workers may change employer during authorized stay. Prevents exploitation by ensuring legal status is not solely dependent on single employer. 25 EU member states transposed (Denmark and Ireland opt-out).",
        "source": "European Union, 2014/36/EU (2014)",
    },
    {
        "type": "law",
        "jurisdiction": "EU",
        "title": "EU Temporary Protection Directive 2001/55/EC — Application to Ukrainian Refugees (2022)",
        "summary": "Activated for first time in March 2022 for Ukrainians fleeing Russian invasion. Provides: residence permits, access to employment, housing, social welfare, and education. Prevents exploitation by ensuring legal status and work rights. Lessons for trafficking prevention: legal status reduces vulnerability, but rapid displacement creates new risks (online exploitation, labor trafficking of refugees). 4 million+ Ukrainians received temporary protection. Extended to March 2025.",
        "source": "European Union, Council Implementing Decision 2022/382",
    },
    {
        "type": "law",
        "jurisdiction": "EU",
        "title": "EU Victims' Rights Directive 2012/29/EU — Application to Trafficking Victims",
        "summary": "Establishes minimum rights for all crime victims in EU. Relevant for trafficking: right to information, right to interpretation and translation, right to access victim support services, right to be heard, rights in restorative justice, right to legal aid, right to compensation, right to protection including privacy. Trafficking victims recognized as particularly vulnerable requiring enhanced measures. Individual needs assessment mandatory.",
        "source": "European Union, 2012/29/EU (2012)",
    },
    # ══════════════════════════════════════════════════════════════════════
    # REGIONAL INSTRUMENTS — ASIA-PACIFIC
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ASEAN Convention Against Trafficking in Persons, Especially Women and Children (ACTIP, 2015)",
        "summary": "First legally binding ASEAN instrument on trafficking. Criminalizes all forms of trafficking aligned with Palermo Protocol definition. Requires victim protection: shelter, medical care, legal assistance. Promotes cross-border cooperation: joint investigation teams, mutual legal assistance, extradition. Establishes SOMTC (Senior Officials Meeting on Transnational Crime) as coordination body. Ratified by all 10 ASEAN member states. Implementation varies significantly.",
        "source": "ASEAN, ACTIP (2015), entered into force 2017",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ASEAN Declaration on the Protection and Promotion of the Rights of Migrant Workers (Cebu Declaration, 2007)",
        "summary": "Non-binding declaration. Obligations of receiving states: promote fair and appropriate working conditions, provide adequate access to legal system, facilitate exercise of consular functions. Obligations of sending states: regulate and accredit recruitment agencies, establish mechanisms for eliminating excessive recruitment fees, ensure migrant workers understand terms of employment. ASEAN Committee on Migrant Workers established but progress slow.",
        "source": "ASEAN, Cebu Declaration (2007)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ASEAN Consensus on the Protection and Promotion of the Rights of Migrant Workers (2017)",
        "summary": "Attempts to operationalize Cebu Declaration. Non-binding consensus document (not treaty). Covers: fundamental rights, specific rights during employment, obligation of sending states, obligation of receiving states, and commitments on data sharing. Key weakness: language uses 'should' not 'shall,' no enforcement mechanism, and allows states to apply provisions 'in accordance with national laws.' Criticized by civil society as inadequate.",
        "source": "ASEAN, 2017",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Bali Process on People Smuggling, Trafficking in Persons and Related Transnational Crime (2002)",
        "summary": "Regional forum co-chaired by Australia and Indonesia. 49 member states (includes all ASEAN, Oceania, Middle East, South Asia). Develops policy frameworks for: combating smuggling and trafficking, managing irregular migration, expanding legal migration pathways. Bali Process Government and Business Forum (2017) engages private sector. Voluntary and non-binding but influential in shaping regional cooperation on trafficking. Bali Declaration (2016) recognized trafficking-migration nexus.",
        "source": "Bali Process, 2002 (ongoing)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Colombo Process — Ministerial Consultations on Overseas Employment and Contractual Labour for Countries of Origin in Asia (2003)",
        "summary": "Forum of 12 Asian labor-sending countries: Afghanistan, Bangladesh, Cambodia, China, India, Indonesia, Nepal, Pakistan, Philippines, Sri Lanka, Thailand, Vietnam. Focus: protecting overseas workers, optimizing development benefits of migration, promoting bilateral and multilateral cooperation. Key outputs: thematic area working groups on: recruitment integrity, skills and qualifications, pre-departure orientation, and remittances. Non-binding but shapes national policies in member states.",
        "source": "Colombo Process, 2003 (ongoing)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Abu Dhabi Dialogue (ADD) — Ministerial Consultations on Contractual Labour Mobility (2008)",
        "summary": "Unique forum linking Asian origin countries (Colombo Process members) with Gulf and Asian destination countries (Bahrain, Kuwait, Malaysia, Oman, Qatar, Saudi Arabia, Singapore, UAE, Yemen). Focus: temporary contractual labor. Key themes: partnerships between origin and destination, knowledge sharing on labor market needs, preventing illegal recruitment, effective pre-departure orientation, and remittance facilitation. Non-binding but provides rare destination-origin dialogue platform.",
        "source": "Abu Dhabi Dialogue, 2008 (ongoing)",
    },
    # ══════════════════════════════════════════════════════════════════════
    # REGIONAL INSTRUMENTS — SOUTH ASIA
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "SAARC Convention on Preventing and Combating Trafficking in Women and Children for Prostitution (2002)",
        "summary": "Regional convention among 8 South Asian states: Afghanistan, Bangladesh, Bhutan, India, Maldives, Nepal, Pakistan, Sri Lanka. Defines trafficking aligned with Palermo Protocol (but limited to 'prostitution' purpose). Requires criminalization, mutual legal assistance, victim repatriation, and rehabilitative care. Key weakness: narrow definition (prostitution only) excludes labor trafficking. Implementation uneven. Entered into force 2005.",
        "source": "SAARC, 2002",
    },
    # ══════════════════════════════════════════════════════════════════════
    # REGIONAL INSTRUMENTS — AFRICA
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "African Charter on Human and Peoples' Rights (Banjul Charter, 1981)",
        "summary": "Article 5: prohibition of slavery, slave trade, torture, cruel treatment, and degrading punishment. Article 6: right to liberty and security of person. Article 15: right to work under equitable and satisfactory conditions. Enforced by African Court on Human and Peoples' Rights and African Commission. Commission has addressed: slavery in Mauritania, child trafficking in West Africa, migrant worker exploitation in Libya. 54 state parties (all AU members). Protocol on Women's Rights (Maputo Protocol, 2003) strengthens protections.",
        "source": "African Union / OAU, 1981",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "AU Ouagadougou Action Plan to Combat Trafficking in Human Beings, Especially Women and Children (2006)",
        "summary": "Comprehensive AU action plan addressing: legislative framework harmonization, prevention (awareness, root causes), protection (victim identification, assistance, repatriation), prosecution (law enforcement training, mutual legal assistance), and cooperation (regional networks, data sharing). Established AU.COMMIT campaign. Implementation reviewed by AU Commission. Key challenge: AU lacks enforcement mechanism comparable to GRETA in Europe. Progress uneven across 55 member states.",
        "source": "African Union, 2006",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ECOWAS Initial Plan of Action against Trafficking in Persons (2002-2003)",
        "summary": "West African regional plan addressing: child trafficking for labor and sexual exploitation, trafficking of women, internal and cross-border trafficking. Established ECOWAS Joint Border Patrols. Created model anti-trafficking legislation adopted by 13 of 15 ECOWAS states. Focuses on: awareness campaigns, border management, victim return and reintegration, and law enforcement cooperation. Updated through subsequent ECOWAS declarations (2006, 2010).",
        "source": "ECOWAS, 2002",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "African Union Protocol to the African Charter on Human and Peoples' Rights on the Rights of Women in Africa (Maputo Protocol, 2003)",
        "summary": "Article 4: right to life, integrity, and security including protection from trafficking. Article 13: economic and social welfare rights including equal pay. Article 24: right to healthy and sustainable environment. Specifically addresses: forced marriage, widow inheritance, and female genital mutilation as forms of exploitation. 44 ratifications. Relevant to trafficking as it addresses gender-specific exploitation patterns prevalent in African migration corridors.",
        "source": "African Union, Maputo Protocol (2003)",
    },
    # ══════════════════════════════════════════════════════════════════════
    # REGIONAL INSTRUMENTS — MIDDLE EAST
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Arab Charter on Human Rights (2004, entered into force 2008)",
        "summary": "Article 10: prohibition of slavery, slave trade, forced labor, and trafficking for prostitution or exploitation. Article 34: right to work and just working conditions. Article 38: right to adequate standard of living. 18 ratifications (including Iraq, Jordan, Algeria, Libya, Syria, UAE, Bahrain, Qatar, Saudi Arabia, Kuwait). Key limitation: permits broad restrictions based on national law and public order. Enforced by Arab Human Rights Committee through state reporting. No individual complaint mechanism.",
        "source": "League of Arab States, 2004",
    },
    # ══════════════════════════════════════════════════════════════════════
    # REGIONAL INSTRUMENTS — AMERICAS
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "American Convention on Human Rights (Pact of San Jose, 1969) — Article 6: Freedom from Slavery",
        "summary": "Article 6(1): No one shall be subject to slavery or involuntary servitude. Article 6(2): No one shall be required to perform forced or compulsory labor. Inter-American Court landmark cases: Hacienda Brasil Verde Workers v. Brazil (2016) — first international court ruling finding a state liable for modern slavery. Court ordered: compensation, investigation, and policy changes addressing bonded labor in Brazilian agriculture. 23 state parties.",
        "source": "OAS, American Convention (1969)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Inter-American Convention on International Traffic in Minors (1994)",
        "summary": "OAS convention addressing trafficking of children across international borders. Covers: abduction, removal, retention, or attempted retention of minors for unlawful purposes. Requires: international cooperation, prompt return of minors, establishment of central authorities. 14 ratifications. Predates Palermo Protocol; narrower in scope. Supplemented by national anti-trafficking laws in OAS member states.",
        "source": "OAS, 1994",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "OAS Work Plan to Combat Trafficking in Persons in the Western Hemisphere (2015-2018, renewed)",
        "summary": "OAS action plan addressing trafficking across the Americas. Key pillars: prevention, prosecution, victim protection, and partnerships. Establishes: OAS Anti-Trafficking Section, technical assistance programs, and model legislation. Regional challenges: Northern Triangle (Guatemala, Honduras, El Salvador) as source region, US and Mexico as transit/destination, intra-Caribbean trafficking. Coordinates with UNHCR on Venezuelan displacement (7 million+ displaced, trafficking risk).",
        "source": "OAS, 2015 (updated periodically)",
    },
    # ══════════════════════════════════════════════════════════════════════
    # SOFT LAW AND GUIDELINES
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Dhaka Principles for Migration with Dignity (2012)",
        "summary": "10 principles for ethical recruitment developed by Institute for Human Rights and Business after multi-stakeholder consultation. Principles: (1) No fees charged to workers, (2) Clear terms in accessible language, (3) Retention of identity documents by worker, (4) Written employment contract, (5) Wages paid regularly and directly, (6) Right to free movement and communication, (7) Safe working conditions, (8) Right to join trade unions, (9) No retaliation for complaints, (10) Safe and timely return. Endorsed by 50+ companies and organizations. Referenced in corporate supply chain standards.",
        "source": "Institute for Human Rights and Business, Dhaka Principles (2012)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Santa Marta Group — Vatican-Led Anti-Trafficking Initiative (2014)",
        "summary": "Coalition of international police chiefs and bishops working together to combat human trafficking and modern slavery. Established following conference at Vatican's Pontifical Academy of Sciences. Members: 30+ national police forces and Catholic bishops' conferences. Promotes: law enforcement cooperation, victim-centered approach, awareness raising through parish networks. Pope Francis declared human trafficking a 'crime against humanity.' Practical output: training programs for police and community leaders.",
        "source": "Santa Marta Group / Vatican, 2014",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Bali Declaration on People Smuggling, Trafficking in Persons, and Related Transnational Crime (2016)",
        "summary": "Adopted by 45 countries at 6th Bali Process Ministerial Conference. Recognized trafficking-migration nexus. Key commitments: apply non-punishment principle for trafficking victims, strengthen labor migration governance, expand legal pathways to reduce smuggling demand, enhance cooperation on border management, address root causes including poverty and conflict. First Bali Process declaration to explicitly link migration governance with anti-trafficking efforts.",
        "source": "Bali Process, 2016",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "ILO Fair Recruitment Initiative (FRI) — Phase II (2021-2025)",
        "summary": "Global program to: promote fair recruitment practices, prevent trafficking and forced labor, and reduce costs of labor migration. Four components: (1) enhance global knowledge on recruitment, (2) improve laws and enforcement, (3) promote fair business practices, (4) empower workers. Operates in 12 countries: Jordan, Lebanon, Nepal, Philippines, Madagascar, Kenya, Ethiopia, Tunisia, Mexico, Honduras, Guatemala, Paraguay. Budget: USD 26 million. Key output: definition of recruitment fees and related costs adopted by ILO Governing Body (2019).",
        "source": "ILO Fair Recruitment Initiative, 2021",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "OECD Guidelines for Multinational Enterprises on Responsible Business Conduct (updated 2023)",
        "summary": "Recommendations by 51 adhering governments to multinational enterprises. Chapter IV (human rights): enterprises should respect human rights, carry out due diligence, address adverse impacts. Chapter V (employment): enterprises should not use forced labor, respect minimum age, ensure occupational safety. National Contact Points (NCPs) handle complaints (specific instances). Updated 2023 to strengthen: due diligence expectations, climate/environment provisions, technology impacts. Referenced in national legislation and corporate policies.",
        "source": "OECD, 2023 update (original 1976)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "OECD Due Diligence Guidance for Responsible Supply Chains in the Garment and Footwear Sector (2017)",
        "summary": "Sector-specific guidance for garment industry. Recommends due diligence process: embed responsible conduct in policies, identify adverse impacts (forced labor, child labor, excessive overtime), cease/prevent/mitigate impacts, track implementation, communicate. Covers: direct suppliers and sub-suppliers. Addresses: homeworkers, migrant workers, temporary workers. Developed after Rana Plaza disaster (2013). Used by major brands for supply chain auditing frameworks.",
        "source": "OECD, 2017",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "UN Global Compact — Ten Principles on Human Rights and Labour (2000)",
        "summary": "World's largest corporate sustainability initiative. 15,000+ companies in 160+ countries. Principles 1-2: support and respect human rights, ensure non-complicity. Principles 3-6: uphold freedom of association, eliminate forced labor, abolish child labor, eliminate discrimination. Companies must submit annual Communication on Progress. Delisted for non-reporting. Criticism: weak enforcement, 'bluewashing' concerns. Labour Principles Platform provides implementation guidance for supply chains.",
        "source": "United Nations Global Compact, 2000",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Employer Pays Principle — Consumer Goods Forum Resolution (2016)",
        "summary": "Global industry body (400+ consumer goods companies, USD 3.5 trillion combined revenue) adopted resolution: every worker should have freedom of movement, no worker should pay for a job, no worker should be indebted or coerced to work. Priority Industry Principles: every worker should have freedom of movement, no worker should pay for a job, no worker should be indebted or coerced. Members include: Walmart, Nestle, Unilever, P&G, Coca-Cola. Implementation: requiring supplier compliance, recruitment fee reimbursement programs.",
        "source": "Consumer Goods Forum, 2016",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Responsible Business Alliance (RBA) Code of Conduct — Forced Labor Provisions (updated 2024)",
        "summary": "Industry standard for electronics and technology supply chains. 200+ member companies (Apple, Microsoft, Samsung, Intel, HP). Code Section A1 (Freely Chosen Employment): no forced, bonded, indentured labor; no unreasonable restrictions on movement; workers retain identity documents; workers free to leave; recruitment fees paid by employer, not worker. Members must audit suppliers against code. Non-compliance can result in probation or membership revocation. Most influential private-sector anti-forced-labor standard in electronics industry.",
        "source": "Responsible Business Alliance, Code of Conduct v8.0 (2024)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "International Accord for Health and Safety in the Textile and Garment Industry (2021)",
        "summary": "Successor to Bangladesh Accord (2013, post-Rana Plaza disaster). Legally binding agreement between global trade unions and brands. Covers: independent safety inspections, worker training, complaint mechanisms, and binding arbitration. Expanded beyond Bangladesh to Pakistan (2023). 190+ brand signatories. Key innovation: legally enforceable brand obligations for supply chain safety. Relevant to trafficking prevention: safe working conditions reduce worker vulnerability and address ILO forced labor indicator 10 (abusive working conditions).",
        "source": "International Accord Foundation, 2021",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Interfaith Declaration against Modern Slavery — Joint Declaration of Religious Leaders (2014)",
        "summary": "Signed at Vatican by leaders of Catholic, Anglican, Orthodox Christian, Jewish, Muslim, Hindu, and Buddhist faiths. Declared modern slavery and human trafficking crimes against humanity. Committed faith communities to: spiritual and practical action, awareness raising, supporting survivors, addressing root causes. Led to establishment of Global Freedom Network (now integrated into Walk Free). Mobilizes 2 billion+ faith adherents worldwide for anti-slavery action.",
        "source": "Pontifical Academy of Sciences, Vatican, 2014",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Budapest Process — Intergovernmental Dialogue on Migration and Asylum (1993)",
        "summary": "Consultative forum of 50+ governments and 10+ international organizations. Silk Routes Region focus: Central Asia, South Caucasus, Afghanistan, Pakistan, Iran, Iraq. Working groups address: irregular migration, trafficking and smuggling, legal migration, asylum, and migration and development. Developed Istanbul Ministerial Declaration (2013) calling for cooperation on trafficking prevention along Silk Route migration corridors. Funded by EU and participating governments.",
        "source": "Budapest Process, 1993 (ongoing)",
    },
    # ══════════════════════════════════════════════════════════════════════
    # BILATERAL INSTRUMENTS AND FRAMEWORKS
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "bilateral_agreement",
        "jurisdiction": "international",
        "title": "Philippines-Saudi Arabia Domestic Worker Agreement (2013, revised 2017)",
        "summary": "Bilateral agreement governing deployment of Filipino domestic workers to Saudi Arabia. Key provisions: minimum salary SAR 1,500/month, employer covers visa and transportation costs, written contract in Arabic and English, worker retains passport, 24-hour rest per week, 30-day paid vacation per 2 years. Revised 2017 to strengthen: insurance coverage, dispute resolution, and repatriation provisions. Enforcement challenges: many workers employed outside formal channels, no bilateral monitoring mechanism.",
        "source": "Philippines DFA / Saudi Arabia MOL, 2013/2017",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "international",
        "title": "Nepal-Qatar Bilateral Labour Agreement (2005, revised 2017)",
        "summary": "Governs deployment of Nepali workers to Qatar. 2017 revision: zero recruitment fees for workers, electronic visa processing, joint monitoring committee, mandatory contract registration. Qatar committed to: minimum wage for Nepali workers, employer-provided housing meeting standards, medical insurance. Implementation gap: sub-agents in Nepal continue charging fees outside formal channels. Joint committee has met only twice since 2017.",
        "source": "Nepal Ministry of Labour / Qatar MOL, 2005/2017",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "international",
        "title": "Indonesia-Malaysia Memorandum of Understanding on Domestic Workers (2006, suspended 2009, renewed 2011)",
        "summary": "MOU governing deployment of Indonesian domestic workers to Malaysia. Provisions: one day off per week, worker retains passport, minimum salary RM 800/month, employer covers medical expenses. Suspended by Indonesia in 2009 after high-profile abuse cases. Renewed 2011 with stronger protections. Indonesia imposed domestic worker deployment moratorium to Malaysia (2009-2011). Challenges persist: informal recruitment channels bypass MOU, enforcement by Malaysian authorities inadequate.",
        "source": "Indonesia BNP2MI / Malaysia MOHR, 2006/2011",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "international",
        "title": "Bangladesh-Saudi Arabia Labour Agreement (2008)",
        "summary": "Bilateral agreement for Bangladeshi workers in Saudi Arabia. Provisions: government-approved contract, maximum recruitment fee BDT 84,000, worker welfare fund contributions, joint monitoring committee. Reality: actual recruitment costs average BDT 400,000-600,000 (5-7x legal limit). Manpower agents operate with impunity. Joint committee inactive. Bangladesh Wage Earners Welfare Board provides some repatriation support. Agreement widely considered ineffective.",
        "source": "Bangladesh BMET / Saudi Arabia MOL, 2008",
    },
    # ══════════════════════════════════════════════════════════════════════
    # NATIONAL LEGISLATION WITH EXTRATERRITORIAL REACH
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "US",
        "title": "US Uyghur Forced Labor Prevention Act (UFLPA, 2021)",
        "summary": "Creates rebuttable presumption that all goods mined, produced, or manufactured wholly or in part in Xinjiang Uyghur Autonomous Region are made with forced labor and therefore prohibited from US import under Section 307 of Tariff Act of 1930. Importers must demonstrate with 'clear and convincing evidence' that goods are not forced-labor-produced. UFLPA Entity List identifies specific companies. CBP enforced USD 2B+ in detained shipments (2022-2024). Extraterritorial impact on global supply chains.",
        "source": "US Congress, Public Law 117-78 (2021)",
    },
    {
        "type": "law",
        "jurisdiction": "US",
        "title": "US Trafficking Victims Protection Act (TVPA) and Reauthorizations (2000-2022)",
        "summary": "Foundational US anti-trafficking law. Creates three-tier ranking system for all countries (Tier 1: full compliance, Tier 2: significant efforts, Tier 2 Watch List: insufficient efforts, Tier 3: non-compliance). Tier 3 triggers: withholding of non-humanitarian aid, opposition to multilateral development loans. Annual TIP Report covers 188 countries. TVPA also: provides T-visa for trafficking victims, criminalizes trafficking with penalties up to life imprisonment, and establishes Office to Monitor and Combat Trafficking.",
        "source": "US Congress, 22 USC 7101 et seq. (2000, reauthorized 2003, 2005, 2008, 2013, 2017, 2022)",
    },
    {
        "type": "law",
        "jurisdiction": "US",
        "title": "US Tariff Act Section 307 — Forced Labor Import Ban (1930, enforced since 2016)",
        "summary": "Prohibits importation of goods produced by forced labor. Originally contained 'consumptive demand' loophole (goods could be imported if domestic production was insufficient). Trade Facilitation and Trade Enforcement Act (2016) closed loophole. CBP issues Withhold Release Orders (WROs) and Findings. WROs issued against: Malaysian rubber gloves, Chinese tomatoes, cotton, polysilicon, and seafood from various countries. 67 active WROs as of 2024. Most impactful trade-based anti-forced-labor enforcement tool globally.",
        "source": "US Congress, 19 USC 1307 (1930, amended 2016)",
    },
    {
        "type": "law",
        "jurisdiction": "UK",
        "title": "UK Modern Slavery Act 2015 — Section 54 Transparency in Supply Chains",
        "summary": "Requires commercial organizations with annual turnover of GBP 36 million or more to prepare annual slavery and human trafficking statement. Statement must describe: steps taken to ensure slavery is not occurring in business or supply chains, or state that no such steps have been taken. No penalty for non-compliance with statement content (only for failure to publish). Government Modern Slavery Statement Registry launched 2021. Estimated 12,000 organizations in scope. Criticized for weak enforcement; many statements are boilerplate.",
        "source": "UK Parliament, Modern Slavery Act 2015, Section 54",
    },
    {
        "type": "law",
        "jurisdiction": "FR",
        "title": "France Duty of Vigilance Law (Loi de Vigilance, 2017)",
        "summary": "First mandatory human rights and environmental due diligence law. Applies to: French companies with 5,000+ employees in France or 10,000+ worldwide (approximately 300 companies). Requires: vigilance plan identifying and preventing risks in operations and supply chains. Civil liability for failure to establish or implement plan. Landmark cases filed against: TotalEnergies (climate), Casino (Amazon deforestation), Teleperformance (worker rights). Influenced EU CSDDD development.",
        "source": "French Parliament, Loi No. 2017-399 (2017)",
    },
    {
        "type": "law",
        "jurisdiction": "DE",
        "title": "Germany Supply Chain Due Diligence Act (Lieferkettensorgfaltspflichtengesetz, 2023)",
        "summary": "Requires German companies (initially 3,000+ employees, from 2024: 1,000+ employees) to: analyze human rights risks in own business and direct suppliers, establish risk management, take remedial action, establish complaints procedure, document and report. Covers: forced labor, child labor, discrimination, freedom of association, health and safety. Federal Office for Economic Affairs and Export Control (BAFA) enforces. Fines up to 2% of global turnover. Approximately 4,800 companies in scope.",
        "source": "German Bundestag, LkSG (2021, effective 2023)",
    },
    {
        "type": "law",
        "jurisdiction": "AU",
        "title": "Australia Modern Slavery Act 2018 (Cth) — Reporting Requirement",
        "summary": "Requires entities with annual consolidated revenue of AUD 100 million or more to publish annual Modern Slavery Statement. Statements describe: risks of modern slavery in operations and supply chains, actions taken to assess and address risks, effectiveness of those actions. Government-maintained register of statements. No financial penalties for non-compliance (but government named as reporting entity). Statutory review (2023) recommended: penalties for non-compliance, due diligence obligations, independent Anti-Slavery Commissioner.",
        "source": "Australian Parliament, Modern Slavery Act 2018 (Cth)",
    },
    {
        "type": "law",
        "jurisdiction": "CA",
        "title": "Canada Fighting Against Forced Labour and Child Labour in Supply Chains Act (2024)",
        "summary": "Requires Canadian entities (or those doing business in Canada) with CAD 20 million revenue, CAD 40 million assets, or 250+ employees to: report annually on steps taken to prevent and reduce forced labor and child labor in supply chains. Entities must describe: structure, supply chains, policies, due diligence, forced labor risks, remediation measures, training provided, and effectiveness assessment. Penalties: fines up to CAD 250,000 for non-compliance. Effective 1 January 2024.",
        "source": "Canadian Parliament, S.C. 2023, c. 9 (2023)",
    },
    {
        "type": "law",
        "jurisdiction": "NL",
        "title": "Netherlands Child Labour Due Diligence Act (Wet Zorgplicht Kinderarbeid, 2019)",
        "summary": "Requires all companies selling goods or services to Dutch consumers to: investigate whether child labor occurs in their supply chains, and if so, adopt a plan of action. Covers companies worldwide if they supply the Dutch market. Criminal penalties for non-compliance: fines up to EUR 870,000. Originally set to enter into force mid-2022 but postponed pending EU CSDDD. First national-level child labor due diligence law in the world. Influenced EU CSDDD development.",
        "source": "Dutch Parliament, 2019",
    },
    {
        "type": "law",
        "jurisdiction": "NO",
        "title": "Norway Transparency Act (Apenhetsloven, 2022)",
        "summary": "Requires larger enterprises (meeting 2 of 3 criteria: 50+ employees, NOK 70M revenue, NOK 35M balance sheet total) to: carry out human rights due diligence in line with OECD Guidelines, publish annual account of due diligence, respond to information requests from any person. Covers: own operations, supply chains, and business partners. Consumer Rights Authority enforces. Fines and coercive fines for non-compliance. Right to information is innovative — empowers civil society and individuals to request specific supply chain information.",
        "source": "Norwegian Parliament, 2021 (effective July 2022)",
    },
    {
        "type": "law",
        "jurisdiction": "EU",
        "title": "EU Battery Regulation 2023/1542 — Due Diligence Requirements",
        "summary": "Requires economic operators placing batteries on EU market to: establish and implement supply chain due diligence policy for raw materials (cobalt, lithium, nickel, natural graphite). Due diligence must align with OECD guidance. Addresses: forced labor, child labor, and human rights risks in mineral extraction. Applies from February 2025. Affects entire battery supply chain from mining to recycling. First EU product regulation with mandatory human rights due diligence. Relevant to cobalt mining (DRC child labor) and lithium extraction.",
        "source": "European Union, Regulation 2023/1542 (2023)",
    },
    # ══════════════════════════════════════════════════════════════════════
    # ADDITIONAL SOFT LAW AND MULTI-STAKEHOLDER INITIATIVES
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Liechtenstein Initiative — Financial Sector Commission on Modern Slavery and Human Trafficking (2019)",
        "summary": "Multi-stakeholder initiative launched by Liechtenstein, Australia, and Netherlands. Brings together financial institutions, governments, and civil society to leverage financial sector tools against trafficking. Key outputs: Blueprint for Financial Sector Action (5 goals, 40 actions). Goals include: using anti-money-laundering systems for trafficking detection, de-risking victim accounts, survivor empowerment through financial inclusion, innovation in financial sector tools. Endorsed by 40+ financial institutions.",
        "source": "Liechtenstein Initiative / UNU-CPR, 2019",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Tech Against Trafficking Initiative (2018)",
        "summary": "Coalition of technology companies working with anti-trafficking organizations. Members include: Amazon, Microsoft, Nokia, BT, Salesforce. Develops and deploys: survivor support tools, supply chain traceability, data analytics for law enforcement, recruitment monitoring platforms. Key tools: Counter-Trafficking Data Collaborative tech solutions, worker voice platforms integrated with supply chain management, satellite imagery for forced labor detection in agriculture and fishing.",
        "source": "Tech Against Trafficking / BSR, 2018 (ongoing)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Athens Ethical Principles against Human Trafficking (2006)",
        "summary": "Declaration by global business leaders committing to zero tolerance for trafficking in supply chains. Seven principles: zero tolerance policy, contribution to prevention, high standards of conduct, support for anti-trafficking campaigns, best practice sharing, supply chain accountability, and reporting trafficking suspicions. Signed by major corporations at founding. Precursor to more binding initiatives like Consumer Goods Forum principles and KnowTheChain benchmarks.",
        "source": "Athens Ethical Principles, 2006",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Worst Forms of Child Labour Recommendation 190 (ILO, 1999)",
        "summary": "Accompanies ILO Convention 182. Provides detailed guidance on hazardous work prohibited for children under 18. Lists: work exposing children to physical, psychological, or sexual abuse; work underground, underwater, at dangerous heights, or in confined spaces; work with dangerous machinery; work in unhealthy environments (chemicals, extreme temperatures, noise); work for long hours or at night. National hazardous work lists should be developed with tripartite consultation. Referenced in all major supply chain codes of conduct.",
        "source": "ILO, R190 (1999)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Joint UN Statement on Ending Forced Labour, Modern Slavery and Human Trafficking (2015)",
        "summary": "Joint commitment by ILO, OHCHR, UNODC, UNICEF, IOM, and UN Women to: coordinate UN system response to modern slavery, support SDG 8.7 implementation, align data collection and research, strengthen normative frameworks. Established Inter-Agency Coordination Group against Trafficking in Persons (ICAT). ICAT produces joint policy papers and coordinates UN participation in anti-trafficking efforts. Reduces fragmentation across multiple UN mandates on trafficking.",
        "source": "ICAT / United Nations, 2015",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "IOM International Recruitment Integrity System (IRIS) Standard (2014, updated 2022)",
        "summary": "Voluntary standard and certification scheme for ethical labor recruitment. Seven principles: respect for laws, respect for rights, transparent terms, no recruitment fees to workers, confidentiality, access to grievance mechanisms, and no discrimination. Independent compliance assessment and certification. By 2023: 35+ certified agencies across 15 countries. Agencies must demonstrate: zero fees to workers, transparent contracts, worker consent, and ongoing monitoring. Linked to ILO Fair Recruitment Initiative and General Principles on recruitment fees.",
        "source": "IOM, IRIS Standard (2014/2022)",
    },
    # ══════════════════════════════════════════════════════════════════════
    # ADDITIONAL INSTRUMENTS TO REACH 100+ FACTS
    # ══════════════════════════════════════════════════════════════════════
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 190 — Violence and Harassment Convention (2019)",
        "summary": "First international treaty recognizing the right to a world of work free from violence and harassment. Covers: workers regardless of contractual status, including interns, volunteers, jobseekers, and dismissed workers. Defines violence and harassment as behaviors causing physical, psychological, sexual, or economic harm. Addresses gender-based violence. Applies to: workplace, work-related trips, commuting, employer-provided accommodation (relevant to live-in domestic workers). 40 ratifications by 2024. Strengthens protection for migrant workers facing workplace violence.",
        "source": "ILO, C190 (2019)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 111 — Discrimination (Employment and Occupation) Convention (1958)",
        "summary": "Prohibits discrimination in employment based on: race, colour, sex, religion, political opinion, national extraction, or social origin. Requires states to declare and pursue national policy promoting equality of opportunity. 175 ratifications. Fundamental ILO convention binding on all member states under 1998 Declaration. Relevant to migrant worker exploitation: discrimination based on national origin enables differential treatment and lower protections for foreign workers in destination countries.",
        "source": "ILO, C111 (1958)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Convention against Corruption (UNCAC, 2003)",
        "summary": "Comprehensive anti-corruption treaty with 190 state parties. Relevant to trafficking: Article 9 (public procurement integrity reduces trafficking in government contracts), Article 15-16 (bribery of officials who facilitate trafficking), Article 23 (laundering proceeds of corruption and trafficking), Article 51-59 (asset recovery from trafficking profits). UNODC administers. Implementation Review Mechanism examines compliance. Corruption enables trafficking through: border official bribery, police protection of traffickers, and judicial corruption.",
        "source": "United Nations, UNCAC (2003)",
    },
    {
        "type": "law",
        "jurisdiction": "EU",
        "title": "EU Directive on Adequate Minimum Wages 2022/2041",
        "summary": "Establishes framework for adequate minimum wages across EU member states. Does not set specific amount but requires minimum wages to be adequate for decent living standards (benchmarks: 60% of median wage, 50% of average wage). Requires collective bargaining promotion (target: 80% collective bargaining coverage). Relevant to trafficking prevention: adequate minimum wages reduce economic desperation driving irregular migration, and protect migrant workers from sub-minimum wage exploitation.",
        "source": "European Union, 2022/2041 (2022)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Council of Europe Convention on the Protection of Children against Sexual Exploitation and Sexual Abuse (Lanzarote Convention, 2007)",
        "summary": "Requires states to criminalize: sexual abuse, child prostitution, child pornography, and grooming. Establishes preventive measures: screening of professionals working with children, awareness programs, participation of children in policy development. Lanzarote Committee monitors implementation. 50 state parties. Relevant to child trafficking: addresses demand-side of child sexual exploitation, requires victim-friendly judicial procedures, and mandates cross-border cooperation.",
        "source": "Council of Europe, CETS 201 (2007)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Principles for Responsible Investment (PRI) — Modern Slavery and Human Trafficking (2019)",
        "summary": "UN-supported initiative of 5,300+ investor signatories (USD 120+ trillion AUM). Issued guidance on: screening portfolios for modern slavery exposure, engaging with companies on supply chain due diligence, integrating forced labor risk into ESG assessments. Investors increasingly use modern slavery as materiality indicator. PRI-supported CCLA Modern Slavery Engagement Programme has secured commitments from 70+ FTSE 350 companies. Financial sector leverage becoming critical enforcement mechanism.",
        "source": "PRI / UNPRI, 2019",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Kimberly Process Certification Scheme (2003) — Model for Product Traceability",
        "summary": "Established to prevent trade in conflict diamonds. 85 participating countries. Requires: government certification of diamond origin, tamper-proof containers, import/export controls. While focused on diamonds, serves as model for product traceability systems addressing forced labor: cotton certification, seafood traceability, minerals tracking. Criticisms: narrow definition of 'conflict diamonds,' inadequate monitoring, Zimbabwe and CAR exemptions. Lessons applied to Dodd-Frank Section 1502 conflict minerals and EU Due Diligence.",
        "source": "Kimberley Process, 2003",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Maritime Labour Convention (MLC, 2006) — Seafarer Protections",
        "summary": "Comprehensive convention for seafarer rights. Requires: minimum age 16, medical certification, employment agreements, wages, hours of work and rest, annual leave, repatriation, accommodation and food, health protection, social security, and complaint procedures. Flag state and port state inspection. 105 ratifications covering 96% of world shipping tonnage. Relevant to trafficking: protects seafarers from exploitation but fishing vessels excluded (covered by C188). MLC compliance certificates required for port entry.",
        "source": "ILO, MLC 2006 (entered into force 2013)",
    },
    {
        "type": "bilateral_agreement",
        "jurisdiction": "international",
        "title": "EU-Jordan Compact (2016) — Trade-for-Refugee-Employment Model",
        "summary": "Innovative agreement linking EU trade preferences to Jordan providing work permits for Syrian refugees. Jordan issued 200,000+ work permits to Syrians. EU relaxed rules of origin for Jordanian exports. Reduces exploitation risk by providing legal work status. Challenges: work permits concentrated in garment sector, some factories employ refugees alongside exploited migrant workers. Model studied for replication in other refugee-hosting countries (Lebanon, Turkey).",
        "source": "European Union / Jordan, 2016",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "UN Forum on Business and Human Rights — Annual Session and Outcomes",
        "summary": "Annual forum (since 2012) bringing together 3,000+ participants: governments, businesses, civil society, affected communities. Discusses implementation of UN Guiding Principles. Working groups address: mandatory due diligence trends, digital technology and human rights, just transition, remedy and accountability. 2023 forum focused on: supply chain legislation convergence, access to remedy for workers, and climate-migration-trafficking nexus. Hosted by OHCHR in Geneva.",
        "source": "OHCHR / UN Working Group on Business and Human Rights, annual",
    },
]
