"""International conventions and national laws on forced labour, trafficking, and migration."""

LAW_FACTS: list[dict] = [
    # ── International Conventions ─────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 29 — Forced Labour (1930)",
        "summary": "Defines forced labour as 'all work or service which is exacted from any person under the menace of any penalty and for which the said person has not offered himself voluntarily.' Ratified by 179 countries.",
        "law": "ILO C029",
        "year": 1930,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 105 — Abolition of Forced Labour (1957)",
        "summary": "Prohibits forced labour as a means of political coercion, economic development, labour discipline, punishment for strikes, or racial/social/religious discrimination.",
        "law": "ILO C105",
        "year": 1957,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 97 — Migration for Employment (1949)",
        "summary": "Requires states to maintain free public employment services for migrant workers, ensure adequate medical attention, and apply no less favourable treatment than nationals regarding working conditions, trade union membership, and social security.",
        "law": "ILO C097",
        "year": 1949,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 143 — Migrant Workers (Supplementary) (1975)",
        "summary": "Requires suppression of clandestine migration and illegal employment. Guarantees equality of opportunity and treatment for migrant workers in lawful residence, including job security and cultural rights.",
        "law": "ILO C143",
        "year": 1975,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 181 — Private Employment Agencies (1997)",
        "summary": "Establishes that private employment agencies shall not charge directly or indirectly, in whole or in part, any fees or costs to workers. Allows exceptions only for certain categories designated by competent authority.",
        "law": "ILO C181",
        "year": 1997,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Convention 189 — Domestic Workers (2011)",
        "summary": "Ensures domestic workers enjoy fair terms of employment, decent working conditions, minimum wage coverage, working time limits, and freedom from abuse/harassment/violence. Requires written contracts.",
        "law": "ILO C189",
        "year": 2011,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Protocol of 2014 to the Forced Labour Convention (P029)",
        "summary": "Supplements C029 with obligations to prevent forced labour, protect victims, and ensure access to remedies including compensation. Entered into force 2016.",
        "law": "ILO P029",
        "year": 2014,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Protocol to Prevent, Suppress and Punish Trafficking in Persons (Palermo Protocol)",
        "summary": "Defines trafficking as recruitment/transport/transfer/harboring by means of threat, force, coercion, fraud, deception, abuse of power, or payments for consent of a controlling person, for exploitation purposes. Art. 3(a).",
        "law": "Palermo Protocol",
        "year": 2000,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN International Convention on the Protection of the Rights of All Migrant Workers (1990)",
        "summary": "Comprehensive treaty on migrant worker rights: freedom of movement, equal treatment with nationals in working conditions, right to transfer earnings, access to education. Only 58 ratifications; no major destination country has ratified.",
        "law": "ICRMW",
        "year": 1990,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Convention on the Elimination of All Forms of Discrimination Against Women (CEDAW)",
        "summary": "Art. 6 requires states to suppress all forms of trafficking and exploitation of women. General Recommendation 26 specifically addresses women migrant workers. 189 state parties.",
        "law": "CEDAW",
        "year": 1979,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "Convention on the Rights of the Child (CRC) — Forced Labour Provisions",
        "summary": "Art. 32 recognizes the right of the child to be protected from economic exploitation and harmful work. Art. 34-36 address sexual exploitation and trafficking of children. 196 state parties.",
        "law": "CRC",
        "year": 1989,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ASEAN Convention Against Trafficking in Persons (ACTIP)",
        "summary": "First legally binding ASEAN instrument on trafficking. Criminalizes trafficking, mandates victim protection, promotes cross-border cooperation. Covers all 10 ASEAN member states.",
        "law": "ACTIP",
        "year": 2015,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "SAARC Convention on Preventing and Combating Trafficking in Women and Children",
        "summary": "Regional convention among South Asian countries. Requires criminalization of trafficking, victim repatriation, and mutual legal assistance. Covers India, Pakistan, Bangladesh, Nepal, Sri Lanka, Bhutan, Maldives.",
        "law": "SAARC Trafficking Convention",
        "year": 2002,
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Recommendation 203 — Supplementary Measures for Forced Labour (2014)",
        "summary": "Accompanies P029. Recommends national action plans, access to education/training for victims, legal assistance, compensation funds, due diligence for businesses, and protection from prosecution for victims.",
        "law": "ILO R203",
        "year": 2014,
    },

    # ── Philippines ───────────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "PH",
        "title": "Republic Act 8042 — Migrant Workers and Overseas Filipinos Act (1995)",
        "summary": "Establishes POEA (now DMW) authority over overseas employment. Requires licensing of recruitment agencies. Prohibits excessive placement fees. Creates Migrant Workers Fund.",
        "law": "RA 8042",
        "year": 1995,
    },
    {
        "type": "law",
        "jurisdiction": "PH",
        "title": "Republic Act 10022 — Amended Migrant Workers Act (2009)",
        "summary": "Strengthens RA 8042 with higher penalties for illegal recruitment (life imprisonment + PHP 2M fine). Mandates pre-departure orientation. Creates compulsory insurance for OFWs.",
        "law": "RA 10022",
        "year": 2009,
    },
    {
        "type": "law",
        "jurisdiction": "PH",
        "title": "Republic Act 9208 — Anti-Trafficking in Persons Act (2003)",
        "summary": "Criminalizes all forms of trafficking with 20-year to life imprisonment. Covers recruitment, transfer, harboring by means of threat, force, fraud, deception, or abuse of vulnerability.",
        "law": "RA 9208",
        "year": 2003,
    },
    {
        "type": "law",
        "jurisdiction": "PH",
        "title": "Republic Act 11862 — Department of Migrant Workers Act (2022)",
        "summary": "Creates the Department of Migrant Workers (DMW), consolidating POEA, OWWA overseas operations, and DOLE migrant worker bureau into a single cabinet-level department.",
        "law": "RA 11862",
        "year": 2022,
    },
    {
        "type": "law",
        "jurisdiction": "PH",
        "title": "Republic Act 10364 — Expanded Anti-Trafficking in Persons Act (2012)",
        "summary": "Expands RA 9208 to cover attempted trafficking, confidentiality of victim identity, establishment of IACAT (Inter-Agency Council Against Trafficking), and creation of trafficking-in-persons fund.",
        "law": "RA 10364",
        "year": 2012,
    },

    # ── Hong Kong ─────────────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "HK",
        "title": "Employment Ordinance (Cap. 57)",
        "summary": "Primary labour law in Hong Kong. Mandates written employment contracts for foreign domestic helpers. Sets minimum allowable wage, rest days, statutory holidays, and maximum working hours.",
        "law": "Employment Ordinance Cap. 57",
        "year": 1968,
    },
    {
        "type": "law",
        "jurisdiction": "HK",
        "title": "Immigration Ordinance (Cap. 115) — FDH Two-Week Rule",
        "summary": "Foreign domestic helpers must leave Hong Kong within 2 weeks of contract termination. Creates vulnerability: workers tolerate abuse rather than lose immigration status and income.",
        "law": "Immigration Ordinance Cap. 115",
        "year": 1971,
    },

    # ── Singapore ─────────────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "SG",
        "title": "Employment of Foreign Manpower Act (EFMA)",
        "summary": "Governs employment of foreign workers in Singapore. MOM issues work permits. Prohibits employers from recovering levy costs from workers. Mandatory medical insurance and security bond.",
        "law": "EFMA",
        "year": 1990,
    },
    {
        "type": "law",
        "jurisdiction": "SG",
        "title": "Prevention of Human Trafficking Act (PHTA 2014)",
        "summary": "Criminalizes trafficking in persons with up to 20 years imprisonment and fines. Establishes inter-agency taskforce. Provides for victim protection orders and temporary shelter.",
        "law": "PHTA 2014",
        "year": 2014,
    },

    # ── Gulf States ───────────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "QA",
        "title": "Law No. 21 of 2015 — Entry, Exit, and Residence of Expatriates",
        "summary": "Reformed Qatar's kafala system: workers may change employers after contract ends without NOC (2020 amendment). Introduced non-discriminatory minimum wage of QAR 1,000/month (2021).",
        "law": "Qatar Law No. 21/2015",
        "year": 2015,
    },
    {
        "type": "law",
        "jurisdiction": "QA",
        "title": "Qatar Law No. 15 of 2017 — Domestic Workers",
        "summary": "First standalone domestic worker law in the Gulf. Requires written contracts, maximum 10-hour workday, weekly rest day, 3 weeks annual leave, and employer-provided accommodation and food.",
        "law": "Qatar Law No. 15/2017",
        "year": 2017,
    },
    {
        "type": "law",
        "jurisdiction": "SA",
        "title": "Saudi Labour Law (Royal Decree M/51)",
        "summary": "Governs private-sector employment in Saudi Arabia. Wage Protection System requires electronic salary transfers. Domestic workers covered separately by Ministerial Resolution No. 310 (2013).",
        "law": "Royal Decree M/51",
        "year": 2005,
    },
    {
        "type": "law",
        "jurisdiction": "SA",
        "title": "Saudi Anti-Trafficking in Persons Law (Royal Decree M/40)",
        "summary": "Criminalizes trafficking with up to 15 years imprisonment and fines up to SAR 1M. Covers forced labour, sexual exploitation, and organ trafficking. Aggravated penalties for organized crime or involving minors.",
        "law": "Royal Decree M/40",
        "year": 2009,
    },
    {
        "type": "law",
        "jurisdiction": "AE",
        "title": "UAE Federal Law No. 51 — Combating Human Trafficking",
        "summary": "Criminalizes all forms of trafficking. Minimum 5-year imprisonment. Victim protection provisions including temporary residence permits, shelter, and psychological support.",
        "law": "Federal Law No. 51/2006",
        "year": 2006,
    },
    {
        "type": "law",
        "jurisdiction": "KW",
        "title": "Kuwait Domestic Workers Law (Law No. 68/2015)",
        "summary": "First domestic worker law in Kuwait: 12-hour maximum workday, weekly rest day, 30 days annual leave, end-of-service indemnity. Establishes domestic worker dispute resolution department.",
        "law": "Law No. 68/2015",
        "year": 2015,
    },

    # ── US / UK / AU ──────────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "US",
        "title": "Trafficking Victims Protection Act (TVPA)",
        "summary": "US federal law establishing trafficking as a crime, creating 3-tier ranking system for countries, mandating annual TIP Report, and providing services to trafficking victims.",
        "law": "TVPA (22 USC 7101)",
        "year": 2000,
    },
    {
        "type": "law",
        "jurisdiction": "UK",
        "title": "Modern Slavery Act 2015",
        "summary": "Requires companies with turnover >GBP 36M to publish annual slavery/trafficking transparency statements. Establishes Independent Anti-Slavery Commissioner. Max life imprisonment for trafficking offences.",
        "law": "Modern Slavery Act 2015",
        "year": 2015,
    },
    {
        "type": "law",
        "jurisdiction": "UK",
        "title": "Gangmasters (Licensing) Act 2004",
        "summary": "Requires licensing of labour providers (gangmasters) in agriculture, shellfish, and food processing. Gangmasters and Labour Abuse Authority (GLAA) enforces. Unlicensed operation is a criminal offence.",
        "law": "Gangmasters (Licensing) Act 2004",
        "year": 2004,
    },
    {
        "type": "law",
        "jurisdiction": "AU",
        "title": "Australia Modern Slavery Act 2018",
        "summary": "Requires entities with annual revenue ≥AUD 100M to report on modern slavery risks in operations and supply chains. Public register of statements. No financial penalties but reputational enforcement.",
        "law": "Modern Slavery Act 2018 (Cth)",
        "year": 2018,
    },

    # ── Asia-Pacific Origin Countries ─────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "NP",
        "title": "Nepal Foreign Employment Act 2007",
        "summary": "Regulates overseas recruitment. Service charge capped at NPR 10,000. Requires license for recruitment agencies. Establishes Foreign Employment Tribunal. Migrant welfare fund from airport levy.",
        "law": "Foreign Employment Act 2007",
        "year": 2007,
    },
    {
        "type": "law",
        "jurisdiction": "BD",
        "title": "Bangladesh Overseas Employment and Migrants Act 2013",
        "summary": "Replaces 1982 Emigration Ordinance. Caps migration costs, requires government-approved contracts, mandates pre-departure training. Establishes Wage Earners Welfare Board. Criminalizes excessive fee charging.",
        "law": "OEMA 2013",
        "year": 2013,
    },
    {
        "type": "law",
        "jurisdiction": "ID",
        "title": "Indonesia Law 18/2017 — Protection of Indonesian Migrant Workers Abroad",
        "summary": "Replaces 2004 law. Establishes zero-cost migration principle. Creates BNP2MI (successor to BNP2TKI). Mandates single-channel placement through government-to-government agreements.",
        "law": "Law 18/2017",
        "year": 2017,
    },
    {
        "type": "law",
        "jurisdiction": "MM",
        "title": "Myanmar Overseas Employment Law 1999",
        "summary": "Governs overseas labour recruitment. Licensed agencies must register with Ministry of Labour. Weak enforcement: sub-agents operate with impunity along Thai and Chinese borders.",
        "law": "Overseas Employment Law 1999",
        "year": 1999,
    },

    # ── Destination Countries (Asia) ──────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "MY",
        "title": "Malaysia Anti-Trafficking in Persons and Anti-Smuggling of Migrants Act 2007",
        "summary": "Criminalizes trafficking with imprisonment up to 20 years. MAPO (Council for Anti-Trafficking and Anti-Smuggling) coordinates enforcement. Provides for interim protection orders for victims.",
        "law": "Act 670",
        "year": 2007,
    },
    {
        "type": "law",
        "jurisdiction": "TH",
        "title": "Thailand Anti-Trafficking in Persons Act B.E. 2551 (2008)",
        "summary": "Criminalizes trafficking with 4-10 years imprisonment (aggravated up to life). Establishes anti-trafficking committee. Applies to Thai and foreign victims. Enhanced penalties for trafficking of children.",
        "law": "Anti-Trafficking Act B.E. 2551",
        "year": 2008,
    },
    {
        "type": "law",
        "jurisdiction": "KR",
        "title": "Korea Employment Permit System Act (2003)",
        "summary": "Government-managed foreign worker recruitment. Eliminates private broker involvement. Workers apply through government channels. Total cost ~USD 1,000 including Korean Language Test. Maximum 4 years 10 months.",
        "law": "EPS Act",
        "year": 2003,
    },
    {
        "type": "law",
        "jurisdiction": "JP",
        "title": "Japan Technical Intern Training Act (2016)",
        "summary": "Revised framework for Technical Intern Training Program (TITP). Establishes OTIT (Organization for Technical Intern Training) for supervision. Prohibits passport confiscation. Allows inspections of accepting organizations.",
        "law": "TITP Act",
        "year": 2016,
    },
    {
        "type": "law",
        "jurisdiction": "LB",
        "title": "Lebanon Code of Labour (1946) — Kafala System Provisions",
        "summary": "Explicitly excludes domestic workers from labour law protections. Kafala ties domestic worker legal status to employer sponsor. No minimum wage, no working hour limits, no rest day requirements for domestic workers.",
        "law": "Labour Code 1946",
        "year": 1946,
    },
    {
        "type": "law",
        "jurisdiction": "JO",
        "title": "Jordan Regulation on Domestic Workers, Cooks, Gardeners and Similar Categories (2009)",
        "summary": "First regulation covering domestic workers in Jordan. Sets 10-hour workday, weekly rest day, and minimum wage. Employer must provide accommodation and food. Kafala system still applies for sponsorship.",
        "law": "Regulation 90/2009",
        "year": 2009,
    },
]
