"""Document retention and passport confiscation — laws, prevalence, and cases."""

PASSPORT_CONFISCATION_FACTS: list[dict] = [
    # ── International Standards ─────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "ILO Indicator — Retention of Identity Documents",
        "summary": "Retention of identity documents is one of 11 ILO indicators of forced labour. Confiscating passports, work permits, or identity cards restricts workers' freedom to leave and creates total dependency on the employer. Applies regardless of employer's stated justification ('safekeeping').",
        "source": "ILO Indicators of Forced Labour (2012)",
    },
    {
        "type": "law",
        "jurisdiction": "international",
        "title": "UN Protocol — Document Confiscation as Trafficking Means",
        "summary": "Palermo Protocol (Art. 3) lists confiscation or destruction of travel documents as a means of trafficking. Used in conjunction with deception, coercion, or abuse of vulnerability. Courts increasingly recognise passport retention alone as evidence of trafficking.",
        "source": "UN Protocol to Prevent, Suppress and Punish Trafficking in Persons (2000)",
    },
    # ── Gulf States ─────────────────────────────────────────────────────
    {
        "type": "law",
        "jurisdiction": "QA",
        "title": "Qatar Law No. 21 of 2015 — Passport Retention Prohibition",
        "summary": "Qatar criminalised passport confiscation under Law No. 21 of 2015 (Art. 8): employers face up to 3 years imprisonment and QAR 25,000 fine. Despite the law, ILO surveys (2019) found 60% of workers reported employers holding their passports. Enforcement remains weak.",
        "source": "Qatar Ministry of Interior / ILO Qatar Office",
    },
    {
        "type": "statistic",
        "jurisdiction": "QA",
        "title": "Qatar — Passport Retention Prevalence",
        "metric": "passport_retention_rate",
        "value": "60%",
        "summary": "ILO-Gallup survey (2019) found 60% of migrant workers in Qatar had passports held by employers despite criminalisation in 2015. Workers in construction and domestic work reported highest rates. Many employers offer 'voluntary safekeeping' arrangements that workers feel unable to refuse.",
        "source": "ILO / Gallup World Poll",
    },
    {
        "type": "law",
        "jurisdiction": "SA",
        "title": "Saudi Arabia — Passport Retention Under Kafala",
        "summary": "Saudi Labour Law (Art. 40, as amended 2021) prohibits passport confiscation. Ministry of Human Resources Resolution No. 70273 imposes fines of SAR 15,000 per worker on violating employers. Practice persists widely: Human Rights Watch (2021) documented 90%+ retention rates for domestic workers. Employers claim insurance against 'absconding'.",
        "source": "Saudi Ministry of Human Resources / Human Rights Watch",
    },
    {
        "type": "case_study",
        "jurisdiction": "AE",
        "title": "UAE — Passport Confiscation in Construction Camps",
        "sector": "construction",
        "exploitation_type": "retention_of_documents",
        "summary": "Amnesty International (2020) documented systematic passport confiscation in UAE construction labour camps housing workers for Expo 2020 projects. Passports locked in company safes. Workers required to give 48-hour notice and written reason to access own documents. Companies argued 'lost passport' liability.",
        "source": "Amnesty International / Equidem",
    },
    {
        "type": "statistic",
        "jurisdiction": "AE",
        "title": "UAE — Domestic Worker Document Retention Rates",
        "metric": "passport_retention_rate",
        "value": "86%",
        "summary": "Surveys by migrant worker advocacy groups found 86% of domestic workers in the UAE had passports held by employers as of 2022. Despite Federal Law No. 10 of 2017 prohibiting confiscation, enforcement is rare. Workers who request passports back often face termination threats.",
        "source": "Migrant-Rights.org / Abu Dhabi Dialogue",
    },
    {
        "type": "law",
        "jurisdiction": "KW",
        "title": "Kuwait Ministerial Resolution No. 842 — Passport Prohibition",
        "summary": "Kuwait Ministerial Resolution No. 842 of 2015 prohibits employers from confiscating worker passports, with fines of KWD 100-200 per violation. Kuwait also introduced secure locker systems in labour accommodation. Compliance estimated at 40-50% as of 2023. Domestic workers excluded from labour law protections until recent reforms.",
        "source": "Kuwait Ministry of Social Affairs and Labour",
    },
    {
        "type": "law",
        "jurisdiction": "BH",
        "title": "Bahrain Labour Market Regulatory Authority — Document Retention Ban",
        "summary": "Bahrain's LMRA prohibits passport retention under Decision No. 79 of 2009. Flexi-permit system (2017) allows workers to leave employers without transfer, reducing coercive leverage. Bahrain considered most reformed Gulf state for labour mobility, but domestic workers still report high confiscation rates.",
        "source": "Bahrain LMRA / Migrant Forum in Asia",
    },
    {
        "type": "law",
        "jurisdiction": "JO",
        "title": "Jordan — Passport Retention in Qualified Industrial Zones",
        "summary": "Jordan Labour Law and anti-trafficking law (2009) prohibit document retention. Despite this, Better Work Jordan assessments (2023) found 15% of QIZ garment factories still held worker passports. Workers from Bangladesh and Sri Lanka most affected. Better Work compliance pressure reduced rate from 40% (2015).",
        "source": "ILO Better Work Jordan / Jordan Ministry of Labour",
    },
    # ── Asia-Pacific ────────────────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "Malaysia — Systemic Passport Retention in Electronics and Palm Oil",
        "sector": "manufacturing",
        "exploitation_type": "retention_of_documents",
        "summary": "Malaysia has no specific law criminalising passport confiscation, only general anti-trafficking provisions. US TIP Report (2023) documents systemic retention across electronics, palm oil, and plantation sectors. Workers told passports needed for 'immigration compliance'. Some employers charge MYR 200-500 'passport storage fee'.",
        "source": "US TIP Report / Verité / SUHAKAM",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Singapore — Document Retention in Domestic Work",
        "sector": "domestic_work",
        "exploitation_type": "retention_of_documents",
        "summary": "Singapore Employment of Foreign Manpower Act (EFMA) makes passport confiscation an offence with fines up to SGD 10,000. HOME (Humanitarian Organization for Migration Economics) still receives 200+ complaints annually from domestic workers whose employers hold passports. Some employers use 'security deposit' systems as alternative control.",
        "source": "Singapore MOM / HOME Singapore",
    },
    {
        "type": "case_study",
        "jurisdiction": "HK",
        "title": "Hong Kong — Passport Retention Despite Strong Legal Protections",
        "sector": "domestic_work",
        "exploitation_type": "retention_of_documents",
        "summary": "Hong Kong Employment Ordinance prohibits passport retention. Mission for Migrant Workers survey (2022) found 14% of Indonesian domestic workers had passports held by employers, down from 28% in 2016. Prosecutions remain rare. Workers fear reporting due to 'two-week rule' requiring them to find new employer or leave HK.",
        "source": "Mission for Migrant Workers / HK Labour Department",
    },
    {
        "type": "law",
        "jurisdiction": "TH",
        "title": "Thailand — Anti-Trafficking Act Passport Provisions",
        "summary": "Thailand Prevention and Suppression of Human Trafficking Act B.E. 2551 (2008, amended 2017) criminalises document confiscation with penalties of 4-12 years imprisonment. In practice, Thai fishing vessel operators routinely confiscate documents of Myanmar and Cambodian workers. Enforcement concentrated in post-raid contexts.",
        "source": "Thailand Ministry of Justice / IJM Thailand",
    },
    # ── Mechanisms and Consequences ─────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Passport Confiscation Mechanisms and Pretexts",
        "summary": "Common employer pretexts: 'safekeeping' from theft, 'immigration requires it', 'company policy', 'insurance requirement'. Methods: collected at airport on arrival, demanded during orientation, locked in employer's safe/office. Some employers provide photocopy while retaining original. Creates total dependency regardless of stated intent.",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Consequences of Passport Confiscation for Workers",
        "summary": "Without passport, worker cannot: leave the country, change employer (even where legally permitted), access consular services independently, open bank accounts, rent housing, prove identity to police. If reported as 'absconding', worker becomes undocumented and subject to arrest. Creates cycle of exploitation and fear.",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Passport Confiscation as Gateway to Forced Labour",
        "summary": "Document retention rarely occurs in isolation — typically accompanied by: wage withholding, restriction of movement, excessive working hours, threats of deportation. ILO research shows passport confiscation present in 78% of forced labour cases involving migrant workers. It is the single most reliable indicator.",
        "source": "ILO Global Estimates of Modern Slavery (2022)",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "international",
        "title": "Employer Pays Principle and Document Retention",
        "summary": "ILO Fair Recruitment Initiative links passport confiscation to debt bondage: workers who paid recruitment fees cannot leave without losing their 'investment', and employers use documents as collateral. Employer Pays Principle would eliminate this leverage by removing worker debt. Adopted by IHRB Dhaka Principles and Leadership Group for Responsible Recruitment.",
        "source": "ILO Fair Recruitment Initiative / IHRB",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Global Prevalence of Document Retention in Forced Labour",
        "metric": "document_retention_in_forced_labour",
        "value": "78%",
        "summary": "ILO estimates document retention occurs in 78% of forced labour cases involving international migrants. Highest prevalence in Gulf states (80-90%), Southeast Asia (60-75%), and among domestic workers globally (70-85%). Gender disaggregation shows female domestic workers face highest rates.",
        "source": "ILO Global Estimates of Modern Slavery (2022) / Walk Free Foundation",
    },
    {
        "type": "case_study",
        "jurisdiction": "LB",
        "title": "Lebanon — Passport Retention and Kafala Collapse",
        "sector": "domestic_work",
        "exploitation_type": "retention_of_documents",
        "summary": "Lebanon's economic crisis (2019-present) intensified passport confiscation impacts. Employers unable to pay salaries still retained passports, trapping workers without wages or ability to leave. Ethiopian embassy reported 100+ workers abandoned per month with confiscated documents. General Security records show 300,000+ domestic workers potentially affected.",
        "source": "Human Rights Watch / Anti-Racism Movement Lebanon",
    },
]
