"""Penalty structures by jurisdiction for trafficking, forced labour, and recruitment violations."""

PENALTY_FACTS: list[dict] = [
    {
        "type": "penalty",
        "jurisdiction": "PH",
        "title": "Illegal Recruitment Penalties — RA 10022",
        "offense": "Large-scale illegal recruitment (3+ victims)",
        "penalty_type": "criminal",
        "amount": "Life imprisonment + PHP 2M-5M fine",
        "details": "Classified as economic sabotage. Also applies when involving minors. Agency license permanently revoked.",
        "law": "RA 10022 §6",
    },
    {
        "type": "penalty",
        "jurisdiction": "PH",
        "title": "Trafficking in Persons — RA 9208/10364",
        "offense": "Trafficking in persons",
        "penalty_type": "criminal",
        "amount": "20 years to life imprisonment + PHP 1M-2M fine",
        "details": "Aggravated: life imprisonment when victim is a child, or involves large-scale trafficking (3+ victims), or committed by a syndicate.",
        "law": "RA 9208 / RA 10364",
    },
    {
        "type": "penalty",
        "jurisdiction": "PH",
        "title": "Excessive Placement Fee — RA 8042",
        "offense": "Charging placement fees above authorized rates",
        "penalty_type": "administrative",
        "amount": "Agency license suspension/cancellation + PHP 50,000-100,000 fine",
        "details": "DMW may suspend (6 months) or cancel agency license. Refund of overcharged amount ordered. Criminal prosecution for repeat offenders.",
        "law": "RA 8042 §6",
    },
    {
        "type": "penalty",
        "jurisdiction": "HK",
        "title": "Employment Agency Overcharging — Cap. 57",
        "offense": "Charging domestic worker more than 10% of first month salary per contract year",
        "penalty_type": "criminal",
        "amount": "HKD 50,000 fine + license revocation",
        "details": "Employment Agencies Administration prosecutes. License revoked on conviction. Worker may recover overcharged amount through Labour Tribunal.",
        "law": "Employment Ordinance Cap. 57",
    },
    {
        "type": "penalty",
        "jurisdiction": "HK",
        "title": "Underpayment of FDH Minimum Wage — Cap. 57",
        "offense": "Paying below Minimum Allowable Wage (HKD 4,870/month)",
        "penalty_type": "criminal",
        "amount": "HKD 350,000 fine + 3 years imprisonment",
        "details": "Labour Department enforces. Worker may claim back-pay through Labour Tribunal. Employer banned from hiring FDH for specified period.",
        "law": "Employment Ordinance Cap. 57 §63B",
    },
    {
        "type": "penalty",
        "jurisdiction": "SG",
        "title": "EFMA Violations — Employer Penalties",
        "offense": "Illegal deployment, salary non-payment, levy recovery from worker",
        "penalty_type": "criminal",
        "amount": "SGD 5,000-30,000 fine + 12 months imprisonment (per charge)",
        "details": "Repeat offenders: mandatory minimum 1 month imprisonment. Caning for certain offences (e.g., physical abuse). Employer banned from hiring foreign workers.",
        "law": "EFMA §22",
    },
    {
        "type": "penalty",
        "jurisdiction": "SG",
        "title": "Human Trafficking — PHTA 2014",
        "offense": "Trafficking in persons",
        "penalty_type": "criminal",
        "amount": "Up to 20 years imprisonment + unlimited fine",
        "details": "Aggravated if involving minors, public officers, or organized crime. Mandatory caning for some offences. Victim protection orders available.",
        "law": "PHTA 2014 §3",
    },
    {
        "type": "penalty",
        "jurisdiction": "QA",
        "title": "Qatar Labour Law Violations — Wage Non-Payment",
        "offense": "Failure to pay wages through WPS (Wage Protection System)",
        "penalty_type": "administrative",
        "amount": "QAR 2,000-6,000 per worker + company work permit suspension",
        "details": "Ministry of Labour enforces. Company may be banned from recruiting new workers. Workers' Support and Insurance Fund covers unpaid wages.",
        "law": "Law No. 14/2004 (amended)",
    },
    {
        "type": "penalty",
        "jurisdiction": "SA",
        "title": "Saudi Human Trafficking Penalties",
        "offense": "Trafficking in persons",
        "penalty_type": "criminal",
        "amount": "Up to 15 years imprisonment + SAR 1,000,000 fine",
        "details": "Aggravated when involving organized crime, public officials, women, children, or disabled persons. Travel ban and asset freezing. Victim compensation from perpetrator.",
        "law": "Royal Decree M/40 (2009)",
    },
    {
        "type": "penalty",
        "jurisdiction": "SA",
        "title": "Saudi Wage Protection System Non-Compliance",
        "offense": "Failure to pay wages electronically through WPS",
        "penalty_type": "administrative",
        "amount": "SAR 3,000-10,000 per worker + company recruitment ban",
        "details": "Ministry of Human Resources enforces. Escalating penalties: warning → fine → recruitment ban → company closure. Applies to firms with 10+ employees.",
        "law": "Ministerial Decision 11/1/3626",
    },
    {
        "type": "penalty",
        "jurisdiction": "US",
        "title": "TVPA Federal Trafficking Penalties",
        "offense": "Forced labour and trafficking",
        "penalty_type": "criminal",
        "amount": "Up to 20 years federal imprisonment (life if death/kidnapping/sexual abuse)",
        "details": "18 USC §1589 (forced labour), §1590 (trafficking). Mandatory restitution to victims. Asset forfeiture. Civil cause of action under §1595.",
        "law": "TVPA / 18 USC §1589-1592",
    },
    {
        "type": "penalty",
        "jurisdiction": "UK",
        "title": "Modern Slavery Act — Trafficking Penalties",
        "offense": "Slavery, servitude, forced labour, human trafficking",
        "penalty_type": "criminal",
        "amount": "Up to life imprisonment",
        "details": "Sections 1-2: slavery/servitude/forced labour offences. Section 4: committing any offence with intent to commit human trafficking. Reparation orders for victims.",
        "law": "Modern Slavery Act 2015 §5",
    },
    {
        "type": "penalty",
        "jurisdiction": "UK",
        "title": "Gangmasters Licensing Penalties",
        "offense": "Operating without GLAA license in regulated sectors",
        "penalty_type": "criminal",
        "amount": "Up to 10 years imprisonment + unlimited fine",
        "details": "Gangmasters and Labour Abuse Authority (GLAA) enforces. Also applies to using unlicensed labour provider. Labour abuse prevention orders.",
        "law": "Gangmasters (Licensing) Act 2004 §12",
    },
    {
        "type": "penalty",
        "jurisdiction": "MY",
        "title": "Malaysia Anti-Trafficking Penalties",
        "offense": "Trafficking in persons",
        "penalty_type": "criminal",
        "amount": "Up to 20 years imprisonment + whipping",
        "details": "Act 670 (2007, amended 2022). Aggravated for trafficking of children, forced labour, or by public officials. Victim protection order available. MAPO coordinates enforcement.",
        "law": "Act 670 §12",
    },
    {
        "type": "penalty",
        "jurisdiction": "MY",
        "title": "Malaysia Forced Labour — Employment Act Amendment",
        "offense": "Forced labour in the private sector",
        "penalty_type": "criminal",
        "amount": "Up to 2 years imprisonment + MYR 100,000 fine",
        "details": "2022 amendment explicitly prohibiting forced labour. Responds to US CBP forced labour import bans. Covers debt bondage, document retention, and restriction of movement.",
        "law": "Employment Act 1955 (amended 2022)",
    },
    {
        "type": "penalty",
        "jurisdiction": "TH",
        "title": "Thailand Anti-Trafficking Penalties",
        "offense": "Trafficking in persons",
        "penalty_type": "criminal",
        "amount": "4-10 years imprisonment (life for aggravated cases)",
        "details": "Aggravated: involving children, organized crime, or public officials. Royal Ordinance on Fisheries (2015) adds separate penalties for fishing sector forced labour.",
        "law": "Anti-Trafficking Act B.E. 2551 §52",
    },
    {
        "type": "penalty",
        "jurisdiction": "AU",
        "title": "Australia Modern Slavery Reporting Penalties",
        "offense": "Failure to submit Modern Slavery Statement",
        "penalty_type": "administrative",
        "amount": "AUD 555,000 per offence (proposed 2024 amendment)",
        "details": "Currently no financial penalty (reputational only: public register). 2024 amendment proposes fines up to AUD 555,000 per entity. Independent Anti-Slavery Commissioner to oversee.",
        "law": "Modern Slavery Act 2018 (Cth)",
    },
    {
        "type": "penalty",
        "jurisdiction": "AE",
        "title": "UAE Anti-Trafficking Penalties",
        "offense": "Human trafficking",
        "penalty_type": "criminal",
        "amount": "Minimum 5 years imprisonment + AED 100,000-1,000,000 fine",
        "details": "Federal Law No. 51/2006 (amended 2020). Aggravated: life imprisonment if victim is a child or person with disability. Mandatory deportation after sentence.",
        "law": "Federal Law No. 51/2006",
    },
]
