"""Recent regulation changes, reforms, and policy updates."""

REGULATION_FACTS: list[dict] = [
    # ── Existing ──────────────────────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "SA",
        "title": "Saudi Arabia Kafala Reform (2021)",
        "summary": "Labour Reforms Initiative: foreign workers may transfer between employers without employer consent after 12 months. Exit/re-entry visa no longer requires employer approval. Covers private sector (not domestic workers).",
        "year": 2021,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "QA",
        "title": "Qatar Non-Discriminatory Minimum Wage (2021)",
        "summary": "First non-discriminatory minimum wage in the region: QAR 1,000/month basic + QAR 500 food + QAR 300 housing (if not provided). Covers all workers including domestic workers.",
        "year": 2021,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "PH",
        "title": "Philippines DMW Creation (2022)",
        "summary": "Republic Act 11641 created Department of Migrant Workers (DMW), absorbing functions of POEA, OWWA overseas operations, and DOLE migrant worker bureau. Streamlines OFW protection under single department.",
        "year": 2022,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "HK",
        "title": "Hong Kong Minimum Allowable Wage for FDH (2023)",
        "summary": "Minimum Allowable Wage for foreign domestic helpers raised to HKD 4,870/month (Oct 2023). Food allowance HKD 1,236/month if meals not provided. Reviewed annually by Labour Department.",
        "year": 2023,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Singapore Foreign Worker Levy Adjustments (2023)",
        "summary": "MOM adjusted foreign worker levies: concessionary domestic worker levy SGD 300/month, higher skilled worker rate SGD 350/month. Levy borne by employer. Penalties for passing levy to worker.",
        "year": 2023,
    },

    # ── New ───────────────────────────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "QA",
        "title": "Qatar Exit Permit Abolition (2018)",
        "summary": "Law No. 13 of 2018 removed requirement for workers to obtain employer's permission (exit permit) to leave Qatar. Employers may apply for exemption for up to 5% of workforce. Major kafala reform milestone.",
        "year": 2018,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "QA",
        "title": "Qatar Abolition of NOC for Job Transfer (2020)",
        "summary": "Ministerial Decision No. 51 of 2020: workers may change employers without employer's No Objection Certificate (NOC). Requires completion of probation period. Major reform enabling job mobility.",
        "year": 2020,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SA",
        "title": "Saudi Musaned Platform for Domestic Workers (2020)",
        "summary": "Digital platform for domestic worker recruitment and contract management. Standard electronic contract, salary transfer tracking, complaint mechanism. Aims to reduce informal recruitment.",
        "year": 2020,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "AE",
        "title": "UAE Wage Protection System Expansion (2023)",
        "summary": "WPS expanded to cover domestic workers. All salaries must be paid through approved electronic channels. Non-compliance triggers employer penalties and work permit suspension.",
        "year": 2023,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KW",
        "title": "Kuwait Domestic Workers Law Implementation (2015)",
        "summary": "Law No. 68/2015 established first domestic worker protections in Kuwait: 12-hour workday, weekly rest, 30 days annual leave, end-of-service indemnity. Enforcement remains weak.",
        "year": 2015,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "BH",
        "title": "Bahrain Flexi-Permit System (2017)",
        "summary": "Allows irregular migrant workers to self-sponsor by purchasing a flexi-permit. Enables legal work for 2 years without employer sponsorship. Reduces vulnerability to exploitation but raises cost concerns.",
        "year": 2017,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "MY",
        "title": "Malaysia Forced Labour Amendments (2022)",
        "summary": "Amended Employment Act 1955 to explicitly prohibit forced labour. New penalties: imprisonment up to 2 years and fine up to MYR 100,000. Responds to US CBP forced labour import bans on Malaysian products.",
        "year": 2022,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "TH",
        "title": "Thailand Fishing Industry Reforms (2015-2019)",
        "summary": "After EU yellow card (2015) for illegal fishing: Royal Ordinance on Fisheries (2015), mandatory vessel monitoring, port inspections, migrant worker registration. EU lifted yellow card in 2019.",
        "year": 2015,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "JP",
        "title": "Japan Specified Skilled Worker (SSW) Visa (2019)",
        "summary": "New visa category allowing direct employment (unlike TITP). Workers may change employers within same sector. 14 eligible sectors. Aims to address labour shortages while improving worker mobility.",
        "year": 2019,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KR",
        "title": "Korea EPS Sector Expansion (2022)",
        "summary": "Employment Permit System expanded to include additional sectors: hospitality, logistics, and food processing. Maximum stay extended from 4 years 10 months to 10 years with re-entry.",
        "year": 2022,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "PH",
        "title": "Philippines Anti-Illegal Recruitment Strengthening (2023)",
        "summary": "DMW enhanced enforcement: mandatory digital registration of all recruitment agencies, real-time contract verification system, mobile app for OFW complaints, increased prosecution of unlicensed recruiters.",
        "year": 2023,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "ID",
        "title": "Indonesia Zero-Cost Migration Policy (BNP2MI, 2020)",
        "summary": "BNP2MI formalized zero-cost placement for all Indonesian migrant workers. All costs to be borne by employer or sending/receiving governments. Enforcement through digital monitoring of recruitment agencies.",
        "year": 2020,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "JO",
        "title": "Jordan Unified Contract for Domestic Workers (2022)",
        "summary": "Standardized employment contract for all domestic workers in Jordan. Specifies minimum wage, maximum hours, rest days, and employer obligations. Arabic and worker's language versions required.",
        "year": 2022,
    },
    {
        "type": "regulation_change",
        "jurisdiction": "AU",
        "title": "Australia Modern Slavery Act Threshold Review (2023)",
        "summary": "Parliamentary inquiry recommended lowering reporting threshold from AUD 100M to AUD 50M. Also recommended introducing penalties for non-compliance. Independent Anti-Slavery Commissioner appointed.",
        "year": 2023,
    },
]
