"""Sector-specific forced labour facts and exploitation patterns."""

SECTOR_FACTS: list[dict] = [
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Forced Labour in Domestic Work — Global Overview",
        "sector": "domestic_work",
        "exploitation_type": "multiple",
        "summary": "8.5M domestic workers in forced labour globally (ILO 2022). 73% are women. Private household setting hinders detection. Key indicators: passport confiscation, confinement, unpaid wages, excessive hours. GCC, HK, SG, MY are major destinations.",
        "source": "ILO Global Estimates 2022",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Forced Labour in Construction — Global Overview",
        "sector": "construction",
        "exploitation_type": "debt_bondage",
        "summary": "Construction accounts for 18% of forced labour in the private economy. Major projects in Gulf states (stadiums, cities, infrastructure) employ millions of migrants. Debt bondage through recruitment fees is primary mechanism. Heat-related deaths documented.",
        "source": "ILO / Amnesty International / ITUC",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Forced Labour in Global Fishing Industry",
        "sector": "fishing",
        "exploitation_type": "restriction_of_movement",
        "summary": "128,000 workers in forced labour on fishing vessels (ILO). Key region: Southeast Asia (TH, MY, ID waters). Workers confined to vessels for months, debt bondage through broker fees. Physical violence documented. ILO Work in Fishing Convention (C188) largely unratified.",
        "source": "ILO / Environmental Justice Foundation",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Forced Labour in Agriculture — Global Overview",
        "sector": "agriculture",
        "exploitation_type": "isolation",
        "summary": "Agriculture accounts for 11% of forced labour in the private economy. Remote locations enable isolation. Seasonal work creates vulnerability. Key crops: palm oil (MY/ID), sugar (TH/BR), tobacco (MW), berries (EU). Children widely involved.",
        "source": "ILO / Walk Free / Verité",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Forced Labour in Manufacturing and Electronics",
        "sector": "manufacturing",
        "exploitation_type": "excessive_overtime",
        "summary": "Manufacturing accounts for 15% of forced labour in the private economy. Electronics assembly, garments, and textiles are key sub-sectors. MY and TH electronics factories subject to US CBP forced labour import bans. Forced overtime and debt bondage.",
        "source": "ILO / US CBP / KnowTheChain",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "Palm Oil Industry Forced Labour — Malaysia",
        "sector": "palm_oil",
        "exploitation_type": "debt_bondage",
        "summary": "Indonesia and Myanmar workers on Malaysian palm oil plantations. Debt bondage through recruitment fees. Remote location = isolation. Passports confiscated. Children work alongside parents. US CBP banned imports from Sime Darby (2022) and FGV (2020).",
        "source": "Wall Street Journal / US CBP / Rainforest Action Network",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Garment and Textile Industry — Supply Chain Forced Labour",
        "sector": "garment",
        "exploitation_type": "excessive_overtime",
        "summary": "Global garment supply chains linked to forced labour in BD, MM, KH, VN, CN. Sub-contracting obscures accountability. Forced overtime, wage theft, restriction of movement in factory dormitories. Rana Plaza collapse (2013, 1,134 deaths) catalyzed reforms.",
        "source": "ILO / Clean Clothes Campaign / Fashion Revolution",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Hospitality and Tourism — Hidden Forced Labour",
        "sector": "hospitality",
        "exploitation_type": "debt_bondage",
        "summary": "Hospitality accounts for 6% of forced labour. Migrant workers in hotels, restaurants, and catering. Common issues: unpaid overtime, tip confiscation, document retention, and employer-provided housing tied to employment. Seasonal work increases vulnerability.",
        "source": "ILO / ECPAT / Shiva Foundation",
    },
    {
        "type": "case_study",
        "jurisdiction": "UK",
        "title": "Meat Processing Forced Labour — United Kingdom",
        "sector": "meat_processing",
        "exploitation_type": "debt_bondage",
        "summary": "Eastern European and Southeast Asian workers in UK meat processing plants. Recruited through gangmasters. Debt for transport and housing. Excessive hours, dangerous conditions, below-minimum-wage pay. GLAA investigations increasing.",
        "source": "GLAA / Anti-Slavery International / The Guardian",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Mining Sector Forced Labour — Global",
        "sector": "mining",
        "exploitation_type": "debt_bondage",
        "summary": "Artisanal mining in Africa and South America involves forced labour and child labour. Cobalt mining in DRC (40,000 children), gold mining in Burkina Faso and Ghana. Commercial mining in some jurisdictions uses migrant workers under exploitative conditions.",
        "source": "Amnesty International / US DOL / Walk Free",
    },
    {
        "type": "case_study",
        "jurisdiction": "TH",
        "title": "Thai Poultry Processing — Forced Labour Documentation",
        "sector": "food_processing",
        "exploitation_type": "excessive_overtime",
        "summary": "Myanmar workers in Thai poultry processing. 12-16 hour shifts in cold environments. Wages below minimum. Illegal deductions for housing. Workers unable to leave: passport confiscated, debt to broker. Product exported globally.",
        "source": "Finnwatch / ILO / Thomson Reuters Foundation",
    },
    # ── Additional Sectors (expanded) ────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Healthcare Worker Recruitment Scams — Global",
        "sector": "healthcare",
        "exploitation_type": "debt_bondage",
        "summary": "Filipino, Indian, and Kenyan nurses recruited for US, UK, SA, AE hospitals through agencies charging USD 5,000-25,000. Credential non-recognition at destination forces workers into care aide roles at fraction of promised salary. Debt bondage through training fee recovery. US: H-1B nursing visa tie to single employer. Philippine Nurses Association documents widespread recruitment fraud.",
        "source": "Filipino Nurses United / RCN / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Seafaring and Maritime Forced Labour — Container Ships and Cruise Lines",
        "sector": "seafaring",
        "exploitation_type": "restriction_of_movement",
        "summary": "1.9M seafarers globally, 89% from developing countries (PH, IN, ID, CN, RU). Wage withholding for months (vessel as 'floating prison'). Manning agencies charge USD 1,000-5,000. MLC 2006 provides protections but enforcement depends on flag state. Flags of convenience (Panama, Liberia, Marshall Islands) have weak enforcement. COVID: 400,000+ seafarers trapped on vessels beyond contract.",
        "source": "ITF / ILO Maritime Labour Convention / ISWAN",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Eldercare and Care Work Sector — Emerging Exploitation",
        "sector": "care_work",
        "exploitation_type": "excessive_overtime",
        "summary": "Aging populations in JP, KR, TW, EU drive demand for care workers. Filipino, Indonesian, Vietnamese workers recruited for nursing homes and home-based eldercare. 24-hour on-call duties, emotional labour, physical demands. Japan kaigo (care worker) program: lower wages than other sectors, language barriers. EU: undocumented care workers in private homes (estimated 2-3M in Italy, Spain, Germany alone).",
        "source": "ILO / IDWF / PSI (Public Services International)",
    },
    {
        "type": "case_study",
        "jurisdiction": "IN",
        "title": "Brick Kiln Bonded Labour — India, Nepal, Pakistan",
        "sector": "brick_kilns",
        "exploitation_type": "debt_bondage",
        "summary": "23,000+ brick kilns in India, employing 10-23M workers (many bonded). Entire families including children migrate seasonally. Advance payment (peshgi) of INR 10,000-50,000 creates debt. Piece-rate payment below subsistence. Workers cannot leave until advance repaid (after season). Similar systems in Nepal (28,000 workers) and Pakistan (4.5M workers in brick kilns). Bonded Labour Abolition Act (1976) rarely enforced.",
        "source": "India NHRC / Anti-Slavery International / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "IN",
        "title": "Carpet Weaving Child and Bonded Labour — South Asia",
        "sector": "carpet_weaving",
        "exploitation_type": "child_labour",
        "summary": "Hand-knotted carpet industry in India (Uttar Pradesh, Rajasthan), Nepal, Pakistan, Afghanistan employs children as young as 5. Children trafficked from poor villages, work 12-14 hours/day in dark rooms. Physical damage: spinal deformity, lung disease, impaired vision. GoodWeave certification (founded by Kailash Satyarthi) monitors and certifies child-labour-free carpets. 200,000+ children still estimated in sector.",
        "source": "GoodWeave / ILO / Bachpan Bachao Andolan",
    },
    {
        "type": "case_study",
        "jurisdiction": "IN",
        "title": "Tea Plantation Labour Exploitation — India and Sri Lanka",
        "sector": "agriculture",
        "exploitation_type": "debt_bondage",
        "summary": "Tea estate workers in Assam (India) and central highlands (Sri Lanka) among lowest-paid agricultural workers globally. India: INR 232/day (USD 2.80) in Assam. Sri Lanka: LKR 1,000/day (USD 3.10). Multi-generational plantation residence creates dependency. Estate housing, healthcare, and education tied to employment. Workers cannot leave without forfeiting housing. Women (60% of workforce) face sexual harassment.",
        "source": "Oxfam / Columbia Center on Sustainable Investment / Plantation Workers Union",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "Rubber Plantation Forced Labour — Malaysia and Thailand",
        "sector": "agriculture",
        "exploitation_type": "debt_bondage",
        "summary": "Malaysia produces 5% of global natural rubber. Indonesian and Myanmar workers on rubber smallholdings: recruitment fees MYR 3,000-8,000, passport confiscation, below-minimum wages. Thailand: Myanmar workers in southern rubber plantations, similar patterns. Rubber enters supply chains of tire manufacturers (Bridgestone, Michelin, Goodyear). Less scrutiny than palm oil despite similar exploitation patterns.",
        "source": "Verité / Mighty Earth / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "CI",
        "title": "Cocoa Farming Forced and Child Labour — West Africa",
        "sector": "agriculture",
        "exploitation_type": "child_labour",
        "summary": "Cote d'Ivoire and Ghana produce 60% of global cocoa. 1.56M children in hazardous cocoa work (NORC 2020). Children trafficked from Burkina Faso and Mali. Adult workers: USD 0.50-2.00/day. Farmer share of chocolate bar price: 6%. Harkin-Engel Protocol (2001) industry self-regulation failed repeatedly. Nestle, Mars, Hershey face litigation. International Cocoa Initiative created but insufficient impact.",
        "source": "NORC / US DOL / International Cocoa Initiative",
    },
    {
        "type": "case_study",
        "jurisdiction": "MW",
        "title": "Tobacco Farming Child Labour — Malawi",
        "sector": "agriculture",
        "exploitation_type": "child_labour",
        "summary": "78,000+ children in Malawi tobacco farming (US DOL). Tenancy system: families work estate land, paid by tobacco weight. Children handle wet tobacco leaves causing Green Tobacco Sickness (nicotine poisoning). No protective equipment. 12-14 hour days during harvest. Tobacco exported to Philip Morris, BAT, JTI. Malawi produces 3% of global tobacco. US DOL lists Malawi tobacco on child labour list.",
        "source": "US DOL / Plan International / HRW",
    },
    {
        "type": "case_study",
        "jurisdiction": "KE",
        "title": "Cut Flower Industry — Kenya and Ethiopia",
        "sector": "agriculture",
        "exploitation_type": "excessive_overtime",
        "summary": "Kenya and Ethiopia export USD 1.5B+ in cut flowers annually (mainly to EU). Workers (70% women) on flower farms: pesticide exposure without protection, 12-16 hour shifts during Valentine's/Mother's Day peak, sexual harassment by supervisors. Wages: KES 300-500/day (USD 2-3.50). Fairtrade certification covers some farms but enforcement gaps. Workers fired for pregnancy or union activity.",
        "source": "Kenya Human Rights Commission / ETI / Hivos",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Electronics Assembly Forced Labour — Supply Chain",
        "sector": "manufacturing",
        "exploitation_type": "debt_bondage",
        "summary": "Electronics assembly in Malaysia, Thailand, and China involves migrant workers in forced labour. Malaysia: Nepali and Bangladeshi workers in semiconductor packaging pay USD 2,000-10,000 recruitment fees. Thailand: Myanmar workers in electronics factories. China: Uyghur forced labour in component manufacturing. US CBP WROs against multiple electronics suppliers. Apple, Samsung supplier audits find persistent violations.",
        "source": "Electronics Watch / Verité / US DOL",
    },
    {
        "type": "case_study",
        "jurisdiction": "GH",
        "title": "Small-Scale Gold Mining — Ghana and Burkina Faso",
        "sector": "mining",
        "exploitation_type": "child_labour",
        "summary": "1M+ artisanal small-scale gold miners in Ghana, 30-40% children. Mercury exposure, tunnel collapses, drowning in mine pits. Children carry heavy loads, dive underwater to mine riverbeds. Burkina Faso: 700,000 in artisanal mining including children as young as 6. Gold enters global supply chain through intermediary buyers. LBMA responsible sourcing standard covers large-scale only.",
        "source": "HRW / Amnesty International / US DOL",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US Meat Processing Plant Labour Exploitation",
        "sector": "food_processing",
        "exploitation_type": "debt_bondage",
        "summary": "US meat processing (beef, pork, poultry) relies heavily on immigrant labour (documented and undocumented). Workers face: high injury rates (knife cuts, repetitive strain, chemical exposure), below-living-wage pay, intimidation against unionization. ICE raids target workers not employers. Tyson Foods, JBS, Smithfield plants documented. COVID-19 outbreaks: 59,000+ meatpacking worker infections, 269 deaths (2020).",
        "source": "OSHA / UFCW / ProPublica / GAO",
    },
]
