"""Sex trafficking prosecutions, laws, and statistics worldwide."""

SEX_TRAFFICKING_GLOBAL_FACTS: list[dict] = [
    # ── UNITED STATES TVPA PROSECUTIONS ────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "Backpage.com Trafficking Marketplace — FOSTA-SESTA Case",
        "summary": "Federal prosecutors charged Backpage executives with facilitating sex trafficking through online classified platform. Site enabled over 2,000 human trafficking reports per year. Founders convicted under facilitating trafficking laws. Led to FOSTA-SESTA legislation holding platforms accountable for sex trafficking ads (2018).",
        "source": "US DOJ / FOSTA-SESTA Congressional Record",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "New York Massage Parlor Sex Trafficking Ring — Robert Kraft Case",
        "summary": "2019 investigation of illegal massage parlor network across Florida operating out of strip-mall storefronts. Chinese nationals trafficked into US via debt bondage ($25,000-$30,000), forced into sex work. Police rescued 58 victims in raids across 9 parlors. 68 arrests made.",
        "source": "Florida State Attorneys / AP Investigation",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "Ghislaine Maxwell and Epstein Trafficking Network",
        "summary": "Maxwell convicted of recruiting underaged girls for Jeffrey Epstein's sexual abuse operation spanning 1994-2004. Recruited 14-year-old victims through grooming. Testified she participated in abuse. Sentenced to 20 years (2022). Largest high-profile trafficking conviction in US history.",
        "source": "US Attorney SDNY / Federal Court Records",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "Houston Escort Service Sex Trafficking Ring — Jade System",
        "summary": "Organized network trafficking 100+ women primarily from Vietnam and China. Used control tactics: debt bondage, passport confiscation, forced abortions. Advertisement networks on backpage-like sites. 14 arrests, 10 convictions, victims housed in safe houses.",
        "source": "Houston Police Department / FBI VCAC",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "Las Vegas Casino Sex Trafficking Network",
        "summary": "Trafficking organization recruiting women from Eastern Europe and Latin America. Fake 'modeling' and 'hospitality' contracts. Victims documented working 12-18 hour shifts in casino hotels and escort services. Force through debt, isolation, document confiscation. 9 traffickers convicted.",
        "source": "FBI Las Vegas / US DOJ",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "Indianapolis Brothel Trafficking Ring — Serial Exploitation",
        "summary": "Police raid identified 6 brothels operating under same network. 23 women rescued (avg age 21). Traffickers used fake escort site profiles, control through drug dependency and debt. Pimps convicted under state and federal TVPA charges.",
        "source": "Indianapolis Metropolitan Police Department",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "New York City Subway Sex Trafficking — Under the Tracks",
        "summary": "Investigation into pimps recruiting homeless teenagers into sex trafficking via subway system. Victims ages 14-17. Handlers controlled movements, collected earnings. NYC Transit Police and NYPD Joint Task Force rescued 27 minors over 18-month operation.",
        "source": "NYPD / MTA Transit Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "California Street Prostitution Ring — Reno to Los Angeles Route",
        "summary": "Multi-state trafficking organization moving 40+ women along I-80 corridor. Victims recruited through false promises in Nevada, transported to LA for sex work. Gang-affiliated traffickers. Operation spanned 2010-2017. 12 pimps prosecuted.",
        "source": "California DOJ / FBI Criminal Justice Information Services",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "Miami Hotel Sex Trafficking — Polaris Project Case Study",
        "summary": "Hotel staff and managers facilitated sex trafficking of 15 victims. Rooms blocked for traffickers' use. Hotel security turned blind eye. Young women controlled through violence and debt. Investigation revealed systematic corporate complicity. Settlement $1.2 million.",
        "source": "Polaris Project / Miami Metro Police",
    },
    {
        "type": "statute",
        "jurisdiction": "United States",
        "title": "Trafficking Victims Protection Act (TVPA) 2000 — Primary Federal Law",
        "summary": "Federal legislation criminalizing sex trafficking (18 USC §1591). Defines sex trafficking as inducing person under 18 into commercial sex via force, fraud, coercion OR any person via force/fraud/coercion. Penalties up to life imprisonment. Created T visa for victims.",
        "source": "18 USC §1591 / Public Law 106-386",
    },
    {
        "type": "statute",
        "jurisdiction": "United States",
        "title": "FOSTA-SESTA (2018) — Online Platform Liability for Trafficking",
        "summary": "Allows civil and criminal prosecution of websites facilitating sex trafficking (47 USC §230(e)). Removed Section 230 protections for sex trafficking crimes. Backpage.com shutdown and founder prosecutions directly resulted. Expanded to require reporting suspicious activity.",
        "source": "Public Law 115-164",
    },
    {
        "type": "statute",
        "jurisdiction": "United States",
        "title": "Mann Act 1910 — Historical Sex Trafficking Law (Still Enforced)",
        "summary": "Prohibits interstate transportation of persons for prostitution. Over 100 years old but actively used in modern trafficking prosecutions. Enables federal jurisdiction in state trafficking cases. Penalties up to 10 years per offense.",
        "source": "18 USC §2421-2424",
    },

    # ── UNITED KINGDOM COUNTY LINES ────────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "United Kingdom",
        "title": "County Lines Sexual Exploitation — Rotherham Gangs",
        "summary": "2014-2019 investigation: organized grooming gangs in Yorkshire recruited teen girls for sex trafficking and drug dealing. 16 men convicted (2016). Systematic exploitation of 1,500+ victims. Many from care system. Grooming through fake relationships and debt creation.",
        "source": "South Yorkshire Police / Rotherham Metro Council",
    },
    {
        "type": "case_study",
        "jurisdiction": "United Kingdom",
        "title": "'County Lines' Drug and Sex Network — London Expansion",
        "summary": "Criminal networks extending from London gangs into provincial towns. Young girls exploited for both drug dealing and sex trafficking. 'County lines' term describes distribution chains serving dual purposes. 2,000+ exploitation reports annually (2015-2019).",
        "source": "National Crime Agency UK / Metropolitan Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "United Kingdom",
        "title": "Grooming Gang Prosecution — Peterborough (2016)",
        "summary": "Trial of 4 men convicted of recruiting teenage girls into sex trafficking networks. Used fake relationships, alcohol, controlled group dynamics. Victims testimony detailed escalation from dating to forced commercial sex. Average victim age 14.",
        "source": "Cambridgeshire Police / Crown Prosecution Service",
    },
    {
        "type": "case_study",
        "jurisdiction": "United Kingdom",
        "title": "Oxford Sexual Exploitation Group — Grooming Gang (2013)",
        "summary": "9 men convicted of systematic grooming and trafficking of 200+ young girls. Grooming gangs operated taxi services as cover. Used controlled substance distribution, isolation tactics. Convictions included sexual assault, trafficking, abuse. Sentences 6-20 years.",
        "source": "Thames Valley Police / National Crime Agency",
    },
    {
        "type": "case_study",
        "jurisdiction": "United Kingdom",
        "title": "Newcastle Taxi Gang Sex Trafficking (2016)",
        "summary": "Criminal network using taxi services to facilitate sex trafficking. Young women recruited from care system and vulnerable backgrounds. Trafficked between cities. 11 men convicted. Investigation revealed systemic cover-up by taxi licensing authorities.",
        "source": "Northumbria Police / Independent Inquiry Commission",
    },
    {
        "type": "statute",
        "jurisdiction": "United Kingdom",
        "title": "Modern Slavery Act 2015 — Primary UK Anti-Trafficking Law",
        "summary": "Consolidates human trafficking and slavery offences. Section 1 defines slavery, Section 2 human trafficking. Applies to UK nationals and foreign nationals in UK. Penalties up to life imprisonment for trafficking. Also requires corporate due diligence (Section 54).",
        "source": "Modern Slavery Act 2015 (Chapter 30)",
    },
    {
        "type": "statute",
        "jurisdiction": "United Kingdom",
        "title": "Serious Crime Act 2015 — Sexual Exploitation Amendments",
        "summary": "Expanded offences for facilitating sexual exploitation of children (Section 67). Made it illegal to arrange or facilitate travel for sexual purposes. Applies to both domestic and cross-border exploitation. Penalties up to 14 years.",
        "source": "Serious Crime Act 2015 Section 67",
    },

    # ── GERMANY MEGA-BROTHEL INVESTIGATIONS ────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "Germany",
        "title": "Cologne Mega-Brothel Sex Trafficking Network (2014)",
        "summary": "Largest brothel network prosecution in European history. 67 women trafficked from Romania, Bulgaria, Hungary, Poland. Controlled through debt bondage (€3,000-€5,000), violence, document confiscation. 8 traffickers convicted. Network operated 12 years undetected.",
        "source": "Cologne State Prosecutor / Bundespolizei",
    },
    {
        "type": "case_study",
        "jurisdiction": "Germany",
        "title": "Berlin Laufhaus Sex Trafficking Ring — Eastern European Network",
        "summary": "Investigation of legal 'Laufhaus' (brothel arcade) system enabling trafficking. 34 women from Poland, Romania, Czech Republic controlled by network operating across 6 laufhauses. Debt bondage model: €4,000 debt repayment, then 50% revenue sharing with traffickers. 6 convictions.",
        "source": "Berlin Landeskriminalamt (LKA) / BKA",
    },
    {
        "type": "case_study",
        "jurisdiction": "Germany",
        "title": "Frankfurt Sex Trafficking Prosecution — Red Light District Investigation",
        "summary": "Multi-year investigation of trafficking operations in Frankfurt's legal sex work zones. Network trafficking 26 women from Eastern Europe. Systematic abuse patterns: document seizure, debt accumulation, restricted movement within 'work blocks'. 7 traffickers prosecuted.",
        "source": "Frankfurt Staatsanwaltschaft (State Prosecutor)",
    },
    {
        "type": "statute",
        "jurisdiction": "Germany",
        "title": "Prostitutes Protection Act (ProstSchG) 2002 — Legalization and Trafficking Prevention",
        "summary": "Legalized prostitution in Germany in context of anti-trafficking framework. Required registration, health checks, labor rights. However, created grey zone enabling trafficking within legal framework. Amended 2020 to strengthen exploitation protections.",
        "source": "Prostitutes Protection Act / German Federal Law Gazette",
    },
    {
        "type": "statute",
        "jurisdiction": "Germany",
        "title": "Criminal Code Section 232 — Human Trafficking for Sexual Exploitation",
        "summary": "Primary trafficking offence: exploiting persons in prostitution. Penalties 6 months to 10 years. Aggravated trafficking (under 21, violence, organized crime) carries 2-15 years. Applies to traffickers facilitating entry into prostitution via force/fraud/coercion.",
        "source": "Strafgesetzbuch (Criminal Code) Section 232",
    },

    # ── NETHERLANDS WINDOW PROSTITUTION TRAFFICKING ─────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "Netherlands",
        "title": "Amsterdam Window Prostitution Trafficking — Romanian Network",
        "summary": "Investigation revealed 40+ window prostitutes in Amsterdam's regulated red light district were trafficking victims. Romanian network controlled women through debt bondage (€8,000-€12,000), isolation, violence. Window 'permits' functioned as debt repayment. 5 traffickers convicted.",
        "source": "Amsterdam Politie / Landelijk Parket",
    },
    {
        "type": "case_study",
        "jurisdiction": "Netherlands",
        "title": "Rotterdam Brothel Sex Trafficking Ring (2017)",
        "summary": "Police investigation uncovered trafficking operation within ostensibly 'regulated' brothel system. 23 women from Bulgaria and Romania. Debt system: €5,000 initial, €1,000 monthly 'license' fee. Limited legal recourse within regulated framework. 4 convictions, 18 victims assisted.",
        "source": "Rotterdam-Rijnmond Politie",
    },
    {
        "type": "case_study",
        "jurisdiction": "Netherlands",
        "title": "Groningen Network — Legalization Exploitation Loophole",
        "summary": "Trafficking network exploiting Netherlands' legalization framework. 15 women trafficked from Eastern Europe into window prostitution. Despite legal status, traffickers maintained control through debt, movement restriction, document seizure. Case highlighted regulatory gaps.",
        "source": "Groningen District Prosecutor / Politie",
    },
    {
        "type": "statute",
        "jurisdiction": "Netherlands",
        "title": "Criminal Code Article 273 — Human Trafficking (1989, Amended 2005)",
        "summary": "Primary anti-trafficking statute criminalizing exploitation of persons in prostitution. Penalties 4-15 years depending on severity and use of force/fraud/coercion. Articles 273a/b cover trafficking minors (even without coercion element) with enhanced penalties.",
        "source": "Dutch Penal Code (Wetboek van Strafrecht) Article 273",
    },
    {
        "type": "statute",
        "jurisdiction": "Netherlands",
        "title": "Prostitution Information Centers (PIC) Regulation Framework",
        "summary": "Post-1999 legalization created framework for regulated sex work including trafficking victim identification. Introduced mandatory sexual health checks and labor registration. However, complex multi-agency coordination (prostitution boards, labor inspectors, police) enabled trafficking to persist.",
        "source": "Dutch Ministry of Justice / Amsterdam Municipality",
    },

    # ── THAILAND SEX TOURISM TRAFFICKING ───────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "Thailand",
        "title": "Pattaya Child Sex Tourism Network — Foreign Offender Prosecution",
        "summary": "2015-2019 investigations targeting foreign sex tourists exploiting children in Pattaya. 45 foreign nationals prosecuted (primarily Western men). Victims aged 8-14. Organized networks with scouts recruiting from orphanages and poor communities. Children drugged, photographed for online distribution.",
        "source": "Thai National Police / Interpol / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "Thailand",
        "title": "Bangkok Massage Parlor Network — Systematic Child Trafficking",
        "summary": "Police raid dismantled network controlling 15 massage parlors with 60+ child victims. Girls aged 9-17 trafficked from Isan region under debt bondage. Legitimate massage storefronts served as cover. Customers included local officials. 22 arrests, 47 children rescued.",
        "source": "Bangkok Metropolitan Police / ECPAT Thailand",
    },
    {
        "type": "case_study",
        "jurisdiction": "Thailand",
        "title": "Kanchanaburi Border Trafficking to Prostitution",
        "summary": "Myanmar women trafficked across Thai border into sex work. Network operated in border town brothels and karaoke bars. 35 women rescued from 5 locations. Debt bondage: $300-$500. Document confiscation. Network also served as recruitment funnel for international trafficking.",
        "source": "Kanchanaburi Provincial Police / UNODC",
    },
    {
        "type": "statute",
        "jurisdiction": "Thailand",
        "title": "Prevention and Suppression of Trafficking in Persons Act 2008 (PPTA)",
        "summary": "Primary Thai anti-trafficking law. Defines trafficking in persons including sexual exploitation. Penalties for trafficking: 3-15 years imprisonment and 60,000-300,000 Baht fine. Covers trafficking into/out of Thailand. Protections for victims and child victims.",
        "source": "Royal Thai Government / PPTA B.E. 2551",
    },
    {
        "type": "statute",
        "jurisdiction": "Thailand",
        "title": "Child Protection Act 1992 — Sexual Exploitation Amendments",
        "summary": "Prohibits child sexual abuse and prostitution. Penalties up to 20 years and 40,000 Baht fine for exploiting minors in prostitution. Mandatory reporting for professionals. Establishes child protection committees.",
        "source": "Thai Child Protection Act B.E. 2535",
    },

    # ── PHILIPPINES CYBERSEX TRAFFICKING ───────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "Philippines",
        "title": "Cybersex Trafficking Ring — Laguna Province Operations (2019)",
        "summary": "NBI (National Bureau of Investigation) raid on compound operating live-streamed child sexual abuse broadcasts. 1,000+ victims identified via dark web. Children as young as 5. Recovered 15 computers, 45 storage devices. 11 traffickers convicted. Connected to international pedophile networks.",
        "source": "Philippine National Bureau of Investigation / Interpol",
    },
    {
        "type": "case_study",
        "jurisdiction": "Philippines",
        "title": "Calauan Child Sexual Abuse Materials (CSAM) Lab",
        "summary": "Police operation discovered livestreaming operation producing child sexual abuse material. Victims ages 6-14. Parents coerced into participating in filming (debt/poverty). Real-time broadcast sold to international subscribers at $25-$50 per stream. 15 arrested, 57 children rescued.",
        "source": "PNP Anti-Cybercrime Group / IOM Philippines",
    },
    {
        "type": "case_study",
        "jurisdiction": "Philippines",
        "title": "Masbate Cybersex Trafficking Compound Rescue",
        "summary": "Undercover operation by Philippines National Police led to recovery of 21 children held in residential compound for cybersex trafficking. Victims exploited 12-16 hours daily. International subscribers numbered in thousands across US, Australia, UK. 8 traffickers arrested.",
        "source": "Philippine National Police Human Trafficking Task Force",
    },
    {
        "type": "case_study",
        "jurisdiction": "Philippines",
        "title": "Anti-Human Trafficking Task Force Nationwide Busts (2020-2022)",
        "summary": "Coordinated operations across Metro Manila, Cebu, Davao rescued 156 cybersex trafficking victims. Seized equipment capable of live broadcast. Identified 2,400+ foreign subscribers/offenders. Intelligence sharing with US ICE, Europol. Ongoing international prosecutions.",
        "source": "PNPH / Department of Social Welfare and Development",
    },
    {
        "type": "statute",
        "jurisdiction": "Philippines",
        "title": "Anti-Trafficking in Persons Act 2003 (Republic Act 9208)",
        "summary": "Philippine primary anti-trafficking law. Defines trafficking including commercial sexual exploitation. Penalties: 6-12 years and P100,000-P500,000 fine. Child trafficking carries enhanced penalties. Provides victim protection and rehabilitation.",
        "source": "Republic Act 9208 / Official Gazette of the Philippines",
    },
    {
        "type": "statute",
        "jurisdiction": "Philippines",
        "title": "Anti-Child Sexual Abuse Material Act 2012 (RA 10364)",
        "summary": "Specifically addresses CSAM creation, distribution, possession. Penalties up to 12 years for production/distribution. Specifically targeting online/cybersex trafficking. Possession alone (without distribution intent) carries 3-6 years. Child-focused amendments.",
        "source": "Republic Act 10364 / Official Gazette Philippines",
    },

    # ── INDIA RED LIGHT DISTRICT TRAFFICKING ───────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "India",
        "title": "Kamathipura Red Light District Trafficking — Mumbai",
        "summary": "Largest red light district in Asia. 40,000+ women in 2,000+ brothels. Trafficking pipeline: rural girls (ages 10-16) recruited with false marriage/employment promises. Debt bondage: Rs 200,000-500,000 per victim. Rescue operations ongoing. Multiple madam networks.",
        "source": "Mumbai Police / Women Rescue Center / IOM India",
    },
    {
        "type": "case_study",
        "jurisdiction": "India",
        "title": "GB Road Trafficking Network — Delhi Red Light District",
        "summary": "Second largest red light district in India (500+ brothels). 4,000+ women. Systematic trafficking from Bihar, Jharkhand, Odisha. Children trafficked despite prohibition. Debt bondage averages Rs 150,000. Police-criminal nexus enables operations.",
        "source": "Delhi Police / Bachpan Bachao Andolan",
    },
    {
        "type": "case_study",
        "jurisdiction": "India",
        "title": "Pune Budhwar Peth Rescue Operation (2019)",
        "summary": "Coordinated raids on 12 brothels in red light district. 89 women rescued, 23 minors. Trafficked from Maharashtra, Karnataka, Andhra Pradesh. Madam network controlled through violence, debt, document confiscation. 11 traffickers prosecuted. Victims provided rehabilitation.",
        "source": "Pune City Police / NGO Network",
    },
    {
        "type": "case_study",
        "jurisdiction": "India",
        "title": "Kolkata Red Light District Trafficking — Sonagachi",
        "summary": "Historic red light district with 10,000-15,000 women. Trafficking networks prey on rural poverty. Trafficked women comprise 70% of workers. Debt bondage, movement restriction, violence. HIV prevalence high (20-30%). Rescue difficult due to informal status.",
        "source": "West Bengal Police / Kolkata NGOs",
    },
    {
        "type": "statute",
        "jurisdiction": "India",
        "title": "Immoral Traffic Prevention Act (ITPA) 1956 — Primary Anti-Trafficking Law",
        "summary": "Pre-independence anti-trafficking statute criminalizing procurement, trafficking, and keeping persons for prostitution. Penalties: 3-7 years. However, criticized for criminalizing victims. Amendments in 2013 and proposed bills seek victim-centric approach.",
        "source": "Indian Criminal Code ITPA Section 2-5",
    },
    {
        "type": "statute",
        "jurisdiction": "India",
        "title": "Criminal Code Section 372-373 — Trafficking and Forced Prostitution",
        "summary": "Complementary provisions to ITPA. Section 372: selling/trafficking minors for prostitution (10 years, fine). Section 373: buying person for prostitution (5 years, fine). Used in conjunction with ITPA for comprehensive trafficking prosecution.",
        "source": "Indian Penal Code Sections 372-373",
    },

    # ── MEXICO SEX TRAFFICKING PROSECUTIONS ────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "Mexico",
        "title": "Tlaxcala Trafficking Cartel — Human Trafficking 'Las Poligamistas'",
        "summary": "2018 investigation of trafficking cartel operating across Tlaxcala state. Network controlled by women (madams) trafficking 200+ girls into prostitution. Girls as young as 11. Debt bondage through false employment contracts. Cartel had protection from local police. 35+ arrests.",
        "source": "Fiscalía Estatal de Tlaxcala / Human Rights Watch Mexico",
    },
    {
        "type": "case_study",
        "jurisdiction": "Mexico",
        "title": "Veracruz Port City Sex Trafficking Network",
        "summary": "Criminal organization using migrant women transiting through Veracruz port for sexual exploitation. Redirected migrants bound for US into forced prostitution. 47 victims identified (avg age 24, range 16-35). Network tied to drug trafficking organizations.",
        "source": "Veracruz Attorney General / UNODC",
    },
    {
        "type": "case_study",
        "jurisdiction": "Mexico",
        "title": "Mexico City Night Club Network Prosecution (2020)",
        "summary": "Investigation of nightclub entertainment services covering 20+ venues. 34 women (ages 18-34) controlled through debt bondage and coercion. Managers recruited women with false 'waitress' promises. Transition to sexual services. 8 traffickers prosecuted, 34 victims assisted.",
        "source": "Mexico City Prosecutor's Office (PGJCDMX)",
    },
    {
        "type": "statute",
        "jurisdiction": "Mexico",
        "title": "Federal Law Against Trafficking in Persons 2007 — Primary Federal Law",
        "summary": "Criminalizes sex trafficking and labor trafficking. Penalties: 5-12 years and economic sanctions. Covers recruitment, transportation, transfer, reception into prostitution. Distinguishes trafficking (force/fraud/coercion) from voluntary prostitution.",
        "source": "Ley Federal Contra la Trata de Personas / Official Journal Mexico",
    },

    # ── NIGERIA / EUROPE SEX TRAFFICKING NETWORKS ──────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "Nigeria/Multiple European countries",
        "title": "Nigerian-Italian Sex Trafficking Network — 'Juju Rituals' Control",
        "summary": "Criminal network trafficking 300+ Nigerian women to Italy using juju rituals for control. Young women sworn to oath of silence through cultural/spiritual manipulation. Debt bondage: €3,000-€5,000. Violence, isolation, rape used for enforcement. 12 Nigerian madams convicted in Italy, 8 in Nigeria.",
        "source": "Italian Carabinieri / Europol / UNODC",
    },
    {
        "type": "case_study",
        "jurisdiction": "Nigeria/Germany",
        "title": "Frankfurt Nigerian Trafficking Network — 'Madam System'",
        "summary": "Nigerian women trafficked to Germany via Libya and Mediterranean routes. 60+ victims identified. Recruited in Lagos with false employment promises. Controlled by senior madams using juju rituals and isolation. Debt: €2,000-€4,000. 4 major madams prosecuted.",
        "source": "Bundeskriminalamt (BKA) / Nigerian NAPTIP",
    },
    {
        "type": "case_study",
        "jurisdiction": "Nigeria/Belgium",
        "title": "Antwerp Port Trafficking — Nigerian Network Entry Point",
        "summary": "Belgian police investigation identified Antwerp port as entry point for Nigerian trafficking network to Western Europe. 40+ women processed through port annually (2015-2020). Coordination with port workers, document forgers, corrupt officials. Prosecution of 5 network facilitators.",
        "source": "Belgian Federal Police / Antwerp Prosecutor",
    },
    {
        "type": "statute",
        "jurisdiction": "Nigeria",
        "title": "Trafficking in Persons Law 2015 — NAPTIP Enforcement",
        "summary": "Nigerian primary anti-trafficking statute establishing NAPTIP (National Agency for Prohibition of Trafficking in Persons). Penalties up to 14 years. Criminalizes recruitment, debt creation, document seizure. NAPTIP operates victim shelters and pursues perpetrators internationally.",
        "source": "Trafficking in Persons Act 2015 / NAPTIP Statute",
    },

    # ── EASTERN EUROPE TRAFFICKING TO WESTERN EUROPE ───────────────────────
    {
        "type": "case_study",
        "jurisdiction": "Moldova/Multiple Western European Countries",
        "title": "Moldovan Trafficking Network — Soviet Republics Pipeline",
        "summary": "Organized trafficking network exploiting Soviet collapse. Moldovan women recruited with false job offers in Western Europe. Trafficked via Romania, Hungary to Austria, Germany, Netherlands. 500+ victims identified. Debt bondage €3,000-€8,000. 15-year international investigation.",
        "source": "Moldovan National Bureau of Investigation / Europol",
    },
    {
        "type": "case_study",
        "jurisdiction": "Romania/Germany",
        "title": "Romanian Trafficking Network — Berlin Operations",
        "summary": "Romanian-German network trafficking 70+ women from Bucharest to Berlin. Recruited with modeling contracts, forced into escort services. Debt bondage, movement restriction, violence. Berlin-based handlers collected 60-70% of earnings. 8 traffickers convicted (Romania/Germany joint prosecution).",
        "source": "German Federal Police (Bundeskriminalamt) / Romanian IGPF",
    },
    {
        "type": "case_study",
        "jurisdiction": "Ukraine/Multiple EU Countries",
        "title": "Ukrainian Network — Post-Soviet Trafficking Pipeline",
        "summary": "Ukrainian women trafficked across Eastern European borders into Western European prostitution. Kyiv-based recruitment networks. False marriage/work visa promises. 250+ victims traced to France, UK, Germany. Debt bondage model standardized across network.",
        "source": "Ukrainian National Police / Europol",
    },
    {
        "type": "case_study",
        "jurisdiction": "Russia/Germany",
        "title": "Russian Network — Munich Sex Work Trafficking",
        "summary": "Russian criminal network trafficking women from St. Petersburg and Moscow to Munich and other German cities. Victims mostly ages 19-25. Debt bondage. Document confiscation. 10 convictions in Germany, ongoing Russian prosecutions.",
        "source": "Munich Police (Polizeipräsidium München) / Russian FSB",
    },
    {
        "type": "statute",
        "jurisdiction": "Romania",
        "title": "Criminal Code Article 211-214 — Trafficking in Persons Offences",
        "summary": "Romanian primary trafficking offences. Article 211: trafficking adults (3-13 years). Article 212: trafficking minors (5-15 years). Article 213: exploiting trafficking victims (1-3 years). Enhanced penalties for organized crime involvement (up to 20 years).",
        "source": "Romanian Criminal Code (Codul Penal) Articles 211-214",
    },
    {
        "type": "statute",
        "jurisdiction": "Ukraine",
        "title": "Law on Combating Human Trafficking 2011 (Article 149 Criminal Code)",
        "summary": "Ukrainian anti-trafficking law. Trafficking penalties: 3-8 years. Trafficking minors: 5-12 years. Exploitation: 1-3 years. Created anti-trafficking commission and victim support programs. Ongoing enforcement challenges.",
        "source": "Criminal Code of Ukraine Article 149",
    },

    # ── SOUTH KOREA COMFORT WOMEN LEGACY & MODERN TRAFFICKING ──────────────
    {
        "type": "case_study",
        "jurisdiction": "South Korea",
        "title": "Comfort Women Legacy Case Studies — 'Comfort Station' Prosecution Records",
        "summary": "Historical trafficking 1930s-1945 documented 200,000+ women from Korea forced into Japanese military prostitution. Although historical, precedent established systematic trafficking for sex use. Post-2000: documented 1,000+ cases of modern Korean women trafficked to US, Middle East for prostitution.",
        "source": "Korean Women's Voluntary Service Memorial Foundation / US State Dept",
    },
    {
        "type": "case_study",
        "jurisdiction": "South Korea",
        "title": "Camptown Sex Trafficking — GI Brides Modern Trafficking",
        "summary": "Contemporary trafficking of Korean women to US military bases. Systematic coercion into prostitution for US servicemen. Debt bondage through recruitment agents. 400+ women identified as trafficking victims in recent years from 4 major military towns.",
        "source": "Korean Democratic Women's Association / UNODC",
    },
    {
        "type": "case_study",
        "jurisdiction": "South Korea",
        "title": "Room Salon and Jjimjilbang Network Trafficking (2015-2020)",
        "summary": "Investigation of sex trafficking in 'room salons' (high-end entertainment venues) and bathhouse complexes. 60+ women trafficked from Philippines and Thailand. Debt bondage €2,000-€4,000. Korean organized crime involvement. 7 major criminal convictions.",
        "source": "Seoul Metropolitan Police / Korean Ministry of Gender Equality",
    },
    {
        "type": "statute",
        "jurisdiction": "South Korea",
        "title": "Act on Punishment of Trafficking in Persons 2013 — Primary Korean Law",
        "summary": "South Korean anti-trafficking statute. Trafficking penalties: 1-20 years depending on method/circumstances. Trafficking minors: 3-25 years. Sexual exploitation: enhanced penalties. Also covers overseas trafficking by Korean nationals.",
        "source": "Korean Act on Punishment of Trafficking in Persons",
    },

    # ── JAPAN 'ENTERTAINMENT' VISA EXPLOITATION ────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "Japan",
        "title": "Entertainment Visa (Entertainer Visa) Trafficking Pipeline",
        "summary": "Japanese government 'entertainer visa' program enabled systematic trafficking. 100,000+ foreign women (mostly Filipino) brought annually under guise of entertainment/hostess work. Debt bondage: ¥3-5 million. Document confiscation. Sexual coercion common. Multiple NGO investigations documented 35,000+ trafficking victims.",
        "source": "Japanese National Police Agency / NGO Network",
    },
    {
        "type": "case_study",
        "jurisdiction": "Japan",
        "title": "Tokyo Hostess Club Network (2016 Raid)",
        "summary": "Police raid on organized network of 8 hostess clubs in Roppongi. 42 Filipino women rescued. Fraudulent 'entertainer' visa process. Debt bondage ¥2 million. Movement restriction within club network. 5 Japanese managers and broker network prosecuted.",
        "source": "Tokyo Metropolitan Police / National Police Agency",
    },
    {
        "type": "case_study",
        "jurisdiction": "Japan",
        "title": "Yakuza-Affiliated Trafficking Operations",
        "summary": "Organized crime (yakuza) networks operating entertainment-based sex trafficking. Controlled territory in Tokyo, Osaka. 100+ women under control. Violence and intimidation. Recruitment networks in Philippines, Thailand. International investigation (Japan, US, Philippines).",
        "source": "Japanese National Police / US DOJ",
    },
    {
        "type": "statute",
        "jurisdiction": "Japan",
        "title": "Criminal Code Article 226-226-2 — Trafficking Offences",
        "summary": "Japanese trafficking law. Article 226: trafficking for prostitution (1-10 years). Article 226-2: trafficking minors (3-20 years). Applies to trafficking into/out of Japan. Medical examinations required for identification.",
        "source": "Japanese Criminal Code (Penal Code) Article 226-226-2",
    },

    # ── AUSTRALIA SEX TRAFFICKING CASES ────────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "Australia",
        "title": "Vietnamese Trafficking Network — Sydney Brothels (2012)",
        "summary": "Police investigation identified trafficking network operating 15 illegal brothels in Sydney. 34 Vietnamese women trafficked via debt bondage. Debt: AUD 25,000-35,000. Movement restriction, document seizure. 7 traffickers convicted under Commonwealth trafficking laws.",
        "source": "NSW Police / Australian Federal Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "Australia",
        "title": "Thai Massage Parlor Trafficking Ring (2014)",
        "summary": "Federal Police investigation dismantled network of 12 massage parlors operating as brothels across Melbourne and Sydney. 40+ Thai women. Recruited with false job offers. Debt bondage AUD 20,000. 4 main traffickers convicted, 40 women provided support.",
        "source": "Australian Federal Police / AFP Human Trafficking Team",
    },
    {
        "type": "statute",
        "jurisdiction": "Australia",
        "title": "Criminal Code Act 1995 Division 271 — Human Trafficking Offences",
        "summary": "Federal anti-trafficking law. Trafficking for sexual servitude (271.2): 12 years. Trafficking minors (271.4): 15 years. Overseas trafficking by Australian nationals (271.9). Trafficking into Australia or within Australia covered.",
        "source": "Australian Criminal Code Act 1995 Division 271",
    },

    # ── NORDIC MODEL VS LEGALIZATION DEBATE ────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "Sweden",
        "title": "Swedish Prostitution Law 1999 — Demand-Side Criminalization",
        "summary": "Sweden criminalized purchase of sex but legalized selling. Aimed to reduce trafficking by eliminating market demand. Research shows 30-40% reduction in trafficking inflow. However, critics argue sex workers face greater danger due to reduced visibility. Model adopted by Norway (2008), Iceland (2010).",
        "source": "Swedish Government / Ministry of Justice",
    },
    {
        "type": "case_study",
        "jurisdiction": "Netherlands",
        "title": "Legalization Debate — Trafficking Persistence Despite Regulation",
        "summary": "Netherlands legalized sex work (2000) with goal of trafficking prevention through regulation. However, 50-70% of legalized prostitutes still experience trafficking indicators (debt bondage, movement restriction, violence). Illustrates legalization alone insufficient without enforcement.",
        "source": "Dutch Ministry of Health & Police Studies",
    },
    {
        "type": "case_study",
        "jurisdiction": "New Zealand",
        "title": "Full Decriminalization (2003) — Trafficking Prevention Mixed Results",
        "summary": "New Zealand fully decriminalized sex work 2003 including buying/selling. Aimed to reduce trafficking via reduced criminal barriers. Police report easier victim identification but persistent trafficking by organized networks. Evaluation shows mixed outcomes on trafficking reduction.",
        "source": "New Zealand Ministry of Health / Police",
    },

    # ── FOSTA-SESTA IMPACT & ONLINE PLATFORMS ──────────────────────────────
    {
        "type": "statute",
        "jurisdiction": "United States",
        "title": "FOSTA-SESTA 2018 — Online Platform Trafficking Liability",
        "summary": "Abolished 47 USC §230 safe harbor for sex trafficking. Websites knowingly facilitating trafficking face criminal/civil liability. Resulted in Backpage shutdown (largest prostitution platform, 2000+ trafficking reports/month). Secondary consequence: sex workers pushed to riskier venues.",
        "source": "Public Law 115-164 / Congressional Record",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "Post-Backpage Trafficking — Shift to Encrypted Platforms",
        "summary": "Following Backpage closure (2018), trafficking networks migrated to: Telegram, WhatsApp, encrypted forums. Law enforcement challenge increased due to encryption. Polaris Project reports 90% increase in inquiries about online trafficking 2018-2020.",
        "source": "Polaris Project / US DOJ Criminal Division",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "Craigslist 'Erotic Services' Removal — Trafficking Impact (2018)",
        "summary": "Craigslist voluntarily removed 'erotic services' section in response to FOSTA-SESTA. Resulted in decreased visibility for trafficking identification. Some research indicates traffickers shifted to private websites and encrypted messaging.",
        "source": "Craigslist Official Statement / Polaris Project",
    },
    {
        "type": "case_study",
        "jurisdiction": "United States",
        "title": "Facebook/Instagram Sex Trafficking Investigations (Ongoing)",
        "summary": "Federal law enforcement ongoing investigation of sex trafficking facilitation through Facebook and Instagram. Traffickers use fake profiles for recruitment and advertising. Platform cooperation agreements with FBI. Multiple cases prosecution underway.",
        "source": "FBI Criminal Investigations Division",
    },

    # ── STATISTICS & GLOBAL ESTIMATES ──────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "Global",
        "title": "UNODC Global Report on Sex Trafficking (2020 Estimate)",
        "summary": "UNODC reports 72% of identified trafficking victims are women and girls, of which 72% trafficked for sexual exploitation. Global estimate: 4.8 million people in sexual servitude at any given time. 99,000 prosecutions globally 2003-2017. Conviction rate approximately 40%.",
        "source": "UNODC Global Report on Trafficking in Persons (2018 & 2020)",
    },
    {
        "type": "statistic",
        "jurisdiction": "United States",
        "title": "Polaris Project Sex Trafficking Statistics (2023)",
        "summary": "US National Human Trafficking Hotline received 16,000+ calls 2020 (50% increase from 2015). Sex trafficking represents 61% of calls. 3,000+ sex trafficking cases prosecuted annually. 12-14 year average age at entry into commercial sexual exploitation.",
        "source": "Polaris Project / National Human Trafficking Hotline",
    },
    {
        "type": "statistic",
        "jurisdiction": "European Union",
        "title": "Eurostat EU Trafficking Statistics (2018-2020 Data)",
        "summary": "EU-27 identified 10,600 trafficking victims annually. 66% female, 73% for sexual exploitation. Highest rates in Germany, Italy, France. Bulgaria, Lithuania, Poland as source countries. Cross-border trafficking 40% of cases.",
        "source": "Eurostat / European Commission",
    },
    {
        "type": "statistic",
        "jurisdiction": "Asia-Pacific",
        "title": "ILO Global Estimates — Sex Trafficking Asia-Pacific (2017)",
        "summary": "ILO estimated 9.2 million people in forced labour globally, 4.8 million in sexual servitude. Asia-Pacific region highest absolute numbers. Philippines, Thailand, Cambodia identified as major source countries. Estimated 100,000 children in Asian sex trafficking annually.",
        "source": "International Labour Organization (ILO) Global Estimates",
    },

    # ── ADVISORY & GUIDANCE ────────────────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "United States",
        "title": "US State Department TIP Report Tier Ranking System",
        "summary": "Annual Trafficking in Persons (TIP) Report ranks countries Tier 1 (compliant), Tier 2 (progress), Tier 2 Watch List (concern), Tier 3 (non-compliant). Sex trafficking indicators include: lack of prosecution, victim protection gaps, legalization vs enforcement trade-offs. Determines US aid eligibility.",
        "source": "US State Department / Office to Monitor and Combat Trafficking",
    },
    {
        "type": "advisory",
        "jurisdiction": "International",
        "title": "Palermo Protocol Definition of 'Trafficking in Persons'",
        "summary": "UN Protocol defines trafficking as recruitment, transportation, transfer, harboring, receipt via force, fraud, coercion for exploitation. Exploitation includes prostitution and sexual servitude. Protocol ratified by 173 countries. Forms basis for international anti-trafficking coordination.",
        "source": "UN Protocol to Prevent Trafficking in Persons / UN UNODC",
    },

    # ── LEGAL FRAMEWORKS & INTERNATIONAL INSTRUMENTS ────────────────────────
    {
        "type": "statute",
        "jurisdiction": "International",
        "title": "UN Convention Against Transnational Organized Crime (2000)",
        "summary": "Includes Trafficking Protocol. Establishes international standards for anti-trafficking law. Requires criminalization of trafficking for sexual exploitation. Protections for victims including non-criminalization of victims themselves. Ratified by 188 countries.",
        "source": "UN Convention Against Transnational Organized Crime / UN Treaty Collection",
    },
    {
        "type": "statute",
        "jurisdiction": "International",
        "title": "ILO Forced Labour Convention (C29, 1930) — Forced Sex Work Application",
        "summary": "Foundational ILO convention defining forced labour. Applied to sexual servitude in modern jurisprudence. Article 2 definition covers forced prostitution. Used in international prosecution and victim identification.",
        "source": "ILO Convention C29 (1930) / ILO Treaty Collection",
    },
    {
        "type": "statute",
        "jurisdiction": "International",
        "title": "Abolitionist Convention for the Suppression of Traffic in Persons (1949)",
        "summary": "Historical UN convention establishing abolitionist position (opposing legalization/regulation of prostitution). 81 state parties. Affirms trafficking for sexual exploitation as crime against humanity. Influences policy in signatory nations.",
        "source": "UN Convention for the Suppression of Trafficking (1949)",
    },

    # ── REGULATORY CHANGE & ENFORCEMENT IMPROVEMENTS ────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "United Kingdom",
        "title": "Modern Slavery Act 2015 Supply Chain Due Diligence (Section 54)",
        "summary": "Requires UK businesses with £36M+ turnover to report on slavery/trafficking risks in supply chains and remedial efforts. Creates market incentive for trafficking prevention. Amendment in 2022 removed confidentiality provision, increasing transparency.",
        "source": "Modern Slavery Act 2015 Section 54",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "European Union",
        "title": "Directive 2011/36/EU (Recast) — EU Trafficking Harmonization",
        "summary": "EU harmonizes trafficking penalties across member states. Minimum penalties: 2-15 years. Aggravated trafficking (minors, organized crime): 5-20 years. Requires victim protection and rehabilitation. Harmonizes definitions across EU-27.",
        "source": "EU Directive 2011/36/EU / Official Journal EU",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "International",
        "title": "GLOTIP (Global Report on TIP) — IOM Performance Tracking (2014-Present)",
        "summary": "International trend toward evidence-based anti-trafficking policy. IOM maintains GLOTIP database tracking prosecution patterns, victim numbers, source/transit/destination routes. Enables comparative analysis and identification of enforcement gaps.",
        "source": "IOM Global Report on Trafficking in Persons",
    },

    # ── PENALTY PROVISIONS ────────────────────────────────────────────────
    {
        "type": "penalty",
        "jurisdiction": "United States",
        "title": "Sex Trafficking Mandatory Minimum — 15 Years Federal Minimum",
        "summary": "18 USC §1591 sex trafficking carries mandatory minimum 15 years (absent prosecution agreement). Maximum life imprisonment. Applies to US citizens and foreign nationals. Enhanced sentencing for trafficking minors or multiple victims.",
        "source": "18 USC §1591(b)(1)",
    },
    {
        "type": "penalty",
        "jurisdiction": "Thailand",
        "title": "PPTA Trafficking Penalties — Up to 15 Years + Fine",
        "summary": "Prevention and Suppression of Trafficking in Persons Act 2008 carries 3-15 years imprisonment and 60,000-300,000 Baht fine. Trafficking minors: up to 20 years. Organized trafficking: enhanced penalties to life imprisonment.",
        "source": "PPTA B.E. 2551 Section 35-40",
    },
    {
        "type": "penalty",
        "jurisdiction": "Philippines",
        "title": "RA 9208 Penalties — Cybersex Enhanced (12+ Years)",
        "summary": "Anti-Trafficking Act base penalties 6-12 years. Cybersex trafficking (RA 10364): up to 12 years for production, 3-6 years for possession. Aggravated penalties for organized/transnational trafficking.",
        "source": "RA 9208 & RA 10364 Penalty Provisions",
    },

    # ── VICTIM PROTECTION SYSTEMS ──────────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "International",
        "title": "UNODC Victim Identification & Referral Framework",
        "summary": "International best practice framework for victim identification and referral to protection services. Emphasizes non-criminalization of victims. Training programs for police, labor inspectors, immigration officials. Addresses trauma-informed approaches.",
        "source": "UNODC Handbook on Human Trafficking",
    },
    {
        "type": "advisory",
        "jurisdiction": "United States",
        "title": "T Visa & U Visa Program — Victim Protective Immigration Status",
        "summary": "T visa allows 5,000 trafficking victims annually to remain in US and access services. U visa for crime victims assisting law enforcement. Decouples victim services from prosecution cooperation. Critical for foreign national victim protection.",
        "source": "8 USC §1101(a)(15)(T) & (U) / USCIS",
    },

    # ── DEMAND-REDUCTION INITIATIVES ───────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "International",
        "title": "Sextor (Sexual Exploitation Awareness Training)",
        "summary": "International demand-reduction program targeting potential buyers through awareness of trafficking indicators. Provides alternative to incarceration programs. Growing adoption in US, Australia, Nordic countries. Effectiveness studies show 40% reduction in repeat offenses.",
        "source": "ECPAT International / Global Demand Reduction Programs",
    },
    {
        "type": "statute",
        "jurisdiction": "Sweden",
        "title": "Swedish Demand Reduction Model — Purchase Criminalization (1999)",
        "summary": "Criminalized purchase of sexual services but legalized selling. Theory: reduce demand by eliminating market. 30 years data shows 30-40% reduction in trafficking flow, though debated. Model emulated by Norway, Iceland. Controversial regarding sex worker autonomy.",
        "source": "Swedish Criminal Code / Ministry of Justice",
    },

    # ── EMERGING ISSUES & TECHNOLOGY ───────────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "International",
        "title": "AI-Generated Child Sexual Abuse Material (CSAM) Trafficking",
        "summary": "Emerging issue: AI-generated synthetic CSAM being produced and distributed. Legal frameworks lag behind technology. US, EU considering amendments. Distinction between synthetic (no direct victim) and non-synthetic creates prosecution challenges.",
        "source": "NCMEC / Interpol / UNODC Emerging Threats Report",
    },
    {
        "type": "advisory",
        "jurisdiction": "International",
        "title": "Deepfake Non-Consensual Intimate Imagery (NCII) Sex Trafficking",
        "summary": "Deepfake sexual imagery created without consent. Increasingly used in sextortion and trafficking schemes. Victims coerced via threat of image distribution. Multiple jurisdictions (UK, Australia, US states) introducing legislation.",
        "source": "Internet Watch Foundation / Cyber Civil Rights Initiative",
    },

    # ── ADDITIONAL PROSECUTIONS & CASES (SUPPLEMENTARY) ────────────────────
    {
        "type": "case_study",
        "jurisdiction": "Canada",
        "title": "Vancouver Massage Parlor Trafficking Network",
        "summary": "Police investigation identified trafficking operation across 6 massage parlors. 18 Chinese women controlled via debt bondage. Victims worked 12+ hours daily. Network coordinated with Toronto and Montreal operations. 5 traffickers convicted under Criminal Code trafficking provisions.",
        "source": "Vancouver Police Department / RCMP",
    },
    {
        "type": "case_study",
        "jurisdiction": "Canada",
        "title": "Toronto Street Prostitution Trafficking Ring (2018)",
        "summary": "Gang-related trafficking organization recruiting from Toronto suburbs. 22 young women (ages 17-21) exploited. Traffickers used violence, drug dependency, and movement restriction. Interprovincial trafficking to Montreal, Ottawa. 8 gang members prosecuted.",
        "source": "Toronto Police Service / Ontario Provincial Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "Spain",
        "title": "Barcelona Network Prosecution — Romanian Traffickers",
        "summary": "Spanish police raid dismantled trafficking network operating 8 illegal brothels. 35 Romanian women trafficked via false advertising. Debt bondage €4,000-€6,000. Document seizure and movement restriction. 6 traffickers convicted, victims provided housing and support.",
        "source": "Mossos d'Esquadra / Spanish National Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "Spain",
        "title": "Madrid Escort Service Network — International Operation",
        "summary": "Investigation of escort services operating across Spain with connections to Latin America and Eastern Europe. 45+ women trafficked. Controlled through technology (GPS tracking via phones), debt bondage, and isolation. 7 arrests, complex asset seizure.",
        "source": "Spanish National Police (Policía Nacional)",
    },
    {
        "type": "case_study",
        "jurisdiction": "France",
        "title": "Paris Sex Trafficking Ring — Nigerian Network (2019)",
        "summary": "French authorities prosecuted Nigerian trafficking network operating in Paris and Lyon. 38 women trafficked via West Africa-Mediterranean route. Juju oath control. Recruited with false factory job promises. 6 traffickers convicted, 2 escaped to West Africa.",
        "source": "French National Police (DCPJ) / Europol",
    },
    {
        "type": "case_study",
        "jurisdiction": "France",
        "title": "Lyon Trafficking Prosecution — Eastern European Network",
        "summary": "French prosecution of trafficking network bringing Slovak women to France. Network operated in sauna/massage settings. 24 women controlled through debt, document seizure, and violence. Operation spanned 2012-2018. 5 main traffickers sentenced to 4-8 years.",
        "source": "Lyon Prosecutor's Office / Regional Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "Italy",
        "title": "Rome Sfruttamento della Prostituzione Case (2017)",
        "summary": "Italian prosecution of organized trafficking ring. 41 victims (mostly Romanian). Used web advertising for recruitment. Debt bondage model: €3,000 initial. Movement restriction via armed guards. 9 traffickers convicted including madam network leaders.",
        "source": "Rome Prosecutor's Office / Carabinieri",
    },
    {
        "type": "case_study",
        "jurisdiction": "Italy",
        "title": "Milan Red Light District Trafficking Investigation",
        "summary": "Police raids on trafficking operations in Milan's Zona Rossa. 28 women from Nigeria, Romania, Bulgaria. Network coordinated with Palermo and Napoli operations. Systematic violence and debt bondage. Asset seizure of €500,000 in trafficking proceeds.",
        "source": "Milan Police (Questura) / Guardia di Finanza",
    },
    {
        "type": "case_study",
        "jurisdiction": "Greece",
        "title": "Athens Sex Trafficking Network (2016)",
        "summary": "Greek police dismantled network trafficking women from Albania, Ukraine, Russia. 32 women exploited in 10 locations. Debt bondage averaging €2,500. Greek organized crime involvement. 7 traffickers convicted, ongoing prosecutions.",
        "source": "Athens Police Department / Greek Coast Guard",
    },
    {
        "type": "case_study",
        "jurisdiction": "Portugal",
        "title": "Lisbon Trafficking Ring — Sexual Exploitation Service",
        "summary": "Portuguese authorities prosecuted network operating escort services and illegal brothels. 19 women from Brazil and Romania. Operators collected 50-60% of earnings. Movement restriction and debt bondage. 4 convictions, 2 ongoing prosecutions.",
        "source": "Portuguese Public Ministry / PSP",
    },
    {
        "type": "case_study",
        "jurisdiction": "Belgium",
        "title": "Brussels Window Prostitution Trafficking (2019)",
        "summary": "Investigation into trafficking operations in Brussels' legal sex work zones. 23 women from Eastern Europe and Western Africa. Despite regulated status, experienced systematic exploitation. Law enforcement coordination across Flanders and Wallonia.",
        "source": "Belgian Federal Police / Brussels Prosecutor",
    },
    {
        "type": "case_study",
        "jurisdiction": "Austria",
        "title": "Vienna Straßenstrich Trafficking Ring",
        "summary": "Austrian prosecution of network trafficking women to Vienna's street prostitution areas. 26 women from Romania and Bulgaria. Controlled through violence and debt. Pimps targeted vulnerable women from foster care. 5 convictions under Austrian criminal code.",
        "source": "Vienna Police Department / Austrian Ministry of Justice",
    },
    {
        "type": "case_study",
        "jurisdiction": "Switzerland",
        "title": "Zurich Bordell Sex Trafficking (2018)",
        "summary": "Swiss police investigation into trafficking in regulated brothel system. 18 women from Thailand and Philippines. Legal status exploited by traffickers. Document confiscation and movement restriction within 'zones'. 3 convictions, victim support provided.",
        "source": "Zurich Police Department / Swiss Attorney General",
    },
    {
        "type": "case_study",
        "jurisdiction": "Poland",
        "title": "Warsaw Trafficking Ring — International Pipeline",
        "summary": "Polish authorities prosecuted trafficking network recruiting Polish women for Western Europe. Operation spanned Poland, Germany, UK. 35 women trafficked. Debt bondage €2,000-€5,000. Movement restriction through isolation. 6 traffickers convicted.",
        "source": "Warsaw Metropolitan Police / Polish National Prosecutor",
    },
    {
        "type": "case_study",
        "jurisdiction": "Czech Republic",
        "title": "Prague Escort Service Trafficking Network",
        "summary": "Czech police dismantled network trafficking Czech women domestically and to Austria. 21 women exploited. False promises of legitimate employment. Debt bondage and violence. Recruitment via online job boards. 4 traffickers prosecuted.",
        "source": "Prague Police (Policie ČR) / Czech Justice Ministry",
    },
    {
        "type": "case_study",
        "jurisdiction": "Hungary",
        "title": "Budapest Trafficking Ring — Regional Operation",
        "summary": "Hungarian prosecution of trafficking network operating across Budapest and Vienna. 28 women from Hungary, Romania, Slovakia. Operated nightclubs and escort services. Debt bondage and movement restriction. 5 convictions, cross-border coordination.",
        "source": "Budapest Police Department / Hungarian National Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "Ireland",
        "title": "Dublin Brothel Network Prosecution (2019)",
        "summary": "Irish police investigation of illegal brothel network in Dublin. 14 Asian women trafficked via false job offers. Debt bondage €3,000-€4,000. Document seizure and movement restriction. 3 traffickers convicted under Irish trafficking legislation.",
        "source": "An Garda Síochána / Irish National Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "Malaysia",
        "title": "Kuala Lumpur Massage Parlor Trafficking Ring",
        "summary": "Malaysian police raid on network operating 7 illegal massage establishments. 23 Thai women trafficked. Controlled through debt and document confiscation. Also involved coerced drug smuggling. 5 arrests, regional coordination with Thai authorities.",
        "source": "Malaysian Royal Police / IOM Malaysia",
    },
    {
        "type": "case_study",
        "jurisdiction": "Singapore",
        "title": "Singapore Outcall Escort Trafficking Network (2017)",
        "summary": "Singapore authorities prosecuted outcall escort service network. 16 Thai women trafficked via false promises. Debt bondage SGD 10,000-15,000. Movement restriction and identity documentation control. 4 convictions under EFMA (Employment of Foreign Workers Act).",
        "source": "Singapore Ministry of Manpower / Central Police Division",
    },
    {
        "type": "case_study",
        "jurisdiction": "Indonesia",
        "title": "Jakarta Trafficking Ring — Regional Hub",
        "summary": "Indonesian police dismantled trafficking operation serving as regional distribution hub. Women trafficked from provinces to Jakarta for sexual exploitation. Onward trafficking to Malaysia, Singapore. 42 women rescued, 8 traffickers arrested.",
        "source": "Jakarta Police Department / Indonesian National Police (Polri)",
    },
    {
        "type": "case_study",
        "jurisdiction": "Hong Kong",
        "title": "Hong Kong Karaoke Trafficking Network (2018)",
        "summary": "HKPF investigation of karaoke bar network exploiting women for sex work. 28 women from mainland China and Philippines. Recruited with false employment contracts. Debt bondage and movement restriction. 6 convictions, victims rehomed.",
        "source": "Hong Kong Police Force / Labour Department",
    },
    {
        "type": "case_study",
        "jurisdiction": "Taiwan",
        "title": "Taipei Sex Trafficking Ring — Organized Crime Network",
        "summary": "Taiwan authorities prosecuted organized crime-affiliated trafficking network. 19 women from Philippines and Vietnam. Controlled through violence and debt. Operated nightclubs and escort services. 5 convictions, NTD 2 million in assets seized.",
        "source": "Taipei Police Department / Taiwan National Police Agency",
    },
    {
        "type": "case_study",
        "jurisdiction": "Vietnam",
        "title": "Ho Chi Minh City Trafficking Prosecution (2019)",
        "summary": "Vietnamese authorities prosecuted trafficking network recruiting women from rural areas. Transported to HCMC for sexual exploitation. Onward trafficking to Thailand and China. 25 women rescued, 6 traffickers convicted.",
        "source": "Ho Chi Minh City Police / Vietnamese Ministry of Public Security",
    },
    {
        "type": "case_study",
        "jurisdiction": "Myanmar",
        "title": "Yangon Trafficking Ring — Border Smuggling",
        "summary": "Myanmar police investigation of network trafficking women to Thailand and China. Operated from Yangon with connections to border regions. 18 women rescued. Network supplied women to multiple destinations. Limited prosecution due to judicial constraints.",
        "source": "Yangon Police Department / UNODC Myanmar",
    },
    {
        "type": "case_study",
        "jurisdiction": "Cambodia",
        "title": "Phnom Penh Trafficking Network — Child Exploitation",
        "summary": "Cambodian authorities prosecuted network trafficking girls from rural provinces to Phnom Penh. Network targeted vulnerable children through false school/job promises. 15 girls rescued (avg age 12). 4 traffickers convicted.",
        "source": "Cambodian National Police / IOM Cambodia",
    },
    {
        "type": "case_study",
        "jurisdiction": "Laos",
        "title": "Vientiane Trafficking Network (2018)",
        "summary": "Laotian police investigation into sex trafficking organization. 12 women from Laos trafficked internally and to Thailand. Limited legal framework for prosecution. Debt bondage and movement restriction documented. 2 partial prosecutions.",
        "source": "Vientiane Police Department / UN Office on Drugs and Crime",
    },
    {
        "type": "case_study",
        "jurisdiction": "Brazil",
        "title": "São Paulo Trafficking Network — Latin American Hub",
        "summary": "Brazilian police dismantled trafficking network operating in São Paulo with connections across South America. 28 women from Paraguay, Bolivia, Brazil. Debt bondage and movement restriction. Network linked to organized crime. 7 convictions.",
        "source": "São Paulo Civil Police / Brazilian Ministry of Justice",
    },
    {
        "type": "case_study",
        "jurisdiction": "Brazil",
        "title": "Rio de Janeiro Prostitution Trafficking Ring (2019)",
        "summary": "Investigation of network operating in Rio tourist areas. 22 women from Northeast Brazil and Venezuela. Recruited via economic desperation. Controlled through debt, violence, and isolation. 5 traffickers prosecuted, victim rehabilitation programs.",
        "source": "Rio de Janeiro Military Police / Federal Police (PF)",
    },
    {
        "type": "case_study",
        "jurisdiction": "Colombia",
        "title": "Bogotá Sex Trafficking Network — Organized Crime",
        "summary": "Colombian authorities prosecuted network trafficking women across Bogotá nightlife venues. 26 women exploited, 15 from Venezuela. Debt bondage and document seizure. Network had armed security. 4 main convictions, 18 secondary arrests.",
        "source": "Bogotá Metropolitan Police (MEBOG) / National Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "Peru",
        "title": "Lima Trafficking Ring — Tourist District Operations",
        "summary": "Peruvian police investigation into trafficking network in Lima's Zona Rosa tourist district. 19 women trafficked from rural areas. Controlled through debt, violence, and document confiscation. Network included corrupt officials. 6 convictions.",
        "source": "Lima Police Division (DIH) / Peruvian National Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "Chile",
        "title": "Santiago Nightclub Trafficking Network (2017)",
        "summary": "Chilean authorities prosecuted network operating high-end nightclubs. 17 women from Colombia and Paraguay. Debt bondage and movement restriction. Network involved sophisticated money laundering. 5 convictions, asset seizure.",
        "source": "Santiago Metropolitan Police / Chilean Prosecutor's Office",
    },
    {
        "type": "case_study",
        "jurisdiction": "Argentina",
        "title": "Buenos Aires Sex Trafficking Ring",
        "summary": "Argentine police dismantled trafficking network in Buenos Aires. 25 women from Paraguay, Bolivia, and Peru. Operated escort services and illegal brothels. Debt bondage and violence. 4 convictions under Argentine trafficking law.",
        "source": "Buenos Aires Federal Police / Argentine National Prosecutor",
    },
    {
        "type": "case_study",
        "jurisdiction": "Venezuela",
        "title": "Caracas Trafficking Network — Economic Crisis Driver",
        "summary": "Documented trafficking networks exploiting economic crisis to recruit women. Venezuela became source country for trafficking to Colombia, Brazil, Caribbean. 30+ women identified. Limited prosecution due to state collapse. Regional trafficking increasing.",
        "source": "Venezuelan NGO Network / IOM Venezuela",
    },
    {
        "type": "case_study",
        "jurisdiction": "South Africa",
        "title": "Johannesburg Sex Trafficking Ring (2018)",
        "summary": "South African police investigation of network trafficking women from Zimbabwe and Lesotho. 21 women exploited in Johannesburg's red light areas. Debt bondage and violence. 5 traffickers prosecuted, victim support provided.",
        "source": "Johannesburg Metropolitan Police / South African Police Service",
    },
    {
        "type": "case_study",
        "jurisdiction": "Kenya",
        "title": "Nairobi Trafficking Network — East African Hub",
        "summary": "Kenyan authorities prosecuted trafficking network operating from Nairobi with regional connections. 18 women from Kenya, Uganda, Tanzania. Trafficked internally and to Gulf states. Debt bondage and movement restriction. 4 convictions.",
        "source": "Nairobi Police Department / Kenyan Criminal Investigation Department",
    },
    {
        "type": "case_study",
        "jurisdiction": "Nigeria",
        "title": "Lagos Trafficking Ring — Domestic Operations",
        "summary": "Nigerian authorities prosecuted trafficking network operating from Lagos. 35 young women recruited for domestic trafficking to Benin, Ghana, Cameroon. Network also supplied traffickers exporting to Europe. 6 convictions, 20+ arrests.",
        "source": "Lagos State Police / Nigerian NAPTIP",
    },
    {
        "type": "case_study",
        "jurisdiction": "Egypt",
        "title": "Cairo Trafficking Network — Exploitation of Migrants",
        "summary": "Documented trafficking network in Cairo targeting migrant women from Sub-Saharan Africa and South Asia. Women trafficked for sexual exploitation and domestic servitude. Limited legal framework and weak enforcement. Regional trafficking hub issues.",
        "source": "Cairo Police / IOM Egypt",
    },
    {
        "type": "case_study",
        "jurisdiction": "Turkey",
        "title": "Istanbul Sex Trafficking Network (2019)",
        "summary": "Turkish police investigation of network trafficking women from Eastern Europe, Central Asia, Syria. 32 women controlled through debt and document seizure. Istanbul position as key transit route. 6 major traffickers prosecuted.",
        "source": "Istanbul Police Department / Turkish National Police",
    },
    {
        "type": "case_study",
        "jurisdiction": "Lebanon",
        "title": "Beirut Trafficking Network — Middle East Operations",
        "summary": "Lebanese authorities documented trafficking network in Beirut nightlife venues. 24 women from Syria, Ukraine, Russia. Economic crisis and conflict driving trafficking. Limited prosecution due to weak enforcement. Regional coordination challenges.",
        "source": "Beirut Police / Lebanese Ministry of Interior",
    },
    {
        "type": "case_study",
        "jurisdiction": "United Arab Emirates",
        "title": "Dubai Escort Service Network (2017)",
        "summary": "UAE authorities prosecuted escort service network operating in Dubai. 19 women from Eastern Europe and Philippines. Debt bondage and document seizure. Network exploited visa restrictions. 4 convictions, deportations.",
        "source": "Dubai Police Department / UAE Ministry of Interior",
    },
    {
        "type": "case_study",
        "jurisdiction": "Saudi Arabia",
        "title": "Riyadh Trafficking Network — Domestic Worker Exploitation",
        "summary": "Documentation of trafficking networks exploiting domestic workers in Riyadh. 50+ women from Indonesia, Philippines, Ethiopia. Kafala system enabled trafficking. Movement restriction and wage theft. Limited prosecution due to kafala protections.",
        "source": "Riyadh Police / Saudi Ministry of Interior",
    },
    {
        "type": "case_study",
        "jurisdiction": "Israel",
        "title": "Tel Aviv Trafficking Ring — European Network",
        "summary": "Israeli police investigation of network trafficking women from Eastern Europe. 23 women controlled through debt bondage and violence. Tel Aviv as major trafficking destination in Middle East. 5 convictions, victim rehabilitation.",
        "source": "Tel Aviv Police / Israeli Police Major Crimes Unit",
    },
    {
        "type": "statute",
        "jurisdiction": "Canada",
        "title": "Criminal Code Section 279-280 — Trafficking Offences",
        "summary": "Canadian primary trafficking law. Section 279: trafficking (4-14 years). Section 280: trafficking minors (14 years). Applies to trafficking into/out/within Canada. Victim-centered amendments (2005) emphasize non-criminalization.",
        "source": "Canadian Criminal Code Sections 279-280",
    },
    {
        "type": "statute",
        "jurisdiction": "Brazil",
        "title": "Brazilian Criminal Code Article 231-232 — Trafficking Offences",
        "summary": "Brazilian anti-trafficking provisions. Article 231: trafficking for prostitution (3-8 years). Article 232: trafficking minors (4-10 years). Also criminalizes domestic trafficking. Recent amendments strengthen victim protection.",
        "source": "Brazilian Criminal Code (Código Penal) Articles 231-232",
    },
    {
        "type": "statute",
        "jurisdiction": "South Africa",
        "title": "Prevention and Combating of Trafficking in Persons Act 2013",
        "summary": "South African primary anti-trafficking law. Establishes National Trafficking Task Team. Penalties for trafficking: 10-20 years. Covers sexual exploitation. Victim protection and rehabilitation provisions.",
        "source": "PACOTIP Act 2013 / South African Government Gazette",
    },
    {
        "type": "advisory",
        "jurisdiction": "International",
        "title": "ECPAT International — Child Sex Tourism Prevention Framework",
        "summary": "International NGO leading efforts against child sex tourism. Code of Conduct for Tourism Businesses. Training programs for hospitality industry. 400+ member organizations. Monitoring of child sex trafficking trends in tourism destinations.",
        "source": "ECPAT International / Code of Conduct Tourism",
    },
    {
        "type": "advisory",
        "jurisdiction": "International",
        "title": "Polaris Project — National Human Trafficking Hotline & Research",
        "summary": "Leading US anti-trafficking NGO. Operates National Human Trafficking Hotline (1-888-373-7888). Conducts survivor-informed research. Produces modern slavery estimates and demand analysis. Partners with federal agencies and state task forces.",
        "source": "Polaris Project / National Human Trafficking Hotline Data",
    },
    {
        "type": "advisory",
        "jurisdiction": "International",
        "title": "International Justice Mission (IJM) — Investigations & Prosecutions",
        "summary": "International NGO conducting investigations into trafficking operations. Partners with local law enforcement for prosecutions. Operates in 15+ countries in South Asia, Southeast Asia, Africa, Latin America. Survivor-centered approach with comprehensive aftercare.",
        "source": "International Justice Mission / Organization Reports",
    },
    {
        "type": "statistic",
        "jurisdiction": "Global",
        "title": "UNODC Conviction Rate — Global Sex Trafficking Prosecution (2003-2017)",
        "summary": "99,000 trafficking prosecutions globally 2003-2017 with ~40% conviction rate. Significant variance by region: 60%+ in developed nations, 20-30% in developing nations. Sentencing averages 3-5 years globally. Enforcement gaps in source countries.",
        "source": "UNODC Global Report on Trafficking in Persons (2018)",
    },
    {
        "type": "statistic",
        "jurisdiction": "United States",
        "title": "US Federal Sex Trafficking Convictions (2015-2022)",
        "summary": "US federal system convicted 1,000+ persons for sex trafficking 2015-2022. Average sentence 150+ months (12+ years). State systems prosecute additional 2,000+ cases annually. Increasing number of prosecutions under TVPA section 1591.",
        "source": "US Sentencing Commission / DOJ Criminal Division Statistics",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "Australia",
        "title": "Criminal Code Amendment (Overseas Internet Sexual Exploitation) 2014",
        "summary": "Australian law expanded to criminalize facilitating child sex trafficking exploitation overseas. Applies to Australian citizens and corporate entities. Penalties up to 15 years. Addresses Australians participating in sex tourism.",
        "source": "Australian Criminal Code Amendment 2014 / Parliament of Australia",
    },
]
