"""Singapore migrant worker exploitation cases, MOM enforcement, and legal framework."""

SINGAPORE_CASE_FACTS: list[dict] = [
    # ── Domestic Worker Abuse Convictions ────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Gaiyathiri Murugayan [2021] — Domestic Worker Death",
        "summary": "Employer convicted of culpable homicide for systematically abusing Myanmar domestic worker Piang Ngaih Don who died from injuries. 12 months of starvation, assault, scalding, and confinement. Victim weighed 24kg at death. Sentenced to 30 years imprisonment — the longest sentence for domestic worker abuse in Singapore history.",
        "source": "Singapore High Court / Straits Times / CNA",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Lim Choon Hong and Chong Sui Foon [2016] — Starving Domestic Worker",
        "summary": "Couple convicted of starving their Filipino domestic worker Thelma Oyasan Gawidan. Victim weighed only 29.4kg when rescued, having been denied adequate food for over a year. Employers also confined her to the apartment. Lim sentenced to 3 weeks jail; Chong to 3 months. Case prompted MOM to strengthen welfare monitoring.",
        "source": "Singapore State Courts / Channel NewsAsia",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Chia Yun Ling [2014] — Assault and Imprisonment of FDW",
        "summary": "Employer convicted of voluntarily causing hurt and wrongfully confining Indonesian domestic worker. Victim beaten with household objects, burned with iron, confined to toilet as punishment. Sentenced to 11 months imprisonment. Court emphasized the vulnerability of domestic workers and the duty of employers.",
        "source": "Singapore State Courts / TODAY newspaper",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Tay Wee Kiat and Chia Yun Ling [2018] — Systematic Abuse of Two FDWs",
        "summary": "Couple convicted of abusing two Indonesian domestic workers over several years. Abuse included punching, slapping, pulling hair, and forcing workers to slap each other. Husband sentenced to 28 months; wife to 17 months (combined sentences for multiple charges). Court of Appeal upheld sentences and set sentencing framework for maid abuse cases.",
        "source": "Singapore Court of Appeal / High Court / Straits Times",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Anpalaki Muniandy Marimuthu [2019] — FDW Abuse Causing Grievous Hurt",
        "summary": "Employer convicted of voluntarily causing grievous hurt to domestic worker. Victim suffered permanent scarring from scalding with hot water and repeated assaults. Sentenced to 2 years and 2 months imprisonment. Judge noted the domestic worker's extreme vulnerability and inability to escape.",
        "source": "Singapore District Court / CNA",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Zariah bte Mohd Ali [2022] — Fatal Abuse of Domestic Worker",
        "summary": "Former teacher convicted of abusing Myanmar domestic worker Piang Ngaih Don alongside daughter Gaiyathiri. Mother-in-law participated in the abuse over 14 months. Sentenced to 6 years for abetting maid abuse. Mother-in-law was aware of daughter's sustained physical violence but did not intervene.",
        "source": "Singapore High Court / Straits Times",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Ong Chin Chin [2008] — Protracted FDW Abuse",
        "summary": "Employer convicted of maid abuse over 2 years. Indonesian domestic worker was hit with hangers, bamboo poles, and forced to stand in stress positions. Convicted of 10 charges of voluntarily causing hurt. Sentenced to 18 months imprisonment. One of the earlier landmark abuse cases that prompted enhanced penalties for domestic worker abuse.",
        "source": "Singapore Subordinate Courts / Straits Times",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Yeo Poh Kwee [2020] — Hot Oil Assault on Domestic Worker",
        "summary": "Employer splashed hot cooking oil on Indonesian domestic worker's arm as punishment for slow cooking. Victim suffered second-degree burns. Employer pleaded guilty to voluntarily causing hurt with a dangerous weapon. Sentenced to 8 months imprisonment.",
        "source": "Singapore State Courts / TODAY newspaper",
    },

    # ── Employment of Foreign Manpower Act (EFMA) Violations ──────────────
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "EFMA Conviction — Illegal Deployment and Kickback Scheme [2023]",
        "summary": "Employment agent convicted under EFMA s22(1)(d) for collecting kickbacks from foreign workers. Agent charged each worker SGD 3,000-8,000 for job placement. Workers were also illegally deployed to companies different from their Work Permit employers. Agent sentenced to 12 months imprisonment and SGD 30,000 fine.",
        "source": "MOM Enforcement / Singapore State Courts",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "EFMA s5(1) — Employer Employing Foreign Worker Without Valid Permit [2022]",
        "summary": "Construction company director convicted of employing 15 foreign workers whose work permits had expired. Workers continued to be deployed to construction sites despite irregular status. Company fined SGD 150,000 (SGD 10,000 per worker count); director sentenced to 3 months imprisonment. MOM emphasized zero tolerance for permit violations.",
        "source": "MOM Press Release / Straits Times",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "EFMA s22A — Furnishing False Information in Work Permit Application [2021]",
        "summary": "Employer convicted of declaring false salary amounts in work permit applications to circumvent foreign worker levy requirements. Declared SGD 2,500 monthly salary for S-Pass holders but paid only SGD 1,200. 7 charges, sentenced to 6 months imprisonment. MOM flagged case through salary verification checks.",
        "source": "MOM Enforcement Division / CNA",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "EFMA s22(1)(a) — Passport Retention by Employer [2019]",
        "summary": "Company director convicted of retaining passports of 23 Bangladeshi construction workers. Workers had to request permission to access their own documents. Director claimed it was for 'safekeeping' but workers testified they could not leave Singapore freely. Fined SGD 46,000 (SGD 2,000 per passport). MOM revoked company's work permit privileges.",
        "source": "MOM Enforcement / Singapore State Courts",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "EFMA s22(1)(d) — Illegal Salary Deductions from Foreign Workers [2020]",
        "summary": "Employer convicted of making unauthorized salary deductions from 40 foreign workers' pay. Deductions for accommodation, tools, and 'administrative fees' reduced effective wages below minimum standards. Total underpayment exceeded SGD 200,000. Employer ordered to make full restitution and fined SGD 80,000.",
        "source": "MOM Press Release / Straits Times",
    },

    # ── Salary Underpayment Cases ─────────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "MOM v. Kim Teck Construction — Mass Salary Non-Payment [2018]",
        "summary": "Construction company failed to pay salaries to 87 foreign workers for 3 consecutive months. Total arrears exceeded SGD 350,000. Workers housed in dormitories with no means to support themselves. MOM intervened, froze company accounts, and ensured workers received back pay. Company director convicted under Employment Act and EFMA. Company barred from hiring foreign workers.",
        "source": "MOM / Tripartite Alliance for Dispute Management (TADM)",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "ECT Claim — Systematic Underpayment of Shipyard Workers [2022]",
        "summary": "Employment Claims Tribunal awarded SGD 180,000 to 32 Bangladeshi shipyard workers whose employer had been paying 30% below contracted salary amounts. Workers were told the difference would be paid 'at end of contract' but never received it. MOM subsequently investigated and brought EFMA charges against the employer.",
        "source": "Employment Claims Tribunal / MOM",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "FDW Salary Underpayment — Agent Deduction Scheme [2021]",
        "summary": "Employment agency convicted of arranging for domestic workers' first 6-8 months salary to be diverted as 'training and placement fees.' Filipino domestic workers paid SGD 0 for the first 6 months of employment despite the legal minimum. Agency license permanently revoked. Director fined SGD 40,000.",
        "source": "MOM Employment Agency Licensing Branch / CNA",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "Landscape Maintenance Company — OT Non-Payment to Indian Workers [2023]",
        "summary": "Landscaping company convicted for failing to pay overtime to 55 Indian workers over 18 months. Workers performed 60-72 hour weeks but were paid for only 44 hours. Total underpayment: SGD 420,000. Company fined SGD 110,000. Workers received full restitution through TADM mediation.",
        "source": "MOM / TADM / Straits Times",
    },

    # ── Work Injury Compensation Cases ────────────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "WICA Claim — Construction Worker Fatal Fall [2022]",
        "summary": "Bangladeshi construction worker died after falling from 12th floor scaffolding that lacked proper safety rails. Employer had not provided fall arrest equipment. Family awarded SGD 204,000 under Work Injury Compensation Act. MOM fined the main contractor SGD 300,000 for Workplace Safety and Health Act violations. Site ordered closed for 2 weeks.",
        "source": "MOM Workplace Safety Division / Commissioner for Labour",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "WICA Dispute — Employer Denied Injury Occurred at Workplace [2021]",
        "summary": "Chinese construction worker suffered severe back injury from falling debris. Employer disputed the claim, alleging injury occurred outside work. Commissioner for Labour ruled in worker's favour after MOM inspectors confirmed site conditions. Worker awarded SGD 85,000 compensation plus medical expenses. Employer fined for failure to report workplace accident within required timeframe.",
        "source": "Commissioner for Labour / MOM",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "Shipyard Explosion — Mass WICA Claims [2020]",
        "summary": "Gas explosion at shipyard injured 14 foreign workers from India and Bangladesh. Employer initially refused to file WICA claims, telling injured workers to use their own medical insurance. MOM intervened and ensured all claims were processed. Total compensation exceeded SGD 1.2 million. Employer prosecuted for WSH Act violations.",
        "source": "MOM / Straits Times / TWC2",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "FDW Work Injury — Employer Repatriation Before Claim Settled [2019]",
        "summary": "Indonesian domestic worker suffered severe burns from cooking accident. Employer attempted to repatriate worker before WICA claim was filed. HOME intervened and obtained court order preventing departure. Worker awarded SGD 42,000 in compensation. Case highlighted vulnerability of injured FDWs to premature repatriation.",
        "source": "HOME Singapore / Commissioner for Labour",
    },

    # ── MOM Enforcement Statistics ────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "MOM Foreign Worker Enforcement Actions — 2023 Annual Statistics",
        "summary": "In 2023, MOM conducted 28,000 workplace inspections and took enforcement action against 1,200 employers for foreign worker-related violations. 340 employers were prosecuted; 860 received composition fines. Violations included salary non-payment (38%), illegal deployment (25%), work permit conditions breach (22%), and safety violations (15%).",
        "source": "MOM Annual Report 2023",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "MOM Employment Agency Enforcement — 2022-2023",
        "summary": "MOM revoked or suspended licenses of 45 employment agencies in 2022-2023 for violations including overcharging workers, deceptive practices, and deploying workers without valid permits. 120 advisory letters issued. 28 agencies faced prosecution. Total fines exceeded SGD 850,000.",
        "source": "MOM Employment Agency Licensing Branch",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "TADM Foreign Worker Salary Claims — 2023",
        "summary": "Tripartite Alliance for Dispute Management (TADM) handled 7,800 salary-related claims from foreign workers in 2023. 85% resolved through mediation (average 4 weeks). Total salary recovery: SGD 18.2 million. Construction sector accounted for 45% of claims, followed by manufacturing (22%), marine (15%), and services (18%).",
        "source": "TADM / MOM Annual Report 2023",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "Workplace Deaths Among Foreign Workers — 2019-2023 Trends",
        "summary": "Workplace fatalities involving foreign workers in Singapore: 2019 (32), 2020 (30), 2021 (37), 2022 (36), 2023 (28). Construction consistently accounts for 50-60% of deaths. Falls from height remain the leading cause. MOM heightened enforcement including Stop Work Orders (480 issued in 2023).",
        "source": "MOM Workplace Safety & Health Statistics",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "Foreign Domestic Worker Population — Singapore 2023",
        "summary": "Approximately 261,800 foreign domestic workers employed in Singapore as of December 2023. Top source countries: Philippines (40%), Indonesia (35%), Myanmar (20%), others (5%). Average monthly salary: SGD 597 (no statutory minimum wage for FDWs). 1 in 5 Singaporean households employs a domestic worker.",
        "source": "MOM Foreign Workforce Statistics / Straits Times",
    },

    # ── Employment Agency Regulation ──────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Employment Agencies Act (Cap 92) — Maximum Fee Regulation",
        "summary": "Employment agencies in Singapore may charge foreign domestic workers a maximum of 2 months' salary as placement fee (reduced from no cap prior to 2011). Agencies charging above this face license revocation and prosecution. Agency must provide itemized fee breakdown. FDW may lodge complaint with MOM within 1 year.",
        "source": "Employment Agencies Act / MOM EA Licensing Conditions",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Mandatory Employment Agency Accreditation — 2023 Update",
        "summary": "Since 2023, all employment agencies placing FDWs must achieve at least a 'Basic' rating under EA accreditation framework. Agencies rated by: worker feedback, complaint rate, compliance history. 'Good' and 'Excellent' agencies get expedited processing. Agencies below 'Basic' face license review. 1,200 licensed agencies as of 2023.",
        "source": "MOM Employment Agency Regulatory Framework",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "EA Advertising Restrictions — Dignity of FDWs [2016]",
        "summary": "MOM prohibited employment agencies from advertising domestic workers by photo with personal details displayed like consumer goods. Agencies must not use language that commodifies workers. Violations result in demerit points and potential license suspension. Policy introduced after public outcry over agencies displaying workers in 'catalogue-style' advertisements.",
        "source": "MOM Press Release 2016 / EA Licensing Conditions",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Employment Agency — Mandatory Written Contract with FDW [2019]",
        "summary": "Employment agencies must provide FDWs with written service agreements detailing: fee amounts and deduction schedule, job scope, salary, rest days, and complaints process. Agreement must be in a language the worker understands. Non-compliance results in demerit points. EA must retain signed copies for 2 years.",
        "source": "MOM EA Licensing Conditions / EFMA Regulations",
    },

    # ── Dormitory Conditions (including COVID-19) ─────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "COVID-19 Outbreak in Foreign Worker Dormitories — 2020",
        "summary": "Singapore's migrant worker dormitories became major COVID-19 clusters in April 2020. Over 175,000 workers (of 323,000 dormitory residents) tested positive by end of 2020. Workers confined to rooms for months under Stay-Home Notices. Cramped conditions (12-20 workers per room, shared facilities) made social distancing impossible. Government deployed medical teams and eventually moved 30,000 workers to alternative sites.",
        "source": "Ministry of Health Singapore / CNA / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Post-COVID Dormitory Standards Overhaul — New Living Space Requirements",
        "summary": "Following COVID-19, Singapore mandated new dormitory standards: minimum 4.5 sqm per worker (up from no minimum), maximum occupancy limits per room, improved ventilation systems, dedicated sick bays, and recreational facilities. Estimated SGD 2 billion investment to build new-generation dormitories. Deadline for compliance: 2030. 12 new Quick Build Dormitories constructed by 2022.",
        "source": "MOM / Assurance, Care and Engagement (ACE) Group",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Dormitory Operator License Suspension — Hygiene and Safety Failures [2021]",
        "summary": "Two foreign worker dormitory operators had licenses suspended for failing to meet hygiene and safety standards: pest infestation, non-functioning toilets, overcrowding beyond licensed capacity, inadequate fire safety measures. 4,000 workers relocated to compliant dormitories. Operators fined SGD 200,000 each.",
        "source": "MOM / Straits Times",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Mental Health Crisis Among Dormitory Workers — COVID-19 Lockdown Impact",
        "summary": "During the 2020-2021 dormitory lockdowns, mental health organizations reported significant increases in distress calls from foreign workers. HealthServe reported a 4x increase in mental health support requests. Issues included: isolation, uncertainty about employment, inability to send remittances, separation from families, confined living spaces. Government partnered with NGOs to provide multilingual counselling.",
        "source": "HealthServe / HOME Singapore / ILO",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "Foreign Worker Dormitory Population — 2023 Statistics",
        "summary": "Approximately 295,000 foreign workers housed in purpose-built dormitories (PBDs) and factory-converted dormitories (FCDs) in Singapore. 43 PBDs and ~1,200 FCDs licensed by MOM. New-generation dormitories include recreational rooms, mini-marts, outdoor spaces, and Wi-Fi. Average cost to worker: SGD 250-350/month deducted from salary.",
        "source": "MOM / Inter-agency Taskforce on Migrant Worker Well-being",
    },

    # ── Construction Sector Exploitation ──────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Construction Company Wage Theft Ring — Multi-Project Scheme [2022]",
        "summary": "MOM uncovered a scheme involving three related construction companies that systematically underpaid 200+ Bangladeshi and Indian workers across multiple projects. Workers paid SGD 18/day instead of the SGD 28/day contracted rate. Total underpayment over 2 years: SGD 1.8 million. Three directors prosecuted. Companies debarred from hiring foreign workers. Full restitution ordered.",
        "source": "MOM / Straits Times / TWC2",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Illegal Subcontracting Chain — Workers Deployed Without Proper Permits [2021]",
        "summary": "MOM investigation revealed a 4-tier subcontracting chain in which foreign construction workers were deployed to worksites by companies that did not hold their work permits. Workers had no employment relationship with the actual site operator. 120 workers affected. Principal employer, 2 sub-contractors, and 1 labour supplier prosecuted under EFMA s5(3) for illegal deployment.",
        "source": "MOM Enforcement / CNA",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Heat Stress Deaths on Construction Sites — 2018-2023 Pattern",
        "summary": "Multiple construction worker deaths attributed to heat stress in Singapore's tropical climate. MOM mandated heat stress management measures: water breaks every hour, shaded rest areas, monitoring of wet bulb globe temperature, work cessation at WBGT above 33C. Despite measures, TWC2 documented cases of workers pressured to continue working during heat alerts to meet project deadlines.",
        "source": "MOM WSH Advisory / TWC2 / Straits Times",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Recruitment Fee Debt Bondage — Bangladeshi Construction Workers [2023]",
        "summary": "TWC2 survey of 500 Bangladeshi construction workers found: average recruitment fee paid was SGD 8,500 (range SGD 4,000-14,000). Workers typically earn SGD 600-900/month. Debt repayment takes 10-18 months. During repayment period, workers tolerate poor conditions fearing job loss before recovering recruitment investment. Singapore prohibits employers from charging fees but enforcement focuses on Singapore-side agents only.",
        "source": "TWC2 Research / ILO",
    },

    # ── Prevention of Human Trafficking Act 2014 ──────────────────────────
    {
        "type": "law",
        "jurisdiction": "SG",
        "title": "Prevention of Human Trafficking Act 2014 (PHTA) — Overview",
        "summary": "Singapore enacted PHTA in 2015 (assented March 2014) criminalizing all forms of trafficking in persons. Key provisions: Section 3 — trafficking in persons (max 10 years + fine + caning); Section 4 — receiving payment for exploitation (max 7 years + fine); Section 5 — abetting trafficking. Applies to labour and sex trafficking. Extraterritorial jurisdiction for Singaporeans trafficking abroad.",
        "source": "Prevention of Human Trafficking Act 2014 / Singapore Statutes",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "First PHTA Prosecution — PP v. Tan Wee Guan [2017]",
        "summary": "First prosecution under the Prevention of Human Trafficking Act. Employer charged with trafficking domestic worker for labour exploitation. Worker was confined, overworked, and had freedom of movement restricted. Case demonstrated Singapore's willingness to use PHTA beyond sex trafficking. Convicted; sentenced to imprisonment and fine.",
        "source": "Singapore State Courts / MOM",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "PHTA Enforcement Statistics — 2015-2023",
        "summary": "Since enactment of PHTA: 56 trafficking cases investigated (2015-2023), 21 prosecutions, 15 convictions. Majority (65%) involved sex trafficking; 35% labour trafficking. 89 victims identified and referred to support services. Singapore remains on US TIP Report Tier 2 Watch List partly due to low prosecution numbers relative to known exploitation indicators.",
        "source": "US TIP Report / MOM / Singapore Inter-Agency Taskforce on Trafficking",
    },
    {
        "type": "law",
        "jurisdiction": "SG",
        "title": "PHTA Section 17 — Victim Protection and Support",
        "summary": "PHTA Section 17 provides for victim protection: temporary shelter, medical care, legal assistance, and temporary immigration relief. Victims may receive Special Pass to remain in Singapore during investigation and trial. National Approach Against Trafficking in Persons (NAATIP) coordinates multi-agency response including MOM, Singapore Police Force, and Ministry of Social and Family Development.",
        "source": "PHTA 2014 s17 / NAATIP Framework",
    },

    # ── Sentencing Guidelines for FDW Abuse ───────────────────────────────
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "Tay Wee Kiat Sentencing Framework — FDW Abuse Guidelines [2018]",
        "summary": "Court of Appeal in PP v. Tay Wee Kiat established a sentencing framework for maid abuse under s73 Penal Code (enhanced penalties for abuse of domestic workers). Framework considers: (1) severity of harm, (2) culpability factors (premeditation, duration, vulnerability exploitation), (3) aggravating/mitigating factors. Section 73 allows 1.5x normal penalty. Framework widely cited in subsequent maid abuse cases.",
        "source": "Singapore Court of Appeal [2018] SGCA 78",
    },
    {
        "type": "law",
        "jurisdiction": "SG",
        "title": "Penal Code s73 — Enhanced Penalties for FDW Abuse",
        "summary": "Section 73 of the Penal Code provides that where a domestic worker is the victim of certain offences (voluntarily causing hurt, wrongful confinement, criminal intimidation, etc.) committed by the employer or household member, the court may sentence up to 1.5 times the maximum punishment. Enacted in 1998 to deter exploitation of vulnerable domestic workers. Applies automatically; no special charge required.",
        "source": "Singapore Penal Code s73 / Parliamentary debates 1998",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. BDB [2018] — Framework for Assault Causing Grievous Hurt to FDW",
        "summary": "High Court established sentencing framework for s325 Penal Code (voluntarily causing grievous hurt) in the context of domestic worker abuse. Two-step framework: (1) indicative starting sentence based on seriousness of injury, (2) adjustment for aggravating/mitigating factors. Framework: permanent disfigurement or serious disability = 3.5-7 years; multiple fractures = 2-3.5 years. With s73 enhancement, maximum is 15 years.",
        "source": "Singapore High Court [2018] SGHC 127",
    },

    # ── TWC2 and HOME Data ────────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "TWC2 Annual Caseload — Foreign Worker Assistance 2023",
        "summary": "Transient Workers Count Too (TWC2) assisted 4,200 foreign workers in 2023. Most common issues: salary non-payment (42%), work injury claims (28%), wrongful termination (15%), poor living conditions (8%), assault/abuse (7%). 85% of cases involved construction or marine sector workers. TWC2 operates a free meal program serving 36,000 meals annually to destitute workers awaiting claim resolution.",
        "source": "TWC2 Annual Report 2023",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "HOME Case Statistics — Domestic Worker Assistance 2023",
        "summary": "Humanitarian Organisation for Migration Economics (HOME) handled 1,800 cases in 2023: domestic worker abuse (35%), salary disputes (25%), trafficking referrals (10%), employment agency complaints (15%), repatriation issues (15%). HOME operates a shelter housing up to 60 domestic workers at any time. Average shelter stay: 3-6 months while cases are resolved.",
        "source": "HOME Singapore Annual Report 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "TWC2 Research — Injury Claims Processing Delays",
        "summary": "TWC2 documented that injured foreign workers wait an average of 9-14 months for WICA claims to be resolved. During this period, workers cannot work (Special Pass does not allow employment), cannot return home (must attend medical appointments), and receive only SGD 35/day temporary disability pay. Many workers exhaust savings and rely on NGO food programs. TWC2 advocates for interim work rights.",
        "source": "TWC2 Research Papers / Price of a Better Life Report",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "HOME — Debt Bondage Through Agency Fee Recovery [2022]",
        "summary": "HOME documented 340 cases of domestic workers experiencing effective debt bondage through agency fee structures in 2022. Workers pay agencies SGD 2,000-4,000 (often deducted over 6-8 months salary). Workers cannot change employers during repayment without forfeiting fees already paid. HOME called the practice 'structural debt bondage' and advocated for employer-pays model.",
        "source": "HOME Singapore Research / Straits Times",
    },

    # ── Security Bond System ──────────────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "FDW Security Bond — SGD 5,000 Requirement",
        "summary": "Employers of foreign domestic workers must post a SGD 5,000 security bond with MOM. Bond is forfeited if worker goes missing, becomes unlawfully employed, or becomes a public charge. Critics argue the bond creates perverse incentives: employers restrict workers' freedom of movement on rest days to prevent bond forfeiture. MOM counters that the bond ensures employer responsibility for worker welfare.",
        "source": "EFMA Regulations / MOM FDW Policy",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Security Bond Forfeiture Disputes — Runaway FDW Cases [2022]",
        "summary": "Multiple cases of employers losing SGD 5,000 security bond when domestic workers left employment. Some employers had committed abuse; workers fled to HOME or police. Employers challenged bond forfeiture, claiming workers absconded without cause. MOM's position: bond forfeiture is administrative, not punitive; abuse allegations are investigated separately. HOME documented cases where fear of bond forfeiture deterred employers from allowing FDWs rest days outside the home.",
        "source": "HOME Singapore / TADM records / Straits Times",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Security Bond Conditions — Movement Restriction Controversy",
        "summary": "NGOs (HOME, TWC2, AWARE) have repeatedly called for reform of the security bond system, arguing it incentivizes employers to confine domestic workers. MOM response: bond conditions were updated in 2019 to clarify that employers must not unreasonably restrict FDWs' movement on rest days. However, enforcement relies on worker complaints, and many workers fear repatriation if they report restrictions.",
        "source": "AWARE Policy Paper / HOME Research / MOM Press Release 2019",
    },

    # ── Foreign Domestic Worker Levy ──────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "FDW Monthly Levy — Current Rates and Structure",
        "summary": "Employers pay a monthly levy to the government for each FDW employed. Standard rate: SGD 300/month; concessionary rate: SGD 60/month (for households with young children, elderly, or persons with disabilities). Levy collected via GIRO. Levy is employer's cost and must not be passed to worker. MOM investigates cases of employers deducting levy from FDW salary (EFMA violation).",
        "source": "MOM FDW Levy Policy / EFMA Regulations",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Employer Passing FDW Levy to Worker — Prosecution [2020]",
        "summary": "Employer convicted under EFMA for deducting the SGD 300 monthly levy from domestic worker's salary over 18 months. Total illegal deduction: SGD 5,400. Worker paid only SGD 300/month instead of contracted SGD 600. Employer fined SGD 10,000 and ordered to repay deducted amounts. MOM emphasized that levy is exclusively the employer's obligation.",
        "source": "MOM / Singapore State Courts",
    },

    # ── Medical Examination Requirements ──────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "FDW Mandatory 6-Monthly Medical Examination",
        "summary": "Foreign domestic workers must undergo medical examination every 6 months (within 14 days of 6-month mark). Tests include: pregnancy, HIV, syphilis, and tuberculosis screening. If a worker is found pregnant, the work permit is revoked. This pregnancy termination provision has been criticized by human rights groups as coercive. Cost borne by employer (SGD 50-80 per examination).",
        "source": "EFMA Conditions of Work Permit (FDW) / MOM",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "FDW Pregnancy — Work Permit Revocation Controversy",
        "summary": "Human rights organizations (HOME, CEDAW Committee, HRW) have criticized Singapore's policy of revoking FDW work permits upon pregnancy. Workers face deportation, creating pressure to undergo abortions or hide pregnancies. HOME documented cases of pregnant FDWs being repatriated without final salary. CEDAW Committee (2017) recommended Singapore remove the pregnancy test requirement and permit revocation policy. Government position: unchanged as of 2024.",
        "source": "CEDAW Concluding Observations on Singapore 2017 / HOME / HRW",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "FDW Medical Insurance Requirement — Employer Obligation",
        "summary": "Employers must purchase medical insurance for FDWs with minimum coverage of SGD 15,000 per year (increased from SGD 5,000 in 2019). Insurance must cover inpatient care, day surgery, and outpatient treatment. Employers must also bear costs of FDW's medical treatment up to the insurance coverage limit. FDWs should not be made to pay for their own medical expenses.",
        "source": "EFMA Conditions of Work Permit / MOM Circular 2019",
    },

    # ── Transfer and Release Process ──────────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "FDW Transfer Process — Employer Consent Requirement",
        "summary": "Foreign domestic workers cannot change employers without a Letter of Release from the current employer or MOM approval. Process: employer issues letter → worker has 1 month to find new employer → new employer applies for work permit transfer. If employer refuses to issue letter, FDW must return home and be re-recruited. HOME and TWC2 argue this creates employer dependency. MOM can issue release in abuse cases.",
        "source": "MOM FDW Transfer Policy / EFMA Regulations",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "FDW Transfer Denied — Employer Refuses Letter of Release [2022]",
        "summary": "HOME documented 280 cases in 2022 where employers refused to issue Letters of Release for FDWs seeking to change employers. Common reasons cited: not wanting to lose recruitment investment, punishing workers for complaints, retaining control. Workers faced choice: tolerate conditions or return home at own expense. MOM intervened in 40% of cases upon NGO referral. HOME advocates for abolition of employer consent requirement.",
        "source": "HOME Singapore Case Records / Straits Times",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Work Permit Cancellation as Retaliation — MOM Investigation [2021]",
        "summary": "MOM investigated 15 cases where employers cancelled FDW work permits shortly after workers filed salary or abuse complaints. Pattern: worker reports to MOM or police → employer cancels work permit → worker given 1-2 weeks to leave Singapore. MOM issued Special Passes for workers to remain during investigation but acknowledged the gap between permit cancellation and Special Pass issuance creates vulnerability.",
        "source": "MOM / HOME Singapore / TWC2",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Work Permit Holders — No Transfer Between Sectors",
        "summary": "Foreign workers on Work Permits cannot transfer between employment sectors (e.g., construction to manufacturing). Workers must return to home country and be re-recruited for a different sector. This rigidity means workers who face exploitation in one sector cannot easily move to better conditions. Exception: MOM may approve sector change in exceptional circumstances such as company closure.",
        "source": "EFMA Work Permit Conditions / MOM Policy",
    },

    # ── Additional Enforcement and Policy ─────────────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Mandatory Weekly Rest Day for FDWs — 2013 Policy",
        "summary": "From January 2013, employers must provide FDWs with one rest day per week or compensate in-lieu at the worker's agreement. Before 2013, there was no mandatory rest day. Compensation in-lieu must equal one day's salary. HOME surveys indicate that in practice, 40% of FDWs still do not receive a weekly rest day, often due to employer pressure to accept compensation that may not actually be paid.",
        "source": "EFMA Conditions / MOM Press Release 2012 / HOME Survey 2022",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Settling-In Programme (SIP) — Mandatory FDW Orientation",
        "summary": "All first-time FDWs in Singapore must attend a one-day Settling-In Programme within 3 days of arrival. SIP covers: Singapore laws, worker rights, safety at home, stress management, and where to seek help (MOM, police, NGOs). Conducted in worker's native language. Cost: SGD 75 (borne by employer). SIP is also mandatory for first-time FDW employers since 2019 (Employers' Orientation Programme).",
        "source": "MOM / Accredited SIP training centres",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "Foreign Workforce in Singapore — 2023 Composition",
        "summary": "Singapore's foreign workforce (excluding foreign domestic workers): 1.17 million workers on Work Permits and S-Passes as of December 2023. Breakdown: construction (320,000), manufacturing (250,000), marine shipyard (65,000), process (40,000), services (495,000). Top source countries: Bangladesh, India, China, Myanmar. Total with FDWs and Employment Pass holders: approximately 1.6 million foreign workers.",
        "source": "MOM Foreign Workforce Statistics Q4 2023",
    },
    {
        "type": "law",
        "jurisdiction": "SG",
        "title": "Employment of Foreign Manpower Act (EFMA) — Key Provisions",
        "summary": "EFMA (Cap 91A) is Singapore's primary legislation governing foreign worker employment. Key provisions: s5 — offence to employ without valid work pass (fine up to SGD 30,000 or 12 months jail per worker); s10 — conditions of work passes (employer obligations); s22 — offences including document retention, kickbacks, false declarations; s22A — furnishing false information. Maximum penalties increased in 2012 amendments.",
        "source": "Employment of Foreign Manpower Act (Cap 91A) / Singapore Statutes",
    },
    {
        "type": "law",
        "jurisdiction": "SG",
        "title": "Employment Act (Cap 91) — Coverage of Foreign Workers",
        "summary": "Singapore's Employment Act covers all employees (including foreign workers on Work Permits and S-Passes) except domestic workers, seafarers, and statutory board employees. Protections include: salary payment within 7 days, overtime pay (1.5x for workers earning up to SGD 2,600), rest days, annual leave, and sick leave. FDWs are excluded from most Employment Act protections — a significant gap criticized by ILO and NGOs.",
        "source": "Employment Act (Cap 91) / MOM / ILO CEACR Observations",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Repatriation Without Final Salary — Common Pattern [2023]",
        "summary": "TWC2 documented 180 cases in 2023 where employers repatriated foreign workers without paying final salary and outstanding overtime. Workers booked onto flights with 24-48 hours notice, preventing them from filing MOM complaints. TWC2 assists workers in filing claims from home countries but acknowledges low recovery rates (30%) for post-departure claims. MOM introduced online claims portal to address this.",
        "source": "TWC2 Annual Report / MOM Online Claims System",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Employer-Arranged Return Flights as Control Mechanism [2022]",
        "summary": "HOME and TWC2 documented employer use of return flight booking as a threat and control mechanism. Employers purchase one-way tickets and tell workers they will be sent home if they complain or refuse overtime. Workers, fearing loss of recruitment fee investment, comply with exploitative conditions. MOM advises workers to contact authorities before departure but acknowledges practical barriers.",
        "source": "HOME Singapore / TWC2 / Straits Times",
    },
    {
        "type": "advisory",
        "jurisdiction": "SG",
        "title": "US TIP Report — Singapore Assessment 2023",
        "summary": "The US Trafficking in Persons Report 2023 placed Singapore on Tier 2 Watch List. Key concerns: insufficient PHTA prosecutions relative to exploitation indicators, continued conflation of trafficking with smuggling in enforcement, security bond incentivizing employer restriction of FDW movement, FDWs excluded from Employment Act, and mandatory pregnancy testing linked to permit revocation.",
        "source": "US Department of State TIP Report 2023 — Singapore Country Narrative",
    },
    {
        "type": "advisory",
        "jurisdiction": "SG",
        "title": "ILO CEACR Observations — Singapore Forced Labour Convention",
        "summary": "ILO Committee of Experts on the Application of Conventions and Recommendations (CEACR) has made repeated observations on Singapore's implementation of Forced Labour Convention (C29). Key concerns: employer-tied work permits creating dependency, security bond restricting FDW mobility, recruitment fee structures creating debt bondage indicators, need for stronger PHTA enforcement.",
        "source": "ILO CEACR Direct Requests — Singapore / NORMLEX",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Progressive Wage Model — Migrant Worker Inclusion Debate",
        "summary": "Singapore's Progressive Wage Model (PWM) sets minimum wages for specific sectors (cleaning, security, landscape). As of 2023, PWM applies only to Singaporeans and permanent residents, not to foreign workers on Work Permits. This creates a dual wage system where foreign workers in the same roles may earn significantly less. NTUC and some MPs have called for extending PWM to foreign workers. Government position: under review.",
        "source": "MOM / NTUC / Parliamentary Questions 2023",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "ECT and TADM Foreign Worker Claims — Resolution Statistics 2023",
        "summary": "Employment Claims Tribunals (ECT) handled 2,400 foreign worker claims in 2023 (up from 1,800 in 2022). Success rate for workers: 65% received some payment; 40% received full claimed amount. Average claim amount: SGD 4,200. Average time from filing to resolution: 8 weeks. Claims filed after worker departure: 35% success rate (vs 65% for claims filed while in Singapore).",
        "source": "ECT / TADM / Ministry of Manpower",
    },
    {
        "type": "court_ruling",
        "jurisdiction": "SG",
        "title": "PP v. Oh Kok Kiong [2019] — Trafficking for Labour Exploitation",
        "summary": "Employer convicted under PHTA for trafficking two Chinese nationals for labour exploitation. Workers deceived about job nature and salary, then forced to work as unlicensed moneylenders. Passports confiscated, movement restricted, wages withheld. Sentenced to 6 years and 8 months imprisonment plus 6 strokes of the cane. One of few PHTA labour trafficking convictions.",
        "source": "Singapore High Court / CNA / MOM",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "MOM Digital Claims Portal — Foreign Workers [2023]",
        "summary": "MOM launched enhanced digital claims portal allowing foreign workers to file salary and injury claims online, including from their home countries after departure. Portal available in 8 languages (English, Mandarin, Malay, Tamil, Bengali, Thai, Burmese, Tagalog). SMS notification system for case updates. Aim: reduce dependency on NGO intermediaries and improve post-departure claim rates.",
        "source": "MOM Press Release / Straits Times 2023",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "COVID-19 Worker Support Package — Government Intervention 2020",
        "summary": "Singapore government spent approximately SGD 1.3 billion on migrant worker COVID-19 response: testing (all 323,000 dormitory workers), medical treatment, temporary housing, food provision, and dormitory cleaning/disinfection. Created Forward Assurance and Support Teams (FAST) deployed to dormitories. Allocated SGD 100 million for improved recreational facilities. Workers received free SIM cards and Wi-Fi for family contact.",
        "source": "Ministry of Finance / ACE Group / MOM",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Electronic Medical Certificate (eMC) for Foreign Workers [2022]",
        "summary": "MOM mandated electronic medical certificates for foreign worker sick leave to prevent employer fraud (destroying paper MCs to deny sick leave). eMC system directly notifies MOM and employer when worker receives medical leave. TWC2 had documented cases of employers confiscating paper MCs and demanding workers continue working while ill. eMC system launched July 2022.",
        "source": "MOM / TWC2 Advocacy / Straits Times",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Marine Sector Worker Exploitation — Shipyard Practices [2023]",
        "summary": "TWC2 reported that marine shipyard sector continues to have high rates of exploitation despite MOM oversight. Issues include: 70-80 hour work weeks with overtime pay calculated incorrectly, exposure to hazardous materials (asbestos, paint fumes) without adequate PPE, housing in converted containers near industrial areas, and recruitment fees averaging SGD 6,000-10,000 for Indian and Bangladeshi workers.",
        "source": "TWC2 / MOM WSH Enforcement / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "SG",
        "title": "Process Sector — Chemical Plant Foreign Worker Exposure [2022]",
        "summary": "MOM investigated chemical processing plant after 8 Indian workers reported chronic respiratory symptoms. Workers had been assigned to handle toxic solvents without proper respiratory PPE for 6 months. Company provided cloth masks instead of required chemical cartridge respirators. 3 workers hospitalized. Company fined SGD 250,000 under WSH Act; safety officer's certification suspended.",
        "source": "MOM WSH Division / Straits Times",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "SG",
        "title": "Foreign Employee Dormitories Act 2015 — Licensing Framework",
        "summary": "The Foreign Employee Dormitories Act (FEDA) 2015 established a licensing regime for dormitories housing 1,000+ foreign workers. Requirements include: minimum living space, maintenance standards, provision of amenities (cooking, laundry, recreation), operator compliance with fire safety, and accessible complaint mechanisms. MOM can revoke licenses for non-compliance. As of 2023, 43 purpose-built dormitories are FEDA-licensed.",
        "source": "Foreign Employee Dormitories Act 2015 / MOM",
    },
]
