"""Global, regional, and sectoral statistics on forced labour and trafficking."""

STATISTIC_FACTS: list[dict] = [
    # ── Existing global estimates ─────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Global Modern Slavery Estimates 2022",
        "metric": "Total victims of modern slavery",
        "value": "49.6 million",
        "year": 2022,
        "details": "ILO, Walk Free, and IOM joint estimate. Includes 27.6M in forced labour and 22M in forced marriage. Increased by 10M from 2016 estimates.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Forced Labour in Private Economy",
        "metric": "Forced labour in private sector exploitation",
        "value": "17.3 million",
        "year": 2022,
        "details": "Private sector forced labour includes domestic work (23%), construction, manufacturing, agriculture, fishing. 86% of all forced labour occurs in private economy.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "State-Imposed Forced Labour",
        "metric": "State-imposed forced labour victims",
        "value": "3.9 million",
        "year": 2022,
        "details": "Imposed by state authorities including prison labour, compulsory military labour, and state-mandated work. ILO Global Estimates 2022.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Children in Forced Labour",
        "metric": "Child victims of forced labour",
        "value": "3.3 million",
        "year": 2022,
        "details": "Children aged 0-17 in forced labour. Often in agriculture, domestic work, and manufacturing. ILO-UNICEF joint estimates.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Forced Labour Profits",
        "metric": "Annual illegal profits from forced labour",
        "value": "USD 236 billion",
        "year": 2024,
        "details": "ILO Profits and Poverty report (2024). Up from USD 150B (2014). Forced commercial sexual exploitation generates USD 173B. Other forced labour generates USD 63B.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Domestic Worker Forced Labour",
        "metric": "Share of forced labour in domestic work",
        "value": "23%",
        "year": 2022,
        "details": "Domestic work accounts for 23% of all forced labour in the private economy. Predominantly affects women and girls. Isolation in private households hinders detection.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Asia-Pacific Forced Labour Prevalence",
        "metric": "Forced labour victims in Asia-Pacific",
        "value": "15.1 million",
        "year": 2022,
        "details": "Asia-Pacific has the highest absolute number of forced labour victims (55% of global total). Key sectors: domestic work, construction, manufacturing, fishing.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Migrant Worker Forced Labour",
        "metric": "Migrant workers in forced labour",
        "value": "12.6%",
        "year": 2022,
        "details": "International migrant workers are 3x more likely to be in forced labour than non-migrant workers. Recruitment fees and debt bondage are primary mechanisms.",
    },

    # ── New regional statistics ───────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Africa Forced Labour Estimates",
        "metric": "Forced labour victims in Africa",
        "value": "7.0 million",
        "year": 2022,
        "details": "Sub-Saharan Africa has highest prevalence rate (5.2 per 1,000). Includes agricultural labour, domestic work, mining, and child labour. ILO Global Estimates 2022.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Arab States Forced Labour Estimates",
        "metric": "Forced labour victims in Arab States",
        "value": "1.7 million",
        "year": 2022,
        "details": "Highest prevalence rate globally (5.3 per 1,000). Driven by kafala system, construction boom, and domestic worker exploitation. GCC countries are primary destinations.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Europe and Central Asia Forced Labour Estimates",
        "metric": "Forced labour victims in Europe/Central Asia",
        "value": "6.4 million",
        "year": 2022,
        "details": "Includes forced labour in agriculture, construction, hospitality, and domestic work. Significant trafficking from Eastern Europe and Central Asia to Western Europe.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Americas Forced Labour Estimates",
        "metric": "Forced labour victims in Americas",
        "value": "3.6 million",
        "year": 2022,
        "details": "Includes agricultural forced labour, domestic servitude, and forced sexual exploitation. Key corridors: Central America to US, Bolivia/Paraguay to Brazil/Argentina.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Women and Girls in Forced Labour",
        "metric": "Female share of forced labour victims",
        "value": "54%",
        "year": 2022,
        "details": "Women and girls make up 54% of all forced labour victims. Overwhelmingly concentrated in domestic work and commercial sexual exploitation. ILO Global Estimates 2022.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Debt Bondage Prevalence",
        "metric": "Forced labour involving debt bondage",
        "value": "50%",
        "year": 2022,
        "details": "Half of all forced labour cases involve debt bondage. Recruitment fees are the primary mechanism. Average debt: 4-9 times monthly salary in many corridors.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Average Duration of Forced Labour",
        "metric": "Mean time in forced labour before escape/rescue",
        "value": "20.5 months",
        "year": 2022,
        "details": "Average duration of forced labour episode is 20.5 months. Some cases last years. Domestic workers and those under kafala face longest durations.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Trafficking Conviction Rate",
        "metric": "Global trafficking conviction rate",
        "value": "0.04%",
        "year": 2022,
        "details": "Only approximately 1 in 2,500 trafficking cases globally results in a conviction. UNODC Global Report on Trafficking in Persons. Identification and prosecution remain major challenges.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Domestic Workers in Forced Labour",
        "metric": "Domestic workers in forced labour globally",
        "value": "8.5 million",
        "year": 2022,
        "details": "8.5M domestic workers in forced labour. 73% are women. ILO C189 ratified by only 36 countries. GCC countries, HK, SG, and MY are major destinations.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Recruitment Fee Burden",
        "metric": "Average recruitment fee as multiple of monthly salary",
        "value": "4-9x monthly salary",
        "year": 2023,
        "details": "Migrant workers pay 4-9 times their expected monthly salary in recruitment fees. Bangladesh workers report highest fees (6-12x). ILO fair recruitment initiative benchmark.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Wage Theft from Migrant Workers",
        "metric": "Estimated annual wage theft from migrant workers",
        "value": "USD 8 billion",
        "year": 2023,
        "details": "ILO estimates USD 8 billion annually stolen from migrant workers through non-payment, underpayment, illegal deductions, and unpaid overtime. GCC countries are a major contributor.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "COVID-19 Impact on Modern Slavery",
        "metric": "Increase in modern slavery 2016-2021",
        "value": "10 million",
        "year": 2022,
        "details": "10 million more people in modern slavery in 2021 compared to 2016. COVID-19 pandemic exacerbated vulnerability through job losses, travel restrictions, and reduced oversight.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Intra-Regional Trafficking",
        "metric": "Trafficking victims trafficked within their region",
        "value": "73%",
        "year": 2022,
        "details": "73% of trafficking victims are exploited within their own region. Cross-border but intra-regional trafficking dominates. UNODC Global Report on Trafficking in Persons.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Trafficking Victim Gender Distribution",
        "metric": "Women and girls as share of trafficking victims",
        "value": "71%",
        "year": 2022,
        "details": "Women and girls make up 71% of detected trafficking victims globally. Men increasingly identified in labour trafficking (construction, fishing, agriculture). UNODC 2022.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Child Trafficking Victims",
        "metric": "Children as share of trafficking victims",
        "value": "25%",
        "year": 2022,
        "details": "1 in 4 detected trafficking victims are children. Girls disproportionately affected. Forced begging, domestic work, and sexual exploitation are primary forms.",
    },
    {
        "type": "statistic",
        "jurisdiction": "PH",
        "title": "Philippines Remittance Dependency",
        "metric": "Annual OFW remittances",
        "value": "USD 36.1 billion",
        "year": 2023,
        "details": "OFW remittances make up ~9% of Philippine GDP. Creates systemic pressure to maintain labour export despite risks. 10.2 million Filipinos work abroad.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Forced Labour by Sector — Construction",
        "metric": "Construction share of private-sector forced labour",
        "value": "18%",
        "year": 2022,
        "details": "Construction accounts for 18% of forced labour in the private economy. Key corridors: South Asia to Gulf (NP-QA, BD-SA, IN-AE). Debt bondage is primary mechanism.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Forced Labour in Fishing",
        "metric": "Forced labour in fishing industry",
        "value": "128,000",
        "year": 2022,
        "details": "An estimated 128,000 workers in forced labour on fishing vessels globally. Key region: Southeast Asia (TH, MY, ID waters). Workers confined to vessels for months. EJF/ILO data.",
    },
    # ── Additional Statistics (expanded) ─────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Trafficking Profits — Global Estimate",
        "metric": "Annual trafficking profits",
        "value": "USD 150 billion",
        "year": 2022,
        "details": "ILO estimates forced labour generates USD 150B/year in illegal profits. Forced sexual exploitation: USD 99B. Domestic work: USD 8B. Agriculture: USD 9B. Other sectors: USD 34B. Asia-Pacific generates most profits (USD 51.8B). Profits per victim: USD 6,200 average.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Trafficking Conviction Rates — Global",
        "metric": "Conviction rate",
        "value": "0.04%",
        "year": 2022,
        "details": "Only 0.04% of trafficking cases globally result in conviction. 10,500 prosecutions globally (2022). 5,260 convictions. Compared to estimated 27.6M victims. Prosecution rates highest in: US, Netherlands, UK. Lowest in: Gulf states, most of Africa and Asia. Victim identification is primary bottleneck.",
    },
    {
        "type": "statistic",
        "jurisdiction": "UK",
        "title": "UK NRM Referrals — Trafficking Victim Identification",
        "metric": "Annual NRM referrals",
        "value": "17,004",
        "year": 2023,
        "details": "17,004 potential trafficking victims referred to UK National Referral Mechanism (2023). Top nationalities: Albanian (19%), UK (17%), Vietnamese (7%), Eritrean (5%). Labour exploitation: 40%. Sexual exploitation: 25%. Criminal exploitation: 20%. Reasonable grounds decision: 85%+ positive rate.",
    },
    {
        "type": "statistic",
        "jurisdiction": "US",
        "title": "US T-Visa Grants for Trafficking Victims",
        "metric": "Annual T-visa approvals",
        "value": "~2,000",
        "year": 2023,
        "details": "~2,000 T-visas approved annually (cap: 5,000, rarely reached). Total since 2001: ~18,000. T-visa provides: 4-year stay, work authorization, path to permanent residency. Derivative visas for family members. Annual applications: ~3,500. Approval rate: ~55%. Processing time: 18-24 months.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "US TIP Report Country Tier Rankings Distribution",
        "metric": "Tier ranking distribution",
        "value": "188 countries ranked",
        "year": 2023,
        "details": "Tier 1 (fully compliant): 30 countries. Tier 2: 96 countries. Tier 2 Watch List: 40 countries. Tier 3 (no effort): 22 countries. Tier 3 triggers sanctions. Key destination countries: SA (T2WL), QA (T2WL), MY (T2WL), AE (T2), SG (T2), HK (T2). Origins: PH (T1), ID (T2), NP (T2), BD (T2).",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Recruitment Fee Averages by Corridor (USD)",
        "metric": "Average recruitment fees",
        "value": "USD 1,200-10,000 depending on corridor",
        "year": 2023,
        "details": "Corridor averages: BD-SA USD 3,500, NP-QA USD 1,800, PH-SA USD 900 (zero-fee policy partially enforced), VN-JP USD 7,500 (highest), ID-MY USD 1,400, MM-TH USD 750, ET-SA USD 1,500, PH-HK USD 1,100, KH-TH USD 400, BD-MY USD 2,500, ID-HK USD 2,500.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Worker Deaths Abroad — Construction Sector",
        "metric": "Annual migrant worker deaths abroad",
        "value": "Thousands annually (underreported)",
        "year": 2023,
        "details": "Nepal: 1,600+ workers died abroad (2022, FEB data). India: 8,000+ died in Gulf (2012-2022, wire services). QA: 6,500+ deaths 2010-2020 (The Guardian estimate). SA: data not published. Common causes: cardiac arrest (suspected heat-related), falls, vehicle accidents. Heat-related deaths underreported: cause listed as 'natural causes' or 'cardiac arrest.'",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Number of Licensed Recruitment Agencies by Origin Country",
        "metric": "Licensed agencies",
        "value": "Varies by country",
        "year": 2023,
        "details": "PH: 1,200+ licensed agencies (DMW). BD: 1,200+ licensed (BMET). NP: 900+ licensed (DFE). ID: 500+ licensed (BNP2MI). VN: 400+ licensed (DOLAB). For every licensed agency, estimated 2-5 unlicensed sub-agents operate in recruitment chain. Enforcement: 50-100 licenses revoked per year in PH, fewer in other countries.",
    },
    {
        "type": "statistic",
        "jurisdiction": "BD",
        "title": "Bangladesh Remittance Dependency",
        "metric": "Annual remittances",
        "value": "USD 21.6 billion",
        "year": 2023,
        "details": "Remittances = 5.4% of GDP. 7.5M Bangladeshis working abroad. Top destinations: SA (2.5M), AE (1M), MY (800K), QA (400K), OM (400K). BMET manages deployment of 700,000+ workers annually. Remittances are second-largest source of foreign exchange after garment exports.",
    },
    {
        "type": "statistic",
        "jurisdiction": "NP",
        "title": "Nepal Remittance Dependency",
        "metric": "Annual remittances",
        "value": "USD 8.3 billion",
        "year": 2023,
        "details": "Remittances = 25% of GDP (one of highest ratios globally). 3.5M Nepalis abroad. Top destinations: QA, SA, AE, MY, KR, JP. 500,000+ deployed annually. FEB records 1,600+ worker deaths abroad annually. Economic dependency creates systemic pressure to maintain labour migration despite exploitation risks.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Duration of Forced Labour Before Escape/Rescue",
        "metric": "Average duration",
        "value": "20.5 months",
        "year": 2022,
        "details": "Average duration in forced labour before escape, rescue, or release: 20.5 months (ILO 2022). State-imposed: 52 months. Sexual exploitation: 23 months. Other forced labour: 17 months. Fishing: 24-36 months (longest in private sector). Domestic work: 12-18 months. Construction: 18-24 months.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "COVID-19 Impact on Modern Slavery",
        "metric": "Increase in modern slavery",
        "value": "10 million increase (2016-2021)",
        "year": 2022,
        "details": "10M more people in modern slavery in 2021 vs 2016 (ILO). COVID drivers: job losses pushed workers into exploitative situations, border closures trapped workers with abusive employers, online recruitment scams surged, child labour increased (8.4M more). Domestic work and online exploitation saw largest increases.",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Repeat Trafficking Rates",
        "metric": "Re-trafficking rate",
        "value": "20-40%",
        "year": 2022,
        "details": "Estimated 20-40% of trafficking victims are re-trafficked within 2 years of return. Drivers: outstanding debt, lack of alternative livelihood, family pressure, same recruitment networks targeting returnees. Prevention programs (vocational training, microfinance) reduce rate to 5-10% but are underfunded and reach <10% of returnees.",
    },
]
