"""Corporate supply chain forced labour cases and accountability frameworks."""

SUPPLY_CHAIN_FACTS: list[dict] = [
    # ── Withhold Release Orders (US CBP) ─────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US CBP Withhold Release Order — Sime Darby Plantation (Malaysia Palm Oil)",
        "sector": "palm_oil",
        "exploitation_type": "debt_bondage",
        "summary": "US CBP issued WRO against Sime Darby Plantation Berhad (Dec 2020) for forced labour indicators including debt bondage, passport retention, and excessive overtime on Malaysian palm oil plantations. Blocked all US imports. Revoked Jan 2023 after remediation.",
        "source": "US Customs and Border Protection",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US CBP WRO — FGV Holdings (Malaysia Palm Oil)",
        "sector": "palm_oil",
        "exploitation_type": "debt_bondage",
        "summary": "WRO against FGV Holdings Berhad (Sep 2020) for 11 ILO forced labour indicators on palm oil plantations. Workers from Indonesia, Bangladesh, India, Philippines. Recruitment fees USD 2,000-5,000 creating debt bondage. Products blocked at US ports.",
        "source": "US CBP / Wall Street Journal investigation",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US CBP WRO — Top Glove Corporation (Malaysia Rubber Gloves)",
        "sector": "manufacturing",
        "exploitation_type": "debt_bondage",
        "summary": "WRO against Top Glove (Mar 2021), world's largest rubber glove manufacturer. Workers from Bangladesh, Nepal paid USD 1,000-5,000 recruitment fees. Passport confiscation, cramped dormitories (25-50 workers per room). COVID-19 outbreaks. WRO revoked Sep 2021 after USD 33M remediation.",
        "source": "US CBP / Reuters",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US CBP WRO — Natchi Apparel (India Garments)",
        "sector": "garment",
        "exploitation_type": "excessive_overtime",
        "summary": "WRO against Natchi Apparel (Nov 2021) for Sumangali scheme exploitation of young Tamil women in spinning mills. Workers recruited as adolescents with promise of lump-sum payment after 3-5 years. Excessive overtime, restricted movement, below-minimum wages.",
        "source": "US CBP / Anti-Slavery International",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US CBP WRO — Chinese Seafood Processing (Forced Labour)",
        "sector": "fishing",
        "exploitation_type": "restriction_of_movement",
        "summary": "Multiple WROs against Chinese seafood processors (2021-2023) including Dalian Ocean Fishing and others. North Korean workers in forced labour conditions. Products transshipped through third countries. Linked to IUU fishing and forced labour on distant-water vessels.",
        "source": "US CBP / Outlaw Ocean Project",
    },
    # ── EU and National Legislation ──────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "EU",
        "title": "EU Forced Labour Import Ban Regulation (2024)",
        "sector": "multiple",
        "exploitation_type": "multiple",
        "summary": "EU regulation prohibiting products made with forced labour from EU market (adopted 2024). Covers all products regardless of origin. Competent authorities can investigate based on risk indicators. Products seized at borders. Modeled on US Section 307 but broader enforcement mechanisms.",
        "source": "European Commission / European Parliament",
    },
    {
        "type": "case_study",
        "jurisdiction": "DE",
        "title": "German Supply Chain Due Diligence Act (LkSG, 2023)",
        "sector": "multiple",
        "exploitation_type": "multiple",
        "summary": "Lieferkettensorgfaltspflichtengesetz (LkSG) requires companies with 1,000+ employees to identify forced labour risks in direct suppliers. Risk analysis, prevention, remediation obligations. Fines up to 2% of annual global turnover. BAFA enforcement. Extended to indirect suppliers upon substantiated knowledge.",
        "source": "German Federal Government / BAFA",
    },
    {
        "type": "case_study",
        "jurisdiction": "FR",
        "title": "French Duty of Vigilance Law (Loi de Vigilance, 2017)",
        "sector": "multiple",
        "exploitation_type": "multiple",
        "summary": "First national mandatory human rights due diligence law. Applies to companies with 5,000+ employees in France or 10,000+ worldwide. Must publish vigilance plan covering subsidiaries and supply chain. Civil liability for failures. TotalEnergies, EDF, Casino sued under this law.",
        "source": "French National Assembly / Business & Human Rights Resource Centre",
    },
    {
        "type": "case_study",
        "jurisdiction": "US",
        "title": "US Uyghur Forced Labor Prevention Act (UFLPA, 2021)",
        "sector": "multiple",
        "exploitation_type": "state_imposed",
        "summary": "Creates rebuttable presumption that goods from Xinjiang Uyghur Autonomous Region (XUAR) are made with forced labour. Importers must prove otherwise with clear and convincing evidence. Blocked USD 2B+ in goods in first 2 years. Impacts cotton, polysilicon, tomatoes, PVC.",
        "source": "US Congress / DHS Forced Labor Enforcement Task Force",
    },
    # ── Sector-Specific Supply Chain Cases ────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "TH",
        "title": "Thai Seafood Supply Chain — Shrimp and Fish Processing",
        "sector": "fishing",
        "exploitation_type": "multiple",
        "corridor": "MM-TH",
        "summary": "Thai seafood industry supplies global brands (Walmart, Costco, major pet food companies). Myanmar and Cambodian workers in pre-processing (peeling sheds). 16-hour shifts, locked facilities, wage withholding. AP investigation (2015) freed 2,000 slaves from Indonesian island. EU IUU yellow card (2015-2019) forced partial reforms.",
        "source": "Associated Press / Environmental Justice Foundation / Guardian",
    },
    {
        "type": "case_study",
        "jurisdiction": "CI",
        "title": "West African Cocoa Supply Chain — Child and Forced Labour",
        "sector": "agriculture",
        "exploitation_type": "child_labour",
        "summary": "1.56M children in hazardous cocoa farming in Cote d'Ivoire and Ghana (NORC 2020). Children trafficked from Burkina Faso and Mali. Harkin-Engel Protocol (2001) voluntary commitments repeatedly missed. Industry pledged to end worst forms by 2005, then 2010, then 2020. Nestle, Mars, Hershey face ongoing litigation.",
        "source": "NORC / US DOL / International Cocoa Initiative",
    },
    {
        "type": "case_study",
        "jurisdiction": "BD",
        "title": "Bangladesh Garment Factory Supply Chains",
        "sector": "garment",
        "exploitation_type": "excessive_overtime",
        "summary": "4M+ workers in Bangladesh RMG sector, 80% women. Sub-contracting to unregistered factories obscures forced labour. Rana Plaza collapse (2013, 1,134 deaths) led to Bangladesh Accord. Workers earn USD 95/month minimum. Forced overtime during peak orders. Union organizers face violence and termination.",
        "source": "Bangladesh Accord / Clean Clothes Campaign / ILO",
    },
    {
        "type": "case_study",
        "jurisdiction": "CN",
        "title": "Xinjiang Cotton and Polysilicon Supply Chains",
        "sector": "manufacturing",
        "exploitation_type": "state_imposed",
        "summary": "State-sponsored forced labour of Uyghurs in cotton picking (20% of world supply), polysilicon production (45% of global supply for solar panels), and tomato processing. 'Labour transfer' programs move workers to factories in eastern China. Affects major electronics, fashion, and solar brands globally.",
        "source": "Australian Strategic Policy Institute / Sheffield Hallam University",
    },
    {
        "type": "case_study",
        "jurisdiction": "BR",
        "title": "Brazil Coffee and Sugar — Dirty List System",
        "sector": "agriculture",
        "exploitation_type": "debt_bondage",
        "summary": "Brazil's 'Lista Suja' (Dirty List) publicly names employers caught using forced labour. 53,000+ workers rescued since 1995. Coffee, sugar, cattle ranching, charcoal are key sectors. Workers recruited from northeast, transported to remote farms. Debt bondage through overpriced food/transport. Fines and debarment from government contracts.",
        "source": "Brazilian Ministry of Labour / Repórter Brasil",
    },
    # ── Audit and Certification Failures ─────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Social Audit Failures in Detecting Forced Labour",
        "sector": "multiple",
        "exploitation_type": "multiple",
        "summary": "Social audits (SA8000, SMETA, BSCI) routinely fail to detect forced labour. Announced audits allow preparation. Workers coached on responses. Auditors spend 1-2 days per factory. Sub-contracting hidden. Multiple certifications did not prevent forced labour at Top Glove, FGV, Thai Union. MSI Integrity (2020): no evidence MSIs improve human rights.",
        "source": "MSI Integrity / Clean Clothes Campaign / NYU Stern BHR",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Tier 2/3 Supplier Opacity in Global Supply Chains",
        "sector": "multiple",
        "exploitation_type": "multiple",
        "summary": "Most forced labour occurs at Tier 2-3+ suppliers (raw material extraction, component manufacturing). Brands have visibility into Tier 1 (assembly) but not deeper. Sub-contracting chains of 5-7 levels common in garments, electronics. KnowTheChain benchmarks show average score 26/100 for forced labour due diligence.",
        "source": "KnowTheChain / Verité / Business & Human Rights Resource Centre",
    },
    {
        "type": "case_study",
        "jurisdiction": "MY",
        "title": "Malaysian Electronics Sector — Forced Labour in Global Supply Chains",
        "sector": "manufacturing",
        "exploitation_type": "debt_bondage",
        "summary": "Malaysia produces 7% of global semiconductors and 13% of IC packaging/testing. Migrant workers from Nepal, Bangladesh, Myanmar pay USD 2,000-10,000 recruitment fees. Passport confiscation standard practice. US CBP WROs against multiple companies. Samsung, Apple, Intel supplier audits find persistent violations.",
        "source": "Verité / Electronics Watch / US DOL",
    },
    {
        "type": "case_study",
        "jurisdiction": "IT",
        "title": "Italian Agricultural Supply Chains — Caporalato System",
        "sector": "agriculture",
        "exploitation_type": "debt_bondage",
        "summary": "Caporalato (gangmaster) system exploits African and Eastern European migrants in Italian tomato, fruit, and olive harvesting. Workers paid EUR 20-30/day for 12-14 hour shifts. Housed in informal camps (ghettos). Transport and food deducted. Anti-caporalato law (2016) criminalized exploitation but enforcement limited.",
        "source": "Ferrara / Oxfam / FLAI-CGIL",
    },
    {
        "type": "case_study",
        "jurisdiction": "UK",
        "title": "UK Modern Slavery Act Section 54 — Reporting Gaps",
        "sector": "multiple",
        "exploitation_type": "multiple",
        "summary": "UK MSA s.54 requires companies with turnover GBP 36M+ to publish annual modern slavery statements. Analysis shows: 40% of in-scope companies non-compliant, most statements are boilerplate, few report actual risks found, none have been prosecuted for non-compliance. Government review (2019) recommended mandatory reporting areas.",
        "source": "Business & Human Rights Resource Centre / UK Home Office",
    },
    {
        "type": "case_study",
        "jurisdiction": "AU",
        "title": "Australia Modern Slavery Act — Reporting and Remediation",
        "sector": "multiple",
        "exploitation_type": "multiple",
        "summary": "Australian MSA (2018) requires entities with AUD 100M+ annual consolidated revenue to report on modern slavery risks. 7,000+ entities in scope. First reports (2020-2021) showed limited engagement with deep supply chain tiers. Independent review (2023) recommended strengthening enforcement and penalties.",
        "source": "Australian Border Force / Walk Free / ACSI",
    },
    # ── Emerging Supply Chain Issues ──────────────────────────────────
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Cobalt Mining Supply Chain — DRC to Global Electronics",
        "sector": "mining",
        "exploitation_type": "child_labour",
        "summary": "70% of global cobalt from DRC. 40,000 children in artisanal mining. Cobalt enters supply chains of Apple, Samsung, Tesla via intermediaries. Tunnel collapses, toxic exposure. RMI Responsible Minerals Initiative created but covers minority of supply. DRC Entreprise Générale du Cobalt (EGC) monopoly since 2020.",
        "source": "Amnesty International / Siddharth Kara / RMI",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Solar Panel Supply Chain — Polysilicon and Forced Labour",
        "sector": "manufacturing",
        "exploitation_type": "state_imposed",
        "summary": "45% of global polysilicon from Xinjiang, China. Uyghur forced labour in quartz mining, polysilicon refining, and wafer production. US UFLPA blocks imports. Solar industry attempting supply chain diversification but dependency remains. Traceability challenging due to blending and re-export through third countries.",
        "source": "Sheffield Hallam University / Solar Energy Industries Association",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Fast Fashion and Ultra-Fast Fashion Supply Chain Exploitation",
        "sector": "garment",
        "exploitation_type": "excessive_overtime",
        "summary": "Ultra-fast fashion (Shein, Temu) compresses production cycles to 3-7 days, pushing forced overtime onto garment workers. Shein suppliers work 18-hour shifts, earn 3 cents per garment. 6,000+ new styles daily requires sub-contracting to unregistered workshops. No social auditing of most suppliers.",
        "source": "Channel 4 Dispatches / Public Eye / Clean Clothes Campaign",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "EU Corporate Sustainability Due Diligence Directive (CSDDD, 2024)",
        "sector": "multiple",
        "exploitation_type": "multiple",
        "summary": "EU CSDDD requires large companies to identify, prevent, and mitigate adverse human rights impacts (including forced labour) throughout value chains. Applies to EU companies with 1,000+ employees and EUR 450M+ turnover, and non-EU companies with EUR 450M+ EU turnover. Civil liability provisions. Member states must transpose by 2026.",
        "source": "European Commission / European Parliament",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "ILO-IOE-ITUC Tripartite Declaration on Multinational Enterprises",
        "sector": "multiple",
        "exploitation_type": "multiple",
        "summary": "ILO MNE Declaration (revised 2017) provides guidance to multinational enterprises on labour practices including forced labour elimination. Voluntary. Supplements UN Guiding Principles on Business and Human Rights (UNGPs, 2011). National Contact Points under OECD Guidelines handle complaints. Limited enforcement mechanism.",
        "source": "ILO / OECD / OHCHR",
    },
]
