"""Pre-departure training programs, worker education, and rights awareness materials."""

TRAINING_MATERIAL_FACTS: list[dict] = [
    {
        "type": "training_material",
        "jurisdiction": "PH",
        "title": "Philippines PDOS — Pre-Departure Orientation Seminar",
        "organization": "DMW (formerly OWWA/POEA)",
        "summary": "Mandatory 1-day seminar for all departing OFWs. Covers: destination country laws, employment contract terms, cultural orientation, health and safety, financial literacy, complaint mechanisms, emergency contacts (POLO/OWWA hotlines). Country-specific modules for top destinations (SA, AE, HK, SG, QA, KW). Annual attendance: 1M+ workers. Criticism: too late in process, information overload in single day.",
        "source": "DMW / OWWA",
    },
    {
        "type": "training_material",
        "jurisdiction": "BD",
        "title": "Bangladesh BMET Pre-Departure Briefing",
        "organization": "Bureau of Manpower, Employment and Training",
        "summary": "BMET operates 70 Technical Training Centres (TTCs) providing: skills training (construction, welding, electronics), language basics, pre-departure orientation. Duration: 2-30 days depending on program. Briefing covers: contract terms, destination laws, complaint mechanisms, emergency contacts. Reach: 400,000+ workers annually. Gap: TTCs concentrated in Dhaka; rural workers have limited access.",
        "source": "BMET / ILO Dhaka",
    },
    {
        "type": "training_material",
        "jurisdiction": "NP",
        "title": "Nepal Foreign Employment Board Orientation Training",
        "organization": "Nepal Foreign Employment Board",
        "summary": "Mandatory 2-day orientation for Gulf-bound workers. Covers: destination laws, kafala system implications, complaint mechanisms, safe migration tips, financial management, health precautions. Conducted by licensed orientation agencies. Fee: NPR 500 (subsidized). Annual reach: 300,000+ workers. ILO supports curriculum development. Gap: quality varies by provider, workers sometimes attend just to get certificate.",
        "source": "Nepal FEB / ILO Kathmandu",
    },
    {
        "type": "training_material",
        "jurisdiction": "ID",
        "title": "Indonesia BNP2MI Pre-Departure Training Requirements",
        "organization": "BNP2MI",
        "summary": "Indonesian migrant workers must complete: skills training (30-200 hours depending on destination), language training (minimum 200 hours for Japan/Korea), cultural orientation, pre-departure briefing. Training centres in Jakarta, Surabaya, Batam, Bekasi. Criticism: some centres used as holding facilities, excessive fees charged, quality inconsistent. BNP2MI reform since 2020 aims to standardize.",
        "source": "BNP2MI / HOME Singapore",
    },
    {
        "type": "training_material",
        "jurisdiction": "international",
        "title": "ILO Fair Recruitment Initiative Training Materials",
        "organization": "ILO",
        "summary": "ILO FRI provides: 'General Principles and Operational Guidelines for Fair Recruitment' (2019), training modules for recruitment agencies, worker rights awareness materials in 15+ languages, 'Know Before You Go' campaign materials for origin countries, employer guidance on ethical recruitment. Materials freely available online. Used by 50+ countries in pre-departure programs.",
        "source": "ILO Fair Recruitment Initiative",
    },
    {
        "type": "training_material",
        "jurisdiction": "JP",
        "title": "Japan TITP Pre-Departure Japanese Language Training",
        "organization": "JITCO / Sending Organizations",
        "summary": "TITP trainees must pass Japanese Language Proficiency Test N5 (basic) before departure. 3-6 months language training in origin country (VN, ID, PH, CN, MM). Training fee: often USD 2,000-5,000 (added to worker's debt). Quality varies by sending organization. Post-arrival: 1-2 months Japanese training at supervising organization. SSW requires N4 level (higher). Korean EPS requires TOPIK Level 2.",
        "source": "JITCO / OTIT / Sending organizations",
    },
    {
        "type": "training_material",
        "jurisdiction": "KR",
        "title": "South Korea EPS — Korean Language and Culture Training",
        "organization": "Korea HRD Service",
        "summary": "EPS requires: TOPIK (Test of Proficiency in Korean) Level 2 minimum, pre-departure training (20 hours in origin country), post-arrival training (20 hours at HRD centre). Government-managed training (no private broker involvement). Training cost included in total recruitment fee (USD 900-1,000). Curriculum: Korean language, labour law, workplace safety, cultural orientation. Model for other programs.",
        "source": "Korea HRD Service / ILO",
    },
    {
        "type": "training_material",
        "jurisdiction": "HK",
        "title": "Hong Kong FDH Rights Awareness — NGO Materials",
        "organization": "Mission for Migrant Workers / MFMW",
        "summary": "Key NGOs provide rights awareness: Mission for Migrant Workers (MFMW) — know your rights booklets in Filipino, Indonesian, Thai; Bethune House shelter + legal clinic; PathFinders (for pregnant/parenting FDHs); ATKI-HK (Indonesian worker association). Materials cover: Standard Employment Contract terms, rest day rights, MAW amount, complaint procedures, Labour Tribunal process. Distributed in churches and community centres on Sundays.",
        "source": "MFMW / Bethune House / PathFinders / ATKI-HK",
    },
    {
        "type": "training_material",
        "jurisdiction": "SG",
        "title": "Singapore Settling-In Programme for FDWs",
        "organization": "Singapore MOM",
        "summary": "Mandatory 1-day Settling-In Programme (SIP) for first-time FDWs within first 3 days of arrival. Covers: Singapore laws, employment terms, safety at home, stress management, MOM hotline. Cost: SGD 75 (paid by employer). Conducted by accredited centres. Criticism: conducted in English (many FDWs have limited English), information overload, no follow-up. Employers also required to attend employer orientation programme (since 2017).",
        "source": "Singapore MOM",
    },
    {
        "type": "training_material",
        "jurisdiction": "international",
        "title": "IOM MigApp — Mobile Application for Migrant Workers",
        "organization": "IOM",
        "summary": "IOM MigApp: free mobile app providing: country-specific migration information, know-your-rights content, embassy/consulate locator, complaint mechanism contacts, counter-trafficking hotlines, travel safety tips, COVID-19 information. Available in 10+ languages. 100,000+ downloads. Limitations: requires smartphone and data, some workers have phones confiscated by employers, app not widely known among at-risk populations.",
        "source": "IOM",
    },
    {
        "type": "training_material",
        "jurisdiction": "international",
        "title": "Financial Literacy Programs for Migrant Workers",
        "organization": "ILO / IOM / World Bank",
        "summary": "Pre-departure financial literacy: remittance sending options (formal vs informal channels), savings strategies, investment basics, loan management, avoiding predatory lenders. Programs by: ILO (integrated into PDOS), World Bank (Greenback 2.0 project), Remittance Community Task Force. Gap: most workers receive financial training too late (after debt incurred) and content doesn't address recruitment fee negotiation.",
        "source": "ILO / World Bank / IOM",
    },
    {
        "type": "training_material",
        "jurisdiction": "international",
        "title": "Workplace Safety Training for Construction Migrants",
        "organization": "BWI / ILO",
        "summary": "Construction sector safety training: heat stress prevention (critical in Gulf), fall protection, equipment operation, chemical handling, first aid. Training should be in workers' language but often conducted in Arabic or English only. BWI (Building and Wood Workers' International) provides translated safety materials. Qatar: mandatory safety induction since 2021. UAE: new Construction Workers Welfare Standard. Deaths from heat exposure remain underreported.",
        "source": "BWI / ILO / Qatar Supreme Committee",
    },
    {
        "type": "training_material",
        "jurisdiction": "PH",
        "title": "Philippines Comprehensive Pre-Departure Education Program (CPDEP)",
        "organization": "DMW / TESDA",
        "summary": "For domestic workers: 216-hour Comprehensive Pre-Departure Education Program covering: language (Arabic/English), culture, cooking, housekeeping, elderly/child care, first aid, stress management, financial literacy, workers' rights. TESDA-certified. Cost: PHP 7,000-15,000 (often added to worker's debt). Required for first-time HSW deployers. Criticism: training centres vary in quality; some are holding facilities with poor conditions.",
        "source": "DMW / TESDA",
    },
    {
        "type": "training_material",
        "jurisdiction": "international",
        "title": "NGO Worker Rights Education Networks in Asia",
        "organization": "Migrant Forum in Asia / CARAM Asia",
        "summary": "Key regional NGO networks providing worker education: Migrant Forum in Asia (MFA, 200+ member organizations across Asia), CARAM Asia (health and migration), GAATW (Global Alliance Against Traffic in Women), IDWF (International Domestic Workers Federation). Provide: rights awareness workshops, paralegal training for worker leaders, research-based advocacy, community organizing support. Funded by donor governments and foundations.",
        "source": "MFA / CARAM Asia / GAATW / IDWF",
    },
    {
        "type": "training_material",
        "jurisdiction": "international",
        "title": "IRIS Ethical Recruitment Training for Agencies",
        "organization": "IOM IRIS",
        "summary": "IOM International Recruitment Integrity System (IRIS): voluntary certification standard for ethical recruitment agencies. Training covers: zero-fee principle, transparent contracts, worker consent, grievance mechanisms, monitoring compliance. 60+ agencies engaged. Certified agencies listed on IRIS website. Limitation: voluntary, covers minority of recruitment market, no enforcement mechanism for non-certified agencies.",
        "source": "IOM IRIS",
    },
    {
        "type": "training_material",
        "jurisdiction": "international",
        "title": "Dhaka Principles for Migration with Dignity",
        "organization": "Institute for Human Rights and Business (IHRB)",
        "summary": "10 principles for human rights-compliant recruitment: (1) no fees to workers, (2) clear contracts, (3) informed consent, (4) freedom of movement, (5) fair working conditions, (6) access to remedy, (7) safe accommodation, (8) freedom to change employment, (9) safe return, (10) access to justice. Endorsed by 40+ companies and organizations. Used as benchmarking tool by KnowTheChain and corporate due diligence programs.",
        "source": "IHRB / Leadership Group for Responsible Recruitment",
    },
]
