"""Wage protection systems, wage theft patterns, and minimum wage data."""

WAGE_PROTECTION_FACTS: list[dict] = [
    # ── Electronic Wage Protection Systems ───────────────────────────
    {
        "type": "regulation_change",
        "jurisdiction": "SA",
        "title": "Saudi Arabia Wage Protection System (WPS)",
        "year": 2013,
        "summary": "Mandatory electronic salary transfer for all private sector employers. Wages must be deposited into worker's bank account within 7 days of due date. MoHR monitors compliance. Non-compliant employers face recruitment ban. Excludes domestic workers (added partially in 2021 via Musaned). 85% compliance rate reported but complaints persist about delayed or partial payments.",
        "source": "Saudi Ministry of Human Resources / ILO",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "QA",
        "title": "Qatar Wage Protection System (WPS) and Minimum Wage",
        "year": 2021,
        "summary": "Mandatory non-discriminatory minimum wage of QAR 1,000/month + QAR 500 food + QAR 300 housing (if not provided). Total QAR 1,800 (USD 494). WPS requires electronic transfer. Labour Dispute Resolution Committees (LDRC) handle claims. 2,700+ cases filed in first year. Recovery rate ~60%. Includes domestic workers since 2017 (Law 15/2017).",
        "source": "Qatar Ministry of Labour / ILO Programme Office in Qatar",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "AE",
        "title": "UAE Wage Protection System",
        "year": 2009,
        "summary": "UAE WPS launched 2009, expanded progressively. All wages must be paid electronically through authorized banks/exchange houses within 15 days. Employers failing to pay for 60+ days face recruitment ban. 2023 update: real-time monitoring, automatic alerts. Domestic workers covered under separate standard contract (2017). Coverage: 5M+ workers.",
        "source": "UAE Ministry of Human Resources and Emiratisation",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "BH",
        "title": "Bahrain Labour Market Regulatory Authority (LMRA) Wage Protection",
        "year": 2019,
        "summary": "Bahrain WPS mandates electronic salary payment. LMRA flexi-permit system (2017) allows workers to sponsor themselves (BHD 300/year), reducing kafala dependency. Minimum wage: none for private sector (BHD 300 for Bahraini nationals only). Migrant workers negotiate individually. Complaints handled by MoL conciliation.",
        "source": "Bahrain LMRA",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "KW",
        "title": "Kuwait Electronic Wage Transfer Requirement",
        "year": 2018,
        "summary": "Kuwait mandates electronic salary transfer for companies with 50+ employees. KWD 75/month minimum for domestic workers (Domestic Workers Law 68/2015). Non-payment complaints to Public Authority of Manpower. Processing time: 3-6 months. Workers must remain in country during dispute resolution, creating vulnerability. Domestic workers often paid in cash despite regulations.",
        "source": "Kuwait Public Authority of Manpower",
    },
    # ── Minimum Wage Data ────────────────────────────────────────────
    {
        "type": "statistic",
        "jurisdiction": "HK",
        "title": "Hong Kong Minimum Allowable Wage for Foreign Domestic Helpers",
        "metric": "minimum_wage",
        "value": "HKD 4,870/month",
        "year": 2023,
        "details": "Statutory minimum for FDHs (separate from general minimum wage HKD 40/hour). Employers must also provide food (HKD 1,236/month allowance if not provided) and accommodation. Actual enforcement: Labour Tribunal handles claims. Common violations: requiring work during rest day without pay, excessive hours (14-18 hours documented).",
        "source": "Hong Kong Labour Department",
    },
    {
        "type": "statistic",
        "jurisdiction": "SG",
        "title": "Singapore — No Minimum Wage for Foreign Domestic Workers",
        "metric": "minimum_wage",
        "value": "None (market rate SGD 450-800/month)",
        "year": 2023,
        "details": "Singapore has no statutory minimum wage for foreign domestic workers. Market rate: SGD 450-800/month depending on nationality and experience. Indonesian workers typically earn less than Filipino workers. MOM advisory: SGD 600/month. After agency fee deductions (8 months salary), effective pay for first year can be SGD 0-200/month.",
        "source": "Singapore Ministry of Manpower / HOME Singapore",
    },
    {
        "type": "statistic",
        "jurisdiction": "SA",
        "title": "Saudi Arabia Domestic Worker Wages",
        "metric": "minimum_wage",
        "value": "No statutory minimum (SAR 1,000-1,500/month typical)",
        "year": 2023,
        "details": "No minimum wage for domestic workers (excluded from Labour Law). Musaned platform suggests SAR 1,000-2,000/month depending on nationality. Filipino workers: SAR 1,500-2,000 (bilateral agreement). Ethiopian workers: SAR 800-1,200. Deductions for food/accommodation common despite being employer obligation.",
        "source": "Saudi Ministry of Human Resources / Musaned",
    },
    # ── Illegal Deductions Catalog ───────────────────────────────────
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Common Illegal Salary Deductions from Migrant Workers",
        "summary": "Documented illegal deductions: accommodation (USD 50-300/month), food (USD 30-150/month), uniforms/work clothes (USD 20-50), tools/equipment (USD 50-200), medical exams (USD 50-200/year), visa renewal (USD 100-500), insurance (USD 20-100/month), transport to worksite (USD 30-100/month), 'security deposit' (USD 200-1,000 one-time). Total deductions can exceed 50% of gross salary.",
        "source": "ILO / Verité / BWI",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Payment in Kind Abuse as Wage Theft",
        "summary": "Employers substitute cash wages with 'payment in kind': accommodation, food, clothing counted against salary. Value inflated: employer-provided room valued at USD 200/month (market rate USD 50). Food valued at USD 150/month (actual cost USD 30). Creates illusion of fair pay while actual cash received is minimal. Particularly common in domestic work, agriculture, and fishing sectors.",
        "source": "ILO / Anti-Slavery International",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "End-of-Service Benefit Denial Patterns",
        "summary": "Workers entitled to end-of-service gratuity (typically 15-30 days salary per year of service) frequently denied: employer claims worker 'absconded' (forfeits entitlements), employer falsifies termination reason, employer delays final payment until worker's visa expires and must leave, employer offers 'take it or leave' reduced settlement. Gulf states: 80%+ of labour complaints involve end-of-service disputes.",
        "source": "ILO / Migrant-Rights.org",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Global Wage Theft from Migrant Workers — Annual Estimate",
        "metric": "wage_theft_amount",
        "value": "USD 8B+ annually",
        "year": 2022,
        "details": "ILO estimates USD 8B+ in wage theft from migrant workers globally. Includes: non-payment of overtime (most common), salary withholding, illegal deductions, below-minimum-wage payment, end-of-service denial. Recovery rate: <10% of stolen wages recovered through legal channels. Most workers abandon claims due to inability to remain in country during dispute.",
        "source": "ILO / World Bank",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Tip Confiscation in Hospitality Sector",
        "summary": "Migrant workers in hotels, restaurants, and tourism forced to surrender tips to employer or supervisor. Tips counted as 'income' to justify below-minimum base pay. Service charge added to bills but not distributed to workers. Documented in Gulf hotels, Southeast Asian resorts, European restaurants. Workers who object face termination or transfer to less desirable position.",
        "source": "ILO / UNITE HERE / Fair Tips campaign",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Forced Overtime Without Compensation",
        "summary": "Migrant workers routinely forced to work overtime (60-80+ hours/week) without legal overtime premium. Methods: clock manipulation (record 8 hours for 12-hour shift), classify overtime as 'voluntary,' threaten contract termination, require 'voluntary' weekend work. Gulf construction: 10-14 hour shifts standard in summer despite heat work bans. Domestic workers: 'on call' 24 hours, no overtime concept.",
        "source": "ILO / BWI / Amnesty International",
    },
    {
        "type": "statistic",
        "jurisdiction": "QA",
        "title": "Qatar LDRC Wage Claim Statistics",
        "metric": "claims_filed",
        "value": "35,000+ (2022-2023)",
        "year": 2023,
        "details": "Qatar Labour Dispute Resolution Committees received 35,000+ cases in 2022-2023. Average claim: QAR 15,000 (USD 4,100). Resolution time: 3-6 weeks (improved from 6+ months). Recovery rate: ~60%. Employer non-appearance rate: 30%. Workers must remain in Qatar during proceedings, losing income. ILO Worker Support and Insurance Fund covers unpaid wages for workers whose employers cannot be located.",
        "source": "Qatar Ministry of Labour / ILO",
    },
    {
        "type": "regulation_change",
        "jurisdiction": "QA",
        "title": "Qatar Workers' Support and Insurance Fund",
        "year": 2022,
        "summary": "Fund established to guarantee payment of wages and end-of-service benefits when employers fail to pay or cannot be located. Funded by employer contributions. Covers all workers in Qatar regardless of nationality. Paid QAR 350M+ (USD 96M) in first 2 years. Model for other Gulf states. Workers apply through LDRC process.",
        "source": "Qatar Ministry of Labour / ILO",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Currency Manipulation and Exchange Rate Exploitation",
        "summary": "Employers exploit currency exchange to underpay workers: pay in local currency at disadvantageous rate (vs. contract currency), force use of employer-designated exchange service with high commissions, delay payments during currency depreciation. Documented in Gulf states (SAR/QAR paid instead of contractual USD), Malaysia (MYR conversion), Thailand (THB). Workers lose 5-15% of earnings to exchange manipulation.",
        "source": "ILO / Migrant Forum in Asia",
    },
    {
        "type": "advisory",
        "jurisdiction": "international",
        "title": "Salary Withholding as Retention Tool",
        "summary": "Employers withhold 1-6 months salary claiming 'safekeeping' or 'guarantee against early departure.' Worker cannot access own earnings. If worker leaves, withheld salary forfeited. Creates financial barrier to termination. Documented across Gulf domestic work, Malaysian manufacturing, Thai fishing. Some employers hold entire first year salary until contract renewal.",
        "source": "ILO / Migrant-Rights.org / Amnesty International",
    },
    {
        "type": "case_study",
        "jurisdiction": "international",
        "title": "Construction Worker Wage Theft in Mega-Projects",
        "sector": "construction",
        "exploitation_type": "withholding_wages",
        "summary": "Large infrastructure projects (stadiums, cities, airports) use sub-contracting chains of 3-7 levels. Payment flows top-down; delays cascade. Workers at bottom receive wages 2-6 months late. Sub-contractors sometimes disappear with wages. Workers have no contractual relationship with project owner. Documented at: FIFA 2022 Qatar, Expo 2020 Dubai, NEOM Saudi, Saadiyat Island Abu Dhabi.",
        "source": "Amnesty International / BWI / ITUC",
    },
    {
        "type": "statistic",
        "jurisdiction": "international",
        "title": "Wage Theft Recovery Rates by Destination",
        "metric": "recovery_rate",
        "value": "varies 5-60%",
        "year": 2023,
        "details": "Estimated wage theft recovery: Qatar 60% (highest, LDRC + insurance fund), HK 40-50% (Labour Tribunal relatively accessible), SG 30-40% (MOM mediation), SA 15-25% (courts slow, worker must remain), AE 20-30%, MY 10-20%, TH 5-15% (informal sector, no documentation). Workers who return home before resolution recover <5%.",
        "source": "ILO / Corridor-specific research",
    },
]
