"""
Adapter factory — generate adapter code for wrapping external libraries.

Produces BaseMutator subclasses that wrap functions from external packages,
with proper try/except guards for optional dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from string import Template


@dataclass
class AdapterSpec:
    """Specification for an external library adapter."""

    package: str  # pip package name
    import_name: str  # Python import name
    category: str  # Mutator category to place adapters in
    functions: list[dict[str, str]] = field(default_factory=list)
    # Each: {"name": "mutator_name", "class": "ClassName", "func": "lib.func_name",
    #         "description": "...", "technique": "..."}


_ADAPTER_TEMPLATE = '''\
"""
${category_title} — Adapter for ${package}

Wraps ${package} functions as BaseMutator subclasses.
Requires: pip install ${package}

Auto-generated by AdapterFactory.
"""

from __future__ import annotations

from src.prompt_injection import BaseMutator, register_mutator

try:
    import ${import_name}
    _HAS_LIB = True
except ImportError:
    _HAS_LIB = False


${mutator_classes}
'''

_MUTATOR_TEMPLATE = '''\
@register_mutator
class ${class_name}(BaseMutator):
    """${description}

    Requires: pip install ${package}
    """

    NAME = "${name}"
    CATEGORY = "${category}"
    DESCRIPTION = "${description}"

    def _apply(self, prompt: str, **kwargs) -> list[tuple[str, str, dict]]:
        if not _HAS_LIB:
            # Graceful fallback when library not installed
            return [
                (
                    prompt,
                    "${name} (library not installed)",
                    {"technique": "${technique}", "variant": "fallback", "error": "${package} not installed"},
                ),
            ]

        # TODO: Replace with actual library call
        # result = ${import_name}.${func_call}(prompt)
        result = prompt  # Placeholder

        return [
            (
                result,
                "${description}",
                {"technique": "${technique}", "variant": "standard"},
            ),
        ]

'''


class AdapterFactory:
    """Generate adapter modules that wrap external libraries.

    Usage:
        factory = AdapterFactory()

        spec = AdapterSpec(
            package="textattack",
            import_name="textattack",
            category="adversarial_nlp",
            functions=[
                {
                    "name": "textfooler_attack",
                    "class": "TextFoolerMutator",
                    "func": "textattack.attack_recipes.TextFoolerJin2019",
                    "description": "TextFooler synonym substitution attack",
                    "technique": "textfooler",
                },
            ],
        )

        code = factory.generate(spec)
        factory.write(spec, output_dir="src/prompt_injection/")
    """

    def generate(self, spec: AdapterSpec) -> str:
        """Generate a complete adapter module."""
        mutator_classes = []
        for func in spec.functions:
            cls_code = Template(_MUTATOR_TEMPLATE).safe_substitute(
                class_name=func["class"],
                name=func["name"],
                category=spec.category,
                description=func.get("description", func["name"]),
                package=spec.package,
                import_name=spec.import_name,
                technique=func.get("technique", func["name"]),
                func_call=func.get("func", "transform"),
            )
            mutator_classes.append(cls_code)

        return Template(_ADAPTER_TEMPLATE).safe_substitute(
            category_title=spec.category.replace("_", " ").title(),
            package=spec.package,
            import_name=spec.import_name,
            mutator_classes="\n".join(mutator_classes),
        )

    def write(
        self,
        spec: AdapterSpec,
        output_dir: str = "src/prompt_injection",
    ) -> str:
        """Write the adapter module to disk."""
        from pathlib import Path

        filename = f"{spec.category}.py"
        output = Path(output_dir) / filename
        code = self.generate(spec)
        output.write_text(code, encoding="utf-8")
        return str(output)

    def preview(self, spec: AdapterSpec) -> dict[str, str]:
        """Preview without writing."""
        code = self.generate(spec)
        return {
            "filename": f"{spec.category}.py",
            "package": spec.package,
            "mutator_count": str(len(spec.functions)),
            "code_preview": code[:800] + "..." if len(code) > 800 else code,
        }
